// -----------------------------------------------------------------------------
// Auto-Generated by:        __   _ __      _  __
//                          / /  (_) /____ | |/_/
//                         / /__/ / __/ -_)>  <
//                        /____/_/\__/\__/_/|_|
//                     Build your hardware, easily!
//                   https://github.com/enjoy-digital/litex
//
// Filename   : xing_top.v
// Top        : Unknown
// Device     : Unknown
// Hierarchy  : disabled
// LiteX sha1 : a1e1c36
// Date       : 2026-10-10 14:05:48
//------------------------------------------------------------------------------

`timescale 1ns / 1ps

//------------------------------------------------------------------------------
// Module
//------------------------------------------------------------------------------

module xing_top (
    input  wire          ar_first,
    output wire          ar_first_1,
    output wire          ar_last,
    input  wire          ar_last_1,
    output wire   [31:0] ar_payload_addr,
    input  wire   [31:0] ar_payload_addr_1,
    output wire    [2:0] ar_payload_prot,
    input  wire    [2:0] ar_payload_prot_1,
    output wire          ar_ready,
    input  wire          ar_ready_1,
    input  wire          ar_valid,
    output wire          ar_valid_1,
    input  wire          aw_first,
    output wire          aw_first_1,
    input  wire          aw_last,
    output wire          aw_last_1,
    input  wire   [31:0] aw_payload_addr,
    output wire   [31:0] aw_payload_addr_1,
    input  wire    [2:0] aw_payload_prot,
    output wire    [2:0] aw_payload_prot_1,
    output wire          aw_ready,
    input  wire          aw_ready_1,
    input  wire          aw_valid,
    output wire          aw_valid_1,
    output wire          b_first,
    input  wire          b_first_1,
    output wire          b_last,
    input  wire          b_last_1,
    output wire    [1:0] b_payload_resp,
    input  wire    [1:0] b_payload_resp_1,
    input  wire          b_ready,
    output wire          b_ready_1,
    output wire          b_valid,
    input  wire          b_valid_1,
    input  wire          macdp_clk,
    input  wire          macdp_rst,
    input  wire          macsys_clk,
    input  wire          macsys_rst,
    input  wire          milan_clk,
    input  wire          milan_rst,
    input  wire          r_first,
    output wire          r_first_1,
    input  wire          r_last,
    output wire          r_last_1,
    input  wire   [31:0] r_payload_data,
    output wire   [31:0] r_payload_data_1,
    input  wire    [1:0] r_payload_resp,
    output wire    [1:0] r_payload_resp_1,
    output wire          r_ready,
    input  wire          r_ready_1,
    input  wire          r_valid,
    output wire          r_valid_1,
    input  wire          sink_first,
    input  wire          sink_first_1,
    input  wire          sink_last,
    input  wire          sink_last_1,
    input  wire   [63:0] sink_payload_data,
    input  wire   [63:0] sink_payload_data_1,
    input  wire    [7:0] sink_payload_keep,
    input  wire    [7:0] sink_payload_keep_1,
    output wire          sink_ready,
    output wire          sink_ready_1,
    input  wire          sink_valid,
    input  wire          sink_valid_1,
    output wire          source_first,
    output wire          source_first_1,
    output wire          source_last,
    output wire          source_last_1,
    output wire   [63:0] source_payload_data,
    output wire   [63:0] source_payload_data_1,
    output wire    [7:0] source_payload_keep,
    output wire    [7:0] source_payload_keep_1,
    input  wire          source_ready,
    input  wire          source_ready_1,
    output wire          source_valid,
    output wire          source_valid_1,
    input  wire          sys_clk,
    input  wire          sys_rst,
    input  wire          w_first,
    output wire          w_first_1,
    input  wire          w_last,
    output wire          w_last_1,
    input  wire   [31:0] w_payload_data,
    output wire   [31:0] w_payload_data_1,
    input  wire    [3:0] w_payload_strb,
    output wire    [3:0] w_payload_strb_1,
    output wire          w_ready,
    input  wire          w_ready_1,
    input  wire          w_valid,
    output wire          w_valid_1
);


//------------------------------------------------------------------------------
// Hierarchy
//------------------------------------------------------------------------------


//------------------------------------------------------------------------------
// Signals
//------------------------------------------------------------------------------

wire    [3:0] array_read_memory0_adr;
wire   [71:0] array_read_memory0_dat_r;
wire    [3:0] array_read_memory1_adr;
wire    [1:0] array_read_memory1_dat_r;
wire    [3:0] array_read_memory2_adr;
wire   [71:0] array_read_memory2_dat_r;
wire    [3:0] array_read_memory3_adr;
wire    [1:0] array_read_memory3_dat_r;
wire    [3:0] array_write_memory0_adr;
wire   [71:0] array_write_memory0_dat_r;
wire   [71:0] array_write_memory0_dat_w;
wire          array_write_memory0_we;
wire    [3:0] array_write_memory1_adr;
wire    [1:0] array_write_memory1_dat_r;
wire    [1:0] array_write_memory1_dat_w;
wire          array_write_memory1_we;
wire    [3:0] array_write_memory2_adr;
wire   [71:0] array_write_memory2_dat_r;
wire   [71:0] array_write_memory2_dat_w;
wire          array_write_memory2_we;
wire    [3:0] array_write_memory3_adr;
wire    [1:0] array_write_memory3_dat_r;
wire    [1:0] array_write_memory3_dat_w;
wire          array_write_memory3_we;
reg     [4:0] multiregimpl00 = 5'd0;
reg     [4:0] multiregimpl01 = 5'd0;
reg     [4:0] multiregimpl10 = 5'd0;
reg     [2:0] multiregimpl100 = 3'd0;
reg     [2:0] multiregimpl101 = 3'd0;
reg     [4:0] multiregimpl11 = 5'd0;
reg     [2:0] multiregimpl110 = 3'd0;
reg     [2:0] multiregimpl111 = 3'd0;
reg     [2:0] multiregimpl120 = 3'd0;
reg     [2:0] multiregimpl121 = 3'd0;
reg     [2:0] multiregimpl130 = 3'd0;
reg     [2:0] multiregimpl131 = 3'd0;
reg     [4:0] multiregimpl20 = 5'd0;
reg     [4:0] multiregimpl21 = 5'd0;
reg     [4:0] multiregimpl30 = 5'd0;
reg     [4:0] multiregimpl31 = 5'd0;
reg     [2:0] multiregimpl40 = 3'd0;
reg     [2:0] multiregimpl41 = 3'd0;
reg     [2:0] multiregimpl50 = 3'd0;
reg     [2:0] multiregimpl51 = 3'd0;
reg     [2:0] multiregimpl60 = 3'd0;
reg     [2:0] multiregimpl61 = 3'd0;
reg     [2:0] multiregimpl70 = 3'd0;
reg     [2:0] multiregimpl71 = 3'd0;
reg     [2:0] multiregimpl80 = 3'd0;
reg     [2:0] multiregimpl81 = 3'd0;
reg     [2:0] multiregimpl90 = 3'd0;
reg     [2:0] multiregimpl91 = 3'd0;
wire   [73:0] rx_cdc_asyncfifo_din;
wire   [73:0] rx_cdc_asyncfifo_dout;
wire          rx_cdc_asyncfifo_re;
wire          rx_cdc_asyncfifo_readable;
wire          rx_cdc_asyncfifo_we;
wire          rx_cdc_asyncfifo_writable;
wire    [4:0] rx_cdc_consume_wdomain;
reg    [73:0] rx_cdc_dout = 74'd0;
wire          rx_cdc_fifo_in_first;
wire          rx_cdc_fifo_in_last;
wire   [63:0] rx_cdc_fifo_in_payload_data;
wire    [7:0] rx_cdc_fifo_in_payload_keep;
wire          rx_cdc_fifo_out_first;
wire          rx_cdc_fifo_out_last;
wire   [63:0] rx_cdc_fifo_out_payload_data;
wire    [7:0] rx_cdc_fifo_out_payload_keep;
wire          rx_cdc_graycounter0_ce;
reg     [4:0] rx_cdc_graycounter0_q = 5'd0;
reg     [4:0] rx_cdc_graycounter0_q_binary = 5'd0;
wire    [4:0] rx_cdc_graycounter0_q_next;
reg     [4:0] rx_cdc_graycounter0_q_next_binary = 5'd0;
wire          rx_cdc_graycounter1_ce;
reg     [4:0] rx_cdc_graycounter1_q = 5'd0;
reg     [4:0] rx_cdc_graycounter1_q_binary = 5'd0;
wire    [4:0] rx_cdc_graycounter1_q_next;
reg     [4:0] rx_cdc_graycounter1_q_next_binary = 5'd0;
wire    [4:0] rx_cdc_produce_rdomain;
wire    [3:0] rx_cdc_rdport_adr;
wire   [73:0] rx_cdc_rdport_dat_r;
wire          rx_cdc_re;
reg           rx_cdc_readable = 1'd0;
wire          rx_cdc_sink_first;
wire          rx_cdc_sink_last;
wire   [63:0] rx_cdc_sink_payload_data;
wire    [7:0] rx_cdc_sink_payload_keep;
wire          rx_cdc_sink_ready;
wire          rx_cdc_sink_valid;
wire          rx_cdc_source_first;
wire          rx_cdc_source_last;
wire   [63:0] rx_cdc_source_payload_data;
wire    [7:0] rx_cdc_source_payload_keep;
wire          rx_cdc_source_ready;
wire          rx_cdc_source_valid;
wire    [3:0] rx_cdc_wrport_adr;
wire   [73:0] rx_cdc_wrport_dat_w;
wire          rx_cdc_wrport_we;
wire   [36:0] slave_ar_cdc_cdc_asyncfifo_din;
wire   [36:0] slave_ar_cdc_cdc_asyncfifo_dout;
wire          slave_ar_cdc_cdc_asyncfifo_re;
wire          slave_ar_cdc_cdc_asyncfifo_readable;
wire          slave_ar_cdc_cdc_asyncfifo_we;
wire          slave_ar_cdc_cdc_asyncfifo_writable;
wire    [2:0] slave_ar_cdc_cdc_consume_wdomain;
wire          slave_ar_cdc_cdc_fifo_in_first;
wire          slave_ar_cdc_cdc_fifo_in_last;
wire   [31:0] slave_ar_cdc_cdc_fifo_in_payload_addr;
wire    [2:0] slave_ar_cdc_cdc_fifo_in_payload_prot;
wire          slave_ar_cdc_cdc_fifo_out_first;
wire          slave_ar_cdc_cdc_fifo_out_last;
wire   [31:0] slave_ar_cdc_cdc_fifo_out_payload_addr;
wire    [2:0] slave_ar_cdc_cdc_fifo_out_payload_prot;
wire          slave_ar_cdc_cdc_graycounter0_ce;
reg     [2:0] slave_ar_cdc_cdc_graycounter0_q = 3'd0;
reg     [2:0] slave_ar_cdc_cdc_graycounter0_q_binary = 3'd0;
wire    [2:0] slave_ar_cdc_cdc_graycounter0_q_next;
reg     [2:0] slave_ar_cdc_cdc_graycounter0_q_next_binary = 3'd0;
wire          slave_ar_cdc_cdc_graycounter1_ce;
reg     [2:0] slave_ar_cdc_cdc_graycounter1_q = 3'd0;
reg     [2:0] slave_ar_cdc_cdc_graycounter1_q_binary = 3'd0;
wire    [2:0] slave_ar_cdc_cdc_graycounter1_q_next;
reg     [2:0] slave_ar_cdc_cdc_graycounter1_q_next_binary = 3'd0;
wire    [2:0] slave_ar_cdc_cdc_produce_rdomain;
wire    [1:0] slave_ar_cdc_cdc_rdport_adr;
wire   [36:0] slave_ar_cdc_cdc_rdport_dat_r;
wire          slave_ar_cdc_cdc_sink_first;
wire          slave_ar_cdc_cdc_sink_last;
wire   [31:0] slave_ar_cdc_cdc_sink_payload_addr;
wire    [2:0] slave_ar_cdc_cdc_sink_payload_prot;
wire          slave_ar_cdc_cdc_sink_ready;
wire          slave_ar_cdc_cdc_sink_valid;
wire          slave_ar_cdc_cdc_source_first;
wire          slave_ar_cdc_cdc_source_last;
wire   [31:0] slave_ar_cdc_cdc_source_payload_addr;
wire    [2:0] slave_ar_cdc_cdc_source_payload_prot;
wire          slave_ar_cdc_cdc_source_ready;
wire          slave_ar_cdc_cdc_source_valid;
wire    [1:0] slave_ar_cdc_cdc_wrport_adr;
wire   [36:0] slave_ar_cdc_cdc_wrport_dat_r;
wire   [36:0] slave_ar_cdc_cdc_wrport_dat_w;
wire          slave_ar_cdc_cdc_wrport_we;
wire          slave_ar_cdc_sink_sink_first;
wire          slave_ar_cdc_sink_sink_last;
wire   [31:0] slave_ar_cdc_sink_sink_payload_addr;
wire    [2:0] slave_ar_cdc_sink_sink_payload_prot;
wire          slave_ar_cdc_sink_sink_ready;
wire          slave_ar_cdc_sink_sink_valid;
wire          slave_ar_cdc_source_source_first;
wire          slave_ar_cdc_source_source_last;
wire   [31:0] slave_ar_cdc_source_source_payload_addr;
wire    [2:0] slave_ar_cdc_source_source_payload_prot;
wire          slave_ar_cdc_source_source_ready;
wire          slave_ar_cdc_source_source_valid;
wire    [1:0] slave_array_read_memory0_adr;
wire   [35:0] slave_array_read_memory0_dat_r;
wire    [1:0] slave_array_read_memory1_adr;
wire    [1:0] slave_array_read_memory1_dat_r;
wire    [1:0] slave_array_read_memory2_adr;
wire   [33:0] slave_array_read_memory2_dat_r;
wire    [1:0] slave_array_read_memory3_adr;
wire    [1:0] slave_array_read_memory3_dat_r;
wire    [1:0] slave_array_write_memory0_adr;
wire   [35:0] slave_array_write_memory0_dat_r;
wire   [35:0] slave_array_write_memory0_dat_w;
wire          slave_array_write_memory0_we;
wire    [1:0] slave_array_write_memory1_adr;
wire    [1:0] slave_array_write_memory1_dat_r;
wire    [1:0] slave_array_write_memory1_dat_w;
wire          slave_array_write_memory1_we;
wire    [1:0] slave_array_write_memory2_adr;
wire   [33:0] slave_array_write_memory2_dat_r;
wire   [33:0] slave_array_write_memory2_dat_w;
wire          slave_array_write_memory2_we;
wire    [1:0] slave_array_write_memory3_adr;
wire    [1:0] slave_array_write_memory3_dat_r;
wire    [1:0] slave_array_write_memory3_dat_w;
wire          slave_array_write_memory3_we;
wire   [36:0] slave_aw_cdc_cdc_asyncfifo_din;
wire   [36:0] slave_aw_cdc_cdc_asyncfifo_dout;
wire          slave_aw_cdc_cdc_asyncfifo_re;
wire          slave_aw_cdc_cdc_asyncfifo_readable;
wire          slave_aw_cdc_cdc_asyncfifo_we;
wire          slave_aw_cdc_cdc_asyncfifo_writable;
wire    [2:0] slave_aw_cdc_cdc_consume_wdomain;
wire          slave_aw_cdc_cdc_fifo_in_first;
wire          slave_aw_cdc_cdc_fifo_in_last;
wire   [31:0] slave_aw_cdc_cdc_fifo_in_payload_addr;
wire    [2:0] slave_aw_cdc_cdc_fifo_in_payload_prot;
wire          slave_aw_cdc_cdc_fifo_out_first;
wire          slave_aw_cdc_cdc_fifo_out_last;
wire   [31:0] slave_aw_cdc_cdc_fifo_out_payload_addr;
wire    [2:0] slave_aw_cdc_cdc_fifo_out_payload_prot;
wire          slave_aw_cdc_cdc_graycounter0_ce;
reg     [2:0] slave_aw_cdc_cdc_graycounter0_q = 3'd0;
reg     [2:0] slave_aw_cdc_cdc_graycounter0_q_binary = 3'd0;
wire    [2:0] slave_aw_cdc_cdc_graycounter0_q_next;
reg     [2:0] slave_aw_cdc_cdc_graycounter0_q_next_binary = 3'd0;
wire          slave_aw_cdc_cdc_graycounter1_ce;
reg     [2:0] slave_aw_cdc_cdc_graycounter1_q = 3'd0;
reg     [2:0] slave_aw_cdc_cdc_graycounter1_q_binary = 3'd0;
wire    [2:0] slave_aw_cdc_cdc_graycounter1_q_next;
reg     [2:0] slave_aw_cdc_cdc_graycounter1_q_next_binary = 3'd0;
wire    [2:0] slave_aw_cdc_cdc_produce_rdomain;
wire    [1:0] slave_aw_cdc_cdc_rdport_adr;
wire   [36:0] slave_aw_cdc_cdc_rdport_dat_r;
wire          slave_aw_cdc_cdc_sink_first;
wire          slave_aw_cdc_cdc_sink_last;
wire   [31:0] slave_aw_cdc_cdc_sink_payload_addr;
wire    [2:0] slave_aw_cdc_cdc_sink_payload_prot;
wire          slave_aw_cdc_cdc_sink_ready;
wire          slave_aw_cdc_cdc_sink_valid;
wire          slave_aw_cdc_cdc_source_first;
wire          slave_aw_cdc_cdc_source_last;
wire   [31:0] slave_aw_cdc_cdc_source_payload_addr;
wire    [2:0] slave_aw_cdc_cdc_source_payload_prot;
wire          slave_aw_cdc_cdc_source_ready;
wire          slave_aw_cdc_cdc_source_valid;
wire    [1:0] slave_aw_cdc_cdc_wrport_adr;
wire   [36:0] slave_aw_cdc_cdc_wrport_dat_r;
wire   [36:0] slave_aw_cdc_cdc_wrport_dat_w;
wire          slave_aw_cdc_cdc_wrport_we;
wire          slave_aw_cdc_sink_sink_first;
wire          slave_aw_cdc_sink_sink_last;
wire   [31:0] slave_aw_cdc_sink_sink_payload_addr;
wire    [2:0] slave_aw_cdc_sink_sink_payload_prot;
wire          slave_aw_cdc_sink_sink_ready;
wire          slave_aw_cdc_sink_sink_valid;
wire          slave_aw_cdc_source_source_first;
wire          slave_aw_cdc_source_source_last;
wire   [31:0] slave_aw_cdc_source_source_payload_addr;
wire    [2:0] slave_aw_cdc_source_source_payload_prot;
wire          slave_aw_cdc_source_source_ready;
wire          slave_aw_cdc_source_source_valid;
wire    [3:0] slave_b_cdc_cdc_asyncfifo_din;
wire    [3:0] slave_b_cdc_cdc_asyncfifo_dout;
wire          slave_b_cdc_cdc_asyncfifo_re;
wire          slave_b_cdc_cdc_asyncfifo_readable;
wire          slave_b_cdc_cdc_asyncfifo_we;
wire          slave_b_cdc_cdc_asyncfifo_writable;
wire    [2:0] slave_b_cdc_cdc_consume_wdomain;
wire          slave_b_cdc_cdc_fifo_in_first;
wire          slave_b_cdc_cdc_fifo_in_last;
wire    [1:0] slave_b_cdc_cdc_fifo_in_payload_resp;
wire          slave_b_cdc_cdc_fifo_out_first;
wire          slave_b_cdc_cdc_fifo_out_last;
wire    [1:0] slave_b_cdc_cdc_fifo_out_payload_resp;
wire          slave_b_cdc_cdc_graycounter0_ce;
reg     [2:0] slave_b_cdc_cdc_graycounter0_q = 3'd0;
reg     [2:0] slave_b_cdc_cdc_graycounter0_q_binary = 3'd0;
wire    [2:0] slave_b_cdc_cdc_graycounter0_q_next;
reg     [2:0] slave_b_cdc_cdc_graycounter0_q_next_binary = 3'd0;
wire          slave_b_cdc_cdc_graycounter1_ce;
reg     [2:0] slave_b_cdc_cdc_graycounter1_q = 3'd0;
reg     [2:0] slave_b_cdc_cdc_graycounter1_q_binary = 3'd0;
wire    [2:0] slave_b_cdc_cdc_graycounter1_q_next;
reg     [2:0] slave_b_cdc_cdc_graycounter1_q_next_binary = 3'd0;
wire    [2:0] slave_b_cdc_cdc_produce_rdomain;
wire    [1:0] slave_b_cdc_cdc_rdport_adr;
wire    [3:0] slave_b_cdc_cdc_rdport_dat_r;
wire          slave_b_cdc_cdc_sink_first;
wire          slave_b_cdc_cdc_sink_last;
wire    [1:0] slave_b_cdc_cdc_sink_payload_resp;
wire          slave_b_cdc_cdc_sink_ready;
wire          slave_b_cdc_cdc_sink_valid;
wire          slave_b_cdc_cdc_source_first;
wire          slave_b_cdc_cdc_source_last;
wire    [1:0] slave_b_cdc_cdc_source_payload_resp;
wire          slave_b_cdc_cdc_source_ready;
wire          slave_b_cdc_cdc_source_valid;
wire    [1:0] slave_b_cdc_cdc_wrport_adr;
wire    [3:0] slave_b_cdc_cdc_wrport_dat_r;
wire    [3:0] slave_b_cdc_cdc_wrport_dat_w;
wire          slave_b_cdc_cdc_wrport_we;
wire          slave_b_cdc_sink_sink_first;
wire          slave_b_cdc_sink_sink_last;
wire    [1:0] slave_b_cdc_sink_sink_payload_resp;
wire          slave_b_cdc_sink_sink_ready;
wire          slave_b_cdc_sink_sink_valid;
wire          slave_b_cdc_source_source_first;
wire          slave_b_cdc_source_source_last;
wire    [1:0] slave_b_cdc_source_source_payload_resp;
wire          slave_b_cdc_source_source_ready;
wire          slave_b_cdc_source_source_valid;
wire   [35:0] slave_r_cdc_cdc_asyncfifo_din;
wire   [35:0] slave_r_cdc_cdc_asyncfifo_dout;
wire          slave_r_cdc_cdc_asyncfifo_re;
wire          slave_r_cdc_cdc_asyncfifo_readable;
wire          slave_r_cdc_cdc_asyncfifo_we;
wire          slave_r_cdc_cdc_asyncfifo_writable;
wire    [2:0] slave_r_cdc_cdc_consume_wdomain;
wire          slave_r_cdc_cdc_fifo_in_first;
wire          slave_r_cdc_cdc_fifo_in_last;
wire   [31:0] slave_r_cdc_cdc_fifo_in_payload_data;
wire    [1:0] slave_r_cdc_cdc_fifo_in_payload_resp;
wire          slave_r_cdc_cdc_fifo_out_first;
wire          slave_r_cdc_cdc_fifo_out_last;
wire   [31:0] slave_r_cdc_cdc_fifo_out_payload_data;
wire    [1:0] slave_r_cdc_cdc_fifo_out_payload_resp;
wire          slave_r_cdc_cdc_graycounter0_ce;
reg     [2:0] slave_r_cdc_cdc_graycounter0_q = 3'd0;
reg     [2:0] slave_r_cdc_cdc_graycounter0_q_binary = 3'd0;
wire    [2:0] slave_r_cdc_cdc_graycounter0_q_next;
reg     [2:0] slave_r_cdc_cdc_graycounter0_q_next_binary = 3'd0;
wire          slave_r_cdc_cdc_graycounter1_ce;
reg     [2:0] slave_r_cdc_cdc_graycounter1_q = 3'd0;
reg     [2:0] slave_r_cdc_cdc_graycounter1_q_binary = 3'd0;
wire    [2:0] slave_r_cdc_cdc_graycounter1_q_next;
reg     [2:0] slave_r_cdc_cdc_graycounter1_q_next_binary = 3'd0;
wire    [2:0] slave_r_cdc_cdc_produce_rdomain;
wire    [1:0] slave_r_cdc_cdc_rdport_adr;
wire   [35:0] slave_r_cdc_cdc_rdport_dat_r;
wire          slave_r_cdc_cdc_sink_first;
wire          slave_r_cdc_cdc_sink_last;
wire   [31:0] slave_r_cdc_cdc_sink_payload_data;
wire    [1:0] slave_r_cdc_cdc_sink_payload_resp;
wire          slave_r_cdc_cdc_sink_ready;
wire          slave_r_cdc_cdc_sink_valid;
wire          slave_r_cdc_cdc_source_first;
wire          slave_r_cdc_cdc_source_last;
wire   [31:0] slave_r_cdc_cdc_source_payload_data;
wire    [1:0] slave_r_cdc_cdc_source_payload_resp;
wire          slave_r_cdc_cdc_source_ready;
wire          slave_r_cdc_cdc_source_valid;
wire    [1:0] slave_r_cdc_cdc_wrport_adr;
wire   [35:0] slave_r_cdc_cdc_wrport_dat_w;
wire          slave_r_cdc_cdc_wrport_we;
wire          slave_r_cdc_sink_sink_first;
wire          slave_r_cdc_sink_sink_last;
wire   [31:0] slave_r_cdc_sink_sink_payload_data;
wire    [1:0] slave_r_cdc_sink_sink_payload_resp;
wire          slave_r_cdc_sink_sink_ready;
wire          slave_r_cdc_sink_sink_valid;
wire          slave_r_cdc_source_source_first;
wire          slave_r_cdc_source_source_last;
wire   [31:0] slave_r_cdc_source_source_payload_data;
wire    [1:0] slave_r_cdc_source_source_payload_resp;
wire          slave_r_cdc_source_source_ready;
wire          slave_r_cdc_source_source_valid;
wire   [37:0] slave_w_cdc_cdc_asyncfifo_din;
wire   [37:0] slave_w_cdc_cdc_asyncfifo_dout;
wire          slave_w_cdc_cdc_asyncfifo_re;
wire          slave_w_cdc_cdc_asyncfifo_readable;
wire          slave_w_cdc_cdc_asyncfifo_we;
wire          slave_w_cdc_cdc_asyncfifo_writable;
wire    [2:0] slave_w_cdc_cdc_consume_wdomain;
wire          slave_w_cdc_cdc_fifo_in_first;
wire          slave_w_cdc_cdc_fifo_in_last;
wire   [31:0] slave_w_cdc_cdc_fifo_in_payload_data;
wire    [3:0] slave_w_cdc_cdc_fifo_in_payload_strb;
wire          slave_w_cdc_cdc_fifo_out_first;
wire          slave_w_cdc_cdc_fifo_out_last;
wire   [31:0] slave_w_cdc_cdc_fifo_out_payload_data;
wire    [3:0] slave_w_cdc_cdc_fifo_out_payload_strb;
wire          slave_w_cdc_cdc_graycounter0_ce;
reg     [2:0] slave_w_cdc_cdc_graycounter0_q = 3'd0;
reg     [2:0] slave_w_cdc_cdc_graycounter0_q_binary = 3'd0;
wire    [2:0] slave_w_cdc_cdc_graycounter0_q_next;
reg     [2:0] slave_w_cdc_cdc_graycounter0_q_next_binary = 3'd0;
wire          slave_w_cdc_cdc_graycounter1_ce;
reg     [2:0] slave_w_cdc_cdc_graycounter1_q = 3'd0;
reg     [2:0] slave_w_cdc_cdc_graycounter1_q_binary = 3'd0;
wire    [2:0] slave_w_cdc_cdc_graycounter1_q_next;
reg     [2:0] slave_w_cdc_cdc_graycounter1_q_next_binary = 3'd0;
wire    [2:0] slave_w_cdc_cdc_produce_rdomain;
wire    [1:0] slave_w_cdc_cdc_rdport_adr;
wire   [37:0] slave_w_cdc_cdc_rdport_dat_r;
wire          slave_w_cdc_cdc_sink_first;
wire          slave_w_cdc_cdc_sink_last;
wire   [31:0] slave_w_cdc_cdc_sink_payload_data;
wire    [3:0] slave_w_cdc_cdc_sink_payload_strb;
wire          slave_w_cdc_cdc_sink_ready;
wire          slave_w_cdc_cdc_sink_valid;
wire          slave_w_cdc_cdc_source_first;
wire          slave_w_cdc_cdc_source_last;
wire   [31:0] slave_w_cdc_cdc_source_payload_data;
wire    [3:0] slave_w_cdc_cdc_source_payload_strb;
wire          slave_w_cdc_cdc_source_ready;
wire          slave_w_cdc_cdc_source_valid;
wire    [1:0] slave_w_cdc_cdc_wrport_adr;
wire   [37:0] slave_w_cdc_cdc_wrport_dat_w;
wire          slave_w_cdc_cdc_wrport_we;
wire          slave_w_cdc_sink_sink_first;
wire          slave_w_cdc_sink_sink_last;
wire   [31:0] slave_w_cdc_sink_sink_payload_data;
wire    [3:0] slave_w_cdc_sink_sink_payload_strb;
wire          slave_w_cdc_sink_sink_ready;
wire          slave_w_cdc_sink_sink_valid;
wire          slave_w_cdc_source_source_first;
wire          slave_w_cdc_source_source_last;
wire   [31:0] slave_w_cdc_source_source_payload_data;
wire    [3:0] slave_w_cdc_source_source_payload_strb;
wire          slave_w_cdc_source_source_ready;
wire          slave_w_cdc_source_source_valid;
wire   [73:0] tx_cdc_asyncfifo_din;
wire   [73:0] tx_cdc_asyncfifo_dout;
wire          tx_cdc_asyncfifo_re;
wire          tx_cdc_asyncfifo_readable;
wire          tx_cdc_asyncfifo_we;
wire          tx_cdc_asyncfifo_writable;
wire    [4:0] tx_cdc_consume_wdomain;
reg    [73:0] tx_cdc_dout = 74'd0;
wire          tx_cdc_fifo_in_first;
wire          tx_cdc_fifo_in_last;
wire   [63:0] tx_cdc_fifo_in_payload_data;
wire    [7:0] tx_cdc_fifo_in_payload_keep;
wire          tx_cdc_fifo_out_first;
wire          tx_cdc_fifo_out_last;
wire   [63:0] tx_cdc_fifo_out_payload_data;
wire    [7:0] tx_cdc_fifo_out_payload_keep;
wire          tx_cdc_graycounter0_ce;
reg     [4:0] tx_cdc_graycounter0_q = 5'd0;
reg     [4:0] tx_cdc_graycounter0_q_binary = 5'd0;
wire    [4:0] tx_cdc_graycounter0_q_next;
reg     [4:0] tx_cdc_graycounter0_q_next_binary = 5'd0;
wire          tx_cdc_graycounter1_ce;
reg     [4:0] tx_cdc_graycounter1_q = 5'd0;
reg     [4:0] tx_cdc_graycounter1_q_binary = 5'd0;
wire    [4:0] tx_cdc_graycounter1_q_next;
reg     [4:0] tx_cdc_graycounter1_q_next_binary = 5'd0;
wire    [4:0] tx_cdc_produce_rdomain;
wire    [3:0] tx_cdc_rdport_adr;
wire   [73:0] tx_cdc_rdport_dat_r;
wire          tx_cdc_re;
reg           tx_cdc_readable = 1'd0;
wire          tx_cdc_sink_first;
wire          tx_cdc_sink_last;
wire   [63:0] tx_cdc_sink_payload_data;
wire    [7:0] tx_cdc_sink_payload_keep;
wire          tx_cdc_sink_ready;
wire          tx_cdc_sink_valid;
wire          tx_cdc_source_first;
wire          tx_cdc_source_last;
wire   [63:0] tx_cdc_source_payload_data;
wire    [7:0] tx_cdc_source_payload_keep;
wire          tx_cdc_source_ready;
wire          tx_cdc_source_valid;
wire    [3:0] tx_cdc_wrport_adr;
wire   [73:0] tx_cdc_wrport_dat_w;
wire          tx_cdc_wrport_we;

//------------------------------------------------------------------------------
// Combinatorial Logic
//------------------------------------------------------------------------------

assign tx_cdc_sink_valid = sink_valid;
assign sink_ready = tx_cdc_sink_ready;
assign tx_cdc_sink_first = sink_first;
assign tx_cdc_sink_last = sink_last;
assign tx_cdc_sink_payload_data = sink_payload_data;
assign tx_cdc_sink_payload_keep = sink_payload_keep;
assign source_valid = tx_cdc_source_valid;
assign tx_cdc_source_ready = source_ready;
assign source_first = tx_cdc_source_first;
assign source_last = tx_cdc_source_last;
assign source_payload_data = tx_cdc_source_payload_data;
assign source_payload_keep = tx_cdc_source_payload_keep;
assign tx_cdc_asyncfifo_din = {tx_cdc_fifo_in_last, tx_cdc_fifo_in_first, tx_cdc_fifo_in_payload_keep, tx_cdc_fifo_in_payload_data};
assign {tx_cdc_fifo_out_last, tx_cdc_fifo_out_first, tx_cdc_fifo_out_payload_keep, tx_cdc_fifo_out_payload_data} = tx_cdc_dout;
assign tx_cdc_sink_ready = tx_cdc_asyncfifo_writable;
assign tx_cdc_asyncfifo_we = tx_cdc_sink_valid;
assign tx_cdc_fifo_in_first = tx_cdc_sink_first;
assign tx_cdc_fifo_in_last = tx_cdc_sink_last;
assign tx_cdc_fifo_in_payload_data = tx_cdc_sink_payload_data;
assign tx_cdc_fifo_in_payload_keep = tx_cdc_sink_payload_keep;
assign tx_cdc_source_valid = tx_cdc_readable;
assign tx_cdc_source_first = tx_cdc_fifo_out_first;
assign tx_cdc_source_last = tx_cdc_fifo_out_last;
assign tx_cdc_source_payload_data = tx_cdc_fifo_out_payload_data;
assign tx_cdc_source_payload_keep = tx_cdc_fifo_out_payload_keep;
assign tx_cdc_re = tx_cdc_source_ready;
assign tx_cdc_asyncfifo_re = (tx_cdc_re | (~tx_cdc_readable));
assign tx_cdc_graycounter0_ce = (tx_cdc_asyncfifo_writable & tx_cdc_asyncfifo_we);
assign tx_cdc_graycounter1_ce = (tx_cdc_asyncfifo_readable & tx_cdc_asyncfifo_re);
assign tx_cdc_asyncfifo_writable = (((tx_cdc_graycounter0_q[4] == tx_cdc_consume_wdomain[4]) | (tx_cdc_graycounter0_q[3] == tx_cdc_consume_wdomain[3])) | (tx_cdc_graycounter0_q[2:0] != tx_cdc_consume_wdomain[2:0]));
assign tx_cdc_asyncfifo_readable = (tx_cdc_graycounter1_q != tx_cdc_produce_rdomain);
assign tx_cdc_wrport_adr = tx_cdc_graycounter0_q_binary[3:0];
assign tx_cdc_wrport_dat_w = tx_cdc_asyncfifo_din;
assign tx_cdc_wrport_we = tx_cdc_graycounter0_ce;
assign tx_cdc_rdport_adr = tx_cdc_graycounter1_q_next_binary[3:0];
assign tx_cdc_asyncfifo_dout = tx_cdc_rdport_dat_r;
assign array_write_memory0_adr = tx_cdc_wrport_adr;
assign array_write_memory0_we = tx_cdc_wrport_we;
assign array_write_memory0_dat_w = tx_cdc_wrport_dat_w[71:0];
assign array_read_memory0_adr = tx_cdc_rdport_adr;
assign array_write_memory1_adr = tx_cdc_wrport_adr;
assign array_write_memory1_we = tx_cdc_wrport_we;
assign array_write_memory1_dat_w = tx_cdc_wrport_dat_w[73:72];
assign array_read_memory1_adr = tx_cdc_rdport_adr;
assign tx_cdc_rdport_dat_r = {array_read_memory1_dat_r, array_read_memory0_dat_r};
always @(*) begin
    tx_cdc_graycounter0_q_next_binary = 5'd0;
    if (tx_cdc_graycounter0_ce) begin
        tx_cdc_graycounter0_q_next_binary = (tx_cdc_graycounter0_q_binary + 1'd1);
    end else begin
        tx_cdc_graycounter0_q_next_binary = tx_cdc_graycounter0_q_binary;
    end
end
assign tx_cdc_graycounter0_q_next = (tx_cdc_graycounter0_q_next_binary ^ tx_cdc_graycounter0_q_next_binary[4:1]);
always @(*) begin
    tx_cdc_graycounter1_q_next_binary = 5'd0;
    if (tx_cdc_graycounter1_ce) begin
        tx_cdc_graycounter1_q_next_binary = (tx_cdc_graycounter1_q_binary + 1'd1);
    end else begin
        tx_cdc_graycounter1_q_next_binary = tx_cdc_graycounter1_q_binary;
    end
end
assign tx_cdc_graycounter1_q_next = (tx_cdc_graycounter1_q_next_binary ^ tx_cdc_graycounter1_q_next_binary[4:1]);
assign rx_cdc_sink_valid = sink_valid_1;
assign sink_ready_1 = rx_cdc_sink_ready;
assign rx_cdc_sink_first = sink_first_1;
assign rx_cdc_sink_last = sink_last_1;
assign rx_cdc_sink_payload_data = sink_payload_data_1;
assign rx_cdc_sink_payload_keep = sink_payload_keep_1;
assign source_valid_1 = rx_cdc_source_valid;
assign rx_cdc_source_ready = source_ready_1;
assign source_first_1 = rx_cdc_source_first;
assign source_last_1 = rx_cdc_source_last;
assign source_payload_data_1 = rx_cdc_source_payload_data;
assign source_payload_keep_1 = rx_cdc_source_payload_keep;
assign rx_cdc_asyncfifo_din = {rx_cdc_fifo_in_last, rx_cdc_fifo_in_first, rx_cdc_fifo_in_payload_keep, rx_cdc_fifo_in_payload_data};
assign {rx_cdc_fifo_out_last, rx_cdc_fifo_out_first, rx_cdc_fifo_out_payload_keep, rx_cdc_fifo_out_payload_data} = rx_cdc_dout;
assign rx_cdc_sink_ready = rx_cdc_asyncfifo_writable;
assign rx_cdc_asyncfifo_we = rx_cdc_sink_valid;
assign rx_cdc_fifo_in_first = rx_cdc_sink_first;
assign rx_cdc_fifo_in_last = rx_cdc_sink_last;
assign rx_cdc_fifo_in_payload_data = rx_cdc_sink_payload_data;
assign rx_cdc_fifo_in_payload_keep = rx_cdc_sink_payload_keep;
assign rx_cdc_source_valid = rx_cdc_readable;
assign rx_cdc_source_first = rx_cdc_fifo_out_first;
assign rx_cdc_source_last = rx_cdc_fifo_out_last;
assign rx_cdc_source_payload_data = rx_cdc_fifo_out_payload_data;
assign rx_cdc_source_payload_keep = rx_cdc_fifo_out_payload_keep;
assign rx_cdc_re = rx_cdc_source_ready;
assign rx_cdc_asyncfifo_re = (rx_cdc_re | (~rx_cdc_readable));
assign rx_cdc_graycounter0_ce = (rx_cdc_asyncfifo_writable & rx_cdc_asyncfifo_we);
assign rx_cdc_graycounter1_ce = (rx_cdc_asyncfifo_readable & rx_cdc_asyncfifo_re);
assign rx_cdc_asyncfifo_writable = (((rx_cdc_graycounter0_q[4] == rx_cdc_consume_wdomain[4]) | (rx_cdc_graycounter0_q[3] == rx_cdc_consume_wdomain[3])) | (rx_cdc_graycounter0_q[2:0] != rx_cdc_consume_wdomain[2:0]));
assign rx_cdc_asyncfifo_readable = (rx_cdc_graycounter1_q != rx_cdc_produce_rdomain);
assign rx_cdc_wrport_adr = rx_cdc_graycounter0_q_binary[3:0];
assign rx_cdc_wrport_dat_w = rx_cdc_asyncfifo_din;
assign rx_cdc_wrport_we = rx_cdc_graycounter0_ce;
assign rx_cdc_rdport_adr = rx_cdc_graycounter1_q_next_binary[3:0];
assign rx_cdc_asyncfifo_dout = rx_cdc_rdport_dat_r;
assign array_write_memory2_adr = rx_cdc_wrport_adr;
assign array_write_memory2_we = rx_cdc_wrport_we;
assign array_write_memory2_dat_w = rx_cdc_wrport_dat_w[71:0];
assign array_read_memory2_adr = rx_cdc_rdport_adr;
assign array_write_memory3_adr = rx_cdc_wrport_adr;
assign array_write_memory3_we = rx_cdc_wrport_we;
assign array_write_memory3_dat_w = rx_cdc_wrport_dat_w[73:72];
assign array_read_memory3_adr = rx_cdc_rdport_adr;
assign rx_cdc_rdport_dat_r = {array_read_memory3_dat_r, array_read_memory2_dat_r};
always @(*) begin
    rx_cdc_graycounter0_q_next_binary = 5'd0;
    if (rx_cdc_graycounter0_ce) begin
        rx_cdc_graycounter0_q_next_binary = (rx_cdc_graycounter0_q_binary + 1'd1);
    end else begin
        rx_cdc_graycounter0_q_next_binary = rx_cdc_graycounter0_q_binary;
    end
end
assign rx_cdc_graycounter0_q_next = (rx_cdc_graycounter0_q_next_binary ^ rx_cdc_graycounter0_q_next_binary[4:1]);
always @(*) begin
    rx_cdc_graycounter1_q_next_binary = 5'd0;
    if (rx_cdc_graycounter1_ce) begin
        rx_cdc_graycounter1_q_next_binary = (rx_cdc_graycounter1_q_binary + 1'd1);
    end else begin
        rx_cdc_graycounter1_q_next_binary = rx_cdc_graycounter1_q_binary;
    end
end
assign rx_cdc_graycounter1_q_next = (rx_cdc_graycounter1_q_next_binary ^ rx_cdc_graycounter1_q_next_binary[4:1]);
assign slave_aw_cdc_sink_sink_valid = aw_valid;
assign aw_ready = slave_aw_cdc_sink_sink_ready;
assign slave_aw_cdc_sink_sink_first = aw_first;
assign slave_aw_cdc_sink_sink_last = aw_last;
assign slave_aw_cdc_sink_sink_payload_addr = aw_payload_addr;
assign slave_aw_cdc_sink_sink_payload_prot = aw_payload_prot;
assign aw_valid_1 = slave_aw_cdc_source_source_valid;
assign slave_aw_cdc_source_source_ready = aw_ready_1;
assign aw_first_1 = slave_aw_cdc_source_source_first;
assign aw_last_1 = slave_aw_cdc_source_source_last;
assign aw_payload_addr_1 = slave_aw_cdc_source_source_payload_addr;
assign aw_payload_prot_1 = slave_aw_cdc_source_source_payload_prot;
assign slave_w_cdc_sink_sink_valid = w_valid;
assign w_ready = slave_w_cdc_sink_sink_ready;
assign slave_w_cdc_sink_sink_first = w_first;
assign slave_w_cdc_sink_sink_last = w_last;
assign slave_w_cdc_sink_sink_payload_data = w_payload_data;
assign slave_w_cdc_sink_sink_payload_strb = w_payload_strb;
assign w_valid_1 = slave_w_cdc_source_source_valid;
assign slave_w_cdc_source_source_ready = w_ready_1;
assign w_first_1 = slave_w_cdc_source_source_first;
assign w_last_1 = slave_w_cdc_source_source_last;
assign w_payload_data_1 = slave_w_cdc_source_source_payload_data;
assign w_payload_strb_1 = slave_w_cdc_source_source_payload_strb;
assign slave_b_cdc_sink_sink_valid = b_valid_1;
assign b_ready_1 = slave_b_cdc_sink_sink_ready;
assign slave_b_cdc_sink_sink_first = b_first_1;
assign slave_b_cdc_sink_sink_last = b_last_1;
assign slave_b_cdc_sink_sink_payload_resp = b_payload_resp_1;
assign b_valid = slave_b_cdc_source_source_valid;
assign slave_b_cdc_source_source_ready = b_ready;
assign b_first = slave_b_cdc_source_source_first;
assign b_last = slave_b_cdc_source_source_last;
assign b_payload_resp = slave_b_cdc_source_source_payload_resp;
assign slave_ar_cdc_sink_sink_valid = ar_valid;
assign ar_ready = slave_ar_cdc_sink_sink_ready;
assign slave_ar_cdc_sink_sink_first = ar_first;
assign slave_ar_cdc_sink_sink_last = ar_last_1;
assign slave_ar_cdc_sink_sink_payload_addr = ar_payload_addr_1;
assign slave_ar_cdc_sink_sink_payload_prot = ar_payload_prot_1;
assign ar_valid_1 = slave_ar_cdc_source_source_valid;
assign slave_ar_cdc_source_source_ready = ar_ready_1;
assign ar_first_1 = slave_ar_cdc_source_source_first;
assign ar_last = slave_ar_cdc_source_source_last;
assign ar_payload_addr = slave_ar_cdc_source_source_payload_addr;
assign ar_payload_prot = slave_ar_cdc_source_source_payload_prot;
assign slave_r_cdc_sink_sink_valid = r_valid;
assign r_ready = slave_r_cdc_sink_sink_ready;
assign slave_r_cdc_sink_sink_first = r_first;
assign slave_r_cdc_sink_sink_last = r_last;
assign slave_r_cdc_sink_sink_payload_resp = r_payload_resp;
assign slave_r_cdc_sink_sink_payload_data = r_payload_data;
assign r_valid_1 = slave_r_cdc_source_source_valid;
assign slave_r_cdc_source_source_ready = r_ready_1;
assign r_first_1 = slave_r_cdc_source_source_first;
assign r_last_1 = slave_r_cdc_source_source_last;
assign r_payload_resp_1 = slave_r_cdc_source_source_payload_resp;
assign r_payload_data_1 = slave_r_cdc_source_source_payload_data;
assign slave_aw_cdc_cdc_sink_valid = slave_aw_cdc_sink_sink_valid;
assign slave_aw_cdc_sink_sink_ready = slave_aw_cdc_cdc_sink_ready;
assign slave_aw_cdc_cdc_sink_first = slave_aw_cdc_sink_sink_first;
assign slave_aw_cdc_cdc_sink_last = slave_aw_cdc_sink_sink_last;
assign slave_aw_cdc_cdc_sink_payload_addr = slave_aw_cdc_sink_sink_payload_addr;
assign slave_aw_cdc_cdc_sink_payload_prot = slave_aw_cdc_sink_sink_payload_prot;
assign slave_aw_cdc_source_source_valid = slave_aw_cdc_cdc_source_valid;
assign slave_aw_cdc_cdc_source_ready = slave_aw_cdc_source_source_ready;
assign slave_aw_cdc_source_source_first = slave_aw_cdc_cdc_source_first;
assign slave_aw_cdc_source_source_last = slave_aw_cdc_cdc_source_last;
assign slave_aw_cdc_source_source_payload_addr = slave_aw_cdc_cdc_source_payload_addr;
assign slave_aw_cdc_source_source_payload_prot = slave_aw_cdc_cdc_source_payload_prot;
assign slave_aw_cdc_cdc_asyncfifo_din = {slave_aw_cdc_cdc_fifo_in_last, slave_aw_cdc_cdc_fifo_in_first, slave_aw_cdc_cdc_fifo_in_payload_prot, slave_aw_cdc_cdc_fifo_in_payload_addr};
assign {slave_aw_cdc_cdc_fifo_out_last, slave_aw_cdc_cdc_fifo_out_first, slave_aw_cdc_cdc_fifo_out_payload_prot, slave_aw_cdc_cdc_fifo_out_payload_addr} = slave_aw_cdc_cdc_asyncfifo_dout;
assign slave_aw_cdc_cdc_sink_ready = slave_aw_cdc_cdc_asyncfifo_writable;
assign slave_aw_cdc_cdc_asyncfifo_we = slave_aw_cdc_cdc_sink_valid;
assign slave_aw_cdc_cdc_fifo_in_first = slave_aw_cdc_cdc_sink_first;
assign slave_aw_cdc_cdc_fifo_in_last = slave_aw_cdc_cdc_sink_last;
assign slave_aw_cdc_cdc_fifo_in_payload_addr = slave_aw_cdc_cdc_sink_payload_addr;
assign slave_aw_cdc_cdc_fifo_in_payload_prot = slave_aw_cdc_cdc_sink_payload_prot;
assign slave_aw_cdc_cdc_source_valid = slave_aw_cdc_cdc_asyncfifo_readable;
assign slave_aw_cdc_cdc_source_first = slave_aw_cdc_cdc_fifo_out_first;
assign slave_aw_cdc_cdc_source_last = slave_aw_cdc_cdc_fifo_out_last;
assign slave_aw_cdc_cdc_source_payload_addr = slave_aw_cdc_cdc_fifo_out_payload_addr;
assign slave_aw_cdc_cdc_source_payload_prot = slave_aw_cdc_cdc_fifo_out_payload_prot;
assign slave_aw_cdc_cdc_asyncfifo_re = slave_aw_cdc_cdc_source_ready;
assign slave_aw_cdc_cdc_graycounter0_ce = (slave_aw_cdc_cdc_asyncfifo_writable & slave_aw_cdc_cdc_asyncfifo_we);
assign slave_aw_cdc_cdc_graycounter1_ce = (slave_aw_cdc_cdc_asyncfifo_readable & slave_aw_cdc_cdc_asyncfifo_re);
assign slave_aw_cdc_cdc_asyncfifo_writable = (((slave_aw_cdc_cdc_graycounter0_q[2] == slave_aw_cdc_cdc_consume_wdomain[2]) | (slave_aw_cdc_cdc_graycounter0_q[1] == slave_aw_cdc_cdc_consume_wdomain[1])) | (slave_aw_cdc_cdc_graycounter0_q[0] != slave_aw_cdc_cdc_consume_wdomain[0]));
assign slave_aw_cdc_cdc_asyncfifo_readable = (slave_aw_cdc_cdc_graycounter1_q != slave_aw_cdc_cdc_produce_rdomain);
assign slave_aw_cdc_cdc_wrport_adr = slave_aw_cdc_cdc_graycounter0_q_binary[1:0];
assign slave_aw_cdc_cdc_wrport_dat_w = slave_aw_cdc_cdc_asyncfifo_din;
assign slave_aw_cdc_cdc_wrport_we = slave_aw_cdc_cdc_graycounter0_ce;
assign slave_aw_cdc_cdc_rdport_adr = slave_aw_cdc_cdc_graycounter1_q_next_binary[1:0];
assign slave_aw_cdc_cdc_asyncfifo_dout = slave_aw_cdc_cdc_rdport_dat_r;
always @(*) begin
    slave_aw_cdc_cdc_graycounter0_q_next_binary = 3'd0;
    if (slave_aw_cdc_cdc_graycounter0_ce) begin
        slave_aw_cdc_cdc_graycounter0_q_next_binary = (slave_aw_cdc_cdc_graycounter0_q_binary + 1'd1);
    end else begin
        slave_aw_cdc_cdc_graycounter0_q_next_binary = slave_aw_cdc_cdc_graycounter0_q_binary;
    end
end
assign slave_aw_cdc_cdc_graycounter0_q_next = (slave_aw_cdc_cdc_graycounter0_q_next_binary ^ slave_aw_cdc_cdc_graycounter0_q_next_binary[2:1]);
always @(*) begin
    slave_aw_cdc_cdc_graycounter1_q_next_binary = 3'd0;
    if (slave_aw_cdc_cdc_graycounter1_ce) begin
        slave_aw_cdc_cdc_graycounter1_q_next_binary = (slave_aw_cdc_cdc_graycounter1_q_binary + 1'd1);
    end else begin
        slave_aw_cdc_cdc_graycounter1_q_next_binary = slave_aw_cdc_cdc_graycounter1_q_binary;
    end
end
assign slave_aw_cdc_cdc_graycounter1_q_next = (slave_aw_cdc_cdc_graycounter1_q_next_binary ^ slave_aw_cdc_cdc_graycounter1_q_next_binary[2:1]);
assign slave_w_cdc_cdc_sink_valid = slave_w_cdc_sink_sink_valid;
assign slave_w_cdc_sink_sink_ready = slave_w_cdc_cdc_sink_ready;
assign slave_w_cdc_cdc_sink_first = slave_w_cdc_sink_sink_first;
assign slave_w_cdc_cdc_sink_last = slave_w_cdc_sink_sink_last;
assign slave_w_cdc_cdc_sink_payload_data = slave_w_cdc_sink_sink_payload_data;
assign slave_w_cdc_cdc_sink_payload_strb = slave_w_cdc_sink_sink_payload_strb;
assign slave_w_cdc_source_source_valid = slave_w_cdc_cdc_source_valid;
assign slave_w_cdc_cdc_source_ready = slave_w_cdc_source_source_ready;
assign slave_w_cdc_source_source_first = slave_w_cdc_cdc_source_first;
assign slave_w_cdc_source_source_last = slave_w_cdc_cdc_source_last;
assign slave_w_cdc_source_source_payload_data = slave_w_cdc_cdc_source_payload_data;
assign slave_w_cdc_source_source_payload_strb = slave_w_cdc_cdc_source_payload_strb;
assign slave_w_cdc_cdc_asyncfifo_din = {slave_w_cdc_cdc_fifo_in_last, slave_w_cdc_cdc_fifo_in_first, slave_w_cdc_cdc_fifo_in_payload_strb, slave_w_cdc_cdc_fifo_in_payload_data};
assign {slave_w_cdc_cdc_fifo_out_last, slave_w_cdc_cdc_fifo_out_first, slave_w_cdc_cdc_fifo_out_payload_strb, slave_w_cdc_cdc_fifo_out_payload_data} = slave_w_cdc_cdc_asyncfifo_dout;
assign slave_w_cdc_cdc_sink_ready = slave_w_cdc_cdc_asyncfifo_writable;
assign slave_w_cdc_cdc_asyncfifo_we = slave_w_cdc_cdc_sink_valid;
assign slave_w_cdc_cdc_fifo_in_first = slave_w_cdc_cdc_sink_first;
assign slave_w_cdc_cdc_fifo_in_last = slave_w_cdc_cdc_sink_last;
assign slave_w_cdc_cdc_fifo_in_payload_data = slave_w_cdc_cdc_sink_payload_data;
assign slave_w_cdc_cdc_fifo_in_payload_strb = slave_w_cdc_cdc_sink_payload_strb;
assign slave_w_cdc_cdc_source_valid = slave_w_cdc_cdc_asyncfifo_readable;
assign slave_w_cdc_cdc_source_first = slave_w_cdc_cdc_fifo_out_first;
assign slave_w_cdc_cdc_source_last = slave_w_cdc_cdc_fifo_out_last;
assign slave_w_cdc_cdc_source_payload_data = slave_w_cdc_cdc_fifo_out_payload_data;
assign slave_w_cdc_cdc_source_payload_strb = slave_w_cdc_cdc_fifo_out_payload_strb;
assign slave_w_cdc_cdc_asyncfifo_re = slave_w_cdc_cdc_source_ready;
assign slave_w_cdc_cdc_graycounter0_ce = (slave_w_cdc_cdc_asyncfifo_writable & slave_w_cdc_cdc_asyncfifo_we);
assign slave_w_cdc_cdc_graycounter1_ce = (slave_w_cdc_cdc_asyncfifo_readable & slave_w_cdc_cdc_asyncfifo_re);
assign slave_w_cdc_cdc_asyncfifo_writable = (((slave_w_cdc_cdc_graycounter0_q[2] == slave_w_cdc_cdc_consume_wdomain[2]) | (slave_w_cdc_cdc_graycounter0_q[1] == slave_w_cdc_cdc_consume_wdomain[1])) | (slave_w_cdc_cdc_graycounter0_q[0] != slave_w_cdc_cdc_consume_wdomain[0]));
assign slave_w_cdc_cdc_asyncfifo_readable = (slave_w_cdc_cdc_graycounter1_q != slave_w_cdc_cdc_produce_rdomain);
assign slave_w_cdc_cdc_wrport_adr = slave_w_cdc_cdc_graycounter0_q_binary[1:0];
assign slave_w_cdc_cdc_wrport_dat_w = slave_w_cdc_cdc_asyncfifo_din;
assign slave_w_cdc_cdc_wrport_we = slave_w_cdc_cdc_graycounter0_ce;
assign slave_w_cdc_cdc_rdport_adr = slave_w_cdc_cdc_graycounter1_q_next_binary[1:0];
assign slave_w_cdc_cdc_asyncfifo_dout = slave_w_cdc_cdc_rdport_dat_r;
assign slave_array_write_memory0_adr = slave_w_cdc_cdc_wrport_adr;
assign slave_array_write_memory0_we = slave_w_cdc_cdc_wrport_we;
assign slave_array_write_memory0_dat_w = slave_w_cdc_cdc_wrport_dat_w[35:0];
assign slave_array_read_memory0_adr = slave_w_cdc_cdc_rdport_adr;
assign slave_array_write_memory1_adr = slave_w_cdc_cdc_wrport_adr;
assign slave_array_write_memory1_we = slave_w_cdc_cdc_wrport_we;
assign slave_array_write_memory1_dat_w = slave_w_cdc_cdc_wrport_dat_w[37:36];
assign slave_array_read_memory1_adr = slave_w_cdc_cdc_rdport_adr;
assign slave_w_cdc_cdc_rdport_dat_r = {slave_array_read_memory1_dat_r, slave_array_read_memory0_dat_r};
always @(*) begin
    slave_w_cdc_cdc_graycounter0_q_next_binary = 3'd0;
    if (slave_w_cdc_cdc_graycounter0_ce) begin
        slave_w_cdc_cdc_graycounter0_q_next_binary = (slave_w_cdc_cdc_graycounter0_q_binary + 1'd1);
    end else begin
        slave_w_cdc_cdc_graycounter0_q_next_binary = slave_w_cdc_cdc_graycounter0_q_binary;
    end
end
assign slave_w_cdc_cdc_graycounter0_q_next = (slave_w_cdc_cdc_graycounter0_q_next_binary ^ slave_w_cdc_cdc_graycounter0_q_next_binary[2:1]);
always @(*) begin
    slave_w_cdc_cdc_graycounter1_q_next_binary = 3'd0;
    if (slave_w_cdc_cdc_graycounter1_ce) begin
        slave_w_cdc_cdc_graycounter1_q_next_binary = (slave_w_cdc_cdc_graycounter1_q_binary + 1'd1);
    end else begin
        slave_w_cdc_cdc_graycounter1_q_next_binary = slave_w_cdc_cdc_graycounter1_q_binary;
    end
end
assign slave_w_cdc_cdc_graycounter1_q_next = (slave_w_cdc_cdc_graycounter1_q_next_binary ^ slave_w_cdc_cdc_graycounter1_q_next_binary[2:1]);
assign slave_b_cdc_cdc_sink_valid = slave_b_cdc_sink_sink_valid;
assign slave_b_cdc_sink_sink_ready = slave_b_cdc_cdc_sink_ready;
assign slave_b_cdc_cdc_sink_first = slave_b_cdc_sink_sink_first;
assign slave_b_cdc_cdc_sink_last = slave_b_cdc_sink_sink_last;
assign slave_b_cdc_cdc_sink_payload_resp = slave_b_cdc_sink_sink_payload_resp;
assign slave_b_cdc_source_source_valid = slave_b_cdc_cdc_source_valid;
assign slave_b_cdc_cdc_source_ready = slave_b_cdc_source_source_ready;
assign slave_b_cdc_source_source_first = slave_b_cdc_cdc_source_first;
assign slave_b_cdc_source_source_last = slave_b_cdc_cdc_source_last;
assign slave_b_cdc_source_source_payload_resp = slave_b_cdc_cdc_source_payload_resp;
assign slave_b_cdc_cdc_asyncfifo_din = {slave_b_cdc_cdc_fifo_in_last, slave_b_cdc_cdc_fifo_in_first, slave_b_cdc_cdc_fifo_in_payload_resp};
assign {slave_b_cdc_cdc_fifo_out_last, slave_b_cdc_cdc_fifo_out_first, slave_b_cdc_cdc_fifo_out_payload_resp} = slave_b_cdc_cdc_asyncfifo_dout;
assign slave_b_cdc_cdc_sink_ready = slave_b_cdc_cdc_asyncfifo_writable;
assign slave_b_cdc_cdc_asyncfifo_we = slave_b_cdc_cdc_sink_valid;
assign slave_b_cdc_cdc_fifo_in_first = slave_b_cdc_cdc_sink_first;
assign slave_b_cdc_cdc_fifo_in_last = slave_b_cdc_cdc_sink_last;
assign slave_b_cdc_cdc_fifo_in_payload_resp = slave_b_cdc_cdc_sink_payload_resp;
assign slave_b_cdc_cdc_source_valid = slave_b_cdc_cdc_asyncfifo_readable;
assign slave_b_cdc_cdc_source_first = slave_b_cdc_cdc_fifo_out_first;
assign slave_b_cdc_cdc_source_last = slave_b_cdc_cdc_fifo_out_last;
assign slave_b_cdc_cdc_source_payload_resp = slave_b_cdc_cdc_fifo_out_payload_resp;
assign slave_b_cdc_cdc_asyncfifo_re = slave_b_cdc_cdc_source_ready;
assign slave_b_cdc_cdc_graycounter0_ce = (slave_b_cdc_cdc_asyncfifo_writable & slave_b_cdc_cdc_asyncfifo_we);
assign slave_b_cdc_cdc_graycounter1_ce = (slave_b_cdc_cdc_asyncfifo_readable & slave_b_cdc_cdc_asyncfifo_re);
assign slave_b_cdc_cdc_asyncfifo_writable = (((slave_b_cdc_cdc_graycounter0_q[2] == slave_b_cdc_cdc_consume_wdomain[2]) | (slave_b_cdc_cdc_graycounter0_q[1] == slave_b_cdc_cdc_consume_wdomain[1])) | (slave_b_cdc_cdc_graycounter0_q[0] != slave_b_cdc_cdc_consume_wdomain[0]));
assign slave_b_cdc_cdc_asyncfifo_readable = (slave_b_cdc_cdc_graycounter1_q != slave_b_cdc_cdc_produce_rdomain);
assign slave_b_cdc_cdc_wrport_adr = slave_b_cdc_cdc_graycounter0_q_binary[1:0];
assign slave_b_cdc_cdc_wrport_dat_w = slave_b_cdc_cdc_asyncfifo_din;
assign slave_b_cdc_cdc_wrport_we = slave_b_cdc_cdc_graycounter0_ce;
assign slave_b_cdc_cdc_rdport_adr = slave_b_cdc_cdc_graycounter1_q_next_binary[1:0];
assign slave_b_cdc_cdc_asyncfifo_dout = slave_b_cdc_cdc_rdport_dat_r;
always @(*) begin
    slave_b_cdc_cdc_graycounter0_q_next_binary = 3'd0;
    if (slave_b_cdc_cdc_graycounter0_ce) begin
        slave_b_cdc_cdc_graycounter0_q_next_binary = (slave_b_cdc_cdc_graycounter0_q_binary + 1'd1);
    end else begin
        slave_b_cdc_cdc_graycounter0_q_next_binary = slave_b_cdc_cdc_graycounter0_q_binary;
    end
end
assign slave_b_cdc_cdc_graycounter0_q_next = (slave_b_cdc_cdc_graycounter0_q_next_binary ^ slave_b_cdc_cdc_graycounter0_q_next_binary[2:1]);
always @(*) begin
    slave_b_cdc_cdc_graycounter1_q_next_binary = 3'd0;
    if (slave_b_cdc_cdc_graycounter1_ce) begin
        slave_b_cdc_cdc_graycounter1_q_next_binary = (slave_b_cdc_cdc_graycounter1_q_binary + 1'd1);
    end else begin
        slave_b_cdc_cdc_graycounter1_q_next_binary = slave_b_cdc_cdc_graycounter1_q_binary;
    end
end
assign slave_b_cdc_cdc_graycounter1_q_next = (slave_b_cdc_cdc_graycounter1_q_next_binary ^ slave_b_cdc_cdc_graycounter1_q_next_binary[2:1]);
assign slave_ar_cdc_cdc_sink_valid = slave_ar_cdc_sink_sink_valid;
assign slave_ar_cdc_sink_sink_ready = slave_ar_cdc_cdc_sink_ready;
assign slave_ar_cdc_cdc_sink_first = slave_ar_cdc_sink_sink_first;
assign slave_ar_cdc_cdc_sink_last = slave_ar_cdc_sink_sink_last;
assign slave_ar_cdc_cdc_sink_payload_addr = slave_ar_cdc_sink_sink_payload_addr;
assign slave_ar_cdc_cdc_sink_payload_prot = slave_ar_cdc_sink_sink_payload_prot;
assign slave_ar_cdc_source_source_valid = slave_ar_cdc_cdc_source_valid;
assign slave_ar_cdc_cdc_source_ready = slave_ar_cdc_source_source_ready;
assign slave_ar_cdc_source_source_first = slave_ar_cdc_cdc_source_first;
assign slave_ar_cdc_source_source_last = slave_ar_cdc_cdc_source_last;
assign slave_ar_cdc_source_source_payload_addr = slave_ar_cdc_cdc_source_payload_addr;
assign slave_ar_cdc_source_source_payload_prot = slave_ar_cdc_cdc_source_payload_prot;
assign slave_ar_cdc_cdc_asyncfifo_din = {slave_ar_cdc_cdc_fifo_in_last, slave_ar_cdc_cdc_fifo_in_first, slave_ar_cdc_cdc_fifo_in_payload_prot, slave_ar_cdc_cdc_fifo_in_payload_addr};
assign {slave_ar_cdc_cdc_fifo_out_last, slave_ar_cdc_cdc_fifo_out_first, slave_ar_cdc_cdc_fifo_out_payload_prot, slave_ar_cdc_cdc_fifo_out_payload_addr} = slave_ar_cdc_cdc_asyncfifo_dout;
assign slave_ar_cdc_cdc_sink_ready = slave_ar_cdc_cdc_asyncfifo_writable;
assign slave_ar_cdc_cdc_asyncfifo_we = slave_ar_cdc_cdc_sink_valid;
assign slave_ar_cdc_cdc_fifo_in_first = slave_ar_cdc_cdc_sink_first;
assign slave_ar_cdc_cdc_fifo_in_last = slave_ar_cdc_cdc_sink_last;
assign slave_ar_cdc_cdc_fifo_in_payload_addr = slave_ar_cdc_cdc_sink_payload_addr;
assign slave_ar_cdc_cdc_fifo_in_payload_prot = slave_ar_cdc_cdc_sink_payload_prot;
assign slave_ar_cdc_cdc_source_valid = slave_ar_cdc_cdc_asyncfifo_readable;
assign slave_ar_cdc_cdc_source_first = slave_ar_cdc_cdc_fifo_out_first;
assign slave_ar_cdc_cdc_source_last = slave_ar_cdc_cdc_fifo_out_last;
assign slave_ar_cdc_cdc_source_payload_addr = slave_ar_cdc_cdc_fifo_out_payload_addr;
assign slave_ar_cdc_cdc_source_payload_prot = slave_ar_cdc_cdc_fifo_out_payload_prot;
assign slave_ar_cdc_cdc_asyncfifo_re = slave_ar_cdc_cdc_source_ready;
assign slave_ar_cdc_cdc_graycounter0_ce = (slave_ar_cdc_cdc_asyncfifo_writable & slave_ar_cdc_cdc_asyncfifo_we);
assign slave_ar_cdc_cdc_graycounter1_ce = (slave_ar_cdc_cdc_asyncfifo_readable & slave_ar_cdc_cdc_asyncfifo_re);
assign slave_ar_cdc_cdc_asyncfifo_writable = (((slave_ar_cdc_cdc_graycounter0_q[2] == slave_ar_cdc_cdc_consume_wdomain[2]) | (slave_ar_cdc_cdc_graycounter0_q[1] == slave_ar_cdc_cdc_consume_wdomain[1])) | (slave_ar_cdc_cdc_graycounter0_q[0] != slave_ar_cdc_cdc_consume_wdomain[0]));
assign slave_ar_cdc_cdc_asyncfifo_readable = (slave_ar_cdc_cdc_graycounter1_q != slave_ar_cdc_cdc_produce_rdomain);
assign slave_ar_cdc_cdc_wrport_adr = slave_ar_cdc_cdc_graycounter0_q_binary[1:0];
assign slave_ar_cdc_cdc_wrport_dat_w = slave_ar_cdc_cdc_asyncfifo_din;
assign slave_ar_cdc_cdc_wrport_we = slave_ar_cdc_cdc_graycounter0_ce;
assign slave_ar_cdc_cdc_rdport_adr = slave_ar_cdc_cdc_graycounter1_q_next_binary[1:0];
assign slave_ar_cdc_cdc_asyncfifo_dout = slave_ar_cdc_cdc_rdport_dat_r;
always @(*) begin
    slave_ar_cdc_cdc_graycounter0_q_next_binary = 3'd0;
    if (slave_ar_cdc_cdc_graycounter0_ce) begin
        slave_ar_cdc_cdc_graycounter0_q_next_binary = (slave_ar_cdc_cdc_graycounter0_q_binary + 1'd1);
    end else begin
        slave_ar_cdc_cdc_graycounter0_q_next_binary = slave_ar_cdc_cdc_graycounter0_q_binary;
    end
end
assign slave_ar_cdc_cdc_graycounter0_q_next = (slave_ar_cdc_cdc_graycounter0_q_next_binary ^ slave_ar_cdc_cdc_graycounter0_q_next_binary[2:1]);
always @(*) begin
    slave_ar_cdc_cdc_graycounter1_q_next_binary = 3'd0;
    if (slave_ar_cdc_cdc_graycounter1_ce) begin
        slave_ar_cdc_cdc_graycounter1_q_next_binary = (slave_ar_cdc_cdc_graycounter1_q_binary + 1'd1);
    end else begin
        slave_ar_cdc_cdc_graycounter1_q_next_binary = slave_ar_cdc_cdc_graycounter1_q_binary;
    end
end
assign slave_ar_cdc_cdc_graycounter1_q_next = (slave_ar_cdc_cdc_graycounter1_q_next_binary ^ slave_ar_cdc_cdc_graycounter1_q_next_binary[2:1]);
assign slave_r_cdc_cdc_sink_valid = slave_r_cdc_sink_sink_valid;
assign slave_r_cdc_sink_sink_ready = slave_r_cdc_cdc_sink_ready;
assign slave_r_cdc_cdc_sink_first = slave_r_cdc_sink_sink_first;
assign slave_r_cdc_cdc_sink_last = slave_r_cdc_sink_sink_last;
assign slave_r_cdc_cdc_sink_payload_resp = slave_r_cdc_sink_sink_payload_resp;
assign slave_r_cdc_cdc_sink_payload_data = slave_r_cdc_sink_sink_payload_data;
assign slave_r_cdc_source_source_valid = slave_r_cdc_cdc_source_valid;
assign slave_r_cdc_cdc_source_ready = slave_r_cdc_source_source_ready;
assign slave_r_cdc_source_source_first = slave_r_cdc_cdc_source_first;
assign slave_r_cdc_source_source_last = slave_r_cdc_cdc_source_last;
assign slave_r_cdc_source_source_payload_resp = slave_r_cdc_cdc_source_payload_resp;
assign slave_r_cdc_source_source_payload_data = slave_r_cdc_cdc_source_payload_data;
assign slave_r_cdc_cdc_asyncfifo_din = {slave_r_cdc_cdc_fifo_in_last, slave_r_cdc_cdc_fifo_in_first, slave_r_cdc_cdc_fifo_in_payload_data, slave_r_cdc_cdc_fifo_in_payload_resp};
assign {slave_r_cdc_cdc_fifo_out_last, slave_r_cdc_cdc_fifo_out_first, slave_r_cdc_cdc_fifo_out_payload_data, slave_r_cdc_cdc_fifo_out_payload_resp} = slave_r_cdc_cdc_asyncfifo_dout;
assign slave_r_cdc_cdc_sink_ready = slave_r_cdc_cdc_asyncfifo_writable;
assign slave_r_cdc_cdc_asyncfifo_we = slave_r_cdc_cdc_sink_valid;
assign slave_r_cdc_cdc_fifo_in_first = slave_r_cdc_cdc_sink_first;
assign slave_r_cdc_cdc_fifo_in_last = slave_r_cdc_cdc_sink_last;
assign slave_r_cdc_cdc_fifo_in_payload_resp = slave_r_cdc_cdc_sink_payload_resp;
assign slave_r_cdc_cdc_fifo_in_payload_data = slave_r_cdc_cdc_sink_payload_data;
assign slave_r_cdc_cdc_source_valid = slave_r_cdc_cdc_asyncfifo_readable;
assign slave_r_cdc_cdc_source_first = slave_r_cdc_cdc_fifo_out_first;
assign slave_r_cdc_cdc_source_last = slave_r_cdc_cdc_fifo_out_last;
assign slave_r_cdc_cdc_source_payload_resp = slave_r_cdc_cdc_fifo_out_payload_resp;
assign slave_r_cdc_cdc_source_payload_data = slave_r_cdc_cdc_fifo_out_payload_data;
assign slave_r_cdc_cdc_asyncfifo_re = slave_r_cdc_cdc_source_ready;
assign slave_r_cdc_cdc_graycounter0_ce = (slave_r_cdc_cdc_asyncfifo_writable & slave_r_cdc_cdc_asyncfifo_we);
assign slave_r_cdc_cdc_graycounter1_ce = (slave_r_cdc_cdc_asyncfifo_readable & slave_r_cdc_cdc_asyncfifo_re);
assign slave_r_cdc_cdc_asyncfifo_writable = (((slave_r_cdc_cdc_graycounter0_q[2] == slave_r_cdc_cdc_consume_wdomain[2]) | (slave_r_cdc_cdc_graycounter0_q[1] == slave_r_cdc_cdc_consume_wdomain[1])) | (slave_r_cdc_cdc_graycounter0_q[0] != slave_r_cdc_cdc_consume_wdomain[0]));
assign slave_r_cdc_cdc_asyncfifo_readable = (slave_r_cdc_cdc_graycounter1_q != slave_r_cdc_cdc_produce_rdomain);
assign slave_r_cdc_cdc_wrport_adr = slave_r_cdc_cdc_graycounter0_q_binary[1:0];
assign slave_r_cdc_cdc_wrport_dat_w = slave_r_cdc_cdc_asyncfifo_din;
assign slave_r_cdc_cdc_wrport_we = slave_r_cdc_cdc_graycounter0_ce;
assign slave_r_cdc_cdc_rdport_adr = slave_r_cdc_cdc_graycounter1_q_next_binary[1:0];
assign slave_r_cdc_cdc_asyncfifo_dout = slave_r_cdc_cdc_rdport_dat_r;
assign slave_array_write_memory2_adr = slave_r_cdc_cdc_wrport_adr;
assign slave_array_write_memory2_we = slave_r_cdc_cdc_wrport_we;
assign slave_array_write_memory2_dat_w = slave_r_cdc_cdc_wrport_dat_w[33:0];
assign slave_array_read_memory2_adr = slave_r_cdc_cdc_rdport_adr;
assign slave_array_write_memory3_adr = slave_r_cdc_cdc_wrport_adr;
assign slave_array_write_memory3_we = slave_r_cdc_cdc_wrport_we;
assign slave_array_write_memory3_dat_w = slave_r_cdc_cdc_wrport_dat_w[35:34];
assign slave_array_read_memory3_adr = slave_r_cdc_cdc_rdport_adr;
assign slave_r_cdc_cdc_rdport_dat_r = {slave_array_read_memory3_dat_r, slave_array_read_memory2_dat_r};
always @(*) begin
    slave_r_cdc_cdc_graycounter0_q_next_binary = 3'd0;
    if (slave_r_cdc_cdc_graycounter0_ce) begin
        slave_r_cdc_cdc_graycounter0_q_next_binary = (slave_r_cdc_cdc_graycounter0_q_binary + 1'd1);
    end else begin
        slave_r_cdc_cdc_graycounter0_q_next_binary = slave_r_cdc_cdc_graycounter0_q_binary;
    end
end
assign slave_r_cdc_cdc_graycounter0_q_next = (slave_r_cdc_cdc_graycounter0_q_next_binary ^ slave_r_cdc_cdc_graycounter0_q_next_binary[2:1]);
always @(*) begin
    slave_r_cdc_cdc_graycounter1_q_next_binary = 3'd0;
    if (slave_r_cdc_cdc_graycounter1_ce) begin
        slave_r_cdc_cdc_graycounter1_q_next_binary = (slave_r_cdc_cdc_graycounter1_q_binary + 1'd1);
    end else begin
        slave_r_cdc_cdc_graycounter1_q_next_binary = slave_r_cdc_cdc_graycounter1_q_binary;
    end
end
assign slave_r_cdc_cdc_graycounter1_q_next = (slave_r_cdc_cdc_graycounter1_q_next_binary ^ slave_r_cdc_cdc_graycounter1_q_next_binary[2:1]);
assign tx_cdc_produce_rdomain = multiregimpl01;
assign tx_cdc_consume_wdomain = multiregimpl11;
assign rx_cdc_produce_rdomain = multiregimpl21;
assign rx_cdc_consume_wdomain = multiregimpl31;
assign slave_aw_cdc_cdc_produce_rdomain = multiregimpl41;
assign slave_aw_cdc_cdc_consume_wdomain = multiregimpl51;
assign slave_w_cdc_cdc_produce_rdomain = multiregimpl61;
assign slave_w_cdc_cdc_consume_wdomain = multiregimpl71;
assign slave_b_cdc_cdc_produce_rdomain = multiregimpl81;
assign slave_b_cdc_cdc_consume_wdomain = multiregimpl91;
assign slave_ar_cdc_cdc_produce_rdomain = multiregimpl101;
assign slave_ar_cdc_cdc_consume_wdomain = multiregimpl111;
assign slave_r_cdc_cdc_produce_rdomain = multiregimpl121;
assign slave_r_cdc_cdc_consume_wdomain = multiregimpl131;


//------------------------------------------------------------------------------
// Synchronous Logic
//------------------------------------------------------------------------------

always @(posedge macdp_clk) begin
    tx_cdc_graycounter0_q_binary <= tx_cdc_graycounter0_q_next_binary;
    tx_cdc_graycounter0_q <= tx_cdc_graycounter0_q_next;
    if ((rx_cdc_re | (~rx_cdc_readable))) begin
        rx_cdc_dout <= rx_cdc_asyncfifo_dout;
        rx_cdc_readable <= rx_cdc_asyncfifo_readable;
    end
    rx_cdc_graycounter1_q_binary <= rx_cdc_graycounter1_q_next_binary;
    rx_cdc_graycounter1_q <= rx_cdc_graycounter1_q_next;
    if (macdp_rst) begin
        tx_cdc_graycounter0_q <= 5'd0;
        tx_cdc_graycounter0_q_binary <= 5'd0;
        rx_cdc_readable <= 1'd0;
        rx_cdc_graycounter1_q <= 5'd0;
        rx_cdc_graycounter1_q_binary <= 5'd0;
    end
    multiregimpl10 <= tx_cdc_graycounter1_q;
    multiregimpl11 <= multiregimpl10;
    multiregimpl20 <= rx_cdc_graycounter0_q;
    multiregimpl21 <= multiregimpl20;
end

always @(posedge macsys_clk) begin
    if ((tx_cdc_re | (~tx_cdc_readable))) begin
        tx_cdc_dout <= tx_cdc_asyncfifo_dout;
        tx_cdc_readable <= tx_cdc_asyncfifo_readable;
    end
    tx_cdc_graycounter1_q_binary <= tx_cdc_graycounter1_q_next_binary;
    tx_cdc_graycounter1_q <= tx_cdc_graycounter1_q_next;
    rx_cdc_graycounter0_q_binary <= rx_cdc_graycounter0_q_next_binary;
    rx_cdc_graycounter0_q <= rx_cdc_graycounter0_q_next;
    if (macsys_rst) begin
        tx_cdc_readable <= 1'd0;
        tx_cdc_graycounter1_q <= 5'd0;
        tx_cdc_graycounter1_q_binary <= 5'd0;
        rx_cdc_graycounter0_q <= 5'd0;
        rx_cdc_graycounter0_q_binary <= 5'd0;
    end
    multiregimpl00 <= tx_cdc_graycounter0_q;
    multiregimpl01 <= multiregimpl00;
    multiregimpl30 <= rx_cdc_graycounter1_q;
    multiregimpl31 <= multiregimpl30;
end

always @(posedge milan_clk) begin
    slave_aw_cdc_cdc_graycounter1_q_binary <= slave_aw_cdc_cdc_graycounter1_q_next_binary;
    slave_aw_cdc_cdc_graycounter1_q <= slave_aw_cdc_cdc_graycounter1_q_next;
    slave_w_cdc_cdc_graycounter1_q_binary <= slave_w_cdc_cdc_graycounter1_q_next_binary;
    slave_w_cdc_cdc_graycounter1_q <= slave_w_cdc_cdc_graycounter1_q_next;
    slave_b_cdc_cdc_graycounter0_q_binary <= slave_b_cdc_cdc_graycounter0_q_next_binary;
    slave_b_cdc_cdc_graycounter0_q <= slave_b_cdc_cdc_graycounter0_q_next;
    slave_ar_cdc_cdc_graycounter1_q_binary <= slave_ar_cdc_cdc_graycounter1_q_next_binary;
    slave_ar_cdc_cdc_graycounter1_q <= slave_ar_cdc_cdc_graycounter1_q_next;
    slave_r_cdc_cdc_graycounter0_q_binary <= slave_r_cdc_cdc_graycounter0_q_next_binary;
    slave_r_cdc_cdc_graycounter0_q <= slave_r_cdc_cdc_graycounter0_q_next;
    if (milan_rst) begin
        slave_aw_cdc_cdc_graycounter1_q <= 3'd0;
        slave_aw_cdc_cdc_graycounter1_q_binary <= 3'd0;
        slave_w_cdc_cdc_graycounter1_q <= 3'd0;
        slave_w_cdc_cdc_graycounter1_q_binary <= 3'd0;
        slave_b_cdc_cdc_graycounter0_q <= 3'd0;
        slave_b_cdc_cdc_graycounter0_q_binary <= 3'd0;
        slave_ar_cdc_cdc_graycounter1_q <= 3'd0;
        slave_ar_cdc_cdc_graycounter1_q_binary <= 3'd0;
        slave_r_cdc_cdc_graycounter0_q <= 3'd0;
        slave_r_cdc_cdc_graycounter0_q_binary <= 3'd0;
    end
    multiregimpl40 <= slave_aw_cdc_cdc_graycounter0_q;
    multiregimpl41 <= multiregimpl40;
    multiregimpl60 <= slave_w_cdc_cdc_graycounter0_q;
    multiregimpl61 <= multiregimpl60;
    multiregimpl90 <= slave_b_cdc_cdc_graycounter1_q;
    multiregimpl91 <= multiregimpl90;
    multiregimpl100 <= slave_ar_cdc_cdc_graycounter0_q;
    multiregimpl101 <= multiregimpl100;
    multiregimpl130 <= slave_r_cdc_cdc_graycounter1_q;
    multiregimpl131 <= multiregimpl130;
end

always @(posedge sys_clk) begin
    slave_aw_cdc_cdc_graycounter0_q_binary <= slave_aw_cdc_cdc_graycounter0_q_next_binary;
    slave_aw_cdc_cdc_graycounter0_q <= slave_aw_cdc_cdc_graycounter0_q_next;
    slave_w_cdc_cdc_graycounter0_q_binary <= slave_w_cdc_cdc_graycounter0_q_next_binary;
    slave_w_cdc_cdc_graycounter0_q <= slave_w_cdc_cdc_graycounter0_q_next;
    slave_b_cdc_cdc_graycounter1_q_binary <= slave_b_cdc_cdc_graycounter1_q_next_binary;
    slave_b_cdc_cdc_graycounter1_q <= slave_b_cdc_cdc_graycounter1_q_next;
    slave_ar_cdc_cdc_graycounter0_q_binary <= slave_ar_cdc_cdc_graycounter0_q_next_binary;
    slave_ar_cdc_cdc_graycounter0_q <= slave_ar_cdc_cdc_graycounter0_q_next;
    slave_r_cdc_cdc_graycounter1_q_binary <= slave_r_cdc_cdc_graycounter1_q_next_binary;
    slave_r_cdc_cdc_graycounter1_q <= slave_r_cdc_cdc_graycounter1_q_next;
    if (sys_rst) begin
        slave_aw_cdc_cdc_graycounter0_q <= 3'd0;
        slave_aw_cdc_cdc_graycounter0_q_binary <= 3'd0;
        slave_w_cdc_cdc_graycounter0_q <= 3'd0;
        slave_w_cdc_cdc_graycounter0_q_binary <= 3'd0;
        slave_b_cdc_cdc_graycounter1_q <= 3'd0;
        slave_b_cdc_cdc_graycounter1_q_binary <= 3'd0;
        slave_ar_cdc_cdc_graycounter0_q <= 3'd0;
        slave_ar_cdc_cdc_graycounter0_q_binary <= 3'd0;
        slave_r_cdc_cdc_graycounter1_q <= 3'd0;
        slave_r_cdc_cdc_graycounter1_q_binary <= 3'd0;
    end
    multiregimpl50 <= slave_aw_cdc_cdc_graycounter1_q;
    multiregimpl51 <= multiregimpl50;
    multiregimpl70 <= slave_w_cdc_cdc_graycounter1_q;
    multiregimpl71 <= multiregimpl70;
    multiregimpl80 <= slave_b_cdc_cdc_graycounter0_q;
    multiregimpl81 <= multiregimpl80;
    multiregimpl110 <= slave_ar_cdc_cdc_graycounter1_q;
    multiregimpl111 <= multiregimpl110;
    multiregimpl120 <= slave_r_cdc_cdc_graycounter0_q;
    multiregimpl121 <= multiregimpl120;
end


//------------------------------------------------------------------------------
// Specialized Logic
//------------------------------------------------------------------------------

(* ram_style = "block" *)
//------------------------------------------------------------------------------
// Memory storage: 16-words x 72-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Read-First 
// Port 1 | Read: Sync  | Write: ---- | 
reg [71:0] storage[0:15];
reg [71:0] storage_dat0;
reg [71:0] storage_dat1;
always @(posedge macdp_clk) begin
	if (array_write_memory0_we)
		storage[array_write_memory0_adr] <= array_write_memory0_dat_w;
	storage_dat0 <= storage[array_write_memory0_adr];
end
always @(posedge macsys_clk) begin
	storage_dat1 <= storage[array_read_memory0_adr];
end
assign array_write_memory0_dat_r = storage_dat0;
assign array_read_memory0_dat_r = storage_dat1;


(* ram_style = "distributed" *)
//------------------------------------------------------------------------------
// Memory storage_1: 16-words x 2-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Read-First 
// Port 1 | Read: Sync  | Write: ---- | 
reg [1:0] storage_1[0:15];
reg [1:0] storage_1_dat0;
reg [1:0] storage_1_dat1;
always @(posedge macdp_clk) begin
	if (array_write_memory1_we)
		storage_1[array_write_memory1_adr] <= array_write_memory1_dat_w;
	storage_1_dat0 <= storage_1[array_write_memory1_adr];
end
always @(posedge macsys_clk) begin
	storage_1_dat1 <= storage_1[array_read_memory1_adr];
end
assign array_write_memory1_dat_r = storage_1_dat0;
assign array_read_memory1_dat_r = storage_1_dat1;


(* ram_style = "block" *)
//------------------------------------------------------------------------------
// Memory storage_2: 16-words x 72-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Read-First 
// Port 1 | Read: Sync  | Write: ---- | 
reg [71:0] storage_2[0:15];
reg [71:0] storage_2_dat0;
reg [71:0] storage_2_dat1;
always @(posedge macsys_clk) begin
	if (array_write_memory2_we)
		storage_2[array_write_memory2_adr] <= array_write_memory2_dat_w;
	storage_2_dat0 <= storage_2[array_write_memory2_adr];
end
always @(posedge macdp_clk) begin
	storage_2_dat1 <= storage_2[array_read_memory2_adr];
end
assign array_write_memory2_dat_r = storage_2_dat0;
assign array_read_memory2_dat_r = storage_2_dat1;


(* ram_style = "distributed" *)
//------------------------------------------------------------------------------
// Memory storage_3: 16-words x 2-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Read-First 
// Port 1 | Read: Sync  | Write: ---- | 
reg [1:0] storage_3[0:15];
reg [1:0] storage_3_dat0;
reg [1:0] storage_3_dat1;
always @(posedge macsys_clk) begin
	if (array_write_memory3_we)
		storage_3[array_write_memory3_adr] <= array_write_memory3_dat_w;
	storage_3_dat0 <= storage_3[array_write_memory3_adr];
end
always @(posedge macdp_clk) begin
	storage_3_dat1 <= storage_3[array_read_memory3_adr];
end
assign array_write_memory3_dat_r = storage_3_dat0;
assign array_read_memory3_dat_r = storage_3_dat1;


//------------------------------------------------------------------------------
// Memory storage_4: 4-words x 37-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Read-First 
// Port 1 | Read: Sync  | Write: ---- | 
reg [36:0] storage_4[0:3];
reg [36:0] storage_4_dat0;
reg [36:0] storage_4_dat1;
always @(posedge sys_clk) begin
	if (slave_aw_cdc_cdc_wrport_we)
		storage_4[slave_aw_cdc_cdc_wrport_adr] <= slave_aw_cdc_cdc_wrport_dat_w;
	storage_4_dat0 <= storage_4[slave_aw_cdc_cdc_wrport_adr];
end
always @(posedge milan_clk) begin
	storage_4_dat1 <= storage_4[slave_aw_cdc_cdc_rdport_adr];
end
assign slave_aw_cdc_cdc_wrport_dat_r = storage_4_dat0;
assign slave_aw_cdc_cdc_rdport_dat_r = storage_4_dat1;


//------------------------------------------------------------------------------
// Memory storage_5: 4-words x 4-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Read-First 
// Port 1 | Read: Sync  | Write: ---- | 
reg [3:0] storage_5[0:3];
reg [3:0] storage_5_dat0;
reg [3:0] storage_5_dat1;
always @(posedge milan_clk) begin
	if (slave_b_cdc_cdc_wrport_we)
		storage_5[slave_b_cdc_cdc_wrport_adr] <= slave_b_cdc_cdc_wrport_dat_w;
	storage_5_dat0 <= storage_5[slave_b_cdc_cdc_wrport_adr];
end
always @(posedge sys_clk) begin
	storage_5_dat1 <= storage_5[slave_b_cdc_cdc_rdport_adr];
end
assign slave_b_cdc_cdc_wrport_dat_r = storage_5_dat0;
assign slave_b_cdc_cdc_rdport_dat_r = storage_5_dat1;


//------------------------------------------------------------------------------
// Memory storage_6: 4-words x 37-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Read-First 
// Port 1 | Read: Sync  | Write: ---- | 
reg [36:0] storage_6[0:3];
reg [36:0] storage_6_dat0;
reg [36:0] storage_6_dat1;
always @(posedge sys_clk) begin
	if (slave_ar_cdc_cdc_wrport_we)
		storage_6[slave_ar_cdc_cdc_wrport_adr] <= slave_ar_cdc_cdc_wrport_dat_w;
	storage_6_dat0 <= storage_6[slave_ar_cdc_cdc_wrport_adr];
end
always @(posedge milan_clk) begin
	storage_6_dat1 <= storage_6[slave_ar_cdc_cdc_rdport_adr];
end
assign slave_ar_cdc_cdc_wrport_dat_r = storage_6_dat0;
assign slave_ar_cdc_cdc_rdport_dat_r = storage_6_dat1;


(* ram_style = "block" *)
//------------------------------------------------------------------------------
// Memory storage_7: 4-words x 36-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Read-First 
// Port 1 | Read: Sync  | Write: ---- | 
reg [35:0] storage_7[0:3];
reg [35:0] storage_7_dat0;
reg [35:0] storage_7_dat1;
always @(posedge sys_clk) begin
	if (slave_array_write_memory0_we)
		storage_7[slave_array_write_memory0_adr] <= slave_array_write_memory0_dat_w;
	storage_7_dat0 <= storage_7[slave_array_write_memory0_adr];
end
always @(posedge milan_clk) begin
	storage_7_dat1 <= storage_7[slave_array_read_memory0_adr];
end
assign slave_array_write_memory0_dat_r = storage_7_dat0;
assign slave_array_read_memory0_dat_r = storage_7_dat1;


(* ram_style = "distributed" *)
//------------------------------------------------------------------------------
// Memory storage_8: 4-words x 2-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Read-First 
// Port 1 | Read: Sync  | Write: ---- | 
reg [1:0] storage_8[0:3];
reg [1:0] storage_8_dat0;
reg [1:0] storage_8_dat1;
always @(posedge sys_clk) begin
	if (slave_array_write_memory1_we)
		storage_8[slave_array_write_memory1_adr] <= slave_array_write_memory1_dat_w;
	storage_8_dat0 <= storage_8[slave_array_write_memory1_adr];
end
always @(posedge milan_clk) begin
	storage_8_dat1 <= storage_8[slave_array_read_memory1_adr];
end
assign slave_array_write_memory1_dat_r = storage_8_dat0;
assign slave_array_read_memory1_dat_r = storage_8_dat1;


(* ram_style = "block" *)
//------------------------------------------------------------------------------
// Memory storage_9: 4-words x 34-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Read-First 
// Port 1 | Read: Sync  | Write: ---- | 
reg [33:0] storage_9[0:3];
reg [33:0] storage_9_dat0;
reg [33:0] storage_9_dat1;
always @(posedge milan_clk) begin
	if (slave_array_write_memory2_we)
		storage_9[slave_array_write_memory2_adr] <= slave_array_write_memory2_dat_w;
	storage_9_dat0 <= storage_9[slave_array_write_memory2_adr];
end
always @(posedge sys_clk) begin
	storage_9_dat1 <= storage_9[slave_array_read_memory2_adr];
end
assign slave_array_write_memory2_dat_r = storage_9_dat0;
assign slave_array_read_memory2_dat_r = storage_9_dat1;


(* ram_style = "distributed" *)
//------------------------------------------------------------------------------
// Memory storage_10: 4-words x 2-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Read-First 
// Port 1 | Read: Sync  | Write: ---- | 
reg [1:0] storage_10[0:3];
reg [1:0] storage_10_dat0;
reg [1:0] storage_10_dat1;
always @(posedge milan_clk) begin
	if (slave_array_write_memory3_we)
		storage_10[slave_array_write_memory3_adr] <= slave_array_write_memory3_dat_w;
	storage_10_dat0 <= storage_10[slave_array_write_memory3_adr];
end
always @(posedge sys_clk) begin
	storage_10_dat1 <= storage_10[slave_array_read_memory3_adr];
end
assign slave_array_write_memory3_dat_r = storage_10_dat0;
assign slave_array_read_memory3_dat_r = storage_10_dat1;


endmodule

// -----------------------------------------------------------------------------
//  Auto-Generated by LiteX on 2026-10-10 14:05:48.
//------------------------------------------------------------------------------

