# SPDX-FileCopyrightText: 2026 Kebag Logic
# SPDX-License-Identifier: CERN-OHL-W-2.0
"""Emit the SystemVerilog package, the C header and the reference page.

Each emitter writes every entry of ``mailbox_model.constants()`` under the
same name: ``MBX_<name>_C`` in SystemVerilog, ``MBX_<name>`` in C and in the
page's constant table. The per-channel tables the RTL and the host model index
at run time are built from those names, never from the numbers again, so a
table cannot disagree with the constant it lists.
"""

from __future__ import annotations

from mailbox_model import Channel, Constant, Contract, Field, Register, Word, constants

SOURCE = "sw/mailbox/mailbox.yaml"
GENERATOR = "sw/mailbox/gen_mailbox.py"

#: Per-channel tables: (table name, per-channel constant suffix).
CHANNEL_TABLES = (
    ("CH_RX_BASE_TBL", "RX_BASE"), ("CH_RX_WORDS_TBL", "RX_WORDS"),
    ("CH_TX_BASE_TBL", "TX_BASE"), ("CH_TX_WORDS_TBL", "TX_WORDS"),
    ("CH_MAX_FRAME_BYTES_TBL", "MAX_FRAME_BYTES"),
    ("CH_RATE_BURST_TBL", "RATE_BURST"), ("CH_RATE_REFILL_MS_TBL", "RATE_REFILL_MS"),
)

#: Flattened match-tuple tables, indexed channel * MAX_TUPLES + tuple.
TUPLE_TABLES = (("TUPLE_DST_TBL", "DST"), ("TUPLE_DST_HI_TBL", "DST_HI"), ("TUPLE_DST_LO_TBL", "DST_LO"),
                ("TUPLE_ETHERTYPE_TBL", "ETHERTYPE"), ("TUPLE_HAS_SUBTYPE_TBL", "HAS_SUBTYPE"),
                ("TUPLE_SUBTYPE_TBL", "SUBTYPE"), ("TUPLE_MSG_MASK_TBL", "MSG_MASK"))

#: Flattened accept-term tables, indexed channel * MAX_TERMS + term.
TERM_TABLES = (("TERM_TEST_TBL", "TEST"), ("TERM_OFFSET_TBL", "OFFSET"), ("TERM_MASK_TBL", "MSG_MASK"))

#: Each table family's SystemVerilog size and index, by its name's prefix.
TABLE_SHAPES = {"CH_": ("MBX_N_CH_C", "channel id"),
                "TUPLE_": ("MBX_N_CH_C * MBX_MAX_TUPLES_C", "channel id * MAX_TUPLES + tuple"),
                "TERM_": ("MBX_N_CH_C * MBX_MAX_TERMS_C", "channel id * MAX_TERMS + term")}


def derived(contract: Contract) -> list[Constant]:
    """The widths the RTL needs, derived from the contract's sizes."""
    rings = [contract.evt_words] + [w for ch in contract.channels for w in (ch.rx_words, ch.tx_words)]
    return [
        Constant("IF_W", max(1, (contract.interfaces - 1).bit_length()), "interface index bits", False),
        Constant("CH_W", max(1, (len(contract.channels) - 1).bit_length()), "channel index bits", False),
        Constant("RING_AW", (max(rings) - 1).bit_length(), "widest ring word index", False),
        Constant("ADDR_W", (contract.window_bytes // 4 - 1).bit_length(), "window word address bits", False),
        Constant("FRAME_BYTES_MAX", max(ch.max_frame_bytes for ch in contract.channels),
                 "the largest max_frame_bytes of any channel", False),
    ]


def all_constants(contract: Contract) -> list[Constant]:
    """The contract's constants and the derived widths, in output order."""
    return constants(contract) + derived(contract)


def _num(c: Constant, sv: bool) -> str:
    """A constant's value as the target language writes it."""
    if sv:
        return f"32'h{c.value:08X}" if c.hexa else f"32'd{c.value}"
    return f"0x{c.value:X}u" if c.hexa else f"{c.value}u"


def _tables(contract: Contract) -> list[tuple[str, list[str]]]:
    """(table name, member constant names) for every run-time table."""
    out: list[tuple[str, list[str]]] = []
    for table, suffix in CHANNEL_TABLES:
        out.append((table, [f"CH_{ch.name.upper()}_{suffix}" for ch in contract.channels]))
    for table, suffix in TUPLE_TABLES:
        out.append((table, [f"CH_{ch.name.upper()}_M{k}_{suffix}"
                            for ch in contract.channels for k in range(contract.max_tuples)]))
    for table, suffix in TERM_TABLES:
        out.append((table, [f"CH_{ch.name.upper()}_T{k}_{suffix}"
                            for ch in contract.channels for k in range(contract.max_terms)]))
    return out


def _header_lines(path: str, comment: str) -> list[str]:
    """The banner every generated file opens with, in its comment syntax."""
    return [
        f"{comment} SPDX-FileCopyrightText: 2026 Kebag Logic",
        f"{comment} SPDX-License-Identifier: CERN-OHL-W-2.0",
        f"{comment}",
        f"{comment} GENERATED by {GENERATOR} from {SOURCE}; DO NOT EDIT.",
        f"{comment} Regenerate with: python3 {GENERATOR} --write",
        f"{comment}",
        f"{comment} {path}: the packet-mailbox contract (#665 lane F0).",
    ]


def emit_sv_package(contract: Contract) -> str:
    """KL_mbx_pkg.sv: every constant and every run-time table."""
    lines = _header_lines("hdl/milan/mailbox/KL_mbx_pkg.sv", "//") + [
        "//",
        "// Every constant is `MBX_<name>_C`, the C header's `MBX_<name>`. The",
        "// tables at the end list those names by channel id, so the RTL can index",
        "// a channel at run time without restating a number.",
        "",
        "`default_nettype none",
        "",
        "package KL_mbx_pkg;",
        "",
    ]
    for c in all_constants(contract):
        lines.append(f"  //! {c.doc}")
        lines.append(f"  localparam int unsigned MBX_{c.name}_C = {_num(c, sv=True)};")
    lines.append("")
    for table, members in _tables(contract):
        size, index = next(shape for prefix, shape in TABLE_SHAPES.items() if table.startswith(prefix))
        body = ", ".join(f"MBX_{m}_C" for m in members)
        lines.append(f"  //! by {index}")
        lines.append(f"  localparam int unsigned MBX_{table}_C [{size}] = '{{{body}}};")
    lines += [
        "",
        "  //! `value` placed into the field [lsb +: width] of a 32-bit word",
        "  function automatic logic [31:0] mbx_place_f(input logic [31:0] value, input int unsigned lsb,",
        "                                              input int unsigned width);",
        "    logic [31:0] mask;",
        "    mask = (width >= 32) ? 32'hFFFF_FFFF : ((32'd1 << width) - 32'd1);",
        "    return (value & mask) << lsb;",
        "  endfunction : mbx_place_f",
        "",
        "  //! the field [lsb +: width] of a 32-bit word",
        "  function automatic logic [31:0] mbx_field_f(input logic [31:0] word, input int unsigned lsb,",
        "                                              input int unsigned width);",
        "    logic [31:0] mask;",
        "    mask = (width >= 32) ? 32'hFFFF_FFFF : ((32'd1 << width) - 32'd1);",
        "    return (word >> lsb) & mask;",
        "  endfunction : mbx_field_f",
        "",
        "endpackage : KL_mbx_pkg", "", "`default_nettype wire", ""]
    return "\n".join(lines)


def emit_c_header(contract: Contract) -> str:
    """mbx_contract.h: every constant and every table initialiser."""
    lines = _header_lines("sw/firmware/ctrl/mbx/mbx_contract.h", "//") + [
        "//",
        "// Every constant is `MBX_<name>`, the SystemVerilog package's",
        "// `MBX_<name>_C`. The *_TBL macros are brace initialisers listing those",
        "// names by channel id, for code that indexes a channel at run time.",
        "",
        "#ifndef MBX_CONTRACT_H",
        "#define MBX_CONTRACT_H",
        "",
    ]
    for c in all_constants(contract):
        lines.append(f"/* {c.doc} */")
        lines.append(f"#define MBX_{c.name} {_num(c, sv=False)}")
    lines.append("")
    for table, members in _tables(contract):
        lines.append(f"#define MBX_{table} {{ {', '.join(f'MBX_{m}' for m in members)} }}")
    lines += ["", "#endif /* MBX_CONTRACT_H */", ""]
    return "\n".join(lines)


def _field_rows(fields: tuple[Field, ...]) -> list[str]:
    """One table row per field: bits, name, meaning."""
    rows = []
    for f in sorted(fields, key=lambda x: -x.lsb):
        bits = f"[{f.lsb + f.width - 1}:{f.lsb}]" if f.width > 1 else f"[{f.lsb}]"
        rows.append(f"| `{bits}` | `{f.name}` | {f.doc} |")
    return rows


def _register_section(title: str, regs: tuple[Register, ...], where: str) -> list[str]:
    """A register block: one table of offsets, then one field table per register."""
    out = [f"### {title}", "", where, "", "| Offset | Register | Access | Meaning |", "|---|---|---|---|"]
    for r in regs:
        out.append(f"| `0x{r.offset:03X}` | `{r.name}` | {r.access} | {r.doc} |")
    out.append("")
    for r in regs:
        out += [f"`{r.name}` fields:", "", "| Bits | Field | Meaning |", "|---|---|---|"]
        out += _field_rows(r.fields) + [""]
    return out


def _word_rows(words: tuple[Word, ...], label: str) -> list[str]:
    """One table row per field of every header word."""
    rows = []
    for w in words:
        for f in sorted(w.fields, key=lambda x: -x.lsb):
            bits = f"[{f.lsb + f.width - 1}:{f.lsb}]" if f.width > 1 else f"[{f.lsb}]"
            rows.append(f"| {label} {w.index} | `{bits}` | `{f.name}` | {f.doc} |")
    return rows


def _mac(value: int) -> str:
    """A 48-bit MAC in the colon form the clauses write."""
    return ":".join(f"{(value >> (8 * (5 - k))) & 0xFF:02X}" for k in range(6))


def _types(mask: int) -> str:
    """The message types a mask names, or `any`."""
    return "any" if mask == 0xFFFF else ", ".join(str(m) for m in range(16) if mask >> m & 1)


def _tuple_rows(contract: Contract) -> list[str]:
    """One row per match tuple: the full tuple a channel classifies on."""
    out = ["| Channel | Tuple | VLAN tag | Destination MAC | EtherType | AVTP subtype | message_type | Why |",
           "|---|---:|---|---|---|---|---|---|"]
    for ch in contract.channels:
        for k, m in enumerate(ch.tuples):
            dst = f"`{_mac(m.mac)}`" if m.dst == "mac" else "own MAC of the arrival interface (`OWN_MAC`)"
            sub = "not read" if m.subtype is None else f"`0x{m.subtype:02X}`"
            out.append(f"| `{ch.name}` | {k} | absent | {dst} | `0x{m.ethertype:04X}` | {sub} "
                       f"| {_types(m.msg_mask)} | {m.doc} |")
    return out + [""]


def _channel_rows(contract: Contract) -> list[str]:
    """The channel table, the tuple table and one rule table per channel."""
    out = ["| Channel | id | receive ring | transmit ring | Max frame | Rate |",
           "|---|---:|---|---|---:|---|"]
    for ch in contract.channels:
        out.append(f"| `{ch.name}` | {ch.ident} | `0x{ch.rx_base:04X}`, {ch.rx_words} words "
                   f"| `0x{ch.tx_base:04X}`, {ch.tx_words} words | {ch.max_frame_bytes} "
                   f"| burst {ch.burst}, one token per {ch.refill_ms} ms |")
    out.append("")
    out += _tuple_rows(contract)
    for ch in contract.channels:
        out += [f"`{ch.name}` accepts a frame when one term holds ({ch.cite}):", "",
                "| Term | Test | Wire byte | message_type | Field | Why |", "|---|---|---:|---|---|---|"]
        for k, t in enumerate(ch.terms):
            out.append(f"| {k} | `{t.test}` | {t.offset} | {_types(t.msg_mask)} | `{t.field}` | {t.doc} |")
        out.append("")
    return out


def _intro(contract: Contract) -> list[str]:
    """The page's opening: banner, purpose and the byte-order statement."""
    return [
        "<!-- SPDX-License-Identifier: CERN-OHL-W-2.0 -->",
        "# Packet mailbox contract, generated reference",
        "",
        f"**GENERATED** by `{GENERATOR}` from `{SOURCE}`; do not hand-edit.",
        f"Regenerate with `python3 {GENERATOR} --write`.",
        "",
        "The design page is [MAILBOX_SPLIT.md](../design/MAILBOX_SPLIT.md).",
        f"This page is contract version {contract.major}.{contract.minor}.",
        "",
        "## Byte order",
        "",
        "- Every register, record header word and event word is one 32-bit value.",
        "- A field sits at the bit positions below, whatever the host's byte order.",
        "- Frame bytes travel four to a ring word, in little-endian lanes.",
        "- Frame byte k is in ring word k/4, at bits 8*(k%4)+7 down to 8*(k%4).",
        "- Wire fields inside a frame keep network (big-endian) order.",
        "- The bus carries 32-bit accesses only; a partial write is refused.",
        "",
    ]


def emit_doc(contract: Contract) -> str:
    """MAILBOX_CONTRACT.md: the human tables and the machine-checked constant table."""
    lines = _intro(contract)
    lines += ["## Registers", ""]
    lines += _register_section("Global registers", contract.registers,
                               "Byte offsets from the window base.")
    lines += _register_section(
        "Interface registers", contract.if_registers,
        f"Interface i's block starts at `0x{contract.if_base:03X} + 0x{contract.if_stride:X} * i`.")
    lines += _register_section(
        "Interface filter registers", contract.iff_registers,
        f"Interface i's filter block starts at `0x{contract.iff_base:03X} + 0x{contract.iff_stride:X} * i`.")
    lines += _register_section(
        "Interface bound-talker registers", contract.bnd_registers,
        f"Interface i's bound-talker table starts at `0x{contract.bnd_base:03X} + 0x{contract.bnd_stride:X} * i`, "
        f"and its entry e at `0x{contract.bnd_entry_stride:X} * e` inside it, for {contract.bound_talkers} entries "
        "(one per listener stream). An `eq_bound` term reads the table of the interface the frame arrived on.")
    lines += _register_section(
        "Channel registers", contract.ch_registers,
        f"Channel c's block starts at `0x{contract.ch_base:03X} + 0x{contract.ch_stride:X} * c`.")
    lines += ["## Records", "", contract.rx_doc, "", contract.tx_doc, "", contract.ev_doc, "",
              "| Record | Word | Bits | Field | Meaning |", "|---|---|---|---|---|"]
    lines += [f"| RX frame | {r[2:]}" for r in _word_rows(contract.rx_header, "word")]
    lines += [f"| TX frame | {r[2:]}" for r in _word_rows(contract.tx_header, "word")]
    lines += [f"| event | {r[2:]}" for r in _word_rows(contract.ev_header, "word")]
    for etype in contract.event_types:
        lines += [f"| {etype.name} event | {r[2:]}" for r in _word_rows(etype.words, "word")]
    lines += ["", "An RX or TX record is the header words, then ceil(LEN/4) payload words.", "",
              "| Event | TYPE | Meaning |", "|---|---:|---|"]
    lines += [f"| `{e.name}` | {e.value} | {e.doc} |" for e in contract.event_types]
    tpids = ", ".join(f"`0x{t:04X}`" for t in contract.tpids)
    lines += ["", "## Channels and the ingress filter", "",
              f"A frame is classified when its byte {contract.msg_type_byte} arrives, by its full tuple,",
              f"or at its last byte when it ends at byte {contract.subtype_byte}.",
              "A channel's tuple holds when the destination MAC is the tuple's address,",
              "or, for an `own` tuple, `OWN_MAC` of the interface the frame arrived on;",
              "the EtherType is the tuple's; the AVTP subtype is the tuple's where it names one;",
              f"and the message_type (the low nibble of byte {contract.msg_type_byte}, 0 when the frame ends",
              f"at byte {contract.subtype_byte}) is one of the tuple's where it names some.",
              "The frame passes when its channel is open and one accept term (the identity term) holds.",
              "It must also fit max_frame_bytes and the free ring space.",
              "Then the channel's token bucket must hold a token.", "",
              f"Untagged frames only, by construction: a VLAN tag's TPID ({tpids}) sits where the",
              "EtherType is read, and no tuple names one, so a tagged frame reaches no channel",
              "and no counter. An untagged frame whose EtherType some tuple names, matching no tuple,",
              "counts once in `FILTER_MISMATCH`. A frame failing its identity term is dropped uncounted.",
              f"A frame that ends before byte {contract.subtype_byte} is classified into nothing and counted nowhere.",
              ""]
    lines += _channel_rows(contract)
    lines += ["| Destination | Value | Holds when |", "|---|---:|---|"]
    lines += [f"| `{name}` | {value} | {doc} |" for name, value, doc in contract.dsts]
    lines += ["", "| Test | Value | Holds when |", "|---|---:|---|"]
    lines += [f"| `{name}` | {value} | {doc} |" for name, value, doc in contract.tests]
    lines += ["", "## Constants", "",
              "Every constant below is `MBX_<name>` in C and `MBX_<name>_C` in SystemVerilog.",
              "`gen_mailbox.py --selftest` reads this table back.", "",
              "| Name | Value |", "|---|---:|"]
    lines += [f"| `MBX_{c.name}` | `{c.value:#x}` |" for c in all_constants(contract)]
    lines.append("")
    return "\n".join(lines)


def channel_names(contract: Contract) -> list[Channel]:
    """The channels in id order, for the skeleton emitter."""
    return list(contract.channels)
