# SPDX-FileCopyrightText: 2026 Kebag Logic
# SPDX-License-Identifier: CERN-OHL-W-2.0
"""Emit the SystemVerilog package, the C header and the reference page.

Each emitter writes every entry of ``mailbox_model.constants()`` under the
same name: ``MBX_<name>_C`` in SystemVerilog, ``MBX_<name>`` in C and in the
page's constant table. The per-channel tables the RTL and the host model index
at run time are built from those names, never from the numbers again, so a
table cannot disagree with the constant it lists.
"""

from __future__ import annotations

from mailbox_model import Channel, Constant, Contract, Field, Register, Word, constants

SOURCE = "sw/mailbox/mailbox.yaml"
GENERATOR = "sw/mailbox/gen_mailbox.py"

#: Per-channel tables: (table name, per-channel constant suffix).
CHANNEL_TABLES = (
    ("CH_RX_BASE_TBL", "RX_BASE"), ("CH_RX_WORDS_TBL", "RX_WORDS"),
    ("CH_TX_BASE_TBL", "TX_BASE"), ("CH_TX_WORDS_TBL", "TX_WORDS"),
    ("CH_MAX_FRAME_BYTES_TBL", "MAX_FRAME_BYTES"),
    ("CH_ETHERTYPE0_TBL", "ETHERTYPE0"), ("CH_ETHERTYPE1_TBL", "ETHERTYPE1"),
    ("CH_HAS_SUBTYPE_TBL", "HAS_SUBTYPE"), ("CH_SUBTYPE_TBL", "SUBTYPE"),
    ("CH_RATE_BURST_TBL", "RATE_BURST"), ("CH_RATE_REFILL_MS_TBL", "RATE_REFILL_MS"),
)

#: Flattened accept-term tables, indexed channel * MAX_TERMS + term.
TERM_TABLES = (("TERM_TEST_TBL", "TEST"), ("TERM_OFFSET_TBL", "OFFSET"), ("TERM_MASK_TBL", "MSG_MASK"))


def derived(contract: Contract) -> list[Constant]:
    """The widths the RTL needs, derived from the contract's sizes."""
    rings = [contract.evt_words] + [w for ch in contract.channels for w in (ch.rx_words, ch.tx_words)]
    return [
        Constant("IF_W", max(1, (contract.interfaces - 1).bit_length()), "interface index bits", False),
        Constant("CH_W", max(1, (len(contract.channels) - 1).bit_length()), "channel index bits", False),
        Constant("RING_AW", (max(rings) - 1).bit_length(), "widest ring word index", False),
        Constant("ADDR_W", (contract.window_bytes // 4 - 1).bit_length(), "window word address bits", False),
        Constant("FRAME_BYTES_MAX", max(ch.max_frame_bytes for ch in contract.channels),
                 "the largest max_frame_bytes of any channel", False),
    ]


def all_constants(contract: Contract) -> list[Constant]:
    """The contract's constants and the derived widths, in output order."""
    return constants(contract) + derived(contract)


def _num(c: Constant, sv: bool) -> str:
    """A constant's value as the target language writes it."""
    if sv:
        return f"32'h{c.value:08X}" if c.hexa else f"32'd{c.value}"
    return f"0x{c.value:X}u" if c.hexa else f"{c.value}u"


def _tables(contract: Contract) -> list[tuple[str, list[str]]]:
    """(table name, member constant names) for every run-time table."""
    out: list[tuple[str, list[str]]] = []
    for table, suffix in CHANNEL_TABLES:
        out.append((table, [f"CH_{ch.name.upper()}_{suffix}" for ch in contract.channels]))
    for table, suffix in TERM_TABLES:
        out.append((table, [f"CH_{ch.name.upper()}_T{k}_{suffix}"
                            for ch in contract.channels for k in range(contract.max_terms)]))
    return out


def _header_lines(path: str, comment: str) -> list[str]:
    """The banner every generated file opens with, in its comment syntax."""
    return [
        f"{comment} SPDX-FileCopyrightText: 2026 Kebag Logic",
        f"{comment} SPDX-License-Identifier: CERN-OHL-W-2.0",
        f"{comment}",
        f"{comment} GENERATED by {GENERATOR} from {SOURCE}; DO NOT EDIT.",
        f"{comment} Regenerate with: python3 {GENERATOR} --write",
        f"{comment}",
        f"{comment} {path}: the packet-mailbox contract (#665 lane F0).",
    ]


def emit_sv_package(contract: Contract) -> str:
    """KL_mbx_pkg.sv: every constant and every run-time table."""
    lines = _header_lines("hdl/milan/mailbox/KL_mbx_pkg.sv", "//") + [
        "//",
        "// Every constant is `MBX_<name>_C`, the C header's `MBX_<name>`. The",
        "// tables at the end list those names by channel id, so the RTL can index",
        "// a channel at run time without restating a number.",
        "",
        "`default_nettype none",
        "",
        "package KL_mbx_pkg;",
        "",
    ]
    for c in all_constants(contract):
        lines.append(f"  //! {c.doc}")
        lines.append(f"  localparam int unsigned MBX_{c.name}_C = {_num(c, sv=True)};")
    lines.append("")
    for table, members in _tables(contract):
        size = "MBX_N_CH_C" if table.startswith("CH_") else "MBX_N_CH_C * MBX_MAX_TERMS_C"
        body = ", ".join(f"MBX_{m}_C" for m in members)
        lines.append(f"  //! by {'channel id' if table.startswith('CH_') else 'channel id * MAX_TERMS + term'}")
        lines.append(f"  localparam int unsigned MBX_{table}_C [{size}] = '{{{body}}};")
    lines += [
        "",
        "  //! `value` placed into the field [lsb +: width] of a 32-bit word",
        "  function automatic logic [31:0] mbx_place_f(input logic [31:0] value, input int unsigned lsb,",
        "                                              input int unsigned width);",
        "    logic [31:0] mask;",
        "    mask = (width >= 32) ? 32'hFFFF_FFFF : ((32'd1 << width) - 32'd1);",
        "    return (value & mask) << lsb;",
        "  endfunction : mbx_place_f",
        "",
        "  //! the field [lsb +: width] of a 32-bit word",
        "  function automatic logic [31:0] mbx_field_f(input logic [31:0] word, input int unsigned lsb,",
        "                                              input int unsigned width);",
        "    logic [31:0] mask;",
        "    mask = (width >= 32) ? 32'hFFFF_FFFF : ((32'd1 << width) - 32'd1);",
        "    return (word >> lsb) & mask;",
        "  endfunction : mbx_field_f",
        "",
        "endpackage : KL_mbx_pkg", "", "`default_nettype wire", ""]
    return "\n".join(lines)


def emit_c_header(contract: Contract) -> str:
    """mbx_contract.h: every constant and every table initialiser."""
    lines = _header_lines("sw/firmware/ctrl/mbx/mbx_contract.h", "//") + [
        "//",
        "// Every constant is `MBX_<name>`, the SystemVerilog package's",
        "// `MBX_<name>_C`. The *_TBL macros are brace initialisers listing those",
        "// names by channel id, for code that indexes a channel at run time.",
        "",
        "#ifndef MBX_CONTRACT_H",
        "#define MBX_CONTRACT_H",
        "",
    ]
    for c in all_constants(contract):
        lines.append(f"/* {c.doc} */")
        lines.append(f"#define MBX_{c.name} {_num(c, sv=False)}")
    lines.append("")
    for table, members in _tables(contract):
        lines.append(f"#define MBX_{table} {{ {', '.join(f'MBX_{m}' for m in members)} }}")
    lines += ["", "#endif /* MBX_CONTRACT_H */", ""]
    return "\n".join(lines)


def _field_rows(fields: tuple[Field, ...]) -> list[str]:
    """One table row per field: bits, name, meaning."""
    rows = []
    for f in sorted(fields, key=lambda x: -x.lsb):
        bits = f"[{f.lsb + f.width - 1}:{f.lsb}]" if f.width > 1 else f"[{f.lsb}]"
        rows.append(f"| `{bits}` | `{f.name}` | {f.doc} |")
    return rows


def _register_section(title: str, regs: tuple[Register, ...], where: str) -> list[str]:
    """A register block: one table of offsets, then one field table per register."""
    out = [f"### {title}", "", where, "", "| Offset | Register | Access | Meaning |", "|---|---|---|---|"]
    for r in regs:
        out.append(f"| `0x{r.offset:03X}` | `{r.name}` | {r.access} | {r.doc} |")
    out.append("")
    for r in regs:
        out += [f"`{r.name}` fields:", "", "| Bits | Field | Meaning |", "|---|---|---|"]
        out += _field_rows(r.fields) + [""]
    return out


def _word_rows(words: tuple[Word, ...], label: str) -> list[str]:
    """One table row per field of every header word."""
    rows = []
    for w in words:
        for f in sorted(w.fields, key=lambda x: -x.lsb):
            bits = f"[{f.lsb + f.width - 1}:{f.lsb}]" if f.width > 1 else f"[{f.lsb}]"
            rows.append(f"| {label} {w.index} | `{bits}` | `{f.name}` | {f.doc} |")
    return rows


def _channel_rows(contract: Contract) -> list[str]:
    """The channel table and one rule table per channel."""
    out = ["| Channel | id | RX ring | TX ring | Max frame | Match | Rate |",
           "|---|---:|---|---|---:|---|---|"]
    for ch in contract.channels:
        match = " or ".join(f"`0x{e:04X}`" for e in ch.ethertypes)
        if ch.subtype is not None:
            match += f", subtype `0x{ch.subtype:02X}`"
        out.append(f"| `{ch.name}` | {ch.ident} | `0x{ch.rx_base:04X}`, {ch.rx_words} words "
                   f"| `0x{ch.tx_base:04X}`, {ch.tx_words} words | {ch.max_frame_bytes} | {match} "
                   f"| burst {ch.burst}, one token per {ch.refill_ms} ms |")
    out.append("")
    for ch in contract.channels:
        out += [f"`{ch.name}` accepts a frame when one term holds ({ch.cite}):", "",
                "| Term | Test | Wire byte | message_type | Field | Why |", "|---|---|---:|---|---|---|"]
        for k, t in enumerate(ch.terms):
            types = "any" if t.msg_mask == 0xFFFF else ", ".join(
                str(m) for m in range(16) if t.msg_mask >> m & 1)
            out.append(f"| {k} | `{t.test}` | {t.offset} | {types} | `{t.field}` | {t.doc} |")
        out.append("")
    return out


def _intro(contract: Contract) -> list[str]:
    """The page's opening: banner, purpose and the byte-order statement."""
    return [
        "<!-- SPDX-License-Identifier: CERN-OHL-W-2.0 -->",
        "# Packet mailbox contract, generated reference",
        "",
        f"**GENERATED** by `{GENERATOR}` from `{SOURCE}`; do not hand-edit.",
        f"Regenerate with `python3 {GENERATOR} --write`.",
        "",
        "The design page is [MAILBOX_SPLIT.md](../design/MAILBOX_SPLIT.md).",
        f"This page is contract version {contract.major}.{contract.minor}.",
        "",
        "## Byte order",
        "",
        "- Every register, record header word and event word is one 32-bit value.",
        "- A field sits at the bit positions below, whatever the host's byte order.",
        "- Frame bytes travel four to a ring word, in little-endian lanes.",
        "- Frame byte k is in ring word k/4, at bits 8*(k%4)+7 down to 8*(k%4).",
        "- Wire fields inside a frame keep network (big-endian) order.",
        "- The bus carries 32-bit accesses only; a partial write is refused.",
        "",
    ]


def emit_doc(contract: Contract) -> str:
    """MAILBOX_CONTRACT.md: the human tables and the machine-checked constant table."""
    lines = _intro(contract)
    lines += ["## Registers", ""]
    lines += _register_section("Global registers", contract.registers,
                               "Byte offsets from the window base.")
    lines += _register_section(
        "Interface registers", contract.if_registers,
        f"Interface i's block starts at `0x{contract.if_base:03X} + 0x{contract.if_stride:X} * i`.")
    lines += _register_section(
        "Channel registers", contract.ch_registers,
        f"Channel c's block starts at `0x{contract.ch_base:03X} + 0x{contract.ch_stride:X} * c`.")
    lines += ["## Records", "", contract.rx_doc, "", contract.tx_doc, "", contract.ev_doc, "",
              "| Record | Word | Bits | Field | Meaning |", "|---|---|---|---|---|"]
    lines += [f"| RX frame | {r[2:]}" for r in _word_rows(contract.rx_header, "word")]
    lines += [f"| TX frame | {r[2:]}" for r in _word_rows(contract.tx_header, "word")]
    lines += [f"| event | {r[2:]}" for r in _word_rows(contract.ev_header, "word")]
    for etype in contract.event_types:
        lines += [f"| {etype.name} event | {r[2:]}" for r in _word_rows(etype.words, "word")]
    lines += ["", "An RX or TX record is the header words, then ceil(LEN/4) payload words.", "",
              "| Event | TYPE | Meaning |", "|---|---:|---|"]
    lines += [f"| `{e.name}` | {e.value} | {e.doc} |" for e in contract.event_types]
    lines += ["", "## Channels and the ingress filter", "",
              "A frame is classified by EtherType, and by AVTP subtype where the channel names one.",
              "It passes when its channel is open and one accept term holds.",
              "It must also fit max_frame_bytes and the free ring space.",
              "Then the channel's token bucket must hold a token.", ""]
    lines += _channel_rows(contract)
    lines += ["| Test | Value | Holds when |", "|---|---:|---|"]
    lines += [f"| `{name}` | {value} | {doc} |" for name, value, doc in contract.tests]
    lines += ["", "## Constants", "",
              "Every constant below is `MBX_<name>` in C and `MBX_<name>_C` in SystemVerilog.",
              "`gen_mailbox.py --selftest` reads this table back.", "",
              "| Name | Value |", "|---|---:|"]
    lines += [f"| `MBX_{c.name}` | `{c.value:#x}` |" for c in all_constants(contract)]
    lines.append("")
    return "\n".join(lines)


def channel_names(contract: Contract) -> list[Channel]:
    """The channels in id order, for the skeleton emitter."""
    return list(contract.channels)
