#!/usr/bin/env python3
"""[R383] Run the committed head probe twice in the CURRENT interpreter/env
(meant for the pins-only env) for one config/port, then compare the two runs
with each other and with a kept local-interpreter head run (from
probe_equiv.py). Tcl/XDC/.v are normalized as probe_equiv.py does; the XDC is
also compared as a sorted line multiset to separate ordering from content.
Usage: pins_vs_local.py <tree> <scratch> <config> <port> <kept local run dir>"""
import os, re, subprocess, sys
from pathlib import Path
tree, scratch, config, port, local = Path(sys.argv[1]).resolve(), Path(sys.argv[2]).resolve(), sys.argv[3], sys.argv[4], Path(sys.argv[5]).resolve()
STAMP = re.compile(r"^(// Date\s+:|//\s+Auto-Generated by LiteX|# Auto-Generated by LiteX).*$", re.M | re.I)
def norm(p, root):
    t = STAMP.sub("<STAMP>", p.read_text().replace(str(root), "<OUT>").replace(str(tree), "<ROOT>"))
    if p.suffix == ".v":
        t = "\n".join(l for l in t.splitlines() if not l.lstrip().startswith("//") and not any(g in l for g in "│├└"))
    return t
runs = []
for i in (1, 2):
    out = scratch / f"pinsrun{i}-{config}-{port}"
    subprocess.run(["rm", "-rf", str(out)], check=True)
    r = subprocess.run([sys.executable, "-B", str(tree / "sw/builder/test_shipping_clock_constraints.py"), "--config", config,
                        "--port", port, "--output-dir", str(out)], cwd=tree / "sw/litex", capture_output=True, text=True,
                       timeout=900, env=dict(os.environ, PYTHONHASHSEED="0"))
    print(f"pins run {i}: rc={r.returncode} {[l[:60] for l in r.stdout.splitlines() if l.startswith('[constraints]')]}")
    runs.append(out)
for name in ("alinx_ax7101.tcl", "alinx_ax7101.xdc", "alinx_ax7101.v"):
    a, b, c = (norm(d / "gateware" / name, d) for d in (runs[0], runs[1], local))
    print(f"{name}: pins1==pins2 {a == b}; pins1==local {a == c}; as sorted lines pins1==local {sorted(a.splitlines()) == sorted(c.splitlines())}")
    if name.endswith(".tcl"):
        hook = lambda t: [l for l in t.splitlines() if l.startswith("milan_eth_constraints ")]
        print(f"  milan_eth_constraints line identical pins1/pins2/local: {hook(a) == hook(b) == hook(c)}")
