import sys, json, hashlib, shutil, runpy, time, subprocess, os
from pathlib import Path
root=Path.cwd().resolve()
scratch=Path(os.environ["MEASURE_DIR"]).resolve()
scratch.mkdir(parents=True,exist_ok=True)
phase, name=sys.argv[1:]
sys.path.insert(0,str(root/'sw/builder'))
sys.path.insert(0,str(root/'sw/litex'))
import endstation_builder as eb
import pythondata_cpu_vexiiriscv
if "VEX_DATA_DIR" in os.environ:
 pythondata_cpu_vexiiriscv.data_location=os.environ["VEX_DATA_DIR"]
result=eb.build(root/'configs'/f'endstation_{name}.yaml',root/'sw/builder/out')
out=scratch/'exports'/name
if out.exists(): shutil.rmtree(out)
argv=result['argv']+['--entity-gen-dir',str(root/'configs/generated'/f'endstation_{name}'), '--output-dir',str(out),'--no-compile-software']
sys.argv=['milan_soc.py',*argv]
# Equal build-time inputs, not normalization of generated bytes.
if phase.endswith('-fixed'):
 time.time = lambda: 1700000000
 # The diagnostic hierarchy sorts Instance objects by their address repr.
 # Stabilize that display input equally; RTL lowering already sorts by duid.
 from migen.fhdl.specials import Instance
 Instance.__repr__ = lambda self: "Instance(%020d)" % self.duid
 source = subprocess.check_output(['git','show','e21c1ca024d37ea188ad15b5c8f9c2dae18628df:sw/litex/milan_soc.py'],cwd=root) if phase == 'baseline-fixed' else (root/'sw/litex/milan_soc.py').read_bytes()
 exec(compile(source,str(root/'sw/litex/milan_soc.py'),'exec'),{'__name__':'__main__','__file__':str(root/'sw/litex/milan_soc.py')})
else:
 runpy.run_path(str(root/'sw/litex/milan_soc.py'),run_name='__main__')
files={}
for prefix,directory in [('export',out),('builder',root/'sw/builder/out'/f'endstation_{name}'),('shape',root/'configs/generated'/f'endstation_{name}')]:
 for p in sorted(directory.rglob('*')):
  if p.is_file() and p.suffix != ".log":
   data=p.read_bytes()
   key=prefix+'/'+str(p.relative_to(directory))
   files[key]={'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()}
   if phase.endswith('-fixed'):
    saved=scratch/'snapshots'/phase/name/key
    saved.parent.mkdir(parents=True,exist_ok=True)
    saved.write_bytes(data)
    if phase=='candidate-fixed':
     assert data==(scratch/'snapshots'/'baseline-fixed'/name/key).read_bytes(), key
assert files and any(k.endswith('.v') for k in files),files
manifest={'config':name,'argv':argv,'files':files}
(scratch/f'{phase}-{name}.json').write_text(json.dumps(manifest,indent=2)+'\n')
if phase in ('candidate','candidate-fixed'):
 previous=json.loads((scratch/f"{'baseline-fixed' if phase.endswith('-fixed') else 'baseline'}-{name}.json").read_text())
 assert previous==manifest, 'generated outputs changed: '+name
print('EXPORT PASS',phase,name,len(files),flush=True)
