#!/usr/bin/env python3
# SPDX-License-Identifier: CERN-OHL-W-2.0
"""Generate a lockstep KL_srp_top for the R458-1 review of milan-fpga #230.

Reads the head KL_srp_top header (parameters and ports), and writes:
  <out>/srp_ref/*.sv   base SRP modules renamed KL_srp_*_ref
  <out>/srp_new/*.sv   head SRP modules renamed KL_srp_*_new
  <out>/KL_srp_top_lockstep.sv
                       a module named KL_srp_top with the head's exact header
                       that instantiates both, drives its outputs from the
                       head copy, and compares every output plus the timer-arm
                       FIFO bookkeeping every cycle after the first reset.
It also counts FIFO boundary events so the run reports what it reached.

usage: gen_top_lockstep.py <base_tree> <head_tree> <out_dir>
"""
import pathlib
import re
import sys

SRP_FILES = ["KL_srp_decoder.sv", "KL_srp_domain.sv", "KL_srp_vlan.sv",
             "KL_srp_talker_fsm.sv", "KL_srp_listener_fsm.sv",
             "KL_srp_admission.sv", "KL_srp_encoder.sv", "KL_srp_top.sv"]
MOD_RE = re.compile(r"\bKL_srp_(decoder|domain|vlan|talker_fsm|listener_fsm|"
                    r"admission|encoder|top)\b")


def rename(src: str, suffix: str) -> str:
    return MOD_RE.sub(lambda m: f"KL_srp_{m.group(1)}_{suffix}", src)


def header(src: str) -> str:
    start = src.index("module KL_srp_top")
    end = src.index("\n);", start) + 3
    return src[start:end]


def ports(hdr: str):
    out = []
    pre = re.compile(r"^\s*(input|output)\s+(?:wire|logic)?\s*((?:\[[^\]]+\])*)"
                     r"\s*(\w+)\s*,?")
    for line in hdr.splitlines():
        m = pre.match(line.split("//")[0])
        if m:
            out.append((m.group(1), m.group(2).strip(), m.group(3)))
    return out


def params(hdr: str):
    return re.findall(r"^\s*parameter\s+[^=]*?(\w+)\s*=", hdr, re.M)


def main() -> int:
    base, head, out = (pathlib.Path(a) for a in sys.argv[1:4])
    for sub, tree, sfx in (("srp_ref", base, "ref"), ("srp_new", head, "new")):
        d = out / sub
        d.mkdir(parents=True, exist_ok=True)
        for f in SRP_FILES:
            src = (tree / "hdl/srp" / f).read_text()
            (d / f.replace(".sv", f"_{sfx}.sv")).write_text(rename(src, sfx))
    hsrc = (head / "hdl/srp/KL_srp_top.sv").read_text()
    hdr = header(hsrc)
    pl = ports(hdr)
    pa = params(hdr)
    outs = [p for p in pl if p[0] == "output"]
    ins = [p for p in pl if p[0] == "input"]
    assert len(outs) == 51, f"expected 51 outputs, found {len(outs)}"
    imports = "\n".join(l for l in hsrc[hsrc.index("module KL_srp_top"):].splitlines()[1:3]
                        if l.strip().startswith("import"))
    L = []
    L.append("// generated by gen_top_lockstep.py (R458-1 review probe, scratch only)")
    L.append("`default_nettype none")
    L.append("/* verilator lint_off MULTIDRIVEN */")
    L.append(hdr.replace("module KL_srp_top", "module KL_srp_top", 1))
    for _, rng, n in outs:
        L.append(f"  logic {rng} {n}__ref;")
    pmap = ",\n".join(f"    .{p}({p})" for p in pa)
    for inst, sfx, tgt in (("u_ref", "ref", "__ref"), ("u_new", "new", "")):
        conns = [f"    .{n}({n})" for _, _, n in ins]
        conns += [f"    .{n}({n}{tgt})" for _, _, n in outs]
        L.append(f"  KL_srp_top_{sfx} #(\n{pmap}\n  ) {inst} (\n" + ",\n".join(conns) + "\n  );")
    # comparison
    L.append("  logic seen_rst_r = 1'b0;")
    L.append("  longint unsigned cyc_r = 0, mis_out_r = 0, mis_int_r = 0;")
    L.append("  longint unsigned c_full[2], c_push_full[2], c_push_pop[2], c_wr_eq_rd[2],"
             " c_push_empty[2], c_pop_last[2], c_wrap[2], c_pop[2], c_push[2];")
    L.append("  int unsigned c_max[2];")
    L.append("  initial begin for (int u = 0; u < 2; u++) begin c_full[u]=0; c_push_full[u]=0;"
             " c_push_pop[u]=0; c_wr_eq_rd[u]=0; c_push_empty[u]=0; c_pop_last[u]=0; c_wrap[u]=0;"
             " c_pop[u]=0; c_push[u]=0; c_max[u]=0; end end")
    L.append("  wire [1:0] arm_v_w = {u_new.ls_arm_v_w, u_new.tk_arm_v_w};")
    L.append("  always @(posedge clk_i) begin : lockstep_cmp")
    L.append("    cyc_r <= cyc_r + 1;")
    L.append("    if (!rst_n) seen_rst_r <= 1'b1;")
    L.append("    if (seen_rst_r) begin")
    for _, _, n in outs:
        L.append(f"      if ({n}__ref != {n}) begin mis_out_r <= mis_out_r + 1;"
                 f" if (mis_out_r < 20) $display(\"LOCKSTEP-MISMATCH out {n} cyc=%0d\", cyc_r); end")
    ints = ["tf_push_w", "tf_pop_w", "tm_st_r", "tm_sel_r", "tm_rr_r",
            "tf_cnt_r[0]", "tf_cnt_r[1]", "tf_wptr_r[0]", "tf_wptr_r[1]",
            "tf_rptr_r[0]", "tf_rptr_r[1]", "tk_arm_v_w", "ls_arm_v_w",
            "u_talker.ev_valid_o", "u_talker.ev_value_o", "u_talker.txop_done_o",
            "u_listener.ev_valid_o", "u_listener.ev_value_o", "u_listener.txop_done_o",
            "u_admission.sr_admitted_o", "u_admission.granted_slope_bps_o",
            "u_admission.round_done_o", "u_admission.sum_slope_bps_o"]
    for s in ints:
        L.append(f"      if (u_ref.{s} != u_new.{s}) begin mis_int_r <= mis_int_r + 1;"
                 f" if (mis_int_r < 20) $display(\"LOCKSTEP-MISMATCH int {s} cyc=%0d\", cyc_r); end")
    # the head word is meaningful only when TM_POP consumes it
    L.append("      if (rst_n && u_new.tm_st_r == 1'b1 && u_ref.tf_q_r[u_new.tm_sel_r] != u_new.tf_q_r[u_new.tm_sel_r]) begin"
             " mis_int_r <= mis_int_r + 1; if (mis_int_r < 20) $display(\"LOCKSTEP-MISMATCH int tf_q_r cyc=%0d\", cyc_r); end")
    L.append("      if (rst_n) for (int u = 0; u < 2; u++) begin")
    L.append("        if (u_new.tf_cnt_r[u] == 6'd32) c_full[u] <= c_full[u] + 1;")
    L.append("        if (arm_v_w[u] && u_new.tf_cnt_r[u] == 6'd32) c_push_full[u] <= c_push_full[u] + 1;")
    L.append("        if (u_new.tf_push_w[u]) c_push[u] <= c_push[u] + 1;")
    L.append("        if (u_new.tf_pop_w[u]) c_pop[u] <= c_pop[u] + 1;")
    L.append("        if (u_new.tf_push_w[u] && u_new.tf_pop_w[u]) c_push_pop[u] <= c_push_pop[u] + 1;")
    L.append("        if (u_new.tf_push_w[u] && u_new.tf_wptr_r[u] == u_new.tf_rptr_r[u]) c_wr_eq_rd[u] <= c_wr_eq_rd[u] + 1;")
    L.append("        if (u_new.tf_push_w[u] && u_new.tf_cnt_r[u] == 6'd0) c_push_empty[u] <= c_push_empty[u] + 1;")
    L.append("        if (u_new.tf_pop_w[u] && u_new.tf_cnt_r[u] == 6'd1) c_pop_last[u] <= c_pop_last[u] + 1;")
    L.append("        if (u_new.tf_push_w[u] && u_new.tf_wptr_r[u] == 5'd31) c_wrap[u] <= c_wrap[u] + 1;")
    L.append("        if (32'(u_new.tf_cnt_r[u]) > c_max[u]) c_max[u] <= 32'(u_new.tf_cnt_r[u]);")
    L.append("      end")
    L.append("    end")
    L.append("  end")
    L.append("  final begin")
    L.append("    $display(\"LOCKSTEP-SUMMARY N_SOURCES=%0d N_SINKS=%0d cycles=%0d mismatching_out=%0d mismatching_int=%0d\","
             " N_SOURCES_P, N_SINKS_P, cyc_r, mis_out_r, mis_int_r);")
    L.append("    for (int u = 0; u < 2; u++)")
    L.append("      $display(\"LOCKSTEP-FIFO%0d push=%0d pop=%0d max=%0d full_cycles=%0d push_at_full=%0d"
             " push_pop_same=%0d write_at_read_ptr=%0d push_empty=%0d pop_last=%0d wptr_wrap=%0d\","
             " u, c_push[u], c_pop[u], c_max[u], c_full[u], c_push_full[u], c_push_pop[u], c_wr_eq_rd[u],"
             " c_push_empty[u], c_pop_last[u], c_wrap[u]);")
    L.append("  end")
    L.append("endmodule")
    L.append("`default_nettype wire")
    (out / "KL_srp_top_lockstep.sv").write_text("\n".join(L) + "\n")
    print(f"ports: {len(ins)} in, {len(outs)} out; params {len(pa)}; internal compares {len(ints) + 1}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
