/*
 * SPDX-FileCopyrightText: 2026 Kebag Logic
 * SPDX-License-Identifier: CERN-OHL-W-2.0
 */
//---------------------------------------------------------------------------//
//  File        : pp_acmp_pkg.sv
//  Project     : IEEE 1722.1 protocol processor (docs/architecture/05)
//
//  Description : ACMP listener types shared by the executor
//                (KL_pp_acmp_listener.sv), the transition-ROM generator
//                contract (rom/gen_ltn_rom.py) and the suite
//                (tb/acmp_listener): the 8 listener SM states and the 14
//                matrix events of F05.3 — the enum codes ARE the ROM
//                geometry, address = {event[3:0], state[2:0]} — the
//                P-ACMP-TROM-W (32-bit) ROM entry layout, the 384-bit
//                F07.6 sink record as ONE packed struct, the A1..A17
//                action-bit positions of the 05 §6.3 legend, the Milan
//                F05.13 ACMPDU constants (message types, flags masks,
//                cdl 44), the IEEE 1722.1-2021 Table 8-3 status codes the
//                listener uses, and the F08.1 ACMP timer constants.
//
//                The one decision that matters: the record and the ROM
//                entry are PACKED SHAPES with fixed field positions (F07.6
//                lane order from bit 0 up; ROM = {next, A-bitmap, VALID,
//                IGN, COND_TK}), so the Python generator, the RTL and the
//                independent C++ matrix model meet at one bit-exact
//                contract instead of three private encodings.
//---------------------------------------------------------------------------//
`default_nettype none

package pp_acmp_pkg;

  // ---- listener SM states (05 §6.1; F05.3 column key order) --------------
  typedef enum logic [2:0] {
    LSM_UNB = 3'd0,  // UNBOUND         (pbsta DISABLED)
    LSM_PWA = 3'd1,  // PRB_W_AVAIL     (pbsta PASSIVE)
    LSM_PWD = 3'd2,  // PRB_W_DELAY     (pbsta ACTIVE)
    LSM_PWR = 3'd3,  // PRB_W_RESP      (pbsta ACTIVE)
    LSM_PW2 = 3'd4,  // PRB_W_RESP2     (pbsta ACTIVE)
    LSM_PWT = 3'd5,  // PRB_W_RETRY     (pbsta ACTIVE)
    LSM_SNR = 3'd6,  // SETTLED_NO_RSV  (pbsta COMPLETED)
    LSM_SOK = 3'd7   // SETTLED_RSV_OK  (pbsta COMPLETED)
  } lsm_state_e;

  // ---- matrix events (F05.3 row order, top to bottom) --------------------
  typedef enum logic [3:0] {
    LEV_BIND_SAME  = 4'd0,   // BIND_RX same talker+source
    LEV_BIND_NEW   = 4'd1,   // BIND_RX new/different source
    LEV_UNBIND     = 4'd2,   // UNBIND_RX
    LEV_GETRX      = 4'd3,   // GET_RX_STATE
    LEV_PROBE_OK   = 4'd4,   // PROBE_TX_RESPONSE status = SUCCESS
    LEV_PROBE_FAIL = 4'd5,   // PROBE_TX_RESPONSE status != SUCCESS
    LEV_TMR_DELAY  = 4'd6,   // T-ACMP-DELAY expiry
    LEV_TMR_CMD    = 4'd7,   // T-ACMP-CMD expiry
    LEV_TMR_RETRY  = 4'd8,   // T-ACMP-RETRY expiry
    LEV_TMR_NOTK   = 4'd9,   // T-ACMP-NOTK expiry
    LEV_TK_DISC    = 4'd10,  // EVT_TK_DISCOVERED
    LEV_TK_DEP     = 4'd11,  // EVT_TK_DEPARTED
    LEV_TK_REG     = 4'd12,  // EVT_TK_REGISTERED (adv or failed)
    LEV_TK_UNREG   = 4'd13   // EVT_TK_UNREGISTERED
  } lsm_event_e;

  // ---- transition-ROM geometry (P-ACMP-TROM-W = 32, F01.5) ---------------
  // Address = {event[3:0], state[2:0]}: 14 x 8 = 112 used cells, 128 deep.
  localparam int unsigned TROM_W_C     = 32;
  localparam int unsigned TROM_AW_C    = 7;
  localparam int unsigned TROM_DEPTH_C = 128;

  // Entry layout (generated by rom/gen_ltn_rom.py, one line per F05.3 cell):
  localparam int unsigned TROM_NEXT_LSB_C = 0;   // [2:0]  next_state
  localparam int unsigned TROM_ACT_LSB_C  = 3;   // [19:3] A1..A17 bitmap
  localparam int unsigned TROM_VALID_B_C  = 20;  // cell defined (0 = F05.3 em-dash)
  localparam int unsigned TROM_IGN_B_C    = 21;  // 'ign' / 'note only' cell (inert)
  localparam int unsigned TROM_COND_B_C   = 22;  // dagger cell: ROM holds the tk
                                                 // arm {next, A12}; executor swaps
                                                 // to {PWA, A17} when tk_disc = 0

  // ---- A1..A17 action bitmap positions (bit i-1 = Ai, 05 §6.3 legend) ----
  localparam int unsigned ACT_A1_C  = 0;   // lock check / abort cell
  localparam int unsigned ACT_A2_C  = 1;   // store binding + NVM mark
  localparam int unsigned ACT_A3_C  = 2;   // BIND_RX_RESPONSE SUCCESS
  localparam int unsigned ACT_A4_C  = 3;   // arm discovery SM; pbsta<-PASSIVE
  localparam int unsigned ACT_A5_C  = 4;   // send PROBE_TX #1; arm T-ACMP-CMD
  localparam int unsigned ACT_A6_C  = 5;   // re-bind short-circuit (ctlr + SW)
  localparam int unsigned ACT_A7_C  = 6;   // UNBIND_RX_RESPONSE SUCCESS
  localparam int unsigned ACT_A8_C  = 7;   // SRP/AVTP teardown; clear settled
  localparam int unsigned ACT_A9_C  = 8;   // disarm discovery SM
  localparam int unsigned ACT_A10_C = 9;   // clear binding + NVM clear
  localparam int unsigned ACT_A11_C = 10;  // stop the active SM timer
  localparam int unsigned ACT_A12_C = 11;  // arm T-ACMP-DELAY (PRNG draw)
  localparam int unsigned ACT_A13_C = 12;  // exact-duplicate probe; arm T-ACMP-CMD
  localparam int unsigned ACT_A14_C = 13;  // arm T-ACMP-RETRY; acmpsta<-status
  localparam int unsigned ACT_A15_C = 14;  // settle: latch params, arm T-ACMP-NOTK
  localparam int unsigned ACT_A16_C = 15;  // GET_RX_STATE response (F05.14)
  localparam int unsigned ACT_A17_C = 16;  // pbsta<-PASSIVE, acmpsta<-0

  // ---- TK event kinds on the class-C face (02 §5 catalog) ----------------
  localparam logic [1:0] TK_KIND_DISC_C  = 2'd0;  // EVT_TK_DISCOVERED{sink}
  localparam logic [1:0] TK_KIND_DEP_C   = 2'd1;  // EVT_TK_DEPARTED{sink}
  localparam logic [1:0] TK_KIND_REG_C   = 2'd2;  // TK_ATTR_REGISTERED{sink, adv|failed}
  localparam logic [1:0] TK_KIND_UNREG_C = 2'd3;  // TK_ATTR_UNREGISTERED{sink}

  // ---- pbsta encodings (05 §5, Milan §5.3.8.6) ---------------------------
  localparam logic [2:0] PB_DISABLED_C  = 3'd0;
  localparam logic [2:0] PB_PASSIVE_C   = 3'd1;
  localparam logic [2:0] PB_ACTIVE_C    = 3'd2;
  localparam logic [2:0] PB_COMPLETED_C = 3'd3;

  // ---- ACMP message types (F05.13; Milan names, Δ1) ----------------------
  localparam logic [3:0] AMSG_PROBE_TX_CMD_C     = 4'd0;
  localparam logic [3:0] AMSG_PROBE_TX_RESP_C    = 4'd1;
  localparam logic [3:0] AMSG_BIND_RX_CMD_C      = 4'd6;
  localparam logic [3:0] AMSG_BIND_RX_RESP_C     = 4'd7;
  localparam logic [3:0] AMSG_UNBIND_RX_CMD_C    = 4'd8;
  localparam logic [3:0] AMSG_UNBIND_RX_RESP_C   = 4'd9;
  localparam logic [3:0] AMSG_GET_RX_STATE_CMD_C = 4'd10;
  localparam logic [3:0] AMSG_GET_RX_STATE_RESP_C = 4'd11;

  // ---- ACMP status codes used here (IEEE 1722.1-2021 Table 8-3) ----------
  localparam logic [4:0] AST_SUCCESS_C                 = 5'd0;
  localparam logic [4:0] AST_LISTENER_UNKNOWN_ID_C     = 5'd1;
  localparam logic [4:0] AST_LISTENER_TALKER_TIMEOUT_C = 5'd7;
  localparam logic [4:0] AST_CONTROLLER_NOT_AUTH_C     = 5'd13;

  // ---- ACMPDU flags masks (F05.13; MSB-first wire warning applies) -------
  localparam logic [15:0] AFLG_FAST_CONNECT_C   = 16'h0002;
  localparam logic [15:0] AFLG_STREAMING_WAIT_C = 16'h0008;
  localparam logic [15:0] AFLG_REG_FAILED_C     = 16'h0040;

  // ---- Milan truncated ACMPDU geometry (F05.13, Δ2) ----------------------
  localparam logic [10:0] ACMP_CDL_MILAN_C  = 11'd44;  // 56-byte PDU
  localparam int unsigned ACMP_PDU_BYTES_C  = 56;

  // ---- ACMP timer constants (F08.1; T-ACMP-DELAY is a PRNG kind-0 draw) --
  localparam logic [31:0] T_ACMP_CMD_MS_C   = 32'd200;    // Milan Table 5.26
  localparam logic [31:0] T_ACMP_RETRY_MS_C = 32'd4000;   // Milan §5.5.3.5.23
  localparam logic [31:0] T_ACMP_NOTK_MS_C  = 32'd10000;  // Milan §5.5.3.5.18
  localparam logic [2:0]  PRNG_KIND_ACMP_DELAY_C = 3'd0;  // 0..1000 ms (Table 5.29)

  // ---- the 384-bit sink record (F07.6, lanes bottom->top = bit 0 up) -----
  // Flag lane order within flags[7:0] (F07.6): bound, started, sw, retried,
  // srp_decl[1:0], tk_reg, tk_disc — first listed at the lane's LSB.
  // srp_decl usage (05 §5 "srp_listener_declared"): bit 0 = listen armed
  // (A15 set / A8 clear); bit 1 = the matching talker attribute registered
  // FAILED (drives REGISTERING_FAILED in F05.14 / GET_RX_STATE at SOK).
  typedef struct packed {
    logic [7:0]  rsv2;               // [383:376]
    logic [7:0]  noadp_tmr_handle;   // [375:368] owned by ADP (04), preserved
    logic [7:0]  sm_tmr_handle;      // [367:360] shared SM timer slot (08 §5)
    logic [7:0]  saved_if_index;     // [359:352] discovery-saved interface
    logic [31:0] last_avail_index;   // [351:320] owned by ADP (04), preserved
    logic [3:0]  rsv1;               // [319:316]
    logic [11:0] settled_vlan;       // [315:304] settled SRP params (A15)
    logic [47:0] settled_da;         // [303:256]
    logic [63:0] settled_stream_id;  // [255:192]
    logic [63:0] bind_ctlr_eid;      // [191:128]
    logic [15:0] probe_seq;          // [127:112] saved probe regenerated, not stored raw
    logic [15:0] talker_uid;         // [111:96]
    logic [63:0] talker_eid;         // [95:32]
    logic [12:0] rsv0;               // [31:19]
    logic        f_tk_disc;          // [18] discovery-SM mirror (bookkeeping)
    logic        f_tk_reg;           // [17] matching talker attr registered
    logic [1:0]  f_srp_decl;         // [16:15] see header note
    logic        f_retried;          // [14] probe #2 (exact duplicate) sent
    logic        f_sw;               // [13] saved STREAMING_WAIT
    logic        f_started;          // [12] started/stopped (Milan §5.3.8.7)
    logic        f_bound;            // [11]
    logic [4:0]  acmpsta;            // [10:6] Table 8-3 code while PROBING_ACTIVE
    logic [2:0]  pbsta;              // [5:3]  PB_*_C
    logic [2:0]  sm_state;           // [2:0]  lsm_state_e
  } acmp_rec_t;

  localparam int unsigned ACMP_REC_W_C = $bits(acmp_rec_t);  // 384 (F07.6)

endpackage : pp_acmp_pkg
`default_nettype wire
