#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Kebag Logic
# SPDX-License-Identifier: (GPL-2.0 OR MIT)
"""gen_mtd_partitions.py - emit the QSPI `fixed-partitions` node from the SoC flash map.

The flash map has exactly one source of truth: ``FLASHBOOT_LAYOUT`` +
``FLASHBOOT_RESERVED`` in ``sw/litex/milan_soc.py``.  This tool READS THAT
SOURCE and emits ``sw/dts/mtd-partitions.dtsi``; the .dtsi is checked in so the
tree is complete without a LiteX install, and ``--check`` re-emits and
byte-compares it so the two can never drift silently.  That is the same
discipline as ``sw/builder/test_builder.py`` gates 19a/19b, and it exists
because the alternative - a hand-written partition table next to a Python dict -
is the exact defect shape recorded in
``docs/limitations/RECURRING_DEFECT_PATTERNS.md`` pattern 4.

``milan_soc.py`` imports LiteX at module scope, so this tool does NOT import it.
It parses the two dicts out of the source with ``ast``, which also means it
cannot accidentally pick up a value some build path mutated at run time.

WHAT IS AND IS NOT PROVEN HERE.  The node below is emitted, dtc-checked and
byte-gated on this host.  Whether Linux BINDS an mtd driver to the LiteSPI
controller on this SoC is NOT established anywhere in this tree - there is no
``mtd``/``spi-nor``/``jffs2`` node in any deployed device tree today, and no
board has been booted with one.  See ``docs/design/SAVED_STATE_FASTCONNECT.md``
section 10 for the kernel-side work and section 11 gate G1 for how to falsify it
on a board.

usage:
    gen_mtd_partitions.py            write sw/dts/mtd-partitions.dtsi
    gen_mtd_partitions.py --check    fail if the checked-in file is stale
    gen_mtd_partitions.py --print    write the fragment to stdout
    gen_mtd_partitions.py --map      print the flash map as a table
"""

import argparse
import ast
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
SOC = os.path.join(ROOT, "sw", "litex", "milan_soc.py")
OUT = os.path.join(HERE, "mtd-partitions.dtsi")

# Slots Linux must never write.  `read-only` on the boot images is not paranoia:
# a stray `dd` onto /dev/mtd0 bricks the board's self-config, and the kernel
# honours the flag.  `journal` and `user` are deliberately writable - they are
# the whole point.
READ_ONLY = {"bitstream", "kernel", "opensbi", "dtb", "rootfs"}


def _dict_literal(tree, name):
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name) and t.id == name:
                    return ast.literal_eval(node.value)
    raise SystemExit(f"gen_mtd_partitions: {name} not found in {SOC}")


def _int_literal(tree, name):
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name) and t.id == name:
                    return ast.literal_eval(node.value)
    raise SystemExit(f"gen_mtd_partitions: {name} not found in {SOC}")


def load_map():
    """[(name, offset, size, kind)] ordered by offset, plus (flash_size, eb)."""
    tree = ast.parse(open(SOC, encoding="utf-8").read())
    layout = _dict_literal(tree, "FLASHBOOT_LAYOUT")
    reserved = _dict_literal(tree, "FLASHBOOT_RESERVED")
    flash_size = _int_literal(tree, "FLASH_SIZE")
    erase = _int_literal(tree, "FLASH_ERASE_BLOCK")
    rows = [(n, e["offset"], e["size"], "image") for n, e in layout.items()]
    rows += [(n, e["offset"], e["size"], "reserved") for n, e in reserved.items()]
    return sorted(rows, key=lambda r: r[1]), flash_size, erase


def check_map(rows, flash_size, erase):
    problems, prev_end, prev_name = [], 0, None
    for name, off, size, _k in rows:
        if size <= 0:
            problems.append(f"{name}: non-positive size {size}")
        if off % erase:
            problems.append(f"{name}: offset 0x{off:X} not erase-block aligned")
        if size % erase:
            problems.append(f"{name}: size 0x{size:X} not an erase-block multiple")
        if off < prev_end:
            problems.append(f"{name} @0x{off:X} overlaps {prev_name} "
                            f"(ends 0x{prev_end:X})")
        if off + size > flash_size:
            problems.append(f"{name}: ends 0x{off + size:X} past the device "
                            f"(0x{flash_size:X})")
        prev_end, prev_name = off + size, name
    return problems


def emit(rows, flash_size, erase):
    lines = [
        "// SPDX-License-Identifier: (GPL-2.0 OR MIT)",
        "/*",
        " * GENERATED by sw/dts/gen_mtd_partitions.py from FLASHBOOT_LAYOUT +",
        " * FLASHBOOT_RESERVED in sw/litex/milan_soc.py.  DO NOT EDIT BY HAND -",
        " * regenerate, and let `gen_mtd_partitions.py --check` prove the two agree.",
        " *",
        " * Attaches to the flash node LiteX's json2dts emits for LiteSPI:",
        " *",
        " *     litespiflash: spiflash@<csr> {",
        " *         compatible = \"litex,spiflash\";",
        " *         flash: flash@0 { compatible = \"jedec,spi-nor\"; reg = <0 SIZE>; };",
        " *     };",
        " *",
        " * so the `&flash` label below is the one that base tree already defines.",
        " * Append this fragment to the generated base.dts before dtc, exactly like",
        " * the kl,dma-ether overlay (see sw/dts/README.md).",
        " *",
        " * NOT YET PROVEN ON A BOARD: no deployed tree carries an mtd node today and",
        " * no mtd driver is known to bind to this controller in this kernel config.",
        " * docs/design/SAVED_STATE_FASTCONNECT.md section 11 gate G1 is the falsifier",
        " * (`cat /proc/mtd` after a flash + boot).",
        " */",
        "",
        "&flash {",
        "\t#address-cells = <1>;",
        "\t#size-cells = <1>;",
        "",
        "\tpartitions {",
        "\t\tcompatible = \"fixed-partitions\";",
        "\t\t#address-cells = <1>;",
        "\t\t#size-cells = <1>;",
        "",
    ]
    for name, off, size, kind in rows:
        ro = "\n\t\t\tread-only;" if name in READ_ONLY else ""
        note = "boot image" if kind == "image" else "WRITABLE"
        lines += [
            f"\t\t/* {note}: {size // 1024} KiB */",
            f"\t\tpartition@{off:x} {{",
            f"\t\t\tlabel = \"{name}\";",
            f"\t\t\treg = <0x{off:x} 0x{size:x}>;{ro}",
            "\t\t};",
        ]
    used = sum(r[2] for r in rows)
    lines += [
        "\t};",
        "};",
        "",
        f"/* {len(rows)} partitions, 0x{used:x} of 0x{flash_size:x} bytes allocated, "
        f"erase block 0x{erase:x} */",
        "",
    ]
    return "\n".join(lines)


def dtc_check(text):
    """Run dtc over the fragment nested in a synthetic base that supplies the
    `flash` label the real base tree defines.  Returns [] or a list of errors;
    ['dtc not installed'] when dtc is missing, which the caller may treat as a
    loud skip rather than a failure."""
    import shutil
    import subprocess
    import tempfile

    if shutil.which("dtc") is None:
        return ["dtc not installed"]
    body = text[text.index("&flash {"):]
    wrapper = (
        "/dts-v1/;\n/ {\n"
        "  #address-cells = <1>;\n  #size-cells = <1>;\n"
        "  spiflash@0 {\n"
        "    #address-cells = <1>;\n    #size-cells = <1>;\n"
        "    compatible = \"litex,spiflash\";\n"
        "    reg = <0x0 0x100>;\n"
        "    flash: flash@0 {\n"
        "      compatible = \"jedec,spi-nor\";\n"
        "      reg = <0x0 0x1000000>;\n"
        "    };\n"
        "  };\n};\n\n" + body)
    with tempfile.NamedTemporaryFile("w", suffix=".dts", delete=False) as f:
        f.write(wrapper)
        tmp = f.name
    try:
        r = subprocess.run(["dtc", "-I", "dts", "-O", "dtb", tmp, "-o",
                            os.devnull], capture_output=True, text=True)
    finally:
        os.unlink(tmp)
    errs = [ln for ln in r.stderr.splitlines()
            if "Error" in ln or "FATAL" in ln]
    if r.returncode != 0 and not errs:
        errs = [r.stderr.strip() or f"dtc exited {r.returncode}"]
    return errs


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--print", dest="to_stdout", action="store_true")
    ap.add_argument("--map", action="store_true")
    ap.add_argument("--dtc", action="store_true",
                    help="also run dtc over the fragment")
    args = ap.parse_args(argv)

    rows, flash_size, erase = load_map()
    problems = check_map(rows, flash_size, erase)
    if problems:
        for p in problems:
            print(f"gen_mtd_partitions: {p}", file=sys.stderr)
        return 1

    if args.map:
        print(f"{'slot':<10} {'offset':>10} {'size':>10} {'end':>10}  kind")
        for name, off, size, kind in rows:
            print(f"{name:<10} 0x{off:08X} 0x{size:08X} 0x{off + size:08X}  {kind}")
        free = flash_size - sum(r[2] for r in rows)
        print(f"{'(free)':<10} {'':>10} 0x{free:08X}")
        return 0

    text = emit(rows, flash_size, erase)
    if args.dtc:
        errs = dtc_check(text)
        if errs == ["dtc not installed"]:
            print("gen_mtd_partitions: dtc not installed - SKIPPING the "
                  "structural check (install dtc to run it)", file=sys.stderr)
        elif errs:
            for e in errs:
                print(f"gen_mtd_partitions: dtc: {e}", file=sys.stderr)
            return 1
        else:
            print("gen_mtd_partitions: dtc OK")
    if args.to_stdout:
        sys.stdout.write(text)
        return 0
    if args.check:
        if not os.path.isfile(OUT):
            print(f"gen_mtd_partitions: {OUT} missing - run without --check",
                  file=sys.stderr)
            return 1
        cur = open(OUT, encoding="utf-8").read()
        if cur != text:
            print("gen_mtd_partitions: mtd-partitions.dtsi is STALE vs "
                  "FLASHBOOT_LAYOUT/FLASHBOOT_RESERVED - regenerate it",
                  file=sys.stderr)
            return 1
        print(f"gen_mtd_partitions: OK ({len(rows)} partitions, in step with "
              f"{os.path.relpath(SOC, ROOT)})")
        return 0
    open(OUT, "w", encoding="utf-8").write(text)
    print(f"gen_mtd_partitions: wrote {os.path.relpath(OUT, ROOT)} "
          f"({len(rows)} partitions)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
