#!/usr/bin/env python3
# SPDX-License-Identifier: (GPL-2.0 OR MIT)
#
# milan_dt.py — device-tree tooling for the Milan TSN NIC.
#
# ============================================================================
#  GENERATION IS RETIRED (2026-07-26).  `extract` and `gen` REFUSE TO RUN.
#  The kl,dma-ether + kl,milan-pcm nodes are emitted by
#      sw/builder/endstation_builder.py   (emit_dt_overlay, from configs/*.yaml)
#  whose output BYTE-MATCHES both deployed trees, gated by test_builder.py
#  gates 19a/19b.  This file keeps `validate` only — the binding check for
#  whatever emitted the overlay.
#
#  WHY RETIRED, with the numbers.  Fed the CURRENT deployed build's csr.json
#  (build_ax8x8_rxq1fix_eppo), the generator below emits:
#    * FOUR reg windows, no `phy` — the deployed trees carry FIVE
#      (`csr, dma-tx, dma-rx, dma-ts, phy`; `phy` = 0xf0003800/0xc, the MDIO
#      bit-bang window `ethtool mdio1` uses);
#    * dma-rx size 0x68 — the min/max span of the milan_dma_rx_* CSRs — where
#      the deployed trees and the driver ABI use 0x40.  The DT window is a
#      DRIVER ABI constant, not a CSR span, so no csr.json-derived rule can
#      produce it;
#    * `compatible = "kl,dma-ether-0.9"` (one string) vs the deployed pair;
#    * no `dma-coherent`, no `kl,rsc-clk-mhz` (absent = 50 MHz default = the
#      2x-fast PHC that broke asCapable/SRP on silicon), no PCM node, no
#      reserved-memory node;
#    * `phy-mode = "rgmii-id"` from boards/ax7101.json on a GMII-wired board.
#  Making it agree would mean copying sw/builder's driver-ABI window table into
#  a SECOND place — which is the exact defect class this retirement closes
#  (see also the 2026-07-22 RMON tie-off and the 2026-07-24 rx-queues drift).
#  The checked-in ir/*.json and milan-nic.*.dtsi are two memory-map generations
#  stale (0xf00028xx) and are kept only as historical artifacts.
# ============================================================================
#
# What survives the retirement is the part that was always the contract rather
# than a second implementation: the BINDINGS in bindings/ (kl,dma-ether.yaml,
# kl,milan-pcm.yaml) and the checker that holds an overlay to them.
#
#     configs/*.yaml ──endstation_builder──▶ overlay .dtsi ──milan_dt.py validate──▶ dtc + bindings
#
# Subcommands:
#   validate <dts|dtsi>   dtc structure + EVERY kl,* node checked against its
#                         binding in bindings/ (required properties present,
#                         no property the binding does not declare - the
#                         `additionalProperties: false` rule, enforced without
#                         needing dtschema installed)
#   extract | gen         RETIRED, see the banner above; they exit 2.
#
# Fully-FPGA flow (see sw/dts/README.md):
#   litex_json2dts_linux build/csr.json > base.dts
#   python3 sw/builder/endstation_builder.py configs/endstation_ax7101_8x8.yaml
#   python3 sw/dts/milan_dt.py validate configs/generated/<...>_dt.dtsi
#   cat <overlay> >> base.dts && dtc -I dts -O dtb base.dts -o milan.dtb
#
# Pure stdlib — runs with plain python3, no LiteX venv needed.

import os
import re
import sys
import argparse
import subprocess

HERE   = os.path.dirname(os.path.abspath(__file__))
SCHEMA = os.path.join(HERE, "milan-dt.schema.json")

RETIRED = """
milan_dt.py {cmd}: RETIRED 2026-07-26.

The kl,dma-ether + kl,milan-pcm device-tree nodes are generated by

    python3 sw/builder/endstation_builder.py configs/endstation_<shape>.yaml

from the declarative end-station config. Its output byte-matches both deployed
trees (milan_ax7101_vexii.dts / milan_arty_vexii.dts) and is gated by
sw/builder/test_builder.py gates 19a/19b.

This tool could not reproduce that node: it emits four reg windows (no `phy`),
a dma-rx window of 0x68 (the CSR span) where the driver ABI is 0x40, a
single-string `compatible`, no `dma-coherent` / `kl,rsc-clk-mhz`, and no PCM or
reserved-memory node. Full reasoning in the banner at the top of this file and
in sw/dts/README.md.

`milan_dt.py validate <overlay>` still works and is the binding check.
"""


# --- validate: dtc (+ dtschema if present) ------------------------------------------

def validate_dts(path):
    """Wrap the overlay in a synthetic base tree (providing the referenced labels) and
    run dtc for a structural check; run dt-validate against the binding if available."""
    frag = open(path).read()
    if "/dts-v1/" in frag:
        # a COMPLETE tree (e.g. a deployed .dts): dtc it as-is. Wrapping it
        # would redeclare intc0/gpio and dtc would fail on the duplicate labels.
        tmp = None
        r = subprocess.run(["dtc", "-I", "dts", "-O", "dtb", path, "-o", os.devnull],
                           capture_output=True, text=True)
    else:
        # an OVERLAY fragment: nest it under a synthetic root that supplies the
        # labels it references.
        body = frag[frag.index("/ {") + 3: frag.rindex("};")]
        wrapper = (
            "/dts-v1/;\n/ {\n"
            "  #address-cells = <1>;\n  #size-cells = <1>;\n"
            "  intc0: intc { interrupt-controller; #interrupt-cells = <1>; phandle = <1>; };\n"
            "  intc: intc2 { interrupt-controller; #interrupt-cells = <3>; phandle = <2>; };\n"
            "  gpio: gpio { gpio-controller; #gpio-cells = <2>; phandle = <3>; };\n"
            + body + "\n};\n"
        )
        import tempfile
        with tempfile.NamedTemporaryFile("w", suffix=".dts", delete=False) as f:
            f.write(wrapper); tmp = f.name
        try:
            r = subprocess.run(["dtc", "-I", "dts", "-O", "dtb", tmp, "-o", os.devnull],
                               capture_output=True, text=True)
        finally:
            os.unlink(tmp)
    errs = [l for l in r.stderr.splitlines() if "Error" in l or "FATAL" in l]
    if r.returncode != 0 or errs:
        print(r.stderr, file=sys.stderr)
        raise SystemExit(f"dtc FAILED for {path}")
    print(f"dtc: {os.path.basename(path)} parses OK (structure valid)")
    return check_bindings(frag, path)


# --- binding check (the `additionalProperties: false` rule, without dtschema) ---------

# Properties every DT node may carry regardless of its binding (dtschema's core
# meta-schema supplies these; our hand check must too or it would reject the
# deployed nodes for being well-formed).
_STANDARD_PROPS = {"status", "phandle", "interrupt-parent", "#address-cells",
                   "#size-cells", "ranges", "compatible", "reg", "reg-names",
                   "interrupts", "interrupt-names", "label"}


def _load_bindings():
    """{compatible: (path, properties set, required list)} from bindings/*.yaml.

    Parsed with pyyaml when available; otherwise a deliberately small regex
    reader for the two keys we check (`properties:` names and `required:`
    entries), so the gate still runs on a bare python3 - the point of the tool.
    """
    out = {}
    for fn in sorted(os.listdir(os.path.join(HERE, "bindings"))):
        if not fn.endswith(".yaml"):
            continue
        p = os.path.join(HERE, "bindings", fn)
        txt = open(p).read()
        try:
            import yaml
            doc = yaml.safe_load(txt)
            props = set(doc.get("properties", {}))
            req = list(doc.get("required", []))
        except ImportError:
            body = txt.split("\nproperties:", 1)[1].split("\nrequired:", 1)[0]
            props = set(re.findall(r"^  ([A-Za-z0-9,#_.-]+):", body, re.M))
            rq = txt.split("\nrequired:", 1)
            req = re.findall(r"^  - (\S+)", rq[1].split("\n\n", 1)[0], re.M) \
                if len(rq) > 1 else []
        # the binding file name IS the compatible it governs
        out[fn[:-len(".yaml")]] = (p, props, req)
    return out


def _strip_comments(t):
    t = re.sub(r"/\*.*?\*/", "", t, flags=re.S)
    return re.sub(r"//[^\n]*", "", t)


def _nodes(frag):
    """[(header, {property names}, node text)] for every node one level below
    the overlay root. Brace-matched (not line-based): DT properties routinely
    span several lines - `reg = <..>,\n      <..>;` is the normal shape - and a
    line-based reader silently misses exactly the properties that matter."""
    t = _strip_comments(frag)
    out, depth, i, n = [], 0, 0, len(t)
    hdr_start = 0
    stack = []
    while i < n:
        c = t[i]
        if c == "{":
            depth += 1
            header = t[hdr_start:i].strip().splitlines()[-1].strip() if t[hdr_start:i].strip() else ""
            stack.append((depth, header, i + 1))
            hdr_start = i + 1
        elif c == "}":
            d, header, body_start = stack.pop() if stack else (depth, "", i)
            if d >= 2:
                out.append((header, _props(t[body_start:i]), t[body_start:i]))
            depth -= 1
            hdr_start = i + 1
        elif c == ";":
            hdr_start = i + 1
        i += 1
    return out


def _props(body):
    """Property names of a node body, sub-nodes excluded."""
    flat = re.sub(r"\{[^{}]*\}", "", body)
    while re.search(r"\{[^{}]*\}", flat):
        flat = re.sub(r"\{[^{}]*\}", "", flat)
    names = set()
    for stmt in flat.split(";"):
        m = re.match(r"\s*([A-Za-z0-9,#_.+-]+)\s*(=|$)", stmt)
        if m and m.group(1):
            names.add(m.group(1))
    return names


def check_bindings(frag, path):
    """Every node whose `compatible` names a kl,* binding must satisfy it:
    all `required` properties present, and no property the binding does not
    declare (`additionalProperties: false`). Returns the number of problems."""
    bindings = _load_bindings()
    bad = 0
    checked = 0
    for header, props, body in _nodes(frag):
        # this node's OWN compatible (searching the whole file from the header
        # would pick up the next node's - reserved-memory has none)
        m = re.search(r'compatible\s*=\s*([^;]+);', body)
        if not m:
            continue
        compats = re.findall(r'"([^"]+)"', m.group(1))
        b = next((c for c in compats if c in bindings), None)
        if b is None:
            continue
        bpath, declared, required = bindings[b]
        checked += 1
        missing = [r for r in required if r not in props]
        extra = sorted(props - declared - _STANDARD_PROPS)
        for r in missing:
            print(f"  BINDING FAIL {header}: required '{r}' missing "
                  f"({os.path.basename(bpath)})", file=sys.stderr)
            bad += 1
        for e in extra:
            print(f"  BINDING FAIL {header}: '{e}' is not declared in "
                  f"{os.path.basename(bpath)} (additionalProperties: false)",
                  file=sys.stderr)
            bad += 1
        if not missing and not extra:
            print(f"  binding OK: {header} vs {os.path.basename(bpath)} "
                  f"({len(props)} properties)")
    if checked == 0:
        print(f"  WARNING: {os.path.basename(path)} has no node with a known "
              "kl,* compatible - nothing was checked", file=sys.stderr)
        bad += 1
    return bad


# --- self-test (negative controls: a checker that never fails is not a gate) ---------

_GOOD = '''/ {
\tmilan_nic: ethernet@90000000 {
\t\tcompatible = "kl,dma-ether-0.9", "kl,dma-ether";
\t\treg = <0x90000000 0x10000>,
\t\t      <0xf0003000 0x24>;
\t\treg-names = "csr", "dma-tx";
\t\tinterrupts = <3>;
\t\tdma-coherent;
\t\tkl,rsc-clk-mhz = <100>;
\t\tkl,txq-cnt = <4>;
\t\tkl,rxq-cnt = <1>;
\t\tstatus = "okay";
\t};
};
'''


def selftest():
    """Prove the binding check can FAIL. The multi-line `reg` in _GOOD is the
    important half: a line-based property reader misses it and then reports
    "required 'reg' missing" on a perfectly good node (that bug was real, and
    this fixture is what caught it)."""
    ok = True
    cases = [
        ("clean node", _GOOD, 0),
        ("undeclared property",
         _GOOD.replace("\t\tstatus", "\t\tkl,not-a-real-prop = <1>;\n\t\tstatus"), 1),
        ("required property missing",
         _GOOD.replace('\t\tkl,rxq-cnt = <1>;\n', ""), 1),
        ("unknown compatible (nothing checked)",
         _GOOD.replace('"kl,dma-ether-0.9", "kl,dma-ether"', '"vendor,other"'), 1),
    ]
    for name, text, want in cases:
        got = check_bindings(text, f"<selftest {name}>")
        verdict = "OK" if (got > 0) == (want > 0) else "FAILED"
        print(f"  [selftest] {name}: {got} problem(s), expected "
              f"{'>0' if want else '0'} -> {verdict}")
        ok = ok and verdict == "OK"
    return 0 if ok else 1


# --- CLI ----------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(
        description="Milan device-tree binding checker (generation retired - see "
                    "the banner in this file; nodes come from sw/builder)")
    sub = ap.add_subparsers(dest="cmd", required=True)

    pe = sub.add_parser("extract", help="RETIRED (see sw/builder/endstation_builder.py)")
    pe.add_argument("--platform", default="litex")
    pe.add_argument("csr_json", nargs="?")
    pe.add_argument("--board", default=None)

    pg = sub.add_parser("gen", help="RETIRED (see sw/builder/endstation_builder.py)")
    pg.add_argument("ir_json", nargs="?")

    pv = sub.add_parser("validate", help="dtc + binding check for an overlay")
    pv.add_argument("dts")

    sub.add_parser("selftest", help="negative controls for the binding check")

    args = ap.parse_args()
    if args.cmd in ("extract", "gen"):
        print(RETIRED.format(cmd=args.cmd), file=sys.stderr)
        return 2
    if args.cmd == "validate":
        return 1 if validate_dts(args.dts) else 0
    if args.cmd == "selftest":
        return selftest()
    return 0


if __name__ == "__main__":
    sys.exit(main())
