#!/usr/bin/python3 -S
import sys
sys.path.insert(0, '$WORKSPACE_HOME/milan-fpga-management/2026-09-22/517-f1-author/staged-backpressure/make-flush-SIGINT-repeated')
import fake_leg
fake_leg.main({'out': [['out', 'L7 partial\n']], 'name': 'L7', 'ledger': '$WORKSPACE_HOME/milan-fpga-management/2026-09-22/517-f1-author/staged-backpressure/make-flush-SIGINT-repeated/ledger.jsonl', 'announce': '$WORKSPACE_HOME/milan-fpga-management/2026-09-22/517-f1-author/staged-backpressure/make-flush-SIGINT-repeated/announce.fifo'})
