#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Kebag Logic
# SPDX-License-Identifier: (GPL-2.0 OR MIT)
"""milan_persist_state.py - THE definition of what Milan v1.2 requires to survive
a power cycle, and of what this end station can actually restore.

THIS BUILD RESTORES NOTHING.  READ THIS FIRST (2026-08-12).
========================================================================
Both ingest paths this file used to describe are DELETED with the IEEE 1722.1
control plane:

  * the E3 persistence journal - ``KL_persist_journal.sv``, CSR
    ``0x7B8-0x7C4`` - which verified and applied a saved binding into
    ``KL_acmp_lstn_ctx``'s ``rest_*`` ports.  Both that engine and the ACMP
    listener contexts it wrote into are gone.
  * the E4 AEM patch port - ``KL_aem_patch.sv``, CSR ``0x7C8-0x7D4`` - the
    write master ``KL_aecp_aem_store`` never had.  That engine, that store,
    and the whole ``hdl/ieee17221/aecp`` tree are gone.

The two CSR groups still ACCEPT WRITES, because the register block outlived
the engines behind them; the writes land NOWHERE, and ``JNL_STAT`` /
``JNL_SEQ`` read structural zeros.  No binding, no format, no mapping and no
name is ever restored after a power cycle on this gateware.

So EVERY item below now carries ``restore=None``.  That is not a downgrade of
the inventory - it is the inventory doing its job.  The alternative, leaving
verdicts that say "fabric-journal" and "csr" beside registers that swallow
writes, is software that appears to persist state when nothing does, and this
file exists precisely to make that state of affairs unsayable.  The clause
list itself is UNCHANGED and still true: Milan still requires these things:
what changed is our answer to "and can this build put it back".

The generated ``milan-persist-state.sh`` says the same thing in the form a
board helper reads: ``MILAN_PERSIST_SUPPORTED=0`` and an EMPTY
``MILAN_PERSIST_ITEMS``, so a helper that iterates the item list does nothing
at all rather than saving records it can never replay.  The clause register
survives beside it as ``MILAN_PERSIST_INVENTORY`` for tools that report
compliance status.
========================================================================

ONE DEFINITION, MANY READERS.  ``PERSIST_ITEMS`` below is the only place in
either repo that says "clause X requires state Y".  Everything that needs the
list derives it from here:

  * the board helper ``milan-persist`` gets ``milan-persist-state.sh``
    (generated by ``--emit-sh``): the record tags, the item order, and the
    per-item restore verdict;
  * ``milan_torture.py``'s A_STATE_RESTORED prose gets the same list through
    ``--emit-json``;
  * the design record gets ``--emit-md``.

The project has been bitten five times in one week by a constant restated in a
second place (``docs/limitations/RECURRING_DEFECT_PATTERNS.md``); a clause list
is exactly the kind of thing that agrees on day one and diverges in silence, so
it is generated, byte-gated by ``--check``, and never retyped.

THE VERDICTS.  Each item carries ``restore`` naming HOW the saved value gets
back into the entity after a power cycle.  Two of the three answers are
currently unreachable and are kept documented so that a future plane can claim
them again by name rather than by re-inventing the vocabulary:

  ``"fabric-journal"``  the fabric verifies and applies it.  UNREACHABLE: its
                        engine (``KL_persist_journal``) and its destination
                        (``KL_acmp_lstn_ctx``) are deleted.

  ``"csr"``             a plain CSR write puts the value back.  UNREACHABLE
                        for AEM state: the E4 patch port (``KL_aem_patch``)
                        and the store it wrote into are deleted.

  ``None``              NO INGEST PATH EXISTS.  ``gap`` names precisely what
                        is missing.  This is every item today.

CLAUSES THAT REQUIRE THE OPPOSITE.  Milan 5.3.4.1 and 5.3.4.2 say the locked
state and the registered-controller list are CLEARED by a power cycle.  They are
listed here with ``restore=None, gap="must NOT persist"`` so that a future,
broader store cannot quietly start saving them: the inventory is the register of
both obligations.  They are the only two rows this round did not change - and
they are, trivially and for the wrong reason, the only two currently satisfied.

usage:
    milan_persist_state.py --emit-sh    write sw/persist/milan-persist-state.sh
    milan_persist_state.py --emit-json  print the inventory as JSON
    milan_persist_state.py --emit-md    print the inventory as a markdown table
    milan_persist_state.py --check      fail if the checked-in .sh is stale
    milan_persist_state.py --gaps       print only the items with no restore path
"""

import argparse
import ast
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
SOC = os.path.join(ROOT, "sw", "litex", "milan_soc.py")
SH_OUT = os.path.join(HERE, "milan-persist-state.sh")

#: `/etc` of the flashed rootfs overlay, same convention (and same env
#: override) as ``sw/builder/endstation_builder.py``'s ROOTFS_OVERLAY_ETC:
#: the image is built in the sibling repo, and the copy is simply SKIPPED when
#: that checkout is not on this disk.
ROOTFS_OVERLAY_ETC = os.environ.get(
    "MILAN_ROOTFS_OVERLAY_ETC",
    os.path.expanduser("~/milan-tests-avb/fpga/buildroot/br2-external/"
                       "board/milan_naxriscv/rootfs_overlay/etc"))


def _flash_reserved():
    """``FLASHBOOT_RESERVED`` read out of milan_soc.py with ``ast``.

    The SAME reader discipline as ``sw/dts/gen_mtd_partitions.py``: milan_soc.py
    imports LiteX at module scope so it cannot be imported here, and a second
    hand-kept copy of the offsets is the defect this whole file exists to avoid.
    The board helper gets these through the generated include and therefore
    never carries a flash offset of its own - which is exactly the bug in the
    shipping ``acmp-persist``, whose ``SECT=0xFF0000`` literal names the LAST
    sector of the device and lands inside the ``user`` partition rather than
    ``journal``.
    """
    tree = ast.parse(open(SOC, encoding="utf-8").read())
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name) and t.id == "FLASHBOOT_RESERVED":
                    return ast.literal_eval(node.value)
    raise SystemExit(f"milan_persist_state: FLASHBOOT_RESERVED not in {SOC}")

#: The one sentence every unreachable-path ``gap`` ends with. A single string
#: rather than eleven paraphrases: this is exactly the kind of fact that is
#: retyped slightly differently in each row and then updated in only some of
#: them when a plane comes back.
PLANE_DELETED = (
    "2026-08-12: the IEEE 1722.1 control plane is deleted, so this cannot be "
    "restored by any path. CSR 0x7B8-0x7C4 (E3 journal) and 0x7C8-0x7D4 (E4 "
    "AEM patch port) still accept writes and land nowhere; JNL_STAT/JNL_SEQ "
    "read structural zeros")

#: Container magic for the SOFTWARE-verified AEM dynamic-state record set.
#: 'KLS1' little-endian, byte 0 = 'K' - deliberately the same shape as the
#: fabric's 'KLJ1' (KL_persist_journal MAGIC_P) so a hexdump of either slot is
#: readable, and deliberately a DIFFERENT value so neither engine can ever be
#: handed the other's image and try to parse it.
KLS1_MAGIC = 0x3153_4C4B
KLS1_FMT_MAJOR = 1
KLS1_FMT_MINOR = 0

#: The Milan clause text, quoted.  Extracted from
#: "Milan_Specification_Consolidated_v1.2_Final_Approved 20231130.pdf" with
#: `pdftotext -layout`; the line numbers are of that extraction and are recorded
#: so any reader can re-derive the quote rather than trust this file.
PERSIST_ITEMS = [
    dict(
        key="strin_fmt", clause="5.3.8.1", pdf_line=1927,
        title="STREAM_INPUT current format",
        quote="The current format shall be saved in a non-volatile memory and "
              "restored after a power cycle.",
        scope="per-descriptor", descriptor="STREAM_INPUT", width_words=2,
        read="AECP GET_STREAM_FORMAT(STREAM_INPUT, idx); also the 0x800 window "
             "words 0x824/0x828 for the bound stream",
        restore=None,
        restore_note="was the E4 AEM patch port, CSR 0x7C8-0x7D4 "
                     "(KL_aem_patch, gateware 0x0022-0x0042): SEL {0x0005, "
                     "idx}, FIELD 0, two DATA words MSW-first, CTRL commit",
        gap="the E4 patch port (KL_aem_patch) and the AEM store it wrote "
            "into (KL_aecp_aem_store) are both deleted. " + PLANE_DELETED,
    ),
    dict(
        key="strout_fmt", clause="5.3.7.1", pdf_line=1758,
        title="STREAM_OUTPUT current format",
        quote="The current format shall be saved in a non-volatile memory and "
              "restored after a power cycle.",
        scope="per-descriptor", descriptor="STREAM_OUTPUT", width_words=2,
        read="AECP GET_STREAM_FORMAT(STREAM_OUTPUT, idx)",
        restore=None,
        restore_note="was the E4 AEM patch port, CSR 0x7C8-0x7D4 (gateware "
                     "0x0022-0x0042): SEL {0x0006, idx}, FIELD 0",
        gap="the E4 patch port and the AEM store it wrote into are both "
            "deleted. " + PLANE_DELETED,
    ),
    dict(
        key="bound", clause="5.3.8.2", pdf_line=1942,
        title="STREAM_INPUT bound state",
        quote="The current bound state shall be saved in a non-volatile memory "
              "and restored after a power cycle.",
        scope="per-descriptor", descriptor="STREAM_INPUT", width_words=1,
        read="CSR 0x6A4 lsm state; 0x800 window 0x82C per index",
        restore=None,
        restore_note="was the fabric journal: KL_persist_journal (CSR "
                     "0x7B8-0x7C4) -> KL_acmp_lstn_ctx rest_*",
        gap="KL_persist_journal and the ACMP listener contexts it restored "
            "into are both deleted. " + PLANE_DELETED,
    ),
    dict(
        key="bind_params", clause="5.3.8.3", pdf_line=1947,
        title="STREAM_INPUT binding parameters",
        quote="For each bound Stream Input, a PAAD-AE shall save the following "
              "information, called the binding parameters, in a non-volatile "
              "memory: Entity ID of the talker to which it is currently bound; "
              "The index of the Source that the Stream Input is currently bound "
              "to; Entity ID of the controller that requested the binding; "
              "Started/stopped state.",
        scope="per-descriptor", descriptor="STREAM_INPUT", width_words=6,
        read="CSR 0x6A8/0x6AC talker eid; 0x800 window 0x860/0x864 controller "
             "eid, 0x868 {flags, talker_unique_id}",
        #: 5.3.8.1-style clauses say WHAT to keep; these two say WHEN to write
        #: it, and one of them is an ERASE.  5.5.2.4 (Controller Bind): "The
        #: Listener stores the binding parameters contained in the
        #: BIND_RX_COMMAND message ... in non-volatile memory in order to
        #: enable the stream to be quickly reestablished after a power cycle
        #: and/or network disruption."  5.5.3.5.3 and its siblings: "then save
        #: them to non volatile memory" - note Milan spells it UNHYPHENATED
        #: outside 5.3, which is a live trap for anyone re-deriving these
        #: quotes with a hyphen-only grep.  And 5.3.8.3 itself closes with
        #: "The binding parameters are cleared when the Stream Input gets
        #: unbound", matched by "Clear the saved binding parameters." in the
        #: same 5.5.3.5.x steps: a store that KEEPS a record after UNBIND_RX
        #: violates this clause exactly as surely as one that never wrote it.
        #: The journal's VALID[30]=0 hole is how that erase is represented.
        also_clauses=["5.5.2.4", "5.5.3.5.3"],
        restore=None,
        restore_note="was the fabric journal: KL_persist_journal (CSR "
                     "0x7B8-0x7C4) -> KL_acmp_lstn_ctx rest_*",
        gap="KL_persist_journal and the ACMP listener contexts it restored "
            "into are both deleted. " + PLANE_DELETED,
    ),
    dict(
        key="started", clause="5.3.8.7", pdf_line=2029,
        title="STREAM_INPUT started/stopped state",
        quote="The current started/stopped state shall be saved in a "
              "non-volatile memory and restored after a power cycle.",
        scope="per-descriptor", descriptor="STREAM_INPUT", width_words=1,
        read="the STREAMING_WAIT bit of the binding flags, 0x800 window 0x868",
        # carried INSIDE the 5.3.8.3 binding-parameter record, which 5.3.8.3
        # itself lists as one of the four parameters - not a second store.
        restore=None,
        restore_note="was the fabric journal: KL_persist_journal (CSR "
                     "0x7B8-0x7C4) -> KL_acmp_lstn_ctx rest_*",
        gap="KL_persist_journal and the ACMP listener contexts it restored "
            "into are both deleted. " + PLANE_DELETED,
    ),
    dict(
        key="pres_offset", clause="5.3.7.6", pdf_line=1880,
        title="STREAM_OUTPUT presentation time offset",
        quote="The Presentation time offset shall be saved in a non-volatile "
              "memory and restored after a power cycle.",
        scope="per-descriptor", descriptor="STREAM_OUTPUT", width_words=1,
        read="AECP GET_STREAM_INFO(STREAM_OUTPUT, idx) presentation offset; the "
             "per-output file lives in KL_aecp_response_builder (pres_offset_o)",
        restore=None,
        gap="the presentation-offset file lived in KL_aecp_response_builder, "
            "which is deleted along with the E4 patch port that reserved "
            "FIELD 3 for it. " + PLANE_DELETED,
    ),
    dict(
        key="samp_rate", clause="5.3.5.1", pdf_line=1684,
        title="AUDIO_UNIT current sampling rate",
        quote="The current sampling rate shall be saved in a non-volatile "
              "memory and restored after a power cycle.",
        scope="per-descriptor", descriptor="AUDIO_UNIT", width_words=1,
        read="AECP GET_SAMPLING_RATE(AUDIO_UNIT, idx)",
        restore=None,
        restore_note="was the E4 AEM patch port, CSR 0x7C8-0x7D4 (gateware "
                     "0x0022-0x0042): SEL {0x0002, 0}, FIELD 1, ONE DATA word",
        gap="the E4 patch port and the AEM store it wrote into are both "
            "deleted. " + PLANE_DELETED,
    ),
    dict(
        key="clock_src", clause="5.3.11.1", pdf_line=2187,
        title="CLOCK_DOMAIN current clock source",
        quote="The current clock source shall be saved in a non-volatile "
              "memory and restored after a power cycle.",
        scope="per-descriptor", descriptor="CLOCK_DOMAIN", width_words=1,
        read="AECP GET_CLOCK_SOURCE(CLOCK_DOMAIN, idx)",
        #: DELIBERATELY STILL OPEN, and the narrowest gap in this list. The E4
        #: port restores the DESCRIPTOR (CSR 0x7C8, FIELD 2), so
        #: GET_CLOCK_SOURCE answers with the saved index - but the live
        #: selector clk_src_r inside KL_aecp_response_builder has no slave
        #: port, so the FABRIC would still be clocking from the boot default.
        #: An entity that reports a source it is not using is a worse answer
        #: than one that admits the revert, so this stays unmet until the
        #: shadow follows.
        restore=None,
        gap="the descriptor bytes were restorable via the E4 port (CSR 0x7C8 "
            "FIELD 2) while the live selector clk_src_r in "
            "KL_aecp_response_builder never was; both are now deleted. " +
            PLANE_DELETED,
    ),
    dict(
        key="omap", clause="5.3.9.1", pdf_line=2151,
        title="STREAM_PORT_OUTPUT channel mappings",
        quote="The PAAD-AE shall maintain a list of all its output channel "
              "mappings. This list shall be saved in a non-volatile memory and "
              "restored after a power cycle.",
        scope="per-descriptor", descriptor="STREAM_PORT_OUTPUT", width_words=0,
        read="AECP GET_AUDIO_MAP(STREAM_PORT_OUTPUT, idx, page) walk",
        restore=None,
        gap="the output dynamic-map store lived in "
            "KL_aecp_response_builder, written only by "
            "ADD/REMOVE_AUDIO_MAPPINGS, and is deleted with it. " +
            PLANE_DELETED,
    ),
    dict(
        key="imap", clause="5.3.10.1", pdf_line=2171,
        title="STREAM_PORT_INPUT channel mappings",
        quote="The PAAD-AE shall maintain a list of all its input channel "
              "mappings. This list shall be saved in a non-volatile memory and "
              "restored after a power cycle.",
        scope="per-descriptor", descriptor="STREAM_PORT_INPUT", width_words=0,
        read="AECP GET_AUDIO_MAP(STREAM_PORT_INPUT, idx, page) walk",
        restore=None,
        gap="the input dynamic-map store lived in "
            "KL_aecp_response_builder, written only by "
            "ADD/REMOVE_AUDIO_MAPPINGS, and is deleted with it. " +
            PLANE_DELETED,
    ),
    dict(
        key="names", clause="5.3.13", pdf_line=2255,
        title="User names (entity, configuration, cluster, clock domain, ...)",
        quote="All the names in the list above shall have a default value which "
              "is vendor-specific and shall be modifiable by the user. The "
              "PAAD-AE shall save them in a non-volatile memory and restore "
              "them after a power cycle.",
        scope="per-descriptor", descriptor="*", width_words=0,
        read="AECP GET_NAME(descriptor, index, name_index)",
        # The ENTITY descriptor's own name is the ONE exception: the fabric
        # serves it from the CSR overlay slot OVL_ENT_NAME8_C, driven by
        # 0x724/0x728, which S50milan already writes.  Everything else is a
        # SET_NAME write-back into the AEM store.
        restore=None,
        restore_note="was the ENTITY name only, via CSR 0x724/0x728 "
                     "(OVL_ENT_NAME8_C) served out of the AEM ROM's overlay "
                     "slot; every other descriptor's name needed the E4 port",
        gap="every name, including the ENTITY descriptor's: the overlay slot "
            "0x724/0x728 fed KL_aecp_aem_store's ROM image and nothing reads "
            "it now, and SET_NAME's own path (KL_aecp_accessor's "
            "descriptor-name pointer cone) is deleted with it. " +
            PLANE_DELETED,
    ),
    # ---- the two clauses that require the OPPOSITE ------------------------
    dict(
        key="locked", clause="5.3.4.1", pdf_line=1646,
        title="Locked state - MUST NOT persist",
        quote="The locked state is cleared by a power cycle.",
        scope="global", descriptor="ENTITY", width_words=0,
        read="AECP LOCK_ENTITY state",
        restore=None,
        gap="must NOT persist - a store that saved this would violate 5.3.4.1",
    ),
    dict(
        key="registered_ctlrs", clause="5.3.4.2", pdf_line=1676,
        title="Registered controller list - MUST NOT persist",
        quote="The list of registered controllers is cleared by a power cycle.",
        scope="global", descriptor="ENTITY", width_words=0,
        read="the unsolicited-notification registration table",
        restore=None,
        gap="must NOT persist - a store that saved this would violate 5.3.4.2",
    ),
]

#: Items whose obligation is "do not keep this", separated so no reader has to
#: parse prose to tell an unmet SHALL from a met SHALL-NOT.
MUST_NOT_PERSIST = {"locked", "registered_ctlrs"}


def restorable(item):
    """True when a saved value can actually be put back after a power cycle."""
    return item["restore"] is not None


def open_gaps():
    """Items Milan requires to survive that this build cannot restore."""
    return [i for i in PERSIST_ITEMS
            if i["key"] not in MUST_NOT_PERSIST and not restorable(i)]


def emit_sh():
    """The board-side include: the REFUSAL, plus the clause register.

    Deliberately data-only - no logic - so ``milan-persist`` owns the
    behaviour and this file owns the facts.

    ``MILAN_PERSIST_ITEMS`` is EMPTY (2026-08-12) and
    ``MILAN_PERSIST_SUPPORTED`` is 0: no item has a restore path, so a helper
    that loops over the item list correctly does nothing.  Saving records that
    can never be replayed is not a half-measure, it is a lie told in flash.
    The clause register moves to ``MILAN_PERSIST_INVENTORY`` so a compliance
    reporter still has the list.
    """
    res = _flash_reserved()
    jnl = res["journal"]
    live = [i["key"] for i in PERSIST_ITEMS
            if i["key"] not in MUST_NOT_PERSIST and restorable(i)]
    lines = [
        "# SPDX-License-Identifier: (GPL-2.0 OR MIT)",
        "# GENERATED by sw/persist/milan_persist_state.py - DO NOT EDIT BY HAND.",
        "# Regenerate, and let `milan_persist_state.py --check` prove the two",
        "# agree.  The Milan clause text this is derived from is quoted in the",
        "# generator; nothing here restates a clause number that is not also",
        "# there.",
        "#",
        "# THIS BUILD RESTORES NOTHING (2026-08-12).  The E3 persistence",
        "# journal (KL_persist_journal, CSR 0x7B8-0x7C4) and the E4 AEM patch",
        "# port (KL_aem_patch, CSR 0x7C8-0x7D4) are DELETED with the IEEE",
        "# 1722.1 control plane.  Both CSR groups still accept writes; the",
        "# writes land nowhere and JNL_STAT/JNL_SEQ read structural zeros.",
        "# So MILAN_PERSIST_SUPPORTED is 0 and MILAN_PERSIST_ITEMS is EMPTY:",
        "# a helper that iterates the item list does nothing, which is the",
        "# only honest behaviour when nothing can be put back.  Do not",
        "# 'fix' this by looping over MILAN_PERSIST_INVENTORY instead - that",
        "# is the clause register, not a work list.",
        "#",
        "# MILAN_PERSIST_SUPPORTED       1 iff any item can be restored",
        "# MILAN_PERSIST_ITEMS   record tags a helper may save+replay, in",
        "#                       image order (EMPTY while SUPPORTED=0)",
        "# MILAN_PERSIST_INVENTORY  every clause-mandated item, restorable or",
        "#                       not - for reporting, never for saving",
        "# MILAN_PERSIST_RESTORE_<tag>   fabric-journal | csr | none",
        "# MILAN_PERSIST_CLAUSE_<tag>    the clause that demands it",
        "# MILAN_PERSIST_GAP_<tag>       why it cannot be restored",
        "#",
        "# The flash geometry below is READ OUT OF FLASHBOOT_RESERVED in",
        "# sw/litex/milan_soc.py, the single source of truth the mtd partition",
        "# node is also generated from.  A board tool that hardcodes an offset",
        "# instead is how the shipping acmp-persist ended up journalling into",
        "# the `user` slot.  It is kept CURRENT even while nothing writes it:",
        "# a stale offset that comes back to life is the same defect twice.",
        "",
        f"MILAN_PERSIST_MAGIC=0x{KLS1_MAGIC:08X}",
        f"MILAN_PERSIST_FMT=0x{(KLS1_FMT_MAJOR << 16) | KLS1_FMT_MINOR:08X}",
        "",
        f"MILAN_JOURNAL_OFF=0x{jnl['offset']:X}",
        f"MILAN_JOURNAL_SIZE=0x{jnl['size']:X}",
        f"MILAN_USER_OFF=0x{res['user']['offset']:X}",
        f"MILAN_USER_SIZE=0x{res['user']['size']:X}",
        "",
        f"MILAN_PERSIST_SUPPORTED={1 if live else 0}",
        "MILAN_PERSIST_ITEMS=\"" + " ".join(live) + "\"",
        "MILAN_PERSIST_INVENTORY=\"" + " ".join(
            i["key"] for i in PERSIST_ITEMS
            if i["key"] not in MUST_NOT_PERSIST) + "\"",
        "MILAN_PERSIST_MUST_NOT=\"" + " ".join(sorted(MUST_NOT_PERSIST)) + "\"",
        "",
    ]
    for i in PERSIST_ITEMS:
        tag = i["key"]
        lines.append(f"MILAN_PERSIST_CLAUSE_{tag}=\"{i['clause']}\"")
        lines.append(f"MILAN_PERSIST_RESTORE_{tag}=\"{i['restore'] or 'none'}\"")
        lines.append(f"MILAN_PERSIST_TITLE_{tag}=\"{i['title']}\"")
        if i["gap"]:
            lines.append(f"MILAN_PERSIST_GAP_{tag}=\"{i['gap']}\"")
        lines.append("")
    return "\n".join(lines)


def emit_md():
    rows = ["| Clause | State | Scope | Restore path | Status |",
            "|---|---|---|---|---|"]
    # every OPEN row's status carries its own gap text, which since
    # 2026-08-12 ends in the same PLANE_DELETED sentence - so the table says
    # WHY without a reader having to hold a separate note in their head.
    for i in PERSIST_ITEMS:
        if i["key"] in MUST_NOT_PERSIST:
            status = "**must NOT persist** (satisfied: nothing saves it)"
            path = "n/a"
        elif restorable(i):
            status = "**restorable today**"
            path = i["restore"]
        else:
            status = f"**OPEN** - {i['gap']}"
            path = "none"
        rows.append(f"| {i['clause']} | {i['title']} | {i['scope']} "
                    f"| {path} | {status} |")
    return "\n".join(rows)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit-sh", action="store_true")
    ap.add_argument("--emit-json", action="store_true")
    ap.add_argument("--emit-md", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--gaps", action="store_true")
    a = ap.parse_args()
    if a.emit_json:
        print(json.dumps(PERSIST_ITEMS, indent=2))
        return
    if a.emit_md:
        print(emit_md())
        return
    if a.gaps:
        for i in open_gaps():
            print(f"{i['clause']:10s} {i['title']}\n           GAP: {i['gap']}")
        return
    text = emit_sh()
    if a.check:
        try:
            have = open(SH_OUT, encoding="utf-8").read()
        except OSError:
            sys.exit(f"milan_persist_state: {SH_OUT} is missing - regenerate it")
        if have != text:
            sys.exit("milan_persist_state: milan-persist-state.sh is STALE vs "
                     "PERSIST_ITEMS - regenerate it")
        print("milan_persist_state: OK - milan-persist-state.sh matches "
              "PERSIST_ITEMS")
        return
    with open(SH_OUT, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"milan_persist_state: wrote {SH_OUT}")
    #: and the copy the flashed image actually reads.  Written here rather
    #: than checked in twice by hand for the same reason the entity conf is:
    #: two copies of a generated fact rot independently and agree on day one.
    if os.path.isdir(ROOTFS_OVERLAY_ETC):
        dst = os.path.join(ROOTFS_OVERLAY_ETC, "milan-persist-state.sh")
        with open(dst, "w", encoding="utf-8") as f:
            f.write(text)
        print(f"milan_persist_state: wrote {dst}")
    else:
        print("milan_persist_state: rootfs overlay not on this disk "
              f"({ROOTFS_OVERLAY_ETC}) - board copy SKIPPED")


if __name__ == "__main__":
    main()
