# SPDX-License-Identifier: (GPL-2.0 OR MIT)
# GENERATED by sw/persist/milan_persist_state.py - DO NOT EDIT BY HAND.
# Regenerate, and let `milan_persist_state.py --check` prove the two
# agree.  The Milan clause text this is derived from is quoted in the
# generator; nothing here restates a clause number that is not also
# there.
#
# THIS BUILD RESTORES NOTHING (2026-08-12).  The E3 persistence
# journal (KL_persist_journal, CSR 0x7B8-0x7C4) and the E4 AEM patch
# port (KL_aem_patch, CSR 0x7C8-0x7D4) are DELETED with the IEEE
# 1722.1 control plane.  Both CSR groups still accept writes; the
# writes land nowhere and JNL_STAT/JNL_SEQ read structural zeros.
# So MILAN_PERSIST_SUPPORTED is 0 and MILAN_PERSIST_ITEMS is EMPTY:
# a helper that iterates the item list does nothing, which is the
# only honest behaviour when nothing can be put back.  Do not
# 'fix' this by looping over MILAN_PERSIST_INVENTORY instead - that
# is the clause register, not a work list.
#
# MILAN_PERSIST_SUPPORTED       1 iff any item can be restored
# MILAN_PERSIST_ITEMS   record tags a helper may save+replay, in
#                       image order (EMPTY while SUPPORTED=0)
# MILAN_PERSIST_INVENTORY  every clause-mandated item, restorable or
#                       not - for reporting, never for saving
# MILAN_PERSIST_RESTORE_<tag>   fabric-journal | csr | none
# MILAN_PERSIST_CLAUSE_<tag>    the clause that demands it
# MILAN_PERSIST_GAP_<tag>       why it cannot be restored
#
# The flash geometry below is READ OUT OF FLASHBOOT_RESERVED in
# sw/litex/milan_soc.py, the single source of truth the mtd partition
# node is also generated from.  A board tool that hardcodes an offset
# instead is how the shipping acmp-persist ended up journalling into
# the `user` slot.  It is kept CURRENT even while nothing writes it:
# a stale offset that comes back to life is the same defect twice.

MILAN_PERSIST_MAGIC=0x31534C4B
MILAN_PERSIST_FMT=0x00010000

MILAN_JOURNAL_OFF=0xEE0000
MILAN_JOURNAL_SIZE=0x20000
MILAN_USER_OFF=0xF00000
MILAN_USER_SIZE=0x100000

MILAN_PERSIST_SUPPORTED=0
MILAN_PERSIST_ITEMS=""
MILAN_PERSIST_INVENTORY="strin_fmt strout_fmt bound bind_params started pres_offset samp_rate clock_src omap imap names"
MILAN_PERSIST_MUST_NOT="locked registered_ctlrs"

MILAN_PERSIST_CLAUSE_strin_fmt="5.3.8.1"
MILAN_PERSIST_RESTORE_strin_fmt="none"
MILAN_PERSIST_TITLE_strin_fmt="STREAM_INPUT current format"
MILAN_PERSIST_GAP_strin_fmt="the E4 patch port (KL_aem_patch) and the AEM store it wrote into (KL_aecp_aem_store) are both deleted. 2026-08-12: the IEEE 1722.1 control plane is deleted, so this cannot be restored by any path. CSR 0x7B8-0x7C4 (E3 journal) and 0x7C8-0x7D4 (E4 AEM patch port) still accept writes and land nowhere; JNL_STAT/JNL_SEQ read structural zeros"

MILAN_PERSIST_CLAUSE_strout_fmt="5.3.7.1"
MILAN_PERSIST_RESTORE_strout_fmt="none"
MILAN_PERSIST_TITLE_strout_fmt="STREAM_OUTPUT current format"
MILAN_PERSIST_GAP_strout_fmt="the E4 patch port and the AEM store it wrote into are both deleted. 2026-08-12: the IEEE 1722.1 control plane is deleted, so this cannot be restored by any path. CSR 0x7B8-0x7C4 (E3 journal) and 0x7C8-0x7D4 (E4 AEM patch port) still accept writes and land nowhere; JNL_STAT/JNL_SEQ read structural zeros"

MILAN_PERSIST_CLAUSE_bound="5.3.8.2"
MILAN_PERSIST_RESTORE_bound="none"
MILAN_PERSIST_TITLE_bound="STREAM_INPUT bound state"
MILAN_PERSIST_GAP_bound="KL_persist_journal and the ACMP listener contexts it restored into are both deleted. 2026-08-12: the IEEE 1722.1 control plane is deleted, so this cannot be restored by any path. CSR 0x7B8-0x7C4 (E3 journal) and 0x7C8-0x7D4 (E4 AEM patch port) still accept writes and land nowhere; JNL_STAT/JNL_SEQ read structural zeros"

MILAN_PERSIST_CLAUSE_bind_params="5.3.8.3"
MILAN_PERSIST_RESTORE_bind_params="none"
MILAN_PERSIST_TITLE_bind_params="STREAM_INPUT binding parameters"
MILAN_PERSIST_GAP_bind_params="KL_persist_journal and the ACMP listener contexts it restored into are both deleted. 2026-08-12: the IEEE 1722.1 control plane is deleted, so this cannot be restored by any path. CSR 0x7B8-0x7C4 (E3 journal) and 0x7C8-0x7D4 (E4 AEM patch port) still accept writes and land nowhere; JNL_STAT/JNL_SEQ read structural zeros"

MILAN_PERSIST_CLAUSE_started="5.3.8.7"
MILAN_PERSIST_RESTORE_started="none"
MILAN_PERSIST_TITLE_started="STREAM_INPUT started/stopped state"
MILAN_PERSIST_GAP_started="KL_persist_journal and the ACMP listener contexts it restored into are both deleted. 2026-08-12: the IEEE 1722.1 control plane is deleted, so this cannot be restored by any path. CSR 0x7B8-0x7C4 (E3 journal) and 0x7C8-0x7D4 (E4 AEM patch port) still accept writes and land nowhere; JNL_STAT/JNL_SEQ read structural zeros"

MILAN_PERSIST_CLAUSE_pres_offset="5.3.7.6"
MILAN_PERSIST_RESTORE_pres_offset="none"
MILAN_PERSIST_TITLE_pres_offset="STREAM_OUTPUT presentation time offset"
MILAN_PERSIST_GAP_pres_offset="the presentation-offset file lived in KL_aecp_response_builder, which is deleted along with the E4 patch port that reserved FIELD 3 for it. 2026-08-12: the IEEE 1722.1 control plane is deleted, so this cannot be restored by any path. CSR 0x7B8-0x7C4 (E3 journal) and 0x7C8-0x7D4 (E4 AEM patch port) still accept writes and land nowhere; JNL_STAT/JNL_SEQ read structural zeros"

MILAN_PERSIST_CLAUSE_samp_rate="5.3.5.1"
MILAN_PERSIST_RESTORE_samp_rate="none"
MILAN_PERSIST_TITLE_samp_rate="AUDIO_UNIT current sampling rate"
MILAN_PERSIST_GAP_samp_rate="the E4 patch port and the AEM store it wrote into are both deleted. 2026-08-12: the IEEE 1722.1 control plane is deleted, so this cannot be restored by any path. CSR 0x7B8-0x7C4 (E3 journal) and 0x7C8-0x7D4 (E4 AEM patch port) still accept writes and land nowhere; JNL_STAT/JNL_SEQ read structural zeros"

MILAN_PERSIST_CLAUSE_clock_src="5.3.11.1"
MILAN_PERSIST_RESTORE_clock_src="none"
MILAN_PERSIST_TITLE_clock_src="CLOCK_DOMAIN current clock source"
MILAN_PERSIST_GAP_clock_src="the descriptor bytes were restorable via the E4 port (CSR 0x7C8 FIELD 2) while the live selector clk_src_r in KL_aecp_response_builder never was; both are now deleted. 2026-08-12: the IEEE 1722.1 control plane is deleted, so this cannot be restored by any path. CSR 0x7B8-0x7C4 (E3 journal) and 0x7C8-0x7D4 (E4 AEM patch port) still accept writes and land nowhere; JNL_STAT/JNL_SEQ read structural zeros"

MILAN_PERSIST_CLAUSE_omap="5.3.9.1"
MILAN_PERSIST_RESTORE_omap="none"
MILAN_PERSIST_TITLE_omap="STREAM_PORT_OUTPUT channel mappings"
MILAN_PERSIST_GAP_omap="the output dynamic-map store lived in KL_aecp_response_builder, written only by ADD/REMOVE_AUDIO_MAPPINGS, and is deleted with it. 2026-08-12: the IEEE 1722.1 control plane is deleted, so this cannot be restored by any path. CSR 0x7B8-0x7C4 (E3 journal) and 0x7C8-0x7D4 (E4 AEM patch port) still accept writes and land nowhere; JNL_STAT/JNL_SEQ read structural zeros"

MILAN_PERSIST_CLAUSE_imap="5.3.10.1"
MILAN_PERSIST_RESTORE_imap="none"
MILAN_PERSIST_TITLE_imap="STREAM_PORT_INPUT channel mappings"
MILAN_PERSIST_GAP_imap="the input dynamic-map store lived in KL_aecp_response_builder, written only by ADD/REMOVE_AUDIO_MAPPINGS, and is deleted with it. 2026-08-12: the IEEE 1722.1 control plane is deleted, so this cannot be restored by any path. CSR 0x7B8-0x7C4 (E3 journal) and 0x7C8-0x7D4 (E4 AEM patch port) still accept writes and land nowhere; JNL_STAT/JNL_SEQ read structural zeros"

MILAN_PERSIST_CLAUSE_names="5.3.13"
MILAN_PERSIST_RESTORE_names="none"
MILAN_PERSIST_TITLE_names="User names (entity, configuration, cluster, clock domain, ...)"
MILAN_PERSIST_GAP_names="every name, including the ENTITY descriptor's: the overlay slot 0x724/0x728 fed KL_aecp_aem_store's ROM image and nothing reads it now, and SET_NAME's own path (KL_aecp_accessor's descriptor-name pointer cone) is deleted with it. 2026-08-12: the IEEE 1722.1 control plane is deleted, so this cannot be restored by any path. CSR 0x7B8-0x7C4 (E3 journal) and 0x7C8-0x7D4 (E4 AEM patch port) still accept writes and land nowhere; JNL_STAT/JNL_SEQ read structural zeros"

MILAN_PERSIST_CLAUSE_locked="5.3.4.1"
MILAN_PERSIST_RESTORE_locked="none"
MILAN_PERSIST_TITLE_locked="Locked state - MUST NOT persist"
MILAN_PERSIST_GAP_locked="must NOT persist - a store that saved this would violate 5.3.4.1"

MILAN_PERSIST_CLAUSE_registered_ctlrs="5.3.4.2"
MILAN_PERSIST_RESTORE_registered_ctlrs="none"
MILAN_PERSIST_TITLE_registered_ctlrs="Registered controller list - MUST NOT persist"
MILAN_PERSIST_GAP_registered_ctlrs="must NOT persist - a store that saved this would violate 5.3.4.2"
