#!/usr/bin/env python3
"""Compare two gateware exports after removing run-specific text.

Usage: normalise_compare.py DIR_A ROOT_A DIR_B ROOT_B

Removed before comparing: each side's tree root and output directory (paths),
LiteX's date stamps, and LiteX's comment-only hierarchy tree in the top .v
(its box-drawing lines, and "//" lines after a "Hierarchy" banner), whose
order varies between runs. litex.log, a console transcript whose writers
interleave, is compared as a sorted list of its non-tree lines. Prints one line per file and exits 1 on any difference.
"""
import re
import sys
from pathlib import Path

STAMP = re.compile(r"(Auto-generated by LiteX \([0-9a-f]+\)) on \d{4}-\d\d-\d\d \d\d:\d\d:\d\d")
DATE = re.compile(r"\d{4}-\d\d-\d\d[ T]\d\d:\d\d:\d\d")
TREE = ("\u251c", "\u2514", "\u2502")  # the hierarchy tree's box-drawing glyphs


def norm(path: Path, root: Path, out: Path) -> list[str]:
    text = path.read_text(errors="replace")
    text = text.replace(str(out), "<OUT>").replace(str(root), "<ROOT>")
    text = STAMP.sub(r"\1 on <DATE>", text)
    text = DATE.sub("<DATE>", text)
    if path.name == "litex.log":
        # a console transcript: two writers interleave, so compare its lines as a set
        text = text.replace("VexiiRiscv netlist", "\nVexiiRiscv netlist")
        return sorted(ln for ln in text.splitlines() if ln.strip() and not any(g in ln for g in TREE))
    lines = text.splitlines()
    if path.suffix == ".v":
        lines = [ln for ln in lines if not any(g in ln for g in TREE)]
        kept, in_tree = [], False
        for ln in lines:
            if "Hierarchy" in ln and ln.lstrip().startswith("//"):
                in_tree = True
                continue
            if in_tree:
                if ln.lstrip().startswith("//") or not ln.strip():
                    continue
                in_tree = False
            kept.append(ln)
        lines = kept
    return lines


def main() -> int:
    a, ra, b, rb = (Path(x).resolve() for x in sys.argv[1:5])
    fa = sorted(p.relative_to(a) for p in a.rglob("*") if p.is_file())
    fb = sorted(p.relative_to(b) for p in b.rglob("*") if p.is_file())
    bad = 0
    if fa != fb:
        print(f"FILE SETS DIFFER: only A {sorted(set(fa) - set(fb))} only B {sorted(set(fb) - set(fa))}")
        bad += 1
    equal = 0
    for rel in sorted(set(fa) & set(fb)):
        same = norm(a / rel, ra, a) == norm(b / rel, rb, b)
        equal += same
        bad += 0 if same else 1
        print(f"{'equal' if same else 'DIFFER'} {rel}")
    print(f"{equal} of {len(set(fa) | set(fb))} files equal")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
