#!/usr/bin/env python3
"""Disposable mutation campaign for the #520 cache controls.

Each mutant is applied to a private copy of the exact-head tree (never to the
review clone), then the two named self-tests run in that copy:

  python3 syn/yosys/result_cache.py --selftest      (unit)
  python3 syn/yosys/cache_selftest.py               (unit + original live arms + ROM bank)

A mutant is KILLED when either exits non-zero. Each substitution must match
its anchor exactly once, so a mutant cannot silently become a no-op.

usage: mutate.py HEAD_COPY WORK_DIR OUT_JSON [MUTANT_ID...]   (default: all)
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

RC = "syn/yosys/result_cache.py"
SH = "syn/yosys/run.sh"
RT = "syn/yosys/rom_cache_selftest.py"

# id: (description, [(file, old, new), ...])
MUTANTS: dict[str, tuple[str, list[tuple[str, str, str]]]] = {
    "R1-fields-drop-rom": (
        "INPUT_FIELDS omits rom_sha256 (key and hit rule ignore the ROM bundle)",
        [(RC, '"yosys_sha256", "sv2v_version", "rom_sha256")', '"yosys_sha256", "sv2v_version")')]),
    "R2-key-ignores-rom": (
        "canonical() skips rom_sha256; hit rule still compares it",
        [(RC, "        for name in INPUT_FIELDS:\n            lines.append(",
              "        for name in INPUT_FIELDS:\n            if name == 'rom_sha256':\n                continue\n            lines.append(")]),
    "R3-verify-ignores-rom": (
        "verify_entry skips the recorded rom_sha256 comparison",
        [(RC, "    for name in INPUT_FIELDS:\n        want = getattr(inputs, name)",
              "    for name in INPUT_FIELDS:\n        if name == 'rom_sha256':\n            continue\n        want = getattr(inputs, name)")]),
    "R4-no-length-frame": (
        "rom_digest drops the 8-byte length frame",
        [(RC, "        digest.update(len(content).to_bytes(8, \"big\"))\n", "")]),
    "R5-no-name": (
        "rom_digest drops the NUL-terminated name",
        [(RC, "        digest.update(name.encode(\"ascii\") + b\"\\0\")\n", "")]),
    "R6-drop-gptp-image": (
        "ROM_IMAGES omits gptp_ucode.hex",
        [(RC, 'ROM_IMAGES = ("gptp_ucode.hex", "ltn_rom.hex", "ucode.hex")',
              'ROM_IMAGES = ("ltn_rom.hex", "ucode.hex")')]),
    "R6b-drop-ltn-image": (
        "ROM_IMAGES omits ltn_rom.hex",
        [(RC, 'ROM_IMAGES = ("gptp_ucode.hex", "ltn_rom.hex", "ucode.hex")',
              'ROM_IMAGES = ("gptp_ucode.hex", "ucode.hex")')]),
    "R7-glob-directory": (
        "rom_digest enumerates every *.hex in the directory instead of fixed names",
        [(RC, "    for name in ROM_IMAGES:\n        content = (directory / name).read_bytes()",
              "    for name in sorted(p.name for p in directory.glob('*.hex')):\n        content = (directory / name).read_bytes()")]),
    "R8-digest-arg-lax": (
        "digest_arg accepts any string",
        [(RC, "    if len(value) != 64 or any(char not in \"0123456789abcdef\" for char in value):",
              "    if False:")]),
    "R9-schema-not-advanced": (
        "SCHEMA left at schema 1 while adding the ROM field",
        [(RC, 'SCHEMA = "milan-yosys-result-cache/2"', 'SCHEMA = "milan-yosys-result-cache/1"')]),
    "R10-empty-digested": (
        "rom_digest accepts an empty image",
        [(RC, "        if not content:\n            raise ValueError", "        if False:\n            raise ValueError")]),
    "S1-constant-digest": (
        "run.sh passes a constant ROM digest (no binding to generated bytes)",
        [(SH, 'ROM_SHA256="$(python3 "$R/syn/yosys/result_cache.py" rom-digest --rom-dir "$TMP")" || {',
              'ROM_SHA256="$(printf %064d 0)" || {')]),
    "S2-generator-source-key": (
        "run.sh keys on generator SOURCE bytes rather than generated bytes",
        [(SH, 'ROM_SHA256="$(python3 "$R/syn/yosys/result_cache.py" rom-digest --rom-dir "$TMP")" || {',
              'ROM_SHA256="$(cat "$R/protocol-processor/hdl/acmp/rom/gen_ltn_rom.py" "$R/protocol-processor/hdl/aecp/ucode/gen_ucode.py" "$R/gptp-processor/hdl/ucode/gen_gptp_ucode.py" | sha256sum | cut -c1-64)" || {')]),
    "S3-seed-only-no-digest": (
        "run.sh computes the digest only with --cache, not with --cache-seed alone",
        [(SH, '  ROM_SHA256=""\n  if [ -n "$CACHE" ] || [ -n "$CACHE_SEED" ]; then',
              '  ROM_SHA256=""\n  if [ -n "$CACHE" ]; then')]),
    "S4-store-omits-rom": (
        "cache_store drops --rom-sha256",
        [(SH, "    --top \"$1\" --mode \"$MODE\" --sv2v-file \"$TMP/$1.v\" --program \"$2\" \\\n    --rom-sha256 \"$ROM_SHA256\" \\\n    --yosys-version \"$YOSYS_ID\" --yosys-bin-sha256 \"$YOSYS_BIN_SHA\" --sv2v-version \"$SV2V_ID\" \\\n    --cells",
              "    --top \"$1\" --mode \"$MODE\" --sv2v-file \"$TMP/$1.v\" --program \"$2\" \\\n    --yosys-version \"$YOSYS_ID\" --yosys-bin-sha256 \"$YOSYS_BIN_SHA\" --sv2v-version \"$SV2V_ID\" \\\n    --cells")]),
    "S5-store-other-digest": (
        "cache_store records a different digest than lookup uses",
        [(SH, "    --rom-sha256 \"$ROM_SHA256\" \\\n    --yosys-version \"$YOSYS_ID\" --yosys-bin-sha256 \"$YOSYS_BIN_SHA\" --sv2v-version \"$SV2V_ID\" \\\n    --cells",
              "    --rom-sha256 \"$(printf %064d 1)\" \\\n    --yosys-version \"$YOSYS_ID\" --yosys-bin-sha256 \"$YOSYS_BIN_SHA\" --sv2v-version \"$SV2V_ID\" \\\n    --cells")]),
    "S6-digest-before-nonempty": (
        "run.sh digests before the existing nonempty checks",
        [(SH, "  for image in \"$TMP/ltn_rom.hex\" \"$TMP/ucode.hex\" \"$TMP/gptp_ucode.hex\"; do\n    [ -s \"$image\" ] || { echo \"Yosys: generated ROM is empty: $image\" >&2; exit 2; }\n  done\n",
              "  ROM_SHA256=\"\"\n  if [ -n \"$CACHE\" ] || [ -n \"$CACHE_SEED\" ]; then\n    ROM_SHA256=\"$(python3 \"$R/syn/yosys/result_cache.py\" rom-digest --rom-dir \"$TMP\")\" || {\n      echo \"Yosys: generated ROM bundle could not be digested\" >&2; exit 2;\n    }\n  fi\n  for image in \"$TMP/ltn_rom.hex\" \"$TMP/ucode.hex\" \"$TMP/gptp_ucode.hex\"; do\n    [ -s \"$image\" ] || { echo \"Yosys: generated ROM is empty: $image\" >&2; exit 2; }\n  done\n")]),
    "S8-empty-check-removed": (
        "run.sh drops the existing nonempty loop (digest refusal would still stop cached runs)",
        [(SH, "    [ -s \"$image\" ] || { echo \"Yosys: generated ROM is empty: $image\" >&2; exit 2; }\n",
              "    :\n")]),
}


def apply(tree: Path, edits: list[tuple[str, str, str]]) -> None:
    for rel, old, new in edits:
        path = tree / rel
        text = path.read_text(encoding="utf-8")
        count = text.count(old)
        if count != 1:
            raise SystemExit(f"anchor matched {count} times in {rel}: {old[:60]!r}")
        path.write_text(text.replace(old, new), encoding="utf-8")


def run_one(head: Path, work: Path, mid: str) -> dict:
    desc, edits = MUTANTS[mid]
    tree = work / mid
    if tree.exists():
        shutil.rmtree(tree)
    shutil.copytree(head, tree, symlinks=True)
    apply(tree, edits)
    result = {"id": mid, "description": desc}
    for label, cmd in (("unit", ["python3", RC, "--selftest"]),
                       ("integration", ["python3", "syn/yosys/cache_selftest.py", "--logs", str(work / f"{mid}.logs")])):
        start = time.monotonic()
        proc = subprocess.run(cmd, cwd=tree, capture_output=True, text=True)
        out = (proc.stdout + proc.stderr).replace(str(work), "<work>")
        result[label] = {"exit": proc.returncode, "seconds": round(time.monotonic() - start, 1),
                         "tail": [l[:300] for l in out.splitlines() if "FAIL" in l or "OK" in l][:6]}
        (work / f"{mid}.{label}.log").write_text(out, encoding="utf-8")
    result["killed"] = result["unit"]["exit"] != 0 or result["integration"]["exit"] != 0
    shutil.rmtree(tree)
    return result


def main(argv: list[str]) -> int:
    head, work, out, *ids = argv
    head, work = Path(head), Path(work)
    work.mkdir(parents=True, exist_ok=True)
    ids = ids or list(MUTANTS)
    with ThreadPoolExecutor(max_workers=6) as pool:
        results = list(pool.map(lambda m: run_one(head, work, m), ids))
    Path(out).write_text(json.dumps(results, indent=2) + "\n", encoding="utf-8")
    for r in results:
        print(f"{r['id']:34s} unit={r['unit']['exit']} integ={r['integration']['exit']} "
              f"{'KILLED' if r['killed'] else 'SURVIVED'}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
