#!/usr/bin/python3 -S
import sys
sys.path.insert(0, '$WORKSPACE_HOME/milan-fpga-management/2026-09-22/517-f1-author/final-backpressure/make-flush-SIGTERM-repeated')
import fake_leg
fake_leg.main({'out': [['out', 'L8 partial\n']], 'name': 'L8', 'ledger': '$WORKSPACE_HOME/milan-fpga-management/2026-09-22/517-f1-author/final-backpressure/make-flush-SIGTERM-repeated/ledger.jsonl', 'announce': '$WORKSPACE_HOME/milan-fpga-management/2026-09-22/517-f1-author/final-backpressure/make-flush-SIGTERM-repeated/announce.fifo'})
