// SPDX-FileCopyrightText: 2026 Kebag Logic
// SPDX-License-Identifier: CERN-OHL-W-2.0
//
// GENERATED by sw/mailbox/gen_mailbox.py from sw/mailbox/mailbox.yaml; DO NOT EDIT.
// Regenerate with: python3 sw/mailbox/gen_mailbox.py --write
//
// hdl/milan/mailbox/KL_mbx_pkg.sv: the packet-mailbox contract (#665 lane F0).
//
// Every constant is `MBX_<name>_C`, the C header's `MBX_<name>`. The
// tables at the end list those names by channel id, so the RTL can index
// a channel at run time without restating a number.

`default_nettype none

package KL_mbx_pkg;

  //! contract major version
  localparam int unsigned MBX_VERSION_MAJOR_C = 32'd1;
  //! contract minor version
  localparam int unsigned MBX_VERSION_MINOR_C = 32'd0;
  //! ID.MAGIC
  localparam int unsigned MBX_MAGIC_C = 32'h00004D42;
  //! host window size
  localparam int unsigned MBX_WINDOW_BYTES_C = 32'h00008000;
  //! registers live below this offset
  localparam int unsigned MBX_REGISTER_SPACE_BYTES_C = 32'h00000400;
  //! interfaces
  localparam int unsigned MBX_N_IF_C = 32'd1;
  //! timer slots
  localparam int unsigned MBX_N_TIMERS_C = 32'd16;
  //! NOW_MS milliseconds per TICK (one centisecond)
  localparam int unsigned MBX_TICK_MS_C = 32'd10;
  //! channels
  localparam int unsigned MBX_N_CH_C = 32'd5;
  //! ring counter width
  localparam int unsigned MBX_INDEX_BITS_C = 32'd16;
  //! accept terms per channel
  localparam int unsigned MBX_MAX_TERMS_C = 32'd2;
  //! bytes a filter term reads
  localparam int unsigned MBX_TERM_FIELD_BYTES_C = 32'd8;
  //! wire byte of the EtherType
  localparam int unsigned MBX_ETHERTYPE_BYTE_C = 32'd12;
  //! wire byte of the AVTP subtype
  localparam int unsigned MBX_SUBTYPE_BYTE_C = 32'd14;
  //! wire byte whose low nibble is message_type
  localparam int unsigned MBX_MSG_TYPE_BYTE_C = 32'd15;
  //! never (an unused term)
  localparam int unsigned MBX_TEST_NONE_C = 32'd0;
  //! always
  localparam int unsigned MBX_TEST_ANY_C = 32'd1;
  //! the 8-byte big-endian field equals OWN_EID
  localparam int unsigned MBX_TEST_EQ_OWN_C = 32'd2;
  //! the 8-byte field is 0
  localparam int unsigned MBX_TEST_EQ_ZERO_C = 32'd3;
  //! the 6-byte start and 2-byte count overlap [MAAP_BASE, MAAP_BASE + MAAP_COUNT - 1]
  localparam int unsigned MBX_TEST_RANGE_OVERLAP_C = 32'd4;
  //! TMR_CMD.OP arm
  localparam int unsigned MBX_TMR_OP_ARM_C = 32'd1;
  //! TMR_CMD.OP cancel
  localparam int unsigned MBX_TMR_OP_CANCEL_C = 32'd2;
  //! Contract identity. Firmware checks MAGIC and MAJOR before it opens a channel.
  localparam int unsigned MBX_REG_ID_C = 32'h00000000;
  //! ID: contract minor version
  localparam int unsigned MBX_ID_MINOR_LSB_C = 32'd0;
  //! ID: contract minor version
  localparam int unsigned MBX_ID_MINOR_WIDTH_C = 32'd8;
  //! ID: contract major version
  localparam int unsigned MBX_ID_MAJOR_LSB_C = 32'd8;
  //! ID: contract major version
  localparam int unsigned MBX_ID_MAJOR_WIDTH_C = 32'd8;
  //! ID: 0x4D42
  localparam int unsigned MBX_ID_MAGIC_LSB_C = 32'd16;
  //! ID: 0x4D42
  localparam int unsigned MBX_ID_MAGIC_WIDTH_C = 32'd16;
  //! What this build elaborated.
  localparam int unsigned MBX_REG_CAPS_C = 32'h00000004;
  //! CAPS: channel count
  localparam int unsigned MBX_CAPS_N_CH_LSB_C = 32'd0;
  //! CAPS: channel count
  localparam int unsigned MBX_CAPS_N_CH_WIDTH_C = 32'd4;
  //! CAPS: interface count
  localparam int unsigned MBX_CAPS_N_IF_LSB_C = 32'd4;
  //! CAPS: interface count
  localparam int unsigned MBX_CAPS_N_IF_WIDTH_C = 32'd4;
  //! CAPS: timer slots
  localparam int unsigned MBX_CAPS_N_TIMERS_LSB_C = 32'd8;
  //! CAPS: timer slots
  localparam int unsigned MBX_CAPS_N_TIMERS_WIDTH_C = 32'd8;
  //! CAPS: event ring size
  localparam int unsigned MBX_CAPS_EVT_WORDS_LOG2_LSB_C = 32'd16;
  //! CAPS: event ring size
  localparam int unsigned MBX_CAPS_EVT_WORDS_LOG2_WIDTH_C = 32'd4;
  //! The interrupt causes. RX and EVT are levels: they stay set while the ring holds an unconsumed record and clear when the core advances its tail. ERR is sticky and cleared by writing 1.
  localparam int unsigned MBX_REG_IRQ_STATUS_C = 32'h00000008;
  //! IRQ_STATUS: bit c: channel c's receive ring is not empty (level)
  localparam int unsigned MBX_IRQ_STATUS_RX_LSB_C = 32'd0;
  //! IRQ_STATUS: bit c: channel c's receive ring is not empty (level)
  localparam int unsigned MBX_IRQ_STATUS_RX_WIDTH_C = 32'd8;
  //! IRQ_STATUS: the event ring is not empty (level)
  localparam int unsigned MBX_IRQ_STATUS_EVT_LSB_C = 32'd8;
  //! IRQ_STATUS: the event ring is not empty (level)
  localparam int unsigned MBX_IRQ_STATUS_EVT_WIDTH_C = 32'd1;
  //! IRQ_STATUS: a drop or error counter moved (sticky
  localparam int unsigned MBX_IRQ_STATUS_ERR_LSB_C = 32'd31;
  //! IRQ_STATUS: a drop or error counter moved (sticky
  localparam int unsigned MBX_IRQ_STATUS_ERR_WIDTH_C = 32'd1;
  //! The interrupt line is the OR of IRQ_STATUS AND IRQ_ENABLE. Reset 0.
  localparam int unsigned MBX_REG_IRQ_ENABLE_C = 32'h0000000C;
  //! IRQ_ENABLE: per-channel enable
  localparam int unsigned MBX_IRQ_ENABLE_RX_LSB_C = 32'd0;
  //! IRQ_ENABLE: per-channel enable
  localparam int unsigned MBX_IRQ_ENABLE_RX_WIDTH_C = 32'd8;
  //! IRQ_ENABLE: event ring enable
  localparam int unsigned MBX_IRQ_ENABLE_EVT_LSB_C = 32'd8;
  //! IRQ_ENABLE: event ring enable
  localparam int unsigned MBX_IRQ_ENABLE_EVT_WIDTH_C = 32'd1;
  //! IRQ_ENABLE: error enable
  localparam int unsigned MBX_IRQ_ENABLE_ERR_LSB_C = 32'd31;
  //! IRQ_ENABLE: error enable
  localparam int unsigned MBX_IRQ_ENABLE_ERR_WIDTH_C = 32'd1;
  //! Free-running fabric millisecond counter, the time base of every timer deadline.
  localparam int unsigned MBX_REG_NOW_MS_C = 32'h00000010;
  //! NOW_MS: milliseconds since reset
  localparam int unsigned MBX_NOW_MS_MS_LSB_C = 32'd0;
  //! NOW_MS: milliseconds since reset
  localparam int unsigned MBX_NOW_MS_MS_WIDTH_C = 32'd32;
  //! Current link level per interface.
  localparam int unsigned MBX_REG_LINK_C = 32'h00000014;
  //! LINK: bit i: interface i link up
  localparam int unsigned MBX_LINK_UP_LSB_C = 32'd0;
  //! LINK: bit i: interface i link up
  localparam int unsigned MBX_LINK_UP_WIDTH_C = 32'd4;
  //! The centisecond tick. Reset 0. While EN is set the fabric counts one tick every tick_ms milliseconds of NOW_MS and posts TICK events carrying the ticks elapsed since the previous TICK record, so the firmware calls its centisecond timer port (lwSRP's shlan_timer_tick) once per tick counted and loses none when it is late. Clearing EN drops the unposted count.
  localparam int unsigned MBX_REG_TICK_CTL_C = 32'h00000018;
  //! TICK_CTL: post TICK events
  localparam int unsigned MBX_TICK_CTL_EN_LSB_C = 32'd0;
  //! TICK_CTL: post TICK events
  localparam int unsigned MBX_TICK_CTL_EN_WIDTH_C = 32'd1;
  //! The filter's entity_id, low word. Reset 0; firmware writes it before it opens a channel.
  localparam int unsigned MBX_REG_OWN_EID_LO_C = 32'h00000020;
  //! OWN_EID_LO: entity_id[31:0]
  localparam int unsigned MBX_OWN_EID_LO_EID_LSB_C = 32'd0;
  //! OWN_EID_LO: entity_id[31:0]
  localparam int unsigned MBX_OWN_EID_LO_EID_WIDTH_C = 32'd32;
  //! The filter's entity_id, high word.
  localparam int unsigned MBX_REG_OWN_EID_HI_C = 32'h00000024;
  //! OWN_EID_HI: entity_id[63:32]
  localparam int unsigned MBX_OWN_EID_HI_EID_LSB_C = 32'd0;
  //! OWN_EID_HI: entity_id[63:32]
  localparam int unsigned MBX_OWN_EID_HI_EID_WIDTH_C = 32'd32;
  //! Bit c opens channel c. Reset 0: every channel is closed and its frames are dropped uncounted until the firmware has written OWN_EID and opened it.
  localparam int unsigned MBX_REG_FILTER_EN_C = 32'h00000028;
  //! FILTER_EN: per-channel open
  localparam int unsigned MBX_FILTER_EN_OPEN_LSB_C = 32'd0;
  //! FILTER_EN: per-channel open
  localparam int unsigned MBX_FILTER_EN_OPEN_WIDTH_C = 32'd8;
  //! The MAAP range this entity probes or holds, low 32 bits of the first address.
  localparam int unsigned MBX_REG_MAAP_BASE_LO_C = 32'h0000002C;
  //! MAAP_BASE_LO: first address[31:0]
  localparam int unsigned MBX_MAAP_BASE_LO_ADDR_LSB_C = 32'd0;
  //! MAAP_BASE_LO: first address[31:0]
  localparam int unsigned MBX_MAAP_BASE_LO_ADDR_WIDTH_C = 32'd32;
  //! The MAAP range, high 16 bits of the first address.
  localparam int unsigned MBX_REG_MAAP_BASE_HI_C = 32'h00000030;
  //! MAAP_BASE_HI: first address[47:32]
  localparam int unsigned MBX_MAAP_BASE_HI_ADDR_LSB_C = 32'd0;
  //! MAAP_BASE_HI: first address[47:32]
  localparam int unsigned MBX_MAAP_BASE_HI_ADDR_WIDTH_C = 32'd16;
  //! Addresses in the MAAP range. 0 means no range, and no MAAP frame passes.
  localparam int unsigned MBX_REG_MAAP_COUNT_C = 32'h00000034;
  //! MAAP_COUNT: address count
  localparam int unsigned MBX_MAAP_COUNT_COUNT_LSB_C = 32'd0;
  //! MAAP_COUNT: address count
  localparam int unsigned MBX_MAAP_COUNT_COUNT_WIDTH_C = 32'd16;
  //! The deadline the next TMR_CMD arm uses, in NOW_MS units.
  localparam int unsigned MBX_REG_TMR_DEADLINE_C = 32'h00000038;
  //! TMR_DEADLINE: absolute deadline
  localparam int unsigned MBX_TMR_DEADLINE_MS_LSB_C = 32'd0;
  //! TMR_DEADLINE: absolute deadline
  localparam int unsigned MBX_TMR_DEADLINE_MS_WIDTH_C = 32'd32;
  //! A write arms or cancels one timer slot. An arm replaces whatever the slot held and drops its unposted expiry; a cancel disarms it and drops its unposted expiry. An expiry already in the event ring stays there and carries the tag of the arm it belongs to. Any other OP is refused and counted in BUS_ERR.
  localparam int unsigned MBX_REG_TMR_CMD_C = 32'h0000003C;
  //! TMR_CMD: timer slot
  localparam int unsigned MBX_TMR_CMD_SLOT_LSB_C = 32'd0;
  //! TMR_CMD: timer slot
  localparam int unsigned MBX_TMR_CMD_SLOT_WIDTH_C = 32'd8;
  //! TMR_CMD: firmware tag
  localparam int unsigned MBX_TMR_CMD_TAG_LSB_C = 32'd8;
  //! TMR_CMD: firmware tag
  localparam int unsigned MBX_TMR_CMD_TAG_WIDTH_C = 32'd16;
  //! TMR_CMD: 1 arm, 2 cancel
  localparam int unsigned MBX_TMR_CMD_OP_LSB_C = 32'd30;
  //! TMR_CMD: 1 arm, 2 cancel
  localparam int unsigned MBX_TMR_CMD_OP_WIDTH_C = 32'd2;
  //! Words the fabric has written into the event ring, modulo 2^16.
  localparam int unsigned MBX_REG_EVT_HEAD_C = 32'h00000060;
  //! EVT_HEAD: producer count
  localparam int unsigned MBX_EVT_HEAD_WORDS_LSB_C = 32'd0;
  //! EVT_HEAD: producer count
  localparam int unsigned MBX_EVT_HEAD_WORDS_WIDTH_C = 32'd16;
  //! Words the core has consumed from the event ring. Writing it releases the space. A value more than the ring behind EVT_HEAD, or ahead of it, leaves no free word: nothing posts until it is back in range.
  localparam int unsigned MBX_REG_EVT_TAIL_C = 32'h00000064;
  //! EVT_TAIL: consumer count
  localparam int unsigned MBX_EVT_TAIL_WORDS_LSB_C = 32'd0;
  //! EVT_TAIL: consumer count
  localparam int unsigned MBX_EVT_TAIL_WORDS_WIDTH_C = 32'd16;
  //! Host accesses refused, saturating. A write with a partial byte strobe and a bad TMR_CMD are refused.
  localparam int unsigned MBX_REG_BUS_ERR_C = 32'h00000070;
  //! BUS_ERR: refusals
  localparam int unsigned MBX_BUS_ERR_COUNT_LSB_C = 32'd0;
  //! BUS_ERR: refusals
  localparam int unsigned MBX_BUS_ERR_COUNT_WIDTH_C = 32'd16;
  //! first interface register block
  localparam int unsigned MBX_IF_BASE_C = 32'h00000040;
  //! bytes per interface block
  localparam int unsigned MBX_IF_STRIDE_C = 32'h00000010;
  //! Grandmaster identity, low word. Reading it snapshots GM_HI and DOMAIN, so the next two reads are coherent with it (the CSR window's convention).
  localparam int unsigned MBX_IF_REG_GM_LO_C = 32'h00000000;
  //! GM_LO: gptp_grandmaster_id[31:0]
  localparam int unsigned MBX_GM_LO_ID_LSB_C = 32'd0;
  //! GM_LO: gptp_grandmaster_id[31:0]
  localparam int unsigned MBX_GM_LO_ID_WIDTH_C = 32'd32;
  //! Grandmaster identity, high word, from the snapshot.
  localparam int unsigned MBX_IF_REG_GM_HI_C = 32'h00000004;
  //! GM_HI: gptp_grandmaster_id[63:32]
  localparam int unsigned MBX_GM_HI_ID_LSB_C = 32'd0;
  //! GM_HI: gptp_grandmaster_id[63:32]
  localparam int unsigned MBX_GM_HI_ID_WIDTH_C = 32'd32;
  //! gPTP domain number, from the snapshot.
  localparam int unsigned MBX_IF_REG_DOMAIN_C = 32'h00000008;
  //! DOMAIN: gptp_domain_number
  localparam int unsigned MBX_DOMAIN_NUMBER_LSB_C = 32'd0;
  //! DOMAIN: gptp_domain_number
  localparam int unsigned MBX_DOMAIN_NUMBER_WIDTH_C = 32'd8;
  //! first channel register block
  localparam int unsigned MBX_CH_BASE_C = 32'h00000100;
  //! bytes per channel block
  localparam int unsigned MBX_CH_STRIDE_C = 32'h00000020;
  //! Words the fabric has committed into the receive ring, modulo 2^16.
  localparam int unsigned MBX_CH_REG_RX_HEAD_C = 32'h00000000;
  //! RX_HEAD: producer count
  localparam int unsigned MBX_RX_HEAD_WORDS_LSB_C = 32'd0;
  //! RX_HEAD: producer count
  localparam int unsigned MBX_RX_HEAD_WORDS_WIDTH_C = 32'd16;
  //! Words the core has consumed. Writing it releases the space (the RX doorbell). A value more than the ring behind RX_HEAD, or ahead of it, leaves no free word: every frame counts in RX_DROP until it is back in range.
  localparam int unsigned MBX_CH_REG_RX_TAIL_C = 32'h00000004;
  //! RX_TAIL: consumer count
  localparam int unsigned MBX_RX_TAIL_WORDS_LSB_C = 32'd0;
  //! RX_TAIL: consumer count
  localparam int unsigned MBX_RX_TAIL_WORDS_WIDTH_C = 32'd16;
  //! Words the core has committed into the transmit ring. Writing it is the TX doorbell. A value more than the ring ahead of TX_TAIL is refused like a malformed record.
  localparam int unsigned MBX_CH_REG_TX_HEAD_C = 32'h00000008;
  //! TX_HEAD: producer count
  localparam int unsigned MBX_TX_HEAD_WORDS_LSB_C = 32'd0;
  //! TX_HEAD: producer count
  localparam int unsigned MBX_TX_HEAD_WORDS_WIDTH_C = 32'd16;
  //! Words the fabric has consumed from the transmit ring.
  localparam int unsigned MBX_CH_REG_TX_TAIL_C = 32'h0000000C;
  //! TX_TAIL: consumer count
  localparam int unsigned MBX_TX_TAIL_WORDS_LSB_C = 32'd0;
  //! TX_TAIL: consumer count
  localparam int unsigned MBX_TX_TAIL_WORDS_WIDTH_C = 32'd16;
  //! Frames the channel accepted but could not store (ring full or over max_frame_bytes), saturating.
  localparam int unsigned MBX_CH_REG_RX_DROP_C = 32'h00000010;
  //! RX_DROP: frames
  localparam int unsigned MBX_RX_DROP_COUNT_LSB_C = 32'd0;
  //! RX_DROP: frames
  localparam int unsigned MBX_RX_DROP_COUNT_WIDTH_C = 32'd16;
  //! Frames the channel's rate limiter refused, saturating.
  localparam int unsigned MBX_CH_REG_RATE_DROP_C = 32'h00000014;
  //! RATE_DROP: frames
  localparam int unsigned MBX_RATE_DROP_COUNT_LSB_C = 32'd0;
  //! RATE_DROP: frames
  localparam int unsigned MBX_RATE_DROP_COUNT_WIDTH_C = 32'd16;
  //! TX records the fabric refused, saturating. A refused record flushes the ring to TX_HEAD.
  localparam int unsigned MBX_CH_REG_TX_ERR_C = 32'h00000018;
  //! TX_ERR: records
  localparam int unsigned MBX_TX_ERR_COUNT_LSB_C = 32'd0;
  //! TX_ERR: records
  localparam int unsigned MBX_TX_ERR_COUNT_WIDTH_C = 32'd16;
  //! Frames committed into the receive ring, modulo 2^16.
  localparam int unsigned MBX_CH_REG_RX_PASS_C = 32'h0000001C;
  //! RX_PASS: frames
  localparam int unsigned MBX_RX_PASS_COUNT_LSB_C = 32'd0;
  //! RX_PASS: frames
  localparam int unsigned MBX_RX_PASS_COUNT_WIDTH_C = 32'd16;
  //! KIND of an RX frame record
  localparam int unsigned MBX_RX_KIND_C = 32'd1;
  //! header words of an RX record
  localparam int unsigned MBX_RX_HDR_WORDS_C = 32'd2;
  //! KIND of a TX frame record
  localparam int unsigned MBX_TX_KIND_C = 32'd2;
  //! header words of a TX record
  localparam int unsigned MBX_TX_HDR_WORDS_C = 32'd2;
  //! words per event record
  localparam int unsigned MBX_EV_WORDS_C = 32'd4;
  //! event ring byte offset
  localparam int unsigned MBX_EVT_BASE_C = 32'h00000400;
  //! event ring words
  localparam int unsigned MBX_EVT_WORDS_C = 32'd64;
  //! RX record word 0: frame bytes
  localparam int unsigned MBX_RXREC_W0_LEN_LSB_C = 32'd0;
  //! RX record word 0: frame bytes
  localparam int unsigned MBX_RXREC_W0_LEN_WIDTH_C = 32'd16;
  //! RX record word 0: interface the frame arrived on
  localparam int unsigned MBX_RXREC_W0_IF_LSB_C = 32'd16;
  //! RX record word 0: interface the frame arrived on
  localparam int unsigned MBX_RXREC_W0_IF_WIDTH_C = 32'd4;
  //! RX record word 0: 1
  localparam int unsigned MBX_RXREC_W0_KIND_LSB_C = 32'd28;
  //! RX record word 0: 1
  localparam int unsigned MBX_RXREC_W0_KIND_WIDTH_C = 32'd4;
  //! RX record word 1: NOW_MS when the frame's last byte arrived
  localparam int unsigned MBX_RXREC_W1_ARRIVAL_MS_LSB_C = 32'd0;
  //! RX record word 1: NOW_MS when the frame's last byte arrived
  localparam int unsigned MBX_RXREC_W1_ARRIVAL_MS_WIDTH_C = 32'd32;
  //! TX record word 0: frame bytes
  localparam int unsigned MBX_TXREC_W0_LEN_LSB_C = 32'd0;
  //! TX record word 0: frame bytes
  localparam int unsigned MBX_TXREC_W0_LEN_WIDTH_C = 32'd16;
  //! TX record word 0: interface to send on
  localparam int unsigned MBX_TXREC_W0_IF_LSB_C = 32'd16;
  //! TX record word 0: interface to send on
  localparam int unsigned MBX_TXREC_W0_IF_WIDTH_C = 32'd4;
  //! TX record word 0: 2
  localparam int unsigned MBX_TXREC_W0_KIND_LSB_C = 32'd28;
  //! TX record word 0: 2
  localparam int unsigned MBX_TXREC_W0_KIND_WIDTH_C = 32'd4;
  //! TX record word 1: commit sequence: the core's count of TX records committed on every channel, modulo 2^16
  localparam int unsigned MBX_TXREC_W1_SEQ_LSB_C = 32'd0;
  //! TX record word 1: commit sequence: the core's count of TX records committed on every channel, modulo 2^16
  localparam int unsigned MBX_TXREC_W1_SEQ_WIDTH_C = 32'd16;
  //! TX record word 1: must be 0; any other value refuses the record
  localparam int unsigned MBX_TXREC_W1_RSVD_LSB_C = 32'd16;
  //! TX record word 1: must be 0; any other value refuses the record
  localparam int unsigned MBX_TXREC_W1_RSVD_WIDTH_C = 32'd16;
  //! event word 0: event type
  localparam int unsigned MBX_EVREC_W0_TYPE_LSB_C = 32'd0;
  //! event word 0: event type
  localparam int unsigned MBX_EVREC_W0_TYPE_WIDTH_C = 32'd8;
  //! event word 0: interface
  localparam int unsigned MBX_EVREC_W0_IF_LSB_C = 32'd8;
  //! event word 0: interface
  localparam int unsigned MBX_EVREC_W0_IF_WIDTH_C = 32'd4;
  //! event word 0: posting sequence
  localparam int unsigned MBX_EVREC_W0_SEQ_LSB_C = 32'd16;
  //! event word 0: posting sequence
  localparam int unsigned MBX_EVREC_W0_SEQ_WIDTH_C = 32'd16;
  //! A timer slot's deadline passed.
  localparam int unsigned MBX_EV_TYPE_TIMER_C = 32'd1;
  //! TIMER event word 1: the tag of the arm that expired
  localparam int unsigned MBX_EV_TIMER_W1_TAG_LSB_C = 32'd0;
  //! TIMER event word 1: the tag of the arm that expired
  localparam int unsigned MBX_EV_TIMER_W1_TAG_WIDTH_C = 32'd16;
  //! TIMER event word 1: timer slot
  localparam int unsigned MBX_EV_TIMER_W1_SLOT_LSB_C = 32'd16;
  //! TIMER event word 1: timer slot
  localparam int unsigned MBX_EV_TIMER_W1_SLOT_WIDTH_C = 32'd8;
  //! TIMER event word 2: the armed deadline
  localparam int unsigned MBX_EV_TIMER_W2_DEADLINE_MS_LSB_C = 32'd0;
  //! TIMER event word 2: the armed deadline
  localparam int unsigned MBX_EV_TIMER_W2_DEADLINE_MS_WIDTH_C = 32'd32;
  //! TIMER event word 3: NOW_MS at posting
  localparam int unsigned MBX_EV_TIMER_W3_NOW_MS_LSB_C = 32'd0;
  //! TIMER event word 3: NOW_MS at posting
  localparam int unsigned MBX_EV_TIMER_W3_NOW_MS_WIDTH_C = 32'd32;
  //! The interface's link level changed.
  localparam int unsigned MBX_EV_TYPE_LINK_C = 32'd2;
  //! LINK event word 1: link level at posting
  localparam int unsigned MBX_EV_LINK_W1_UP_LSB_C = 32'd0;
  //! LINK event word 1: link level at posting
  localparam int unsigned MBX_EV_LINK_W1_UP_WIDTH_C = 32'd1;
  //! LINK event word 3: NOW_MS at posting
  localparam int unsigned MBX_EV_LINK_W3_NOW_MS_LSB_C = 32'd0;
  //! LINK event word 3: NOW_MS at posting
  localparam int unsigned MBX_EV_LINK_W3_NOW_MS_WIDTH_C = 32'd32;
  //! The gPTP plane published a grandmaster change on the interface.
  localparam int unsigned MBX_EV_TYPE_GM_C = 32'd3;
  //! GM event word 1: gptp_grandmaster_id[31:0] at posting
  localparam int unsigned MBX_EV_GM_W1_ID_LO_LSB_C = 32'd0;
  //! GM event word 1: gptp_grandmaster_id[31:0] at posting
  localparam int unsigned MBX_EV_GM_W1_ID_LO_WIDTH_C = 32'd32;
  //! GM event word 2: gptp_grandmaster_id[63:32] at posting
  localparam int unsigned MBX_EV_GM_W2_ID_HI_LSB_C = 32'd0;
  //! GM event word 2: gptp_grandmaster_id[63:32] at posting
  localparam int unsigned MBX_EV_GM_W2_ID_HI_WIDTH_C = 32'd32;
  //! GM event word 3: gptp_domain_number at posting
  localparam int unsigned MBX_EV_GM_W3_DOMAIN_LSB_C = 32'd0;
  //! GM event word 3: gptp_domain_number at posting
  localparam int unsigned MBX_EV_GM_W3_DOMAIN_WIDTH_C = 32'd8;
  //! Centiseconds elapsed (TICK_CTL.EN set). COUNT is the ticks counted since the previous TICK record, at least 1 and saturating; the firmware calls its centisecond timer port COUNT times.
  localparam int unsigned MBX_EV_TYPE_TICK_C = 32'd4;
  //! TICK event word 1: ticks since the previous TICK record
  localparam int unsigned MBX_EV_TICK_W1_COUNT_LSB_C = 32'd0;
  //! TICK event word 1: ticks since the previous TICK record
  localparam int unsigned MBX_EV_TICK_W1_COUNT_WIDTH_C = 32'd16;
  //! TICK event word 3: NOW_MS at posting
  localparam int unsigned MBX_EV_TICK_W3_NOW_MS_LSB_C = 32'd0;
  //! TICK event word 3: NOW_MS at posting
  localparam int unsigned MBX_EV_TICK_W3_NOW_MS_WIDTH_C = 32'd32;
  //! channel adp
  localparam int unsigned MBX_CH_ADP_C = 32'd0;
  //! adp receive ring byte offset
  localparam int unsigned MBX_CH_ADP_RX_BASE_C = 32'h00001000;
  //! adp receive ring words
  localparam int unsigned MBX_CH_ADP_RX_WORDS_C = 32'd256;
  //! adp transmit ring byte offset
  localparam int unsigned MBX_CH_ADP_TX_BASE_C = 32'h00001400;
  //! adp transmit ring words
  localparam int unsigned MBX_CH_ADP_TX_WORDS_C = 32'd128;
  //! adp largest frame
  localparam int unsigned MBX_CH_ADP_MAX_FRAME_BYTES_C = 32'd128;
  //! adp EtherType
  localparam int unsigned MBX_CH_ADP_ETHERTYPE0_C = 32'h000022F0;
  //! adp second EtherType
  localparam int unsigned MBX_CH_ADP_ETHERTYPE1_C = 32'h000022F0;
  //! adp matches a subtype
  localparam int unsigned MBX_CH_ADP_HAS_SUBTYPE_C = 32'd1;
  //! adp AVTP subtype
  localparam int unsigned MBX_CH_ADP_SUBTYPE_C = 32'h000000FA;
  //! adp token bucket depth
  localparam int unsigned MBX_CH_ADP_RATE_BURST_C = 32'd8;
  //! adp ms per refilled token
  localparam int unsigned MBX_CH_ADP_RATE_REFILL_MS_C = 32'd10;
  //! adp term 0: ENTITY_DISCOVER for every entity (Milan v1.2 5.6.3.1 step 2)
  localparam int unsigned MBX_CH_ADP_T0_TEST_C = 32'd3;
  //! adp term 0 field byte
  localparam int unsigned MBX_CH_ADP_T0_OFFSET_C = 32'd18;
  //! adp term 0 message types
  localparam int unsigned MBX_CH_ADP_T0_MSG_MASK_C = 32'h00000004;
  //! adp term 1: ENTITY_DISCOVER for this entity (Milan v1.2 5.6.3.1 step 2)
  localparam int unsigned MBX_CH_ADP_T1_TEST_C = 32'd2;
  //! adp term 1 field byte
  localparam int unsigned MBX_CH_ADP_T1_OFFSET_C = 32'd18;
  //! adp term 1 message types
  localparam int unsigned MBX_CH_ADP_T1_MSG_MASK_C = 32'h00000004;
  //! channel acmp
  localparam int unsigned MBX_CH_ACMP_C = 32'd1;
  //! acmp receive ring byte offset
  localparam int unsigned MBX_CH_ACMP_RX_BASE_C = 32'h00001800;
  //! acmp receive ring words
  localparam int unsigned MBX_CH_ACMP_RX_WORDS_C = 32'd256;
  //! acmp transmit ring byte offset
  localparam int unsigned MBX_CH_ACMP_TX_BASE_C = 32'h00001C00;
  //! acmp transmit ring words
  localparam int unsigned MBX_CH_ACMP_TX_WORDS_C = 32'd256;
  //! acmp largest frame
  localparam int unsigned MBX_CH_ACMP_MAX_FRAME_BYTES_C = 32'd128;
  //! acmp EtherType
  localparam int unsigned MBX_CH_ACMP_ETHERTYPE0_C = 32'h000022F0;
  //! acmp second EtherType
  localparam int unsigned MBX_CH_ACMP_ETHERTYPE1_C = 32'h000022F0;
  //! acmp matches a subtype
  localparam int unsigned MBX_CH_ACMP_HAS_SUBTYPE_C = 32'd1;
  //! acmp AVTP subtype
  localparam int unsigned MBX_CH_ACMP_SUBTYPE_C = 32'h000000FC;
  //! acmp token bucket depth
  localparam int unsigned MBX_CH_ACMP_RATE_BURST_C = 32'd16;
  //! acmp ms per refilled token
  localparam int unsigned MBX_CH_ACMP_RATE_REFILL_MS_C = 32'd5;
  //! acmp term 0: a command or response addressed to this entity's talker
  localparam int unsigned MBX_CH_ACMP_T0_TEST_C = 32'd2;
  //! acmp term 0 field byte
  localparam int unsigned MBX_CH_ACMP_T0_OFFSET_C = 32'd34;
  //! acmp term 0 message types
  localparam int unsigned MBX_CH_ACMP_T0_MSG_MASK_C = 32'h0000FFFF;
  //! acmp term 1: a command or response addressed to this entity's listener
  localparam int unsigned MBX_CH_ACMP_T1_TEST_C = 32'd2;
  //! acmp term 1 field byte
  localparam int unsigned MBX_CH_ACMP_T1_OFFSET_C = 32'd42;
  //! acmp term 1 message types
  localparam int unsigned MBX_CH_ACMP_T1_MSG_MASK_C = 32'h0000FFFF;
  //! channel aecp
  localparam int unsigned MBX_CH_AECP_C = 32'd2;
  //! aecp receive ring byte offset
  localparam int unsigned MBX_CH_AECP_RX_BASE_C = 32'h00002000;
  //! aecp receive ring words
  localparam int unsigned MBX_CH_AECP_RX_WORDS_C = 32'd512;
  //! aecp transmit ring byte offset
  localparam int unsigned MBX_CH_AECP_TX_BASE_C = 32'h00002800;
  //! aecp transmit ring words
  localparam int unsigned MBX_CH_AECP_TX_WORDS_C = 32'd512;
  //! aecp largest frame
  localparam int unsigned MBX_CH_AECP_MAX_FRAME_BYTES_C = 32'd1514;
  //! aecp EtherType
  localparam int unsigned MBX_CH_AECP_ETHERTYPE0_C = 32'h000022F0;
  //! aecp second EtherType
  localparam int unsigned MBX_CH_AECP_ETHERTYPE1_C = 32'h000022F0;
  //! aecp matches a subtype
  localparam int unsigned MBX_CH_AECP_HAS_SUBTYPE_C = 32'd1;
  //! aecp AVTP subtype
  localparam int unsigned MBX_CH_AECP_SUBTYPE_C = 32'h000000FB;
  //! aecp token bucket depth
  localparam int unsigned MBX_CH_AECP_RATE_BURST_C = 32'd16;
  //! aecp ms per refilled token
  localparam int unsigned MBX_CH_AECP_RATE_REFILL_MS_C = 32'd5;
  //! aecp term 0: a command addressed to this entity
  localparam int unsigned MBX_CH_AECP_T0_TEST_C = 32'd2;
  //! aecp term 0 field byte
  localparam int unsigned MBX_CH_AECP_T0_OFFSET_C = 32'd18;
  //! aecp term 0 message types
  localparam int unsigned MBX_CH_AECP_T0_MSG_MASK_C = 32'h0000FFFF;
  //! aecp term 1: unused
  localparam int unsigned MBX_CH_AECP_T1_TEST_C = 32'd0;
  //! aecp term 1 field byte
  localparam int unsigned MBX_CH_AECP_T1_OFFSET_C = 32'd0;
  //! aecp term 1 message types
  localparam int unsigned MBX_CH_AECP_T1_MSG_MASK_C = 32'h00000000;
  //! channel maap
  localparam int unsigned MBX_CH_MAAP_C = 32'd3;
  //! maap receive ring byte offset
  localparam int unsigned MBX_CH_MAAP_RX_BASE_C = 32'h00003000;
  //! maap receive ring words
  localparam int unsigned MBX_CH_MAAP_RX_WORDS_C = 32'd128;
  //! maap transmit ring byte offset
  localparam int unsigned MBX_CH_MAAP_TX_BASE_C = 32'h00003200;
  //! maap transmit ring words
  localparam int unsigned MBX_CH_MAAP_TX_WORDS_C = 32'd128;
  //! maap largest frame
  localparam int unsigned MBX_CH_MAAP_MAX_FRAME_BYTES_C = 32'd64;
  //! maap EtherType
  localparam int unsigned MBX_CH_MAAP_ETHERTYPE0_C = 32'h000022F0;
  //! maap second EtherType
  localparam int unsigned MBX_CH_MAAP_ETHERTYPE1_C = 32'h000022F0;
  //! maap matches a subtype
  localparam int unsigned MBX_CH_MAAP_HAS_SUBTYPE_C = 32'd1;
  //! maap AVTP subtype
  localparam int unsigned MBX_CH_MAAP_SUBTYPE_C = 32'h000000FE;
  //! maap token bucket depth
  localparam int unsigned MBX_CH_MAAP_RATE_BURST_C = 32'd8;
  //! maap ms per refilled token
  localparam int unsigned MBX_CH_MAAP_RATE_REFILL_MS_C = 32'd20;
  //! maap term 0: a PROBE, DEFEND or ANNOUNCE whose requested range conflicts with this entity's range
  localparam int unsigned MBX_CH_MAAP_T0_TEST_C = 32'd4;
  //! maap term 0 field byte
  localparam int unsigned MBX_CH_MAAP_T0_OFFSET_C = 32'd26;
  //! maap term 0 message types
  localparam int unsigned MBX_CH_MAAP_T0_MSG_MASK_C = 32'h0000000E;
  //! maap term 1: unused
  localparam int unsigned MBX_CH_MAAP_T1_TEST_C = 32'd0;
  //! maap term 1 field byte
  localparam int unsigned MBX_CH_MAAP_T1_OFFSET_C = 32'd0;
  //! maap term 1 message types
  localparam int unsigned MBX_CH_MAAP_T1_MSG_MASK_C = 32'h00000000;
  //! channel srp
  localparam int unsigned MBX_CH_SRP_C = 32'd4;
  //! srp receive ring byte offset
  localparam int unsigned MBX_CH_SRP_RX_BASE_C = 32'h00004000;
  //! srp receive ring words
  localparam int unsigned MBX_CH_SRP_RX_WORDS_C = 32'd1024;
  //! srp transmit ring byte offset
  localparam int unsigned MBX_CH_SRP_TX_BASE_C = 32'h00005000;
  //! srp transmit ring words
  localparam int unsigned MBX_CH_SRP_TX_WORDS_C = 32'd512;
  //! srp largest frame
  localparam int unsigned MBX_CH_SRP_MAX_FRAME_BYTES_C = 32'd1514;
  //! srp EtherType
  localparam int unsigned MBX_CH_SRP_ETHERTYPE0_C = 32'h000022EA;
  //! srp second EtherType
  localparam int unsigned MBX_CH_SRP_ETHERTYPE1_C = 32'h000088F5;
  //! srp matches a subtype
  localparam int unsigned MBX_CH_SRP_HAS_SUBTYPE_C = 32'd0;
  //! srp AVTP subtype
  localparam int unsigned MBX_CH_SRP_SUBTYPE_C = 32'h00000000;
  //! srp token bucket depth
  localparam int unsigned MBX_CH_SRP_RATE_BURST_C = 32'd32;
  //! srp ms per refilled token
  localparam int unsigned MBX_CH_SRP_RATE_REFILL_MS_C = 32'd2;
  //! srp term 0: every MSRP and MVRP PDU; both are link-local to this port
  localparam int unsigned MBX_CH_SRP_T0_TEST_C = 32'd1;
  //! srp term 0 field byte
  localparam int unsigned MBX_CH_SRP_T0_OFFSET_C = 32'd0;
  //! srp term 0 message types
  localparam int unsigned MBX_CH_SRP_T0_MSG_MASK_C = 32'h0000FFFF;
  //! srp term 1: unused
  localparam int unsigned MBX_CH_SRP_T1_TEST_C = 32'd0;
  //! srp term 1 field byte
  localparam int unsigned MBX_CH_SRP_T1_OFFSET_C = 32'd0;
  //! srp term 1 message types
  localparam int unsigned MBX_CH_SRP_T1_MSG_MASK_C = 32'h00000000;
  //! interface index bits
  localparam int unsigned MBX_IF_W_C = 32'd1;
  //! channel index bits
  localparam int unsigned MBX_CH_W_C = 32'd3;
  //! widest ring word index
  localparam int unsigned MBX_RING_AW_C = 32'd10;
  //! window word address bits
  localparam int unsigned MBX_ADDR_W_C = 32'd13;
  //! the largest max_frame_bytes of any channel
  localparam int unsigned MBX_FRAME_BYTES_MAX_C = 32'd1514;

  //! by channel id
  localparam int unsigned MBX_CH_RX_BASE_TBL_C [MBX_N_CH_C] = '{MBX_CH_ADP_RX_BASE_C, MBX_CH_ACMP_RX_BASE_C, MBX_CH_AECP_RX_BASE_C, MBX_CH_MAAP_RX_BASE_C, MBX_CH_SRP_RX_BASE_C};
  //! by channel id
  localparam int unsigned MBX_CH_RX_WORDS_TBL_C [MBX_N_CH_C] = '{MBX_CH_ADP_RX_WORDS_C, MBX_CH_ACMP_RX_WORDS_C, MBX_CH_AECP_RX_WORDS_C, MBX_CH_MAAP_RX_WORDS_C, MBX_CH_SRP_RX_WORDS_C};
  //! by channel id
  localparam int unsigned MBX_CH_TX_BASE_TBL_C [MBX_N_CH_C] = '{MBX_CH_ADP_TX_BASE_C, MBX_CH_ACMP_TX_BASE_C, MBX_CH_AECP_TX_BASE_C, MBX_CH_MAAP_TX_BASE_C, MBX_CH_SRP_TX_BASE_C};
  //! by channel id
  localparam int unsigned MBX_CH_TX_WORDS_TBL_C [MBX_N_CH_C] = '{MBX_CH_ADP_TX_WORDS_C, MBX_CH_ACMP_TX_WORDS_C, MBX_CH_AECP_TX_WORDS_C, MBX_CH_MAAP_TX_WORDS_C, MBX_CH_SRP_TX_WORDS_C};
  //! by channel id
  localparam int unsigned MBX_CH_MAX_FRAME_BYTES_TBL_C [MBX_N_CH_C] = '{MBX_CH_ADP_MAX_FRAME_BYTES_C, MBX_CH_ACMP_MAX_FRAME_BYTES_C, MBX_CH_AECP_MAX_FRAME_BYTES_C, MBX_CH_MAAP_MAX_FRAME_BYTES_C, MBX_CH_SRP_MAX_FRAME_BYTES_C};
  //! by channel id
  localparam int unsigned MBX_CH_ETHERTYPE0_TBL_C [MBX_N_CH_C] = '{MBX_CH_ADP_ETHERTYPE0_C, MBX_CH_ACMP_ETHERTYPE0_C, MBX_CH_AECP_ETHERTYPE0_C, MBX_CH_MAAP_ETHERTYPE0_C, MBX_CH_SRP_ETHERTYPE0_C};
  //! by channel id
  localparam int unsigned MBX_CH_ETHERTYPE1_TBL_C [MBX_N_CH_C] = '{MBX_CH_ADP_ETHERTYPE1_C, MBX_CH_ACMP_ETHERTYPE1_C, MBX_CH_AECP_ETHERTYPE1_C, MBX_CH_MAAP_ETHERTYPE1_C, MBX_CH_SRP_ETHERTYPE1_C};
  //! by channel id
  localparam int unsigned MBX_CH_HAS_SUBTYPE_TBL_C [MBX_N_CH_C] = '{MBX_CH_ADP_HAS_SUBTYPE_C, MBX_CH_ACMP_HAS_SUBTYPE_C, MBX_CH_AECP_HAS_SUBTYPE_C, MBX_CH_MAAP_HAS_SUBTYPE_C, MBX_CH_SRP_HAS_SUBTYPE_C};
  //! by channel id
  localparam int unsigned MBX_CH_SUBTYPE_TBL_C [MBX_N_CH_C] = '{MBX_CH_ADP_SUBTYPE_C, MBX_CH_ACMP_SUBTYPE_C, MBX_CH_AECP_SUBTYPE_C, MBX_CH_MAAP_SUBTYPE_C, MBX_CH_SRP_SUBTYPE_C};
  //! by channel id
  localparam int unsigned MBX_CH_RATE_BURST_TBL_C [MBX_N_CH_C] = '{MBX_CH_ADP_RATE_BURST_C, MBX_CH_ACMP_RATE_BURST_C, MBX_CH_AECP_RATE_BURST_C, MBX_CH_MAAP_RATE_BURST_C, MBX_CH_SRP_RATE_BURST_C};
  //! by channel id
  localparam int unsigned MBX_CH_RATE_REFILL_MS_TBL_C [MBX_N_CH_C] = '{MBX_CH_ADP_RATE_REFILL_MS_C, MBX_CH_ACMP_RATE_REFILL_MS_C, MBX_CH_AECP_RATE_REFILL_MS_C, MBX_CH_MAAP_RATE_REFILL_MS_C, MBX_CH_SRP_RATE_REFILL_MS_C};
  //! by channel id * MAX_TERMS + term
  localparam int unsigned MBX_TERM_TEST_TBL_C [MBX_N_CH_C * MBX_MAX_TERMS_C] = '{MBX_CH_ADP_T0_TEST_C, MBX_CH_ADP_T1_TEST_C, MBX_CH_ACMP_T0_TEST_C, MBX_CH_ACMP_T1_TEST_C, MBX_CH_AECP_T0_TEST_C, MBX_CH_AECP_T1_TEST_C, MBX_CH_MAAP_T0_TEST_C, MBX_CH_MAAP_T1_TEST_C, MBX_CH_SRP_T0_TEST_C, MBX_CH_SRP_T1_TEST_C};
  //! by channel id * MAX_TERMS + term
  localparam int unsigned MBX_TERM_OFFSET_TBL_C [MBX_N_CH_C * MBX_MAX_TERMS_C] = '{MBX_CH_ADP_T0_OFFSET_C, MBX_CH_ADP_T1_OFFSET_C, MBX_CH_ACMP_T0_OFFSET_C, MBX_CH_ACMP_T1_OFFSET_C, MBX_CH_AECP_T0_OFFSET_C, MBX_CH_AECP_T1_OFFSET_C, MBX_CH_MAAP_T0_OFFSET_C, MBX_CH_MAAP_T1_OFFSET_C, MBX_CH_SRP_T0_OFFSET_C, MBX_CH_SRP_T1_OFFSET_C};
  //! by channel id * MAX_TERMS + term
  localparam int unsigned MBX_TERM_MASK_TBL_C [MBX_N_CH_C * MBX_MAX_TERMS_C] = '{MBX_CH_ADP_T0_MSG_MASK_C, MBX_CH_ADP_T1_MSG_MASK_C, MBX_CH_ACMP_T0_MSG_MASK_C, MBX_CH_ACMP_T1_MSG_MASK_C, MBX_CH_AECP_T0_MSG_MASK_C, MBX_CH_AECP_T1_MSG_MASK_C, MBX_CH_MAAP_T0_MSG_MASK_C, MBX_CH_MAAP_T1_MSG_MASK_C, MBX_CH_SRP_T0_MSG_MASK_C, MBX_CH_SRP_T1_MSG_MASK_C};

  //! `value` placed into the field [lsb +: width] of a 32-bit word
  function automatic logic [31:0] mbx_place_f(input logic [31:0] value, input int unsigned lsb,
                                              input int unsigned width);
    logic [31:0] mask;
    mask = (width >= 32) ? 32'hFFFF_FFFF : ((32'd1 << width) - 32'd1);
    return (value & mask) << lsb;
  endfunction : mbx_place_f

  //! the field [lsb +: width] of a 32-bit word
  function automatic logic [31:0] mbx_field_f(input logic [31:0] word, input int unsigned lsb,
                                              input int unsigned width);
    logic [31:0] mask;
    mask = (width >= 32) ? 32'hFFFF_FFFF : ((32'd1 << width) - 32'd1);
    return (word >> lsb) & mask;
  endfunction : mbx_field_f

endpackage : KL_mbx_pkg

`default_nettype wire
