# SPDX-FileCopyrightText: 2026 Kebag Logic
# SPDX-License-Identifier: CERN-OHL-W-2.0
"""acmp_mutants.py - lane F3's planted defects (#665): the ACMP module's.

One or more for every test of the acmp, acmpwalk, acmpnvm and acmpif2 arms,
which ctrl_mutants.unnamed_tests proves before any is planted. ctrl_mutants.py
appends this table to its own and plants it the same way. Round 2's defects
(the reviews' findings and the adp channel's bound-talker term) are
acmp_review_mutants.py's, appended here.
"""

from __future__ import annotations

import acmp_review_mutants
from ctrl_mutant import Mutant

MUTANTS = (
    # the configuration (A0)
    Mutant("acmp-init-no-interface", "acmp/acmp.c",
           "if (cfg->n_interfaces == 0u || cfg->n_interfaces > ACMP_MAX_INTERFACES ||",
           "if (cfg->n_interfaces > ACMP_MAX_INTERFACES ||",
           "acmp", "AcmpCore.A0InitRefusesWhatTheStaticSizesCannotHold", "A0 no interface is refused"),
    Mutant("acmp-init-too-many-sinks", "acmp/acmp.c", "cfg->n_sinks > ACMP_MAX_SINKS ||",
           "cfg->n_sinks > ACMP_MAX_SINKS + 1u ||",
           "acmp", "AcmpCore.A0InitRefusesWhatTheStaticSizesCannotHold", "A0 more sinks than ACMP_MAX_SINKS"),
    Mutant("acmp-init-too-many-sources", "acmp/acmp.c", "cfg->n_sources > ACMP_MAX_SOURCES) {",
           "cfg->n_sources > ACMP_MAX_SOURCES + 1u) {",
           "acmp", "AcmpCore.A0InitRefusesWhatTheStaticSizesCannotHold", "A0 more sources than ACMP_MAX_SOURCES"),
    Mutant("acmp-init-sink-interface", "acmp/acmp.c", "\t\tif (cfg->sink_interface[k] >= cfg->n_interfaces) {",
           "\t\tif (cfg->sink_interface[k] > cfg->n_interfaces) {",
           "acmp", "AcmpCore.A0InitRefusesWhatTheStaticSizesCannotHold",
           "A0 a sink on an interface the entity lacks is refused"),
    Mutant("acmp-init-source-interface", "acmp/acmp.c", "\t\tif (cfg->source_interface[k] >= cfg->n_interfaces) {",
           "\t\tif (cfg->source_interface[k] > cfg->n_interfaces) {",
           "acmp", "AcmpCore.A0InitRefusesWhatTheStaticSizesCannotHold",
           "A0 a source on an interface the entity lacks is refused"),
    Mutant("acmp-init-reads-the-seed", "acmp/acmp.c",
           "\ta->rng = (uint32_t)cfg->entity_id ^ (uint32_t)(cfg->entity_id >> 32) ^ 0x7F4A7C15u;",
           "\ta->rng = (uint32_t)cfg->entity_id ^ (uint32_t)(cfg->entity_id >> 32) ^ 0x7F4A7C15u ^ p_seed(a);",
           "acmp", "AcmpCore.A0EverySinkStartsUnboundAndNothingIsCalled", "A0 init calls no port",
           (("acmp", "AcmpMailbox.U5AcmpComesAfterAdpAndReadsNothingBeforeTheContract",
             "U5 composing touches no mailbox register"),)),
    # a wrong number in acmp.h: the tests spell the standards' own (acmp_fake.hpp spec)
    Mutant("acmp-header-no-resp-2s", "acmp/acmp.h", "#define ACMP_TMR_NO_RESP_MS 200u",
           "#define ACMP_TMR_NO_RESP_MS 2000u",
           "acmp", "AcmpCore.A1BindFromUnboundRespondsThenProbes", "A1 and TMR_NO_RESP armed 200 ms",
           (("acmpwalk", "Table530/ListenerWalk.Graded/BIND_NEW_UNB", "the timer's deadline"),)),
    Mutant("acmp-header-retry-2s", "acmp/acmp.h", "#define ACMP_TMR_RETRY_MS 4000u", "#define ACMP_TMR_RETRY_MS 2000u",
           "acmp", "AcmpCore.A9FailureWaitsForTheRetry", "A9 and TMR_RETRY 4 s",
           (("acmpwalk", "Table530/ListenerWalk.Graded/PROBE_FAIL_PWR", "the timer's deadline"),)),
    Mutant("acmp-header-no-tk-5s", "acmp/acmp.h", "#define ACMP_TMR_NO_TK_MS 10000u", "#define ACMP_TMR_NO_TK_MS 5000u",
           "acmp", "AcmpCore.A8SuccessSettles", "A8 TMR_NO_RESP stopped and TMR_NO_TK 10 s started"),
    Mutant("acmp-header-valid-time-in-seconds", "acmp/acmp.h", "#define ACMP_VALID_TIME_UNIT_MS 2000u",
           "#define ACMP_VALID_TIME_UNIT_MS 1000u",
           "acmp", "AcmpCore.A22AvailableDiscoversWhenTheGrandmasterMatches",
           "A22 TMR_NO_ADP is the received valid_time in two-second units"),
    Mutant("acmp-header-listener-unknown-is-2", "acmp/acmp.h", "#define ACMP_STATUS_LISTENER_UNKNOWN_ID 1u",
           "#define ACMP_STATUS_LISTENER_UNKNOWN_ID 2u",
           "acmp", "AcmpCore.A2UnknownSinkIsAnsweredListenerUnknownId",
           "A2 LISTENER_UNKNOWN_ID, the command's fields echoed"),
    Mutant("acmp-header-registering-failed-bit", "acmp/acmp.h", "#define ACMP_FLAG_REGISTERING_FAILED 0x0040u",
           "#define ACMP_FLAG_REGISTERING_FAILED 0x0200u",
           "acmp", "AcmpCore.A2GetRxStateReportsStreamingWaitAndRegisteringFailed",
           "REGISTERING_FAILED 1 (Table 5.39)"),
    Mutant("acmp-header-cdl-84", "acmp/acmp.h", "#define ACMP_CONTROL_DATA_LENGTH 44u",
           "#define ACMP_CONTROL_DATA_LENGTH 84u",
           "acmp", "AcmpCore.A1BindFromUnboundRespondsThenProbes", "A1 every frame goes to the ACMP multicast address"),
    # BIND_RX from UNBOUND (A1, 5.5.3.5.3)
    Mutant("acmp-bind-count-0", "acmp/acmp.c", "\tr.count = 1u;\n\tr.flags = cmd->flags & ACMP_FLAG_STREAMING_WAIT;",
           "\tr.count = 0u;\n\tr.flags = cmd->flags & ACMP_FLAG_STREAMING_WAIT;",
           "acmp", "AcmpCore.A1BindFromUnboundRespondsThenProbes", "A1 BIND_RX_RESPONSE is Table 5.32",
           (("acmpwalk", "Table530/ListenerWalk.Graded/BIND_NEW_UNB", "frame 0 byte for byte"),)),
    Mutant("acmp-probe-without-fast-connect", "acmp/acmp.c",
           "\tp.flags = ACMP_FLAG_FAST_CONNECT;\n\tuint8_t frame[ACMP_FRAME_BYTES];",
           "\tp.flags = 0u;\n\tuint8_t frame[ACMP_FRAME_BYTES];",
           "acmp", "AcmpCore.A1BindFromUnboundRespondsThenProbes", "A1 PROBE_TX_COMMAND is Table 5.33",
           (("acmpwalk", "Table530/ListenerWalk.Graded/BIND_NEW_UNB", "frame 1 byte for byte"),)),
    Mutant("acmp-probe-before-response", "acmp/acmp.c",
           "\ts->started = !sw;\n\tbind_response(a, interface, k, cmd);\n\tdisc_start(s);\n\tprobe(a, k);",
           "\ts->started = !sw;\n\tdisc_start(s);\n\tprobe(a, k);\n\tbind_response(a, interface, k, cmd);",
           "acmp", "AcmpCore.A1BindFromUnboundRespondsThenProbes", "A1 BIND_RX_RESPONSE is Table 5.32"),
    Mutant("acmp-no-resp-2s", "acmp/acmp.c",
           "\ta->now_read = false;\n\tsm_timer(a, s, ACMP_TIMER_NO_RESP, ACMP_TMR_NO_RESP_MS);",
           "\ta->now_read = false;\n\tsm_timer(a, s, ACMP_TIMER_NO_RESP, ACMP_TMR_NO_RESP_MS * 10u);",
           "acmp", "AcmpCore.A1BindFromUnboundRespondsThenProbes", "A1 and TMR_NO_RESP armed 200 ms",
           (("acmp", "AcmpMailbox.B3TheTimersRunOnTheInterfaceSlot", "B3 TMR_NO_RESP is armed"),)),
    Mutant("acmp-bind-starts-no-discovery", "acmp/acmp.c",
           "\tbind_response(a, interface, k, cmd);\n\tdisc_start(s);\n", "\tbind_response(a, interface, k, cmd);\n",
           "acmp", "AcmpCore.A1BindFromUnboundRespondsThenProbes", "A1 the discovery machine starts",
           (("acmpwalk", "Table530/ListenerWalk.Graded/BIND_NEW_UNB", "discovery runs exactly while"),)),
    Mutant("acmp-bind-change-before-response", "acmp/acmp.c",
           "\tbind_response(a, interface, k, cmd);\n\tdisc_start(s);\n",
           "\tp_changed(a, k);\n\tbind_response(a, interface, k, cmd);\n\tdisc_start(s);\n",
           "acmp", "AcmpCore.A1BindFromUnboundRespondsThenProbes", "A1 the change is reported after the response"),
    Mutant("acmp-nothing-persisted", "acmp/acmp.c",
           "\t\t\tmemcpy(s->saved, record, ACMP_BINDING_BYTES);\n\t\t\tp_persist(a, k);",
           "\t\t\tmemcpy(s->saved, record, ACMP_BINDING_BYTES);\n\t\t\t(void)p_persist;",
           "acmp", "AcmpCore.A1BindFromUnboundRespondsThenProbes", "A1 the binding is saved",
           (("acmpnvm", "AcmpStore.N1ABindSurvivesAPowerCycleAndFastConnects", "N1 the bind marks its record"),)),
    Mutant("acmp-unbind-not-persisted", "acmp/acmp.c", "\t\tif (!same_record(record, s->saved)) {",
           "\t\tif (!same_record(record, s->saved) && s->bound) {",
           "acmpnvm", "AcmpStore.N2AnUnbindIsSavedAsAnUnboundRecord", "N2 the unbind marks the record",
           (("acmpwalk", "Table530/ListenerWalk.Graded/UNBIND_PWR", "the store marked"),)),
    Mutant("acmp-rebind-not-persisted", "acmp/acmp.c", "\t\tif (!same_record(record, s->saved)) {",
           "\t\tif (!same_record(record, s->saved) && (s->saved[0] & 0x01u) == 0u) {",
           "acmpnvm", "AcmpStore.N4AnUnreadSlotRefusesPersistence",
           "N4 a new bind is answered and taken, and its record marked",
           (("acmp", "AcmpCore.A6BindAnotherSourceRestartsTheSink", "A6 the new binding is saved"),)),
    Mutant("acmp-streaming-wait-ignored", "acmp/acmp.c",
           "\t// START_STREAMING (Milan v1.2 5.3.8.7)\n\ts->started = !sw;",
           "\t// START_STREAMING (Milan v1.2 5.3.8.7)\n\ts->started = true;",
           "acmp", "AcmpCore.A1BindFromUnboundRespondsThenProbes", "STREAMING_WAIT binds it stopped"),
    Mutant("acmp-sw-read-from-fast-connect", "acmp/acmp.c",
           "\tbool sw = (cmd->flags & ACMP_FLAG_STREAMING_WAIT) != 0u;",
           "\tbool sw = (cmd->flags & ACMP_FLAG_FAST_CONNECT) != 0u;",
           "acmp", "AcmpCore.A2GetRxStateReportsStreamingWaitAndRegisteringFailed", "STREAMING_WAIT saved"),
    # GET_RX_STATE (A2)
    Mutant("acmp-getrx-count-unbound", "acmp/acmp.c", "\tif (s->bound) {\n\t\tr.count = 1u;",
           "\tr.count = 1u;\n\tif (s->bound) {", "acmp", "AcmpCore.A2GetRxStateInEveryState",
           "A2 GET_RX_STATE_RESPONSE is Table 5.34/5.37/5.38/5.39",
           (("acmpwalk", "Table530/ListenerWalk.Graded/GETRX_UNB", "frame 0 byte for byte"),)),
    Mutant("acmp-getrx-no-fast-connect", "acmp/acmp.c",
           "\t\tr.flags = (uint16_t)(ACMP_FLAG_FAST_CONNECT | (s->binding.streaming_wait ? ACMP_FLAG_STREAMING_WAIT : "
           "0u));",
           "\t\tr.flags = (uint16_t)(s->binding.streaming_wait ? ACMP_FLAG_STREAMING_WAIT : 0u);",
           "acmp", "AcmpCore.A2GetRxStateInEveryState", "A2 GET_RX_STATE_RESPONSE is Table 5.34/5.37/5.38/5.39",
           (("acmpwalk", "Table530/ListenerWalk.Graded/GETRX_PWR", "frame 0 byte for byte"),)),
    Mutant("acmp-getrx-no-registering-failed", "acmp/acmp.c", "\t\tr.flags |= ACMP_FLAG_REGISTERING_FAILED;",
           "\t\tr.flags |= 0u;", "acmp", "AcmpCore.A2GetRxStateReportsStreamingWaitAndRegisteringFailed",
           "REGISTERING_FAILED 1 (Table 5.39)"),
    Mutant("acmp-unknown-sink-silent", "acmp/acmp.c",
           "\t\tstruct pdu r = echo(cmd, ACMP_STATUS_LISTENER_UNKNOWN_ID);         // Table 5.27\n"
           "\t\trespond(a, interface, &r, 0u);",
           "\t\tstruct pdu r = echo(cmd, ACMP_STATUS_LISTENER_UNKNOWN_ID);         // Table 5.27\n\t\t(void)r;",
           "acmp", "AcmpCore.A2UnknownSinkIsAnsweredListenerUnknownId", "A2 a command for a sink the entity lacks"),
    # UNBIND_RX (A3)
    Mutant("acmp-unbind-echoes-the-talker", "acmp/acmp.c",
           "\tr.talker = 0u;\n\tr.talker_uid = 0u;\n\trespond(a, interface, &r, 1u << k);",
           "\trespond(a, interface, &r, 1u << k);",
           "acmp", "AcmpCore.A3UnbindInEveryState", "A3 UNBIND_RX_RESPONSE is Table 5.36",
           (("acmpwalk", "Table530/ListenerWalk.Graded/UNBIND_PWR", "frame 0 byte for byte"),)),
    Mutant("acmp-unbind-keeps-srp", "acmp/acmp.c",
           "\tstruct acmp_sink *s = &a->sinks[k];\n"
           "\tif (s->state == ACMP_SETTLED_NO_RSV || s->state == ACMP_SETTLED_RSV_OK) {\n"
           "\t\tsrp_stop(a, k);\n\t}\n\tdisc_stop(s);\n\ts->bound = false;",
           "\tstruct acmp_sink *s = &a->sinks[k];\n\tdisc_stop(s);\n\ts->bound = false;",
           "acmp", "AcmpCore.A3UnbindInEveryState", "A3 a settled sink stops SRP before the response",
           (("acmpwalk", "Table530/ListenerWalk.Graded/UNBIND_SNR", "SRP stopped"),)),
    Mutant("acmp-unbind-srp-after-response", "acmp/acmp.c",
           "\tstruct acmp_sink *s = &a->sinks[k];\n"
           "\tif (s->state == ACMP_SETTLED_NO_RSV || s->state == ACMP_SETTLED_RSV_OK) {\n"
           "\t\tsrp_stop(a, k);\n\t}\n\tdisc_stop(s);\n\ts->bound = false;\n"
           "\tmemset(&s->binding, 0, sizeof s->binding);\n\ts->started = false;\n"
           "\ts->probing = ACMP_PROBING_DISABLED;\n\ts->acmp_status = ACMP_STATUS_SUCCESS;\n\tsm_stop(s);\n"
           "\tstruct pdu r = echo(cmd, ACMP_STATUS_SUCCESS);             // Table 5.36\n"
           "\tr.talker = 0u;\n\tr.talker_uid = 0u;\n\trespond(a, interface, &r, 1u << k);\n",
           "\tstruct acmp_sink *s = &a->sinks[k];\n"
           "\tbool settled = s->state == ACMP_SETTLED_NO_RSV || s->state == ACMP_SETTLED_RSV_OK;\n"
           "\tdisc_stop(s);\n\ts->bound = false;\n"
           "\tmemset(&s->binding, 0, sizeof s->binding);\n\ts->started = false;\n"
           "\ts->probing = ACMP_PROBING_DISABLED;\n\ts->acmp_status = ACMP_STATUS_SUCCESS;\n\tsm_stop(s);\n"
           "\tstruct pdu r = echo(cmd, ACMP_STATUS_SUCCESS);\n"
           "\tr.talker = 0u;\n\tr.talker_uid = 0u;\n\trespond(a, interface, &r, 1u << k);\n"
           "\tif (settled) {\n\t\tsrp_stop(a, k);\n\t}\n",
           "acmp", "AcmpCore.A3UnbindInEveryState", "A3 a settled sink stops SRP before the response"),
    Mutant("acmp-unbind-keeps-discovery", "acmp/acmp.c", "\tdisc_stop(s);\n\ts->bound = false;",
           "\ts->bound = false;", "acmp", "AcmpCore.A3UnbindInEveryState", "A3 then UNBOUND, binding cleared",
           (("acmpwalk", "Table530/ListenerWalk.Graded/UNBIND_PWR", "discovery runs exactly while"),)),
    Mutant("acmp-unbind-change-before-response", "acmp/acmp.c",
           "\tr.talker_uid = 0u;\n\trespond(a, interface, &r, 1u << k);",
           "\tr.talker_uid = 0u;\n\tp_changed(a, k);\n\trespond(a, interface, &r, 1u << k);",
           "acmp", "AcmpCore.A3UnbindInEveryState", "A3 the change is reported after the response (#653)"),
    # the lock (A4)
    Mutant("acmp-not-authorized-is-13", "acmp/acmp.h", "#define ACMP_STATUS_CONTROLLER_NOT_AUTHORIZED 16u",
           "#define ACMP_STATUS_CONTROLLER_NOT_AUTHORIZED 13u",
           "acmp", "AcmpCore.A4LockedByAnotherControllerRefusesBindAndUnbind", "A4 CONTROLLER_NOT_AUTHORIZED (16",
           (("acmpwalk", "ListenerScenario.LD3TheLockRefusalStatus", "LD3 the firmware sends 16"),)),
    Mutant("acmp-lock-ignored", "acmp/acmp.c", "\tif (p_locked(a, &holder) && holder != cmd->controller) {",
           "\tif (p_locked(a, &holder) && holder != cmd->controller && false) {",
           "acmp", "AcmpCore.A4LockedByAnotherControllerRefusesBindAndUnbind", "A4 one response"),
    Mutant("acmp-lock-refuses-the-holder", "acmp/acmp.c",
           "\tif (p_locked(a, &holder) && holder != cmd->controller) {",
           "\tif (p_locked(a, &holder)) {\n\t\t(void)cmd;",
           "acmp", "AcmpCore.A4TheLockingControllerPassesAndGetRxStateIsNotLocked", "A4 the locking controller binds"),
    Mutant("acmp-get-rx-state-locked", "acmp/acmp.c",
           "\tif (cmd->msg == ACMP_MSG_GET_RX_STATE_COMMAND) {\n\t\tget_rx_state(a, interface, k, cmd);\n"
           "\t} else if (lock_refuses(a, cmd)) {",
           "\tif (lock_refuses(a, cmd)) {\n\t\tstruct pdu r = echo(cmd, ACMP_STATUS_CONTROLLER_NOT_AUTHORIZED);\n"
           "\t\trespond(a, interface, &r, 0u);\n"
           "\t} else if (cmd->msg == ACMP_MSG_GET_RX_STATE_COMMAND) {\n\t\tget_rx_state(a, interface, k, cmd);\n"
           "\t} else if (lock_refuses(a, cmd)) {",
           "acmp", "AcmpCore.A4TheLockingControllerPassesAndGetRxStateIsNotLocked", "A4 GET_RX_STATE asks no lock"),
    # re-binds (A5, A6)
    Mutant("acmp-rebind-same-reprobes", "acmp/acmp.c",
           "\t\ts->started = !sw;\n\t\tbind_response(a, interface, k, cmd);\n\t\treturn;\n\t}",
           "\t\ts->started = !sw;\n\t\tbind_response(a, interface, k, cmd);\n\t}",
           "acmp", "AcmpCore.A5RebindTheSameSourceUpdatesAndExits",
           "A5 a re-bind of the same source sends the response alone",
           (("acmpwalk", "Table530/ListenerWalk.Graded/BIND_SAME_PWR", "frames"),)),
    Mutant("acmp-rebind-same-keeps-the-controller", "acmp/acmp.c",
           "\t\ts->binding.controller_entity_id = cmd->controller;\n\t\ts->binding.streaming_wait = sw;",
           "\t\ts->binding.streaming_wait = sw;",
           "acmp", "AcmpCore.A5RebindTheSameSourceUpdatesAndExits", "A5 the controller and STREAMING_WAIT are updated"),
    Mutant("acmp-bind-new-keeps-srp", "acmp/acmp.c",
           "\t\tsrp_stop(a, k);                                 // 5.5.3.5.37 and .43 step 3", "\t\t(void)k;",
           "acmp", "AcmpCore.A6BindAnotherSourceRestartsTheSink", "A6 SRP is stopped and its parameters cleared",
           (("acmpwalk", "Table530/ListenerWalk.Graded/BIND_NEW_SNR", "SRP stopped"),)),
    Mutant("acmp-bind-same-talker-is-the-same-source", "acmp/acmp.c",
           "if (s->bound && cmd->talker == s->binding.talker_entity_id && "
           "cmd->talker_uid == s->binding.talker_unique_id) {",
           "if (s->bound && cmd->talker == s->binding.talker_entity_id) {",
           "acmp", "AcmpCore.A6TheSameTalkerAnotherSourceIsANewBinding",
           "A6 the same talker with another talker_unique_id is a new source"),
    Mutant("acmp-sequence-id-never-advances", "acmp/acmp.c",
           "\ta->sequence_id = (uint16_t)(a->sequence_id + 1u);\n", "",
           "acmp", "AcmpCore.A12DelaySendsANewProbe", "A12 a new PROBE_TX_COMMAND with the next sequence_id",
           (("acmp", "AcmpCore.A16OneCounterForEveryNewProbe", "A16 each new PROBE_TX_COMMAND takes the next"),)),
    Mutant("acmp-sequence-id-per-sink", "acmp/acmp.c",
           "\ts->probe_seq = a->sequence_id;\n\ta->sequence_id = (uint16_t)(a->sequence_id + 1u);",
           "\ts->probe_seq = (uint16_t)(s->probe_seq + 1u);",
           "acmp", "AcmpCore.A16OneCounterForEveryNewProbe", "A16 each new PROBE_TX_COMMAND takes the next",
           (("acmpwalk", "Table530/ListenerWalk.Graded/BIND_NEW_UNB", "frame 1 byte for byte"),)),
    # probe responses (A7 to A9)
    Mutant("acmp-response-keyed-on-the-source", "acmp/acmp.c",
           "\tunsigned k = rsp->listener_uid;\n\tif (k >= a->cfg.n_sinks) {\n"
           "\t\ta->unknown_sink++;                              // 5.5.3.1: ignored",
           "\tunsigned k = 0;\n\twhile (k < a->cfg.n_sinks && (a->sinks[k].probe_talker != rsp->talker ||\n"
           "\t\t\t\t\t a->sinks[k].probe_talker_uid != rsp->talker_uid)) {\n\t\tk++;\n\t}\n"
           "\tif (k >= a->cfg.n_sinks) {\n\t\ta->unknown_sink++;",
           "acmp", "AcmpCore.A7ResponsesKeyOnTheListenerUniqueId", "A7 the response belongs to the sink"),
    Mutant("acmp-guard-controller-dropped", "acmp/acmp.c",
           "\tif (rsp->controller != s->probe_controller || rsp->talker != s->probe_talker ||",
           "\tif (rsp->talker != s->probe_talker ||",
           "acmp", "AcmpCore.A7EachGuardTermIsChecked", "A7 a response with another controller",
           (("acmpwalk", "ListenerScenario.LW2GuardsUnknownSinksAndForeignMessages",
             "LW2 a probe response wrong in guard term 0"),)),
    Mutant("acmp-guard-talker-dropped", "acmp/acmp.c",
           "\tif (rsp->controller != s->probe_controller || rsp->talker != s->probe_talker ||",
           "\tif (rsp->controller != s->probe_controller ||",
           "acmp", "AcmpCore.A7EachGuardTermIsChecked", "A7 a response with another controller",
           (("acmpwalk", "ListenerScenario.LW2GuardsUnknownSinksAndForeignMessages",
             "LW2 a probe response wrong in guard term 1"),)),
    Mutant("acmp-guard-unique-id-dropped", "acmp/acmp.c",
           "\t    rsp->talker_uid != s->probe_talker_uid || rsp->seq != s->probe_seq) {",
           "\t    rsp->seq != s->probe_seq) {",
           "acmp", "AcmpCore.A7EachGuardTermIsChecked", "A7 a response with another controller",
           (("acmpwalk", "ListenerScenario.LW2GuardsUnknownSinksAndForeignMessages",
             "LW2 a probe response wrong in guard term 2"),)),
    Mutant("acmp-guard-sequence-id-dropped", "acmp/acmp.c",
           "\t    rsp->talker_uid != s->probe_talker_uid || rsp->seq != s->probe_seq) {",
           "\t    rsp->talker_uid != s->probe_talker_uid) {",
           "acmp", "AcmpCore.A7EachGuardTermIsChecked", "A7 a response with another controller",
           (("acmpwalk", "ListenerScenario.LW2GuardsUnknownSinksAndForeignMessages",
             "LW2 a probe response wrong in guard term 3"),)),
    Mutant("acmp-guard-reads-the-binding", "acmp/acmp.c", "\tif (rsp->controller != s->probe_controller ||",
           "\tif (rsp->controller != s->binding.controller_entity_id ||",
           "acmp", "AcmpCore.A7TheGuardReadsTheSentProbeNotTheBinding",
           "A7 the answer to the probe sent before a re-bind still matches"),
    Mutant("acmp-responses-taken-outside-probing", "acmp/acmp.c",
           "\tif (s->state != ACMP_PRB_W_RESP && s->state != ACMP_PRB_W_RESP2) {\n\t\ta->rx_ignored++;",
           "\tif (false) {\n\t\ta->rx_ignored++;",
           "acmp", "AcmpCore.A7ResponsesOutsideProbingAreIgnored", "A7 RCV_PROBE_TX_RESP is ignored outside",
           (("acmpwalk", "Table530/ListenerWalk.Graded/PROBE_OK_SNR", "SRP started"),)),
    Mutant("acmp-vlan-masked", "acmp/acmp.c", "\ts->stream.vlan_id = rsp->vlan;",
           "\ts->stream.vlan_id = (uint16_t)(rsp->vlan & 0x0FFFu);",
           "acmp", "AcmpCore.A8SuccessSettles",
           "A8 with the response's stream_id, stream_dest_mac and stream_vlan_id exactly"),
    Mutant("acmp-no-tk-1s", "acmp/acmp.c", "\tsm_timer(a, s, ACMP_TIMER_NO_TK, ACMP_TMR_NO_TK_MS);",
           "\tsm_timer(a, s, ACMP_TIMER_NO_TK, ACMP_TMR_NO_TK_MS / 10u);",
           "acmp", "AcmpCore.A8SuccessSettles", "A8 TMR_NO_RESP stopped and TMR_NO_TK 10 s started",
           (("acmpwalk", "Table530/ListenerWalk.Graded/PROBE_OK_PWR", "the timer's deadline"),)),
    Mutant("acmp-settle-starts-no-srp", "acmp/acmp.c", "\ts->stream.vlan_id = rsp->vlan;\n\tp_srp(a, k, &s->stream);",
           "\ts->stream.vlan_id = rsp->vlan;", "acmp", "AcmpCore.A8SuccessSettles", "A8 SRP is started",
           (("acmpwalk", "Table530/ListenerWalk.Graded/PROBE_OK_PWR", "SRP started"),)),
    Mutant("acmp-settle-swaps-stream-fields", "acmp/acmp.c",
           "\ts->stream.stream_id = rsp->stream_id;                   // step 4, kept exactly (Milan v1.2 5.3.8.9)\n"
           "\ts->stream.dest_mac = rsp->dest_mac;",
           "\ts->stream.stream_id = rsp->dest_mac;\n\ts->stream.dest_mac = rsp->stream_id;",
           "acmp", "AcmpCore.A8SuccessSettles", "stream_vlan_id exactly",
           (("acmpwalk", "Table530/ListenerWalk.Graded/PROBE_OK_PWR", "the settled stream"),)),
    Mutant("acmp-failure-status-dropped", "acmp/acmp.c", "\t\ts->acmp_status = rsp->status;",
           "\t\ts->acmp_status = ACMP_STATUS_SUCCESS;",
           "acmp", "AcmpCore.A9FailureWaitsForTheRetry",
           "A9 a failed response: PRB_W_RETRY, the ACMP status is its status",
           (("acmpwalk", "Table530/ListenerWalk.Graded/PROBE_FAIL_PWR", "state, probing and ACMP status"),)),
    Mutant("acmp-failure-retries-at-200ms", "acmp/acmp.c",
           "\t\tsm_timer(a, s, ACMP_TIMER_RETRY, ACMP_TMR_RETRY_MS);\n\t\ts->acmp_status = rsp->status;",
           "\t\tsm_timer(a, s, ACMP_TIMER_RETRY, ACMP_TMR_NO_RESP_MS);\n\t\ts->acmp_status = rsp->status;",
           "acmp", "AcmpCore.A9FailureWaitsForTheRetry", "A9 and TMR_RETRY 4 s",
           (("acmpwalk", "Table530/ListenerWalk.Graded/PROBE_FAIL_PWR", "the timer's deadline"),)),
    # the timers (A10 to A13)
    Mutant("acmp-duplicate-takes-a-new-sequence-id", "acmp/acmp.c",
           "\t\ts->probe_retried = true;\n\t\tsend_probe(a, k);                               // the same sequence_id",
           "\t\tprobe(a, k);\n\t\ts->probe_retried = true;",
           "acmp", "AcmpCore.A10NoResponseSendsTheDuplicateThenGivesUp", "A10 an exact duplicate of the first probe",
           (("acmpwalk", "Table530/ListenerWalk.Graded/TMR_CMD_PWR", "frame 0 byte for byte"),)),
    Mutant("acmp-second-timeout-keeps-status-0", "acmp/acmp.c",
           "\t\ts->acmp_status = ACMP_STATUS_LISTENER_TALKER_TIMEOUT;", "\t\ts->acmp_status = ACMP_STATUS_SUCCESS;",
           "acmp", "AcmpCore.A10NoResponseSendsTheDuplicateThenGivesUp",
           "A10 the second: no frame, LISTENER_TALKER_TIMEOUT",
           (("acmp", "AcmpCore.A25OnlyTable522ItemsAreReported", "A25 the ACMP status LISTENER_TALKER_TIMEOUT does"),
            ("acmpwalk", "Table530/ListenerWalk.Graded/TMR_CMD_PW2", "state, probing and ACMP status"))),
    Mutant("acmp-no-duplicate", "acmp/acmp.c",
           "\t} else if (kind == ACMP_TIMER_NO_RESP && s->state == ACMP_PRB_W_RESP) {   // 5.5.3.5.16",
           "\t} else if (kind == ACMP_TIMER_NO_RESP && s->state == ACMP_PRB_W_RESP && false) {",
           "acmp", "AcmpCore.A10NoResponseSendsTheDuplicateThenGivesUp", "A10 the first TMR_NO_RESP sends one frame",
           (("acmpwalk", "Table530/ListenerWalk.Graded/TMR_CMD_PWR", "frames"),)),
    Mutant("acmp-retry-ignores-discovery", "acmp/acmp.c",
           "\t} else if (kind == ACMP_TIMER_RETRY && !s->discovered) {   // 5.5.3.5.30 step 1",
           "\t} else if (kind == ACMP_TIMER_RETRY) {",
           "acmp", "AcmpCore.A11RetryWaitsForTheTalkerOrDelays", "A11 TMR_RETRY, talker discovered: TMR_DELAY",
           (("acmpwalk", "Table530/ListenerWalk.Graded/TMR_RETRY_PWT_disc", "state, probing and ACMP status"),)),
    Mutant("acmp-retry-zeroes-the-status", "acmp/acmp.c",
           "\t\tdelay(a, s);\n\t} else {                                                // 5.5.3.5.36, TMR_NO_TK",
           "\t\ts->acmp_status = ACMP_STATUS_SUCCESS;\n\t\tdelay(a, s);\n\t} else {",
           "acmp", "AcmpCore.A11RetryWaitsForTheTalkerOrDelays", "A11 and the ACMP status stays",
           (("acmpwalk", "Table530/ListenerWalk.Graded/TMR_RETRY_PWT_disc", "state, probing and ACMP status"),)),
    Mutant("acmp-delay-resends-the-old-probe", "acmp/acmp.c",
           "\tif (kind == ACMP_TIMER_DELAY) {                         // 5.5.3.5.10\n\t\tprobe(a, k);",
           "\tif (kind == ACMP_TIMER_DELAY) {\n\t\tsend_probe(a, k);",
           "acmp", "AcmpCore.A12DelaySendsANewProbe", "A12 a new PROBE_TX_COMMAND with the next sequence_id",
           (("acmpwalk", "Table530/ListenerWalk.Graded/TMR_DELAY_PWD", "frame 0 byte for byte"),)),
    Mutant("acmp-no-tk-keeps-srp", "acmp/acmp.c",
           "\t} else {                                                // 5.5.3.5.36, TMR_NO_TK\n\t\tsrp_stop(a, k);",
           "\t} else {\n\t\t(void)k;",
           "acmp", "AcmpCore.A13NoTalkerAttributeReprobes", "A13 TMR_NO_TK clears the SRP parameters and stops SRP",
           (("acmpwalk", "Table530/ListenerWalk.Graded/TMR_NOTK_SNR", "SRP stopped"),)),
    Mutant("acmp-reprobe-ignores-discovery", "acmp/acmp.c",
           "\tif (!s->discovered) {\n\t\tpassive(s);\n\t\treturn;\n\t}\n\ts->probing = ACMP_PROBING_ACTIVE;",
           "\tif (true) {\n\t\tpassive(s);\n\t\treturn;\n\t}\n\ts->probing = ACMP_PROBING_ACTIVE;",
           "acmp", "AcmpCore.A13NoTalkerAttributeReprobes", "A13 talker discovered: TMR_DELAY, PRB_W_DELAY",
           (("acmp", "AcmpCore.A15UnregisteredReprobes", "A15 talker discovered: TMR_DELAY, PRB_W_DELAY"),
            ("acmpwalk", "Table530/ListenerWalk.Graded/TMR_NOTK_SNR_disc", "state, probing and ACMP status"))),
    # the SRP side (A14, A15)
    Mutant("acmp-registered-anywhere", "acmp/acmp.c",
           "\tif (sink >= a->cfg.n_sinks || a->sinks[sink].state != ACMP_SETTLED_NO_RSV) {",
           "\tif (sink >= a->cfg.n_sinks) {",
           "acmp", "AcmpCore.A14RegisteredSettlesTheReservation", "A14 EVT_TK_REGISTERED anywhere else",
           (("acmpwalk", "Table530/ListenerWalk.Graded/TK_REG_PWR", "state, probing and ACMP status"),)),
    Mutant("acmp-registered-keeps-no-tk", "acmp/acmp.c",
           "\tstruct acmp_sink *s = &a->sinks[sink];                  // 5.5.3.5.42\n\tsm_stop(s);",
           "\tstruct acmp_sink *s = &a->sinks[sink];",
           "acmp", "AcmpCore.A14RegisteredSettlesTheReservation", "A14 EVT_TK_REGISTERED: TMR_NO_TK cleared",
           (("acmpwalk", "Table530/ListenerWalk.Graded/TK_REG_SNR", "the sink's timer armed or not"),)),
    Mutant("acmp-registered-kind-dropped", "acmp/acmp.c", "\ts->tk_failed = failed;",
           "\ts->tk_failed = false;\n\t(void)failed;",
           "acmp", "AcmpCore.A2GetRxStateReportsStreamingWaitAndRegisteringFailed", "REGISTERING_FAILED 1 (Table 5.39)",
           (("acmpwalk", "Table530/ListenerWalk.Graded/TK_REG_SNR", "registered state"),)),
    Mutant("acmp-unregistered-anywhere", "acmp/acmp.c",
           "\tif (sink >= a->cfg.n_sinks || a->sinks[sink].state != ACMP_SETTLED_RSV_OK) {",
           "\tif (sink >= a->cfg.n_sinks) {",
           "acmp", "AcmpCore.A15UnregisteredReprobes", "A15 EVT_TK_UNREGISTERED anywhere else",
           (("acmpwalk", "Table530/ListenerWalk.Graded/TK_UNREG_SNR", "state, probing and ACMP status"),)),
    Mutant("acmp-unregistered-keeps-srp", "acmp/acmp.c",
           "\tsrp_stop(a, sink);                                      // 5.5.3.5.48",
           "\t(void)sink;", "acmp", "AcmpCore.A15UnregisteredReprobes",
           "A15 EVT_TK_UNREGISTERED, talker not discovered: SRP stopped",
           (("acmpwalk", "Table530/ListenerWalk.Graded/TK_UNREG_SOK", "SRP stopped"),)),
    # one timer per interface (A17, A18)
    Mutant("acmp-timer-at-the-latest-deadline", "acmp/acmp.c",
           "\tif (armed && (!*any || (int32_t)(deadline - *at) < 0)) {",
           "\tif (armed && (!*any || (int32_t)(deadline - *at) > 0)) {",
           "acmp", "AcmpCore.A17EachInterfaceTimerHoldsItsEarliestDeadline",
           "A17 each interface's timer is armed at the earliest"),
    Mutant("acmp-timer-port-called-every-time", "acmp/acmp.c",
           "\t\tif (any && (!a->timer_armed[i] || a->timer_at[i] != at)) {", "\t\tif (any) {",
           "acmp", "AcmpCore.A17EachInterfaceTimerHoldsItsEarliestDeadline",
           "A17 the port is called only when the earliest deadline moves"),
    Mutant("acmp-timer-never-stopped", "acmp/acmp.c", "\t\t} else if (!any && a->timer_armed[i]) {",
           "\t\t} else if (!any && a->timer_armed[i] && false) {",
           "acmp", "AcmpCore.A17EachInterfaceTimerHoldsItsEarliestDeadline",
           "A17 an interface whose sinks hold no deadline",
           (("acmp", "AcmpMailbox.C10C11DiscoveryPathsAreServedInThePassThatTakesTheRecord",
             "C11 ENTITY_DEPARTING: PRB_W_AVAIL, the slot stopped"),)),
    Mutant("acmp-expiry-takes-every-interface", "acmp/acmp.c",
           "\t\tstruct acmp_sink *s = &a->sinks[k];\n\t\tif (s->interface != interface) {\n\t\t\tcontinue;\n\t\t}\n"
           "\t\tif (s->adp_armed && due(s->adp_deadline, now(a))) {",
           "\t\tstruct acmp_sink *s = &a->sinks[k];\n\t\tif (s->adp_armed && due(s->adp_deadline, now(a))) {",
           "acmp", "AcmpCore.A17EachInterfaceTimerHoldsItsEarliestDeadline", "A17 an expiry takes the due timers only"),
    Mutant("acmp-expiry-not-consumed", "acmp/acmp.c",
           "\ta->timer_armed[interface] = false;                      // the port's timer has fired\n", "",
           "acmp", "AcmpCore.A17EachInterfaceTimerHoldsItsEarliestDeadline",
           "A17 an expiry with nothing due changes nothing and re-arms the timer it consumed"),
    Mutant("acmp-zero-delay-waits", "acmp/acmp.c",
           "\t\twhile (sm_running(s) && due(s->timer_deadline, now(a))) {",
           "\t\tif (sm_running(s) && due(s->timer_deadline, now(a))) {",
           "acmp", "AcmpCore.A18AZeroDelayProbesInTheSameExpiry",
           "A18 TMR_RETRY drawing 0 ms sends its probe in the same expiry"),
    Mutant("acmp-delay-up-to-4s", "acmp/acmp.h", "#define ACMP_TMR_DELAY_MAX_MS 1000u",
           "#define ACMP_TMR_DELAY_MAX_MS 4000u",
           "acmp", "AcmpCore.A18AZeroDelayProbesInTheSameExpiry", "A18 the longest draw is 1000 ms"),
    Mutant("acmp-seed-at-every-draw", "acmp/acmp.c", "\t\ta->rng ^= p_seed(a);\n\t\ta->seeded = true;",
           "\t\ta->rng ^= p_seed(a);", "acmp", "AcmpCore.A18TheSeedIsTakenAtTheFirstDraw", "A18 and never again"),
    Mutant("acmp-rng-left-at-0", "acmp/acmp.c",
           "\t\tif (a->rng == 0u) {\n\t\t\ta->rng = 1u;                            // xorshift never leaves 0\n\t\t}\n",
           "",
           "acmp", "AcmpCore.A18TheSeedIsTakenAtTheFirstDraw", "A18 a seed that cancels the state to 0 leaves it 1"),
    # owed frames and #653 (A19, E1, E2)
    Mutant("acmp-response-passes-an-owed-frame", "acmp/acmp.c",
           "\tif (a->owed_count == 0u && p_send(a, interface, frame)) {", "\tif (p_send(a, interface, frame)) {",
           "acmp", "AcmpCore.A19NothingPassesAnOwedFrame", "A19 a response does not pass one already owed"),
    Mutant("acmp-poll-drains-everything", "acmp/acmp.c",
           "\tif (a->owed_count != 0u) {\n\t\tconst struct acmp_owed *o = &a->owed[a->owed_head];\n"
           "\t\tif (p_send(a, o->interface, o->frame)) {",
           "\twhile (a->owed_count != 0u &&\n"
           "\t       p_send(a, a->owed[a->owed_head].interface, a->owed[a->owed_head].frame)) {\n"
           "\t\tconst struct acmp_owed *o = &a->owed[a->owed_head];\n\t\t{",
           "acmp", "AcmpCore.A19AResponseWithoutRoomIsOwedAndItsChangeWaits", "A19 one frame per poll",
           (("acmp", "AcmpMailbox.E2AnOwedResponseIsCommittedInPassKPlus1", "E2 3 frames owed ahead"),)),
    Mutant("acmp-change-not-held-for-its-response", "acmp/acmp.c",
           "\t\ta->sinks[k].change_owed = (uint8_t)(a->sinks[k].change_owed + ((release >> k) & 1u));",
           "\t\t(void)release;",
           "acmp", "AcmpCore.A19AResponseWithoutRoomIsOwedAndItsChangeWaits",
           "A19 but its change is not reported while its response waits (#653)",
           (("acmp", "AcmpMailbox.E1AnOwedResponseLeavesFirstAndItsChangeAfterIt", "E1 nothing reported yet"),)),
    Mutant("acmp-full-queue-acts", "acmp/acmp.c",
           "\tif (a->owed_count < ACMP_OWED_MAX) {\n\t\treturn true;\n\t}\n\ta->busy_drops++;",
           "\tif (true) {\n\t\treturn true;\n\t}\n\ta->busy_drops++;",
           "acmp", "AcmpCore.A19AFullQueueDropsTheCommandBeforeItActs",
           "A19 a command whose response would find the queue full is dropped"),
    Mutant("acmp-lost-probe-uncounted", "acmp/acmp.c",
           "\t\tsm_timer(a, s, ACMP_TIMER_NO_RESP, ACMP_TMR_NO_RESP_MS);\n\t\ta->probes_lost++;\n\t}",
           "\t\tsm_timer(a, s, ACMP_TIMER_NO_RESP, ACMP_TMR_NO_RESP_MS);\n\t}",
           "acmp", "AcmpCore.A19AProbeWithoutRoomIsLostAndRecovered",
           "A19 a probe the full queue cannot take is lost and counted"),
    Mutant("acmp-first-owed-releases-every-change", "acmp/acmp.c",
           "\t\t\t\ta->sinks[k].change_owed = (uint8_t)(a->sinks[k].change_owed - ((o->release >> k) & 1u));",
           "\t\t\t\ta->sinks[k].change_owed = 0u;",
           "acmp", "AcmpCore.A19TwoOwedResponsesForOneSinkReleaseTogether",
           "A19 the bind's response left but the unbind's is still owed"),
    Mutant("acmp-poll-newest-first", "acmp/acmp.c",
           "\t\tconst struct acmp_owed *o = &a->owed[a->owed_head];\n\t\tif (p_send(a, o->interface, o->frame)) {",
           "\t\tconst struct acmp_owed *o = &a->owed[(a->owed_head + a->owed_count - 1u) % ACMP_OWED_MAX];\n"
           "\t\tif (p_send(a, o->interface, o->frame)) {",
           "acmp", "AcmpMailbox.E2AnOwedResponseIsCommittedInPassKPlus1", "E2 3 frames owed ahead",
           (("acmp", "AcmpCore.A19NothingPassesAnOwedFrame", "A19 they leave in the order they were made"),)),
    # the talker (A20, TW)
    Mutant("acmp-probe-tx-reports-asking-failed", "acmp/acmp.c",
           "\t\t\tr.flags = cmd->flags & (ACMP_FLAG_FAST_CONNECT | ACMP_FLAG_STREAMING_WAIT);",
           "\t\t\tr.flags = (uint16_t)((cmd->flags & (ACMP_FLAG_FAST_CONNECT | ACMP_FLAG_STREAMING_WAIT)) |\n"
           "\t\t\t\t\t   (st.asking_failed ? ACMP_FLAG_REGISTERING_FAILED : 0u));",
           "acmp", "AcmpCore.A20ProbeTxIsAnsweredFromTheSource", "A20 PROBE_TX_RESPONSE is Table 5.43"),
    Mutant("acmp-probe-tx-echoes-every-flag", "acmp/acmp.c",
           "\t\t\tr.flags = cmd->flags & (ACMP_FLAG_FAST_CONNECT | ACMP_FLAG_STREAMING_WAIT);",
           "\t\t\tr.flags = cmd->flags;",
           "acmpwalk", "TalkerWalk.TW1ProbeTheFlagLawAndTheSource",
           "TW1 PROBE_TX: SUCCESS, FAST_CONNECT and STREAMING_WAIT echoed"),
    Mutant("acmp-probe-tx-any-interface", "acmp/acmp.c",
           "\tif (cmd->msg == ACMP_MSG_PROBE_TX_COMMAND && interface != a->cfg.source_interface[src]) {",
           "\tif (cmd->msg == ACMP_MSG_PROBE_TX_COMMAND && false) {",
           "acmp", "AcmpCore.A20ProbeTxIsAnsweredFromTheSource", "A20 a probe from another interface than the source's",
           (("acmpwalk", "TalkerWalk.TW4TheInterfaceAndTheStatelessProperty", "TW4 a probe from another interface"),)),
    Mutant("acmp-probe-tx-no-destination-mac-check", "acmp/acmp.c",
           "\t\tstruct pdu r = echo(cmd, st.dest_mac_valid ? ACMP_STATUS_SUCCESS : ACMP_STATUS_TALKER_DEST_MAC_FAIL);",
           "\t\tstruct pdu r = echo(cmd, ACMP_STATUS_SUCCESS);",
           "acmp", "AcmpCore.A20ProbeTxIsAnsweredFromTheSource", "A20 no destination MAC: TALKER_DEST_MAC_FAILED",
           (("acmpwalk", "TalkerWalk.TW1ProbeTheFlagLawAndTheSource", "TW1 no destination MAC"),)),
    Mutant("acmp-disconnect-always-succeeds", "acmp/acmp.c",
           "\tif (src >= a->cfg.n_sources) {\n\t\tstruct pdu r = echo(cmd, ACMP_STATUS_TALKER_UNKNOWN_ID);",
           "\tif (src >= a->cfg.n_sources && cmd->msg != ACMP_MSG_DISCONNECT_TX_COMMAND) {\n"
           "\t\tstruct pdu r = echo(cmd, ACMP_STATUS_TALKER_UNKNOWN_ID);",
           "acmp", "AcmpCore.A20DisconnectGetTxStateAndGetTxConnection",
           "A20 DISCONNECT_TX of an unknown source: TALKER_UNKNOWN_ID",
           (("acmpwalk", "TalkerWalk.TW3DisconnectAndGetTxConnection", "TD1 DISCONNECT_TX of an unknown source"),)),
    Mutant("acmp-unknown-source-answered", "acmp/acmp.c",
           "\tif (src >= a->cfg.n_sources) {\n\t\tstruct pdu r = echo(cmd, ACMP_STATUS_TALKER_UNKNOWN_ID);",
           "\tif (src >= a->cfg.n_sources && false) {\n\t\tstruct pdu r = echo(cmd, ACMP_STATUS_TALKER_UNKNOWN_ID);",
           "acmp", "AcmpCore.A20ProbeTxIsAnsweredFromTheSource", "A20 an unknown source: TALKER_UNKNOWN_ID",
           (("acmpwalk", "TalkerWalk.TW2GetTxStateReadsRegisteringFailedLive", "TW2 an unknown source"),)),
    Mutant("acmp-get-tx-state-echoes-the-listener", "acmp/acmp.c",
           "\tr.listener = 0u;\n\tr.listener_uid = 0u;\n\tr.flags = st.asking_failed",
           "\tr.flags = st.asking_failed",
           "acmp", "AcmpCore.A20DisconnectGetTxStateAndGetTxConnection", "A20 GET_TX_STATE: listener fields 0",
           (("acmpwalk", "TalkerWalk.TW2GetTxStateReadsRegisteringFailedLive",
             "TW2 GET_TX_STATE: listener fields 0"),)),
    Mutant("acmp-get-tx-state-registering-failed-0", "acmp/acmp.c",
           "\tr.flags = st.asking_failed ? ACMP_FLAG_REGISTERING_FAILED : 0u;", "\tr.flags = 0u;",
           "acmp", "AcmpCore.A20DisconnectGetTxStateAndGetTxConnection", "REGISTERING_FAILED live",
           (("acmpwalk", "TalkerWalk.TW2GetTxStateReadsRegisteringFailedLive",
             "TW2 GET_TX_STATE: listener fields 0"),)),
    Mutant("acmp-get-tx-state-unheld-mac", "acmp/acmp.c",
           "\tr.dest_mac = st.dest_mac_valid ? st.stream.dest_mac : 0u;", "\tr.dest_mac = st.stream.dest_mac;",
           "acmp", "AcmpCore.A20DisconnectGetTxStateAndGetTxConnection",
           "A20 with no destination MAC held, none is reported"),
    Mutant("acmp-get-tx-connection-supported", "acmp/acmp.c",
           "\t\tstruct pdu r = echo(cmd, ACMP_STATUS_NOT_SUPPORTED);              // 5.5.4.4, Table 5.48",
           "\t\tstruct pdu r = echo(cmd, ACMP_STATUS_SUCCESS);",
           "acmp", "AcmpCore.A20DisconnectGetTxStateAndGetTxConnection", "A20 GET_TX_CONNECTION: NOT_SUPPORTED",
           (("acmpwalk", "TalkerWalk.TW3DisconnectAndGetTxConnection", "TW3 GET_TX_CONNECTION: NOT_SUPPORTED"),)),
    # what the core does not take (A21)
    Mutant("acmp-every-listener-is-this-one", "acmp/acmp.c", "\tbool listener = cmd.listener == a->cfg.entity_id;",
           "\tbool listener = true;", "acmp", "AcmpCore.A21MessagesNotForThisEntityAreIgnored",
           "A21 commands for another listener or talker"),
    Mutant("acmp-every-talker-is-this-one", "acmp/acmp.c", "\tbool talker = cmd.talker == a->cfg.entity_id;",
           "\tbool talker = true;", "acmp", "AcmpCore.A21MessagesNotForThisEntityAreIgnored",
           "A21 commands for another listener or talker"),
    Mutant("acmp-short-pdu-read", "acmp/acmp.c",
           "\tif (interface >= a->cfg.n_interfaces || len < ACMP_FRAME_BYTES || wire_be16(frame + 12) != "
           "ACMP_ETHERTYPE ||",
           "\tif (interface >= a->cfg.n_interfaces || len < ACMP_FRAME_BYTES - 1u || wire_be16(frame + 12) != "
           "ACMP_ETHERTYPE ||",
           "acmp", "AcmpCore.A21MalformedFramesAreCounted", "A21 a frame shorter than the Milan ACMPDU"),
    Mutant("acmp-longer-pdu-refused", "acmp/acmp.c",
           "\tif (interface >= a->cfg.n_interfaces || len < ACMP_FRAME_BYTES || wire_be16(frame + 12) != "
           "ACMP_ETHERTYPE ||",
           "\tif (interface >= a->cfg.n_interfaces || len != ACMP_FRAME_BYTES || wire_be16(frame + 12) != "
           "ACMP_ETHERTYPE ||",
           "acmp", "AcmpCore.A21MalformedFramesAreCounted", "A21 the longer IEEE 1722.1-2021 PDU is accepted"),
    # discovery (A22, DW)
    Mutant("acmp-discovery-reads-no-grandmaster", "acmp/acmp.c",
           "\treturn d->gm == d->local_gm && d->domain == d->local_domain;", "\treturn true;",
           "acmp", "AcmpCore.A22AvailableDiscoversWhenTheGrandmasterMatches",
           "A22 TK_NOT_DISCOVERED: an AVAILABLE from another grandmaster",
           (("acmpwalk", "Table554/DiscoveryWalk.Graded/AVAILABLE_GM_mismatch__index____last__TK_NOT_DISCOVERED",
             "the discovery state"),)),
    Mutant("acmp-discovery-reads-no-domain", "acmp/acmp.c",
           "\treturn d->gm == d->local_gm && d->domain == d->local_domain;", "\treturn d->gm == d->local_gm;",
           "acmp", "AcmpCore.A22AvailableDiscoversWhenTheGrandmasterMatches", "A22 and from another domain",
           (("acmpwalk", "Table554/DiscoveryWalk.Graded/AVAILABLE_domain_mismatch__index____last__TK_DISCOVERED",
             "the discovery state"),)),
    Mutant("acmp-valid-time-in-seconds", "acmp/acmp.c",
           "\td.valid_ms = (uint32_t)(frame[A_VALID_TIME] >> 3) * ACMP_VALID_TIME_UNIT_MS;   // 6.2.2.5",
           "\td.valid_ms = (uint32_t)(frame[A_VALID_TIME] >> 3) * 1000u;",
           "acmp", "AcmpCore.A22AvailableDiscoversWhenTheGrandmasterMatches",
           "A22 TMR_NO_ADP is the received valid_time in two-second units",
           (("acmpwalk", "Table554/DiscoveryWalk.Graded/", "TMR_NO_ADP armed from the received valid_time"),)),
    Mutant("acmp-discovered-interface-unchecked", "acmp/acmp.c",
           "\tif (ifx != s->disc_interface_index) {\n"
           "\t\treturn;                                         // 5.6.4.5.2 step 1",
           "\tif (false) {\n\t\treturn;",
           "acmp", "AcmpCore.A22DiscoveredStateCells",
           "A22 TK_DISCOVERED: an AVAILABLE with another interface_index is ignored",
           (("acmpwalk", "Table554/DiscoveryWalk.Graded/AVAILABLE_interface_index_differs__TK_DISCOVERED",
             "TMR_NO_ADP untouched"),)),
    Mutant("acmp-restart-on-a-smaller-index-only", "acmp/acmp.c",
           "\tif (index <= s->disc_available_index) {                 // step 2: a new availability cycle",
           "\tif (index < s->disc_available_index) {",
           "acmp", "AcmpCore.A22DiscoveredStateCells", "A22 available_index 700 <= last"),
    Mutant("acmp-restart-raises-no-discovered", "acmp/acmp.c",
           "\t\ttk_discovered(a, s);                            // 2c\n", "",
           "acmp", "AcmpCore.A22DiscoveredStateCells", "EVT_TK_DEPARTED then EVT_TK_DISCOVERED",
           (("acmpwalk", "Table554/DiscoveryWalk.Graded/AVAILABLE_match__index____last__TK_DISCOVERED",
             "the events raised"),)),
    Mutant("acmp-restart-mismatch-keeps-aging", "acmp/acmp.c",
           "\t\t\ts->adp_armed = false;                   // 2b: TK_NOT_DISCOVERED, no step 3", "\t\t\t(void)s;",
           "acmp", "AcmpCore.A22DiscoveredStateCells", "A22 index <= last from another grandmaster",
           (("acmpwalk", "Table554/DiscoveryWalk.Graded/AVAILABLE_GM_mismatch__index____last__TK_DISCOVERED",
             "TMR_NO_ADP stopped"),)),
    Mutant("acmp-refresh-notes-no-index", "acmp/acmp.c",
           "\ts->disc_available_index = index;                        // step 3\n",
           "", "acmp", "AcmpCore.A22DiscoveredStateCells", "A22 a rising available_index is noted",
           (("acmpwalk", "Table554/DiscoveryWalk.Graded/AVAILABLE_match__index___last__TK_DISCOVERED",
             "the available_index noted"),)),
    Mutant("acmp-departing-taken-undiscovered", "acmp/acmp.c",
           "\tif (!s->discovered || ifx != s->disc_interface_index) {", "\tif (ifx != s->disc_interface_index) {",
           "acmp", "AcmpCore.A22DepartingAndAging", "A22 a DEPARTING in TK_NOT_DISCOVERED is ignored"),
    Mutant("acmp-departing-interface-unchecked", "acmp/acmp.c",
           "\tif (!s->discovered || ifx != s->disc_interface_index) {", "\tif (!s->discovered) {\n\t\t(void)ifx;",
           "acmp", "AcmpCore.A22DepartingAndAging", "A22 a DEPARTING with another interface_index is ignored",
           (("acmpwalk", "Table554/DiscoveryWalk.Graded/DEPARTING_interface_index_differs__TK_DISCOVERED",
             "the discovery state"),)),
    Mutant("acmp-departing-keeps-aging", "acmp/acmp.c", "\ts->adp_armed = false;\n\ttk_departed(s);\n}",
           "\ttk_departed(s);\n}", "acmp", "AcmpCore.A22DepartingAndAging", "A22 a DEPARTING: TMR_NO_ADP stopped",
           (("acmpwalk", "Table554/DiscoveryWalk.Graded/DEPARTING_interface_index_matches__TK_DISCOVERED",
             "TMR_NO_ADP stopped"),)),
    Mutant("acmp-no-aging", "acmp/acmp.c",
           "\t\tif (s->adp_armed && due(s->adp_deadline, now(a))) {      // 5.6.4.5.4",
           "\t\tif (s->adp_armed && due(s->adp_deadline, now(a)) && false) {",
           "acmp", "AcmpCore.A22DepartingAndAging", "A22 TMR_NO_ADP: TK_NOT_DISCOVERED and EVT_TK_DEPARTED",
           (("acmpwalk", "Table554/DiscoveryWalk.Graded/TMR_NO_ADP_TK_DISCOVERED", "the discovery state"),)),
    Mutant("acmp-discovery-on-every-interface", "acmp/acmp.c",
           "\t\tif (!s->disc_running || s->interface != interface || s->binding.talker_entity_id != entity) {",
           "\t\tif (!s->disc_running || s->binding.talker_entity_id != entity) {",
           "acmp", "AcmpCore.A22OnlyBoundSinksOfThatTalkerOnThatInterface",
           "A22 every bound sink of the talker processes it"),
    Mutant("acmp-discovery-on-unbound-sinks", "acmp/acmp.c",
           "\t\tif (!s->disc_running || s->interface != interface || s->binding.talker_entity_id != entity) {",
           "\t\tif (s->interface != interface || s->binding.talker_entity_id != entity) {",
           "acmp", "AcmpCore.A22OnlyBoundSinksOfThatTalkerOnThatInterface", "A22 an unbound sink runs no discovery"),
    Mutant("acmp-grandmaster-sampled-for-the-refresh", "acmp/acmp.c",
           "\tuint16_t ifx = d->ifx;\n\tuint32_t index = d->index;",
           "\t(void)gm_matches(a, d);\n\tuint16_t ifx = d->ifx;\n\tuint32_t index = d->index;",
           "acmp", "AcmpCore.A22DiscoveredStateCells",
           "A22 TK_DISCOVERED: an AVAILABLE with another interface_index is ignored"),
    Mutant("acmp-grandmaster-sampled-per-sink", "acmp/acmp.c", "\t\td->sampled = true;\n", "",
           "acmp", "AcmpCore.A22OnlyBoundSinksOfThatTalkerOnThatInterface",
           "A22 and the grandmaster is sampled once for the frame"),
    # the no-callback rule (A23, #678)
    Mutant("acmp-reentry-unguarded", "acmp/acmp.c", "\tif (a->in_port) {\n\t\ta->reentries++;",
           "\tif (false) {\n\t\ta->reentries++;",
           "acmp", "AcmpCore.A23EveryEntryRefusesACallFromInsideAPort",
           "A23 a call made from inside the send port is refused",
           (("acmp", "AcmpCore.A23EveryPortIsGuarded", "A23 the port kind 1 is guarded"),)),
    Mutant("acmp-reentry-untrapped", "acmp/acmp.c", "\t\tREENTRY_TRAP();\n", "",
           "acmp", "AcmpCore.A23EveryEntryRefusesACallFromInsideAPort", "refused, counted and trapped"),
    Mutant("acmp-send-port-unflagged", "acmp/acmp.c", "\ta->in_port = true;\n\tbool ok = a->ports->send(",
           "\tbool ok = a->ports->send(",
           "acmp", "AcmpCore.A23EveryEntryRefusesACallFromInsideAPort",
           "A23 a call made from inside the send port is refused"),
    Mutant("acmp-timer-port-unflagged", "acmp/acmp.c", "\ta->in_port = true;\n\ta->ports->timer(", "\ta->ports->timer(",
           "acmp", "AcmpCore.A23EveryPortIsGuarded", "A23 the port kind 1 is guarded"),
    Mutant("acmp-gptp-port-unflagged", "acmp/acmp.c", "\ta->in_port = true;\n\ta->ports->gptp(", "\ta->ports->gptp(",
           "acmp", "AcmpCore.A23EveryPortIsGuarded", "A23 the port kind 2 is guarded"),
    Mutant("acmp-clock-port-unflagged", "acmp/acmp.c", "\t\ta->in_port = true;\n\t\ta->now = a->ports->now_ms(",
           "\t\ta->now = a->ports->now_ms(",
           "acmp", "AcmpCore.A23EveryPortIsGuarded", "A23 the port kind 3 is guarded"),
    Mutant("acmp-seed-port-unflagged", "acmp/acmp.c", "\ta->in_port = true;\n\tuint32_t seed = a->ports->seed(",
           "\tuint32_t seed = a->ports->seed(",
           "acmp", "AcmpCore.A23EveryPortIsGuarded", "A23 the port kind 4 is guarded"),
    Mutant("acmp-lock-port-unflagged", "acmp/acmp.c", "\ta->in_port = true;\n\tbool locked = a->env->locked(",
           "\tbool locked = a->env->locked(",
           "acmp", "AcmpCore.A23EveryPortIsGuarded", "A23 the port kind 5 is guarded"),
    Mutant("acmp-source-port-unflagged", "acmp/acmp.c", "\ta->in_port = true;\n\ta->env->source(", "\ta->env->source(",
           "acmp", "AcmpCore.A23EveryPortIsGuarded", "A23 the port kind 6 is guarded"),
    Mutant("acmp-srp-port-unflagged", "acmp/acmp.c", "\ta->in_port = true;\n\ta->env->srp(", "\ta->env->srp(",
           "acmp", "AcmpCore.A23EveryPortIsGuarded", "A23 the port kind 7 is guarded"),
    Mutant("acmp-persist-port-unflagged", "acmp/acmp.c", "\ta->in_port = true;\n\ta->env->persist(",
           "\ta->env->persist(",
           "acmp", "AcmpCore.A23EveryPortIsGuarded", "A23 the port kind 8 is guarded"),
    Mutant("acmp-changed-port-unflagged", "acmp/acmp.c", "\ta->in_port = true;\n\ta->env->changed(",
           "\ta->env->changed(",
           "acmp", "AcmpCore.A23EveryPortIsGuarded", "A23 the port kind 9 is guarded"),
    # the saved record (A24, N)
    Mutant("acmp-restore-lands-in-prb-w-resp", "acmp/acmp.c",
           "\t\ts->probing = ACMP_PROBING_PASSIVE;\n\t\ts->state = ACMP_PRB_W_AVAIL;\n\t}\n\tsink_settle(s);",
           "\t\ts->probing = ACMP_PROBING_PASSIVE;\n\t\ts->state = ACMP_PRB_W_RESP;\n\t}\n\tsink_settle(s);",
           "acmp", "AcmpCore.A24ARestoredBindingFastConnects", "A24 startup with a saved binding",
           (("acmpnvm", "AcmpStore.N1ABindSurvivesAPowerCycleAndFastConnects", "N1 into PRB_W_AVAIL"),)),
    Mutant("acmp-restore-starts-no-discovery", "acmp/acmp.c",
           "\t\tdisc_start(s);\n\t\ts->probing = ACMP_PROBING_PASSIVE;", "\t\ts->probing = ACMP_PROBING_PASSIVE;",
           "acmp", "AcmpCore.A24ARestoredBindingFastConnects", "A24 startup with a saved binding",
           (("acmpnvm", "AcmpStore.N1ABindSurvivesAPowerCycleAndFastConnects", "N1 into PRB_W_AVAIL"),)),
    Mutant("acmp-restore-announced", "acmp/acmp.c", "\t}\n\tsink_settle(s);\n\treturn ACMP_RESTORE_APPLIED;",
           "\t}\n\treturn ACMP_RESTORE_APPLIED;",
           "acmpnvm", "AcmpStore.N1ABindSurvivesAPowerCycleAndFastConnects", "N1 probing saves nothing"),
    Mutant("acmp-record-flags-swapped", "acmp/acmp.c",
           "\t\tpayload[0] = (uint8_t)(BIND_VALID | (s->started ? BIND_STARTED : 0u) |\n"
           "\t\t\t\t       (s->binding.streaming_wait ? BIND_STREAMING_WAIT : 0u));",
           "\t\tpayload[0] = (uint8_t)(BIND_VALID | (s->started ? BIND_STREAMING_WAIT : 0u) |\n"
           "\t\t\t\t       (s->binding.streaming_wait ? BIND_STARTED : 0u));",
           "acmpnvm", "AcmpStore.N3EachSinksStartedStateIsSaved",
           "N3 each sink's started state and STREAMING_WAIT come back"),
    Mutant("acmp-record-unique-id-little-endian", "acmp/acmp.c",
           "\t\twire_put_be(payload + 2, s->binding.talker_unique_id, 2);",
           "\t\tpayload[2] = (uint8_t)s->binding.talker_unique_id;\n"
           "\t\tpayload[3] = (uint8_t)(s->binding.talker_unique_id >> 8);",
           "acmp", "AcmpCore.A24ARestoredBindingFastConnects", "A24 the latch gives the same record back"),
    Mutant("acmp-restore-unique-id-little-endian", "acmp/acmp.c",
           "\t\ts->binding.talker_unique_id = wire_be16(payload + 2);",
           "\t\ts->binding.talker_unique_id = (uint16_t)(payload[2] | (payload[3] << 8));",
           "acmp", "AcmpCore.A24ARestoredBindingFastConnects", "A24 the record's flags and parameters, big-endian"),
    Mutant("acmp-roll-back-keeps-the-bindings", "acmp/acmp.c",
           "\tfor (unsigned k = 0; k < a->cfg.n_sinks; ++k) {\n\t\tsink_reset(a, k);\n\t\tsink_settle(&a->sinks[k]);\n"
           "\t}\n}",
           "\t(void)a;\n}",
           "acmp", "AcmpCore.A24UnboundRecordsRefusalsAndRollback", "A24 the roll-back drops every restored binding",
           (("acmpnvm", "AcmpStore.N6TheRollBackAndEveryOtherGroup", "N6 and drops what it applied"),)),
    Mutant("acmp-unbound-record-not-zero", "acmp/acmp.c",
           "\tmemset(payload, 0, ACMP_BINDING_BYTES);\n\tif (s->bound) {",
           "\tpayload[1] = 0u;\n\tif (s->bound) {",
           "acmp", "AcmpCore.A24UnboundRecordsRefusalsAndRollback", "A24 an unbound sink's record is all zeros"),
    Mutant("acmp-started-not-saved", "acmp/acmp.c", "\ta->sinks[sink].started = started;\n\tfinish(a);",
           "\ta->sinks[sink].started = started;",
           "acmp", "AcmpCore.A24StartedIsSavedAndReported", "A24 the started state is saved (5.3.8.7)",
           (("acmpnvm", "AcmpStore.N3EachSinksStartedStateIsSaved", "N3 the started state alone is a change"),)),
    # the notification follows Table 5.22 (A25, LW)
    Mutant("acmp-discovery-notifies", "acmp/acmp.c",
           "\t\t\t(uint64_t)(x->registering_failed != y->registering_failed);",
           "\t\t\t(uint64_t)(x->registering_failed != y->registering_failed) |\n"
           "\t\t\t(uint64_t)(x->talker_discovered != y->talker_discovered);",
           "acmp", "AcmpCore.A25OnlyTable522ItemsAreReported",
           "A25 discovery noted while settled moves no Table 5.22 item",
           (("acmpwalk", "Table530/ListenerWalk.Graded/TK_DISC_PWR",
             "notified exactly when a Table 5.22 item moved"),)),
    Mutant("acmp-status-not-notified", "acmp/acmp.c",
           "\t\t\t(uint64_t)(x->acmp_status ^ y->acmp_status) | (uint64_t)(x->bound != y->bound) |",
           "\t\t\t(uint64_t)(x->bound != y->bound) |",
           "acmp", "AcmpCore.A25OnlyTable522ItemsAreReported", "A25 the ACMP status LISTENER_TALKER_TIMEOUT does"),
    Mutant("acmp-probing-status-not-notified", "acmp/acmp.c",
           "\t\t\t(uint64_t)((unsigned)x->probing_status ^ (unsigned)y->probing_status) |\n", "",
           "acmpwalk", "Table530/ListenerWalk.Graded/TK_DEP_PWD", "notified exactly when a Table 5.22 item moved"),
    # the adapter on the model (B)
    Mutant("acmp-frames-on-the-adp-channel", "acmp/acmp_mbx.c",
           "\treturn mbx_tx_send(MBX_CH_ACMP, interface, frame, (uint16_t)len) == MBX_STATUS_OK;",
           "\treturn mbx_tx_send(MBX_CH_ADP, interface, frame, (uint16_t)len) == MBX_STATUS_OK;",
           "acmp", "AcmpMailbox.B1TheChannelCarriesCommandsAndResponsesInOrder",
           "B1 the response, then the probe, on the acmp channel"),
    Mutant("acmp-timer-on-the-next-slot", "acmp/acmp_mbx.c", "\tmbx_timer_arm(i->slot, i->tag, deadline_ms);",
           "\tmbx_timer_arm((unsigned)i->slot + 1u, i->tag, deadline_ms);",
           "acmp", "AcmpMailbox.B3TheTimersRunOnTheInterfaceSlot",
           "B3 TMR_NO_RESP is armed on interface 0's ACMP slot"),
    Mutant("acmp-timer-deadline-taken-as-a-delay", "acmp/acmp_mbx.c", "\tmbx_timer_arm(i->slot, i->tag, deadline_ms);",
           "\tmbx_timer_arm(i->slot, i->tag, mbx_now_ms() + deadline_ms);",
           "acmp", "AcmpMailbox.B3TheTimersRunOnTheInterfaceSlot",
           "B3 TMR_NO_RESP is armed on interface 0's ACMP slot at NOW_MS + 200"),
    Mutant("acmp-stale-tag-taken", "acmp/acmp_mbx.c", "\t\tif (!i->armed || ev->timer_tag != i->tag) {",
           "\t\tif (!i->armed) {",
           "acmp", "AcmpMailbox.B4AnExpiryThatRacedAStopOrAReArmIsDiscarded", "B4 the expiry of a replaced arm"),
    Mutant("acmp-tag-reused", "acmp/acmp_mbx.c", "\ti->tag_seq = (uint16_t)(i->tag_seq + 1u);\n\ti->tag = i->tag_seq;",
           "\ti->tag = i->tag_seq;",
           "acmp", "AcmpMailbox.B4AnExpiryThatRacedAStopOrAReArmIsDiscarded", "B4 the expiry of a replaced arm"),
    Mutant("acmp-stop-keeps-the-arm", "acmp/acmp_mbx.c", "\ti->armed = armed;\n\tif (!armed) {",
           "\ti->armed = true;\n\tif (!armed) {",
           "acmp", "AcmpMailbox.B4AnExpiryThatRacedAStopOrAReArmIsDiscarded",
           "B4 the expiry of a stopped arm is counted"),
    Mutant("acmp-tap-takes-discover", "acmp/acmp_mbx.c",
           "\tif ((f->bytes[ACMP_HEADER_BYTES + 1u] & 0x0Fu) <= ACMP_ADP_MSG_ENTITY_DEPARTING) {",
           "\tif ((f->bytes[ACMP_HEADER_BYTES + 1u] & 0x0Fu) <= 2u) {",
           "acmp", "AcmpMailbox.B5TheTapHandsAvailableToDiscoveryAndTheRestToAdp",
           "B5 an ENTITY_DISCOVER still goes to ADP"),
    Mutant("acmp-tap-drops-the-rest", "acmp/acmp_mbx.c", "\tm->adp_next.fn(m->adp_next.ctx, f);", "\t(void)f;",
           "acmp", "AcmpMailbox.B5TheTapHandsAvailableToDiscoveryAndTheRestToAdp",
           "B5 an ENTITY_DISCOVER still goes to ADP"),
    Mutant("acmp-no-tap", "acmp/acmp_mbx.c", "\t(void)ctrl_loop_bind_rx(l, MBX_CH_ADP, on_adp_frame, m);",
           "\t(void)on_adp_frame;",
           "acmp", "AcmpMailbox.B5TheTapHandsAvailableToDiscoveryAndTheRestToAdp",
           "B5 and reaches discovery through the tap",
           (("acmp", "AcmpMailbox.U5AcmpComesAfterAdpAndReadsNothingBeforeTheContract",
             "U5 ACMP binds its channel and stands in front of ADP's handler"),)),
    Mutant("acmp-domain-not-sampled", "acmp/acmp_mbx.c", "\t*gm_id = mbx_gm_id(interface, domain);",
           "\t*gm_id = mbx_gm_id(interface, NULL);\n\t*domain = 0u;",
           "acmp", "AcmpMailbox.B6TheGrandmasterIsTheInterfaces",
           "B6 one from interface 0's grandmaster and domain is taken"),
    Mutant("acmp-attach-before-adp", "acmp/acmp_mbx.c",
           "\tif (l->rx[MBX_CH_ADP].fn == NULL || !ctrl_loop_add_sink(l, on_event, m) || !ctrl_loop_add_poll(l, "
           "on_poll, m)) {",
           "\tif (!ctrl_loop_add_sink(l, on_event, m) || !ctrl_loop_add_poll(l, on_poll, m)) {",
           "acmp", "AcmpAdapterUnit.B7RefusalsOfTheAdapter",
           "B7 attaching before ADP bound the adp channel is refused"),
    Mutant("acmp-attach-ignores-sink-room", "acmp/acmp_mbx.c", "|| !ctrl_loop_add_sink(l, on_event, m) ||",
           "|| (!ctrl_loop_add_sink(l, on_event, m) && false) ||",
           "acmp", "AcmpAdapterUnit.B7RefusalsOfTheAdapter", "B7 a loop with no room for the event sink is refused"),
    Mutant("acmp-attach-ignores-poll-room", "acmp/acmp_mbx.c", "|| !ctrl_loop_add_poll(l, on_poll, m)) {",
           "|| (!ctrl_loop_add_poll(l, on_poll, m) && false)) {",
           "acmp", "AcmpAdapterUnit.B7RefusalsOfTheAdapter", "B7 a loop with no room for the poll is refused"),
    Mutant("acmp-slots-past-the-bank", "acmp/acmp_mbx.c",
           "\tif (first_slot > MBX_N_TIMERS - MBX_N_IF || cfg->n_interfaces > MBX_N_IF) {",
           "\tif (cfg->n_interfaces > MBX_N_IF) {",
           "acmp", "AcmpAdapterUnit.B7RefusalsOfTheAdapter", "B7 a first slot of 16 is refused"),
    Mutant("acmp-interfaces-past-the-mailbox", "acmp/acmp_mbx.c",
           "\tif (first_slot > MBX_N_TIMERS - MBX_N_IF || cfg->n_interfaces > MBX_N_IF) {",
           "\tif (first_slot > MBX_N_TIMERS - MBX_N_IF) {",
           "acmp", "AcmpAdapterUnit.B7RefusalsOfTheAdapter", "B7 more interfaces than the mailbox has are refused"),
    Mutant("acmp-poll-owes-nothing", "acmp/acmp_mbx.c", "\treturn acmp_poll(&m->acmp);",
           "\t(void)acmp_poll(&m->acmp);\n\treturn false;",
           "acmp", "AcmpMailbox.E1AnOwedResponseLeavesFirstAndItsChangeAfterIt",
           "E1 nothing reported yet, and the loop does not sleep"),
    # the service cost (C), one extra access per path
    Mutant("acmp-bind-reads-the-clock-twice", "acmp/acmp.c", "\tdisc_start(s);\n\tprobe(a, k);",
           "\tdisc_start(s);\n\t(void)a->ports->now_ms(a->ports->ctx);\n\tprobe(a, k);",
           "acmp", "AcmpMailbox.C0ToC4CommandsAreAnsweredInThePassThatTakesThem",
           "C0 BIND_RX -> response, PROBE_TX, TMR_NO_RESP"),
    Mutant("acmp-get-rx-state-reads-the-clock", "acmp/acmp.c",
           "\tconst struct acmp_sink *s = &a->sinks[k];\n\tstruct pdu r = echo(cmd, ACMP_STATUS_SUCCESS);",
           "\tconst struct acmp_sink *s = &a->sinks[k];\n\t(void)now(a);\n"
           "\tstruct pdu r = echo(cmd, ACMP_STATUS_SUCCESS);",
           "acmp", "AcmpMailbox.C0ToC4CommandsAreAnsweredInThePassThatTakesThem", "C1 GET_RX_STATE -> response"),
    Mutant("acmp-probe-response-reads-the-clock-twice", "acmp/acmp.c",
           "\tsm_stop(s);                                             // step 2",
           "\tsm_stop(s);\n\t(void)a->ports->now_ms(a->ports->ctx);",
           "acmp", "AcmpMailbox.C0ToC4CommandsAreAnsweredInThePassThatTakesThem",
           "C2 PROBE_TX_RESPONSE -> TMR_NO_TK armed"),
    Mutant("acmp-unbind-reads-the-clock", "acmp/acmp.c",
           "\ts->acmp_status = ACMP_STATUS_SUCCESS;\n\tsm_stop(s);\n\tstruct pdu r",
           "\ts->acmp_status = ACMP_STATUS_SUCCESS;\n\tsm_stop(s);\n\t(void)now(a);\n\tstruct pdu r",
           "acmp", "AcmpMailbox.C0ToC4CommandsAreAnsweredInThePassThatTakesThem",
           "C3 UNBIND_RX -> response, timer stopped"),
    Mutant("acmp-talker-reads-the-clock", "acmp/acmp.c",
           "\tunsigned src = cmd->talker_uid;\n\tif (cmd->msg == ACMP_MSG_GET_TX_CONNECTION_COMMAND) {",
           "\tunsigned src = cmd->talker_uid + 0u * now(a);\n\tif (cmd->msg == ACMP_MSG_GET_TX_CONNECTION_COMMAND) {",
           "acmp", "AcmpMailbox.C0ToC4CommandsAreAnsweredInThePassThatTakesThem", "C4 talker command -> response"),
    Mutant("acmp-expiry-reads-the-clock-twice", "acmp/acmp.c",
           "\ta->timer_armed[interface] = false;                      // the port's timer has fired\n",
           "\ta->timer_armed[interface] = false;\n\t(void)a->ports->now_ms(a->ports->ctx);\n",
           "acmp", "AcmpMailbox.C5ToC9TimerPathsAreServedInThePassThatTakesTheExpiry",
           "C5 TMR_NO_RESP -> duplicate PROBE_TX, TMR_NO_RESP"),
    Mutant("acmp-available-reads-the-clock-twice", "acmp/acmp.c", "\ts->adp_deadline = now(a) + valid_ms;",
           "\ts->adp_deadline = now(a) + valid_ms + 0u * a->ports->now_ms(a->ports->ctx);",
           "acmp", "AcmpMailbox.C10C11DiscoveryPathsAreServedInThePassThatTakesTheRecord",
           "C10 ENTITY_AVAILABLE from its RX_HEAD -> TMR_DELAY armed"),
    Mutant("acmp-departing-samples-the-grandmaster", "acmp/acmp.c", "\t\t\tdisc_departing(s, d.ifx);",
           "\t\t\t(void)gm_matches(a, &d);\n\t\t\tdisc_departing(s, d.ifx);",
           "acmp", "AcmpMailbox.C10C11DiscoveryPathsAreServedInThePassThatTakesTheRecord",
           "C11 ENTITY_DEPARTING from its RX_HEAD -> timer stopped"),
    Mutant("acmp-aging-samples-the-grandmaster", "acmp/acmp.c", "\t\t\ts->adp_armed = false;\n\t\t\ttk_departed(s);",
           "\t\t\ts->adp_armed = false;\n\t\t\t{\n\t\t\t\tuint64_t g;\n\t\t\t\tuint8_t dm;\n"
           "\t\t\t\tp_gptp(a, interface, &g, &dm);\n\t\t\t}\n\t\t\ttk_departed(s);",
           "acmp", "AcmpMailbox.C12AgingIsServedInThePassThatTakesTheExpiry", "C12 TMR_NO_ADP -> TK_NOT_DISCOVERED"),
    # the backlog figures (F)
    Mutant("acmp-smallest-record-overstated", "acmp/acmp_mbx.h",
           "#define ACMP_MBX_RX_MIN_RECORD_WORDS (MBX_RX_HDR_WORDS + (MBX_CH_ACMP_T0_OFFSET + MBX_TERM_FIELD_BYTES + "
           "3u) / 4u)",
           "#define ACMP_MBX_RX_MIN_RECORD_WORDS (MBX_RX_HDR_WORDS + 1u + (MBX_CH_ACMP_T0_OFFSET + "
           "MBX_TERM_FIELD_BYTES + 3u) / 4u)",
           "acmp", "AcmpMailbox.F4TheSmallestRecordsTheFilterPassesFillTheRing",
           "F4 the ring holds ACMP_MBX_RX_BACKLOG records of the smallest frame"),
    Mutant("acmp-pass-bound-understated", "acmp/acmp_mbx.h", "#define ACMP_MBX_PASS_MAX      ",
           "#define ACMP_MBX_PASS_MAX (CTRL_LOOP_EVENTS_PER_PASS * MBX_EV_WORDS)\n"
           "#define ACMP_MBX_PASS_MAX_UNUSED      ",
           "acmp", "AcmpMailbox.F0ToF3FullRingsAreTakenWithinTheBound", "F3 the worst pass of the backlog"),
    Mutant("acmp-adp-ring-bound-understated", "acmp/acmp_mbx.h",
           "#define ACMP_MBX_ADP_RX_ACCESSES ((CTRL_LOOP_RX_PASSES(MBX_CH_ADP_RX_WORDS) + 1u) * ACMP_MBX_PASS_MAX)",
           "#define ACMP_MBX_ADP_RX_ACCESSES (CTRL_LOOP_RX_PASSES(MBX_CH_ADP_RX_WORDS) * MBX_RX_HDR_WORDS)",
           "acmp", "AcmpMailbox.F5AnAvailableBehindAFullAdpRingIsServedWithinTheBound",
           "F5 ENTITY_AVAILABLE behind a full adp ring"),
    Mutant("acmp-discovery-takes-the-first-sink", "acmp/acmp.c",
           "\tfor (unsigned k = 0; k < a->cfg.n_sinks; ++k) {        // 5.6.4.1: every bound sink of this talker",
           "\tfor (unsigned k = 0; k < a->cfg.n_sinks && taken == 0u; ++k) {",
           "acmp", "AcmpMailbox.F5AnAvailableBehindAFullAdpRingIsServedWithinTheBound",
           "F5 every matching bound sink takes it in the same pass"),
    Mutant("rx-one-record-per-pass", "loop/ctrl_loop.c", "for (unsigned k = 0; k < CTRL_LOOP_RX_PER_PASS; ++k) {",
           "for (unsigned k = 0; k < 1u; ++k) {",
           "acmp", "AcmpMailbox.F5AnAvailableBehindAFullAdpRingIsServedWithinTheBound",
           "F5 the ENTITY_AVAILABLE is taken by pass",
           (("acmp", "AcmpMailbox.F0ToF3FullRingsAreTakenWithinTheBound", "F2 every acmp record is taken by"),)),
    # the timer paths' own bounds (C6 to C9): each path made to read the bus more than its figure
    Mutant("acmp-second-no-resp-samples-the-grandmaster", "acmp/acmp.c",
           "\t} else if (kind == ACMP_TIMER_NO_RESP) {                // 5.5.3.5.23, in PRB_W_RESP2\n",
           "\t} else if (kind == ACMP_TIMER_NO_RESP) {                // 5.5.3.5.23, in PRB_W_RESP2\n\t\t{\n"
           "\t\t\tuint64_t g;\n\t\t\tuint8_t dm;\n\t\t\tp_gptp(a, s->interface, &g, &dm);\n\t\t}\n",
           "acmp", "AcmpMailbox.C5ToC9TimerPathsAreServedInThePassThatTakesTheExpiry",
           "C6 TMR_NO_RESP -> TMR_RETRY armed"),
    Mutant("acmp-retry-samples-the-grandmaster", "acmp/acmp.c",
           "\t} else if (kind == ACMP_TIMER_RETRY) {                  // step 2: the ACMP status stays\n",
           "\t} else if (kind == ACMP_TIMER_RETRY) {                  // step 2: the ACMP status stays\n\t\t{\n"
           "\t\t\tuint64_t g;\n\t\t\tuint8_t dm;\n\t\t\tp_gptp(a, s->interface, &g, &dm);\n\t\t}\n",
           "acmp", "AcmpMailbox.C5ToC9TimerPathsAreServedInThePassThatTakesTheExpiry",
           "C7 TMR_RETRY -> TMR_DELAY armed"),
    Mutant("acmp-delay-reads-the-clock-again", "acmp/acmp.c",
           "\tif (kind == ACMP_TIMER_DELAY) {                         // 5.5.3.5.10\n\t\tprobe(a, k);",
           "\tif (kind == ACMP_TIMER_DELAY) {                         // 5.5.3.5.10\n"
           "\t\t(void)a->ports->now_ms(a->ports->ctx);\n\t\tprobe(a, k);",
           "acmp", "AcmpMailbox.C5ToC9TimerPathsAreServedInThePassThatTakesTheExpiry",
           "C8 TMR_DELAY -> PROBE_TX, TMR_NO_RESP"),
    Mutant("acmp-no-tk-samples-the-grandmaster", "acmp/acmp.c", "\t\tsrp_stop(a, k);\n\t\treprobe(a, s);",
           "\t\t{\n\t\t\tuint64_t g;\n\t\t\tuint8_t dm;\n\t\t\tp_gptp(a, s->interface, &g, &dm);\n\t\t}\n"
           "\t\tsrp_stop(a, k);\n\t\treprobe(a, s);",
           "acmp", "AcmpMailbox.C5ToC9TimerPathsAreServedInThePassThatTakesTheExpiry",
           "C9 TMR_NO_TK -> TMR_DELAY armed"),
    # the backlog's own preconditions (F0)
    Mutant("acmp-backlog-understated", "acmp/acmp_mbx.h",
           "#define ACMP_MBX_RX_BACKLOG (MBX_CH_ACMP_RX_WORDS / ACMP_MBX_RX_MIN_RECORD_WORDS)",
           "#define ACMP_MBX_RX_BACKLOG (MBX_CH_ACMP_RX_WORDS / ACMP_MBX_RX_MIN_RECORD_WORDS / 2u)",
           "acmp", "AcmpMailbox.F0ToF3FullRingsAreTakenWithinTheBound",
           "F0 the acmp ring holds no more records than A1 assumes",
           (("acmp", "AcmpMailbox.F4TheSmallestRecordsTheFilterPassesFillTheRing",
             "F4 the ring holds ACMP_MBX_RX_BACKLOG records of the smallest frame"),)),
    Mutant("model-event-ring-a-record-short", "host/mbx_model.c",
           "uint16_t free_words = used > MBX_EVT_WORDS ? 0u : (uint16_t)(MBX_EVT_WORDS - used);",
           "uint16_t free_words = used >= MBX_EVT_WORDS - MBX_EV_WORDS ? 0u : "
           "(uint16_t)(MBX_EVT_WORDS - MBX_EV_WORDS - used);",
           "acmp", "AcmpMailbox.F0ToF3FullRingsAreTakenWithinTheBound", "F0 the event ring is full"),
    # a bind without STREAMING_WAIT (A1), the view's flags (A2)
    Mutant("acmp-new-bind-never-started", "acmp/acmp.c",
           "\t// START_STREAMING (Milan v1.2 5.3.8.7)\n\ts->started = !sw;",
           "\t// START_STREAMING (Milan v1.2 5.3.8.7)\n\ts->started = false;",
           "acmp", "AcmpCore.A1BindWithoutStreamingWaitBindsStarted", "A1 a bind without STREAMING_WAIT lands started"),
    Mutant("acmp-bind-response-always-streaming-wait", "acmp/acmp.c",
           "\tr.flags = cmd->flags & ACMP_FLAG_STREAMING_WAIT;\n\trespond(",
           "\tr.flags = ACMP_FLAG_STREAMING_WAIT;\n\trespond(",
           "acmp", "AcmpCore.A1BindWithoutStreamingWaitBindsStarted", "A1 a bind without STREAMING_WAIT lands started"),
    Mutant("acmp-view-without-registering-failed", "acmp/acmp.c",
           "\tv->registering_failed = v->talker_registered && s->tk_failed;",
           "\tv->registering_failed = false;",
           "acmp", "AcmpCore.A2GetRxStateReportsStreamingWaitAndRegisteringFailed", "A2 and the view says so"),
    # discovery from PRB_W_AVAIL (A22, 5.5.3.5.9) and the one grandmaster sample
    Mutant("acmp-discovered-probing-stays-passive", "acmp/acmp.c",
           "\t\ts->probing = ACMP_PROBING_ACTIVE;\n\t\ts->acmp_status = ACMP_STATUS_SUCCESS;\n\t\tdelay(a, s);",
           "\t\ts->acmp_status = ACMP_STATUS_SUCCESS;\n\t\tdelay(a, s);",
           "acmp", "AcmpCore.A22DiscoveredStartsTheProbeFromPrbWAvail", "A22 EVT_TK_DISCOVERED in PRB_W_AVAIL"),
    Mutant("acmp-grandmaster-read-twice", "acmp/acmp.c",
           "\t\tp_gptp(a, d->interface, &d->local_gm, &d->local_domain);\n\t\td->sampled = true;",
           "\t\tp_gptp(a, d->interface, &d->local_gm, &d->local_domain);\n"
           "\t\tp_gptp(a, d->interface, &d->local_gm, &d->local_domain);\n\t\td->sampled = true;",
           "acmp", "AcmpCore.A22DiscoveredStartsTheProbeFromPrbWAvail",
           "A22 the grandmaster is sampled once for the frame",
           (("acmp", "AcmpMailbox.C10C11DiscoveryPathsAreServedInThePassThatTakesTheRecord",
             "C10 ENTITY_AVAILABLE from its RX_HEAD -> TMR_DELAY armed"),)),
    # what discovery takes (A22): each term of acmp_adp_rx's guard but the interface's,
    # which no sink can match past the configuration
    Mutant("acmp-adp-short-frame-taken", "acmp/acmp.c",
           "if (interface >= a->cfg.n_interfaces || len < ACMP_ADP_FRAME_BYTES || ",
           "if (interface >= a->cfg.n_interfaces || len < ACMP_ADP_FRAME_BYTES - 1u || ",
           "acmp", "AcmpCore.A22OtherAdpFramesAreIgnored", "A22 a short ADPDU, a DISCOVER"),
    Mutant("acmp-adp-ethertype-unchecked", "acmp/acmp.c",
           "len < ACMP_ADP_FRAME_BYTES || wire_be16(frame + 12) != ACMP_ETHERTYPE ||",
           "len < ACMP_ADP_FRAME_BYTES ||",
           "acmp", "AcmpCore.A22OtherAdpFramesAreIgnored", "A22 a short ADPDU, a DISCOVER"),
    Mutant("acmp-adp-subtype-unchecked", "acmp/acmp.c",
           "\t    frame[PDU] != ACMP_ADP_SUBTYPE || AVTP_VERSION(frame) != ACMP_AVTP_VERSION ||",
           "\t    AVTP_VERSION(frame) != ACMP_AVTP_VERSION ||",
           "acmp", "AcmpCore.A22OtherAdpFramesAreIgnored", "A22 a short ADPDU, a DISCOVER"),
    Mutant("acmp-adp-discover-taken", "acmp/acmp.c",
           "(frame[O_MSG] & 0x0Fu) > ACMP_ADP_MSG_ENTITY_DEPARTING) {",
           "(frame[O_MSG] & 0x0Fu) > ACMP_ADP_MSG_ENTITY_DEPARTING + 1u) {",
           "acmp", "AcmpCore.A22OtherAdpFramesAreIgnored", "A22 a short ADPDU, a DISCOVER"),
    # every frame to the ACMP multicast address (B1, B2; IEEE 1722.1-2021 8.2.1)
    Mutant("acmp-frames-to-the-own-mac", "acmp/acmp.c", "\twire_put_be(frame, ACMP_MULTICAST_MAC, 6);",
           "\twire_put_be(frame, a->cfg.mac[interface], 6);",
           "acmp", "AcmpMailbox.B2OwnUnicastIsAToleranceAndForeignUnicastIsRefused",
           "B2 and is answered, to the multicast address",
           (("acmp", "AcmpMailbox.B1TheChannelCarriesCommandsAndResponsesInOrder",
             "B1 to the ACMP multicast address from the interface's MAC"),)),
    # the composition (U5)
    Mutant("app-acmp-before-adp", "app/ctrl_app.c", "\tctrl_loop_init(&app->loop);\n\tif (!adp_mbx_init(",
           "\tctrl_loop_init(&app->loop);\n"
           "\tif (cfg->acmp != NULL && (!acmp_mbx_init(&app->acmp, cfg->acmp, cfg->acmp_env, CTRL_APP_ACMP_FIRST_SLOT) "
           "||\n"
           "\t\t\t\t  !acmp_mbx_attach(&app->acmp, &app->loop))) {\n\t\treturn false;\n\t}\n\tif (!adp_mbx_init(",
           "acmp", "AcmpMailbox.U5AcmpComesAfterAdpAndReadsNothingBeforeTheContract",
           "B0 the app with ACMP starts on the model"),
    Mutant("app-acmp-never-composed", "app/ctrl_app.c", "\treturn cfg->acmp == NULL ||", "\treturn true ||",
           "acmp", "AcmpMailbox.U5AcmpComesAfterAdpAndReadsNothingBeforeTheContract",
           "U5 ACMP binds its channel and stands in front of ADP's handler"),
    # the binding owner on the store (N)
    Mutant("acmp-nvm-bindings-to-the-others", "acmp/acmp_nvm.c",
           "\tif (group != n->bind_group) {\n\t\treturn n->others->apply(",
           "\tif (true) {\n\t\treturn n->others->apply(",
           "acmpnvm", "AcmpStore.N1ABindSurvivesAPowerCycleAndFastConnects", "N1 the binding parameters come back"),
    Mutant("acmp-nvm-refusal-applied", "acmp/acmp_nvm.c", "== ACMP_RESTORE_APPLIED ? NVM_APPLIED : NVM_REFUSED;",
           "== ACMP_RESTORE_APPLIED ? NVM_APPLIED : NVM_APPLIED;",
           "acmpnvm", "AcmpStore.N5ARecordTheCoreRefusesKeepsItsDefault",
           "N5 a binding record of a sink the configuration lacks is refused",
           (("acmpnvm", "AcmpStore.N6TheRollBackAndEveryOtherGroup", "N6 one of another length is refused"),)),
    Mutant("acmp-nvm-d3-roll-back-kept", "acmp/acmp_nvm.c",
           "\tif (walk != NVM_W_BIND) {\n\t\treturn n->others->rollback(n->others->ctx, walk);\n\t}",
           "\tif (walk != NVM_W_BIND && false) {\n\t\treturn n->others->rollback(n->others->ctx, walk);\n\t}",
           "acmpnvm", "AcmpStore.N6TheRollBackAndEveryOtherGroup", "N6 every other group"),
    Mutant("acmp-nvm-latch-length-unchecked", "acmp/acmp_nvm.c",
           "\treturn len == ACMP_BINDING_BYTES && acmp_binding_latch(", "\treturn acmp_binding_latch(",
           "acmpnvm", "AcmpStore.N6TheRollBackAndEveryOtherGroup", "N6 a latch of another length gives nothing"),
    Mutant("acmp-nvm-bindings-latched-by-the-others", "acmp/acmp_nvm.c",
           "\tif (group != n->bind_group) {\n\t\treturn n->others->latch(",
           "\tif (true) {\n\t\treturn n->others->latch(",
           "acmpnvm", "AcmpStore.N1ABindSurvivesAPowerCycleAndFastConnects", "N1 the binding parameters come back"),
    Mutant("acmp-nvm-release-dropped", "acmp/acmp_nvm.c", "\tn->others->release(n->others->ctx);", "\t(void)n;",
           "acmpnvm", "AcmpStore.N6TheRollBackAndEveryOtherGroup", "N6 every other group"),
    Mutant("acmp-nvm-settle-dropped", "acmp/acmp_nvm.c", "\treturn n->others->settle(n->others->ctx);",
           "\t(void)n;\n\treturn NVM_APPLIED;",
           "acmpnvm", "AcmpStore.N6TheRollBackAndEveryOtherGroup", "N6 every other group"),
    Mutant("acmp-nvm-model-always-ready", "acmp/acmp_nvm.c", "\treturn n->others->model_ready(n->others->ctx);",
           "\t(void)n;\n\treturn 1;",
           "acmpnvm", "AcmpStore.N6TheRollBackAndEveryOtherGroup", "N6 the model's readiness is the other owners'"),
) + acmp_review_mutants.MUTANTS
