# SPDX-License-Identifier: CERN-OHL-W-2.0
"""One named observable must reject each planted SRP defect; compile errors do not count."""
from dataclasses import dataclass
from pathlib import Path
import shutil
from ctrl_build import CTRL, Tree, Refusal, Outcome
import fw_gtest
from srp_arms import arm_srp
def caught(test: str, needle: str, outcome: Outcome) -> bool:
    """Match the named FT failure and its complete GoogleTest diagnostic.

    FT repeats the last diagnostic line; equality diagnostics put the
    expression on earlier lines. Only that failure block may satisfy it.
    """
    if outcome.rc != 1:
        return False
    for line in outcome.log.splitlines():
        if line.strip().startswith("[FAIL] "+test+":"):
            end=outcome.log.index(line)
            start=outcome.log.rfind("Failure\n",0,end)
            diagnostic=outcome.log[start:end] if start>=0 else line
            if needle in diagnostic or needle in line:
                return True
    return False


@dataclass(frozen=True)
class Defect:
    """A source mutation and the independently named observable it must fail."""

    name: str
    test: str
    old: str
    new: str
    needle: str
    path: str = "srp/srp_mbx.c"
    suite: str = "srp_mbx.cpp"
    debug: bool = False

DEFECTS = (
    Defect(
        name='startup-vid',
        test='StartupDeclaresTalkersDomainAndVlan',
        old='{6,3,2}',
        new='{6,3,7}',
        needle='d.value',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='short-leave',
        test='LeaveAfterLeaveAllStopsAtOriginalFiveSecondDeadline',
        old='i->msrp,0,20,500,1000',
        new='i->msrp,0,20,400,1000',
        needle='Unexpected mock function call',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='asking-is-ready',
        test='RegisteredListenerSubtypeChangeRevokesPermission',
        old='v[8] == 2 || v[8] == 3',
        new='v[8] == 1 || v[8] == 2 || v[8] == 3',
        needle='adapter.ifs[0].active[0]',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='ignore-link',
        test='InterfaceStateDoesNotCross',
        old='if (i->link_seen || !event->link_up)',
        new='if (false)',
        needle='adapter.ifs[i].active[0]',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='failed-listener-ready',
        test='SinkPortUsesMatchingRegisteredTalkerAndRetainsLeaveTimer',
        old='sink->desired = 1;',
        new='sink->desired = 2;',
        needle='declared',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='ignore-peer-domain',
        test='DomainUsesPeerPriorityAndVlan',
        old='i->next_domain = *value;',
        new='i->next_domain = i->domain;',
        needle='domain.priority',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='rx-overtakes-owed',
        test='RefusedMailboxRetainsOwedFrameAndDefersInput',
        old='return m->owed_len == 0 &&',
        new='return',
        needle='adapter.received',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='rx-overtakes-expiry',
        test='ExpiryBacklogPrecedesSamePassReceive',
        old='m->loop->ticks_owed == 0 &&',
        new='true &&',
        needle='adapter.stops',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='reentry-uncounted',
        test='ReentryFromOutputIsRefusedAndCounted',
        old='++m->reentries;',
        new='(void)m;',
        needle='adapter.reentries',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='invalid-vid',
        test='InvalidBindingsAndDuplicateBindingsPreserveState',
        old='vid == 0 || vid >= 4095',
        new='vid >= 4095',
        needle='srp_mbx_bind',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='failed-init-leaks',
        test='ExhaustionDuringEachStartupStageReleasesEveryBlock',
        old='++m->refused;\n            srp_mbx_destroy(m);',
        new='++m->refused;',
        needle='ctrl_pool_in_use',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='missing-port-accepted',
        test='MissingBootDependenciesRefuseBeforeAttachment',
        old='!config->licence || !shlan_port_pool()',
        new='!shlan_port_pool()',
        needle='srp_mbx_init',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='attach-nonatomic',
        test='AttachmentFailureIsAtomicAndDetachesAfterLoopReset',
        old='loop->n_polls < CTRL_LOOP_MAX_POLLS &&',
        new='true &&',
        needle='srp_mbx_attach',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='malformed-uncounted',
        test='InvalidFramesHaveNoReservationSideEffects',
        old='++m->malformed;\n    } else',
        new='(void)m;\n    } else',
        needle='adapter.malformed',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='reset-skips-recreate',
        test='RecreateAllocationFailureIsCountedAndRetried',
        old='if (!i->msrp) {\n            // A failed recreate',
        new='if (!i->msrp) {\n            continue; // A failed recreate',
        needle='adapter.ifs[0].msrp',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='readyfailed-ignored',
        test='ReadyFailedAndUninterestingStreamsAreSeparated',
        old='v[8] == 2 || v[8] == 3',
        new='v[8] == 2',
        needle='Actual function call count',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='foreign-domain-stored',
        test='DomainFilterAndDuplicateDoNotGrowDeclarations',
        old='d->class_id == 6 &&',
        new='d->class_id > 0 &&',
        needle='ctrl_pool_in_use',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='foreign-vlan-stored',
        test='MvrpAcceptsOnlyCurrentDomainVid',
        old='if (vid == i->domain.vid)',
        new='if (vid != 0)',
        needle='ctrl_pool_in_use',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='sink-da-ignored',
        test='WireMismatchesCannotAdmitBoundSinkAndLeaveExpiresIt',
        old='memcmp(sink->dest_mac,v->dest_mac,6) == 0 &&',
        new='true &&',
        needle='declared',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='admission-ceiling-ignored',
        test='AdmissionUsesBandwidthAndEthernetMinimum',
        old='used + slope <= (uint64_t)m->config.link_rate_bps * 3u / 4u',
        new='used + slope <= (uint64_t)m->config.link_rate_bps * 1000u',
        needle='admitted[0]',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='domain-refusal-lost',
        test='DomainExhaustionPreservesOldDeclarationUntilRetry',
        old='if (mvrp_declare(i->mvrp,0,i->next_domain.vid) != 0)',
        new='if (mvrp_declare(i->mvrp,0,i->next_domain.vid) == 99)',
        needle='domain.vid',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='listener-refusal-lost',
        test='SinkDeclarationExhaustionRetriesWithoutLosingBinding',
        old='if (result == 0)',
        new='if (result != 99)',
        needle='declared',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='other-link-cancels-owed',
        test='LinkLossCancelsItsOwedFrameOnly',
        old='m->owed_len && m->owed_if == i->index',
        new='m->owed_len && m->owed_if != i->index',
        needle='adapter.owed_len',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='duplicate-tick-owner',
        test='OneLoopOwnsTheGlobalCentisecondDispatch',
        old='!m->loop && !timer_owner &&',
        new='!m->loop &&',
        needle='srp_mbx_attach',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='binding-debug-guard',
        test='SynchronousBindingFromOutputAsserts',
        old='assert(!m->busy);',
        new='(void)m;',
        needle='failed to die',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=True,
    ),
    Defect(
        name='receive-debug-guard',
        test='SynchronousReceiveFromOutputAsserts',
        old='assert(!m->busy);',
        new='(void)m;',
        needle='failed to die',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=True,
    ),
    Defect(
        name='tick-debug-guard',
        test='SynchronousTickFromOutputAsserts',
        old='assert(!m->busy);',
        new='(void)m;',
        needle='failed to die',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=True,
    ),
    Defect(
        name='licence-before-vlan',
        test='ListenerBeforeVlanCommitCannotStartTalker',
        old='link && i->vlan_sent &&',
        new='link &&',
        needle='joined',
    ),
    Defect(
        name='unbind-shared-listener',
        test='SharedBindingsRetainTheListenerAndVlanUntilTheLastUnbind',
        old='if (!has_sink(i,&old,true))',
        new='if (true)',
        needle='d.event',
    ),
    Defect(
        name='withdraw-bound-domain',
        test='BoundOldDomainVlanSurvivesDomainChange',
        old=' && !has_sink(i,&old_vlan,false)',
        new=' && (old_vlan.vid != 0)',
        needle='d.event',
    ),
    Defect(
        name='withdraw-same-domain',
        test='PriorityOnlyDomainChangeKeepsVlanMembership',
        old='i->domain.vid != i->next_domain.vid && !has_sink',
        new='i->domain.vid != 0 && !has_sink',
        needle='d.event',
    ),
    Defect(
        name='sink-vlan-refusal-lost',
        test='SinkVlanExhaustionRetriesAndDistinctMembershipsRemainIndependent',
        old='if (mvrp_declare(i->mvrp,0,s->vid) != 0)',
        new='if (mvrp_declare(i->mvrp,0,s->vid) == 99)',
        needle='vlan_requested',
    ),
    Defect(
        name='ready-before-vlan',
        test='SinkMembershipCommitsBeforeReadyAtStartup',
        old='if (r->desired != 2 || r->vlan_sent)',
        new='if (true)',
        needle='joined',
    ),
    Defect(
        name='latency-missing-startup',
        test='SrpLatency.StartupJoinPeriodicAndLeaveAllCommitWithinOneBudget',
        old='if (i->link) {',
        new='if (i->link && false) {',
        needle='commits.size()',
        suite='srp_latency.cpp',
    ),
    Defect(
        name='latency-domain-unserviced',
        test='SrpLatency.ReceiveStateMalformedDomainAndListenerPaths',
        old='i->next_domain = *value;',
        new='i->next_domain = i->domain;',
        needle='domain.vid',
        suite='srp_latency.cpp',
    ),
    Defect(
        name='latency-leave-origin',
        test='SrpLatency.OriginalLeaveDeadlineSurvivesCoalescedBacklog',
        old='i->msrp,0,20,500,1000',
        new='i->msrp,0,20,400,1000',
        needle='Unexpected mock function call',
        suite='srp_latency.cpp',
    ),
    Defect(
        name='latency-relaxed-budget',
        test='SrpLatency.FullRingRetainsOriginalOriginAndElevenMillisecondStallFails',
        old='10000000',
        new='20000000',
        needle='service_limit',
        suite='srp_latency.cpp',
        path='test/srp_latency_policy.hpp',
    ),
    Defect(
        name='walk-domain-ignored',
        test='SrpWalk.CertifiedTwoClassDomainVectorAdoptsOnlyClassA',
        old='i->next_domain = *value;',
        new='i->next_domain = i->domain;',
        needle='domain.vid',
        suite='srp_walk.cpp',
    ),
    Defect(
        name='walk-match-da-ignored',
        test='SrpWalk.StreamMatcherNearMissSwapAndImmediateWithdrawal',
        old='memcmp(sink->dest_mac,v->dest_mac,6) == 0 &&',
        new='true &&',
        needle='declared',
        suite='srp_walk.cpp',
    ),
    Defect(
        name='walk-leave-shortened',
        test='SrpWalk.RunBLeaveAllLanesPreserveTheRedeclaredListener',
        old='i->msrp,0,20,500,1000',
        new='i->msrp,0,20,400,1000',
        needle='Unexpected mock function call',
        suite='srp_walk.cpp',
    ),
    Defect(
        name='walk-startup-is-join',
        test='SrpWalk.ProcessorApplicantTransmitAndReceivedRowsAgreeOnTheWire',
        old='&value,true) != 0',
        new='&value,false) != 0',
        needle='d.event',
        suite='srp_walk.cpp',
    ),
    Defect(
        name='walk-malformed-uncounted',
        test='SrpWalk.PerInterfaceWireIdentityAndUnknownOrTruncatedInput',
        old='++m->malformed;\n    } else',
        new='(void)m;\n    } else',
        needle='adapter.malformed',
        suite='srp_walk.cpp',
    ),
    Defect(
        name='shape-last-output-missing',
        test='EveryGeneratedOutputIsDeclaredAndEverySinkFits',
        old='unsigned n = 0; n < CTRL_SRP_SOURCES; ++n) {\n        struct msrp_talker_failed',
        new='unsigned n = 0; n + 1 < CTRL_SRP_SOURCES; ++n) {\n        struct msrp_talker_failed',
        needle='outputs',
        suite='srp_shape.cpp',
    ),
    Defect('tag-overhead-omitted','AdmissionStraddlesTheExactEthernetCeiling',
           '+ 22u','+ 18u','admitted[0]'),
    Defect('preamble-ifg-omitted','AdmissionStraddlesTheExactEthernetCeiling',
           '(size + 20u)','(size + 0u)','admitted[0]'),
    Defect('ninety-percent-ceiling','AdmissionStraddlesTheExactEthernetCeiling',
           '* 3u / 4u','* 9u / 10u','admitted[0]'),
    Defect('readyfailed-callback-stop','ReadyToReadyFailedNeverGlitchesAnActiveLicence',
           'declaration == MSRP_LISTENER_DECL_READY_FAILED','false','mock function call'),
    Defect('short-link-interruption-ignored','AdjacentLinkEdgesResetDomainAndAllPriorRegistrations',
           'if (i->link_seen || !event->link_up)','if (!mbx_link_up(i->index))','domain.priority'),
    Defect('old-prefix-accepted','LinkEventsDiscardOnlyTheirPublishedReceivePrefix',
           'i->discard_prefix && mbx_rx_before(MBX_CH_SRP,i->rx_mark)',
           'false','mock function call'),
    Defect('shared-identity-overwritten','SharedIdentityReconcilesBothBindingOrdersOnTheWire',
           'desired |= r->desired;','desired = r->desired;','last'),
    Defect('event-reentry-unguarded','EventReentryAndSinkCapacityAreGuarded',
           'static void on_event(void *ctx, const struct mbx_event *event)\n{\n'
           '    struct srp_mbx *m = ctx;\n    if (!enter(m))',
           'static void on_event(void *ctx, const struct mbx_event *event)\n{\n'
           '    struct srp_mbx *m = ctx;\n    if (false)',
           'adapter.reentries'),

    Defect('failed-interface-starves-peer','RecreateAllocationFailureIsCountedAndRetried',
           'if (!i->msrp) {\n            m->cursor = (slot + 1u) % (2u * MBX_N_IF);',
           'if (!i->msrp) {','other_sent'),
    Defect('backlogged-old-prefix-accepted','OldReceiveBacklogCannotRegisterAcrossLinkRestart',
           'i->discard_prefix && mbx_rx_before(MBX_CH_SRP,i->rx_mark)',
           'false','mock function call'),
    Defect('link-level-loss-ignored','LinkLevelLossAndFirstDownEventAreFailClosed',
           'if (i->link != link)', 'if (!i->link && link)', 'adapter.ifs[0].active[0]'),
    Defect('reset-leaks-owned-participants','ExhaustedPoolStillReusesOwnedBlocksOnLinkReset',
           'msrp_app_destroy(i->msrp); mvrp_app_destroy(i->mvrp);\n'
           '    i->msrp = NULL; i->mvrp = NULL; i->domain_owed = false;',
           'i->msrp = NULL; i->mvrp = NULL; i->domain_owed = false;', 'adapter.refused'),
    Defect('downlink-receive-accepted','OldReceiveBacklogCannotRegisterAcrossLinkRestart',
           '!i->link || (i->discard_prefix', 'false || (i->discard_prefix',
           'adapter.ifs[i].registered[0]'),
    Defect('delayed-in-listener','InListenerWithdrawalRevokesLicenceImmediately',
           '// These valid constants',
           '((struct mrp_app_ops *)i->msrp->ops)->milan_rapid_leave = false;\n    // These valid constants',
           'adapter.ifs[i].active[0]'),
    Defect('delayed-in-talker','InTalkerWithdrawalImmediatelyWithdrawsListener',
           '// These valid constants',
           '((struct mrp_app_ops *)i->msrp->ops)->milan_rapid_leave = false;\n    // These valid constants',
           'declared'),
    Defect('attach-ignores-current-link','ReattachLearnsAnAlreadyUpLinkWithoutAnotherRecord',
           'm->ifs[n].link = mbx_link_up(n);', 'm->ifs[n].link = false;', 'adapter.ifs[i].link'),
    Defect('cancelled-link-never-recovers','CancelledLinkRecordRecoversFromLevelAndFencesOldReceive',
           'if (i->link != link)', 'if (i->link && !link)', 'adapter.ifs[i].link'),
    Defect('rebind-loses-shared-applicant','SharedRebindKeepsOnlyTheRemainingEligibleRequest',
           'replacement.declared |= r->declared;', '(void)r;', 'left'),
    Defect('consecutive-rebind-loses-applicant','ConsecutiveSharedReplacementsKeepApplicantStateUntilReconciliation',
           'replacement.declared |= r->declared;', '(void)r;', 'left'),
    Defect('joining-binding-loses-applicant','JoiningIneligibleBindingWithdrawsReadyWhenOriginalLeaves',
           'replacement.declared |= r->declared;',
           'if (r == s) { replacement.declared |= r->declared; }', 'd.event'),
    Defect('applicant-inherited-across-streams','ReboundStreamCannotInheritAnotherStreamsReady',
           'if (memcmp(r->stream_id.bytes,identity->bytes,8) == 0)',
           'if (true)', 'ready'),
    Defect('final-unbind-withdraws-domain-vid','FinalDomainVidUnbindKeepsSrClassMembership',
           'if (old.vid != i->domain.vid && !has_sink(i,&old,false))',
           'if (!has_sink(i,&old,false))', 'd.event'),
    Defect('last-ineligible-vid-leaks','LastNeverEligibleBindingWithdrawsTheSharedVidInEitherOrder',
           'if (old.vid != i->domain.vid &&', 'if (old.vlan_requested && old.vid != i->domain.vid &&', 'vlan_left'),
    Defect('reset-keeps-owed-domain','RefusedPeerDomainDoesNotSurviveLinkRestart',
           'i->msrp = NULL; i->mvrp = NULL; i->domain_owed = false;',
           'i->msrp = NULL; i->mvrp = NULL;', 'domain.vid'),
    Defect('reset-keeps-sink-vlan','SinkVlanRedeclaredBeforeReadyAfterLinkRestart',
           'i->sinks[k].vlan_requested = false; i->sinks[k].vlan_sent = false;',
           '(void)k;', 'vlan'),
    Defect('shared-ready-uses-first-vlan','SharedReadyWaitsForTheMatchingBindingsOwnVlan',
           'if (r->desired != 2 || r->vlan_sent)',
           'if (r->desired != 2 || s->vlan_sent)', 'vlan'),
    Defect('milan-rapid-leave-leaks-to-mvrp','MilanMsrpOptionLeavesMvrpOnTheOriginalLeaveDeadline',
           '// These valid constants',
           '((struct mrp_app_ops *)i->mvrp->ops)->milan_rapid_leave = true;\n    // These valid constants',
           'registered()'),

    Defect('receive-retry-removed','SrpRetry.RefusedMixedPayloadRetriesWithoutPeerRetransmission',
           'if (apply_receive(m,&m->pending_rx))', 'if (false)', 'adapter.received',
           suite='srp_rx_retry.cpp'),
    Defect('partial-receive-retry-removed','SrpRetry.PartialPayloadKeepsLaterAttributesAndDoesNotRepeatStop',
           'if (apply_receive(m,&m->pending_rx))', 'if (false)', 'domain.vid',
           suite='srp_rx_retry.cpp'),
    Defect('receive-record-lost','SrpRetry.RefusedMixedPayloadRetriesWithoutPeerRetransmission',
           'm->pending_rx = *frame;', '(void)frame;', 'adapter.pending_rx.len',
           suite='srp_rx_retry.cpp'),
    Defect('receive-refusal-malformed','SrpRetry.RefusedMixedPayloadRetriesWithoutPeerRetransmission',
           'if (result == -SHLAN_ERROR_NO_MEMORY) {',
           'if (result == -SHLAN_ERROR_NO_MEMORY) { ++m->malformed;', 'adapter.malformed',
           suite='srp_rx_retry.cpp'),
    Defect('receive-overtakes-retained','SrpRetry.LaterRecordsCannotOvertakeRetainedInterface',
           'return m->pending_rx.len == 0 && rx_order_ready(m);',
           'return rx_order_ready(m);', 'loop.stats.rx_records', suite='srp_rx_retry.cpp'),
    Defect('reset-keeps-retained-receive','SrpRetry.LinkResetCancelsRetainedPayloadAndFencesLaterOldRecords',
           'm->pending_rx.len && m->pending_rx.interface == i->index', 'false',
           'adapter.received', suite='srp_rx_retry.cpp'),
    Defect('peer-reset-cancels-retained-receive','SrpRetry.OtherInterfaceResetPreservesRetainedPayload',
           'm->pending_rx.len && m->pending_rx.interface == i->index', 'm->pending_rx.len',
           'adapter.pending_rx.len', suite='srp_rx_retry.cpp'),
    Defect('destroy-keeps-retained-receive','SrpRetry.DestroyCancelsRetainedPayloadBeforeReinitialization',
           'm->pending_rx.len = 0;\n    m->initialized = false;',
           'm->initialized = false;', 'adapter.pending_rx.len', suite='srp_rx_retry.cpp'),
    Defect('bind-overtakes-retained-receive','SrpRetry.RefusedMixedPayloadRetriesWithoutPeerRetransmission',
           ' || m->pending_rx.len)', ')', 'srp_mbx_bind', suite='srp_rx_retry.cpp'),
    Defect('composition-attach-omitted','SrpApp.AllThreeProtocolsShareTheLoopAndWakeSources',
           '!srp_mbx_attach(srp,&app->loop)', '!(srp != NULL)', 'app.loop.n_ticks',
           path='app/ctrl_app_srp.c',suite='srp_app.cpp'),
    Defect('composition-srp-irq-omitted','SrpApp.AllThreeProtocolsShareTheLoopAndWakeSources',
           'mbx_place(channels,MBX_IRQ_ENABLE_RX_LSB',
           'mbx_place(channels & ~(1u << MBX_CH_SRP),MBX_IRQ_ENABLE_RX_LSB', 'model.irq_enable',
           path='app/ctrl_app_srp.c',suite='srp_app.cpp'),
    Defect('composition-srp-tick-omitted','SrpApp.AllThreeProtocolsShareTheLoopAndWakeSources',
           'mbx_tick_enable(true);', 'mbx_tick_enable(false);', 'app.loop.stats.ticks',
           path='app/ctrl_app_srp.c',suite='srp_app.cpp'),

    Defect('recreated-receive-retry-removed','SrpRetry.FailedParticipantRecreationRetainsFreshReceive',
           'if (apply_receive(m,&m->pending_rx))', 'if (false)', 'adapter.received',
           suite='srp_rx_retry.cpp'),
    Defect('mvrp-receive-retry-removed','SrpRetry.RetainedMvrpUsesItsOriginalParticipant',
           'if (apply_receive(m,&m->pending_rx))', 'if (false)', 'adapter.received',
           suite='srp_rx_retry.cpp'),
    Defect('receive-retry-passes-owed','SrpRetry.RetainedReceiveWaitsForOwedTransmit',
           'm->pending_rx.interface == n && rx_order_ready(m)', 'm->pending_rx.interface == n',
           'adapter.pending_rx.len', suite='srp_rx_retry.cpp'),
    Defect('receive-retry-passes-backlog','SrpRetry.RetainedReceiveWaitsForTickAndLifecycleBacklogs',
           'm->pending_rx.interface == n && rx_order_ready(m)', 'm->pending_rx.interface == n',
           'adapter.received', suite='srp_rx_retry.cpp'),
    Defect('future-receive-refused','SrpRetry.WholeInvalidPduIsMalformedAndFutureUnknownMessageIsSkipped',
           'frame->len - 14u) :', '(frame->bytes[14] ? 0u : frame->len - 14u)) :',
           'adapter.ifs[0].active[0]', suite='srp_rx_retry.cpp'),
    Defect('invalid-suffix-uncounted','SrpRetry.WholeInvalidPduIsMalformedAndFutureUnknownMessageIsSkipped',
           '++m->malformed;\n    } else', '(void)m;\n    } else',
           'adapter.malformed', suite='srp_rx_retry.cpp'),
    Defect('composition-refusal-ignored','SrpApp.AttachRefusalPreservesExistingComposition',
           '!srp_mbx_attach(srp,&app->loop)', '!(srp != NULL)', 'ctrl_app_attach_srp',
           path='app/ctrl_app_srp.c',suite='srp_app.cpp'),
    Defect('recovery-latency-retry-removed','SrpLatency.ReceiveRecoveryKeepsOriginalArrivalBudget',
           'if (apply_receive(m,&m->pending_rx))', 'if (false)', 'adapter.ifs[0].active[0]',
           suite='srp_latency.cpp'),

    Defect('receive-retention-unbounded','SrpRetry.OversizedValidRecordExpiresOnceAndReleasesOtherInterfaceAndBinding',
           '>= SRP_RX_RETRY_MS', '>= UINT32_MAX', 'adapter.pending_rx.len', suite='srp_rx_retry.cpp'),
    Defect('receive-retention-short','SrpRetry.OversizedValidRecordExpiresOnceAndReleasesOtherInterfaceAndBinding',
           '#define SRP_RX_RETRY_MS 1000u', '#define SRP_RX_RETRY_MS 999u',
           'adapter.rx_discarded', suite='srp_rx_retry.cpp'),
    Defect('receive-retention-late','SrpRetry.OversizedValidRecordExpiresOnceAndReleasesOtherInterfaceAndBinding',
           '>= SRP_RX_RETRY_MS', '> SRP_RX_RETRY_MS', 'adapter.rx_discarded', suite='srp_rx_retry.cpp'),
    Defect('receive-discard-uncounted','SrpRetry.OversizedValidRecordExpiresOnceAndReleasesOtherInterfaceAndBinding',
           '++m->rx_discarded;', '(void)m;', 'adapter.rx_discarded', suite='srp_rx_retry.cpp'),
    Defect('receive-discard-malformed','SrpRetry.OversizedValidRecordExpiresOnceAndReleasesOtherInterfaceAndBinding',
           '++m->rx_discarded;', '++m->rx_discarded; ++m->malformed;',
           'adapter.malformed', suite='srp_rx_retry.cpp'),
    Defect('receive-discard-as-success','SrpRetry.OversizedValidRecordExpiresOnceAndReleasesOtherInterfaceAndBinding',
           '++m->rx_discarded;', '++m->rx_discarded; ++m->received;',
           'adapter.received', suite='srp_rx_retry.cpp'),
    Defect('receive-queue-renews-deadline','SrpRetry.QueuedRefusalKeepsOriginalArrivalDeadlineAcrossClockWrap',
           'm->pending_rx = *frame;', 'm->pending_rx = *frame; m->pending_rx.arrival_ms = mbx_now_ms();',
           'adapter.rx_discarded', suite='srp_rx_retry.cpp'),
    Defect('receive-first-refusal-never-expires','SrpRetry.QueuedRefusalKeepsOriginalArrivalDeadlineAcrossClockWrap',
           'm->pending_rx = *frame;\n        expire_receive(m);', 'm->pending_rx = *frame;',
           'adapter.rx_discarded', suite='srp_rx_retry.cpp'),
    Defect('receive-expiry-precedes-recovery','SrpRetry.RecoveryAtDeadlineStillAppliesTheCompleteRecord',
           'if (apply_receive(m,&m->pending_rx))',
           'expire_receive(m);\n            if (m->pending_rx.len && apply_receive(m,&m->pending_rx))',
           'adapter.received', suite='srp_rx_retry.cpp'),
    Defect('receive-recreate-never-expires','SrpRetry.FailedRecreationCannotRetainInputBeyondItsDeadline',
           'if (m->pending_rx.interface == n)', 'if (false)',
           'adapter.rx_discarded', suite='srp_rx_retry.cpp'),
    Defect('receive-flood-unbounded','SrpRetry.DomainFloodCannotDelayLaterRapidLeave',
           '>= SRP_RX_RETRY_MS', '>= UINT32_MAX', 'adapter.pending_rx.len', suite='srp_rx_retry.cpp'),

    Defect('receive-deadline-not-modular','SrpRetry.RetainedDeadlineCrossesClockWrapWithoutEarlyDiscard',
           '(uint32_t)(mbx_now_ms() - m->pending_rx.arrival_ms) >= SRP_RX_RETRY_MS',
           'mbx_now_ms() >= m->pending_rx.arrival_ms + SRP_RX_RETRY_MS',
           'adapter.rx_discarded', suite='srp_rx_retry.cpp'),

    Defect('four-way-srp-irq-missing',
           'AcmpMailbox.U6AdpAcmpAndMaapShareTheLoopOnDisjointSlotsWithEveryChannelOpen',
           'mbx_place(channels,MBX_IRQ_ENABLE_RX_LSB,MBX_IRQ_ENABLE_RX_WIDTH)',
           'mbx_place(channels & ~(1u << MBX_CH_SRP),MBX_IRQ_ENABLE_RX_LSB,MBX_IRQ_ENABLE_RX_WIDTH)',
           'U6 exact four-channel receive and event interrupt mask',
           path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('four-way-srp-wake-missing',
           'AcmpMailbox.U6AdpAcmpAndMaapShareTheLoopOnDisjointSlotsWithEveryChannelOpen',
           'mbx_place(channels,MBX_IRQ_ENABLE_RX_LSB,MBX_IRQ_ENABLE_RX_WIDTH)',
           'mbx_place(channels & ~(1u << MBX_CH_SRP),MBX_IRQ_ENABLE_RX_LSB,MBX_IRQ_ENABLE_RX_WIDTH)',
           'U6 idle loop wakes for SRP alone',
           path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('four-way-acmp-enable-lost',
           'AcmpMailbox.U6AdpAcmpAndMaapShareTheLoopOnDisjointSlotsWithEveryChannelOpen',
           'channels |= 1u << MBX_CH_ACMP;', 'channels |= 0u;',
           'U6 four receive channels and no others', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('four-way-unbound-irq-enabled',
           'AcmpMailbox.U6AdpAcmpAndMaapShareTheLoopOnDisjointSlotsWithEveryChannelOpen',
           'mbx_place(channels,MBX_IRQ_ENABLE_RX_LSB,MBX_IRQ_ENABLE_RX_WIDTH)',
           'mbx_place(channels | (1u << MBX_CH_AECP),MBX_IRQ_ENABLE_RX_LSB,MBX_IRQ_ENABLE_RX_WIDTH)',
           'U6 exact four-channel receive and event interrupt mask',
           path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('four-way-bound-drops-srp',
           'AcmpMailbox.F6WithMaapComposedEveryPassStaysWithinTheThreeWayBound',
           '#define CTRL_APP_PASS_MAX (CTRL_APP_THREE_PASS_MAX + SRP_MBX_PASS_MAX -',
           '#define CTRL_APP_PASS_MAX (CTRL_APP_THREE_PASS_MAX + 0u -',
           'F6 four modules count each shared event record once', path='app/ctrl_app.h', suite='test_acmp_mbx.cpp'),
    Defect('four-way-bound-duplicates-events',
           'AcmpMailbox.F6WithMaapComposedEveryPassStaysWithinTheThreeWayBound',
           '#define CTRL_APP_PASS_MAX (CTRL_APP_THREE_PASS_MAX + SRP_MBX_PASS_MAX -',
           '#define CTRL_APP_PASS_MAX (CTRL_APP_THREE_PASS_MAX + SRP_MBX_PASS_MAX +',
           'F6 four modules count each shared event record once', path='app/ctrl_app.h', suite='test_acmp_mbx.cpp'),

    Defect('binding-delivery-missing','SrpBinding.BindIsDeferredAndKeepsEverySinkAndInterface',
           'r->pending = true;', 'r->pending = false;', 'binding delivered',
           path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('binding-synchronous','SrpBinding.BindIsDeferredAndKeepsEverySinkAndInterface',
           'r->pending = true;', 'r->pending = true; (void)deliver(app);',
           'callback only queues the binding', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('binding-poll-adds-access','SrpBinding.BindIsDeferredAndKeepsEverySinkAndInterface',
           'bool pending = false;', 'bool pending = false; (void)mbx_irq_status();',
           'binding poll makes no mailbox access', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('binding-interface-lost','SrpBinding.BindIsDeferredAndKeepsEverySinkAndInterface',
           'app->srp,interface,sink,r->bound',
           'app->srp,interface + 1u,sink,r->bound',
           'binding delivered', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('binding-sink-lost','SrpBinding.BindIsDeferredAndKeepsEverySinkAndInterface',
           'app->srp,interface,sink,r->bound', 'app->srp,interface,0u,r->bound',
           'binding delivered', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('binding-refusal-dropped','SrpBinding.RefusedReceiveRetriesAfterRecoveryOrExpiry',
           'pending = r->pending || pending;', 'r->pending = false; pending = r->pending || pending;',
           'binding delivered', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('binding-owed-retry-dropped','SrpBinding.OwedTransmissionRetriesAfterCommit',
           'pending = r->pending || pending;', 'r->pending = false; pending = r->pending || pending;',
           'binding delivered', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('binding-unbind-lost','SrpBinding.UnbindCancelsPendingAndWithdrawsAcceptedBinding',
           'r->bound = stream != NULL;', 'if (!stream) { return; }\n    r->bound = true;',
           'unbind supersedes pending bind', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('binding-replacement-lost','SrpBinding.ReplacementSupersedesPendingIdentity',
           'if (stream) {', 'if (stream && !r->pending) {',
           'stream identity delivered', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('binding-pending-sleeps','SrpBinding.RefusedReceiveRetriesAfterRecoveryOrExpiry',
           'return pending;', 'return false;', 'pending binding keeps service awake',
           path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('binding-count-overflow','SrpBinding.AttachmentRefusesMissingRoomAndShapeWithoutPartialBinding',
           'app->acmp.acmp.cfg.n_sinks > CTRL_SRP_SINKS', 'false',
           'ctrl_app_attach_srp', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('binding-poll-overflow','SrpBinding.AttachmentRefusesMissingRoomAndShapeWithoutPartialBinding',
           'app->loop.n_polls + 2u > CTRL_LOOP_MAX_POLLS', 'false',
           'ctrl_app_attach_srp', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('binding-reattach-recurses','SrpBinding.AttachmentRefusesMissingRoomAndShapeWithoutPartialBinding',
           'app->acmp.acmp.env == &app->acmp_delivery ||', '',
           'recompose before replacing the attached adapter', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('srp-bound-event','EventReceiveAndTransmitPollFitTheirMeasuredBounds',
           'SRP_MBX_EVENT_MAX 1u', 'SRP_MBX_EVENT_MAX 0u', 'SRP event bound',
           path='srp/srp_bounds.h', suite='srp_app.cpp'),
    Defect('srp-bound-receive','EventReceiveAndTransmitPollFitTheirMeasuredBounds',
           'SRP_MBX_RX_MAX 2u', 'SRP_MBX_RX_MAX 1u', 'SRP refused receive bound',
           path='srp/srp_bounds.h', suite='srp_app.cpp'),
    Defect('srp-bound-poll-transmit','EventReceiveAndTransmitPollFitTheirMeasuredBounds',
           '(MBX_N_IF * (4u + 2u * SRP_MBX_TX_MAX))',
           '(MBX_N_IF * (4u + 0u * SRP_MBX_TX_MAX))', 'SRP transmitting poll bound',
           path='srp/srp_bounds.h', suite='srp_app.cpp'),
    Defect('srp-bound-poll','EventReceiveAndTransmitPollFitTheirMeasuredBounds',
           '(MBX_N_IF * (4u + 2u * SRP_MBX_TX_MAX))', '0u', 'SRP retained receive poll bound',
           path='srp/srp_bounds.h', suite='srp_app.cpp'),
    Defect('srp-bound-tx-record','EventReceiveAndTransmitPollFitTheirMeasuredBounds',
           'SRP_MBX_TX_MAX (2u +', 'SRP_MBX_TX_MAX (1u +', 'SRP maximum TX record bound',
           path='srp/srp_bounds.h', suite='srp_app.cpp'),
    Defect('srp-bound-rx-record','EventReceiveAndTransmitPollFitTheirMeasuredBounds',
           'SRP_MBX_RX_RECORD_MAX (2u +', 'SRP_MBX_RX_RECORD_MAX (1u +', 'SRP maximum RX record bound',
           path='srp/srp_bounds.h', suite='srp_app.cpp'),
    Defect('srp-bound-pass','EventReceiveAndTransmitPollFitTheirMeasuredBounds',
           'CTRL_LOOP_RX_PER_PASS * (SRP_MBX_RX_RECORD_MAX + SRP_MBX_RX_MAX) + SRP_MBX_POLL_MAX)',
           '0u)', 'SRP complete pass bound',
           path='srp/srp_bounds.h', suite='srp_app.cpp'),

    Defect('feedback-advertise-missing','SrpBinding.AdvertiseFeedbackIsDeferredAndSurvivesNoTalkerDeadline',
           'if (registered && state == ACMP_SETTLED_NO_RSV)',
           'if (false)',
           'Advertise reaches ACMP', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('feedback-failed-as-advertise','SrpBinding.FailedRegistrationReachesAcmpAndWithdrawalReprobes',
           'acmp_tk_registered(&app->acmp.acmp,sink,registered == 1u)',
           'acmp_tk_registered(&app->acmp.acmp,sink,false)',
           'Failed flag reaches ACMP', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('feedback-withdrawal-missing','SrpBinding.FailedRegistrationReachesAcmpAndWithdrawalReprobes',
           'if (s->withdrawn)',
           'if (false)',
           'withdrawal reaches ACMP', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('feedback-sink-crossed','SrpBinding.RegistrationKeepsSinkAndInterfaceIdentity',
           'uint8_t registered = s->feedback_kind;',
           'uint8_t registered = app->srp->ifs[interface].sinks[0].feedback_kind;',
           'feedback keeps sink identity', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('feedback-interface-suppressed','SrpBinding.RegistrationKeepsSinkAndInterfaceIdentity',
           'if (registered && state == ACMP_SETTLED_NO_RSV)',
           'if (interface != 0u && registered && state == ACMP_SETTLED_NO_RSV)',
           'feedback uses configured interface', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('feedback-repeated','SrpBinding.AdvertiseFeedbackIsDeferredAndSurvivesNoTalkerDeadline',
           'if (registered && state == ACMP_SETTLED_NO_RSV)',
           'if (registered)',
           'unchanged registration is delivered once', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('binding-park-keeps-old','SrpBinding.ParkedReplacementRetiresThePreviouslyAcceptedBinding',
           'r->pending = app->srp->ifs[interface].sinks[sink].bound &&',
           'r->pending = false &&',
           'parking retires the old accepted binding', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('binding-invalid-retries','SrpBinding.PermanentRefusalParksAndDoesNotBlockAnotherSink',
           'if (r->parked)',
           'if (false)',
           'permanent refusal allows sleep', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('binding-invalid-upper-bound','SrpBinding.PermanentRefusalParksAndDoesNotBlockAnotherSink',
           'r->stream.vlan_id >= 4095',
           'r->stream.vlan_id > 4095',
           'permanent refusal is visible', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('binding-park-never-clears','SrpBinding.PermanentRefusalParksAndDoesNotBlockAnotherSink',
           'r->parked = r->bound && (r->stream.vlan_id == 0 || r->stream.vlan_id >= 4095);',
           'r->parked = r->parked || (r->bound && (r->stream.vlan_id == 0 || r->stream.vlan_id >= 4095));',
           'replacement clears parking', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('srp-term-fixed','Srp.PollTermsAreMeasuredSeparatelyThroughRealCallbacks',
           '(MBX_N_IF * (4u + 2u * SRP_MBX_TX_MAX))',
           '(MBX_N_IF * (0u + 2u * SRP_MBX_TX_MAX))',
           'poll fixed term is funded independently', path='srp/srp_bounds.h', suite='srp_app.cpp'),
    Defect('srp-term-transmit-count','Srp.PollTermsAreMeasuredSeparatelyThroughRealCallbacks',
           '(MBX_N_IF * (4u + 2u * SRP_MBX_TX_MAX))',
           '(MBX_N_IF * (4u + 1u * SRP_MBX_TX_MAX))',
           'poll transmit count is funded independently', path='srp/srp_bounds.h', suite='srp_app.cpp'),
    Defect('srp-term-interface-count','Srp.PollTermsAreMeasuredSeparatelyThroughRealCallbacks',
           '(MBX_N_IF * (4u + 2u * SRP_MBX_TX_MAX))',
           '((MBX_N_IF - 1u) * (4u + 2u * SRP_MBX_TX_MAX))',
           'poll fixed term is funded independently', path='srp/srp_bounds.h', suite='srp_app.cpp'),
    Defect('srp-term-send-cost','Srp.PollTermsAreMeasuredSeparatelyThroughRealCallbacks',
           'SRP_MBX_TX_MAX (2u +',
           'SRP_MBX_TX_MAX (1u +',
           'real send callback maximum', path='srp/srp_bounds.h', suite='srp_app.cpp'),
    Defect('srp-term-event-record','Srp.PassFundsEveryEventRecordAndBothMaximumReceives',
           'CTRL_LOOP_EVENTS_PER_PASS * (MBX_EV_WORDS + 2u + SRP_MBX_EVENT_MAX)',
           'CTRL_LOOP_EVENTS_PER_PASS * (SRP_MBX_EVENT_MAX)',
           'pass event records are funded independently', path='srp/srp_bounds.h', suite='srp_app.cpp'),
    Defect('srp-term-rx-count','Srp.PassFundsEveryEventRecordAndBothMaximumReceives',
           'CTRL_LOOP_RX_PER_PASS * (SRP_MBX_RX_RECORD_MAX',
           '1u * (SRP_MBX_RX_RECORD_MAX',
           'pass receive count is funded independently', path='srp/srp_bounds.h', suite='srp_app.cpp'),
    Defect('srp-term-pass-poll','Srp.PassFundsEveryEventRecordAndBothMaximumReceives',
           'SRP_MBX_RX_MAX) + SRP_MBX_POLL_MAX)',
           'SRP_MBX_RX_MAX) + SRP_MBX_POLL_MAX / 2u)',
           'pass funds the independently measured poll envelope', path='srp/srp_bounds.h', suite='srp_app.cpp'),
    Defect('srp-poll-extra-read','Srp.PollTermsAreMeasuredSeparatelyThroughRealCallbacks',
           '        bool link = mbx_link_up(n);\n',
           '        bool link = mbx_link_up(n);\n        (void)mbx_irq_status();\n',
           'one link read per interface', path='srp/srp_mbx.c', suite='srp_app.cpp'),
    Defect('srp-send-extra-read','Srp.PollTermsAreMeasuredSeparatelyThroughRealCallbacks',
           '    if (mbx_tx_send(MBX_CH_SRP,m->owed_if,m->owed_frame,m->owed_len) != MBX_STATUS_OK) {',
           '    (void)mbx_irq_status();\n'
           '    if (mbx_tx_send(MBX_CH_SRP,m->owed_if,m->owed_frame,m->owed_len) != MBX_STATUS_OK) {',
           'real send callback has only the TX record accesses', path='srp/srp_mbx.c', suite='srp_app.cpp'),

    Defect('feedback-kind-failed-lost','SrpFeedback.AdvertiseToFailedUpdatesTheSettledWireView',
           'acmp_tk_kind_changed(&app->acmp.acmp,sink,registered == 1u);',
           'acmp_tk_kind_changed(&app->acmp.acmp,sink,false);',
           'current kind reaches ACMP', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('feedback-kind-advertise-lost','SrpFeedback.FailedToAdvertiseUpdatesTheSettledWireView',
           'acmp_tk_kind_changed(&app->acmp.acmp,sink,registered == 1u);',
           'acmp_tk_kind_changed(&app->acmp.acmp,sink,true);',
           'current kind reaches ACMP', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('feedback-withdrawal-overwritten','SrpFeedback.WithdrawalThenRegistrationRetainsTheFirstEvent',
           'if (!s->withdrawn && s->desired) {',
           'if (s->desired) { s->withdrawn = false;',
           'retained withdrawal reprobes', suite='test_acmp_mbx.cpp'),
    Defect('feedback-intrapdu-lost','SrpFeedback.SinglePduWithdrawalThenRegistrationRetainsTheFirstEvent',
           '    snapshot(i);\n    if (type == MSRP_ATTR_TYPE_DOMAIN)',
           '    if (type == MSRP_ATTR_TYPE_DOMAIN)',
           'retained withdrawal reprobes', suite='test_acmp_mbx.cpp'),
    Defect('feedback-expiry-lost','SrpFeedback.ExpiryThenRegistrationRetainsTheFirstEvent',
           '        s->withdrawn = true;', '        s->withdrawn = false;',
           'expiry retained before receive', suite='test_acmp_mbx.cpp'),
    Defect('feedback-first-registration-lost','SrpFeedback.FirstRegistrationThenWithdrawalIsDeliveredInOrder',
           'uint8_t registered = s->feedback_kind;', 'uint8_t registered = s->desired;',
           'retained withdrawal reprobes', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('feedback-kind-order-lost','SrpFeedback.KindThenWithdrawalIsDeliveredInOrder',
           'acmp_tk_kind_changed(&app->acmp.acmp,sink,registered == 1u);',
           '(void)registered;', 'kind precedes withdrawal', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('feedback-supersession-lost','SrpFeedback.WithdrawalIsIsolatedAndSupersededEvenForAnIdenticalStream',
           '                s->withdrawn = false;\n            }', '            }',
           'kind preserves settled state', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('feedback-withdrawal-sink-crossed','SrpFeedback.WithdrawalIsIsolatedAndSupersededEvenForAnIdenticalStream',
           'if (s->withdrawn)',
           'if (app->srp->ifs[interface].sinks[1u - sink].withdrawn)',
           'retained withdrawal reprobes', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('r10-feedback-ignores-pending','SrpFeedback.ReplacementAwaitingDeliveryGetsNoOldRegistration',
           'if (!r->pending && r->bound) {', 'if (r->bound) {',
           'old registration cannot settle replacement', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('r10-transient-refusal-forgotten','SrpFeedback.EarlierSinkTransientRefusalKeepsDeliveryAwake',
           'pending = r->pending || pending;', 'pending = r->pending;',
           'earlier refusal keeps delivery awake', path='app/ctrl_app_srp.c', suite='test_acmp_mbx.cpp'),
    Defect('r10-feedback-allowance-quarter','SrpFeedback.DiscoveredWithdrawalMeasuresTheFundedPath',
           '(ACMP_MAX_SINKS * 6u)', '(ACMP_MAX_SINKS * 1u)',
           'measured feedback per sink allowance', path='app/ctrl_app.h', suite='test_acmp_mbx.cpp'),
    Defect('r10-feedback-allowance-eight','SrpFeedback.DiscoveredWithdrawalMeasuresTheFundedPath',
           '(ACMP_MAX_SINKS * 6u)', '(8u)',
           'measured feedback per sink allowance', path='app/ctrl_app.h', suite='test_acmp_mbx.cpp'),

)

def campaign(root: Path, lwsrp: Path, jobs: int = 4, interfaces: int = 2) -> bool:
    """Run every mutation in a reusable isolated checkout; true means a failure."""
    build=fw_gtest.Build(jobs=jobs)
    failed=False
    root.mkdir(parents=True,exist_ok=True)
    for d in DEFECTS:
        out=root/"work"
        src=out/"ctrl"
        shutil.copytree(CTRL,src,dirs_exist_ok=True,ignore=shutil.ignore_patterns("__pycache__","*.pyc"))
        target=src/d.path
        source=target.read_text()
        if source.count(d.old)!=1:
            raise Refusal(f"SRP defect {d.name} has {source.count(d.old)} planting sites")
        target.write_text(source.replace(d.old,d.new))
        selected=d.test if "." in d.test else "Srp."+d.test
        try:
            result=arm_srp(Tree(src,out/"build",out/"reuse",build),lwsrp,interfaces,
                           debug=d.debug,test=(d.suite, selected))
            ok=caught(selected,d.needle,result)
            (root/(d.name+".log")).write_text(result.log)
            print(f"[{'ok' if ok else 'ESCAPED'}] {d.name}: {d.test} / {d.needle}",flush=True)
            if not ok: print(result.log,flush=True)
        except Refusal as error:
            ok=False
            print(f"[ESCAPED] {d.name}: {error}",flush=True)
        failed |= not ok
    shutil.rmtree(root/"work")
    return failed
