# SPDX-License-Identifier: CERN-OHL-W-2.0
"""One named observable must reject each planted SRP defect; compile errors do not count."""
from dataclasses import dataclass
from pathlib import Path
import shutil
from ctrl_build import CTRL, Tree, Refusal, Outcome
import fw_gtest
from srp_arms import arm_srp
def caught(test: str, needle: str, outcome: Outcome) -> bool:
    """Match the named FT failure and its complete GoogleTest diagnostic.

    FT repeats the last diagnostic line; equality diagnostics put the
    expression on earlier lines. Only that failure block may satisfy it.
    """
    if outcome.rc != 1:
        return False
    for line in outcome.log.splitlines():
        if line.strip().startswith("[FAIL] "+test+":"):
            end=outcome.log.index(line)
            start=outcome.log.rfind("Failure\n",0,end)
            diagnostic=outcome.log[start:end] if start>=0 else line
            if needle in diagnostic or needle in line:
                return True
    return False


@dataclass(frozen=True)
class Defect:
    """A source mutation and the independently named observable it must fail."""

    name: str
    test: str
    old: str
    new: str
    needle: str
    path: str = "srp/srp_mbx.c"
    suite: str = "srp_mbx.cpp"
    debug: bool = False

DEFECTS = (
    Defect(
        name='startup-vid',
        test='StartupDeclaresTalkersDomainAndVlan',
        old='{6,3,2}',
        new='{6,3,7}',
        needle='d.value',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='short-leave',
        test='LeaveAfterLeaveAllStopsAtOriginalFiveSecondDeadline',
        old='i->msrp,0,20,500,1000',
        new='i->msrp,0,20,400,1000',
        needle='Unexpected mock function call',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='asking-is-ready',
        test='RegisteredListenerSubtypeChangeRevokesPermission',
        old='v[8] == 2 || v[8] == 3',
        new='v[8] == 1 || v[8] == 2 || v[8] == 3',
        needle='adapter.ifs[0].active[0]',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='ignore-link',
        test='InterfaceStateDoesNotCross',
        old='if (i->link_seen || !event->link_up)',
        new='if (false)',
        needle='adapter.ifs[i].active[0]',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='failed-listener-ready',
        test='SinkPortUsesMatchingRegisteredTalkerAndRetainsLeaveTimer',
        old='sink->desired = 1;',
        new='sink->desired = 2;',
        needle='declared',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='ignore-peer-domain',
        test='DomainUsesPeerPriorityAndVlan',
        old='i->next_domain = *value;',
        new='i->next_domain = i->domain;',
        needle='domain.priority',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='rx-overtakes-owed',
        test='RefusedMailboxRetainsOwedFrameAndDefersInput',
        old='return m->owed_len == 0 &&',
        new='return',
        needle='adapter.received',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='rx-overtakes-expiry',
        test='ExpiryBacklogPrecedesSamePassReceive',
        old='m->loop->ticks_owed == 0 &&',
        new='true &&',
        needle='adapter.stops',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='reentry-uncounted',
        test='ReentryFromOutputIsRefusedAndCounted',
        old='++m->reentries;',
        new='(void)m;',
        needle='adapter.reentries',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='invalid-vid',
        test='InvalidBindingsAndDuplicateBindingsPreserveState',
        old='vid == 0 || vid >= 4095',
        new='vid >= 4095',
        needle='srp_mbx_bind',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='failed-init-leaks',
        test='ExhaustionDuringEachStartupStageReleasesEveryBlock',
        old='++m->refused;\n            srp_mbx_destroy(m);',
        new='++m->refused;',
        needle='ctrl_pool_in_use',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='missing-port-accepted',
        test='MissingBootDependenciesRefuseBeforeAttachment',
        old='!config->licence || !shlan_port_pool()',
        new='!shlan_port_pool()',
        needle='srp_mbx_init',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='attach-nonatomic',
        test='AttachmentFailureIsAtomicAndDetachesAfterLoopReset',
        old='loop->n_polls < CTRL_LOOP_MAX_POLLS &&',
        new='true &&',
        needle='srp_mbx_attach',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='malformed-uncounted',
        test='InvalidFramesHaveNoReservationSideEffects',
        old='++m->malformed;\n    } else',
        new='(void)m;\n    } else',
        needle='adapter.malformed',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='reset-skips-recreate',
        test='RecreateAllocationFailureIsCountedAndRetried',
        old='if (!i->msrp) {\n            // A failed recreate',
        new='if (!i->msrp) {\n            continue; // A failed recreate',
        needle='adapter.ifs[0].msrp',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='readyfailed-ignored',
        test='ReadyFailedAndUninterestingStreamsAreSeparated',
        old='v[8] == 2 || v[8] == 3',
        new='v[8] == 2',
        needle='Actual function call count',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='foreign-domain-stored',
        test='DomainFilterAndDuplicateDoNotGrowDeclarations',
        old='d->class_id == 6 &&',
        new='d->class_id > 0 &&',
        needle='ctrl_pool_in_use',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='foreign-vlan-stored',
        test='MvrpAcceptsOnlyCurrentDomainVid',
        old='if (vid == i->domain.vid)',
        new='if (vid != 0)',
        needle='ctrl_pool_in_use',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='sink-da-ignored',
        test='WireMismatchesCannotAdmitBoundSinkAndLeaveExpiresIt',
        old='memcmp(sink->dest_mac,v->dest_mac,6) == 0 &&',
        new='true &&',
        needle='declared',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='admission-ceiling-ignored',
        test='AdmissionUsesBandwidthAndEthernetMinimum',
        old='used + slope <= (uint64_t)m->config.link_rate_bps * 3u / 4u',
        new='used + slope <= (uint64_t)m->config.link_rate_bps * 1000u',
        needle='admitted[0]',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='domain-refusal-lost',
        test='DomainExhaustionPreservesOldDeclarationUntilRetry',
        old='if (mvrp_declare(i->mvrp,0,i->next_domain.vid) != 0)',
        new='if (mvrp_declare(i->mvrp,0,i->next_domain.vid) == 99)',
        needle='domain.vid',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='listener-refusal-lost',
        test='SinkDeclarationExhaustionRetriesWithoutLosingBinding',
        old='if (result == 0)',
        new='if (result != 99)',
        needle='declared',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='other-link-cancels-owed',
        test='LinkLossCancelsItsOwedFrameOnly',
        old='m->owed_len && m->owed_if == i->index',
        new='m->owed_len && m->owed_if != i->index',
        needle='adapter.owed_len',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='duplicate-tick-owner',
        test='OneLoopOwnsTheGlobalCentisecondDispatch',
        old='!m->loop && !timer_owner &&',
        new='!m->loop &&',
        needle='srp_mbx_attach',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=False,
    ),
    Defect(
        name='binding-debug-guard',
        test='SynchronousBindingFromOutputAsserts',
        old='assert(!m->busy);',
        new='(void)m;',
        needle='failed to die',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=True,
    ),
    Defect(
        name='receive-debug-guard',
        test='SynchronousReceiveFromOutputAsserts',
        old='assert(!m->busy);',
        new='(void)m;',
        needle='failed to die',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=True,
    ),
    Defect(
        name='tick-debug-guard',
        test='SynchronousTickFromOutputAsserts',
        old='assert(!m->busy);',
        new='(void)m;',
        needle='failed to die',
        path='srp/srp_mbx.c',
        suite='srp_mbx.cpp',
        debug=True,
    ),
    Defect(
        name='licence-before-vlan',
        test='ListenerBeforeVlanCommitCannotStartTalker',
        old='link && i->vlan_sent &&',
        new='link &&',
        needle='joined',
    ),
    Defect(
        name='unbind-shared-listener',
        test='SharedBindingsRetainTheListenerAndVlanUntilTheLastUnbind',
        old='if (!has_sink(i,&old,true))',
        new='if (true)',
        needle='d.event',
    ),
    Defect(
        name='withdraw-bound-domain',
        test='BoundOldDomainVlanSurvivesDomainChange',
        old=' && !has_sink(i,&old_vlan,false)',
        new=' && (old_vlan.vid != 0)',
        needle='d.event',
    ),
    Defect(
        name='withdraw-same-domain',
        test='PriorityOnlyDomainChangeKeepsVlanMembership',
        old='i->domain.vid != i->next_domain.vid && !has_sink',
        new='i->domain.vid != 0 && !has_sink',
        needle='d.event',
    ),
    Defect(
        name='sink-vlan-refusal-lost',
        test='SinkVlanExhaustionRetriesAndDistinctMembershipsRemainIndependent',
        old='if (mvrp_declare(i->mvrp,0,s->vid) != 0)',
        new='if (mvrp_declare(i->mvrp,0,s->vid) == 99)',
        needle='vlan_requested',
    ),
    Defect(
        name='ready-before-vlan',
        test='SinkMembershipCommitsBeforeReadyAtStartup',
        old='if (r->desired != 2 || r->vlan_sent)',
        new='if (true)',
        needle='joined',
    ),
    Defect(
        name='latency-missing-startup',
        test='SrpLatency.StartupJoinPeriodicAndLeaveAllCommitWithinOneBudget',
        old='if (i->link) {',
        new='if (i->link && false) {',
        needle='commits.size()',
        suite='srp_latency.cpp',
    ),
    Defect(
        name='latency-domain-unserviced',
        test='SrpLatency.ReceiveStateMalformedDomainAndListenerPaths',
        old='i->next_domain = *value;',
        new='i->next_domain = i->domain;',
        needle='domain.vid',
        suite='srp_latency.cpp',
    ),
    Defect(
        name='latency-leave-origin',
        test='SrpLatency.OriginalLeaveDeadlineSurvivesCoalescedBacklog',
        old='i->msrp,0,20,500,1000',
        new='i->msrp,0,20,400,1000',
        needle='Unexpected mock function call',
        suite='srp_latency.cpp',
    ),
    Defect(
        name='latency-relaxed-budget',
        test='SrpLatency.FullRingRetainsOriginalOriginAndElevenMillisecondStallFails',
        old='10000000',
        new='20000000',
        needle='service_limit',
        suite='srp_latency.cpp',
        path='test/srp_latency_policy.hpp',
    ),
    Defect(
        name='walk-domain-ignored',
        test='SrpWalk.CertifiedTwoClassDomainVectorAdoptsOnlyClassA',
        old='i->next_domain = *value;',
        new='i->next_domain = i->domain;',
        needle='domain.vid',
        suite='srp_walk.cpp',
    ),
    Defect(
        name='walk-match-da-ignored',
        test='SrpWalk.StreamMatcherNearMissSwapAndImmediateWithdrawal',
        old='memcmp(sink->dest_mac,v->dest_mac,6) == 0 &&',
        new='true &&',
        needle='declared',
        suite='srp_walk.cpp',
    ),
    Defect(
        name='walk-leave-shortened',
        test='SrpWalk.RunBLeaveAllLanesPreserveTheRedeclaredListener',
        old='i->msrp,0,20,500,1000',
        new='i->msrp,0,20,400,1000',
        needle='Unexpected mock function call',
        suite='srp_walk.cpp',
    ),
    Defect(
        name='walk-startup-is-join',
        test='SrpWalk.ProcessorApplicantTransmitAndReceivedRowsAgreeOnTheWire',
        old='&value,true) != 0',
        new='&value,false) != 0',
        needle='d.event',
        suite='srp_walk.cpp',
    ),
    Defect(
        name='walk-malformed-uncounted',
        test='SrpWalk.PerInterfaceWireIdentityAndUnknownOrTruncatedInput',
        old='++m->malformed;\n    } else',
        new='(void)m;\n    } else',
        needle='adapter.malformed',
        suite='srp_walk.cpp',
    ),
    Defect(
        name='shape-last-output-missing',
        test='EveryGeneratedOutputIsDeclaredAndEverySinkFits',
        old='unsigned n = 0; n < CTRL_SRP_SOURCES; ++n) {\n        struct msrp_talker_failed',
        new='unsigned n = 0; n + 1 < CTRL_SRP_SOURCES; ++n) {\n        struct msrp_talker_failed',
        needle='outputs',
        suite='srp_shape.cpp',
    ),
    Defect('tag-overhead-omitted','AdmissionStraddlesTheExactEthernetCeiling',
           '+ 22u','+ 18u','admitted[0]'),
    Defect('preamble-ifg-omitted','AdmissionStraddlesTheExactEthernetCeiling',
           '(size + 20u)','(size + 0u)','admitted[0]'),
    Defect('ninety-percent-ceiling','AdmissionStraddlesTheExactEthernetCeiling',
           '* 3u / 4u','* 9u / 10u','admitted[0]'),
    Defect('readyfailed-callback-stop','ReadyToReadyFailedNeverGlitchesAnActiveLicence',
           'declaration == MSRP_LISTENER_DECL_READY_FAILED','false','mock function call'),
    Defect('short-link-interruption-ignored','AdjacentLinkEdgesResetDomainAndAllPriorRegistrations',
           'if (i->link_seen || !event->link_up)','if (!mbx_link_up(i->index))','domain.priority'),
    Defect('old-prefix-accepted','LinkEventsDiscardOnlyTheirPublishedReceivePrefix',
           'i->discard_prefix && mbx_rx_before(MBX_CH_SRP,i->rx_mark)',
           'false','mock function call'),
    Defect('shared-identity-overwritten','SharedIdentityReconcilesBothBindingOrdersOnTheWire',
           'desired |= r->desired;','desired = r->desired;','last'),
    Defect('event-reentry-unguarded','EventReentryAndSinkCapacityAreGuarded',
           'static void on_event(void *ctx, const struct mbx_event *event)\n{\n'
           '    struct srp_mbx *m = ctx;\n    if (!enter(m))',
           'static void on_event(void *ctx, const struct mbx_event *event)\n{\n'
           '    struct srp_mbx *m = ctx;\n    if (false)',
           'adapter.reentries'),

    Defect('failed-interface-starves-peer','RecreateAllocationFailureIsCountedAndRetried',
           'if (!i->msrp) {\n            m->cursor = (slot + 1u) % (2u * MBX_N_IF);',
           'if (!i->msrp) {','other_sent'),
    Defect('backlogged-old-prefix-accepted','OldReceiveBacklogCannotRegisterAcrossLinkRestart',
           'i->discard_prefix && mbx_rx_before(MBX_CH_SRP,i->rx_mark)',
           'false','mock function call'),
    Defect('link-level-loss-ignored','LinkLevelLossAndFirstDownEventAreFailClosed',
           'if (i->link != link)', 'if (!i->link && link)', 'adapter.ifs[0].active[0]'),
    Defect('reset-leaks-owned-participants','ExhaustedPoolStillReusesOwnedBlocksOnLinkReset',
           'msrp_app_destroy(i->msrp); mvrp_app_destroy(i->mvrp);\n'
           '    i->msrp = NULL; i->mvrp = NULL; i->domain_owed = false;',
           'i->msrp = NULL; i->mvrp = NULL; i->domain_owed = false;', 'adapter.refused'),
    Defect('downlink-receive-accepted','OldReceiveBacklogCannotRegisterAcrossLinkRestart',
           '!i->link || (i->discard_prefix', 'false || (i->discard_prefix',
           'adapter.ifs[i].registered[0]'),
    Defect('delayed-in-listener','InListenerWithdrawalRevokesLicenceImmediately',
           '// These valid constants',
           '((struct mrp_app_ops *)i->msrp->ops)->milan_rapid_leave = false;\n    // These valid constants',
           'adapter.ifs[i].active[0]'),
    Defect('delayed-in-talker','InTalkerWithdrawalImmediatelyWithdrawsListener',
           '// These valid constants',
           '((struct mrp_app_ops *)i->msrp->ops)->milan_rapid_leave = false;\n    // These valid constants',
           'declared'),
    Defect('attach-ignores-current-link','ReattachLearnsAnAlreadyUpLinkWithoutAnotherRecord',
           'm->ifs[n].link = mbx_link_up(n);', 'm->ifs[n].link = false;', 'adapter.ifs[i].link'),
    Defect('cancelled-link-never-recovers','CancelledLinkRecordRecoversFromLevelAndFencesOldReceive',
           'if (i->link != link)', 'if (i->link && !link)', 'adapter.ifs[i].link'),
    Defect('rebind-loses-shared-applicant','SharedRebindKeepsOnlyTheRemainingEligibleRequest',
           'replacement.declared |= r->declared;', '(void)r;', 'left'),
    Defect('consecutive-rebind-loses-applicant','ConsecutiveSharedReplacementsKeepApplicantStateUntilReconciliation',
           'replacement.declared |= r->declared;', '(void)r;', 'left'),
    Defect('joining-binding-loses-applicant','JoiningIneligibleBindingWithdrawsReadyWhenOriginalLeaves',
           'replacement.declared |= r->declared;',
           'if (r == s) { replacement.declared |= r->declared; }', 'd.event'),
    Defect('applicant-inherited-across-streams','ReboundStreamCannotInheritAnotherStreamsReady',
           'if (memcmp(r->stream_id.bytes,identity->bytes,8) == 0)',
           'if (true)', 'ready'),
    Defect('final-unbind-withdraws-domain-vid','FinalDomainVidUnbindKeepsSrClassMembership',
           'if (old.vid != i->domain.vid && !has_sink(i,&old,false))',
           'if (!has_sink(i,&old,false))', 'd.event'),
    Defect('last-ineligible-vid-leaks','LastNeverEligibleBindingWithdrawsTheSharedVidInEitherOrder',
           'if (old.vid != i->domain.vid &&', 'if (old.vlan_requested && old.vid != i->domain.vid &&', 'vlan_left'),
    Defect('reset-keeps-owed-domain','RefusedPeerDomainDoesNotSurviveLinkRestart',
           'i->msrp = NULL; i->mvrp = NULL; i->domain_owed = false;',
           'i->msrp = NULL; i->mvrp = NULL;', 'domain.vid'),
    Defect('reset-keeps-sink-vlan','SinkVlanRedeclaredBeforeReadyAfterLinkRestart',
           'i->sinks[k].vlan_requested = false; i->sinks[k].vlan_sent = false;',
           '(void)k;', 'vlan'),
    Defect('shared-ready-uses-first-vlan','SharedReadyWaitsForTheMatchingBindingsOwnVlan',
           'if (r->desired != 2 || r->vlan_sent)',
           'if (r->desired != 2 || s->vlan_sent)', 'vlan'),
    Defect('milan-rapid-leave-leaks-to-mvrp','MilanMsrpOptionLeavesMvrpOnTheOriginalLeaveDeadline',
           '// These valid constants',
           '((struct mrp_app_ops *)i->mvrp->ops)->milan_rapid_leave = true;\n    // These valid constants',
           'registered()'),

    Defect('receive-retry-removed','SrpRetry.RefusedMixedPayloadRetriesWithoutPeerRetransmission',
           'if (apply_receive(m,&m->pending_rx))', 'if (false)', 'adapter.received',
           suite='srp_rx_retry.cpp'),
    Defect('partial-receive-retry-removed','SrpRetry.PartialPayloadKeepsLaterAttributesAndDoesNotRepeatStop',
           'if (apply_receive(m,&m->pending_rx))', 'if (false)', 'domain.vid',
           suite='srp_rx_retry.cpp'),
    Defect('receive-record-lost','SrpRetry.RefusedMixedPayloadRetriesWithoutPeerRetransmission',
           'm->pending_rx = *frame;', '(void)frame;', 'adapter.pending_rx.len',
           suite='srp_rx_retry.cpp'),
    Defect('receive-refusal-malformed','SrpRetry.RefusedMixedPayloadRetriesWithoutPeerRetransmission',
           'if (result == -SHLAN_ERROR_NO_MEMORY) {',
           'if (result == -SHLAN_ERROR_NO_MEMORY) { ++m->malformed;', 'adapter.malformed',
           suite='srp_rx_retry.cpp'),
    Defect('receive-overtakes-retained','SrpRetry.LaterRecordsCannotOvertakeRetainedInterface',
           'return m->pending_rx.len == 0 && rx_order_ready(m);',
           'return rx_order_ready(m);', 'loop.stats.rx_records', suite='srp_rx_retry.cpp'),
    Defect('reset-keeps-retained-receive','SrpRetry.LinkResetCancelsRetainedPayloadAndFencesLaterOldRecords',
           'm->pending_rx.len && m->pending_rx.interface == i->index', 'false',
           'adapter.received', suite='srp_rx_retry.cpp'),
    Defect('peer-reset-cancels-retained-receive','SrpRetry.OtherInterfaceResetPreservesRetainedPayload',
           'm->pending_rx.len && m->pending_rx.interface == i->index', 'm->pending_rx.len',
           'adapter.pending_rx.len', suite='srp_rx_retry.cpp'),
    Defect('destroy-keeps-retained-receive','SrpRetry.DestroyCancelsRetainedPayloadBeforeReinitialization',
           'm->pending_rx.len = 0;\n    m->initialized = false;',
           'm->initialized = false;', 'adapter.pending_rx.len', suite='srp_rx_retry.cpp'),
    Defect('bind-overtakes-retained-receive','SrpRetry.RefusedMixedPayloadRetriesWithoutPeerRetransmission',
           ' || m->pending_rx.len)', ')', 'srp_mbx_bind', suite='srp_rx_retry.cpp'),
    Defect('composition-attach-omitted','SrpApp.AllThreeProtocolsShareTheLoopAndWakeSources',
           '!srp_mbx_attach(srp,&app->loop)', '!(srp != NULL)', 'app.loop.n_ticks',
           path='app/ctrl_app_srp.c',suite='srp_app.cpp'),
    Defect('composition-srp-irq-omitted','SrpApp.AllThreeProtocolsShareTheLoopAndWakeSources',
           'mbx_place(channels,MBX_IRQ_ENABLE_RX_LSB',
           'mbx_place(channels & ~(1u << MBX_CH_SRP),MBX_IRQ_ENABLE_RX_LSB', 'model.irq_enable',
           path='app/ctrl_app_srp.c',suite='srp_app.cpp'),
    Defect('composition-srp-tick-omitted','SrpApp.AllThreeProtocolsShareTheLoopAndWakeSources',
           'mbx_tick_enable(true);', 'mbx_tick_enable(false);', 'app.loop.stats.ticks',
           path='app/ctrl_app_srp.c',suite='srp_app.cpp'),

    Defect('recreated-receive-retry-removed','SrpRetry.FailedParticipantRecreationRetainsFreshReceive',
           'if (apply_receive(m,&m->pending_rx))', 'if (false)', 'adapter.received',
           suite='srp_rx_retry.cpp'),
    Defect('mvrp-receive-retry-removed','SrpRetry.RetainedMvrpUsesItsOriginalParticipant',
           'if (apply_receive(m,&m->pending_rx))', 'if (false)', 'adapter.received',
           suite='srp_rx_retry.cpp'),
    Defect('receive-retry-passes-owed','SrpRetry.RetainedReceiveWaitsForOwedTransmit',
           'm->pending_rx.interface == n && rx_order_ready(m)', 'm->pending_rx.interface == n',
           'adapter.pending_rx.len', suite='srp_rx_retry.cpp'),
    Defect('receive-retry-passes-backlog','SrpRetry.RetainedReceiveWaitsForTickAndLifecycleBacklogs',
           'm->pending_rx.interface == n && rx_order_ready(m)', 'm->pending_rx.interface == n',
           'adapter.received', suite='srp_rx_retry.cpp'),
    Defect('future-receive-refused','SrpRetry.WholeInvalidPduIsMalformedAndFutureUnknownMessageIsSkipped',
           'frame->len - 14u) :', '(frame->bytes[14] ? 0u : frame->len - 14u)) :',
           'adapter.ifs[0].active[0]', suite='srp_rx_retry.cpp'),
    Defect('invalid-suffix-uncounted','SrpRetry.WholeInvalidPduIsMalformedAndFutureUnknownMessageIsSkipped',
           '++m->malformed;\n    } else', '(void)m;\n    } else',
           'adapter.malformed', suite='srp_rx_retry.cpp'),
    Defect('composition-refusal-ignored','SrpApp.AttachRefusalPreservesExistingComposition',
           '!srp_mbx_attach(srp,&app->loop)', '!(srp != NULL)', 'ctrl_app_attach_srp',
           path='app/ctrl_app_srp.c',suite='srp_app.cpp'),
    Defect('recovery-latency-retry-removed','SrpLatency.ReceiveRecoveryKeepsOriginalArrivalBudget',
           'if (apply_receive(m,&m->pending_rx))', 'if (false)', 'adapter.ifs[0].active[0]',
           suite='srp_latency.cpp'),

)

def campaign(root: Path, lwsrp: Path, jobs: int = 4) -> bool:
    """Run every mutation in a reusable isolated checkout; true means a failure."""
    build=fw_gtest.Build(jobs=jobs)
    failed=False
    root.mkdir(parents=True,exist_ok=True)
    for d in DEFECTS:
        out=root/"work"
        src=out/"ctrl"
        shutil.copytree(CTRL,src,dirs_exist_ok=True,ignore=shutil.ignore_patterns("__pycache__","*.pyc"))
        target=src/d.path
        source=target.read_text()
        if source.count(d.old)!=1:
            raise Refusal(f"SRP defect {d.name} has {source.count(d.old)} planting sites")
        target.write_text(source.replace(d.old,d.new))
        selected=d.test if "." in d.test else "Srp."+d.test
        try:
            result=arm_srp(Tree(src,out/"build",out/"reuse",build),lwsrp,2,
                           debug=d.debug,test=(d.suite, selected))
            ok=caught(selected,d.needle,result)
            (root/(d.name+".log")).write_text(result.log)
            print(f"[{'ok' if ok else 'ESCAPED'}] {d.name}: {d.test} / {d.needle}",flush=True)
            if not ok: print(result.log,flush=True)
        except Refusal as error:
            ok=False
            print(f"[ESCAPED] {d.name}: {error}",flush=True)
        failed |= not ok
    shutil.rmtree(root/"work")
    return failed
