#!/usr/bin/python3 -S
import sys
sys.path.insert(0, '$WORKSPACE_HOME/milan-fpga-management/2026-09-22/517-f1-author/final-staged-backpressure/make-flush-SIGTERM-active')
import fake_leg
fake_leg.main({'out': [['out', 'first binary\x00ÿ\x80\n']], 'hold': '$WORKSPACE_HOME/milan-fpga-management/2026-09-22/517-f1-author/final-staged-backpressure/make-flush-SIGTERM-active/hold-L1.fifo', 'name': 'L1', 'ledger': '$WORKSPACE_HOME/milan-fpga-management/2026-09-22/517-f1-author/final-staged-backpressure/make-flush-SIGTERM-active/ledger.jsonl', 'announce': '$WORKSPACE_HOME/milan-fpga-management/2026-09-22/517-f1-author/final-staged-backpressure/make-flush-SIGTERM-active/announce.fifo'})
