#!/usr/bin/env python3
"""Scratch only (never committed): price the SoC's CPU, cache and L2 variants that the
recipe refuses under its one software profile (issue #649, round-2 ruling).

The tracked recipe sw/litex/milan_soc.py is never written. A scratch export of HEAD
(syn/resmap/yosys_sweep.py export_tree) gets a SECOND copy of the recipe,
milan_soc_pricing.py, with exactly the two baremetal-profile refusals removed. Every
variant (shipping included) is exported through that copy without --build; the
shipping variant is also exported through the unmodified tracked copy, and the two
gateware tops must be byte-identical (the bypass changes nothing an accepted shape
elaborates). CPU netlists are generated by the CPU generators in scratch copies of
the two pythondata packages (PYTHONPATH first), never in the shared LiteX tree.

Each export is then synthesized out of context by Vivado (soc_ooc.tcl, one run at a
time under the shared lock): the LiteX top with the CPU netlist, and every other
non-LiteX module (milan_datapath and the parent's own SystemVerilog blocks) replaced by
a black box with 1024-bit ports, exactly the round-1 Yosys stubbing. Every variant
reads the shipping variant's BIOS ROM image, so ROM content is held constant.

    price_variants.py prepare
    price_variants.py export [NAME..]
    price_variants.py vivado-prep [NAME..]
    price_variants.py collect
"""

import json
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

REPO = Path("$LANES/649-resmap")
sys.path.insert(0, str(REPO / "syn" / "resmap"))
import soc_sweep  # noqa: E402
import yosys_sweep  # noqa: E402

WORK = Path("$VALIDATION_STORAGE/649-a527/r2/soc")
CPU = Path("$VALIDATION_STORAGE/649-a527/r2/cpu")
LITEX_PYTHON = "$WORKSPACE_HOME/litex-milan/venv/bin/python3"
SDK = Path("$VALIDATION_STORAGE/231-a337-sdk")
PART = "xc7a100t-fgg484-2"

#: The recipe's profile refusal, removed in the pricing copy; each block must occur once.
REFUSALS = (
    '    if args.cpu != "vexiiriscv" or args.xlen != 32 or args.cpu_count != 1:\n'
    '        ap.error("--software-profile baremetal requires --cpu vexiiriscv "\n'
    '                 "--xlen 32 --cpu-count 1")\n',
    '    if args.with_fpu or args.l2_bytes or args.scala_args:\n'
    '        ap.error("--software-profile baremetal requires no FPU, --l2-bytes 0, "\n'
    '                 "and no --scala-args overrides")\n',
)

#: name: (parameter, value label, argv edit). The six plan variants keep their plan spelling.
VARIANTS = {
    "ship": ("shipping", "-", {}),
    "l2-8k": ("L2 bytes", "8192", {"set": {"--l2-bytes": "8192"}}),
    "l2-16k": ("L2 bytes", "16384", {"set": {"--l2-bytes": "16384"}}),
    "l2-32k": ("L2 bytes", "32768", {"set": {"--l2-bytes": "32768"}}),
    "cpu2": ("CPU count", "2", {"set": {"--cpu-count": "2"}}),
    "cpu4": ("CPU count", "4", {"set": {"--cpu-count": "4"}}),
    "rv64": ("XLEN", "64", {"set": {"--xlen": "64"}}),
    "rv64-fpu": ("recipe --with-fpu", "RV64 + --with-fpu", {"set": {"--xlen": "64"}, "add": ["--with-fpu"]}),
    "fpu-f": ("FPU (core option)", "F", {"add": ["--scala-args=--with-rvf"]}),
    "fpu-fd": ("FPU (core option)", "F+D", {"add": ["--scala-args=--with-rvf --with-rvd"]}),
    "isa-m": ("ISA extensions", "M", {"add": ["--scala-args=--with-mul --with-div"]}),
    "isa-mf": ("ISA extensions", "M+F", {"add": ["--scala-args=--with-mul --with-div --with-rvf"]}),
    "isa-mfd": ("ISA extensions", "M+F+D", {"add": ["--scala-args=--with-mul --with-div --with-rvf --with-rvd"]}),
    "l1-fetch": ("L1 caches", "fetch only", {"add": ["--scala-args=--with-fetch-l1"]}),
    "l1-caches": ("L1 caches", "fetch + LSU, 1 way", {"add": ["--scala-args=--with-fetch-l1 --with-lsu-l1"]}),
    "l1-w2": ("L1 caches", "fetch + LSU, 2 ways",
              {"add": ["--scala-args=--with-fetch-l1 --with-lsu-l1 --fetch-l1-ways=2 --lsu-l1-ways=2"]}),
    "l1-w4": ("L1 caches", "fetch + LSU, 4 ways",
              {"add": ["--scala-args=--with-fetch-l1 --with-lsu-l1 --fetch-l1-ways=4 --lsu-l1-ways=4"]}),
    "l1l2-8k": ("L2 bytes, both L1 caches", "8192",
                {"set": {"--l2-bytes": "8192"}, "add": ["--scala-args=--with-fetch-l1 --with-lsu-l1"]}),
    "l1l2-16k": ("L2 bytes, both L1 caches", "16384",
                 {"set": {"--l2-bytes": "16384"}, "add": ["--scala-args=--with-fetch-l1 --with-lsu-l1"]}),
    "l1l2-32k": ("L2 bytes, both L1 caches", "32768",
                 {"set": {"--l2-bytes": "32768"}, "add": ["--scala-args=--with-fetch-l1 --with-lsu-l1"]}),
    "naxriscv": ("core", "NaxRiscv RV32", {"set": {"--cpu": "naxriscv"}}),
    "naxriscv-rv64": ("core", "NaxRiscv RV64", {"set": {"--cpu": "naxriscv", "--xlen": "64"}}),
}


#: The numeric value of each variant on its parameter's axis, where the parameter has one (the shipping
#: variant is the 0 of the L2 and L1 axes and the 1 of the CPU-count axis).
X = {"l2-8k": 8, "l2-16k": 16, "l2-32k": 32, "l1l2-8k": 8, "l1l2-16k": 16, "l1l2-32k": 32, "cpu2": 2, "cpu4": 4, "l1-caches": 1, "l1-w2": 2, "l1-w4": 4}


def sha256(path: Path) -> str:
    return yosys_sweep.sha256(path)


def env() -> dict:
    return {**os.environ, "PYTHONHASHSEED": "0", "LITEX_ENV_CC_TRIPLE": soc_sweep.compiler_triple(),
            "PYTHONPATH": f"{CPU / 'pythondata-cpu-vexiiriscv'}:{CPU / 'pythondata-cpu-naxriscv'}",
            "PATH": f"{SDK / 'bin'}:{Path(LITEX_PYTHON).parent}:{os.environ['PATH']}"}


def command_prepare() -> int:
    tree = yosys_sweep.export_tree(WORK)
    base = soc_sweep.prepare(WORK)
    recipe = tree / "sw" / "litex" / "milan_soc.py"
    text = recipe.read_text()
    for block in REFUSALS:
        if text.count(block) != 1:
            print(f"prepare: refusal block not found exactly once: {block[:60]!a}")
            return 1
        text = text.replace(block, "    pass  # pricing copy (#649 round 2): the profile refusal is removed\n")
    pricing = recipe.with_name("milan_soc_pricing.py")
    pricing.write_text(text)
    diff = subprocess.run(["diff", "-u", str(recipe), str(pricing)], capture_output=True, text=True).stdout
    (WORK / "pricing-copy.diff").write_text(diff)
    record = {"head": (tree / ".resmap-export").read_text().split()[0], "base_argv": base,
              "tracked_recipe_sha256": sha256(recipe), "pricing_copy_sha256": sha256(pricing),
              "pricing_diff_sha256": sha256(WORK / "pricing-copy.diff"),
              "vexii_patch": subprocess.run(["git", "-C", str(CPU / "pythondata-cpu-vexiiriscv/pythondata_cpu_vexiiriscv/verilog/ext/VexiiRiscv"),
                                             "diff", "--stat"], capture_output=True, text=True).stdout.strip()}
    (WORK / "prepare.json").write_text(json.dumps(record, indent=1, sort_keys=True) + "\n")
    print(f"prepare: export of {record['head']}, pricing copy {record['pricing_copy_sha256'][:16]}")
    return 0


def export_one(name: str, recipe: str, spec: dict, base: list[str]) -> dict:
    directory = WORK / "soc" / name
    if directory.exists():
        shutil.rmtree(directory)
    directory.mkdir(parents=True)
    argv = soc_sweep.variant_argv(base, spec) + ["--output-dir", str(directory / "export")]
    log = directory / "export.log"
    began = time.time()
    with log.open("w") as handle:
        rc = subprocess.run([LITEX_PYTHON, recipe, *argv], cwd=WORK / "tree/sw/litex", env=env(),
                            stdout=handle, stderr=subprocess.STDOUT, check=False).returncode
    text = log.read_text(errors="replace")
    netlist = re.search(r"(?:VexiiRiscv|NaxRiscv) netlist ?: ?(\S+)", text)
    top = directory / "export" / "gateware" / "alinx_ax7101.v"
    record = {"recipe": recipe, "argv": argv, "rc": rc, "seconds": round(time.time() - began, 1),
              "log_sha256": sha256(log), "log_bytes": log.stat().st_size,
              "cpu_netlist": netlist.group(1) if netlist else "",
              "top_sha256": sha256(top) if top.is_file() else "",
              "error_tail": [line for line in text.splitlines() if re.search(r"error|Error|ERROR|Traceback", line)][-6:]}
    print(f"export {name}: rc={rc} {record['seconds']} s {record['cpu_netlist'] or record['error_tail'][-1:]}",
          flush=True)
    return record


def command_export(names: list[str]) -> int:
    prep = json.loads((WORK / "prepare.json").read_text())
    path = WORK / "exports.json"
    records = json.loads(path.read_text()) if path.is_file() else {}
    chosen = [n for n in VARIANTS if not names or n in names]
    if not names or "ship" in names:
        chosen.append("ship-tracked")
    failures = 0
    for name in chosen:
        if name == "ship-tracked":
            record = export_one(name, "milan_soc.py", {}, prep["base_argv"])
        else:
            parameter, value, spec = VARIANTS[name]
            record = export_one(name, "milan_soc_pricing.py", spec, prep["base_argv"])
            record.update(parameter=parameter, value=value)
        records[name] = record
        path.write_text(json.dumps(records, indent=1, sort_keys=True) + "\n")
        failures += record["rc"] != 0
    return 1 if failures else 0


OOC_TCL = r"""# Scratch only: Vivado out-of-context synthesis of one exported SoC top (issue #649 round 2).
set dir [file normalize [lindex $argv 0]]
cd $dir
set fh [open sources.txt r]; set sources [split [string trim [read $fh]] "\n"]; close $fh
foreach source $sources { read_verilog $source }
synth_design -directive default -mode out_of_context -top alinx_ax7101 -part PART_NAME
report_utilization -hierarchical -hierarchical_depth 2 -file synth_hierarchy.rpt
report_utilization -file synth_utilization.rpt
# No opt_design: it refuses primitives that a black box drives (Opt 31-30), and the black boxes are the
# point of this run. Every variant is therefore compared after synthesis.
puts "SOC_OOC_DONE"
""".replace("PART_NAME", PART)


def command_vivado_prep(names: list[str]) -> int:
    exports = json.loads((WORK / "exports.json").read_text())
    ship_rom = WORK / "soc" / "ship" / "export" / "gateware" / "alinx_ax7101_rom.init"
    failures = 0
    for name, record in exports.items():
        if record["rc"] or (names and name not in names) or name == "ship-tracked":
            continue
        gateware = WORK / "soc" / name / "export" / "gateware"
        directory = WORK / "vivado" / name
        if directory.exists():
            shutil.rmtree(directory)
        directory.mkdir(parents=True)
        top_text = (gateware / "alinx_ax7101.v").read_text()
        foreign = soc_sweep.foreign_modules(top_text)
        cpu_module = record["cpu_netlist"]
        if cpu_module not in foreign:
            print(f"vivado-prep {name}: CPU module {cpu_module} is not instantiated by the top")
            failures += 1
            continue
        stubbed = sorted(foreign - {cpu_module})
        (directory / "stubs.v").write_text(soc_sweep.stubs(top_text, set(stubbed)).replace("(* blackbox *)",
                                                                                            "(* black_box *)"))
        tcl_text = (gateware / "alinx_ax7101.tcl").read_text()
        cpu_srcs = soc_sweep.cpu_sources(tcl_text, cpu_module)
        shutil.copyfile(gateware / "alinx_ax7101.v", directory / "alinx_ax7101.v")
        for init in gateware.glob("*.init"):
            shutil.copyfile(init, directory / init.name)
        shutil.copyfile(ship_rom, directory / "alinx_ax7101_rom.init")
        sources = [*map(str, cpu_srcs), str(directory / "alinx_ax7101.v"), str(directory / "stubs.v")]
        (directory / "sources.txt").write_text("\n".join(sources) + "\n")
        (directory / "soc_ooc.tcl").write_text(OOC_TCL)
        meta = {"stubbed": stubbed, "cpu_module": cpu_module,
                "cpu_sources_sha256": {p.name: sha256(p) for p in cpu_srcs},
                "top_sha256": sha256(directory / "alinx_ax7101.v"),
                "own_rom_sha256": sha256(gateware / "alinx_ax7101_rom.init")
                if (gateware / "alinx_ax7101_rom.init").is_file() else "",
                "read_rom_sha256": sha256(ship_rom), "tcl_sha256": sha256(directory / "soc_ooc.tcl")}
        (directory / "meta.json").write_text(json.dumps(meta, indent=1, sort_keys=True) + "\n")
        print(f"vivado-prep {name}: stubbed {stubbed}; cpu {cpu_module}")
    return 1 if failures else 0


def hierarchy_rows(path: Path) -> dict:
    sys.path.insert(0, str(REPO / "syn" / "ooc"))
    from pp_baseline_rank import hierarchy  # noqa: E402,PLC0415
    return hierarchy(path)


def command_collect() -> int:
    exports = json.loads((WORK / "exports.json").read_text())
    out = {}
    for name, record in exports.items():
        directory = WORK / "vivado" / name
        parameter, value, _spec = VARIANTS.get(name, ("shipping", "-", {}))
        entry = {"export": record, "parameter": parameter, "value": value, "x": X.get(name)}
        if record["rc"]:
            text = (WORK / "soc" / name / "export.log").read_text(errors="replace").splitlines()
            first = next((line for line in text if "Exception in thread" in line), "")
            record["reason"] = first.replace("[error] ", "").strip() or (record["error_tail"] or ["?"])[-1]
        if (directory / "meta.json").is_file():
            entry["meta"] = json.loads((directory / "meta.json").read_text())
        for stage in ("synth", "opt"):
            report = directory / f"{stage}_hierarchy.rpt"
            if report.is_file():
                rows = hierarchy_rows(report)
                root = next(k for k in rows if "/" not in k)
                cpu = f"{root}/{entry['meta']['cpu_module']}" if "meta" in entry else None
                cpu = cpu if cpu in rows else None
                entry[stage] = {"total": rows[root], "cpu_row": cpu, "cpu": rows[cpu] if cpu else None,
                                "report_sha256": sha256(report)}
        log = directory / "ooc.log"
        if log.is_file():
            entry["vivado"] = {"rc": int((directory / "ooc.log.rc").read_text()) if (directory / "ooc.log.rc").is_file() else None,
                               "log_sha256": sha256(log), "log_bytes": log.stat().st_size,
                               "start": (directory / "ooc.log.start").read_text().strip() if (directory / "ooc.log.start").is_file() else "",
                               "end": (directory / "ooc.log.end").read_text().strip() if (directory / "ooc.log.end").is_file() else ""}
        out[name] = entry
    (WORK / "soc_prices.json").write_text(json.dumps(out, indent=1, sort_keys=True) + "\n")
    print(f"collect: {len(out)} variants")
    return 0


def main() -> int:
    command, names = sys.argv[1], sys.argv[2:]
    if command == "prepare":
        return command_prepare()
    if command == "export":
        return command_export(names)
    if command == "vivado-prep":
        return command_vivado_prep(names)
    if command == "collect":
        return command_collect()
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main())
