#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Kebag Logic
# SPDX-License-Identifier: CERN-OHL-W-2.0
"""Generate docs/reference/TRACE_EVENTS.md from sw/trace/milan_trace.yaml.

`milan_trace.yaml` is the trace ABI. This renders it as a reader-facing
catalogue - every event type, every field, every enum value - so that "what is
being logged" is answerable without reading the YAML or decoding a trace, and
so the answer CANNOT drift from the contract: the doc is generated, and
`--check` fails when it is stale (same pattern as the traceability matrix).

The YAML carries more than structure: each event is preceded by a comment block
saying WHY it exists, and most fields carry a trailing comment. Both are lifted
into the table, because the reason an event exists is the part that decides
whether it can arm a trace export.

Usage:
    python3 sw/trace/gen_trace_events.py            # write the doc
    python3 sw/trace/gen_trace_events.py --check    # fail if stale
"""
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
YAML = REPO / "sw/trace/milan_trace.yaml"
OUT = REPO / "docs/reference/TRACE_EVENTS.md"


def load_yaml():
    import yaml

    class L(yaml.SafeLoader):
        pass

    # barectf tags its root mapping; we only want the plain data underneath
    L.add_multi_constructor(
        "tag:barectf.org", lambda ldr, suffix, node: ldr.construct_mapping(node, deep=True)
    )
    return yaml.load(YAML.read_text(), Loader=L)


def scrape_comments(text, event_names):
    """Lift the comment block above each event key, and each field's trailing
    comment. The YAML parser drops both, and they carry the intent."""
    lines = text.splitlines()
    ev_doc, fld_doc = {}, {}
    key_re = re.compile(r"^(\s+)([A-Za-z_][A-Za-z0-9_]*):\s*$")
    fld_re = re.compile(r"^\s*-\s*([A-Za-z_][A-Za-z0-9_]*)\s*:\s*\S+\s*#\s*(.+?)\s*$")

    for i, line in enumerate(lines):
        m = key_re.match(line)
        if m and m.group(2) in event_names:
            name, indent = m.group(2), len(m.group(1))
            block = []
            for j in range(i - 1, -1, -1):
                s = lines[j].strip()
                if not s.startswith("#"):
                    break
                if len(lines[j]) - len(lines[j].lstrip()) != indent:
                    break
                body = s.lstrip("#").strip()
                # skip the "-- 9 -----" section rules
                if body and not re.fullmatch(r"-{2,}\s*\d*\s*-*", body):
                    block.append(body)
            ev_doc[name] = " ".join(reversed(block)).strip()

        f = fld_re.match(line)
        if f:
            fld_doc.setdefault(f.group(1), f.group(2))
    return ev_doc, fld_doc


def type_label(alias, aliases):
    """Render a field's alias as something a reader can act on."""
    t = aliases.get(alias)
    if not isinstance(t, dict):
        return f"`{alias}`"
    cls = t.get("class", "")
    if "enumeration" in cls:
        return f"`{alias}` (enum)"
    if cls == "string":
        return f"`{alias}` (string)"
    if alias == "bool":
        return "`bool` (8-bit, 0/1)"
    size = t.get("size")
    # NB: "unsigned-integer" CONTAINS "signed" - test the prefix, not a substring
    signed = "signed" if cls.startswith("signed") else "unsigned"
    base = "hex" if t.get("preferred-display-base") == "hexadecimal" else "dec"
    return f"`{alias}` ({size}-bit {signed}, {base})"


def members_of(ft):
    if not isinstance(ft, dict):
        return []
    out = []
    for m in ft.get("members", []) or []:
        for k, v in m.items():
            out.append((k, v))
    return out


def render():
    d = load_yaml()
    text = YAML.read_text()
    ttype = d["trace"]["type"]
    aliases = ttype.get("$field-type-aliases") or ttype.get("field-type-aliases") or {}
    stream = ttype["data-stream-types"]["milan"]
    events = stream["event-record-types"]
    ev_doc, fld_doc = scrape_comments(text, set(events))
    common = members_of(stream.get("event-record-common-context-field-type"))

    L = []
    a = L.append
    a("<!-- GENERATED by sw/trace/gen_trace_events.py - DO NOT EDIT.")
    a("     Source of truth: sw/trace/milan_trace.yaml (the trace ABI).")
    a("     Regenerate: python3 sw/trace/gen_trace_events.py -->")
    a("")
    a("# What is being logged — the trace event catalogue")
    a("")
    a("Every event type the bare-metal end-station can write into its DRAM")
    a("fault-trace ring, what it carries, and why it exists. This page is **generated**")
    a("from [`sw/trace/milan_trace.yaml`](../../sw/trace/milan_trace.yaml), which is")
    a("the CTF ABI — so it cannot drift from what the producer actually emits.")
    a("")
    a("For the design (why a trace at all, the export budget, workstation")
    a("compression/rotation and torn captures) see")
    a("[`../design/TRACE_LOGGING.md`](../design/TRACE_LOGGING.md).")
    a("For how to read a trace, that document's *Reading a trace* section.")
    a("")
    a(f"**{len(events)} event types.** Every record also carries the common context")
    a("below, so severity and origin are answerable for any event without knowing")
    a("its type.")
    a("")
    a("How to read the tables: the *meaning* column is filled in only where the")
    a("field name is not the definition — most often to name the CSR register and")
    a("bit the value was read from, which is what lets a trace be checked against a")
    a("live board. A blank meaning is not missing documentation; it means the name")
    a("says it.")
    a("")

    a("## Common context — present on every record")
    a("")
    a("| field | type | meaning |")
    a("|---|---|---|")
    for name, alias in common:
        a(f"| `{name}` | {type_label(alias, aliases)} | {fld_doc.get(name, '')} |")
    a("")
    a("`sev` is not decoration: it **is** the flush trigger. A record at or above")
    a("the configured threshold is what promotes the DRAM ring to a segment export, so")
    a("choosing a severity also chooses whether the event can consume export budget.")
    a("")

    # --- the ID map: the ABI's least obvious property, made visible ---------
    # barectf assigns event-record type IDs by SORTED EVENT NAME, not by the
    # order they are declared in (barectf/config.py: `enumerate(sorted(...,
    # key=lambda evt: evt.name))`). That is stated in the YAML header as a rule
    # for changing the file, but the CONSEQUENCE - which id a raw trace will
    # show for a given event, and how far a new name would shift things - is
    # only visible as a table, and only correct if the table is derived the
    # same way barectf derives it. So derive it here rather than repeat the
    # rule in prose.
    decl = list(events)
    by_id = sorted(decl)
    a("## Event-record type IDs — and why declaration order is not it")
    a("")
    a("*Which numeric `id` will a raw trace show for a given event, and what")
    a("moves if I add one?* barectf assigns IDs by **sorted event name**, not by")
    a("declaration order. The two orders below are generated the same way")
    a("barectf generates them, so this table is the answer, not a restatement of")
    a("the rule.")
    a("")
    a("| id | event (sorted name = the ID order) | # in declaration order |")
    a("|---|---|---|")
    for i, name in enumerate(by_id):
        a(f"| `{i}` | `{name}` | {decl.index(name) + 1} |")
    a("")
    moved = sum(1 for i, name in enumerate(by_id) if decl.index(name) != i)
    a(f"{moved} of {len(decl)} events sit at a different position in the two")
    a("orders. **Adding one event renames the IDs of every event that sorts after")
    a("it** — an existing trace file decoded against the new `metadata` would be")
    a("read as the wrong events. That is why the YAML header treats a new event")
    a("name as an ABI change and not a cosmetic one.")
    a("")

    a("## Event types")
    a("")
    for i, (name, body) in enumerate(events.items()):
        a(f"### `{name}`")
        a("")
        why = ev_doc.get(name, "").strip()
        if why:
            a(why)
            a("")
        flds = members_of(body.get("payload-field-type"))
        if flds:
            a("| field | type | meaning |")
            a("|---|---|---|")
            for fname, falias in flds:
                a(f"| `{fname}` | {type_label(falias, aliases)} | {fld_doc.get(fname, '')} |")
        else:
            a("*No payload — the event's occurrence and its common context are the")
            a("whole signal.*")
        a("")

    enums = {k: v for k, v in aliases.items()
             if isinstance(v, dict) and "enumeration" in v.get("class", "")}
    if enums:
        a("## Enumerations")
        a("")
        a("Named values used by the fields above. A reader that does not know these")
        a("still decodes the trace — CTF carries them in the `metadata` document —")
        a("but these are the names you will see.")
        a("")
        for ename, et in enums.items():
            vals = et.get("mappings", {})
            pretty = ", ".join(
                f"`{k}` = {v[0] if isinstance(v, list) and v and not isinstance(v[0], list) else v}"
                for k, v in vals.items())
            a(f"* **`{ename}`** ({et.get('size')}-bit) — {pretty}")
        a("")

    a("## Changing this set")
    a("")
    a("`milan_trace.yaml` is an **ABI**: a trace outlives the build that wrote it,")
    a("and a reader decodes it with the `metadata` shipped alongside. The rules for")
    a("changing it are in the header of that file. Adding an event type is cheap;")
    a("renaming or re-typing a field is not. After any change, regenerate both the")
    a("barectf output and this page, and run")
    a("`python3 sw/trace/test_trace_roundtrip.py`.")
    return "\n".join(L) + "\n"


def main():
    check = "--check" in sys.argv[1:]
    try:
        new = render()
    except ImportError:
        print("gen_trace_events: pyyaml not installed - skipping", file=sys.stderr)
        return 0
    if check:
        if not OUT.exists():
            print(f"STALE (run gen_trace_events.py): {OUT.relative_to(REPO)} missing")
            return 1
        if OUT.read_text() != new:
            print(f"STALE (run gen_trace_events.py): {OUT.relative_to(REPO)}")
            return 1
        n = new.count("\n### `")
        print(f"trace event catalogue up to date ({n} event types)")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(new)
    print(f"wrote {OUT.relative_to(REPO)} ({new.count(chr(10) + '### `')} event types)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
