#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Kebag Logic
# SPDX-License-Identifier: CERN-OHL-W-2.0
"""Generate docs/reference/TRACE_EVENTS.md from sw/trace/milan_trace.yaml.

`milan_trace.yaml` is the trace ABI. This renders it as a reader-facing
catalogue - every event type, every field, every enum value - so that "what is
being logged" is answerable without reading the YAML or decoding a trace, and
so the answer CANNOT drift from the contract: the doc is generated, and
`--check` fails when it is stale (same pattern as the traceability matrix).

The YAML carries more than structure: each event is preceded by a comment block
saying WHY it exists, and most fields carry a trailing comment. Both are lifted
into the table, because the reason an event exists is the part that decides
whether it can arm a trace export.

Usage:
    python3 sw/trace/gen_trace_events.py            # write the doc
    python3 sw/trace/gen_trace_events.py --check    # fail if stale
"""
import re
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parent.parent.parent
YAML = REPO / "sw/trace/milan_trace.yaml"
OUT = REPO / "docs/reference/TRACE_EVENTS.md"


def load_yaml() -> dict[str, Any]:
    """The trace ABI as plain data. barectf tags its own mappings; the loader
    strips those tags so the file reads as the YAML it looks like."""
    import yaml

    class L(yaml.SafeLoader):
        pass

    # barectf tags its root mapping; we only want the plain data underneath
    L.add_multi_constructor(
        "tag:barectf.org", lambda ldr, suffix, node: ldr.construct_mapping(node, deep=True)
    )
    return yaml.load(YAML.read_text(), Loader=L)


def scrape_comments(text: str, event_names: set[str]) -> tuple[dict[str, str], dict[str, str]]:
    """Lift the comment block above each event key, and each field's trailing
    comment. The YAML parser drops both, and they carry the intent."""
    lines = text.splitlines()
    ev_doc, fld_doc = {}, {}
    key_re = re.compile(r"^(\s+)([A-Za-z_][A-Za-z0-9_]*):\s*$")
    fld_re = re.compile(r"^\s*-\s*([A-Za-z_][A-Za-z0-9_]*)\s*:\s*\S+\s*#\s*(.+?)\s*$")

    for i, line in enumerate(lines):
        m = key_re.match(line)
        if m and m.group(2) in event_names:
            name, indent = m.group(2), len(m.group(1))
            block = []
            for j in range(i - 1, -1, -1):
                s = lines[j].strip()
                if not s.startswith("#"):
                    break
                if len(lines[j]) - len(lines[j].lstrip()) != indent:
                    break
                body = s.lstrip("#").strip()
                # skip the "-- 9 -----" section rules
                if body and not re.fullmatch(r"-{2,}\s*\d*\s*-*", body):
                    block.append(body)
            ev_doc[name] = " ".join(reversed(block)).strip()

        f = fld_re.match(line)
        if f:
            fld_doc.setdefault(f.group(1), f.group(2))
    return ev_doc, fld_doc


def type_label(alias: str, aliases: dict[str, Any]) -> str:
    """Render a field's alias as something a reader can act on."""
    t = aliases.get(alias)
    if not isinstance(t, dict):
        return f"`{alias}`"
    cls = t.get("class", "")
    if "enumeration" in cls:
        return f"`{alias}` (enum)"
    if cls == "string":
        return f"`{alias}` (string)"
    if alias == "bool":
        return "`bool` (8-bit, 0/1)"
    size = t.get("size")
    # NB: "unsigned-integer" CONTAINS "signed" - test the prefix, not a substring
    signed = "signed" if cls.startswith("signed") else "unsigned"
    base = "hex" if t.get("preferred-display-base") == "hexadecimal" else "dec"
    return f"`{alias}` ({size}-bit {signed}, {base})"


def members_of(ft: object) -> list[tuple[str, str]]:
    """(field name, type alias) pairs of a structure field type. Anything that
    is not a mapping - a missing payload most often - has no members."""
    if not isinstance(ft, dict):
        return []
    out = []
    for m in ft.get("members", []) or []:
        for k, v in m.items():
            out.append((k, v))
    return out


def _intro_lines(n_events: int) -> list[str]:
    """The generated-file banner and the page's opening prose."""
    return [
        "<!-- GENERATED by sw/trace/gen_trace_events.py - DO NOT EDIT.",
        "     Source of truth: sw/trace/milan_trace.yaml (the trace ABI).",
        "     Regenerate: python3 sw/trace/gen_trace_events.py -->",
        "",
        "# What is being logged \u2014 the trace event catalogue",
        "",
        "Every event type the bare-metal end-station can write into its DRAM",
        "fault-trace ring, what it carries, and why it exists. This page is **generated**",
        "from [`sw/trace/milan_trace.yaml`](../../sw/trace/milan_trace.yaml), which is",
        "the CTF ABI \u2014 so it cannot drift from what the producer actually emits.",
        "",
        "For the design (why a trace at all, the export budget, workstation",
        "compression/rotation and torn captures) see",
        "[`../design/TRACE_LOGGING.md`](../design/TRACE_LOGGING.md).",
        "For how to read a trace, that document's *Reading a trace* section.",
        "",
        f"**{n_events} event types.** Every record also carries the common context",
        "below, so severity and origin are answerable for any event without knowing",
        "its type.",
        "",
        "How to read the tables: the *meaning* column is filled in only where the",
        "field name is not the definition \u2014 most often to name the CSR register and",
        "bit the value was read from, which is what lets a trace be checked against a",
        "live board. A blank meaning is not missing documentation; it means the name",
        "says it.",
        "",
    ]


def _common_context_lines(common: list[tuple[str, str]], aliases: dict[str, Any],
                          fld_doc: dict[str, str]) -> list[str]:
    """The table of fields every record carries, and what `sev` decides."""
    out = [
        "## Common context \u2014 present on every record",
        "",
        "| field | type | meaning |",
        "|---|---|---|",
    ]
    for name, alias in common:
        out.append(f"| `{name}` | {type_label(alias, aliases)} | {fld_doc.get(name, '')} |")
    out += [
        "",
        "`sev` is not decoration: it **is** the flush trigger. A record at or above",
        "the configured threshold is what promotes the DRAM ring to a segment export, so",
        "choosing a severity also chooses whether the event can consume export budget.",
        "",
    ]
    return out


def _id_map_lines(events: dict[str, Any]) -> list[str]:
    """The event-record type IDs, derived the way barectf derives them.

    barectf assigns event-record type IDs by SORTED EVENT NAME, not by the
    order they are declared in (barectf/config.py: `enumerate(sorted(...,
    key=lambda evt: evt.name))`). That is stated in the YAML header as a rule
    for changing the file, but the CONSEQUENCE - which id a raw trace will
    show for a given event, and how far a new name would shift things - is
    only visible as a table, and only correct if the table is derived the
    same way barectf derives it. So derive it here rather than repeat the
    rule in prose.
    """
    decl = list(events)
    by_id = sorted(decl)
    out = [
        "## Event-record type IDs \u2014 and why declaration order is not it",
        "",
        "*Which numeric `id` will a raw trace show for a given event, and what",
        "moves if I add one?* barectf assigns IDs by **sorted event name**, not by",
        "declaration order. The two orders below are generated the same way",
        "barectf generates them, so this table is the answer, not a restatement of",
        "the rule.",
        "",
        "| id | event (sorted name = the ID order) | # in declaration order |",
        "|---|---|---|",
    ]
    for i, name in enumerate(by_id):
        out.append(f"| `{i}` | `{name}` | {decl.index(name) + 1} |")
    moved = sum(1 for i, name in enumerate(by_id) if decl.index(name) != i)
    out += [
        "",
        f"{moved} of {len(decl)} events sit at a different position in the two",
        "orders. **Adding one event renames the IDs of every event that sorts after",
        "it** \u2014 an existing trace file decoded against the new `metadata` would be",
        "read as the wrong events. That is why the YAML header treats a new event",
        "name as an ABI change and not a cosmetic one.",
        "",
    ]
    return out


def _event_type_lines(events: dict[str, Any], aliases: dict[str, Any],
                      ev_doc: dict[str, str], fld_doc: dict[str, str]) -> list[str]:
    """One section per event type: why it exists, then its payload table."""
    out = ["## Event types", ""]
    for name, body in events.items():
        out.append(f"### `{name}`")
        out.append("")
        why = ev_doc.get(name, "").strip()
        if why:
            out.append(why)
            out.append("")
        flds = members_of(body.get("payload-field-type"))
        if flds:
            out.append("| field | type | meaning |")
            out.append("|---|---|---|")
            for fname, falias in flds:
                out.append(
                    f"| `{fname}` | {type_label(falias, aliases)} | {fld_doc.get(fname, '')} |")
        else:
            out.append("*No payload \u2014 the event's occurrence and its common context are the")
            out.append("whole signal.*")
        out.append("")
    return out


def _enumeration_lines(aliases: dict[str, Any]) -> list[str]:
    """The named values the field tables refer to, or nothing when there are none."""
    enums = {k: v for k, v in aliases.items()
             if isinstance(v, dict) and "enumeration" in v.get("class", "")}
    if not enums:
        return []
    out = [
        "## Enumerations",
        "",
        "Named values used by the fields above. A reader that does not know these",
        "still decodes the trace \u2014 CTF carries them in the `metadata` document \u2014",
        "but these are the names you will see.",
        "",
    ]
    for ename, et in enums.items():
        vals = et.get("mappings", {})
        pretty = ", ".join(
            f"`{k}` = {v[0] if isinstance(v, list) and v and not isinstance(v[0], list) else v}"
            for k, v in vals.items())
        out.append(f"* **`{ename}`** ({et.get('size')}-bit) \u2014 {pretty}")
    out.append("")
    return out


def _changing_this_set_lines() -> list[str]:
    """The closing section: what changing the ABI costs, and what to re-run."""
    return [
        "## Changing this set",
        "",
        "`milan_trace.yaml` is an **ABI**: a trace outlives the build that wrote it,",
        "and a reader decodes it with the `metadata` shipped alongside. The rules for",
        "changing it are in the header of that file. Adding an event type is cheap;",
        "renaming or re-typing a field is not. After any change, regenerate both the",
        "barectf output and this page, and run",
        "`python3 sw/trace/test_trace_roundtrip.py`.",
    ]


def render() -> str:
    """The whole catalogue page, assembled from the YAML and the comments the
    YAML parser threw away."""
    d = load_yaml()
    text = YAML.read_text()
    ttype = d["trace"]["type"]
    aliases = ttype.get("$field-type-aliases") or ttype.get("field-type-aliases") or {}
    stream = ttype["data-stream-types"]["milan"]
    events = stream["event-record-types"]
    ev_doc, fld_doc = scrape_comments(text, set(events))
    common = members_of(stream.get("event-record-common-context-field-type"))

    out = (_intro_lines(len(events))
           + _common_context_lines(common, aliases, fld_doc)
           + _id_map_lines(events)
           + _event_type_lines(events, aliases, ev_doc, fld_doc)
           + _enumeration_lines(aliases)
           + _changing_this_set_lines())
    return "\n".join(out) + "\n"


def main() -> int:
    """Write the catalogue, or under --check fail when it no longer matches the
    ABI. Without pyyaml there is nothing to compare against, so the check is
    skipped rather than reported as a pass or a failure."""
    check = "--check" in sys.argv[1:]
    try:
        new = render()
    except ImportError:
        print("gen_trace_events: pyyaml not installed - skipping", file=sys.stderr)
        return 0
    if check:
        if not OUT.exists():
            print(f"STALE (run gen_trace_events.py): {OUT.relative_to(REPO)} missing")
            return 1
        if OUT.read_text() != new:
            print(f"STALE (run gen_trace_events.py): {OUT.relative_to(REPO)}")
            return 1
        n = new.count("\n### `")
        print(f"trace event catalogue up to date ({n} event types)")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(new)
    print(f"wrote {OUT.relative_to(REPO)} ({new.count(chr(10) + '### `')} event types)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
