// SPDX-FileCopyrightText: 2026 Kebag Logic
// SPDX-License-Identifier: CERN-OHL-W-2.0
//
// GENERATED by sw/mailbox/gen_mailbox.py from sw/mailbox/mailbox.yaml; DO NOT EDIT.
// Regenerate with: python3 sw/mailbox/gen_mailbox.py --write
//
// sw/firmware/ctrl/mbx/mbx_contract.h: the packet-mailbox contract (#665 lane F0).
//
// Every constant is `MBX_<name>`, the SystemVerilog package's
// `MBX_<name>_C`. The *_TBL macros are brace initialisers listing those
// names by channel id, for code that indexes a channel at run time.

#ifndef MBX_CONTRACT_H
#define MBX_CONTRACT_H

/* contract major version */
#define MBX_VERSION_MAJOR 1u
/* contract minor version */
#define MBX_VERSION_MINOR 0u
/* ID.MAGIC */
#define MBX_MAGIC 0x4D42u
/* host window size */
#define MBX_WINDOW_BYTES 0x8000u
/* registers live below this offset */
#define MBX_REGISTER_SPACE_BYTES 0x400u
/* interfaces */
#define MBX_N_IF 1u
/* timer slots */
#define MBX_N_TIMERS 16u
/* NOW_MS milliseconds per TICK (one centisecond) */
#define MBX_TICK_MS 10u
/* channels */
#define MBX_N_CH 5u
/* ring counter width */
#define MBX_INDEX_BITS 16u
/* accept terms per channel */
#define MBX_MAX_TERMS 2u
/* bytes a filter term reads */
#define MBX_TERM_FIELD_BYTES 8u
/* wire byte of the EtherType */
#define MBX_ETHERTYPE_BYTE 12u
/* wire byte of the AVTP subtype */
#define MBX_SUBTYPE_BYTE 14u
/* wire byte whose low nibble is message_type */
#define MBX_MSG_TYPE_BYTE 15u
/* never (an unused term) */
#define MBX_TEST_NONE 0u
/* always */
#define MBX_TEST_ANY 1u
/* the 8-byte big-endian field equals OWN_EID */
#define MBX_TEST_EQ_OWN 2u
/* the 8-byte field is 0 */
#define MBX_TEST_EQ_ZERO 3u
/* the 6-byte start and 2-byte count overlap [MAAP_BASE, MAAP_BASE + MAAP_COUNT - 1] */
#define MBX_TEST_RANGE_OVERLAP 4u
/* TMR_CMD.OP arm */
#define MBX_TMR_OP_ARM 1u
/* TMR_CMD.OP cancel */
#define MBX_TMR_OP_CANCEL 2u
/* Contract identity. Firmware checks MAGIC and MAJOR before it opens a channel. */
#define MBX_REG_ID 0x0u
/* ID: contract minor version */
#define MBX_ID_MINOR_LSB 0u
/* ID: contract minor version */
#define MBX_ID_MINOR_WIDTH 8u
/* ID: contract major version */
#define MBX_ID_MAJOR_LSB 8u
/* ID: contract major version */
#define MBX_ID_MAJOR_WIDTH 8u
/* ID: 0x4D42 */
#define MBX_ID_MAGIC_LSB 16u
/* ID: 0x4D42 */
#define MBX_ID_MAGIC_WIDTH 16u
/* What this build elaborated. */
#define MBX_REG_CAPS 0x4u
/* CAPS: channel count */
#define MBX_CAPS_N_CH_LSB 0u
/* CAPS: channel count */
#define MBX_CAPS_N_CH_WIDTH 4u
/* CAPS: interface count */
#define MBX_CAPS_N_IF_LSB 4u
/* CAPS: interface count */
#define MBX_CAPS_N_IF_WIDTH 4u
/* CAPS: timer slots */
#define MBX_CAPS_N_TIMERS_LSB 8u
/* CAPS: timer slots */
#define MBX_CAPS_N_TIMERS_WIDTH 8u
/* CAPS: event ring size */
#define MBX_CAPS_EVT_WORDS_LOG2_LSB 16u
/* CAPS: event ring size */
#define MBX_CAPS_EVT_WORDS_LOG2_WIDTH 4u
/* The interrupt causes. RX and EVT are levels: they stay set while the ring holds an unconsumed record and clear when the core advances its tail. ERR is sticky and cleared by writing 1. */
#define MBX_REG_IRQ_STATUS 0x8u
/* IRQ_STATUS: bit c: channel c's receive ring is not empty (level) */
#define MBX_IRQ_STATUS_RX_LSB 0u
/* IRQ_STATUS: bit c: channel c's receive ring is not empty (level) */
#define MBX_IRQ_STATUS_RX_WIDTH 8u
/* IRQ_STATUS: the event ring is not empty (level) */
#define MBX_IRQ_STATUS_EVT_LSB 8u
/* IRQ_STATUS: the event ring is not empty (level) */
#define MBX_IRQ_STATUS_EVT_WIDTH 1u
/* IRQ_STATUS: a drop or error counter moved (sticky */
#define MBX_IRQ_STATUS_ERR_LSB 31u
/* IRQ_STATUS: a drop or error counter moved (sticky */
#define MBX_IRQ_STATUS_ERR_WIDTH 1u
/* The interrupt line is the OR of IRQ_STATUS AND IRQ_ENABLE. Reset 0. */
#define MBX_REG_IRQ_ENABLE 0xCu
/* IRQ_ENABLE: per-channel enable */
#define MBX_IRQ_ENABLE_RX_LSB 0u
/* IRQ_ENABLE: per-channel enable */
#define MBX_IRQ_ENABLE_RX_WIDTH 8u
/* IRQ_ENABLE: event ring enable */
#define MBX_IRQ_ENABLE_EVT_LSB 8u
/* IRQ_ENABLE: event ring enable */
#define MBX_IRQ_ENABLE_EVT_WIDTH 1u
/* IRQ_ENABLE: error enable */
#define MBX_IRQ_ENABLE_ERR_LSB 31u
/* IRQ_ENABLE: error enable */
#define MBX_IRQ_ENABLE_ERR_WIDTH 1u
/* Free-running fabric millisecond counter, the time base of every timer deadline. */
#define MBX_REG_NOW_MS 0x10u
/* NOW_MS: milliseconds since reset */
#define MBX_NOW_MS_MS_LSB 0u
/* NOW_MS: milliseconds since reset */
#define MBX_NOW_MS_MS_WIDTH 32u
/* Current link level per interface. */
#define MBX_REG_LINK 0x14u
/* LINK: bit i: interface i link up */
#define MBX_LINK_UP_LSB 0u
/* LINK: bit i: interface i link up */
#define MBX_LINK_UP_WIDTH 4u
/* The centisecond tick. Reset 0. While EN is set the fabric counts one tick every tick_ms milliseconds of NOW_MS and posts TICK events carrying the ticks elapsed since the previous TICK record, so the firmware calls its centisecond timer port (lwSRP's shlan_timer_tick) once per tick counted and loses none when it is late. Clearing EN drops the unposted count. */
#define MBX_REG_TICK_CTL 0x18u
/* TICK_CTL: post TICK events */
#define MBX_TICK_CTL_EN_LSB 0u
/* TICK_CTL: post TICK events */
#define MBX_TICK_CTL_EN_WIDTH 1u
/* The filter's entity_id, low word. Reset 0; firmware writes it before it opens a channel. */
#define MBX_REG_OWN_EID_LO 0x20u
/* OWN_EID_LO: entity_id[31:0] */
#define MBX_OWN_EID_LO_EID_LSB 0u
/* OWN_EID_LO: entity_id[31:0] */
#define MBX_OWN_EID_LO_EID_WIDTH 32u
/* The filter's entity_id, high word. */
#define MBX_REG_OWN_EID_HI 0x24u
/* OWN_EID_HI: entity_id[63:32] */
#define MBX_OWN_EID_HI_EID_LSB 0u
/* OWN_EID_HI: entity_id[63:32] */
#define MBX_OWN_EID_HI_EID_WIDTH 32u
/* Bit c opens channel c. Reset 0: every channel is closed and its frames are dropped uncounted until the firmware has written OWN_EID and opened it. */
#define MBX_REG_FILTER_EN 0x28u
/* FILTER_EN: per-channel open */
#define MBX_FILTER_EN_OPEN_LSB 0u
/* FILTER_EN: per-channel open */
#define MBX_FILTER_EN_OPEN_WIDTH 8u
/* The MAAP range this entity probes or holds, low 32 bits of the first address. */
#define MBX_REG_MAAP_BASE_LO 0x2Cu
/* MAAP_BASE_LO: first address[31:0] */
#define MBX_MAAP_BASE_LO_ADDR_LSB 0u
/* MAAP_BASE_LO: first address[31:0] */
#define MBX_MAAP_BASE_LO_ADDR_WIDTH 32u
/* The MAAP range, high 16 bits of the first address. */
#define MBX_REG_MAAP_BASE_HI 0x30u
/* MAAP_BASE_HI: first address[47:32] */
#define MBX_MAAP_BASE_HI_ADDR_LSB 0u
/* MAAP_BASE_HI: first address[47:32] */
#define MBX_MAAP_BASE_HI_ADDR_WIDTH 16u
/* Addresses in the MAAP range. 0 means no range, and no MAAP frame passes. */
#define MBX_REG_MAAP_COUNT 0x34u
/* MAAP_COUNT: address count */
#define MBX_MAAP_COUNT_COUNT_LSB 0u
/* MAAP_COUNT: address count */
#define MBX_MAAP_COUNT_COUNT_WIDTH 16u
/* The deadline the next TMR_CMD arm uses, in NOW_MS units. */
#define MBX_REG_TMR_DEADLINE 0x38u
/* TMR_DEADLINE: absolute deadline */
#define MBX_TMR_DEADLINE_MS_LSB 0u
/* TMR_DEADLINE: absolute deadline */
#define MBX_TMR_DEADLINE_MS_WIDTH 32u
/* A write arms or cancels one timer slot. An arm replaces whatever the slot held and drops its unposted expiry; a cancel disarms it and drops its unposted expiry. An expiry already in the event ring stays there and carries the tag of the arm it belongs to. Any other OP is refused and counted in BUS_ERR. */
#define MBX_REG_TMR_CMD 0x3Cu
/* TMR_CMD: timer slot */
#define MBX_TMR_CMD_SLOT_LSB 0u
/* TMR_CMD: timer slot */
#define MBX_TMR_CMD_SLOT_WIDTH 8u
/* TMR_CMD: firmware tag */
#define MBX_TMR_CMD_TAG_LSB 8u
/* TMR_CMD: firmware tag */
#define MBX_TMR_CMD_TAG_WIDTH 16u
/* TMR_CMD: 1 arm, 2 cancel */
#define MBX_TMR_CMD_OP_LSB 30u
/* TMR_CMD: 1 arm, 2 cancel */
#define MBX_TMR_CMD_OP_WIDTH 2u
/* Words the fabric has written into the event ring, modulo 2^16. */
#define MBX_REG_EVT_HEAD 0x60u
/* EVT_HEAD: producer count */
#define MBX_EVT_HEAD_WORDS_LSB 0u
/* EVT_HEAD: producer count */
#define MBX_EVT_HEAD_WORDS_WIDTH 16u
/* Words the core has consumed from the event ring. Writing it releases the space. */
#define MBX_REG_EVT_TAIL 0x64u
/* EVT_TAIL: consumer count */
#define MBX_EVT_TAIL_WORDS_LSB 0u
/* EVT_TAIL: consumer count */
#define MBX_EVT_TAIL_WORDS_WIDTH 16u
/* Host accesses refused, saturating. A write with a partial byte strobe and a bad TMR_CMD are refused. */
#define MBX_REG_BUS_ERR 0x70u
/* BUS_ERR: refusals */
#define MBX_BUS_ERR_COUNT_LSB 0u
/* BUS_ERR: refusals */
#define MBX_BUS_ERR_COUNT_WIDTH 16u
/* first interface register block */
#define MBX_IF_BASE 0x40u
/* bytes per interface block */
#define MBX_IF_STRIDE 0x10u
/* Grandmaster identity, low word. Reading it snapshots GM_HI and DOMAIN, so the next two reads are coherent with it (the CSR window's convention). */
#define MBX_IF_REG_GM_LO 0x0u
/* GM_LO: gptp_grandmaster_id[31:0] */
#define MBX_GM_LO_ID_LSB 0u
/* GM_LO: gptp_grandmaster_id[31:0] */
#define MBX_GM_LO_ID_WIDTH 32u
/* Grandmaster identity, high word, from the snapshot. */
#define MBX_IF_REG_GM_HI 0x4u
/* GM_HI: gptp_grandmaster_id[63:32] */
#define MBX_GM_HI_ID_LSB 0u
/* GM_HI: gptp_grandmaster_id[63:32] */
#define MBX_GM_HI_ID_WIDTH 32u
/* gPTP domain number, from the snapshot. */
#define MBX_IF_REG_DOMAIN 0x8u
/* DOMAIN: gptp_domain_number */
#define MBX_DOMAIN_NUMBER_LSB 0u
/* DOMAIN: gptp_domain_number */
#define MBX_DOMAIN_NUMBER_WIDTH 8u
/* first channel register block */
#define MBX_CH_BASE 0x100u
/* bytes per channel block */
#define MBX_CH_STRIDE 0x20u
/* Words the fabric has committed into the receive ring, modulo 2^16. */
#define MBX_CH_REG_RX_HEAD 0x0u
/* RX_HEAD: producer count */
#define MBX_RX_HEAD_WORDS_LSB 0u
/* RX_HEAD: producer count */
#define MBX_RX_HEAD_WORDS_WIDTH 16u
/* Words the core has consumed. Writing it releases the space (the RX doorbell). */
#define MBX_CH_REG_RX_TAIL 0x4u
/* RX_TAIL: consumer count */
#define MBX_RX_TAIL_WORDS_LSB 0u
/* RX_TAIL: consumer count */
#define MBX_RX_TAIL_WORDS_WIDTH 16u
/* Words the core has committed into the transmit ring. Writing it is the TX doorbell. */
#define MBX_CH_REG_TX_HEAD 0x8u
/* TX_HEAD: producer count */
#define MBX_TX_HEAD_WORDS_LSB 0u
/* TX_HEAD: producer count */
#define MBX_TX_HEAD_WORDS_WIDTH 16u
/* Words the fabric has consumed from the transmit ring. */
#define MBX_CH_REG_TX_TAIL 0xCu
/* TX_TAIL: consumer count */
#define MBX_TX_TAIL_WORDS_LSB 0u
/* TX_TAIL: consumer count */
#define MBX_TX_TAIL_WORDS_WIDTH 16u
/* Frames the channel accepted but could not store (ring full or over max_frame_bytes), saturating. */
#define MBX_CH_REG_RX_DROP 0x10u
/* RX_DROP: frames */
#define MBX_RX_DROP_COUNT_LSB 0u
/* RX_DROP: frames */
#define MBX_RX_DROP_COUNT_WIDTH 16u
/* Frames the channel's rate limiter refused, saturating. */
#define MBX_CH_REG_RATE_DROP 0x14u
/* RATE_DROP: frames */
#define MBX_RATE_DROP_COUNT_LSB 0u
/* RATE_DROP: frames */
#define MBX_RATE_DROP_COUNT_WIDTH 16u
/* TX records the fabric refused, saturating. A refused record flushes the ring to TX_HEAD. */
#define MBX_CH_REG_TX_ERR 0x18u
/* TX_ERR: records */
#define MBX_TX_ERR_COUNT_LSB 0u
/* TX_ERR: records */
#define MBX_TX_ERR_COUNT_WIDTH 16u
/* Frames committed into the receive ring, modulo 2^16. */
#define MBX_CH_REG_RX_PASS 0x1Cu
/* RX_PASS: frames */
#define MBX_RX_PASS_COUNT_LSB 0u
/* RX_PASS: frames */
#define MBX_RX_PASS_COUNT_WIDTH 16u
/* KIND of an RX frame record */
#define MBX_RX_KIND 1u
/* header words of an RX record */
#define MBX_RX_HDR_WORDS 2u
/* KIND of a TX frame record */
#define MBX_TX_KIND 2u
/* header words of a TX record */
#define MBX_TX_HDR_WORDS 2u
/* words per event record */
#define MBX_EV_WORDS 4u
/* event ring byte offset */
#define MBX_EVT_BASE 0x400u
/* event ring words */
#define MBX_EVT_WORDS 64u
/* RX record word 0: frame bytes */
#define MBX_RXREC_W0_LEN_LSB 0u
/* RX record word 0: frame bytes */
#define MBX_RXREC_W0_LEN_WIDTH 16u
/* RX record word 0: interface the frame arrived on */
#define MBX_RXREC_W0_IF_LSB 16u
/* RX record word 0: interface the frame arrived on */
#define MBX_RXREC_W0_IF_WIDTH 4u
/* RX record word 0: 1 */
#define MBX_RXREC_W0_KIND_LSB 28u
/* RX record word 0: 1 */
#define MBX_RXREC_W0_KIND_WIDTH 4u
/* RX record word 1: NOW_MS when the frame's last byte arrived */
#define MBX_RXREC_W1_ARRIVAL_MS_LSB 0u
/* RX record word 1: NOW_MS when the frame's last byte arrived */
#define MBX_RXREC_W1_ARRIVAL_MS_WIDTH 32u
/* TX record word 0: frame bytes */
#define MBX_TXREC_W0_LEN_LSB 0u
/* TX record word 0: frame bytes */
#define MBX_TXREC_W0_LEN_WIDTH 16u
/* TX record word 0: interface to send on */
#define MBX_TXREC_W0_IF_LSB 16u
/* TX record word 0: interface to send on */
#define MBX_TXREC_W0_IF_WIDTH 4u
/* TX record word 0: 2 */
#define MBX_TXREC_W0_KIND_LSB 28u
/* TX record word 0: 2 */
#define MBX_TXREC_W0_KIND_WIDTH 4u
/* TX record word 1: commit sequence: the core's count of TX records committed on every channel, modulo 2^16 */
#define MBX_TXREC_W1_SEQ_LSB 0u
/* TX record word 1: commit sequence: the core's count of TX records committed on every channel, modulo 2^16 */
#define MBX_TXREC_W1_SEQ_WIDTH 16u
/* TX record word 1: must be 0; any other value refuses the record */
#define MBX_TXREC_W1_RSVD_LSB 16u
/* TX record word 1: must be 0; any other value refuses the record */
#define MBX_TXREC_W1_RSVD_WIDTH 16u
/* event word 0: event type */
#define MBX_EVREC_W0_TYPE_LSB 0u
/* event word 0: event type */
#define MBX_EVREC_W0_TYPE_WIDTH 8u
/* event word 0: interface */
#define MBX_EVREC_W0_IF_LSB 8u
/* event word 0: interface */
#define MBX_EVREC_W0_IF_WIDTH 4u
/* event word 0: posting sequence */
#define MBX_EVREC_W0_SEQ_LSB 16u
/* event word 0: posting sequence */
#define MBX_EVREC_W0_SEQ_WIDTH 16u
/* A timer slot's deadline passed. */
#define MBX_EV_TYPE_TIMER 1u
/* TIMER event word 1: the tag of the arm that expired */
#define MBX_EV_TIMER_W1_TAG_LSB 0u
/* TIMER event word 1: the tag of the arm that expired */
#define MBX_EV_TIMER_W1_TAG_WIDTH 16u
/* TIMER event word 1: timer slot */
#define MBX_EV_TIMER_W1_SLOT_LSB 16u
/* TIMER event word 1: timer slot */
#define MBX_EV_TIMER_W1_SLOT_WIDTH 8u
/* TIMER event word 2: the armed deadline */
#define MBX_EV_TIMER_W2_DEADLINE_MS_LSB 0u
/* TIMER event word 2: the armed deadline */
#define MBX_EV_TIMER_W2_DEADLINE_MS_WIDTH 32u
/* TIMER event word 3: NOW_MS at posting */
#define MBX_EV_TIMER_W3_NOW_MS_LSB 0u
/* TIMER event word 3: NOW_MS at posting */
#define MBX_EV_TIMER_W3_NOW_MS_WIDTH 32u
/* The interface's link level changed. */
#define MBX_EV_TYPE_LINK 2u
/* LINK event word 1: link level at posting */
#define MBX_EV_LINK_W1_UP_LSB 0u
/* LINK event word 1: link level at posting */
#define MBX_EV_LINK_W1_UP_WIDTH 1u
/* LINK event word 3: NOW_MS at posting */
#define MBX_EV_LINK_W3_NOW_MS_LSB 0u
/* LINK event word 3: NOW_MS at posting */
#define MBX_EV_LINK_W3_NOW_MS_WIDTH 32u
/* The gPTP plane published a grandmaster change on the interface. */
#define MBX_EV_TYPE_GM 3u
/* GM event word 1: gptp_grandmaster_id[31:0] at posting */
#define MBX_EV_GM_W1_ID_LO_LSB 0u
/* GM event word 1: gptp_grandmaster_id[31:0] at posting */
#define MBX_EV_GM_W1_ID_LO_WIDTH 32u
/* GM event word 2: gptp_grandmaster_id[63:32] at posting */
#define MBX_EV_GM_W2_ID_HI_LSB 0u
/* GM event word 2: gptp_grandmaster_id[63:32] at posting */
#define MBX_EV_GM_W2_ID_HI_WIDTH 32u
/* GM event word 3: gptp_domain_number at posting */
#define MBX_EV_GM_W3_DOMAIN_LSB 0u
/* GM event word 3: gptp_domain_number at posting */
#define MBX_EV_GM_W3_DOMAIN_WIDTH 8u
/* Centiseconds elapsed (TICK_CTL.EN set). COUNT is the ticks counted since the previous TICK record, at least 1 and saturating; the firmware calls its centisecond timer port COUNT times. */
#define MBX_EV_TYPE_TICK 4u
/* TICK event word 1: ticks since the previous TICK record */
#define MBX_EV_TICK_W1_COUNT_LSB 0u
/* TICK event word 1: ticks since the previous TICK record */
#define MBX_EV_TICK_W1_COUNT_WIDTH 16u
/* TICK event word 3: NOW_MS at posting */
#define MBX_EV_TICK_W3_NOW_MS_LSB 0u
/* TICK event word 3: NOW_MS at posting */
#define MBX_EV_TICK_W3_NOW_MS_WIDTH 32u
/* channel adp */
#define MBX_CH_ADP 0u
/* adp receive ring byte offset */
#define MBX_CH_ADP_RX_BASE 0x1000u
/* adp receive ring words */
#define MBX_CH_ADP_RX_WORDS 256u
/* adp transmit ring byte offset */
#define MBX_CH_ADP_TX_BASE 0x1400u
/* adp transmit ring words */
#define MBX_CH_ADP_TX_WORDS 128u
/* adp largest frame */
#define MBX_CH_ADP_MAX_FRAME_BYTES 128u
/* adp EtherType */
#define MBX_CH_ADP_ETHERTYPE0 0x22F0u
/* adp second EtherType */
#define MBX_CH_ADP_ETHERTYPE1 0x22F0u
/* adp matches a subtype */
#define MBX_CH_ADP_HAS_SUBTYPE 1u
/* adp AVTP subtype */
#define MBX_CH_ADP_SUBTYPE 0xFAu
/* adp token bucket depth */
#define MBX_CH_ADP_RATE_BURST 8u
/* adp ms per refilled token */
#define MBX_CH_ADP_RATE_REFILL_MS 10u
/* adp term 0: ENTITY_DISCOVER for every entity (Milan v1.2 5.6.3.1 step 2) */
#define MBX_CH_ADP_T0_TEST 3u
/* adp term 0 field byte */
#define MBX_CH_ADP_T0_OFFSET 18u
/* adp term 0 message types */
#define MBX_CH_ADP_T0_MSG_MASK 0x4u
/* adp term 1: ENTITY_DISCOVER for this entity (Milan v1.2 5.6.3.1 step 2) */
#define MBX_CH_ADP_T1_TEST 2u
/* adp term 1 field byte */
#define MBX_CH_ADP_T1_OFFSET 18u
/* adp term 1 message types */
#define MBX_CH_ADP_T1_MSG_MASK 0x4u
/* channel acmp */
#define MBX_CH_ACMP 1u
/* acmp receive ring byte offset */
#define MBX_CH_ACMP_RX_BASE 0x1800u
/* acmp receive ring words */
#define MBX_CH_ACMP_RX_WORDS 256u
/* acmp transmit ring byte offset */
#define MBX_CH_ACMP_TX_BASE 0x1C00u
/* acmp transmit ring words */
#define MBX_CH_ACMP_TX_WORDS 256u
/* acmp largest frame */
#define MBX_CH_ACMP_MAX_FRAME_BYTES 128u
/* acmp EtherType */
#define MBX_CH_ACMP_ETHERTYPE0 0x22F0u
/* acmp second EtherType */
#define MBX_CH_ACMP_ETHERTYPE1 0x22F0u
/* acmp matches a subtype */
#define MBX_CH_ACMP_HAS_SUBTYPE 1u
/* acmp AVTP subtype */
#define MBX_CH_ACMP_SUBTYPE 0xFCu
/* acmp token bucket depth */
#define MBX_CH_ACMP_RATE_BURST 16u
/* acmp ms per refilled token */
#define MBX_CH_ACMP_RATE_REFILL_MS 5u
/* acmp term 0: a command or response addressed to this entity's talker */
#define MBX_CH_ACMP_T0_TEST 2u
/* acmp term 0 field byte */
#define MBX_CH_ACMP_T0_OFFSET 34u
/* acmp term 0 message types */
#define MBX_CH_ACMP_T0_MSG_MASK 0xFFFFu
/* acmp term 1: a command or response addressed to this entity's listener */
#define MBX_CH_ACMP_T1_TEST 2u
/* acmp term 1 field byte */
#define MBX_CH_ACMP_T1_OFFSET 42u
/* acmp term 1 message types */
#define MBX_CH_ACMP_T1_MSG_MASK 0xFFFFu
/* channel aecp */
#define MBX_CH_AECP 2u
/* aecp receive ring byte offset */
#define MBX_CH_AECP_RX_BASE 0x2000u
/* aecp receive ring words */
#define MBX_CH_AECP_RX_WORDS 512u
/* aecp transmit ring byte offset */
#define MBX_CH_AECP_TX_BASE 0x2800u
/* aecp transmit ring words */
#define MBX_CH_AECP_TX_WORDS 512u
/* aecp largest frame */
#define MBX_CH_AECP_MAX_FRAME_BYTES 1514u
/* aecp EtherType */
#define MBX_CH_AECP_ETHERTYPE0 0x22F0u
/* aecp second EtherType */
#define MBX_CH_AECP_ETHERTYPE1 0x22F0u
/* aecp matches a subtype */
#define MBX_CH_AECP_HAS_SUBTYPE 1u
/* aecp AVTP subtype */
#define MBX_CH_AECP_SUBTYPE 0xFBu
/* aecp token bucket depth */
#define MBX_CH_AECP_RATE_BURST 16u
/* aecp ms per refilled token */
#define MBX_CH_AECP_RATE_REFILL_MS 5u
/* aecp term 0: a command addressed to this entity */
#define MBX_CH_AECP_T0_TEST 2u
/* aecp term 0 field byte */
#define MBX_CH_AECP_T0_OFFSET 18u
/* aecp term 0 message types */
#define MBX_CH_AECP_T0_MSG_MASK 0xFFFFu
/* aecp term 1: unused */
#define MBX_CH_AECP_T1_TEST 0u
/* aecp term 1 field byte */
#define MBX_CH_AECP_T1_OFFSET 0u
/* aecp term 1 message types */
#define MBX_CH_AECP_T1_MSG_MASK 0x0u
/* channel maap */
#define MBX_CH_MAAP 3u
/* maap receive ring byte offset */
#define MBX_CH_MAAP_RX_BASE 0x3000u
/* maap receive ring words */
#define MBX_CH_MAAP_RX_WORDS 128u
/* maap transmit ring byte offset */
#define MBX_CH_MAAP_TX_BASE 0x3200u
/* maap transmit ring words */
#define MBX_CH_MAAP_TX_WORDS 128u
/* maap largest frame */
#define MBX_CH_MAAP_MAX_FRAME_BYTES 64u
/* maap EtherType */
#define MBX_CH_MAAP_ETHERTYPE0 0x22F0u
/* maap second EtherType */
#define MBX_CH_MAAP_ETHERTYPE1 0x22F0u
/* maap matches a subtype */
#define MBX_CH_MAAP_HAS_SUBTYPE 1u
/* maap AVTP subtype */
#define MBX_CH_MAAP_SUBTYPE 0xFEu
/* maap token bucket depth */
#define MBX_CH_MAAP_RATE_BURST 8u
/* maap ms per refilled token */
#define MBX_CH_MAAP_RATE_REFILL_MS 20u
/* maap term 0: a PROBE, DEFEND or ANNOUNCE whose requested range conflicts with this entity's range */
#define MBX_CH_MAAP_T0_TEST 4u
/* maap term 0 field byte */
#define MBX_CH_MAAP_T0_OFFSET 26u
/* maap term 0 message types */
#define MBX_CH_MAAP_T0_MSG_MASK 0xEu
/* maap term 1: unused */
#define MBX_CH_MAAP_T1_TEST 0u
/* maap term 1 field byte */
#define MBX_CH_MAAP_T1_OFFSET 0u
/* maap term 1 message types */
#define MBX_CH_MAAP_T1_MSG_MASK 0x0u
/* channel srp */
#define MBX_CH_SRP 4u
/* srp receive ring byte offset */
#define MBX_CH_SRP_RX_BASE 0x4000u
/* srp receive ring words */
#define MBX_CH_SRP_RX_WORDS 1024u
/* srp transmit ring byte offset */
#define MBX_CH_SRP_TX_BASE 0x5000u
/* srp transmit ring words */
#define MBX_CH_SRP_TX_WORDS 512u
/* srp largest frame */
#define MBX_CH_SRP_MAX_FRAME_BYTES 1514u
/* srp EtherType */
#define MBX_CH_SRP_ETHERTYPE0 0x22EAu
/* srp second EtherType */
#define MBX_CH_SRP_ETHERTYPE1 0x88F5u
/* srp matches a subtype */
#define MBX_CH_SRP_HAS_SUBTYPE 0u
/* srp AVTP subtype */
#define MBX_CH_SRP_SUBTYPE 0x0u
/* srp token bucket depth */
#define MBX_CH_SRP_RATE_BURST 32u
/* srp ms per refilled token */
#define MBX_CH_SRP_RATE_REFILL_MS 2u
/* srp term 0: every MSRP and MVRP PDU; both are link-local to this port */
#define MBX_CH_SRP_T0_TEST 1u
/* srp term 0 field byte */
#define MBX_CH_SRP_T0_OFFSET 0u
/* srp term 0 message types */
#define MBX_CH_SRP_T0_MSG_MASK 0xFFFFu
/* srp term 1: unused */
#define MBX_CH_SRP_T1_TEST 0u
/* srp term 1 field byte */
#define MBX_CH_SRP_T1_OFFSET 0u
/* srp term 1 message types */
#define MBX_CH_SRP_T1_MSG_MASK 0x0u
/* interface index bits */
#define MBX_IF_W 1u
/* channel index bits */
#define MBX_CH_W 3u
/* widest ring word index */
#define MBX_RING_AW 10u
/* window word address bits */
#define MBX_ADDR_W 13u
/* the largest max_frame_bytes of any channel */
#define MBX_FRAME_BYTES_MAX 1514u

#define MBX_CH_RX_BASE_TBL { MBX_CH_ADP_RX_BASE, MBX_CH_ACMP_RX_BASE, MBX_CH_AECP_RX_BASE, MBX_CH_MAAP_RX_BASE, MBX_CH_SRP_RX_BASE }
#define MBX_CH_RX_WORDS_TBL { MBX_CH_ADP_RX_WORDS, MBX_CH_ACMP_RX_WORDS, MBX_CH_AECP_RX_WORDS, MBX_CH_MAAP_RX_WORDS, MBX_CH_SRP_RX_WORDS }
#define MBX_CH_TX_BASE_TBL { MBX_CH_ADP_TX_BASE, MBX_CH_ACMP_TX_BASE, MBX_CH_AECP_TX_BASE, MBX_CH_MAAP_TX_BASE, MBX_CH_SRP_TX_BASE }
#define MBX_CH_TX_WORDS_TBL { MBX_CH_ADP_TX_WORDS, MBX_CH_ACMP_TX_WORDS, MBX_CH_AECP_TX_WORDS, MBX_CH_MAAP_TX_WORDS, MBX_CH_SRP_TX_WORDS }
#define MBX_CH_MAX_FRAME_BYTES_TBL { MBX_CH_ADP_MAX_FRAME_BYTES, MBX_CH_ACMP_MAX_FRAME_BYTES, MBX_CH_AECP_MAX_FRAME_BYTES, MBX_CH_MAAP_MAX_FRAME_BYTES, MBX_CH_SRP_MAX_FRAME_BYTES }
#define MBX_CH_ETHERTYPE0_TBL { MBX_CH_ADP_ETHERTYPE0, MBX_CH_ACMP_ETHERTYPE0, MBX_CH_AECP_ETHERTYPE0, MBX_CH_MAAP_ETHERTYPE0, MBX_CH_SRP_ETHERTYPE0 }
#define MBX_CH_ETHERTYPE1_TBL { MBX_CH_ADP_ETHERTYPE1, MBX_CH_ACMP_ETHERTYPE1, MBX_CH_AECP_ETHERTYPE1, MBX_CH_MAAP_ETHERTYPE1, MBX_CH_SRP_ETHERTYPE1 }
#define MBX_CH_HAS_SUBTYPE_TBL { MBX_CH_ADP_HAS_SUBTYPE, MBX_CH_ACMP_HAS_SUBTYPE, MBX_CH_AECP_HAS_SUBTYPE, MBX_CH_MAAP_HAS_SUBTYPE, MBX_CH_SRP_HAS_SUBTYPE }
#define MBX_CH_SUBTYPE_TBL { MBX_CH_ADP_SUBTYPE, MBX_CH_ACMP_SUBTYPE, MBX_CH_AECP_SUBTYPE, MBX_CH_MAAP_SUBTYPE, MBX_CH_SRP_SUBTYPE }
#define MBX_CH_RATE_BURST_TBL { MBX_CH_ADP_RATE_BURST, MBX_CH_ACMP_RATE_BURST, MBX_CH_AECP_RATE_BURST, MBX_CH_MAAP_RATE_BURST, MBX_CH_SRP_RATE_BURST }
#define MBX_CH_RATE_REFILL_MS_TBL { MBX_CH_ADP_RATE_REFILL_MS, MBX_CH_ACMP_RATE_REFILL_MS, MBX_CH_AECP_RATE_REFILL_MS, MBX_CH_MAAP_RATE_REFILL_MS, MBX_CH_SRP_RATE_REFILL_MS }
#define MBX_TERM_TEST_TBL { MBX_CH_ADP_T0_TEST, MBX_CH_ADP_T1_TEST, MBX_CH_ACMP_T0_TEST, MBX_CH_ACMP_T1_TEST, MBX_CH_AECP_T0_TEST, MBX_CH_AECP_T1_TEST, MBX_CH_MAAP_T0_TEST, MBX_CH_MAAP_T1_TEST, MBX_CH_SRP_T0_TEST, MBX_CH_SRP_T1_TEST }
#define MBX_TERM_OFFSET_TBL { MBX_CH_ADP_T0_OFFSET, MBX_CH_ADP_T1_OFFSET, MBX_CH_ACMP_T0_OFFSET, MBX_CH_ACMP_T1_OFFSET, MBX_CH_AECP_T0_OFFSET, MBX_CH_AECP_T1_OFFSET, MBX_CH_MAAP_T0_OFFSET, MBX_CH_MAAP_T1_OFFSET, MBX_CH_SRP_T0_OFFSET, MBX_CH_SRP_T1_OFFSET }
#define MBX_TERM_MASK_TBL { MBX_CH_ADP_T0_MSG_MASK, MBX_CH_ADP_T1_MSG_MASK, MBX_CH_ACMP_T0_MSG_MASK, MBX_CH_ACMP_T1_MSG_MASK, MBX_CH_AECP_T0_MSG_MASK, MBX_CH_AECP_T1_MSG_MASK, MBX_CH_MAAP_T0_MSG_MASK, MBX_CH_MAAP_T1_MSG_MASK, MBX_CH_SRP_T0_MSG_MASK, MBX_CH_SRP_T1_MSG_MASK }

#endif /* MBX_CONTRACT_H */
