# SPDX-License-Identifier: CERN-OHL-W-2.0
"""Generate the DIVERGENT-shape header for the obj_nxndv leg.

Every tracked config declares the same first format on every stream row, so
no tracked-header leg can tell a per-row verdict base from a row-0 lookup:
the emitter-level builder gate 30 proves the HEADER carries divergence, and
this generator is what carries that divergence into an ELABORATION. It loads
the arty_4x4 config, gives input row 1 a genuinely different BASE (the 96 kHz
family member the builder's own encoder produces - channels alone would be
masked by the listener family compare), and writes:

  gen_divergent/gen/adp_shape_defaults.svh   the include the leg elaborates
  gen_divergent/divergent_expect.h           the expectations the bench pins

Build-time artifact, like ltn_rom.hex: never tracked, regenerated per make.
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
#: `sys.path` and `endstation_builder`'s own `load_config(path: str)` are both
#: string interfaces; every path INSIDE this module is a `Path`, and the two
#: crossings are spelled `str(...)` where they happen.
sys.path.insert(0, str(ROOT / "sw" / "builder"))

import endstation_builder as eb  # noqa: E402


def main() -> None:
    """Write the divergent shape header and the expectations the bench pins to it.

    The divergence is asserted before anything is emitted: if row 1's base
    ever equalled row 0's, the leg would elaborate, pass, and prove nothing -
    which is exactly the row-0 lookup this shape exists to catch.
    """
    cfg = eb.load_config(str(ROOT / "configs" / "endstation_arty_4x4.yaml"))
    row0 = str((cfg["listeners"][0].get("formats") or ["0x0"])[0])
    div = f"0x{eb.aaf_pcm32(4, 96000):016X}"
    assert int(div, 16) != int(row0, 16), "the divergent base must differ"
    cfg["listeners"][1]["formats"] = [div] \
        + list(cfg["listeners"][1].get("formats") or [])[1:]
    svh = eb.emit_adp_shape_svh(cfg, eb.emit_aem_overlay(cfg))

    out = HERE / "gen_divergent"
    (out / "gen").mkdir(parents=True, exist_ok=True)
    #! spelled whole, because scripts/shape_consumer_inventory.py reads this
    #! literal out of this file's text to prove the generated header has a
    #! named writer. Splitting it into path components hides it from that gate.
    (out / "gen/adp_shape_defaults.svh").write_text(svh)
    (out / "divergent_expect.h").write_text(
        "// generated by gen_divergent_shape.py - do not edit\n"
        f"#define DV_ROW0_FMT {row0}ULL\n"
        f"#define DV_ROW1_FMT {div}ULL\n")
    print(f"divergent shape: row0 {row0}, row1 {div}")


if __name__ == "__main__":
    main()
