# SPDX-License-Identifier: CERN-OHL-W-2.0
"""Generate the DIVERGENT-shape header for the obj_nxndv leg.

Every tracked config declares the same first format on every stream row, so
no tracked-header leg can tell a per-row verdict base from a row-0 lookup:
the emitter-level builder gate 30 proves the HEADER carries divergence, and
this generator is what carries that divergence into an ELABORATION. It loads
the arty_4x4 config, gives input row 1 a genuinely different BASE (the 96 kHz
family member the builder's own encoder produces - channels alone would be
masked by the listener family compare), and writes:

  gen_divergent/gen/adp_shape_defaults.svh   the include the leg elaborates
  gen_divergent/divergent_expect.h           the expectations the bench pins

Build-time artifact, like ltn_rom.hex: never tracked, regenerated per make.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "../../.."))
sys.path.insert(0, os.path.join(ROOT, "sw/builder"))

import endstation_builder as eb  # noqa: E402


def main():
    cfg = eb.load_config(
        os.path.join(ROOT, "configs/endstation_arty_4x4.yaml"))
    row0 = str((cfg["listeners"][0].get("formats") or ["0x0"])[0])
    div = f"0x{eb.aaf_pcm32(4, 96000):016X}"
    assert int(div, 16) != int(row0, 16), "the divergent base must differ"
    cfg["listeners"][1]["formats"] = [div] \
        + list(cfg["listeners"][1].get("formats") or [])[1:]
    svh = eb.emit_adp_shape_svh(cfg, eb.emit_aem_overlay(cfg))

    out = os.path.join(HERE, "gen_divergent")
    os.makedirs(os.path.join(out, "gen"), exist_ok=True)
    with open(os.path.join(out, "gen/adp_shape_defaults.svh"), "w") as f:
        f.write(svh)
    with open(os.path.join(out, "divergent_expect.h"), "w") as f:
        f.write("// generated by gen_divergent_shape.py - do not edit\n")
        f.write(f"#define DV_ROW0_FMT {row0}ULL\n")
        f.write(f"#define DV_ROW1_FMT {div}ULL\n")
    print(f"divergent shape: row0 {row0}, row1 {div}")


if __name__ == "__main__":
    main()
