#!/usr/bin/python3 -S
import sys
sys.path.insert(0, '$WORKSPACE_HOME/milan-fpga-management/2026-09-22/517-f1-author/restored-defect/True-False-SIGINT')
import fake_leg
fake_leg.main({'out': [['out', 'L4 partial\n']], 'name': 'L4', 'ledger': '$WORKSPACE_HOME/milan-fpga-management/2026-09-22/517-f1-author/restored-defect/True-False-SIGINT/ledger.jsonl', 'announce': '$WORKSPACE_HOME/milan-fpga-management/2026-09-22/517-f1-author/restored-defect/True-False-SIGINT/announce.fifo'})
