#!/usr/bin/python3 -S
import sys
sys.path.insert(0, '$WORKSPACE_HOME/milan-fpga-management/2026-09-22/517-f1-author/dev-backpressure2/make-copy-SIGTERM-child-exit')
import fake_leg
fake_leg.main({'out': [['out', 'L6 partial\n']], 'name': 'L6', 'ledger': '$WORKSPACE_HOME/milan-fpga-management/2026-09-22/517-f1-author/dev-backpressure2/make-copy-SIGTERM-child-exit/ledger.jsonl', 'announce': '$WORKSPACE_HOME/milan-fpga-management/2026-09-22/517-f1-author/dev-backpressure2/make-copy-SIGTERM-child-exit/announce.fifo'})
