#!/usr/bin/env python3
"""R426-3: verify the evidence archive at a pinned commit against the page.

Usage: verify_archive.py <repo> <archive-commit> <page-commit> <page-path>

Extracts review-evidence/b6-r1 at <archive-commit> with `git archive` into a
temporary directory (no checkout), then:
  1. every MANIFEST.json entry re-hashes to published_sha256; no file unlisted
     or missing (MANIFEST.json itself excluded);
  2. every 64-hex hash in the page's Artifact hashes tables resolves to the
     archive: an Evidence-file row to original_sha256 of author/<file>, and a
     Raw-file row to author/RAW-ARTIFACTS.json (path and bytes);
  3. mask check: no capture channel index literal, count literal or unmasked
     result key in the published tools or grades (author/, author-r2/).
Prints one line per check and RESULT CLEAN/FAIL; exit 0 only when CLEAN.
"""
import hashlib, json, re, subprocess, sys, tarfile, tempfile, io, pathlib

repo, arch, page_commit, page_path = sys.argv[1:5]
fail = []

tar = subprocess.run(["git", "-C", repo, "archive", arch, "review-evidence/b6-r1"],
                     check=True, capture_output=True).stdout
tmp = pathlib.Path(tempfile.mkdtemp(prefix="r426-3-arch-"))
with tarfile.open(fileobj=io.BytesIO(tar)) as t:
    t.extractall(tmp, filter="data")
root = tmp / "review-evidence/b6-r1"
sha = lambda p: hashlib.sha256(p.read_bytes()).hexdigest()

# 1. manifest
man = json.loads((root / "MANIFEST.json").read_text())
listed = {e["file"]: e for e in man}
present = {str(p.relative_to(root)) for p in root.rglob("*") if p.is_file()} - {"MANIFEST.json"}
bad = [f for f, e in listed.items() if (root / f).is_file() and sha(root / f) != e["published_sha256"]]
missing = sorted(set(listed) - present)
unlisted = sorted(present - set(listed))
print(f"manifest: {len(listed)} listed, {len(present)} present, {len(bad)} mismatched, "
      f"{len(missing)} missing, {len(unlisted)} unlisted")
if bad or missing or unlisted:
    fail.append("manifest")
    print("  mismatched:", bad, "missing:", missing, "unlisted:", unlisted)

# 2. page hashes
page = subprocess.run(["git", "-C", repo, "show", f"{page_commit}:{page_path}"],
                      check=True, capture_output=True, text=True).stdout
sec = page.split("## Artifact hashes", 1)[1]
raw = json.loads((root / "author/RAW-ARTIFACTS.json").read_text())["files"]
raw_by_path = {r["path"]: r for r in raw}
res_orig = res_raw = masked = 0
for line in sec.splitlines():
    m = re.match(r"\| `([^`]+)`[^|]*\| ([0-9,]+) \| `([0-9a-f]{64})` \|", line)
    m2 = re.match(r"\| Tone loop[^|]*\| ([0-9,]+) \| `([0-9a-f]{64})` \|", line)
    if m2:
        # the tone loop is regenerated by the reproduction command, checked separately
        print(f"  tone-loop row: {m2.group(2)} (checked by reproduce.sh)")
        res_raw += 0
        continue
    if not m:
        continue
    f, nbytes, h = m.group(1), int(m.group(2).replace(",", "")), m.group(3)
    if f in raw_by_path:
        r = raw_by_path[f]
        ok = r["sha256"] == h and r["bytes"] == nbytes
        res_raw += ok
    else:
        e = listed.get("author/" + f)
        ok = e is not None and e["original_sha256"] == h
        if ok and e["original_sha256"] != e["published_sha256"]:
            masked += 1
        if ok and e["original_sha256"] == e["published_sha256"]:
            ok = (root / ("author/" + f)).stat().st_size == nbytes
        res_orig += ok
    if not ok:
        fail.append(f"page-hash {f}")
        print("  UNRESOLVED:", f, nbytes, h)
print(f"page hashes: {res_orig} resolve to MANIFEST original_sha256 ({masked} label-masked), "
      f"{res_raw} to RAW-ARTIFACTS.json, tone loop by regeneration")

# 3. mask check
pat = re.compile(r"\[:, *(1[0-9]|[2-9])\]|pair_[0-9]+_[0-9]+|[0-9]+_[0-9]+_decoded|"
                 r"cap-all-[0-9]+ch|CAP_[LR] *= *[0-9]|NCH *(, *CAP_L, *CAP_R)? *= *[0-9]|"
                 r"words24\(full, *[0-9]+\)|range\( *[0-9]+ *\):\s*\n\s*col")
hits = []
for d in ("author", "author-r2"):
    for p in sorted((root / d).rglob("*")):
        if p.is_file() and p.suffix in (".py", ".json", ".csv", ".md", ".txt", ".jsonl", ".sh"):
            txt = p.read_text(errors="replace")
            for mm in pat.finditer(txt):
                ln = txt[:mm.start()].count("\n") + 1
                # the matched text is not printed: it would republish the literal
                hits.append(f"{p.relative_to(root)}:{ln}: capture-layout literal (redacted)")
gb = (root / "author/tools/grade_b6.py").read_text()
for name, need in (("index-literal mask", "w[:, <capture-channel-index>], w[:, <capture-channel-index>]"),
                   ("result-key mask", "pair_decoded=")):
    if need not in gb:
        hits.append(f"author/tools/grade_b6.py: expected {name} missing")
print(f"mask check: {len(hits)} hits")
for h in hits:
    print("  ", h)
if hits:
    fail.append("mask")
print("RESULT", "CLEAN" if not fail else "FAIL " + ",".join(fail))
sys.exit(1 if fail else 0)
