#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Kebag Logic
# SPDX-License-Identifier: CERN-OHL-W-2.0
"""adp_entity.py - the ADP slice's entity fields, generated from an end-station config.

The firmware's ADPDU fields come from the entity model exactly as the
fabric's ADP engine gets them, read through the same functions, never
restated:

  entity_id, mac               the builder's ADP identity block
                               (endstation_builder.overlay_adp_block), which
                               boot_policy.fabric_constants also programs into
                               the fabric's ADP_EID and station MAC words
  entity_model_id              the AEM overlay's entity block (the hash-derived
                               or pinned id the fabric's ADP_MID word carries)
  talker/listener counts, caps the builder's adp_shape, which the fabric
                               compiles as ADP_TALKER_SRC_C and friends
  entity_capabilities          pp_adp_pkg::ADP_ENTITY_CAPS_C, read by the AEM
                               image generator's own reader
  identify_control_index       the index of the shape's one IDENTIFY CONTROL
                               descriptor (Milan v1.2 5.3.3): 0, the value
                               the fabric's ADP_IDX0[31:16] holds

The output is a C header defining ADP_ENTITY_GEN_INIT, a struct adp_entity
initialiser. It is a build product: written where the caller says, never into
the tree.

Usage:
    python3 sw/firmware/ctrl/adp/adp_entity.py configs/endstation_ax7101_1x1_tdm8.yaml -o adp_entity_gen.h

Exit 0 = written; 2 = the config or the caps declaration could not be read.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(REPO / "sw" / "builder"))
sys.path.insert(0, str(REPO / "avdecc"))

import endstation_builder as eb  # noqa: E402
import gen_aemi_image  # noqa: E402

#: The struct adp_entity members, in declaration order (adp.h).
FIELDS = ("entity_id", "entity_model_id", "mac", "entity_capabilities", "talker_stream_sources",
          "talker_capabilities", "listener_stream_sinks", "listener_capabilities", "identify_control_index")


def entity_fields(config: Path) -> dict[str, int]:
    """Every struct adp_entity field for one config, from the builder's own derivations."""
    cfg = eb.load_config(str(config))
    overlay: dict[str, Any] = eb.emit_aem_overlay(cfg)
    adp = overlay["adp"]
    caps, _where = gen_aemi_image.adp_entity_capabilities_declaration()
    controls = int(overlay["descriptor_counts"]["CONTROL"])
    if controls != 1:
        raise ValueError(f"{config}: {controls} CONTROL descriptors; the IDENTIFY control's index is not 0")
    return {
        "entity_id": int(adp["entity_id"], 16),
        "entity_model_id": int(overlay["entity"]["entity_model_id"], 16),
        "mac": int(adp["mac_address"].replace(":", ""), 16),
        "entity_capabilities": caps,
        "talker_stream_sources": int(adp["talker_stream_sources"]),
        "talker_capabilities": int(adp["talker_capabilities"], 16),
        "listener_stream_sinks": int(adp["listener_stream_sinks"]),
        "listener_capabilities": int(adp["listener_capabilities"], 16),
        "identify_control_index": 0,
    }


def emit_header(fields: dict[str, int], source: str) -> str:
    """The C header carrying ADP_ENTITY_GEN_INIT."""
    wide = {"entity_id", "entity_model_id", "mac"}
    body = ", \\\n".join(f"\t.{name} = 0x{fields[name]:X}{'ull' if name in wide else 'u'}" for name in FIELDS)
    return "\n".join([
        "// SPDX-FileCopyrightText: 2026 Kebag Logic",
        "// SPDX-License-Identifier: CERN-OHL-W-2.0",
        "//",
        f"// GENERATED by sw/firmware/ctrl/adp/adp_entity.py from {source}; DO NOT EDIT.",
        "// The struct adp_entity initialiser of this shape (adp.h).",
        "",
        "#ifndef ADP_ENTITY_GEN_H",
        "#define ADP_ENTITY_GEN_H",
        "",
        "#define ADP_ENTITY_GEN_INIT { \\",
        body + " \\",
        "}",
        "",
        "#endif // ADP_ENTITY_GEN_H",
        "",
    ])


def main(argv: list[str] | None = None) -> int:
    """Generate one header."""
    ap = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    ap.add_argument("config", type=Path, help="end-station YAML config")
    ap.add_argument("-o", "--output", type=Path, required=True, help="the header to write")
    args = ap.parse_args(argv)
    try:
        fields = entity_fields(args.config)
    except (OSError, ValueError, KeyError, eb.ConfigError) as exc:
        print(f"adp_entity: {exc}", file=sys.stderr)
        return 2
    source = args.config.resolve().relative_to(REPO) if args.config.resolve().is_relative_to(REPO) else args.config
    args.output.write_text(emit_header(fields, str(source)), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
