#!/usr/bin/env python3
"""Generate the listener lockstep top: KL_pp_acmp_listener_ref (main) beside
KL_pp_acmp_listener (candidate), every input shared, every output of each packed
into one vector (ref_o / dut_o) in port order.

Usage: gen_wrap.py LISTENER_SV OUT_SV
"""
import re
import sys

src = open(sys.argv[1], encoding="utf-8").read()
head = src[src.index("module KL_pp_acmp_listener"):]
head = head[:head.index(");\n") + 2]
ports = []
for line in head.splitlines():
    m = re.match(r"\s*(input|output)\s+(wire|logic)\s+(?:(\w+)\s+)?(\[[^\]]+\]\s*)?(\w+)\s*(?:,|$|//)", line)
    if not m:
        continue
    d, _, typ, rng, name = m.groups()
    typ = (typ or "").strip()
    ports.append((d, typ, (rng or "").strip(), name))

params = ("#(.N_SINKS_P(N_SINKS_P), .TROM_HEX_P(\"ltn_rom.hex\"), .TMR_SLOT_AW_P(7), "
          ".TMR_BASE_SLOT_P(9), .TMR_OWNER_BASE_P(32), .STRM_TIMEOUT_CYC_P(STO))")
out = ["// generated by gen_wrap.py",
       "module lsn_ls import pp_pkg::*; import pp_acmp_pkg::*; #(",
       "    parameter int unsigned N_SINKS_P = 2, parameter int unsigned STO = 64,",
       "    localparam int unsigned SINK_W_C = (N_SINKS_P > 1) ? $clog2(N_SINKS_P) : 1,",
       "    localparam int unsigned RXS_SLOT_W_C = 2, localparam int unsigned RXS_ADDR_W_C = 10,",
       "    localparam int unsigned TXS_SLOT_W_C = 3, localparam int unsigned TXS_LEN_W_C = 11,",
       "    localparam int unsigned TMR_SLOT_AW_P = 7",
       ") ("]
plist = []
for d, typ, rng, name in ports:
    if d == "input" and name == "txn_i":
        plist += ["    input  wire [2:0] t_protocol", "    input  wire [3:0] t_msg_type",
                  "    input  wire [4:0] t_status", "    input  wire [63:0] t_ctlr",
                  "    input  wire [63:0] t_target", "    input  wire [15:0] t_seq",
                  "    input  wire [15:0] t_uid", "    input  wire [2:0] t_rx_slot"]
    elif d == "input":
        if typ:
            plist.append(f"    input  wire {typ} {name}")
        else:
            plist.append(f"    input  wire {rng} {name}")
outs = [(typ, rng, name) for d, typ, rng, name in ports if d == "output"]
for typ, rng, name in [(t, r, n) for d, t, r, n in ports if d == "output"]:
    plist.append(f"    output logic {rng} o_{name}")
plist.append("    output logic [OW-1:0] ref_o")
plist.append("    output logic [OW-1:0] dut_o")
plist.append("    output logic [4:0] dut_xs")
plist.append("    output logic [4:0] ref_xs")
out.append(",\n".join(plist))
out.append(");")
widths = []
for typ, rng, name in outs:
    out.append(f"  logic {rng} r_{name}, d_{name};")
    widths.append(f"$bits(r_{name})")
out.insert(out.index(");"), "")
out += ["  pp_txn_t txn_i;",
        "  always_comb begin",
        "    txn_i = '0;",
        "    txn_i.protocol = pp_protocol_e'(t_protocol);",
        "    txn_i.msg_type = t_msg_type;",
        "    txn_i.status_in = t_status;",
        "    txn_i.controller_eid = t_ctlr;",
        "    txn_i.target_eid = t_target;",
        "    txn_i.sequence_id = t_seq;",
        "    txn_i.opcode = 16'(t_msg_type);",
        "    txn_i.operands.unique_id = t_uid;",
        "    txn_i.rx_slot = t_rx_slot;",
        "  end"]
# OW as a localparam after declarations is not legal in the port list; use a fixed upper bound
conn_r = ", ".join(f".{n}({n})" for d, t, r, n in ports if d == "input")
conn_r += ", " + ", ".join(f".{n}(r_{n})" for t, r, n in outs)
conn_d = ", ".join(f".{n}({n})" for d, t, r, n in ports if d == "input")
conn_d += ", " + ", ".join(f".{n}(d_{n})" for t, r, n in outs)
out.append(f"  KL_pp_acmp_listener_ref {params} u_ref ({conn_r});")
out.append(f"  KL_pp_acmp_listener {params} u_dut ({conn_d});")
out.append("  assign ref_o = OW'({" + ", ".join(f"r_{n}" for t, r, n in outs) + "});")
out.append("  assign dut_o = OW'({" + ", ".join(f"d_{n}" for t, r, n in outs) + "});")
out.append("  assign dut_xs = 5'(u_dut.xs_r);")
for typ, rng, name in outs:
    out.append(f"  assign o_{name} = r_{name};")
out.append("  assign ref_xs = 5'(u_ref.xs_r);")
out.append("  initial if ($bits(ref_o) < (" + " + ".join(widths) + ")) $fatal(1, \"OW too small\");")
out.append("endmodule")
text = "\n".join(out) + "\n"
text = text.replace("module lsn_ls import pp_pkg::*; import pp_acmp_pkg::*; #(",
                    "module lsn_ls import pp_pkg::*; import pp_acmp_pkg::*; #(\n"
                    "    parameter int unsigned OW = 1024,")
open(sys.argv[2], "w", encoding="utf-8").write(text)
sys.stderr.write(f"{len(ports)} ports, {len(outs)} outputs\n")
