#!/usr/bin/env python3
# SPDX-License-Identifier: CERN-OHL-W-2.0
"""Render the builder's unchanged AEM image as statically allocated C input."""
from __future__ import annotations
import argparse
import struct
import sys
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(ROOT / "sw/builder"))
import endstation_builder as builder


def emit(config: Path) -> str:
    """Use the existing descriptor generators and derive storage from their bytes."""
    cfg = builder.load_config(str(config))
    overlay = builder.emit_aem_overlay(cfg)
    blob = builder._entity_model_image(cfg, overlay)["aem_desc.bin"]
    entries = struct.unpack_from(">H", blob, 8)[0]
    offset = struct.unpack_from(">I", blob, 12)[0]
    count = 0
    values = 0
    for row in range(entries):
        number, length = struct.unpack_from(">HH", blob, offset + row * 16 + 4)
        count += number
        values += number * length
    lines = [
        "// SPDX-License-Identifier: CERN-OHL-W-2.0",
        "// Generated by aecp_entity.py; do not edit.",
        "#ifndef CTRL_AECP_ENTITY_GEN_H",
        "#define CTRL_AECP_ENTITY_GEN_H",
        f"#define AECP_ENTITY_DESCRIPTORS {count}u",
        f"#define AECP_ENTITY_VALUE_BYTES {values}u",
        f"#define AECP_ENTITY_CRC 0x{zlib.crc32(blob):08x}u",
        "static const unsigned char aecp_entity_image[] = {",
    ]
    lines.extend("\t" + ",".join(f"0x{b:02x}" for b in blob[n:n + 16]) + ","
                 for n in range(0, len(blob), 16))
    return "\n".join([*lines, "};", "#endif", ""])


def main() -> int:
    """Generate only the explicitly requested output."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("config", type=Path)
    parser.add_argument("-o", "--output", required=True, type=Path)
    args = parser.parse_args()
    args.output.write_text(emit(args.config), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
