#!/usr/bin/env python3
# SPDX-License-Identifier: CERN-OHL-W-2.0
"""Generate the SRP static entity shape from the authoritative builder counts."""
from __future__ import annotations
import argparse
import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]/"adp"))
import adp_entity


def emit(config: Path) -> str:
    """The same stream counts advertised by ADP size the SRP tables and pool."""
    fields=adp_entity.entity_fields(config)
    return "\n".join([
        "// SPDX-License-Identifier: CERN-OHL-W-2.0",
        "// Generated by srp_entity.py; do not edit.",
        "#ifndef CTRL_SRP_ENTITY_H",
        "#define CTRL_SRP_ENTITY_H",
        f"#define CTRL_SRP_SOURCES {fields['talker_stream_sources']}u",
        f"#define CTRL_SRP_SINKS {fields['listener_stream_sinks']}u",
        "#endif", "",
    ])


def main() -> int:
    """Generate a shape header, or report a refused input."""
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("config",type=Path)
    parser.add_argument("-o","--output",type=Path,required=True)
    args=parser.parse_args()
    try:
        args.output.write_text(emit(args.config),encoding="utf-8")
    except (OSError,ValueError,KeyError) as error:
        print(f"srp_entity: {error}",file=sys.stderr)
        return 2
    return 0

if __name__=="__main__":
    raise SystemExit(main())
