#!/usr/bin/env python3
"""Cut the timer arm-port mux block out of protocol_processor_top.sv and wrap it.

usage: gen.py TOP_SV MODULE_NAME OUT_SV [--mutant NAME]
The block is cut from the '// ====' line above 'timer arm-port priority mux
(banner)' to the line before the '// ====' line above 'PRNG draw-port owner mux
(banner)', byte for byte, then wrapped with the eight faces as inputs and the arm
port and the drop counter as outputs.  --mutant plants one reviewer control in
the cut text (exact single replacement, refused otherwise).
"""
import sys

FACES = ["lstn", "tkr", "adp", "srp", "org", "maapeng", "ntfy", "ntfy_mon"]
BLOCK_DECLARES = {"ntfy", "ntfy_mon"}   # the block declares these faces itself

MUTANTS = {
    # each: (old, new)
    "write_refused": ("if (armq_push_ok_w[g]) mem_r[wr_ix_w] <= armq_in_w[g];",
                      "if (armq_in_vld_w[g]) mem_r[wr_ix_w] <= armq_in_w[g];"),
    "wr_at_head": ("assign wr_ix_w = armq_hd_r[g] + armq_cnt_r[g][1:0];",
                   "assign wr_ix_w = armq_hd_r[g];"),
    "wr_at_mid": ("assign wr_ix_w = armq_hd_r[g] + armq_cnt_r[g][1:0];",
                  "assign wr_ix_w = armq_hd_r[g] + armq_mid_w[g][1:0];"),
    "head_stuck": ("armq_hd_r[i]         <= armq_hd_r[i] + 2'd1;",
                   "armq_hd_r[i]         <= armq_hd_r[i];"),
    "read_tail": ("assign armq_hd_w[g] = mem_r[armq_hd_r[g]];",
                  "assign armq_hd_w[g] = mem_r[wr_ix_w];"),
    "ring_of_three": ("armq_hd_r[i]         <= armq_hd_r[i] + 2'd1;",
                      "armq_hd_r[i]         <= (armq_hd_r[i] == 2'd2) ? 2'd0 : armq_hd_r[i] + 2'd1;"),
    # a full queue that pops and pushes refuses the push (depth 3 under load)
    "full_pop_refuses": ("armq_push_ok_w[i] = armq_in_vld_w[i] && (armq_mid_w[i] != 3'd4);",
                         "armq_push_ok_w[i] = armq_in_vld_w[i] && (armq_cnt_r[i] != 3'd4);"),
    # the drop counter adds one per dropping face (an arm count, not a clock count)
    "drop_skip_sat": ("if (arm_drop_r != 16'hFFFF) arm_drop_r <= arm_drop_r + 16'd1;",
                      "arm_drop_r <= arm_drop_r + 16'd1;"),
    # the write lands one entry late when the queue holds three or more
    "wr_wrap_hi": ("assign wr_ix_w = armq_hd_r[g] + armq_cnt_r[g][1:0];",
                   "assign wr_ix_w = (armq_cnt_r[g] >= 3'd3) ? armq_hd_r[g] + 2'd2 : armq_hd_r[g] + armq_cnt_r[g][1:0];"),
    # probe, not a control: the head index not reset (expected equivalent)
    "hd_not_reset": ("armq_hd_r  <= '0;\n", ""),
}


def cut(text: str) -> str:
    lines = text.splitlines(keepends=True)
    a = next(i for i, l in enumerate(lines) if "timer arm-port priority mux (banner)" in l)
    b = next(i for i, l in enumerate(lines) if "PRNG draw-port owner mux (banner)" in l)
    assert lines[a - 1].lstrip().startswith("// ====") and lines[b - 1].lstrip().startswith("// ====")
    return "".join(lines[a - 1:b - 1])


def main() -> None:
    top, name, out = sys.argv[1:4]
    mutant = sys.argv[5] if len(sys.argv) > 5 and sys.argv[4] == "--mutant" else None
    block = cut(open(top).read())
    if mutant:
        old, new = MUTANTS[mutant]
        assert block.count(old) == 1, f"{mutant}: planted text occurs {block.count(old)} times"
        block = block.replace(old, new, 1)
    decl, conn = [], []
    for k, f in enumerate(FACES):
        if f not in BLOCK_DECLARES:
            decl.append(f"  logic {f}_arm_valid_w, {f}_arm_cancel_w;\n"
                        f"  logic [TMR_AW_C-1:0] {f}_arm_slot_w;\n"
                        f"  logic [PP_TIMER_OWNER_W_C-1:0] {f}_arm_owner_w;\n"
                        f"  logic [31:0] {f}_arm_deadline_w;\n")
        conn.append(f"  assign {f}_arm_valid_w = in_vld_i[{k}];\n"
                    f"  assign {{{f}_arm_cancel_w, {f}_arm_slot_w, {f}_arm_owner_w, {f}_arm_deadline_w}}"
                    f" = in_arm_i[{k}];\n")
    src = f"""// generated by gen.py from {top}
/* verilator lint_off UNUSEDSIGNAL */
/* verilator lint_off DECLFILENAME */
module {name} #(parameter int unsigned TMR_AW_C = 6) (
  input  logic clk_i,
  input  logic rst_n,
  input  logic [7:0] in_vld_i,
  input  logic [7:0][1 + TMR_AW_C + 8 + 32 - 1:0] in_arm_i,
  output logic       arm_valid_o,
  output logic [1 + TMR_AW_C + 8 + 32 - 1:0] arm_o,
  output logic [15:0] drop_o,
  output logic [7:0][2:0] cnt_o
);
  localparam int unsigned PP_TIMER_OWNER_W_C = 8;
  logic        tmr_arm_valid_w, tmr_arm_cancel_w;
  logic [TMR_AW_C-1:0] tmr_arm_slot_w;
  logic [PP_TIMER_OWNER_W_C-1:0] tmr_arm_owner_w;
  logic [31:0] tmr_arm_deadline_w;
{''.join(decl)}
{block}
{''.join(conn)}
  assign arm_valid_o = tmr_arm_valid_w;
  assign arm_o = {{tmr_arm_cancel_w, tmr_arm_slot_w, tmr_arm_owner_w, tmr_arm_deadline_w}};
  assign drop_o = arm_drop_r;
  assign cnt_o = armq_cnt_r;
endmodule
"""
    open(out, "w").write(src)


if __name__ == "__main__":
    main()
