#!/usr/bin/env python3
"""R456-1: summarise the suite and probe logs under PACKET/receipts into
PACKET/receipts/summary.txt. Usage: summarize.py PACKET"""
import collections
import re
import sys
from pathlib import Path

P = Path(sys.argv[1]).resolve()
R = P / "receipts"
out = []
w = out.append

LAW = re.compile(r"LAW (\+\d+): (\d+) PDUs, fill at the PDU end (\d+)\.\.(\d+) "
                 r"\((\d+) under the tie rule\), first-event delay from it "
                 r"(\d+)\.\.(\d+) cycles = ([\d.]+)\.\.([\d.]+) media ticks")


def rc(p: Path) -> str:
    for c in (p.with_name(p.name + ".rc"), p.with_suffix(".rc")):
        if c.is_file():
            return c.read_text().strip()
    return "rc=?"


def law_table(log: Path) -> None:
    text = log.read_text(errors="replace")
    fails = [l.strip() for l in text.splitlines() if l.strip().startswith("[FAIL]")]
    tallies = re.findall(r"checks: (\d+)\s+failures: (\d+)", text)
    w(f"### {log.relative_to(P)}  ({rc(log)}; tallies {tallies})")
    for m in LAW.finditer(text):
        w(f"  {m.group(1):>6}  n {m.group(2)}  fill {m.group(3)}..{m.group(4)}  "
          f"ties {m.group(5)}  d {m.group(6)}..{m.group(7)} cyc = "
          f"{m.group(8)}..{m.group(9)} T")
    for line in re.findall(r"\[i\]\s+LAW: waited.*", text):
        w("  " + line)
    for line in re.findall(r"\[i\]\s+T30 CRF LAW:.*", text):
        w("  " + line[:200])
    w(f"  failing checks: {len(fails)}")
    for f in fails:
        w("    " + f[:170])
    w("")


w("R456-1 receipts summary (generated by scripts/summarize.py)")
w("")
for name in ("suite-p631.log", "suite-pc4c.log"):
    law_table(R / name)
    t = (R / name).read_text(errors="replace")
    for line in re.findall(r"\d+ checks: \d+ PASS, \d+ FAIL", t):
        w(f"  leg defects: {line}")
    w("")
for log in sorted((R / "probes").glob("*.log")):
    law_table(log)

w("### per-PDU trace at the tie boundary (probes/hp-tietr18-law.log)")
w("  phase: count x (fill, tie_pop, rule-ok, last pop seen before end [cyc], "
  "first pop seen after end [cyc], first-event delay [cyc])")
trace = (R / "probes" / "hp-tietr18-law.log").read_text(errors="replace")
rows = collections.defaultdict(collections.Counter)
for m in re.finditer(r"\[dbg\] T30 INTERNAL LAW (\+\d+) id \d+ fill (\d+) tie (\d+) "
                     r"ok (\d+) prev_pop_seen_before_end (-?\d+) "
                     r"next_pop_seen_after_end (-?\d+) d (\d+)", trace):
    rows[m.group(1)][m.groups()[1:]] += 1
for ph in ("+2024", "+2025", "+2026", "+2027"):
    for k, n in rows[ph].most_common():
        w(f"  {ph}: {n:3d} x fill {k[0]} tie {k[1]} ok {k[2]} prev {k[3]} next {k[4]} d {k[5]}")
seq = re.findall(r"\[dbg\] T30 INTERNAL LAW \+2025 id (\d+) fill (\d+) tie (\d+) ok \d+ "
                 r"prev_pop_seen_before_end -?\d+ next_pop_seen_after_end (-?\d+)", trace)
w("  +2025 in PDU order (id:fill/tie/next): " +
  " ".join(f"{a}:{b}/{c}/{d}" for a, b, c, d in seq))
w("")
boot = (R / "probes" / "hp-boottrace-law.log").read_text(errors="replace")
errs = [int(x) for x in re.findall(r"\[probe\] tick \d+ engaged \d+ err (-?\d+)", boot)]
w("### boot pull-in (probes/hp-boottrace-law.log, err sampled every 100 ticks)")
w(f"  err min {min(errs)} max {max(errs)} over {len(errs)} samples")
for line in re.findall(r"\[probe\] report (?:MET|LAPSED).*", boot):
    w("  " + line)
(R / "summary.txt").write_text("\n".join(out) + "\n")
print(f"wrote {R / 'summary.txt'} ({len(out)} lines)")
