// GENERATED by avdecc/gen_aem_store.py - DO NOT EDIT.
// Legacy SVH rendering of the selected builder entity model.
// See docs/ENDSTATION_BUILDER.md.
//
// NOT COMPILED BY ANY RTL (2026-08-12). This is a rendering of the
// DECLARATIVE entity model. The IEEE 1722.1 control plane that used to
// `include it (hdl/ieee17221/aecp/**, KL_aecp_aem_store) is DELETED and
// the protocol-processor submodule is the control plane now. It serves
// READ_DESCRIPTOR from the flat DRAM image emitted from this same model.
// The model also supplies the ADP
// shape - talker_stream_sources / listener_stream_sinks and the two
// capability words - via hdl/common/gen/adp_shape_defaults.svh.

localparam int unsigned AEM_ROM_BYTES_C = 3563;
localparam int unsigned AEM_DESC_N_C    = 32;
// Scratch tail (zero-init RAM past the descriptor image): Milan MVU
// media_clock_domain_name (64 B, Milan 1.3 §5.4.4.4)
localparam int unsigned AEM_STORE_BYTES_C = AEM_ROM_BYTES_C + 64;
localparam [15:0] WB_MCR_DOMNAME_C = 16'd3563;

// Descriptor directory: {type[15:0], index[15:0], base[15:0], len[15:0]}
localparam [63:0] AEM_DIR_C [0:31] = '{
  64'h0000_0000_0000_0138,
  64'h0001_0000_0138_006A,
  64'h0002_0000_01A2_009C,
  64'h0005_0000_023E_009A,
  64'h0005_0001_02D8_0092,
  64'h0006_0000_036A_0092,
  64'h0009_0000_03FC_0066,
  64'h000A_0000_0462_0056,
  64'h000A_0001_04B8_0056,
  64'h0024_0000_050E_0050,
  64'h001A_0000_055E_0071,
  64'h000C_0000_05CF_0048,
  64'h000D_0000_0617_01C4,
  64'h000E_0000_07DB_0014,
  64'h000F_0000_07EF_0014,
  64'h0014_0000_0803_005A,
  64'h0014_0001_085D_005A,
  64'h0014_0002_08B7_005A,
  64'h0014_0003_0911_005A,
  64'h0014_0004_096B_005A,
  64'h0014_0005_09C5_005A,
  64'h0014_0006_0A1F_005A,
  64'h0014_0007_0A79_005A,
  64'h0014_0008_0AD3_005A,
  64'h0014_0009_0B2D_005A,
  64'h0014_000A_0B87_005A,
  64'h0014_000B_0BE1_005A,
  64'h0014_000C_0C3B_005A,
  64'h0014_000D_0C95_005A,
  64'h0014_000E_0CEF_005A,
  64'h0014_000F_0D49_005A,
  64'h0017_0000_0DA3_0048
};

// Level 1 of the directory (type-direct-indexed): per-type runs in
// AEM_DIR_C are CONTIGUOUS, ZERO-BASED and ASCENDING (generator-
// asserted 1:1 against the linear scan - gen_aem_store.py
// check_two_level), so (type, index) resolves by ROM indexing alone:
//   hit = index < AEM_L1_CNT_C[type],
//   {base, len} = AEM_DIR_C[AEM_L1_ROW_C[type] + index][31:0].
// Zero-padded to 1 << AEM_L1_AW_C rows: an absent type reads count 0.
localparam int unsigned AEM_L1_AW_C = 6;
localparam int unsigned AEM_L1_N_C  = 64;
localparam [15:0] AEM_L1_CNT_C [0:63] = '{
  16'd1, 16'd1, 16'd1, 16'd0, 16'd0, 16'd2, 16'd1, 16'd0,
  16'd0, 16'd1, 16'd2, 16'd0, 16'd1, 16'd1, 16'd1, 16'd1,
  16'd0, 16'd0, 16'd0, 16'd0, 16'd16, 16'd0, 16'd0, 16'd1,
  16'd0, 16'd0, 16'd1, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0,
  16'd0, 16'd0, 16'd0, 16'd0, 16'd1, 16'd0, 16'd0, 16'd0,
  16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0,
  16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0,
  16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0
};
localparam [15:0] AEM_L1_ROW_C [0:63] = '{
  16'd0, 16'd1, 16'd2, 16'd0, 16'd0, 16'd3, 16'd5, 16'd0,
  16'd0, 16'd6, 16'd7, 16'd0, 16'd11, 16'd12, 16'd13, 16'd14,
  16'd0, 16'd0, 16'd0, 16'd0, 16'd15, 16'd0, 16'd0, 16'd31,
  16'd0, 16'd0, 16'd10, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0,
  16'd0, 16'd0, 16'd0, 16'd0, 16'd9, 16'd0, 16'd0, 16'd0,
  16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0,
  16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0,
  16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0, 16'd0
};

// ROM image (network byte order, addr 0 = first byte of ENTITY)
localparam [7:0] AEM_ROM_INIT_C [0:3562] = '{
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h4D,8'h69,8'h6C,8'h61,8'h6E,8'h20,8'h46,8'h50,8'h47,8'h41,8'h20,8'h54,8'h61,8'h6C,8'h6B,8'h65,
  8'h72,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h02,8'h00,8'h00,8'h32,8'h2E,8'h39,8'h36,8'h2E,8'h30,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h41,8'h58,8'h37,8'h31,8'h30,8'h31,8'h2D,8'h30,8'h30,8'h30,8'h31,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h01,8'h00,8'h00,8'h00,8'h01,8'h00,8'h00,8'h44,8'h65,8'h66,8'h61,
  8'h75,8'h6C,8'h74,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h01,8'h00,8'h08,
  8'h00,8'h4A,8'h00,8'h02,8'h00,8'h01,8'h00,8'h05,8'h00,8'h02,8'h00,8'h06,8'h00,8'h01,8'h00,8'h09,
  8'h00,8'h01,8'h00,8'h24,8'h00,8'h01,8'h00,8'h0A,8'h00,8'h02,8'h00,8'h1A,8'h00,8'h01,8'h00,8'h0C,
  8'h00,8'h01,8'h00,8'h02,8'h00,8'h00,8'h41,8'h75,8'h64,8'h69,8'h6F,8'h20,8'h55,8'h6E,8'h69,8'h74,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'hFF,8'hFF,8'h00,8'h00,8'h00,8'h01,8'h00,8'h00,8'h00,8'h01,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'hBB,8'h80,8'h00,8'h90,
  8'h00,8'h03,8'h00,8'h00,8'hBB,8'h80,8'h00,8'h01,8'h77,8'h00,8'h00,8'h02,8'hEE,8'h00,8'h00,8'h05,
  8'h00,8'h00,8'h53,8'h74,8'h72,8'h65,8'h61,8'h6D,8'h20,8'h31,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'hFF,8'hFF,8'h00,8'h00,8'h00,8'h03,8'h02,8'h05,8'h02,8'h20,8'h00,8'h80,8'h60,8'h00,
  8'h00,8'h8A,8'h00,8'h02,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h20,
  8'h70,8'hB0,8'h00,8'h9A,8'h00,8'h00,8'h00,8'h00,8'h02,8'h05,8'h02,8'h20,8'h00,8'h80,8'h60,8'h00,
  8'h02,8'h15,8'h02,8'h20,8'h02,8'h00,8'h60,8'h00,8'h00,8'h05,8'h00,8'h01,8'h43,8'h52,8'h46,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'hFF,8'hFF,8'h00,8'h00,
  8'h00,8'h03,8'h04,8'h10,8'h60,8'h01,8'h00,8'h00,8'hBB,8'h80,8'h00,8'h8A,8'h00,8'h01,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h20,8'h70,8'hB0,8'h00,8'h92,8'h00,8'h00,
  8'h00,8'h00,8'h04,8'h10,8'h60,8'h01,8'h00,8'h00,8'hBB,8'h80,8'h00,8'h06,8'h00,8'h00,8'h53,8'h74,
  8'h72,8'h65,8'h61,8'h6D,8'h20,8'h4F,8'h75,8'h74,8'h70,8'h75,8'h74,8'h20,8'h30,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'hFF,8'hFF,
  8'h00,8'h00,8'h00,8'h02,8'h02,8'h05,8'h02,8'h20,8'h00,8'h80,8'h60,8'h00,8'h00,8'h8A,8'h00,8'h01,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h92,
  8'h00,8'h00,8'h00,8'h00,8'h02,8'h05,8'h02,8'h20,8'h00,8'h80,8'h60,8'h00,8'h00,8'h09,8'h00,8'h00,
  8'h41,8'h56,8'h42,8'h20,8'h49,8'h6E,8'h74,8'h65,8'h72,8'h66,8'h61,8'h63,8'h65,8'h20,8'h30,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'hFF,8'hFF,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h07,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'hF8,8'hF8,8'h43,8'h6A,8'hFE,8'hF8,8'h00,8'hFD,8'h00,8'h00,8'h00,8'h01,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h0A,8'h00,8'h00,8'h49,8'h6E,8'h74,8'h65,8'h72,8'h6E,8'h61,8'h6C,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'hFF,8'hFF,8'h00,8'h02,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h0A,8'h00,8'h00,8'h00,8'h0A,8'h00,8'h01,8'h43,8'h52,8'h46,8'h20,
  8'h43,8'h6C,8'h6F,8'h63,8'h6B,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'hFF,8'hFF,8'h00,8'h02,
  8'h00,8'h02,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h05,8'h00,8'h01,8'h00,8'h24,
  8'h00,8'h00,8'h43,8'h6C,8'h6F,8'h63,8'h6B,8'h20,8'h52,8'h65,8'h66,8'h65,8'h72,8'h65,8'h6E,8'h63,
  8'h65,8'h20,8'h46,8'h6F,8'h72,8'h6D,8'h61,8'h74,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'hFF,8'hFF,8'h00,8'h00,8'h00,8'h4C,8'h00,8'h02,8'h00,8'h00,8'h00,8'h01,8'h00,8'h1A,
  8'h00,8'h00,8'h49,8'h64,8'h65,8'h6E,8'h74,8'h69,8'h66,8'h79,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'hFF,8'hFF,8'h00,8'h00,8'h01,8'hF4,8'h00,8'h00,8'h01,8'hF4,8'h00,8'h00,8'h00,8'h01,
  8'h90,8'hE0,8'hF0,8'h00,8'h00,8'h00,8'h00,8'h01,8'h00,8'h00,8'h00,8'h00,8'h00,8'h68,8'h00,8'h01,
  8'hFF,8'hFF,8'h00,8'h00,8'h00,8'h00,8'h00,8'hFF,8'hFF,8'h00,8'h00,8'h00,8'h00,8'hFF,8'hFF,8'h00,
  8'h0C,8'h00,8'h00,8'h65,8'h6E,8'h2D,8'h45,8'h4E,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h01,8'h00,8'h00,8'h00,8'h0D,8'h00,8'h00,8'h4D,8'h69,8'h6C,8'h61,8'h6E,
  8'h20,8'h46,8'h50,8'h47,8'h41,8'h20,8'h54,8'h61,8'h6C,8'h6B,8'h65,8'h72,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h34,8'h38,8'h2F,8'h39,8'h36,
  8'h2F,8'h31,8'h39,8'h32,8'h20,8'h6B,8'h48,8'h7A,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h4B,8'h65,8'h62,8'h61,8'h67,
  8'h20,8'h4C,8'h6F,8'h67,8'h69,8'h63,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h0E,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h01,8'h00,8'h00,8'h00,8'h00,8'h00,8'h08,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h0F,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h08,8'h00,8'h08,8'h00,
  8'h01,8'h00,8'h00,8'h00,8'h14,8'h00,8'h00,8'h49,8'h32,8'h53,8'h20,8'h4F,8'h75,8'h74,8'h20,8'h30,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'hFF,8'hFF,8'hFF,8'hFF,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h01,8'hF4,8'h00,8'h00,8'h01,8'hF4,8'h00,8'h01,8'h40,8'h00,8'h00,8'h00,8'h00,8'h14,8'h00,
  8'h01,8'h49,8'h32,8'h53,8'h20,8'h4F,8'h75,8'h74,8'h20,8'h31,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'hFF,8'hFF,8'hFF,8'hFF,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h01,8'hF4,8'h00,8'h00,8'h01,
  8'hF4,8'h00,8'h01,8'h40,8'h00,8'h00,8'h00,8'h00,8'h14,8'h00,8'h02,8'h56,8'h69,8'h72,8'h74,8'h75,
  8'h61,8'h6C,8'h20,8'h4F,8'h75,8'h74,8'h20,8'h32,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'hFF,8'hFF,8'hFF,8'hFF,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h01,8'hF4,8'h00,8'h00,8'h01,8'hF4,8'h00,8'h01,8'h40,8'h00,8'h00,
  8'h00,8'h00,8'h14,8'h00,8'h03,8'h56,8'h69,8'h72,8'h74,8'h75,8'h61,8'h6C,8'h20,8'h4F,8'h75,8'h74,
  8'h20,8'h33,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'hFF,8'hFF,8'hFF,8'hFF,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h01,
  8'hF4,8'h00,8'h00,8'h01,8'hF4,8'h00,8'h01,8'h40,8'h00,8'h00,8'h00,8'h00,8'h14,8'h00,8'h04,8'h56,
  8'h69,8'h72,8'h74,8'h75,8'h61,8'h6C,8'h20,8'h4F,8'h75,8'h74,8'h20,8'h34,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'hFF,
  8'hFF,8'hFF,8'hFF,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h01,8'hF4,8'h00,8'h00,8'h01,8'hF4,8'h00,
  8'h01,8'h40,8'h00,8'h00,8'h00,8'h00,8'h14,8'h00,8'h05,8'h56,8'h69,8'h72,8'h74,8'h75,8'h61,8'h6C,
  8'h20,8'h4F,8'h75,8'h74,8'h20,8'h35,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'hFF,8'hFF,8'hFF,8'hFF,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h01,8'hF4,8'h00,8'h00,8'h01,8'hF4,8'h00,8'h01,8'h40,8'h00,8'h00,8'h00,8'h00,
  8'h14,8'h00,8'h06,8'h56,8'h69,8'h72,8'h74,8'h75,8'h61,8'h6C,8'h20,8'h4F,8'h75,8'h74,8'h20,8'h36,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'hFF,8'hFF,8'hFF,8'hFF,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h01,8'hF4,8'h00,
  8'h00,8'h01,8'hF4,8'h00,8'h01,8'h40,8'h00,8'h00,8'h00,8'h00,8'h14,8'h00,8'h07,8'h56,8'h69,8'h72,
  8'h74,8'h75,8'h61,8'h6C,8'h20,8'h4F,8'h75,8'h74,8'h20,8'h37,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'hFF,8'hFF,8'hFF,
  8'hFF,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h01,8'hF4,8'h00,8'h00,8'h01,8'hF4,8'h00,8'h01,8'h40,
  8'h00,8'h00,8'h00,8'h00,8'h14,8'h00,8'h08,8'h49,8'h32,8'h53,8'h20,8'h49,8'h6E,8'h20,8'h30,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'hFF,8'hFF,8'h00,8'h02,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h01,8'hF4,8'h00,8'h00,8'h01,8'hF4,8'h00,8'h01,8'h40,8'h00,8'h00,8'h00,8'h00,8'h14,8'h00,
  8'h09,8'h49,8'h32,8'h53,8'h20,8'h49,8'h6E,8'h20,8'h31,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'hFF,8'hFF,8'h00,8'h02,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h01,8'hF4,8'h00,8'h00,8'h01,
  8'hF4,8'h00,8'h01,8'h40,8'h00,8'h00,8'h00,8'h00,8'h14,8'h00,8'h0A,8'h56,8'h69,8'h72,8'h74,8'h75,
  8'h61,8'h6C,8'h20,8'h49,8'h6E,8'h20,8'h32,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'hFF,8'hFF,8'h00,8'h02,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h01,8'hF4,8'h00,8'h00,8'h01,8'hF4,8'h00,8'h01,8'h40,8'h00,8'h00,
  8'h00,8'h00,8'h14,8'h00,8'h0B,8'h56,8'h69,8'h72,8'h74,8'h75,8'h61,8'h6C,8'h20,8'h49,8'h6E,8'h20,
  8'h33,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'hFF,8'hFF,8'h00,8'h02,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h01,
  8'hF4,8'h00,8'h00,8'h01,8'hF4,8'h00,8'h01,8'h40,8'h00,8'h00,8'h00,8'h00,8'h14,8'h00,8'h0C,8'h56,
  8'h69,8'h72,8'h74,8'h75,8'h61,8'h6C,8'h20,8'h49,8'h6E,8'h20,8'h34,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'hFF,
  8'hFF,8'h00,8'h02,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h01,8'hF4,8'h00,8'h00,8'h01,8'hF4,8'h00,
  8'h01,8'h40,8'h00,8'h00,8'h00,8'h00,8'h14,8'h00,8'h0D,8'h56,8'h69,8'h72,8'h74,8'h75,8'h61,8'h6C,
  8'h20,8'h49,8'h6E,8'h20,8'h35,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'hFF,8'hFF,8'h00,8'h02,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h01,8'hF4,8'h00,8'h00,8'h01,8'hF4,8'h00,8'h01,8'h40,8'h00,8'h00,8'h00,8'h00,
  8'h14,8'h00,8'h0E,8'h56,8'h69,8'h72,8'h74,8'h75,8'h61,8'h6C,8'h20,8'h49,8'h6E,8'h20,8'h36,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'hFF,8'hFF,8'h00,8'h02,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h01,8'hF4,8'h00,
  8'h00,8'h01,8'hF4,8'h00,8'h01,8'h40,8'h00,8'h00,8'h00,8'h00,8'h14,8'h00,8'h0F,8'h56,8'h69,8'h72,
  8'h74,8'h75,8'h61,8'h6C,8'h20,8'h49,8'h6E,8'h20,8'h37,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'hFF,8'hFF,8'h00,
  8'h02,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h01,8'hF4,8'h00,8'h00,8'h01,8'hF4,8'h00,8'h01,8'h40,
  8'h00,8'h00,8'h00,8'h00,8'h17,8'h00,8'h00,8'h00,8'h08,8'h00,8'h08,8'h00,8'h00,8'h00,8'h00,8'h00,
  8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'h01,8'h00,8'h01,8'h00,8'h00,8'h00,8'h00,8'h00,8'h02,8'h00,
  8'h02,8'h00,8'h00,8'h00,8'h00,8'h00,8'h03,8'h00,8'h03,8'h00,8'h00,8'h00,8'h00,8'h00,8'h04,8'h00,
  8'h04,8'h00,8'h00,8'h00,8'h00,8'h00,8'h05,8'h00,8'h05,8'h00,8'h00,8'h00,8'h00,8'h00,8'h06,8'h00,
  8'h06,8'h00,8'h00,8'h00,8'h00,8'h00,8'h07,8'h00,8'h07,8'h00,8'h00
};

// Dynamic read-overlay sources
localparam [3:0] OVL_ENTITY_ID_C = 4'd0;
localparam [3:0] OVL_MODEL_ID_C = 4'd1;
localparam [3:0] OVL_ECAPS_C = 4'd2;
localparam [3:0] OVL_TALKER_SRC_C = 4'd3;
localparam [3:0] OVL_TALKER_CAP_C = 4'd4;
localparam [3:0] OVL_LISTEN_SINK_C = 4'd5;
localparam [3:0] OVL_LISTEN_CAP_C = 4'd6;
localparam [3:0] OVL_CTRL_CAP_C = 4'd7;
localparam [3:0] OVL_AVAIL_IDX_C = 4'd8;
localparam [3:0] OVL_ASSOC_ID_C = 4'd9;
localparam [3:0] OVL_CURRENT_CFG_C = 4'd10;
localparam [3:0] OVL_MAC_C = 4'd11;
localparam [3:0] OVL_CLOCK_ID_C = 4'd12;
localparam [3:0] OVL_ENT_NAME8_C = 4'd13;

// overlay lookup: rom addr -> {hit, source[3:0], byte_of_source[2:0]}
// byte_of_source 0 = MOST significant byte of the source value.
function automatic [7:0] aem_ovl_lookup(input [15:0] addr);
  begin
    aem_ovl_lookup = 8'h00;  // hit=0
    if (addr >= 16'd4 && addr < 16'd12)
      aem_ovl_lookup = {1'b1, OVL_ENTITY_ID_C, 3'(addr - 16'd4)};
    if (addr >= 16'd12 && addr < 16'd20)
      aem_ovl_lookup = {1'b1, OVL_MODEL_ID_C, 3'(addr - 16'd12)};
    if (addr >= 16'd20 && addr < 16'd24)
      aem_ovl_lookup = {1'b1, OVL_ECAPS_C, 3'(addr - 16'd20)};
    if (addr >= 16'd24 && addr < 16'd26)
      aem_ovl_lookup = {1'b1, OVL_TALKER_SRC_C, 3'(addr - 16'd24)};
    if (addr >= 16'd26 && addr < 16'd28)
      aem_ovl_lookup = {1'b1, OVL_TALKER_CAP_C, 3'(addr - 16'd26)};
    if (addr >= 16'd28 && addr < 16'd30)
      aem_ovl_lookup = {1'b1, OVL_LISTEN_SINK_C, 3'(addr - 16'd28)};
    if (addr >= 16'd30 && addr < 16'd32)
      aem_ovl_lookup = {1'b1, OVL_LISTEN_CAP_C, 3'(addr - 16'd30)};
    if (addr >= 16'd32 && addr < 16'd36)
      aem_ovl_lookup = {1'b1, OVL_CTRL_CAP_C, 3'(addr - 16'd32)};
    if (addr >= 16'd36 && addr < 16'd40)
      aem_ovl_lookup = {1'b1, OVL_AVAIL_IDX_C, 3'(addr - 16'd36)};
    if (addr >= 16'd40 && addr < 16'd48)
      aem_ovl_lookup = {1'b1, OVL_ASSOC_ID_C, 3'(addr - 16'd40)};
    if (addr >= 16'd48 && addr < 16'd56)
      aem_ovl_lookup = {1'b1, OVL_ENT_NAME8_C, 3'(addr - 16'd48)};
    if (addr >= 16'd310 && addr < 16'd312)
      aem_ovl_lookup = {1'b1, OVL_CURRENT_CFG_C, 3'(addr - 16'd310)};
    if (addr >= 16'd1090 && addr < 16'd1096)
      aem_ovl_lookup = {1'b1, OVL_MAC_C, 3'(addr - 16'd1090)};
    if (addr >= 16'd1098 && addr < 16'd1106)
      aem_ovl_lookup = {1'b1, OVL_CLOCK_ID_C, 3'(addr - 16'd1098)};
  end
endfunction

// SET_* write-back base addresses
localparam [15:0] WB_SAMPLING_RATE_C = 16'd554;
localparam [15:0] WB_STREAM_FORMAT_C = 16'd948;
localparam [15:0] WB_STREAM_IN0_FMT_C = 16'd648;
localparam [15:0] WB_STREAM_IN1_FMT_C = 16'd802;
localparam [15:0] WB_CLOCK_SRC_IDX_C = 16'd1364;
localparam [15:0] WB_CONTROL_CUR_C = 16'd1482;
localparam [15:0] WB_AUDIO_MAP_0_C = 16'd3491;

// SET/GET_NAME qualifier: (type, index, name_index) + the directory
// oracle's REGISTERED answer -> {valid, rom addr}. Reads no ROM of
// its own (the level-2 directory is block RAM; a second read port
// here would be a second BRAM or a distributed copy): a masked
// type's object_name sits at descriptor base + 4, name_index 0, for
// every index of its run (generator-asserted 1:1 against the NAMED
// table - gen_aem_store.py named_structure/check_named), so the
// accessor's (found, base) for the SAME (type, index) already carry
// the lookup. Exceptions (ENTITY's entity_name/group_name) are
// constant matches. CALLER CONTRACT: acc_found/acc_base must be
// KL_aecp_accessor's answer for this (t, idx) at config 0.
localparam [63:0] AEM_NAMED_MASK_C = 64'h1004100666;
function automatic [16:0] aem_name_qual(input [15:0] t,
                                        input [15:0] idx,
                                        input [15:0] nidx,
                                        input        acc_found,
                                        input [15:0] acc_base);
  begin
    aem_name_qual = 17'd0;
    if (t == 16'h0000 && idx == 16'd0 && nidx == 16'd0)
      aem_name_qual = {1'b1, 16'd48};
    if (t == 16'h0000 && idx == 16'd0 && nidx == 16'd1)
      aem_name_qual = {1'b1, 16'd180};
    if (t < 16'(AEM_L1_N_C) && nidx == 16'd0 &&
        AEM_NAMED_MASK_C[t[5:0]] && acc_found)
      aem_name_qual = {1'b1, acc_base + 16'd4};
  end
endfunction

// Value validation tables
// CLOCK_SOURCE set: count, and the index of the CRF source
// (AEM_CRF_CLKSRC_C = 16'hFFFF when this shape declares no CRF source)
localparam int unsigned AEM_N_CLKSRC_C = 2;
localparam [15:0] AEM_CRF_CLKSRC_C = 16'd1;

localparam int AEM_RATES_N_C = 3;
localparam [31:0] AEM_RATES_C [0:2] = '{32'h0000BB80, 32'h00017700, 32'h0002EE00};
localparam [63:0] AEM_FMTS_C  [0:1] = '{64'h0205022000806000, 64'h0215022002006000};
localparam [63:0] AEM_CRF_FMTS_C [0:0] = '{64'h041060010000BB80};

// Static AUDIO_MAP serving tables (GET_AUDIO_MAP, 1722.1-2021 7.4.44).
// Per STREAM_PORT: the ROM address of the AUDIO_MAP that port's OWN
// base_map names, THAT descriptor's own number_of_mappings, and its
// own mappings_offset - because 7.2.19 says the mappings field "shall
// be accessed by using the mappings_offset field". All three used to
// be hardcoded in the RTL (descriptor index 1, 8 mappings, offset 8,
// 64 bytes), which on an 8x8 shape served STREAM_PORT_INPUT[1]'s
// 72-byte map to STREAM_PORT_OUTPUT[0] and read 48 B past its
// 24-byte one. ROWS = 0 marks a port with no static map - 7.2.13:
// "These Entities set the number_of_maps field to zero (0) and the
// base_map field is ignored when read." On a STREAM_PORT_OUTPUT that
// DOES have a map, ROWS != 0 is also the condition under which Milan
// v1.2 5.4.2.26 requires NOT_SUPPORTED rather than a served map.
localparam int unsigned AEM_SMAP_IN_N_C  = 1;
localparam int unsigned AEM_SMAP_OUT_N_C = 1;
localparam [15:0] AEM_SMAP_IN_ADDR_C [0:0] = '{16'd0};
localparam [15:0] AEM_SMAP_IN_ROWS_C [0:0] = '{16'd0};
localparam [15:0] AEM_SMAP_IN_MOFF_C [0:0] = '{16'd0};
localparam [15:0] AEM_SMAP_OUT_ADDR_C [0:0] = '{16'd3491};
localparam [15:0] AEM_SMAP_OUT_ROWS_C [0:0] = '{16'd8};
localparam [15:0] AEM_SMAP_OUT_MOFF_C [0:0] = '{16'd8};

// Dynamic audio-map engine (gaps item 8, roadmap 23): every
// map_mode-dynamic STREAM_PORT_INPUT carries no AUDIO_MAP
// descriptor and advertises number_of_maps=0 (1722.1-2021
// 7.2.13); ADD/REMOVE/GET are served by the RTL mappings store
// per Milan 5.4.2.26-28. Fully static shapes never emit this.
// The store key is the GLOBAL cluster index (PBASE + offset) =
// the render crossbar map-RAM address.
`define AEM_DYNMAP
localparam int unsigned AEM_DMAP_KEYS_C  = 8;   // global dynamic cluster keys (mono clusters)
localparam int unsigned AEM_DMAP_PAGE_C  = 8;   // GET_AUDIO_MAP fixed partition size (shared)
if (AEM_DMAP_PAGE_C > 9) $error("AEM_DMAP_PAGE_C %0d exceeds the GET_AUDIO_MAP const-scratch bound of 9 (8*PAGE + 5 <= 79)", AEM_DMAP_PAGE_C);
localparam int unsigned AEM_DMAP_PHYS_C  = 10;   // render crossbar depth (CHMAP_PHYS_C)
localparam int unsigned AEM_DMAP_NPORTS_C = 1;   // STREAM_PORT_INPUT descriptors
localparam bit AEM_DMAP_PDYN_C [0:0] = '{1'b1};
localparam [31:0] AEM_DMAP_PBASE_C [0:0] = '{32'd0};
localparam [31:0] AEM_DMAP_PCLS_C [0:0] = '{32'd8};
localparam [31:0] AEM_DMAP_PNMAPS_C [0:0] = '{32'd1};
// A STATIC port (input or output) is served from the shared
// AEM_SMAP_* tables above - one generated source for "what map
// does this port serve", static and dynamic shapes alike.
// Per-STREAM_INPUT mappability + reset channel count: a mapping
// names any STREAM_INPUT (Table 7-33) and 5.4.2.27 rejects a
// channel absent from THAT stream's current format.
localparam int unsigned AEM_DMAP_NSTRIN_C = 2;
localparam bit AEM_DMAP_SAAF_C [0:1] = '{1'b1, 1'b0};
localparam [9:0] AEM_DMAP_SCH_C [0:1] = '{10'd2, 10'd0};
