#!/usr/bin/env python3
"""Reconcile public receipts, source bytes, reconstructed overlay and sweep qualification."""
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys

repo=Path(sys.argv[1]).resolve()
packet=Path(__file__).resolve().parent
pub=packet/'scratch/published'
author=pub/'author'
base='e21c1ca024d37ea188ad15b5c8f9c2dae18628df'
head='35fb2a95007ce6dd1ec4f51c2dcb793800623cfd'
ring='2525eae9567865a8bc741901914bdf5a1caf2c26'
expected_overlay='01f65c3b2693d2b1c494e0738b9562a1778740b5'
def git(*args, **kw):
    return subprocess.check_output(['git',*args],cwd=repo,**kw)
def digest(data):return hashlib.sha256(data).hexdigest()
def read(name):return json.loads((author/name).read_text())

manifest=json.loads((pub/'MANIFEST.json').read_text())
for row in manifest:
    assert digest((pub/row['file']).read_bytes())==row['published_sha256'],row['file']
print(f'PASS public manifest: {len(manifest)} files')
env=dict(os.environ,GIT_INDEX_FILE=str(packet/'scratch/audit-overlay.index'))
subprocess.run(['git','read-tree',ring],cwd=repo,env=env,check=True)
subprocess.run(['git','apply','--cached'],cwd=repo,env=env,input=git('diff','--binary',base,head),check=True)
assert git('write-tree',env=env).decode().strip()==expected_overlay
print('PASS overlay reconstructed:',expected_overlay)
all_results={}
for name,tree in [('dev',head),('ring',expected_overlay)]:
    checked=[];generated=[]
    for row in read(name+'-synthesis-inputs.json'):
        prefix=f'$SCRATCH/{name}-test/'
        if not row['path'].startswith(prefix):
            generated.append(row);continue
        rel=row['path'][len(prefix):]
        sub=next((s for s in ('protocol-processor','gptp-processor','third_party/verilog-axis') if rel.startswith(s+'/')),None)
        if sub:
            oid=git('rev-parse',tree+':'+sub).decode().strip()
            data=subprocess.check_output(['git','show',oid+':'+rel[len(sub)+1:]],cwd=repo/sub)
        else:
            data=git('show',tree+':'+rel)
        assert len(data)==row['bytes'] and digest(data)==row['sha256'],rel
        checked.append({'path':rel,'sha256':row['sha256']})
    assert len(checked)==112 and len(generated)==4
    artifacts=read('ARTIFACTS.json')+read('ROUND1B-ARTIFACTS.json')
    for row in generated:
        rel=row['path'].removeprefix('$SCRATCH/')
        matches=[a for a in artifacts if a.get('path',a.get('scratch_relative_path'))==rel]
        assert matches and all(a['sha256']==row['sha256'] and a['bytes']==row['bytes'] for a in matches)
    all_results[name]={'source_files_checked':checked,'generated_receipts_reconciled':generated}
    print(f'PASS {name}: 112 source bytes independently match; four generated-input hashes reconcile with artifact receipts (generated bytes not downloaded)')

for name in ('capture','reset_before_d'):
    data=(packet/f'scratch/capture/{name}.v').read_bytes()
    entry=next(r for r in read('ARTIFACTS.json') if r['scratch_relative_path']==f'capture/{name}.v')
    assert len(data)==entry['bytes'] and digest(data)==entry['sha256'],name
    print('PASS regenerated fixture hash:',name,entry['sha256'])

rows=read('TIMING.json');gates=read('ROUND1B-GATES.json');artifacts=read('ROUND1B-ARTIFACTS.json')
assert len(rows)==6
expected={
 ('dev','ExtraPostPlacementOpt'):(.492,.040,1.660,.007),
 ('dev','AltSpreadLogic_high'):(.064,.052,1.638,.029),
 ('dev','ExtraTimingOpt'):(.098,.074,1.362,.036),
 ('ring','ExtraPostPlacementOpt'):(.238,.102,1.518,.036),
 ('ring','AltSpreadLogic_high'):(.227,.071,1.521,.035),
 ('ring','ExtraTimingOpt'):(.013,.069,1.561,.036)}
for row in rows:
    name,directive=row['tree'],row['directive']
    text=(author/f'{name}-{directive}-iob.rpt').read_text()
    census={k:len(re.findall('^'+k+r' +',text,re.M)) for k in ('PASS','INERT','FAIL')}
    assert census==row['iob']=={'PASS':21,'INERT':1,'FAIL':0}
    for port in ['eth0_rx_dv',*[f'eth0_rx_data[{i}]' for i in range(8)]]:
        assert re.search('^PASS  '+re.escape(port)+r': IN, .*ILOGIC_',text,re.M),port
    assert re.search(r'^INERT +eth0_rx_er:',text,re.M)
    artifact=next(a for a in artifacts if a['path']==f'{name}-timing/{directive}/alinx_ax7101_iob_pack.rpt')
    assert digest(text.encode())==artifact['sha256']
    assert len(row['timing'])==4
    for corner in row['timing']:
        offset=2 if '_Fast_' in corner['report'] else 0
        assert (corner['WNS'],corner['WHS'])==expected[(name,directive)][offset:offset+2]
        assert corner['TNS']==corner['THS']==0
        assert corner['margin_pass']==(corner['WNS']>=.030 and corner['WHS']>=0)
        assert any(a['path']==f'{name}-timing/{directive}/'+corner['report'] for a in artifacts)
    passed=all(c['margin_pass'] for c in row['timing'])
    assert row['rc']==(0 if passed else 1)
    assert row['status']==('PASS' if passed else 'FAIL')
    assert next(g for g in gates if g['label']==name+'-'+directive)['rc']==row['rc']
    print('PASS reconciliation:',name,directive,census,'Slow/Fast WNS/WHS',expected[(name,directive)],'qualification rc',row['rc'])
for name in ('dev','ring'):
    keep=max([r for r in rows if r['tree']==name],key=lambda r:min(c['WNS'] for c in r['timing']))
    assert keep['directive']=='ExtraPostPlacementOpt' and keep['rc']==0
    print('PASS kept-build margin:',name,keep['directive'])
for row in read('ROUND1B-CLOCK.json'):
    assert len(row['datapath_only_rows'])==4 and not row['unsafe_rows'] and not row['critical_warnings']
    assert all('8.00' in r and 'Max Delay Datapath Only' in r for r in row['datapath_only_rows'])
print('PASS six clock receipts: four 8 ns crossing rows each; no reported unsafe rows or critical warnings')
(packet/'source-input-audit.json').write_text(json.dumps(all_results,indent=2)+'\n')
print('LIMIT: raw full timing reports/checkpoints and generated full-image files are represented by public receipts and hashes; implementation was not rerun')
