#!/usr/bin/env python3
"""Scratch (never committed): generate the lockstep top for issue #230.

KL_srp_top_ref (the base RTL, every SRP module renamed with a _ref suffix) and
KL_srp_top (the RTL under test) get the same inputs every cycle. Every output
of the top is compared every cycle (diff_o, one bit per port), and so are the
talker, listener, admission and encoder-intake faces inside the top and the
timer-FIFO bookkeeping (idiff_o, one bit per signal). The ref's environment
faces go out to the C++ models.

usage: gen_top.py <KL_srp_top.sv of the RTL under test> <out.sv>
"""
import re
import sys

src = open(sys.argv[1]).read()
hdr = src[src.index("module KL_srp_top"):]
hdr = hdr[:hdr.index(");\n")]
params = hdr[hdr.index("#(") + 2:hdr.index(") (")]
ports = hdr[hdr.index(") (") + 3:]

decl = []
for line in ports.splitlines():
    line = line.split("//")[0].strip()
    if not line:
        continue
    m = re.match(r"(input|output)\s+(wire|logic)\s*(.*?)\s*(\w+)\s*,?$", line)
    assert m, line
    decl.append((m.group(1), m.group(3), m.group(4)))

inputs = [(r, n) for d, r, n in decl if d == "input"]
outputs = [(r, n) for d, r, n in decl if d == "output"]

# internal faces compared through hierarchical references (present in both)
INTERNAL = [
    "tk_dbg_app_w", "tk_dbg_reg_w", "ls_dbg_app_w", "ls_dbg_reg_w",
    "tk_ev_valid_w", "tk_ev_type_w", "tk_ev_event_w", "tk_ev_fp_w", "tk_ev_value_w",
    "ls_ev_valid_w", "ls_ev_type_w", "ls_ev_event_w", "ls_ev_fp_w", "ls_ev_value_w",
    "tk_txop_done_w", "ls_txop_done_w", "gate_ready_w", "ctl_ready_w",
    "tk_user_valid_w", "tk_user_join_w", "tk_user_vid_w",
    "ls_user_valid_w", "ls_user_join_w", "ls_user_vid_w",
    "tk_arm_v_w", "tk_arm_cancel_w", "tk_arm_slot_w", "tk_arm_owner_w", "tk_arm_dl_w",
    "ls_arm_v_w", "ls_arm_cancel_w", "ls_arm_slot_w", "ls_arm_owner_w", "ls_arm_dl_w",
    "adm_admitted_w", "adm_round_w", "sr_adm_fsm_w",
    "enc_ev_valid_w", "enc_ev_ready_w", "enc_ev_app_w", "enc_ev_type_w",
    "enc_ev_event_w", "enc_ev_fp_w", "enc_ev_value_w", "enc_ev_drop_w",
    "tf_push_w", "tf_pop_w", "tm_st_r", "tm_sel_r", "tm_rr_r",
]
# unpacked bookkeeping arrays: compared element by element
INTERNAL_IDX = ["tf_cnt_r", "tf_wptr_r", "tf_rptr_r"]

pnames = ["N_SOURCES_P", "N_SINKS_P", "JOIN_MS_P", "PERIODIC_MS_P", "LEAVE_MS_P",
          "SLOT_AW_P", "CAD_SLOT_BASE_P", "TK_SLOT_BASE_P", "LS_SLOT_BASE_P"]

o = []
o.append("// generated by gen_top.py (scratch, never committed)")
o.append("`default_nettype none")
o.append("module lockstep_top")
o.append("  import srp_pkg::*;")
o.append("#(" + params.rstrip().rstrip(",") + ") (")
pl = []
for r, n in inputs:
    pl.append(f"    input  wire  {r} {n}")
for r, n in outputs:
    pl.append(f"    output logic {r} {n}")
pl.append(f"    output logic [{len(outputs) - 1}:0] diff_o")
pl.append(f"    output logic [{len(INTERNAL) + 2 * len(INTERNAL_IDX) - 1}:0] idiff_o")
o.append(",\n".join(pl))
o.append(");")
for r, n in outputs:
    o.append(f"  logic {r} n_{n};")
for inst, mod, pre in (("u_ref", "KL_srp_top_ref", ""), ("u_new", "KL_srp_top", "n_")):
    o.append(f"  {mod} #(")
    o.append(",\n".join(f"      .{p} ({p})" for p in pnames))
    o.append(f"  ) {inst} (")
    conn = [f"      .{n} ({n})" for r, n in inputs]
    conn += [f"      .{n} ({pre}{n})" for r, n in outputs]
    o.append(",\n".join(conn))
    o.append("  );")
for k, (r, n) in enumerate(outputs):
    o.append(f"  assign diff_o[{k}] = ({n} != n_{n});")
for k, n in enumerate(INTERNAL):
    o.append(f"  assign idiff_o[{k}] = (u_ref.{n} != u_new.{n});")
base = len(INTERNAL)
for j, n in enumerate(INTERNAL_IDX):
    for u in range(2):
        o.append(f"  assign idiff_o[{base + 2 * j + u}] = (u_ref.{n}[{u}] != u_new.{n}[{u}]);")
o.append("endmodule")
o.append("`default_nettype wire")
open(sys.argv[2], "w").write("\n".join(o) + "\n")

names = [n for r, n in outputs]
inames = INTERNAL + [f"{n}[{u}]" for n in INTERNAL_IDX for u in range(2)]
with open(sys.argv[2] + ".names", "w") as f:
    f.write("\n".join(names) + "\n--\n" + "\n".join(inames) + "\n")
print(f"{len(inputs)} inputs, {len(outputs)} outputs, {len(inames)} internal")
