#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Kebag Logic
# SPDX-License-Identifier: CERN-OHL-W-2.0
"""Copy milan_datapath's grid-aligner keep-off declarations into an include.

Why this exists. coherence_wrap.sv binds KL_media_grid_align as
milan_datapath binds it, and the keep-off is the one part of that binding the
wrapper cannot reach: a localparam inside the datapath. Restated in the
wrapper as a literal it could drift from the shipped value while every leg
stayed green - a datapath keep-off halved to 128 cycles passed the whole
datapath leg (#617, R395-2 F2). So the build copies the datapath's own
declarations, MGA_SAMPLE_CYC_C and MGA_KEEPOFF_CYC_C, verbatim into the build
directory, and the wrapper elaborates them against its own clock. The
mutation arm's DP_SRC reaches the junction leg the same way.

Each declaration must appear exactly once, so a refactor that renames or
splits one fails the build here instead of binding something else. And the
datapath's aligner instance must bind LOCK_KEEPOFF_CYC_P to
MGA_KEEPOFF_CYC_C, the one binding in the file: a literal there (RM9, #617
R394-3 S1) would leave the declaration this copies at 256 while the datapath
ships another keep-off, which the datapath leg does not see and the wrapper,
binding the declaration, cannot.

Usage: python3 mga_keepoff.py <milan_datapath.sv> <out.svh>
Exit 0 = both declarations copied and the binding is the declaration's.
"""

import re
import sys
from pathlib import Path

#: the declarations the wrapper binds, in the datapath's order (the keep-off
#: is stated in terms of the sample period)
NAMES = ("MGA_SAMPLE_CYC_C", "MGA_KEEPOFF_CYC_C")
#: the aligner parameter the datapath must bind to the copied declaration
BINDING = ("LOCK_KEEPOFF_CYC_P", "MGA_KEEPOFF_CYC_C")

HEADER = ("// GENERATED by tb/verilator/capture_coherence/mga_keepoff.py from {src}:\n"
          "// milan_datapath's grid-aligner keep-off, verbatim. Do not edit.\n")


def declaration(src: str, name: str) -> str | None:
    """The one `localparam int unsigned <name> = ...;` statement, or None."""
    found = re.findall(rf"^[ \t]*localparam\s+int\s+unsigned\s+{name}\b[^;]*;", src, re.M)
    return found[0].strip() if len(found) == 1 else None


def bindings(src: str, param: str) -> list[str]:
    """Every `.<param> (<expr>)` named parameter binding, as its expression."""
    return [" ".join(expr.split()) for expr in re.findall(rf"\.{param}\s*\(([^()]*)\)", src)]


def main() -> int:
    """Write the include; 1 if a declaration or the binding is not as required."""
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    src_path = Path(sys.argv[1])
    src = src_path.read_text()
    decls = []
    for name in NAMES:
        decl = declaration(src, name)
        if decl is None:
            print(f"mga_keepoff.py: {src_path} does not declare `localparam int unsigned {name}` exactly "
                  f"once; the wrapper cannot bind the datapath's keep-off", file=sys.stderr)
            return 1
        decls.append(decl)
    param, decl_name = BINDING
    bound = bindings(src, param)
    if bound != [decl_name]:
        print(f"mga_keepoff.py: {src_path} does not bind {param} to {decl_name} exactly once (bindings "
              f"found: {bound}); the wrapper binds that declaration, so every sweep would grade a keep-off "
              f"the datapath does not ship", file=sys.stderr)
        return 1
    Path(sys.argv[2]).write_text(HEADER.format(src=src_path.name) + "\n".join(decls) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
