#!/usr/bin/env python3
"""After default_exports.py: compare sources for all configs and emitted files."""
import concurrent.futures, hashlib, json, os, pathlib, re, subprocess, sys
p=pathlib.Path(__file__).resolve().parents[1]
r=p/'scratch/export-tree'; out=p/'scratch/default-exports'
env=dict(os.environ,TMPDIR=str(p/'scratch'),PYTHONDONTWRITEBYTECODE='1',PYTHONHASHSEED='0')
fragments=json.loads((p/'receipts/default-fragments.json').read_text())
def run(job):
    cfg,kind,argv=job; dest=p/'scratch'/('sources-'+cfg+'-'+kind+'.json')
    entry=r/'sw/litex'/('review_base_soc.py' if kind=='base' else 'milan_soc.py')
    args=[sys.executable,str(p/'scripts/capture_default_sources.py'),str(dest),str(entry),*argv,
          '--entity-gen-dir',str(r/'configs/generated'/cfg),'--no-compile',
          '--output-dir',str(out/cfg/kind)]
    with (p/'scratch'/('source-capture-'+cfg+'-'+kind+'.log')).open('w') as f:
        subprocess.run(args,cwd=r,env=env,stdout=f,stderr=subprocess.STDOUT,timeout=500,check=True)
    text=dest.read_text().replace(str(out/cfg/kind),'$OUTPUT').replace(str(r),'$SOURCE')
    return cfg,kind,json.loads(text)
jobs=[(pathlib.Path(f['config']).stem,k,f['argv']) for f in fragments for k in ('base','head')]
with concurrent.futures.ThreadPoolExecutor(max_workers=2) as pool: captures=list(pool.map(run,jobs))
summary=[]
for f in fragments:
    cfg=pathlib.Path(f['config']).stem
    pair={kind:data for c,kind,data in captures if c==cfg}
    assert pair['base']==pair['head'],cfg+' source list differs'
    digest=hashlib.sha256(json.dumps(pair['head'],sort_keys=True).encode()).hexdigest()
    summary.append({'config':cfg,'source_count':len(pair['head']['sources']),'source_lists_equal':True,'source_list_sha256':digest})
    (p/'receipts'/('sources-'+cfg+'.json')).write_text(json.dumps(pair['head'],indent=2)+'\n')
    print(cfg,'source lists IDENTICAL',len(pair['head']['sources']),digest)
# Compare all successful exports except the non-deterministic build log.
for cfg,kind,rc,d in json.loads((p/'scratch/export-results.json').read_text()):
    if kind!='base' or rc: continue
    a=pathlib.Path(d); b=a.parent/'head'; comparisons=[]
    for file in sorted(a.rglob('*')):
        if not file.is_file() or file.name=='litex.log': continue
        rel=file.relative_to(a); other=b/rel
        x=file.read_bytes(); y=other.read_bytes(); raw_equal=x==y; rules=[]
        if not raw_equal:
            try:
                xx=x.decode(); yy=y.decode()
            except UnicodeDecodeError: raise AssertionError(str(rel)+' binary differs')
            xx=re.sub(r'^(//|#) Auto-generated by LiteX \(([^)]+)\) on .*$',r'\1 Auto-generated by LiteX (\2)',xx,flags=re.M)
            yy=re.sub(r'^(//|#) Auto-generated by LiteX \(([^)]+)\) on .*$',r'\1 Auto-generated by LiteX (\2)',yy,flags=re.M)
            rules.append('LiteX generation timestamp')
            # Comments contain generation time and unordered hierarchy display.
            if file.suffix=='.v':
                xx=re.sub(r'/\*.*?\*/','',xx,flags=re.S); yy=re.sub(r'/\*.*?\*/','',yy,flags=re.S)
                xx=re.sub(r'^// Date\s*:.*\n','',xx,flags=re.M); yy=re.sub(r'^// Date\s*:.*\n','',yy,flags=re.M)
                rules.append('block comments and generation-date comment')
            xx=xx.replace(str(a),'$OUTPUT'); yy=yy.replace(str(b),'$OUTPUT')
            rules.append('absolute output directory')
            x=xx.encode(); y=yy.encode()
        assert x==y,cfg+'/'+str(rel)+' differs after stated normalization'
        comparisons.append({'path':str(rel),'raw_equal':raw_equal,'normalization':rules,'compared_sha256':hashlib.sha256(x).hexdigest()})
    summary.append({'config':cfg,'export_files':comparisons})
    print(cfg,'emitted files IDENTICAL under recorded normalization:',len(comparisons))
(p/'receipts/default-comparison.json').write_text(json.dumps(summary,indent=2)+'\n')
