#!/usr/bin/python3 -S
import sys
sys.path.insert(0, '$WORKSPACE_HOME/milan-fpga-management/2026-09-22/517-f1-author/final-staged-backpressure/make-flush-SIGINT-active')
import fake_leg
fake_leg.main({'out': [['out', 'L9 partial\n']], 'name': 'L9', 'ledger': '$WORKSPACE_HOME/milan-fpga-management/2026-09-22/517-f1-author/final-staged-backpressure/make-flush-SIGINT-active/ledger.jsonl', 'announce': '$WORKSPACE_HOME/milan-fpga-management/2026-09-22/517-f1-author/final-staged-backpressure/make-flush-SIGINT-active/announce.fifo'})
