#///link1

set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rxd[0]}]
set_property PACKAGE_PIN N17 [get_ports {rgmii_rxd[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rxd[1]}]
set_property PACKAGE_PIN R18 [get_ports {rgmii_rxd[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rxd[2]}]
set_property PACKAGE_PIN T17 [get_ports {rgmii_rxd[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rxd[3]}]
set_property PACKAGE_PIN W19 [get_ports {rgmii_rxd[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_rx_ctl]
set_property PACKAGE_PIN P18 [get_ports rgmii_rx_ctl]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_rx_clk]
set_property PACKAGE_PIN N20 [get_ports rgmii_rx_clk]

set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_txd[0]}]
set_property PACKAGE_PIN Y16 [get_ports {rgmii_txd[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_txd[1]}]
set_property PACKAGE_PIN Y17 [get_ports {rgmii_txd[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_txd[2]}]
set_property PACKAGE_PIN Y18 [get_ports {rgmii_txd[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_txd[3]}]
set_property PACKAGE_PIN Y19 [get_ports {rgmii_txd[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_tx_ctl]
set_property PACKAGE_PIN P16 [get_ports rgmii_tx_ctl]
set_property IOSTANDARD LVCMOS18 [get_ports rgmii_tx_clk]
set_property PACKAGE_PIN P15 [get_ports rgmii_tx_clk]

set_property PACKAGE_PIN U20 [get_ports MDIO_link_1_mdio_io]
set_property IOSTANDARD LVCMOS18 [get_ports MDIO_link_1_mdio_io]
set_property PULLUP true [get_ports MDIO_link_1_mdio_io]
set_property PACKAGE_PIN T20 [get_ports MDIO_link_1_mdc]
set_property IOSTANDARD LVCMOS18 [get_ports MDIO_link_1_mdc]
set_property PULLUP true [get_ports MDIO_link_1_mdc]