#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Kebag Logic
# SPDX-License-Identifier: CERN-OHL-W-2.0
"""Emitters: one assembled model rendered as SVH text or as JSON.

Split out of `gen_aem_store.py` (Rule 12). Nothing here decides anything
about the model - it only writes one out, so a change to a rendering can
never move a byte in the ROM.

NO RTL CONSUMES THE .svh. It is a readable rendering of the declarative
model, written only where a caller asks for it with --out-dir; the AEM plane
that used to compile it is deleted (see `gen_aem_store`'s module docstring).

`gen_aem_store` re-exports every name here.
"""
import json
from collections.abc import Callable, Iterator, Sequence
from pathlib import Path
from typing import Any

from aem_assemble import SRC_IDS

# ------------------------------------------------------------- emitters ----
def emit_svh(M: dict[str, Any], path: str | Path) -> None:
    """Write the ROM include. The text itself comes from emit_svh_text() so a
    caller that wants the bytes without a file (sw/builder/endstation_builder
    .py emit_aem_rom_svh) gets the SAME generator, not a second one.

    `path` is accepted as a `str` too: callers outside this tree's own CLI
    hand it one, and the file this writes is compared byte for byte.
    """
    Path(path).write_text(emit_svh_text(M))

def _svh_header(M):
    """Provenance banner, the store's sizes and the descriptor directory."""
    rom_, directory_ = M["rom"], M["directory"]
    rom_size = M["ROM_SIZE"]
    lines = []
    a = lines.append
    a("// GENERATED by avdecc/gen_aem_store.py - DO NOT EDIT.")
    a("// Legacy SVH rendering of the selected builder entity model.")
    a("// See docs/ENDSTATION_BUILDER.md.")
    a("//")
    a("// NOT COMPILED BY ANY RTL (2026-08-12). This is a rendering of the")
    a("// DECLARATIVE entity model. The IEEE 1722.1 control plane that used to")
    a("// `include it (hdl/ieee17221/aecp/**, KL_aecp_aem_store) is DELETED and")
    a("// the protocol-processor submodule is the control plane now. It serves")
    a("// READ_DESCRIPTOR from the flat DRAM image emitted from this same model.")
    a("// The model also supplies the ADP")
    a("// shape - talker_stream_sources / listener_stream_sinks and the two")
    a("// capability words - via hdl/common/gen/adp_shape_defaults.svh.")
    a("")
    a(f"localparam int unsigned AEM_ROM_BYTES_C = {rom_size};")
    a(f"localparam int unsigned AEM_DESC_N_C    = {len(directory_)};")
    a("// Scratch tail (zero-init RAM past the descriptor image): Milan MVU")
    a("// media_clock_domain_name (64 B, Milan 1.3 §5.4.4.4)")
    a("localparam int unsigned AEM_STORE_BYTES_C = AEM_ROM_BYTES_C + 64;")
    a(f"localparam [15:0] WB_MCR_DOMNAME_C = 16'd{rom_size};")
    a("")
    a("// Descriptor directory: {type[15:0], index[15:0], base[15:0], len[15:0]}")
    a(f"localparam [63:0] AEM_DIR_C [0:{len(directory_)-1}] = '{{")
    for n, (t, i, b, l) in enumerate(directory_):
        sep = "," if n < len(directory_) - 1 else ""
        a(f"  64'h{t:04X}_{i:04X}_{b:04X}_{l:04X}{sep}")
    a("};")
    a("")
    return lines


def _svh_level1(M):
    """Level 1 of the directory: the type-direct-indexed count/row tables."""
    lines = []
    a = lines.append
    l1 = M["L1"]

    def rows16(vals: Sequence[int]) -> Iterator[str]:
        """`vals` as SV array-literal lines, eight 16-bit entries to a line."""
        for k in range(0, len(vals), 8):
            chunk = ", ".join(f"16'd{v}" for v in vals[k:k + 8])
            yield "  " + chunk + ("," if k + 8 < len(vals) else "")
    a("// Level 1 of the directory (type-direct-indexed): per-type runs in")
    a("// AEM_DIR_C are CONTIGUOUS, ZERO-BASED and ASCENDING (generator-")
    a("// asserted 1:1 against the linear scan - gen_aem_store.py")
    a("// check_two_level), so (type, index) resolves by ROM indexing alone:")
    a("//   hit = index < AEM_L1_CNT_C[type],")
    a("//   {base, len} = AEM_DIR_C[AEM_L1_ROW_C[type] + index][31:0].")
    a("// Zero-padded to 1 << AEM_L1_AW_C rows: an absent type reads count 0.")
    a(f"localparam int unsigned AEM_L1_AW_C = {l1['AW']};")
    a(f"localparam int unsigned AEM_L1_N_C  = {l1['N']};")
    a(f"localparam [15:0] AEM_L1_CNT_C [0:{l1['N'] - 1}] = '{{")
    for line in rows16(l1["CNT"]):
        a(line)
    a("};")
    a(f"localparam [15:0] AEM_L1_ROW_C [0:{l1['N'] - 1}] = '{{")
    for line in rows16(l1["ROW"]):
        a(line)
    a("};")
    a("")
    return lines


def _svh_rom_image(M):
    """The descriptor ROM itself, 16 bytes to a line."""
    rom_ = M["rom"]
    rom_size = M["ROM_SIZE"]
    lines = []
    a = lines.append
    a("// ROM image (network byte order, addr 0 = first byte of ENTITY)")
    a(f"localparam [7:0] AEM_ROM_INIT_C [0:{rom_size-1}] = '{{")
    row = []
    for n, byte in enumerate(rom_):
        row.append(f"8'h{byte:02X}")
        if len(row) == 16:
            sep = "," if n < rom_size - 1 else ""
            a("  " + ",".join(row) + sep)
            row = []
    if row:
        a("  " + ",".join(row))
    a("};")
    a("")
    return lines


def _svh_overlays(M):
    """The dynamic read overlays and the address->source lookup function."""
    lines = []
    a = lines.append
    a("// Dynamic read-overlay sources")
    for name, n in SRC_IDS.items():
        a(f"localparam [3:0] OVL_{name}_C = 4'd{n};")
    a("")
    a("// overlay lookup: rom addr -> {hit, source[3:0], byte_of_source[2:0]}")
    a("// byte_of_source 0 = MOST significant byte of the source value.")
    a("function automatic [7:0] aem_ovl_lookup(input [15:0] addr);")
    a("  begin")
    a("    aem_ovl_lookup = 8'h00;  // hit=0")
    for base, nb, src in M["OVERLAYS"]:
        a(f"    if (addr >= 16'd{base} && addr < 16'd{base + nb})")
        a(f"      aem_ovl_lookup = {{1'b1, OVL_{src}_C, 3'(addr - 16'd{base})}};")
    a("  end")
    a("endfunction")
    a("")
    return lines


def _svh_writeback(M):
    """SET_* write-back base addresses."""
    lines = []
    a = lines.append
    a("// SET_* write-back base addresses")
    for k, v in M["WB"].items():
        a(f"localparam [15:0] WB_{k}_C = 16'd{v};")
    a("")
    return lines


def _svh_name_qualifier(M):
    """SET/GET_NAME: the named-type mask and the qualifier function."""
    lines = []
    a = lines.append
    a("// SET/GET_NAME qualifier: (type, index, name_index) + the directory")
    a("// oracle's REGISTERED answer -> {valid, rom addr}. Reads no ROM of")
    a("// its own (the level-2 directory is block RAM; a second read port")
    a("// here would be a second BRAM or a distributed copy): a masked")
    a("// type's object_name sits at descriptor base + 4, name_index 0, for")
    a("// every index of its run (generator-asserted 1:1 against the NAMED")
    a("// table - gen_aem_store.py named_structure/check_named), so the")
    a("// accessor's (found, base) for the SAME (type, index) already carry")
    a("// the lookup. Exceptions (ENTITY's entity_name/group_name) are")
    a("// constant matches. CALLER CONTRACT: acc_found/acc_base must be")
    a("// KL_aecp_accessor's answer for this (t, idx) at config 0.")
    l1_aw = M["L1"]["AW"]
    a(f"localparam [{M['L1']['N'] - 1}:0] AEM_NAMED_MASK_C = "
      f"{M['L1']['N']}'h{M['NAME_MASK']:X};")
    a("function automatic [16:0] aem_name_qual(input [15:0] t,")
    a("                                        input [15:0] idx,")
    a("                                        input [15:0] nidx,")
    a("                                        input        acc_found,")
    a("                                        input [15:0] acc_base);")
    a("  begin")
    a("    aem_name_qual = 17'd0;")
    for t, i, nidx, addr in M["NAME_EXC"]:
        a(f"    if (t == 16'h{t:04X} && idx == 16'd{i} && nidx == 16'd{nidx})")
        a(f"      aem_name_qual = {{1'b1, 16'd{addr}}};")
    a("    if (t < 16'(AEM_L1_N_C) && nidx == 16'd0 &&")
    a(f"        AEM_NAMED_MASK_C[t[{l1_aw - 1}:0]] && acc_found)")
    a("      aem_name_qual = {1'b1, acc_base + 16'd4};")
    a("  end")
    a("endfunction")
    a("")
    return lines


def _svh_validation_tables(M):
    """What a SET_* value is checked against: clock sources, rates, formats."""
    lines = []
    a = lines.append
    a("// Value validation tables")
    # The COUNT, not just the table. KL_aecp_response_builder used to compare
    # a SET_SAMPLING_RATE against AEM_RATES_C[0], [1] and [2] literally, which
    # only worked while every config advertised exactly three rates: the 8x8
    # ship config honestly advertises ONE (audio_unit_rates_hz: [48000]), so
    # [1] and [2] read off the end of a [0:0] array - Verilator SELRANGE, and
    # in synthesis an out-of-range read is simply zero, so the check "passed"
    # by accident rather than by construction. Emit the bound and let the RTL
    # loop over it.
    # CLOCK_SOURCE shape. Emitted UNCONDITIONALLY (not inside the per-stream
    # block below): every shape has a CLOCK_DOMAIN, and the two facts the RTL
    # needs about it - how many sources exist, and which one is the CRF - were
    # hardcoded as "3" and "2" until 0x0042. Those literals are only right for
    # a 1-listener shape: the CLOCK_SOURCE set is internal, then ONE PER AAF
    # LISTENER, then CRF, so an 8-listener shape has 10 sources with CRF at 9.
    # A controller could not select the CRF clock there, and the servo would
    # have engaged on "Stream Clock 1" instead. Derive, never mirror.
    _n_cs, _crf_ix = M["N_CLKSRC"], M["CRF_CLKSRC"]
    a("// CLOCK_SOURCE set: count, and the index of the CRF source")
    a("// (AEM_CRF_CLKSRC_C = 16'hFFFF when this shape declares no CRF source)")
    a(f"localparam int unsigned AEM_N_CLKSRC_C = {_n_cs};")
    a(f"localparam [15:0] AEM_CRF_CLKSRC_C = 16'd{_crf_ix};"
      if _crf_ix is not None else
      "localparam [15:0] AEM_CRF_CLKSRC_C = 16'hFFFF;")
    a("")
    a(f"localparam int AEM_RATES_N_C = {len(M['RATES'])};")
    a(f"localparam [31:0] AEM_RATES_C [0:{len(M['RATES'])-1}] = "
      "'{" + ", ".join(f"32'h{r:08X}" for r in M["RATES"]) + "};")
    a(f"localparam [63:0] AEM_FMTS_C  [0:{len(M['FORMATS'])-1}] = "
      "'{" + ", ".join(f"64'h{f:016X}" for f in M["FORMATS"]) + "};")
    a(f"localparam [63:0] AEM_CRF_FMTS_C [0:{len(M['CRF_FMTS'])-1}] = "
      "'{" + ", ".join(f"64'h{f:016X}" for f in M["CRF_FMTS"]) + "};")
    a("")
    return lines


def _svh_per_stream(M):
    """Per-descriptor stream-format tables (multi-stream shapes only)."""
    lines = []
    a = lines.append
    ps = M["PER_STREAM"]
    if ps["EMIT"]:
        n_in, n_out = len(ps["IN_FMT0"]), len(ps["OUT_FMT0"])
        a("// Per-descriptor stream-format tables (multi-stream shapes only:")
        a("// the deployed 1-AAF-in/1-out shape keeps the legacy layout above")
        a("// byte-identical; KL_aecp_response_builder switches on this define)")
        a("`define AEM_PER_STREAM_FMT")
        a(f"localparam int unsigned AEM_N_STRIN_C  = {n_in};")
        a(f"localparam int unsigned AEM_N_STROUT_C = {n_out};")
        a(f"localparam bit AEM_STRIN_CRF_C [0:{n_in-1}] = "
          "'{" + ", ".join("1'b1" if c else "1'b0" for c in ps["IN_CRF"])
          + "};")
        a(f"localparam [63:0] AEM_STRIN_FMT_C [0:{n_in-1}] = "
          "'{" + ", ".join(f"64'h{f:016X}" for f in ps["IN_FMT0"]) + "};")
        a(f"localparam [63:0] AEM_STROUT_FMT_C [0:{n_out-1}] = "
          "'{" + ", ".join(f"64'h{f:016X}" for f in ps["OUT_FMT0"]) + "};")
        a(f"localparam [15:0] WB_STRIN_FMT_ADDR_C [0:{n_in-1}] = "
          "'{" + ", ".join(f"16'd{v}" for v in ps["IN_WB"]) + "};")
        a(f"localparam [15:0] WB_STROUT_FMT_ADDR_C [0:{n_out-1}] = "
          "'{" + ", ".join(f"16'd{v}" for v in ps["OUT_WB"]) + "};")
        a(f"localparam [15:0] WB_STRIN_FMT_CRF_C = 16'd{ps['IN_WB'][-1]};"
          "  // the CRF sink = the LAST STREAM_INPUT (Table 5.22 push arm)")
        a("")
    return lines


def _svh_static_maps(M):
    """Per-STREAM_PORT static AUDIO_MAP serving tables (every shape)."""
    lines = []
    a = lines.append
    sm = M["SMAP"]
    a("// Static AUDIO_MAP serving tables (GET_AUDIO_MAP, 1722.1-2021 7.4.44).")
    a("// Per STREAM_PORT: the ROM address of the AUDIO_MAP that port's OWN")
    a("// base_map names, THAT descriptor's own number_of_mappings, and its")
    a("// own mappings_offset - because 7.2.19 says the mappings field \"shall")
    a("// be accessed by using the mappings_offset field\". All three used to")
    a("// be hardcoded in the RTL (descriptor index 1, 8 mappings, offset 8,")
    a("// 64 bytes), which on an 8x8 shape served STREAM_PORT_INPUT[1]'s")
    a("// 72-byte map to STREAM_PORT_OUTPUT[0] and read 48 B past its")
    a("// 24-byte one. ROWS = 0 marks a port with no static map - 7.2.13:")
    a("// \"These Entities set the number_of_maps field to zero (0) and the")
    a("// base_map field is ignored when read.\" On a STREAM_PORT_OUTPUT that")
    a("// DOES have a map, ROWS != 0 is also the condition under which Milan")
    a("// v1.2 5.4.2.26 requires NOT_SUPPORTED rather than a served map.")
    a(f"localparam int unsigned AEM_SMAP_IN_N_C  = {sm['IN_N']};")
    a(f"localparam int unsigned AEM_SMAP_OUT_N_C = {sm['OUT_N']};")
    for nm in ("IN_ADDR", "IN_ROWS", "IN_MOFF",
               "OUT_ADDR", "OUT_ROWS", "OUT_MOFF"):
        v = sm[nm]
        a(f"localparam [15:0] AEM_SMAP_{nm}_C [0:{len(v)-1}] = "
          "'{" + ", ".join(f"16'd{x}" for x in v) + "};")
    a("")
    return lines


def _svh_dynamic_maps(M):
    """The listener- and talker-side dynamic audio-map engine constants."""
    lines = []
    a = lines.append
    dm = M["DYNMAP"]
    if dm["EMIT"]:
        def arr(t: str, name: str, vals: Sequence[Any],
                fmt: Callable[[Any], str] | None = None) -> None:
            """Emit one SV localparam array line, `fmt` per element."""
            if fmt is None:
                fmt = (lambda v: f"32'd{v}") if t == "[31:0]" else str
            a(f"localparam {t} {name} [0:{len(vals)-1}] = "
              "'{" + ", ".join(fmt(v) for v in vals) + "};")

        a("// Dynamic audio-map engine (gaps item 8, roadmap 23): every")
        a("// map_mode-dynamic STREAM_PORT_INPUT carries no AUDIO_MAP")
        a("// descriptor and advertises number_of_maps=0 (1722.1-2021")
        a("// 7.2.13); ADD/REMOVE/GET are served by the RTL mappings store")
        a("// per Milan 5.4.2.26-28. Fully static shapes never emit this.")
        a("// The store key is the GLOBAL cluster index (PBASE + offset) =")
        a("// the render crossbar map-RAM address.")
        a("`define AEM_DYNMAP")
        a(f"localparam int unsigned AEM_DMAP_KEYS_C  = {dm['KEYS']};"
          "   // global dynamic cluster keys (mono clusters)")
        a(f"localparam int unsigned AEM_DMAP_PAGE_C  = {dm['PAGE']};"
          "   // GET_AUDIO_MAP fixed partition size (shared)")
        #: A-F13: the GET page scan writes 6 + 8*PAGE bytes into an 80-byte
        #: const scratch, so PAGE > 9 would run off the end of const_q at
        #: RUNTIME. Codegen already refuses it; this makes a hand-edited svh
        #: die at ELABORATION instead, which is the only place left to catch
        #: it once the file is on disk.
        #: ONE string literal: SystemVerilog has no C-style adjacent
        #: string-literal concatenation, so a split message is a syntax error.
        a("if (AEM_DMAP_PAGE_C > 9) $error(\"AEM_DMAP_PAGE_C %0d exceeds "
          "the GET_AUDIO_MAP const-scratch bound of 9 (8*PAGE + 5 <= 79)\","
          " AEM_DMAP_PAGE_C);")
        a(f"localparam int unsigned AEM_DMAP_PHYS_C  = {dm['PHYS']};"
          "   // render crossbar depth (CHMAP_PHYS_C)")
        a(f"localparam int unsigned AEM_DMAP_NPORTS_C = {dm['NPORTS']};"
          "   // STREAM_PORT_INPUT descriptors")
        arr("bit", "AEM_DMAP_PDYN_C", dm["PDYN"],
            lambda v: "1'b1" if v else "1'b0")
        arr("[31:0]", "AEM_DMAP_PBASE_C", dm["PBASE"])
        arr("[31:0]", "AEM_DMAP_PCLS_C", dm["PCLS"])
        arr("[31:0]", "AEM_DMAP_PNMAPS_C", dm["PNMAPS"])
        a("// A STATIC port (input or output) is served from the shared")
        a("// AEM_SMAP_* tables above - one generated source for \"what map")
        a("// does this port serve\", static and dynamic shapes alike.")
        a("// Per-STREAM_INPUT mappability + reset channel count: a mapping")
        a("// names any STREAM_INPUT (Table 7-33) and 5.4.2.27 rejects a")
        a("// channel absent from THAT stream's current format.")
        a(f"localparam int unsigned AEM_DMAP_NSTRIN_C = {dm['NSTRIN']};")
        arr("bit", "AEM_DMAP_SAAF_C", dm["SAAF"],
            lambda v: "1'b1" if v else "1'b0")
        arr("[9:0]", "AEM_DMAP_SCH_C", dm["SCH"], lambda v: f"10'd{v}")
        a("")
    od = M.get("ODMAP", {"EMIT": False})
    if od["EMIT"]:
        a("// Talker-side dynamic audio-map engine (USER 08-01). Key = the")
        a("// port's STREAM channel (8 per port, ch[2:0] fabric bound);")
        a("// Milan 5.4.2.26's output partition is over Stream Output")
        a("// channels, <= 8, so number_of_maps is 1 for every port.")
        a("// CSRC = per-output-cluster capture-source template")
        a("// {valid, half, src[2:0], idxh[3:0], idx[3:0]}; INIT = the")
        a("// power-on identity image per key {v, cluster_offset[4:0]}.")
        a("`define AEM_ODYNMAP")
        a(f"localparam int unsigned AEM_ODMAP_KEYS_C   = {od['KEYS']};")
        a(f"localparam int unsigned AEM_ODMAP_NPORTS_C = {od['NPORTS']};")
        arr("bit", "AEM_ODMAP_PDYN_C", od["PDYN"],
            lambda v: "1'b1" if v else "1'b0")
        arr("[31:0]", "AEM_ODMAP_PCLS_C", od["PCLS"])
        arr("[31:0]", "AEM_ODMAP_PCBASE_C", od["PCBASE"])
        arr("[31:0]", "AEM_ODMAP_PSTR_C", od["PSTR"])
        arr("[31:0]", "AEM_ODMAP_SLOTB_C", od["SLOTB"])
        arr("[9:0]", "AEM_ODMAP_SCH_C", od["SCH"], lambda v: f"10'd{v}")
        arr("[12:0]", "AEM_ODMAP_CSRC_C", od["CSRC"],
            lambda s: "13'h{:04X}".format(
                ((1 if s.get("valid", True) else 0) << 12)
                | ((s.get("half", 0) & 1) << 11)
                | ((s["src"] & 7) << 8)
                | ((s.get("idxh", 0) & 0xF) << 4)
                | (s.get("idx", 0) & 0xF)))
        arr("[5:0]", "AEM_ODMAP_INIT_C", od["INIT"],
            lambda e: "6'h{:02X}".format(
                ((1 if e["v"] else 0) << 5) | (e["co"] & 0x1F)))
        a("")
    return lines


def emit_svh_text(M: dict[str, Any]) -> str:
    """The whole ROM include as text, one section per emitter, in ROM order.

    This is the single generator: emit_svh() writes what this returns, and the
    builder's emit_aem_rom_svh() renders the same string without a file, so
    the two cannot drift into two renderings of one model.
    """
    lines = []
    for section in (_svh_header, _svh_level1, _svh_rom_image, _svh_overlays,
                    _svh_writeback, _svh_name_qualifier,
                    _svh_validation_tables, _svh_per_stream,
                    _svh_static_maps, _svh_dynamic_maps):
        lines += section(M)
    return "\n".join(lines)


# emit_c_golden() is GONE (2026-08-12).  It wrote tb/verilator/aecp/aem_golden.h,
# the byte-exact image the aecp Verilator suite compared the RTL against; that
# suite and the RTL it exercised are both deleted, so the emitter had exactly
# zero consumers left.  Kept as a note rather than as dead code: a golden image
# with no harness is a file that goes stale silently and then gets believed.

def emit_json(M: dict[str, Any], path: str | Path) -> None:
    """Write the model to `path` as the aem_rom.json document: the ROM hex plus
    the four tables (directory, overlays, write-back, names) the Python
    measurement controller resolves descriptors through, so it never re-derives
    an address the generator already knows.

    `path` is accepted as a `str` too, for the same reason emit_svh() does.
    """
    with Path(path).open("w") as f:
        json.dump({
            "rom_hex": M["rom"].hex(),
            "directory": [
                {"type": t, "index": i, "base": b, "len": l}
                for (t, i, b, l) in M["directory"]],
            "overlays": [
                {"addr": a_, "bytes": n, "source": s}
                for (a_, n, s) in M["OVERLAYS"]],
            "writeback": M["WB"],
            "named": [
                {"type": t, "index": i, "name_index": n, "addr": a_}
                for (t, i, n, a_) in M["NAMED"]],
            "rates": M["RATES"],
            "formats": M["FORMATS"],
            "crf_formats": M["CRF_FMTS"],
        }, f, indent=1)
