#!/usr/bin/env python3
# SPDX-License-Identifier: CERN-OHL-W-2.0
"""Module↔testbench traceability matrix. --check fails on drift or on any
module with no suite (untested budget is ZERO — a new module with no
testbench fails CI outright, from day one)."""
import re, subprocess, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "traceability" / "MODULE_MATRIX.md"


def modules() -> dict[str, str]:
    """Every `module`/`package` name in hdl/, mapped to the file declaring it."""
    mods = {}
    for f in sorted(ROOT.glob("hdl/**/*.sv")):
        for m in re.findall(r"^\s*(?:module|package)\s+(\w+)", f.read_text(), re.M):
            mods[m] = f.relative_to(ROOT).as_posix()
    return mods


def suites() -> dict[str, set[str]]:
    """Source file basename -> the tb/ suites whose Makefile compiles it."""
    cover = {}
    for mk in sorted(ROOT.glob("tb/*/Makefile")):
        suite = mk.parent.name
        text = mk.read_text()
        for sv in re.findall(r"[\w./$()-]+\.sv", text):
            cover.setdefault(pathlib.Path(sv).name, set()).add(suite)
    return cover


def render() -> tuple[str, list[str]]:
    """The matrix page, and the module names no testbench covers."""
    mods, cov = modules(), suites()
    lines = ["<!-- SPDX-License-Identifier: CERN-OHL-W-2.0 -->",
             "# Module ↔ testbench matrix (generated by scripts/gen_matrix.py)",
             "", "| Module | File | Suites |", "|---|---|---|"]
    untested = []
    for m, f in sorted(mods.items()):
        s = sorted(cov.get(pathlib.Path(f).name, []))
        if not s:
            untested.append(m)
        lines.append(f"| `{m}` | `{f}` | {', '.join(s) if s else '⚪ UNTESTED'} |")
    lines += ["", f"Modules: {len(mods)} · untested: {len(untested)} (budget: 0)", ""]
    return "\n".join(lines), untested


def main() -> int:
    """--check reports drift or an untested module; otherwise rewrite the page."""
    body, untested = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != body:
            print("MATRIX FAIL: stale — regenerate with scripts/gen_matrix.py")
            return 1
        if untested:
            print(f"MATRIX FAIL: untested modules over budget 0: {untested}")
            return 1
        print(f"matrix: OK ({body.count('| `')} rows, 0 untested)")
        return 0
    OUT.write_text(body)
    if untested:
        print(f"WARNING untested: {untested}")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
