#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Kebag Logic
# SPDX-License-Identifier: CERN-OHL-W-2.0
"""Per-page annotated table of contents: generate, refresh, and gate.

Why this exists. The corpus is 157 pages and 885 sections, several past 600
lines, and a bare list of headings barely helps a reader landing on one, so
each entry carries a sentence saying what you get there. The split of
ownership is the point: THIS SCRIPT owns which sections exist, their order,
their nesting and their anchors, all read off the page so it cannot drift; A
HUMAN owns the description, the part that carries judgement. Descriptions
survive regeneration, keyed by anchor and copied forward, so a renamed
heading gets a fresh one rather than a stale sentence.

WHICH SECTIONS EXIST is the renderer's answer, not this script's. Every page
is parsed by cmark-gfm, the renderer GitHub uses, and its HTML is parsed as a
browser parses it (`gen_toc_renderer.py`, pinned with hashes in
`tools/markdown/requirements.txt`). A section is a heading that survives both
stages. This script reads that answer and keeps what it MEANS here: which
headings a Contents block lists, their labels and anchors, and whether a line
is generated navigation (#437 and #516, replacing a Markdown walk of its own).

Anchors follow GitHub's algorithm (lowercase; drop everything that is not
alphanumeric, space or hyphen; spaces to hyphens; `-1`, `-2` on collision).
`--verify-anchors` checks it against every `file.md#fragment` link in the
tree, the only independent evidence we have that it is right.

Usage:
    python3 scripts/gen_toc.py --check           # gate (exit 1 on drift/missing)
    python3 scripts/gen_toc.py --write           # insert/refresh every TOC
    python3 scripts/gen_toc.py --write PATH...   # just these pages
    python3 scripts/gen_toc.py --verify-anchors  # anchor algorithm vs real links
"""
import ast
import functools
import re
import subprocess
import sys
from collections.abc import Iterator
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_toc_renderer import (Node, RendererError,  # noqa: E402,F401
                              render as render_markdown)

REPO = Path(__file__).resolve().parent.parent

TOC_HEAD = "## Contents"
#: what the generator writes when it has no description yet. The gate REFUSES
#: this, so a freshly generated TOC is not mistakable for a finished one.
TODO = "TODO describe this section"

#: A page with fewer than this many top-level sections gets no TOC.
MIN_SECTIONS = 3

#: When `##` is thin but `###` carries the real structure (REGISTER_MAP.md
#: is 3 and 25), the TOC nests one level deeper.
NEST_WHEN_H2_BELOW = 5
NEST_WHEN_H3_ATLEAST = 8

#: The arm families the case tables carry, and a FLOOR under the total.
#: Nothing pinned an arm count, so a family dropped from the runner's
#: import printed a smaller total and exited 0 ([R86] suggestion, round 6
#: on PR #428). The floor rises with the corpus.
ARM_FAMILIES = ("walk", "tag", "guard", "heading", "predecessor",
                "provenance", "refusal", "I440", "shape")
MIN_ARMS = 1433

#: Pages that are deliberately TOC-free, with the reason.
SKIP = {
    "README.md":       "landing page - it IS a table of contents",
    "docs/README.md":  "documentation index - it IS a table of contents",
}

#: The blanks CommonMark 2.1 names, spaces and tabs, and no other character.
BLANK = " \t"
#: The characters at which PYTHON'S notion of whitespace and the
#: renderer's disagree: everything `str.isspace()` accepts but the space,
#: the tab and the line feed. A page carrying one is REFUSED (`refusals()`),
#: on EITHER side a decision is read from.
REFUSED = ("\v\f\r\x1c\x1d\x1e\x1f\x85\xa0\u1680\u2000\u2001\u2002"
           "\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u2028"
           "\u2029\u202f\u205f\u3000")

#: A page written by a generator must not be hand-edited: the next run
#: discards whatever was added. Both spellings this tree uses are matched,
#: `do not hand-edit` and a bare bold **GENERATED**; missing either made
#: `gen_module_matrix.py --check` report a page STALE.
GENERATED_RE = re.compile(
    r"auto-?generated|generated file|generated by|generated script"
    r"|regenerate with|do not hand-?edit|do not edit|\*\*GENERATED\b", re.I)
GENERATED_SCAN_LINES = 12

#: What a line is, for every reader in this repository. The names are what a
#: finding calls the line, so they read as English in a message.
TEXT, FENCE, COMMENT, CODE, HTML = ("prose line", "fenced line",
                                    "commented line", "indented code line",
                                    "raw HTML line")
#: What `line_kinds()` adds for a line of rendered Markdown text.
HEADING_LINE, TABLE_ROW = "heading", "table row"


def refusals(text: str) -> list[tuple[int, int, str]]:
    """Every position this walk REFUSES to read: (line, column, character).
    Every character in `REFUSED` is named with its page, line, column and
    code point. Such a page obtains no provenance and so no exemption. The
    raw `blocks()` and `headings()` helpers do not apply this policy
    themselves; their callers must check it.

    IT BINDS EVERY PAGE A DECISION IS READ FROM, or it holds nothing: the
    branch page provenance comes from AND the base page whose headings
    decide the label (`check_em_dash.base_labels`, [R85] F1, [R86] F2, round
    10 on PR #428).

    WHY IT OUTLIVES THE WALK IT WAS WRITTEN FOR. The renderer now decides
    what every line is (#437), but this script still reads a page in
    Python: a line is what `text.split("\\n")` gives, where the renderer
    also ends a line at a lone carriage return, and a label, an anchor and
    the Contents heading are compared after `str.strip()`, which drops every
    character here where the renderer drops only spaces and tabs. The policy
    is unchanged; only its reason moved. There are 26 and no page in the
    corpus carries one. Both shipped readers translate line endings first,
    `Path.read_text()` in the generator and git in text mode in the gate.
    """
    return [(n, col, char)
            for n, line in enumerate(text.split("\n"), 1)
            for col, char in enumerate(line, 1) if char in REFUSED]


def refusal_notes(name: str, text: str) -> list[str]:
    """One message per refused position, naming the page and the character."""
    return [f"{name}:{n}: U+{ord(char):04X} at column {col} is neither a "
            f"space nor a tab, so this walk does not read the page (use a "
            f"space or a tab)" for n, col, char in refusals(text)]


def _renderer_lines(text: str) -> tuple[list[str], list[int]]:
    """The lines the RENDERER reads, and the `text.split("\\n")` row each
    starts on. The renderer ends a line at a line feed, a carriage return
    and line feed, or a lone carriage return; that split keeps a lone
    carriage return inside a row, so two renderer lines can share one."""
    lines, rows, row, start = [], [], 0, 0
    for at, char in enumerate(text):
        if char == "\n" or (char == "\r" and text[at + 1:at + 2] != "\n"):
            lines.append(text[start:at].removesuffix("\r"))
            rows.append(row)
            row, start = row + (char == "\n"), at + 1
    lines.append(text[start:])
    rows.append(row)
    return lines, rows


def _rows(node: Node, rows: list[int], count: int) -> range:
    """The `text.split("\\n")` rows one block covers.

    A raw HTML block and an indented code block cover exactly the lines of
    their literal: the renderer reports a raw HTML block's end one line
    short when its end condition closes it, and an indented code block's
    trailing blank lines are not part of it. Every other block covers the
    lines the renderer reports."""
    last = node.last
    if node.kind == "html_block" or (node.kind == "code_block"
                                     and not node.fenced):
        last = node.first + node.literal.count("\n") - 1 + (
            not node.literal.endswith("\n"))
    first = rows[min(node.first, len(rows)) - 1]
    last = rows[min(max(last, node.first), len(rows)) - 1]
    return range(first, min(last, count - 1) + 1)


def _atx_text(line: str) -> str:
    """The raw content of an ATX heading line read from its first hash:
    CommonMark 4.2's rule. The opening run is dropped; a closing run is
    dropped only when a space or a tab precedes it or nothing else is left,
    so `## Old ## bar` is `Old ## bar` and `## Old#` is `Old#`; the blanks
    around what remains are stripped, and only spaces and tabs are blanks
    ([R86] F2, rounds 4 and 5 on PR #428). The RENDERER has already decided
    that the line is a heading and that it renders; this reads its label."""
    rest = line.lstrip("#").rstrip(BLANK)
    body = rest.rstrip("#")
    if body != rest and (not body or body[-1] in BLANK):
        rest = body
    return rest.strip(BLANK)


@functools.lru_cache(maxsize=512)
def _page(text: str) -> tuple[tuple[str, ...], tuple[str, ...],
                              tuple[tuple[int, str, int, str], ...]]:
    """(block labels, line kinds, headings) of one page, as rendered.

    A code block's lines are FENCE or CODE and a raw HTML block's lines are
    HTML, or COMMENT when the block is an HTML comment. The lines of a
    block whose element the HTML parse swallowed (into a comment, an
    attribute value or a `<select>`) are COMMENT: they render as nothing.
    Every other line is TEXT, refined to a heading or a table row. A heading
    is (level, raw text, row, rendered text) for each heading element that
    survives, in the rendered document's order. Its raw text is read off its
    own source line for an ATX heading, which keeps every label written
    before the renderer byte-identical, and is the rendered text for a
    setext one, whose line breaks the anchor drops as GitHub's does."""
    rendered = render_markdown(text)
    rows_of = text.split("\n")
    lines, rows = _renderer_lines(text)
    labels, kinds = [TEXT] * len(rows_of), [TEXT] * len(rows_of)
    shown = {position for _, position, _ in rendered.shown if position}
    heads = {}
    for node in rendered.nodes:
        block = {"code_block": FENCE if node.fenced else CODE,
                 "html_block": COMMENT if node.literal.lstrip(" ").startswith(
                     "<!--") else HTML}.get(node.kind)
        kind = {"heading": HEADING_LINE, "table": TABLE_ROW}.get(node.kind)
        for row in _rows(node, rows, len(rows_of)):
            labels[row] = block or labels[row]
            kinds[row] = kind or kinds[row]
        if node.kind == "heading":
            heads[node.position] = node
    for node in rendered.nodes:
        if node.element and node.position not in shown:
            for row in _rows(node, rows, len(rows_of)):
                labels[row] = COMMENT
    found = []
    for tag, position, rendered_text in rendered.shown:
        node = heads.get(position)
        if node is None or tag != f"h{node.level}":
            continue
        raw = rendered_text
        if node.last == node.first:
            line = lines[node.first - 1].encode("utf-8")
            raw = _atx_text(line[node.column - 1:].decode("utf-8", "replace"))
        found.append((node.level, raw, rows[node.first - 1], rendered_text))
    return tuple(labels), tuple(kinds), tuple(found)


def blocks(text: str) -> list[str]:
    """What every line of ``text`` is: TEXT, FENCE, COMMENT, CODE or HTML.

    ONE answer, and the only one in this repository that decides which
    lines are NAVIGATION: a gate that re-derived it disagreed with this
    generator about which lines are headings, five review rounds running
    on PR #384. THREE other gates carry a fence and comment toggle of
    their own for a different question (`docs_check.py` a wording
    deny-list, `check_feature_status.py` status tables, `check_doc_style.py`
    the sentence-length limits in its `prose_blocks()`); none decides what
    a line IS.

    THE RENDERER DECIDES (`_page()`). A fenced or indented code block, a
    raw HTML block and an HTML comment block are the blocks cmark-gfm parsed,
    containers included: a fence in a list item or a block quote is a fence,
    and a line indented into an item's content is that item's text. A block
    the HTML parse swallows renders as nothing and is COMMENT, which is how
    a heading after a raw `<!--` GitHub leaves open is hidden (#516). A
    blank line that ends a raw HTML block is not part of it. Nothing here
    reads Markdown syntax; `refusals()` names the pages this script will not
    read, and a caller must apply it.
    """
    return list(_page(text)[0])


def line_kinds(text: str) -> list[str]:
    """`blocks()`, refined for the lines that are rendered Markdown text: a
    line of a heading, a line of a table, or prose. This is what a finding
    names, and it is the owner's answer rather than a second reader's."""
    labels, kinds, _ = _page(text)
    return [kind if label == TEXT else label
            for label, kind in zip(labels, kinds)]


#: One Contents entry as this script writes it: the label, the anchor, the
#: separator (U+2014 on the pages that predate the em-dash rule, `--` on
#: every block written since) and the description. check_em_dash.py reads
#: entries with this expression, so the gate and the generator cannot
#: disagree on what an entry is. Indentation is bounded at three, which
#: still renders as a list item ([R0] round 4 on PR #384).
TOC_ENTRY_RE = re.compile(
    r"[ ]{0,3}-[ \t]+(?:\*\*)?\[([^\]]*)\]\(#([^)]*)\)(?:\*\*)?"
    r"[ \t]*(\u2014|--)[ \t]*(.*)")


def anchor(text: str, seen: dict[str, int]) -> str:
    """GitHub's heading-anchor algorithm."""
    a = text.strip().lower()
    a = re.sub(r"[^\w\- ]", "", a, flags=re.UNICODE)  # \w keeps digits/underscore
    a = a.replace(" ", "-")
    n = seen.get(a, 0)
    seen[a] = n + 1
    return a if n == 0 else f"{a}-{n}"


def strip_md(text: str) -> str:
    """Heading text as a reader sees it: no backticks, no link syntax, no bold."""
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    text = text.replace("`", "")
    text = re.sub(r"\*\*([^*]*)\*\*", r"\1", text)
    return text.strip()


def label(text: str) -> str:
    """strip_md, then make it safe as the text of a **bold** link.

    A heading like ``## 2. Per-module HDL pages (`hdl/**/doc/*.md`)`` keeps
    a literal `**` once the backticks come off, closing the entry's bold
    early, so any surviving asterisk is escaped. A setext heading's text can
    span lines; an entry is one line, so a line break reads as a space."""
    return strip_md(text).replace("*", r"\*").replace("\n", " ")


def headings(text: str) -> list[tuple[int, str, str]]:
    """(level, raw_text, anchor) for every heading that renders as one.

    A heading is what the renderer draws as one (`_page()`): ATX and
    setext, at the top level or inside a list item, a block quote or a
    referenced footnote. Anything it draws as text or hides is no heading
    and its label no evidence of an anchor ([R0] round 5 F2 on PR #384): a
    heading inside a fence, an indented code block, a raw HTML block, or
    after a raw `<!--` the page leaves open (#516). A heading written as
    raw HTML is not listed. Anchors are numbered over ALL headings in the
    rendered order, GitHub counting collisions page-wide."""
    seen = {}
    return [(level, raw, anchor(strip_md(raw), seen))
            for level, raw, _, _ in _page(text)[2]]


def rendered_headings(text: str) -> list[tuple[int, str]]:
    """(level, text) of every heading `headings()` lists, the text as the
    renderer shows it with its blanks collapsed: what a recorded GitHub
    rendering of the same page is compared with (`gen_toc_shape_cases`)."""
    return [(level, " ".join(shown.split()))
            for level, _, _, shown in _page(text)[2]]


def plan(text: str) -> list[tuple[int, str, str]] | None:
    """Which headings belong in this page's TOC, or None if it gets none."""
    hs = headings(text)
    h2 = [h for h in hs if h[0] == 2 and h[1].strip() != TOC_HEAD[3:]]
    h3 = [h for h in hs if h[0] == 3]
    if len(h2) < MIN_SECTIONS:
        return None
    nest = len(h2) < NEST_WHEN_H2_BELOW and len(h3) >= NEST_WHEN_H3_ATLEAST
    want = {2, 3} if nest else {2}
    return [h for h in hs if h[0] in want and h[1].strip() != TOC_HEAD[3:]]


def existing(
        text: str) -> tuple[dict[str, str], int | None, int | None, str | None]:
    """Descriptions keyed by anchor, the TOC span, and its separator. The
    span is located through `blocks()`, so a `## Contents` heading inside
    a fence, a comment, an indented code block or a raw HTML block is an
    example and not this page's own."""
    lines, kinds = text.split("\n"), blocks(text)
    start = next((i for i, l in enumerate(lines)
                  if kinds[i] == TEXT and l.strip() == TOC_HEAD), None)
    if start is None:
        return {}, None, None, None
    end = start + 1
    while end < len(lines) and not (kinds[end] == TEXT
                                    and lines[end].startswith("## ")):
        end += 1
    desc, separator = {}, None
    for i in range(start, end):
        m = TOC_ENTRY_RE.match(lines[i]) if kinds[i] == TEXT else None
        if m:
            desc[m.group(2)] = m.group(4).strip()
            if separator is None:
                separator = m.group(3)
    return desc, start, end, separator


def render(items: list[tuple[int, str, str]], desc: dict[str, str],
           separator: str) -> list[str]:
    """The Contents block itself, with each surviving description put
    back. A heading with no description carried forward gets `TODO`, which
    the gate refuses: the sentence after the separator is a human's."""
    out = [TOC_HEAD, ""]
    for lvl, raw, anc in items:
        lab = label(raw)
        d = desc.get(anc, TODO)
        if lvl == 2:
            out.append(f"- **[{lab}](#{anc})** {separator} {d}")
        else:
            out.append(f"  - [{lab}](#{anc}) {separator} {d}")
    out.append("")
    return out


def apply(path: Path, text: str) -> str | None:
    """Return the page with its TOC inserted/refreshed, or None if unchanged."""
    items = plan(text)
    desc, start, end, separator = existing(text)
    lines = text.split("\n")

    if items is None:
        if start is None:
            return None
        del lines[start:end]                      # too few sections now
        return "\n".join(lines)

    # A page keeps the separator it has; a block written for the first time
    # uses `--`, the only separator the em-dash rule lets a change add.
    block = render(items, desc, separator or "--")
    if start is not None:
        lines[start:end] = block
    else:
        first = next((i for i, l in enumerate(lines) if l.startswith("## ")), None)
        if first is None:
            return None
        lines[first:first] = block
    new = "\n".join(lines)
    return None if new == text else new


def owns(relpath: str, text: str) -> bool:
    """Whether THIS script writes the Contents block of ``relpath``. One
    population, read by `pages()` and by every tool that asks about
    provenance: the historical tree is frozen, `SKIP` names the two
    indexes that ARE tables of contents, and a generator-owned page
    belongs to its generator ([R0] round 6 on PR #384)."""
    if relpath.startswith("docs/history/v1/") or relpath in SKIP:
        return False
    head = "\n".join(text.split("\n")[:GENERATED_SCAN_LINES])
    return not GENERATED_RE.search(head)


def generated_block(text: str,
                    relpath: str | None = None) -> tuple[int, list[str]] | None:
    """Where this page's Contents block starts and the exact lines THIS
    SCRIPT renders for it, or None when the page carries no block, its
    block is not what this script would write, or the walk refuses it.
    It is the provenance answer other tools ask for: a line is generated
    navigation if it is byte-identical to the line here, at its own
    position, on a page this script owns and READS -- a page outside
    `owns()` answers None, and so does one the walk refuses
    (`refusals()`). `check_em_dash.py` exempts a copied heading label only
    on that answer, so no second reader decides what navigation is; five
    rounds of PR #384 showed that it decides differently.
    """
    if refusals(text) or (relpath is not None and not owns(relpath, text)):
        return None
    items = plan(text)
    desc, start, end, separator = existing(text)
    if items is None or start is None:
        return None
    block = render(items, desc, separator or "--")
    if text.split("\n")[start:end] != block:
        return None
    return start, block


def pages() -> Iterator[Path]:
    """Every hand-written .md the gate has an opinion about.

    The corpus comes from `git ls-files`, THE INDEX, which can name a page
    that is not on disk. That raised FileNotFoundError and took the whole
    run down, and a gate that dies on one path reports NOTHING about the
    other hundred-odd, so a vanished page is SKIPPED and NAMED.
    """
    out = subprocess.run(["git", "-C", str(REPO), "ls-files", "-z", "*.md"],
                         capture_output=True, text=True, check=True).stdout
    for p in sorted(filter(None, out.split("\0"))):
        md = REPO / p
        if not md.is_file():
            if owns(p, ""):
                print(f"  GONE  {p}: tracked in the index but not on disk "
                      f"(stage the deletion, or restore the file) - skipped")
            continue
        if owns(p, md.read_text()):
            yield md


def verify_anchors() -> int:
    """Check the anchor algorithm against `file.md#frag` links people wrote."""
    ok = bad = 0
    for md in pages():
        for m in re.finditer(r"\]\(([^)\s]+\.md)#([^)\s]+)\)", md.read_text()):
            tgt = (md.parent / m.group(1))
            if not tgt.exists():
                continue
            if m.group(2) in {a for _, _, a in headings(tgt.read_text())}:
                ok += 1
            else:
                bad += 1
                print(f"  MISS {md.relative_to(REPO)} -> {m.group(1)}#{m.group(2)}")
    print(f"anchor check: {ok} existing cross-page fragment links reproduced"
          f"{f', {bad} NOT reproduced' if bad else ''}")
    return 1 if bad else 0


def _tally_guards(families: dict[str, list], scored: int) -> list[str]:
    """What the ARM TALLY must satisfy before a single arm is scored: every
    family present and carrying arms, at least `MIN_ARMS` in all, and
    every arm the tables hold reaching the runner. A family dropped from
    the runner's import printed `PASS (94/94 arm(s))` and exited 0 ([R86]
    suggestion, round 6 on PR #428); `scored` is what it really reads.
    """
    bad = [f"arm family {name!r} is missing or empty"
           for name in ARM_FAMILIES if not families.get(name)]
    total = sum(len(arms) for arms in families.values())
    if total < MIN_ARMS:
        bad.append(f"{total} arm(s) in all, below the {MIN_ARMS} recorded")
    if scored != total:
        bad.append(f"{scored} arm(s) reach the runner of the {total} the "
                   "tables hold")
    return bad


def _owner_guards(name: str, source: str, values: dict) -> list[str]:
    """That a module beside the walk - the case tables, the renderer's
    binding - carries no classification of its OWN: it imports no expression
    engine and holds no compiled expression, so no rule for what a line is
    can grow outside the renderer and this script, which #413 names as the
    one owner of block classification ([R85] suggestion, round 6 on PR
    #428; the renderer replaced the walk in #437). The imports are read off its
    syntax tree and the compiled expressions off its values, so prose
    naming the engine cannot trip it and an alias cannot slip past it.
    WHAT IT CANNOT SEE: those two and nothing else, so plain string
    methods, an engine reached through `importlib` and a third-party
    engine all pass it, each measured ([R85] suggestion, round 7). It is a
    structural proxy; the proof is that the runner and every arm live here.
    """
    bad, imported = [], set()
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.Import):
            imported |= {a.name.split(".")[0] for a in node.names}
        elif isinstance(node, ast.ImportFrom):
            imported.add((node.module or "").split(".")[0])
    if re.__name__ in imported:
        bad.append(f"{name} imports the expression engine: every expression "
                   "that classifies a line belongs beside the walk")
    compiled = sorted(n for n, v in values.items() if isinstance(v, re.Pattern))
    if compiled:
        bad.append(f"{name} holds compiled expression(s) {compiled}: "
                   "the same rule")
    return bad


def selftest() -> int:
    """Run every arm family. 0 when every one holds.

    The RUNNER and every rule it scores live here because this script owns
    the walk: a gate that carried its own copy refused a legitimate page
    and exempted three that render nothing ([R0] rounds 4 and 5 on PR
    #384). Only the case TABLES sit next door ([R86] suggestion, round 5
    on PR #428). The import is inside this body because that module
    imports this one, and this module is registered under its own NAME
    first, or the families would be scored against a second copy of the
    walk ([R85] suggestion, round 6).
    """
    sys.modules.setdefault("gen_toc", sys.modules[__name__])
    import gen_toc_cases as cases
    import gen_toc_closer_cases as closers
    import gen_toc_renderer as renderer
    import gen_toc_renderer_cases as renderer_cases
    import gen_toc_shape_cases as shapes
    families = {"walk": cases.walk_arms(), "tag": cases.tag_arms(),
                "guard": cases.guard_arms(), "heading": cases.heading_arms(),
                "predecessor": cases.predecessor_arms(),
                "provenance": cases.provenance_arms(),
                "refusal": cases.refusal_arms(), "I440": closers.closer_arms(),
                "shape": shapes.shape_arms()}
    on_walk = families["walk"] + families["tag"] + families["I440"]
    on_page = (families["provenance"] + families["predecessor"]
               + families["heading"] + families["guard"]
               + families["refusal"] + families["shape"])
    arms = len(on_walk) + len(on_page)
    notes = _tally_guards(families, arms)
    for beside in (cases, closers, shapes, renderer_cases,
                   renderer):  # none may hold a rule
        src = Path(beside.__file__)
        notes += _owner_guards(src.name, src.read_text(), vars(beside))
    for note in notes:
        print(f"  GUARD {note}")
    problems = len(notes)
    for name, page, holds in on_walk:
        if not holds(blocks(page)):
            problems += 1
            print(f"  FAIL [{name}]: {blocks(page)}")
    for name, page, holds in on_page:
        if not holds(page):
            problems += 1
            print(f"  FAIL [{name}]")
    print(f"TOC selftest: {'PASS' if not problems else 'FAIL'} "
          f"({arms - problems}/{arms} arm(s))")
    return 1 if problems else 0


def main() -> int:
    """Run one arm: `--selftest`, `--verify-anchors`, `--write`, or the gate.

    `--check` is the default and separates a page with no contents list
    from one whose list has drifted: the two need different work from
    whoever reads it. A page the walk does not read is NAMED and left
    alone, neither written nor judged: the refusal is a limit on what this
    script may answer, not a rule about what a page may carry, and failing
    the workflow on one made it a rule no authoritative document states
    ([R85] F5, round 10 on PR #428).
    """
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    flags = {a for a in sys.argv[1:] if a.startswith("--")}

    if "--selftest" in flags:
        return selftest()
    if "--verify-anchors" in flags:
        return verify_anchors()

    targets = [Path(a).resolve() for a in args] if args else list(pages())
    changed, missing, stale, refused = [], [], [], []

    for md in targets:
        text = md.read_text()
        rel = md.relative_to(REPO)
        notes = refusal_notes(str(rel), text)
        for note in notes:
            print(f"  NOT READ  {note}")
        if notes:
            refused.append(rel)
            continue
        new = apply(md, text)
        if "--write" in flags:
            if new is not None:
                md.write_text(new)
                changed.append(rel)
            continue
        # --check
        if new is not None:
            (missing if TOC_HEAD not in text else stale).append(rel)
        elif TOC_HEAD in text:
            desc, _, _, _ = existing(text)
            if any(d == TODO or not d for d in desc.values()):
                stale.append(rel)

    read = [md for md in targets if md.relative_to(REPO) not in refused]
    unread = f", {len(refused)} page(s) not read" if refused else ""
    if "--write" in flags:
        todo = sum(1 for md in read
                   if TOC_HEAD in md.read_text()
                   for d in existing(md.read_text())[0].values() if d == TODO)
        print(f"TOC: {len(changed)} page(s) written{unread}"
              f"{f', {todo} description(s) still {TODO!r}' if todo else ''}")
        return 0

    if missing or stale:
        for p in missing:
            print(f"  NO TOC    {p}  (>= {MIN_SECTIONS} sections and no '{TOC_HEAD}')")
        for p in stale:
            print(f"  TOC DRIFT {p}  (headings changed, or a description is "
                  f"still {TODO!r})")
        print(f"\n{len(missing) + len(stale)} page(s) need attention. "
              f"Run: python3 scripts/gen_toc.py --write <page>\n"
              f"then WRITE the description for each entry - the generator "
              f"cannot, and a list that only repeats the headings is not "
              f"worth the space it takes.")
        return 1

    n = sum(1 for md in read if TOC_HEAD in md.read_text())
    print(f"TOC gate: OK ({n} page(s) carry an annotated contents list, "
          f"{len(read) - n} below the {MIN_SECTIONS}-section "
          f"threshold{unread})")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except RendererError as exc:
        # Not a verdict on any page: without the pinned renderer nothing
        # here can say what a page renders, so the run is refused whole.
        print(f"gen_toc: cannot read Markdown: {exc}", file=sys.stderr)
        sys.exit(2)
