#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Kebag Logic
# SPDX-License-Identifier: CERN-OHL-W-2.0
"""Per-page annotated table of contents: generate, refresh, and gate.

Why this exists. The corpus is 157 pages and 885 sections, several pages past
600 lines. Landing on one of them gives a reader no way to see what is in it
short of scrolling, and a bare list of headings barely helps - a heading like
"The memory cascade" does not tell you whether the section is worth your time.
So each entry carries a sentence saying what you get if you jump there.

The split of ownership is the point:

  * THIS SCRIPT owns which sections exist, their order, their nesting and
    their anchors - all of it read off the page, so it cannot drift.
  * A HUMAN owns the description. It is the part that carries judgement, and
    a generated one would be worthless ("this section covers the budget").

Descriptions survive regeneration: they are keyed by anchor and copied
forward. Rename a heading and its anchor changes, so the description is NOT
carried over - the gate then demands a fresh one rather than leaving a stale
sentence pointing at a section that has become something else.

Anchors follow GitHub's algorithm (lowercase; drop everything that is not
alphanumeric, space or hyphen; spaces to hyphens; `-1`, `-2` on collision).
`--verify-anchors` checks that algorithm against every `file.md#fragment`
link already in the tree, which is the only independent evidence we have that
it is right.

Usage:
    python3 scripts/gen_toc.py --check           # gate (exit 1 on drift/missing)
    python3 scripts/gen_toc.py --write           # insert/refresh every TOC
    python3 scripts/gen_toc.py --write PATH...   # just these pages
    python3 scripts/gen_toc.py --verify-anchors  # anchor algorithm vs real links
"""
import re
import subprocess
import sys
from collections.abc import Iterator
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

TOC_HEAD = "## Contents"
#: what the generator writes when it has no description yet. The gate REFUSES
#: this, so a freshly generated TOC is not mistakable for a finished one.
TODO = "TODO describe this section"

#: A page with fewer than this many top-level sections gets no TOC - a
#: contents list of two entries is furniture, not navigation.
MIN_SECTIONS = 3

#: When `##` is thin but `###` carries the real structure (REGISTER_MAP.md is
#: 3 and 25), the TOC nests one level deeper or it says nothing useful.
NEST_WHEN_H2_BELOW = 5
NEST_WHEN_H3_ATLEAST = 8

#: Pages that are deliberately TOC-free, with the reason.
SKIP = {
    "README.md":       "landing page - it IS a table of contents",
    "docs/README.md":  "documentation index - it IS a table of contents",
}

#: A page written by a generator must not be hand-edited: the next run of that
#: generator silently discards whatever was added. If one of these should carry
#: a contents list, teach its GENERATOR to emit it - do not edit the output.
#: `do not hand-edit` and a bare bold **GENERATED** are both in use in this
#: tree; missing either one is not cosmetic. docs/traceability/MODULE_MATRIX.md
#: says "**GENERATED - do not hand-edit**", matched none of the first-draft
#: patterns, got a contents list written into it, and that made
#: `gen_module_matrix.py --check` report the page STALE - one generator's
#: output failing another generator's gate.
GENERATED_RE = re.compile(
    r"auto-?generated|generated file|generated by|generated script"
    r"|regenerate with|do not hand-?edit|do not edit|\*\*GENERATED\b", re.I)
GENERATED_SCAN_LINES = 12

#: A fence delimiter line: at most three spaces of indentation, then a run of
#: three or more backticks or tildes, then the rest of the line. What the run
#: and the rest MEAN depends on the block already open, which is why
#: `blocks()` below and not this expression decides it.
FENCE_RE = re.compile(r"^ {0,3}(`{3,}|~{3,})(.*)$")
HEAD_RE = re.compile(r"^(#{1,6}) +(.*?)\s*$")
#: Four spaces or a tab of indentation start an indented code block, which
#: renders as code. Such a run cannot interrupt a paragraph, so it begins
#: only after a blank line.
INDENT_CODE_RE = re.compile(r"^(?: {4}|\t)")
#: CommonMark's type-1 raw HTML block: its content is not parsed as Markdown
#: and it survives blank lines, so a Contents block written inside one
#: renders as literal text ([R0] and [R10] round 5 on PR #384).
RAW_HTML_TAGS = ("pre", "script", "style", "textarea")
RAW_HTML_OPEN_RE = re.compile(r"^ {0,3}<(%s)[\s>/]" % "|".join(RAW_HTML_TAGS),
                              re.IGNORECASE)
COMMENT_OPEN, COMMENT_CLOSE = "<!--", "-->"
#: What a line is, for every reader in this repository. The names are what a
#: finding calls the line, so they read as English in a message.
TEXT, FENCE, COMMENT, CODE, HTML = ("prose line", "fenced line",
                                    "commented line", "indented code line",
                                    "raw HTML line")


def _closes_fence(delim: str, run: str, info: str) -> bool:
    """Whether a delimiter line closes the fence `delim` opened: same
    character, at least as long, and nothing after it but whitespace."""
    return bool(run) and run[0] == delim[0] and len(run) >= len(delim) \
        and not info.strip()


def blocks(text: str) -> list[str]:
    """What every line of ``text`` is: TEXT, FENCE, COMMENT, CODE or HTML.

    ONE walk, and the only one in this repository: a gate that re-derived
    it disagreed with this generator about which lines are navigation, five
    review rounds running on PR #384. It is a single state machine, so the
    block already open decides what a delimiter means -- a fence delimiter
    inside an HTML comment does not open a fence, and a comment delimiter
    inside a fence does not open a comment ([R0] round 5 F3, where a
    three-backtick line inside an old comment made this walk refuse a
    legitimate page).

    The rules are CommonMark's, with indentation measured from column 0
    rather than from an enclosing container's content column: a fence
    opener is indented at most three spaces; it closes only on a line of
    the SAME character, at least as long, carrying nothing but whitespace
    after the run, so a three-backtick line inside a four-backtick block is
    content; a backtick opener's info string may not contain a backtick,
    while a tilde opener's may. An indented code run needs a blank line
    before it, because it cannot interrupt a paragraph. A comment runs to
    its closing delimiter and a type-1 raw HTML block to its closing tag,
    both across blank lines.
    """
    out, state, delim, tag = [], TEXT, "", ""
    prev_blank = True
    for line in text.split("\n"):
        if state in (FENCE, COMMENT, HTML):
            out.append(state)
            state, delim, tag = _still_open(line, state, delim, tag)
        else:
            label, state, delim, tag = _opens(line, prev_blank, state)
            out.append(label)
        prev_blank = not line.strip()
    return out


def _still_open(line: str, state: str, delim: str,
                tag: str) -> tuple[str, str, str]:
    """The state after a line INSIDE a fence, comment or raw HTML block.
    Only that block's own closer is read, which is the whole precedence
    rule: nothing else on the line means anything while it is open."""
    if state == COMMENT:
        return (TEXT if COMMENT_CLOSE in line else COMMENT), "", ""
    if state == HTML:
        return ((TEXT if re.search(r"</%s\s*>" % tag, line, re.IGNORECASE)
                 else HTML), "", tag)
    m = FENCE_RE.match(line)
    if m and _closes_fence(delim, m.group(1), m.group(2)):
        return TEXT, "", ""
    return FENCE, delim, ""


def _opens(line: str, prev_blank: bool,
           state: str) -> tuple[str, str, str, str]:
    """(what this line is, the state after it, fence delimiter, HTML tag)
    for a line that no block encloses.

    The order is CommonMark's: an indented code run swallows the line
    before any delimiter on it is read; a comment that opens after visible
    text leaves THIS line ordinary and starts the span on the next one, so
    a heading with a trailing comment is still a heading.
    """
    if state == CODE and (not line.strip() or INDENT_CODE_RE.match(line)):
        return CODE, CODE, "", ""      # the run continues across blank lines
    if INDENT_CODE_RE.match(line) and prev_blank:
        return CODE, CODE, "", ""
    m = FENCE_RE.match(line)
    if m and not (m.group(1)[0] == "`" and "`" in m.group(2)):
        return FENCE, FENCE, m.group(1), ""
    html = RAW_HTML_OPEN_RE.match(line)
    if html:
        tag = html.group(1)
        closed = re.search(r"</%s\s*>" % tag, line, re.IGNORECASE)
        return HTML, (TEXT if closed else HTML), "", tag
    head, sep, rest = line.partition(COMMENT_OPEN)
    if sep and COMMENT_CLOSE not in rest:
        return (COMMENT if not head.strip() else TEXT), COMMENT, "", ""
    return TEXT, TEXT, "", ""


def line_kinds(text: str) -> list[str]:
    """`blocks()`, refined for the lines that are ordinary Markdown text: a
    heading, a table row, or prose. This is what a finding names, and it is
    the owner's answer rather than a second reader's."""
    out = []
    for line, kind in zip(text.split("\n"), blocks(text)):
        if kind != TEXT:
            out.append(kind)
        elif HEAD_RE.match(line):
            out.append("heading")
        elif line.lstrip().startswith("|"):
            out.append("table row")
        else:
            out.append(TEXT)
    return out


def fenced(text: str) -> list[bool]:
    """Per line: is it inside a fenced code block? Derived from `blocks()`,
    never re-walked."""
    return [k == FENCE for k in blocks(text)]


#: One Contents entry as this script writes it: the label, the anchor, the
#: separator (U+2014 on the pages that predate the em-dash rule, `--` on
#: every block written since) and the description. check_em_dash.py reads
#: entries with this same expression, so the gate and the generator cannot
#: disagree on what an entry is. The indentation is bounded at three spaces,
#: which is what this script writes (none, or two for a nested entry) and
#: what Markdown still renders as a list item: at four it is an indented
#: code block, which renders as code and is no navigation entry at all
#: ([R0] round 4 on PR #384).
TOC_ENTRY_RE = re.compile(
    r" {0,3}- +(?:\*\*)?\[([^\]]*)\]\(#([^)]*)\)(?:\*\*)?\s*(\u2014|--)\s*(.*)")


def anchor(text: str, seen: dict[str, int]) -> str:
    """GitHub's heading-anchor algorithm."""
    a = text.strip().lower()
    a = re.sub(r"[^\w\- ]", "", a, flags=re.UNICODE)  # \w keeps digits/underscore
    a = a.replace(" ", "-")
    n = seen.get(a, 0)
    seen[a] = n + 1
    return a if n == 0 else f"{a}-{n}"


def strip_md(text: str) -> str:
    """Heading text as a reader sees it: no backticks, no link syntax, no bold."""
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    text = text.replace("`", "")
    text = re.sub(r"\*\*([^*]*)\*\*", r"\1", text)
    return text.strip()


def label(text: str) -> str:
    """strip_md, then make it safe as the text of a **bold** link.

    A heading like ``## 2. Per-module HDL pages (`hdl/**/doc/*.md`)`` keeps a
    literal `**` once the backticks come off. Dropped inside the bold wrapper
    of a TOC entry that closes the bold early and mangles the rest of the
    line, so any surviving asterisk is escaped."""
    return strip_md(text).replace("*", r"\*")


def headings(text: str) -> list[tuple[int, str, str]]:
    """(level, raw_text, anchor) for every heading that renders as one.

    A heading inside a fence, an indented code block, an HTML comment or a
    raw HTML block renders as text, so it is no heading here and its label
    is no evidence of an anchor to preserve ([R0] round 5 F2 on PR #384,
    where commented heading syntax authorised a new label).

    Anchors must be numbered over ALL headings - GitHub counts collisions
    across the whole page, including the H1 and the Contents heading itself -
    so the walk cannot skip anything before assigning."""
    seen, out = {}, []
    for line, kind in zip(text.split("\n"), blocks(text)):
        if kind != TEXT:
            continue
        m = HEAD_RE.match(line)
        if m:
            lvl, raw = len(m.group(1)), m.group(2)
            out.append((lvl, raw, anchor(strip_md(raw), seen)))
    return out


def plan(text: str) -> list[tuple[int, str, str]] | None:
    """Which headings belong in this page's TOC, or None if it gets none."""
    hs = headings(text)
    h2 = [h for h in hs if h[0] == 2 and h[1].strip() != TOC_HEAD[3:]]
    h3 = [h for h in hs if h[0] == 3]
    if len(h2) < MIN_SECTIONS:
        return None
    nest = len(h2) < NEST_WHEN_H2_BELOW and len(h3) >= NEST_WHEN_H3_ATLEAST
    want = {2, 3} if nest else {2}
    return [h for h in hs if h[0] in want and h[1].strip() != TOC_HEAD[3:]]


def existing(
        text: str) -> tuple[dict[str, str], int | None, int | None, str | None]:
    """Descriptions keyed by anchor, the TOC span, and its separator.

    The span is located through `blocks()`, so a `## Contents` heading
    written inside a fence, a comment, an indented code block or a raw HTML
    block is an example of one and not this page's own.
    """
    lines, kinds = text.split("\n"), blocks(text)
    start = next((i for i, l in enumerate(lines)
                  if kinds[i] == TEXT and l.strip() == TOC_HEAD), None)
    if start is None:
        return {}, None, None, None
    end = start + 1
    while end < len(lines) and not (kinds[end] == TEXT
                                    and lines[end].startswith("## ")):
        end += 1
    desc = {}
    separator = None
    for i in range(start, end):
        m = TOC_ENTRY_RE.match(lines[i]) if kinds[i] == TEXT else None
        if m:
            desc[m.group(2)] = m.group(4).strip()
            if separator is None:
                separator = m.group(3)
    return desc, start, end, separator


def render(items: list[tuple[int, str, str]], desc: dict[str, str],
           separator: str) -> list[str]:
    """The Contents block itself, with each surviving description put back.

    A heading with no description carried forward gets `TODO`, which the gate
    then refuses: the generator's job ends at the link, and the sentence after
    the separator is the half a human still owes.
    """
    out = [TOC_HEAD, ""]
    for lvl, raw, anc in items:
        lab = label(raw)
        d = desc.get(anc, TODO)
        if lvl == 2:
            out.append(f"- **[{lab}](#{anc})** {separator} {d}")
        else:
            out.append(f"  - [{lab}](#{anc}) {separator} {d}")
    out.append("")
    return out


def apply(path: Path, text: str) -> str | None:
    """Return the page with its TOC inserted/refreshed, or None if unchanged."""
    items = plan(text)
    desc, start, end, separator = existing(text)
    lines = text.split("\n")

    if items is None:
        if start is None:
            return None
        del lines[start:end]                      # too few sections now
        return "\n".join(lines)

    # A page keeps the separator it has; a block written for the first time
    # uses `--`, the only separator the em-dash rule lets a change add.
    block = render(items, desc, separator or "--")
    if start is not None:
        lines[start:end] = block
    else:
        first = next((i for i, l in enumerate(lines) if l.startswith("## ")), None)
        if first is None:
            return None
        lines[first:first] = block
    new = "\n".join(lines)
    return None if new == text else new


def generated_block(text: str) -> tuple[int, list[str]] | None:
    """Where this page's Contents block starts and the exact lines THIS
    SCRIPT renders for it, or None when the page carries no block or its
    block is not what this script would write.

    It is the provenance answer other tools ask for: a line is generated
    navigation if it is byte-identical to the line here, at its own
    position. `check_em_dash.py` exempts a copied heading label only on
    that answer, so no second reader has to decide what renders as
    navigation -- five rounds of PR #384 showed that a second reader
    decides it differently. Equality holds for every page the `--check`
    arm below passes, which is the same comparison `apply()` makes.
    """
    items = plan(text)
    desc, start, end, separator = existing(text)
    if items is None or start is None:
        return None
    block = render(items, desc, separator or "--")
    if text.split("\n")[start:end] != block:
        return None
    return start, block


def pages() -> Iterator[Path]:
    """Every hand-written .md the gate has an opinion about.

    The corpus comes from `git ls-files`, i.e. THE INDEX - which can name a
    page that is not on disk, most often mid-change when a deletion has been
    made in the working tree but not staged. That used to raise
    FileNotFoundError out of read_text() and take the whole run down, and a
    gate that dies on one missing path reports NOTHING about the other
    hundred-odd pages: one loud traceback reads like a single failure when it
    is really an unmeasured corpus. So a vanished page is SKIPPED and NAMED,
    never fatal - it is a git-state observation, not a table-of-contents
    finding, and it must not be able to mask one.
    """
    out = subprocess.run(["git", "-C", str(REPO), "ls-files", "-z", "*.md"],
                         capture_output=True, text=True, check=True).stdout
    for p in sorted(out.split("\0")):
        if not p or p.startswith("docs/history/v1/") or p in SKIP:
            continue
        md = REPO / p
        if not md.is_file():
            print(f"  GONE  {p}: tracked in the index but not on disk "
                  f"(stage the deletion, or restore the file) - skipped")
            continue
        head = "\n".join(md.read_text().split("\n")[:GENERATED_SCAN_LINES])
        if GENERATED_RE.search(head):
            continue                       # generator-owned; see GENERATED_RE
        yield md


def verify_anchors() -> int:
    """Check the anchor algorithm against `file.md#frag` links people wrote."""
    ok = bad = 0
    for md in pages():
        for m in re.finditer(r"\]\(([^)\s]+\.md)#([^)\s]+)\)", md.read_text()):
            tgt = (md.parent / m.group(1))
            if not tgt.exists():
                continue
            if m.group(2) in {a for _, _, a in headings(tgt.read_text())}:
                ok += 1
            else:
                bad += 1
                print(f"  MISS {md.relative_to(REPO)} -> {m.group(1)}#{m.group(2)}")
    print(f"anchor check: {ok} existing cross-page fragment links reproduced"
          f"{f', {bad} NOT reproduced' if bad else ''}")
    return 1 if bad else 0


#: A page whose Contents block this script owns: three sections, one
#: heading carrying text a label must copy verbatim, and the block itself.
_ARM_PAGE = """# Page

## Contents

- **[Alpha](#alpha)** -- What alpha holds.
- **[Beta](#beta)** -- What beta holds.
- **[Gamma](#gamma)** -- What gamma holds.

## Alpha

Body.

## Beta

Body.

## Gamma

Body.
"""


def _walk_arms() -> list[tuple[str, str, object]]:
    """The block walk's arms: (name, page, predicate over `blocks(page)`).

    Every one of them was an escape or a false refusal measured on PR #384,
    so each states the rule it holds rather than a shape it happens to
    accept.
    """
    tick, tilde = "`" * 3, "~" * 3
    return [
        ("a fence delimiter inside a comment opens no fence",
         f"<!--\n{tick}\n-->\n\n## Contents\n",
         lambda k: k[:3] == [COMMENT] * 3 and k[4] == TEXT),
        ("a comment delimiter inside a fence opens no comment",
         f"{tick}\n<!--\n{tick}\n\n## Contents\n",
         lambda k: k[:3] == [FENCE] * 3 and k[4] == TEXT),
        ("a short delimiter inside a longer fence is content",
         f"{tick}`\n{tick}\n## Contents\n{tick}`\ntext\n",
         lambda k: k[:4] == [FENCE] * 4 and k[4] == TEXT),
        ("a tilde fence does not close on backticks",
         f"{tilde}\n{tick}\n## Contents\n{tilde}\ntext\n",
         lambda k: k[:4] == [FENCE] * 4 and k[4] == TEXT),
        ("a closer carrying an info string does not close",
         f"{tick}\n{tick} text\n## Contents\n{tick}\ntext\n",
         lambda k: k[:4] == [FENCE] * 4 and k[4] == TEXT),
        ("a backtick in a backtick opener's info string voids the opener",
         f"{tick} `x\ntext\n", lambda k: k[0] == TEXT),
        ("a backtick in a tilde opener's info string does not",
         f"{tilde} `x\ntext\n", lambda k: k[0] == FENCE),
        ("an opener indented three spaces still opens",
         f"   {tick}\ntext\n   {tick}\n", lambda k: k[:3] == [FENCE] * 3),
        ("four spaces after a blank line is code, not a fence",
         f"text\n\n    {tick}\n", lambda k: k[2] == CODE),
        ("an indented line continuing a paragraph is not code",
         "text\n    more text\n", lambda k: k[1] == TEXT),
        ("a raw HTML block's content is not Markdown",
         "<pre>\n## Contents\n</pre>\n\n## Real\n",
         lambda k: k[:3] == [HTML] * 3 and k[4] == TEXT),
        ("a raw HTML block closed on its own line ends there",
         "<pre>x</pre>\n\n## Real\n", lambda k: k[0] == HTML and k[2] == TEXT),
        ("a comment opened after visible text leaves that line alone",
         "## Head <!-- note\n-->\n## B\n",
         lambda k: k[0] == TEXT and k[1] == COMMENT and k[2] == TEXT),
    ]


def _provenance_arms() -> list[tuple[str, str, object]]:
    """`generated_block`'s arms: what counts as this script's own output."""
    page = _ARM_PAGE
    return [
        ("a block this script would write has provenance", page,
         lambda t: generated_block(t) is not None),
        ("a hand-edited entry loses it for the block",
         page.replace("- **[Beta](#beta)** --", "- **[Beta](#beta)**  --"),
         lambda t: generated_block(t) is None),
        ("an entry indented four spaces loses it",
         page.replace("- **[Beta]", "    - **[Beta]"),
         lambda t: generated_block(t) is None),
        ("a block inside a fence is no block of this page",
         page.replace("## Contents", "```\n## Contents").replace(
             "\n## Alpha", "\n```\n\n## Alpha", 1),
         lambda t: generated_block(t) is None),
        ("a block inside a comment is no block of this page",
         page.replace("## Contents", "<!--\n## Contents").replace(
             "\n## Alpha", "\n-->\n\n## Alpha", 1),
         lambda t: generated_block(t) is None),
        ("a block inside a raw HTML block is no block of this page",
         page.replace("## Contents", "<pre>\n## Contents").replace(
             "\n## Alpha", "\n</pre>\n\n## Alpha", 1),
         lambda t: generated_block(t) is None),
        ("a heading inside a comment is no heading",
         "<!--\n## Alpha\n-->\n\n## Beta\n",
         lambda t: [a for _, _, a in headings(t)] == ["beta"]),
    ]


def selftest() -> int:
    """Run the block-walk and provenance arms. 0 when every one holds.

    They live here because this script owns the walk: a gate that carried
    its own copy of it refused a legitimate page and exempted three that
    render nothing ([R0] rounds 4 and 5 on PR #384).
    """
    problems = 0
    for name, page, holds in _walk_arms():
        if not holds(blocks(page)):
            problems += 1
            print(f"  FAIL [{name}]: {blocks(page)}")
    for name, page, holds in _provenance_arms():
        if not holds(page):
            problems += 1
            print(f"  FAIL [{name}]")
    arms = len(_walk_arms()) + len(_provenance_arms())
    print(f"TOC selftest: {'PASS' if not problems else 'FAIL'} "
          f"({arms - problems}/{arms} arm(s))")
    return 1 if problems else 0


def main() -> int:
    """Run one of the three arms - `--verify-anchors`, `--write`, or the gate.

    `--check` is the default and the only one that can fail: it separates a
    page with no contents list at all from one whose list has drifted, because
    the two need different work from whoever reads the report.
    """
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    flags = {a for a in sys.argv[1:] if a.startswith("--")}

    if "--selftest" in flags:
        return selftest()

    if "--verify-anchors" in flags:
        return verify_anchors()

    targets = [Path(a).resolve() for a in args] if args else list(pages())
    changed, missing, stale = [], [], []

    for md in targets:
        text = md.read_text()
        rel = md.relative_to(REPO)
        new = apply(md, text)
        if "--write" in flags:
            if new is not None:
                md.write_text(new)
                changed.append(rel)
            continue
        # --check
        if new is not None:
            (missing if TOC_HEAD not in text else stale).append(rel)
        elif TOC_HEAD in text:
            desc, _, _, _ = existing(text)
            if any(d == TODO or not d for d in desc.values()):
                stale.append(rel)

    if "--write" in flags:
        todo = sum(1 for md in targets
                   if TOC_HEAD in md.read_text()
                   for d in existing(md.read_text())[0].values() if d == TODO)
        print(f"TOC: {len(changed)} page(s) written"
              f"{f', {todo} description(s) still {TODO!r}' if todo else ''}")
        return 0

    if missing or stale:
        for p in missing:
            print(f"  NO TOC    {p}  (>= {MIN_SECTIONS} sections and no '{TOC_HEAD}')")
        for p in stale:
            print(f"  TOC DRIFT {p}  (headings changed, or a description is "
                  f"still {TODO!r})")
        print(f"\n{len(missing) + len(stale)} page(s) need attention. "
              f"Run: python3 scripts/gen_toc.py --write <page>\nthen WRITE the "
              f"description for each entry - the generator cannot, and a "
              f"contents\nlist that only repeats the headings is not worth the "
              f"space it takes.")
        return 1

    n = sum(1 for md in targets if TOC_HEAD in md.read_text())
    print(f"TOC gate: OK ({n} page(s) carry an annotated contents list, "
          f"{len(targets) - n} below the {MIN_SECTIONS}-section threshold)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
