#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Kebag Logic
# SPDX-License-Identifier: CERN-OHL-W-2.0
"""Per-page annotated table of contents: generate, refresh, and gate.

Why this exists. The corpus is 157 pages and 885 sections, several pages past
600 lines. Landing on one of them gives a reader no way to see what is in it
short of scrolling, and a bare list of headings barely helps - a heading like
"The memory cascade" does not tell you whether the section is worth your time.
So each entry carries a sentence saying what you get if you jump there.

The split of ownership is the point:

  * THIS SCRIPT owns which sections exist, their order, their nesting and
    their anchors - all of it read off the page, so it cannot drift.
  * A HUMAN owns the description. It is the part that carries judgement, and
    a generated one would be worthless ("this section covers the budget").

Descriptions survive regeneration: they are keyed by anchor and copied
forward. Rename a heading and its anchor changes, so the description is NOT
carried over - the gate then demands a fresh one rather than leaving a stale
sentence pointing at a section that has become something else.

Anchors follow GitHub's algorithm (lowercase; drop everything that is not
alphanumeric, space or hyphen; spaces to hyphens; `-1`, `-2` on collision).
`--verify-anchors` checks that algorithm against every `file.md#fragment`
link already in the tree, which is the only independent evidence we have that
it is right.

Usage:
    python3 scripts/gen_toc.py --check           # gate (exit 1 on drift/missing)
    python3 scripts/gen_toc.py --write           # insert/refresh every TOC
    python3 scripts/gen_toc.py --write PATH...   # just these pages
    python3 scripts/gen_toc.py --verify-anchors  # anchor algorithm vs real links
"""
import ast
import re
import subprocess
import sys
from collections.abc import Iterator
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

TOC_HEAD = "## Contents"
#: what the generator writes when it has no description yet. The gate REFUSES
#: this, so a freshly generated TOC is not mistakable for a finished one.
TODO = "TODO describe this section"

#: A page with fewer than this many top-level sections gets no TOC - a
#: contents list of two entries is furniture, not navigation.
MIN_SECTIONS = 3

#: When `##` is thin but `###` carries the real structure (REGISTER_MAP.md is
#: 3 and 25), the TOC nests one level deeper or it says nothing useful.
NEST_WHEN_H2_BELOW = 5
NEST_WHEN_H3_ATLEAST = 8

#: The arm families `gen_toc_cases` carries, and the arm total measured
#: here. Nothing in this tree pinned an arm COUNT, so a family dropped
#: from the runner's import printed a smaller total and exited 0 ([R86]
#: suggestion, round 6 on PR #428). MIN_ARMS is a floor: it rises with the
#: corpus and is lowered only by someone who means to remove an arm.
ARM_FAMILIES = ("walk", "tag", "guard", "heading", "predecessor",
                "provenance")
MIN_ARMS = 191

#: Pages that are deliberately TOC-free, with the reason.
SKIP = {
    "README.md":       "landing page - it IS a table of contents",
    "docs/README.md":  "documentation index - it IS a table of contents",
}

#: A page written by a generator must not be hand-edited: the next run of that
#: generator silently discards whatever was added. If one of these should carry
#: a contents list, teach its GENERATOR to emit it - do not edit the output.
#: `do not hand-edit` and a bare bold **GENERATED** are both in use in this
#: tree; missing either one is not cosmetic. docs/traceability/MODULE_MATRIX.md
#: says "**GENERATED - do not hand-edit**", matched none of the first-draft
#: patterns, got a contents list written into it, and that made
#: `gen_module_matrix.py --check` report the page STALE - one generator's
#: output failing another generator's gate.
GENERATED_RE = re.compile(
    r"auto-?generated|generated file|generated by|generated script"
    r"|regenerate with|do not hand-?edit|do not edit|\*\*GENERATED\b", re.I)
GENERATED_SCAN_LINES = 12

#: A fence delimiter line: at most three spaces of indentation, then a run of
#: three or more backticks or tildes, then the rest of the line. What the run
#: and the rest MEAN depends on the block already open, which is why
#: `blocks()` below and not this expression decides it.
FENCE_RE = re.compile(r"^ {0,3}(`{3,}|~{3,})(.*)$")
#: An ATX heading and its text, the optional closing sequence of hashes
#: dropped as CommonMark 4.2 drops it ([R86] suggestion, round 4 on PR #428).
#: That sequence is a RUN of hashes with a space or a tab before it and
#: nothing but blanks after it: `## Old ## bar` is the text `Old ## bar`
#: and `## Old#` is the text `Old#`, as the renderer shows both. Each
#: bound has an arm ([R86] F2, round 5).
HEAD_RE = re.compile(r"^(#{1,6}) +(.*?)(?:[ \t]+#+)?\s*$")
#: Four spaces or a tab of indentation start an indented code block, which
#: renders as code. Such a run cannot interrupt a paragraph but follows any
#: block that closed (CommonMark 4.4: `# Heading` then `    foo`), so it
#: opens only while no paragraph is open and no container holds the line
#: ([R85] F1, round 3 on PR #428, where it began only after a blank line).
INDENT_CODE_RE = re.compile(r"^(?: {4}|\t)")
#: CommonMark's type-1 raw HTML block: its content is not parsed as Markdown
#: and it survives blank lines, so a Contents block written inside one
#: renders as literal text ([R0] and [R10] round 5 on PR #384). It ends at
#: its closing tag.
RAW_HTML_TAGS = ("pre", "script", "style", "textarea")
RAW_HTML_OPEN_RE = re.compile(r"^ {0,3}<(%s)[\s>/]" % "|".join(RAW_HTML_TAGS),
                              re.IGNORECASE)
#: CommonMark's type-6 raw HTML block: a block-level tag on its own line
#: opens it and a BLANK LINE closes it, and nothing inside is parsed as
#: Markdown. A `## Head` line tucked between `<div>` and `</div>` with no
#: blank line renders as text, so it is no heading and its label is no
#: evidence of an anchor ([R0] and [R10] round 7 on PR #384). Adding the
#: blank lines ends the block, and then the heading really does render.
HTML_BLOCK_TAGS = (
    "address|article|aside|base|basefont|blockquote|body|caption|center|col"
    "|colgroup|dd|details|dialog|dir|div|dl|dt|fieldset|figcaption|figure"
    "|footer|form|frame|frameset|h1|h2|h3|h4|h5|h6|head|header|hr|html"
    "|iframe|legend|li|link|main|menu|menuitem|nav|noframes|ol|optgroup"
    "|option|p|param|search|section|summary|table|tbody|td|tfoot|th|thead"
    "|title|tr|track|ul")
HTML_BLOCK_OPEN_RE = re.compile(r"^ {0,3}</?(%s)([\s/>]|$)" % HTML_BLOCK_TAGS,
                                re.IGNORECASE)
#: CommonMark's type-7 raw HTML block: ONE complete open or closing tag of
#: any other name (`<span>`, `<b>`, `<custom-tag>`, `</b>`), alone on its
#: line, opens it, and a blank line closes it exactly as a type-6 block. The
#: tag grammar is the specification's: a name is an ASCII letter then
#: letters, digits or hyphens; an attribute has an XML name and an optional
#: unquoted, single-quoted or double-quoted value. Unlike type 6, this kind
#: may not interrupt a paragraph, so `_opens()` reads it only while no
#: paragraph is open, which `blocks()` tracks line by line: under a
#: heading, a thematic break, a closing fence, a closing comment, a list
#: item, a block quote, a footnote definition or a table row the tag opens
#: a block with no blank line before it; under paragraph text it is that
#: paragraph's continuation ([R85] F1 and [R86] F1, round 1 on PR #428;
#: the footnote definition from [R86] F1, round 2). A type-1 name is read
#: first and never reaches here, which is the specification's exclusion
#: (#413).
_HTML_TAG_NAME = r"[A-Za-z][A-Za-z0-9-]*"
_HTML_ATTRIBUTE = (r"(?:[ \t]+[A-Za-z_:][A-Za-z0-9_.:-]*"
                   r"(?:[ \t]*=[ \t]*(?:[^ \t\"'=<>`]+|'[^']*'|\"[^\"]*\"))?)")
HTML_TAG_LINE_RE = re.compile(
    r"^ {0,3}(?:<%s%s*[ \t]*/?>|</%s[ \t]*>)[ \t]*$"
    % (_HTML_TAG_NAME, _HTML_ATTRIBUTE, _HTML_TAG_NAME))
#: Whether a paragraph is open, for the one block that may not interrupt
#: one. NO_PARAGRAPH: none is, and the next plain line starts one.
#: PARAGRAPH: a top-level paragraph is open. HELD: a list item, a block
#: quote or a table holds the plain lines that follow (CommonMark's lazy
#: continuation, GFM's rows without a pipe), so no top-level paragraph is
#: open and a plain line does not start one; a blank line or a block that
#: interrupts ends the hold. The lines that decide it are read flat, as the
#: whole walk is: at most three spaces of indentation, no container.
NO_PARAGRAPH, PARAGRAPH, HELD = "no paragraph", "paragraph", "held"
#: CommonMark's ATX opener, not `HEAD_RE`: an indented or empty heading
#: ends a paragraph even though `headings()` lists neither.
ATX_HEADING_RE = re.compile(r"^ {0,3}#{1,6}(?:[ \t]|$)")
THEMATIC_BREAK_RE = re.compile(
    r"^ {0,3}(?:(?:\*[ \t]*){3,}|(?:-[ \t]*){3,}|(?:_[ \t]*){3,})$")
SETEXT_UNDERLINE_RE = re.compile(r"^ {0,3}(?:=+|-+)[ \t]*$")
BLOCK_QUOTE_RE = re.compile(r"^ {0,3}>")
#: A list item: group 1 is the ordinal (None for a bullet), group 2 the
#: first character of its content (None when the item is empty).
#: Interrupting a paragraph takes content and, when ordered, the ordinal 1.
LIST_ITEM_RE = re.compile(
    r"^ {0,3}(?:[-+*]|(\d{1,9})[.)])(?:[ \t]+(\S)|[ \t]*$)")
#: GFM's table delimiter row, which makes the paragraph line above it a
#: header row: cells of hyphens with optional colons, separated by pipes,
#: a leading and a trailing pipe optional (GFM 0.29 section 4.10), so
#: `:-:`, `:---`, `---:` and `:-` are one-cell rows. A pipeless row of
#: hyphens alone is a setext underline or a thematic break, both read
#: before it. The row makes a table only when its cells number the header
#: row's (`_table_cells`); otherwise both lines stay paragraph text ([R86]
#: F1, round 2 on PR #428, where a pipe was demanded of the row). Its
#: indentation is bounded at three spaces whether or not a pipe leads it;
#: at four, or a tab, the line continues the paragraph ([R85] F2, round 3).
TABLE_DELIMITER_RE = re.compile(
    r"^ {0,3}(?:\|[ \t]*)?:?-+:?[ \t]*(?:\|[ \t]*:?-+:?[ \t]*)*\|?[ \t]*$")
#: One cell of a GFM table row, anything up to a pipe with a backslash
#: escaping the character after it; then the pipe that ends the cell and
#: the blanks after it.
TABLE_CELL_RE = re.compile(r"(?:\\.|[^|])*")
TABLE_CELL_END_RE = re.compile(r"\|[ \t]*")
#: GFM's footnote definition (`[^1]: note`): `[^`, a label with no blank
#: and no `]`, then `]:`, indented at most three spaces. It is outside the
#: 0.29 specification text; GitHub's renderer reads it as a container like
#: a list item, so it interrupts a paragraph, holds the plain lines after
#: it, and a lone tag directly under it opens a type-7 block ([R86] F1,
#: round 2 on PR #428).
FOOTNOTE_DEFINITION_RE = re.compile(r"^ {0,3}\[\^[^\]\s]+\]:")
COMMENT_OPEN, COMMENT_CLOSE = "<!--", "-->"
#: What a line is, for every reader in this repository. The names are what a
#: finding calls the line, so they read as English in a message.
TEXT, FENCE, COMMENT, CODE, HTML = ("prose line", "fenced line",
                                    "commented line", "indented code line",
                                    "raw HTML line")


def blocks(text: str) -> list[str]:
    """What every line of ``text`` is: TEXT, FENCE, COMMENT, CODE or HTML.

    ONE walk, and the only one in this repository that decides which lines
    are NAVIGATION: a gate that re-derived it disagreed with this
    generator about which lines are headings, five review rounds running
    on PR #384. Two other gates carry a fence and comment toggle of their
    own, for a different question (`docs_check.py` scopes a wording
    deny-list, `check_feature_status.py` scopes status tables); neither
    decides what a line IS ([R86] suggestion, round 6 on PR #428). It is a single state machine, so the
    block already open decides what a delimiter means -- a fence delimiter
    inside an HTML comment does not open a fence, and a comment delimiter
    inside a fence does not open a comment ([R0] round 5 F3, where a
    three-backtick line inside an old comment made this walk refuse a
    legitimate page).

    Three kinds of raw HTML block are read, held apart by how they begin
    and end: a type-1 block (`pre`, `script`, `style`, `textarea`) ends at
    its closing tag and survives blank lines; a type-6 block, any other
    block-level tag on its own line, ends at the first BLANK line; a type-7
    block, one complete tag of any other name alone on its line, ends at
    the first blank line too but may not interrupt a paragraph, so it
    opens only while none is open: under a heading, a thematic break, a
    closing fence or comment, a list item, a block quote, a footnote
    definition or a table row as well as after a blank line, never under
    paragraph text. None parses its content as Markdown, so a heading or a
    Contents block written inside any of them is text.

    The rules are CommonMark's, with indentation measured from column 0
    rather than from an enclosing container's content column: a fence
    opener is indented at most three spaces; it closes only on a line of
    the SAME character, at least as long, carrying nothing but whitespace
    after the run, so a three-backtick line inside a four-backtick block is
    content; a backtick opener's info string may not contain a backtick,
    while a tilde opener's may. An indented code run cannot interrupt a
    paragraph but follows any block that closed ([R85] F1, round 3 on PR
    #428, where a blank line was demanded of it); containers being flat
    here, a line indented under a list item, a block quote, a footnote
    definition or a table row is that container's content and opens no
    run. A comment runs to its closing delimiter and a type-1 raw HTML
    block to its closing tag, both across blank lines. A line that mixes
    commented and visible text is labelled by the block it STARTS in,
    which can only withhold a heading or a Contents block from a reader,
    never invent one. Containers are flat the same way for the paragraph a
    type-7 tag may not interrupt (`_paragraph_after`): a block quote or
    list-item line holds the plain lines after it as that container's
    paragraph whatever the container itself held, and a tag indented into
    a list item's content column opens a block where CommonMark continues
    the item's paragraph. Those two withhold a heading the page renders.
    One member of the same family runs the other way, which is why
    flatness is not harmless here: after a BLANK line inside a list item,
    a plain line indented into the item's content column (two or three
    spaces) is a fresh top-level paragraph to this walk, where the
    renderer holds it inside the item. A lone tag on the next line then
    interrupts nothing the renderer has open, so the renderer opens a
    block and reads the heading inside it as text while this walk KEEPS
    that heading, and a Contents label mirroring it would be exempt. The
    test is the item's content column, not indentation as such: one space
    and four spaces both agree with the renderer, and so do the block
    quote, the footnote definition and the tab. Distinguishing a
    container's own paragraph from a top-level one is a change to this
    walk's state model rather than a rule, and it is carried as issue
    #437 ([R86] F1, round 5 on PR #428). Two GFM
    constructs are read as GitHub's renderer reads them ([R86] F1, round 2
    on PR #428). A table delimiter row is what GFM 0.29 section 4.10
    defines, cells of hyphens and optional colons between optional pipes,
    indented at most three spaces ([R85] F2, round 3), so `:-:` under a
    paragraph line is a one-cell table, and it makes a table only when its
    cells number the header row's, so a row that does not match leaves
    the paragraph open. A footnote definition (`[^1]:
    note`) has no clause in that specification's text; the renderer reads
    it as a container, which interrupts a paragraph and holds the plain
    lines after it, and opens a type-7 block on a lone tag directly under
    it, so no paragraph is open after one here either. Both decisions were
    measured against that renderer, and each closes an escape: the pipe
    once demanded of the row and the footnote read as text both kept a
    paragraph open where GitHub has none, and let a wrapped heading
    through.
    """
    out, state, delim, tag, prev, para = [], TEXT, "", "", "", NO_PARAGRAPH
    for line in text.split("\n"):
        if state in (FENCE, COMMENT, HTML):
            out.append(state)
            state, delim, tag = _still_open(line, state, delim, tag)
        else:
            label, state, delim, tag = _opens(line, para, state)
            out.append(label)
        para, prev = _paragraph_after(line, out[-1], para, prev), line
    return out


def _table_cells(row: str) -> int:
    """How many cells a GFM table row carries, counted as GitHub's parser
    counts them: one leading pipe is skipped, a pipe that is not
    backslash-escaped ends a cell, and a trailing pipe closes the last
    cell rather than opening an empty one, so `| a |`, `a` and `||` are
    one cell each and a lone `|` is none."""
    rest = row.strip()
    if rest.startswith("|"):
        rest = rest[1:].lstrip(" \t")
    cells = 0
    while rest:
        cell = TABLE_CELL_RE.match(rest).end()
        end = TABLE_CELL_END_RE.match(rest, cell)
        cells += 1
        rest = rest[end.end() if end else cell:]
    return cells


def _paragraph_after(line: str, label: str, para: str, prev: str) -> str:
    """The paragraph state after a line, from the line's own label, its
    text, the state before it and the line before it.

    Only a plain TEXT line starts or continues a paragraph. A heading, a
    thematic break or a setext underline ends one and starts none; a list
    item, a block quote, a footnote definition or a table delimiter row
    starts a HOLD, which a plain line continues rather than ending; an
    ordered item not numbered 1, or an empty item, cannot interrupt a
    paragraph and continues it instead ([R85] F1 and [R86] F1, round 1 on
    PR #428, where the blank line stood in for all of this and a tag under
    any of these nine lines stayed paragraph text). A delimiter row makes a
    table of the paragraph line above it, `prev`, only when the two carry
    the same number of cells, and no pipe is demanded of it ([R86] F1,
    round 2, where `:-:` left the paragraph open).
    """
    if label != TEXT or not line.strip() or ATX_HEADING_RE.match(line) \
            or THEMATIC_BREAK_RE.match(line) \
            or (para == PARAGRAPH and SETEXT_UNDERLINE_RE.match(line)):
        return NO_PARAGRAPH
    item = LIST_ITEM_RE.match(line)
    interrupts = bool(item and item.group(2) and int(item.group(1) or 1) == 1)
    if BLOCK_QUOTE_RE.match(line) or FOOTNOTE_DEFINITION_RE.match(line) \
            or (item and (para != PARAGRAPH or interrupts)):
        return HELD
    if para == PARAGRAPH and TABLE_DELIMITER_RE.match(line) \
            and _table_cells(line) == _table_cells(prev):
        return HELD
    return HELD if para == HELD else PARAGRAPH


def _comment_after(line: str, inside: bool) -> bool:
    """Whether a comment is open AFTER this line, reading EVERY delimiter on
    it in order.

    One `-->` is not the end of the story: `<!-- first --> <!-- second`
    closes one comment and opens another, and a walk that read only the
    first delimiter left the second span classified as text, which handed
    a hand-written block inside it the navigation exemption ([R0] round 6
    on PR #384). A comment is also the only block that can open after
    visible text on a line, so this scan is the only residue any line
    needs: a fence, an indented code run and a raw HTML block all require
    the line's own start.
    """
    scan = line
    while scan:
        if inside:
            at = scan.find(COMMENT_CLOSE)
            if at < 0:
                return True
            scan, inside = scan[at + len(COMMENT_CLOSE):], False
        else:
            at = scan.find(COMMENT_OPEN)
            if at < 0:
                return False
            scan, inside = scan[at + len(COMMENT_OPEN):], True
    return inside


def _still_open(line: str, state: str, delim: str,
                tag: str) -> tuple[str, str, str]:
    """The state after a line INSIDE a fence, comment or raw HTML block.
    Only that block's own closer is read, which is the whole precedence
    rule: nothing else on the line means anything while it is open."""
    if state == COMMENT:
        return (COMMENT if _comment_after(line, True) else TEXT), "", ""
    if state == HTML:
        if not tag:                     # type 6: a blank line ends it
            return (TEXT if not line.strip() else HTML), "", tag
        return ((TEXT if re.search(r"</%s\s*>" % tag, line, re.IGNORECASE)
                 else HTML), "", tag)
    m = FENCE_RE.match(line)         # closes on the SAME character, a run
    if m and m.group(1)[0] == delim[0] and len(m.group(1)) >= len(delim) \
            and not m.group(2).strip():  # at least as long, nothing after it
        return TEXT, "", ""
    return FENCE, delim, ""


def _opens(line: str, para: str, state: str) -> tuple[str, str, str, str]:
    """(what this line is, the state after it, fence delimiter, HTML tag)
    for a line that no block encloses.

    The order is CommonMark's: an indented code run swallows the line
    before any delimiter on it is read; a type-1 tag is read before the
    type-7 grammar, so `<pre>` opens the block that survives blank lines;
    a comment that opens after visible text leaves THIS line ordinary and
    starts the span on the next one, so a heading with a trailing comment
    is still a heading. `para` gates the two blocks that may not interrupt
    a paragraph: the code run opens only while none is open and no
    container holds the line, the type-7 tag whenever none is open.
    """
    if state == CODE and (not line.strip() or INDENT_CODE_RE.match(line)):
        return CODE, CODE, "", ""      # the run continues across blank lines
    if INDENT_CODE_RE.match(line) and para == NO_PARAGRAPH:
        return CODE, CODE, "", ""
    m = FENCE_RE.match(line)
    if m and not (m.group(1)[0] == "`" and "`" in m.group(2)):
        return FENCE, FENCE, m.group(1), ""
    html = RAW_HTML_OPEN_RE.match(line)
    if html:
        tag = html.group(1)
        closed = re.search(r"</%s\s*>" % tag, line, re.IGNORECASE)
        return HTML, (TEXT if closed else HTML), "", tag
    if HTML_BLOCK_OPEN_RE.match(line) or (para != PARAGRAPH
                                          and HTML_TAG_LINE_RE.match(line)):
        # Types 6 and 7 carry no tag here: the blank line, not a closing
        # tag, is what ends them. A lone `<span>` under paragraph text is
        # that paragraph's continuation, not a block, so the line stays
        # TEXT; under anything else it opens the block.
        return HTML, HTML, "", ""
    if COMMENT_OPEN in line:
        after = COMMENT if _comment_after(line, False) else TEXT
        starts = line.lstrip().startswith(COMMENT_OPEN)
        return (COMMENT if starts else TEXT), after, "", ""
    return TEXT, TEXT, "", ""


def line_kinds(text: str) -> list[str]:
    """`blocks()`, refined for the lines that are ordinary Markdown text: a
    heading, a table row, or prose. This is what a finding names, and it is
    the owner's answer rather than a second reader's."""
    out = []
    for line, kind in zip(text.split("\n"), blocks(text)):
        if kind != TEXT:
            out.append(kind)
        elif HEAD_RE.match(line):
            out.append("heading")
        elif line.lstrip().startswith("|"):
            out.append("table row")
        else:
            out.append(TEXT)
    return out


#: One Contents entry as this script writes it: the label, the anchor, the
#: separator (U+2014 on the pages that predate the em-dash rule, `--` on
#: every block written since) and the description. check_em_dash.py reads
#: entries with this same expression, so the gate and the generator cannot
#: disagree on what an entry is. The indentation is bounded at three spaces,
#: which is what this script writes (none, or two for a nested entry) and
#: what Markdown still renders as a list item: at four it is an indented
#: code block, which renders as code and is no navigation entry at all
#: ([R0] round 4 on PR #384).
TOC_ENTRY_RE = re.compile(
    r" {0,3}- +(?:\*\*)?\[([^\]]*)\]\(#([^)]*)\)(?:\*\*)?\s*(\u2014|--)\s*(.*)")


def anchor(text: str, seen: dict[str, int]) -> str:
    """GitHub's heading-anchor algorithm."""
    a = text.strip().lower()
    a = re.sub(r"[^\w\- ]", "", a, flags=re.UNICODE)  # \w keeps digits/underscore
    a = a.replace(" ", "-")
    n = seen.get(a, 0)
    seen[a] = n + 1
    return a if n == 0 else f"{a}-{n}"


def strip_md(text: str) -> str:
    """Heading text as a reader sees it: no backticks, no link syntax, no bold."""
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    text = text.replace("`", "")
    text = re.sub(r"\*\*([^*]*)\*\*", r"\1", text)
    return text.strip()


def label(text: str) -> str:
    """strip_md, then make it safe as the text of a **bold** link.

    A heading like ``## 2. Per-module HDL pages (`hdl/**/doc/*.md`)`` keeps a
    literal `**` once the backticks come off. Dropped inside the bold wrapper
    of a TOC entry that closes the bold early and mangles the rest of the
    line, so any surviving asterisk is escaped."""
    return strip_md(text).replace("*", r"\*")


def headings(text: str) -> list[tuple[int, str, str]]:
    """(level, raw_text, anchor) for every heading that renders as one.

    A heading inside a fence, an indented code block, an HTML comment or a
    raw HTML block renders as text, so it is no heading here and its label
    is no evidence of an anchor to preserve ([R0] round 5 F2 on PR #384,
    where commented heading syntax authorised a new label).

    Anchors must be numbered over ALL headings - GitHub counts collisions
    across the whole page, including the H1 and the Contents heading itself -
    so the walk cannot skip anything before assigning."""
    seen, out = {}, []
    for line, kind in zip(text.split("\n"), blocks(text)):
        if kind != TEXT:
            continue
        m = HEAD_RE.match(line)
        if m:
            lvl, raw = len(m.group(1)), m.group(2)
            out.append((lvl, raw, anchor(strip_md(raw), seen)))
    return out


def plan(text: str) -> list[tuple[int, str, str]] | None:
    """Which headings belong in this page's TOC, or None if it gets none."""
    hs = headings(text)
    h2 = [h for h in hs if h[0] == 2 and h[1].strip() != TOC_HEAD[3:]]
    h3 = [h for h in hs if h[0] == 3]
    if len(h2) < MIN_SECTIONS:
        return None
    nest = len(h2) < NEST_WHEN_H2_BELOW and len(h3) >= NEST_WHEN_H3_ATLEAST
    want = {2, 3} if nest else {2}
    return [h for h in hs if h[0] in want and h[1].strip() != TOC_HEAD[3:]]


def existing(
        text: str) -> tuple[dict[str, str], int | None, int | None, str | None]:
    """Descriptions keyed by anchor, the TOC span, and its separator.

    The span is located through `blocks()`, so a `## Contents` heading
    written inside a fence, a comment, an indented code block or a raw HTML
    block is an example of one and not this page's own.
    """
    lines, kinds = text.split("\n"), blocks(text)
    start = next((i for i, l in enumerate(lines)
                  if kinds[i] == TEXT and l.strip() == TOC_HEAD), None)
    if start is None:
        return {}, None, None, None
    end = start + 1
    while end < len(lines) and not (kinds[end] == TEXT
                                    and lines[end].startswith("## ")):
        end += 1
    desc, separator = {}, None
    for i in range(start, end):
        m = TOC_ENTRY_RE.match(lines[i]) if kinds[i] == TEXT else None
        if m:
            desc[m.group(2)] = m.group(4).strip()
            if separator is None:
                separator = m.group(3)
    return desc, start, end, separator


def render(items: list[tuple[int, str, str]], desc: dict[str, str],
           separator: str) -> list[str]:
    """The Contents block itself, with each surviving description put back.

    A heading with no description carried forward gets `TODO`, which the gate
    then refuses: the generator's job ends at the link, and the sentence after
    the separator is the half a human still owes.
    """
    out = [TOC_HEAD, ""]
    for lvl, raw, anc in items:
        lab = label(raw)
        d = desc.get(anc, TODO)
        if lvl == 2:
            out.append(f"- **[{lab}](#{anc})** {separator} {d}")
        else:
            out.append(f"  - [{lab}](#{anc}) {separator} {d}")
    out.append("")
    return out


def apply(path: Path, text: str) -> str | None:
    """Return the page with its TOC inserted/refreshed, or None if unchanged."""
    items = plan(text)
    desc, start, end, separator = existing(text)
    lines = text.split("\n")

    if items is None:
        if start is None:
            return None
        del lines[start:end]                      # too few sections now
        return "\n".join(lines)

    # A page keeps the separator it has; a block written for the first time
    # uses `--`, the only separator the em-dash rule lets a change add.
    block = render(items, desc, separator or "--")
    if start is not None:
        lines[start:end] = block
    else:
        first = next((i for i, l in enumerate(lines) if l.startswith("## ")), None)
        if first is None:
            return None
        lines[first:first] = block
    new = "\n".join(lines)
    return None if new == text else new


def owns(relpath: str, text: str) -> bool:
    """Whether THIS script writes the Contents block of ``relpath``.

    One population, read by `pages()` below and by every tool that asks
    about provenance: the historical tree is frozen, `SKIP` names the two
    indexes that ARE tables of contents, and a generator-owned page belongs
    to its own generator. A gate that skipped this question exempted a
    label on a hand-written index ([R0] round 6 on PR #384).
    """
    if relpath.startswith("docs/history/v1/") or relpath in SKIP:
        return False
    head = "\n".join(text.split("\n")[:GENERATED_SCAN_LINES])
    return not GENERATED_RE.search(head)


def generated_block(text: str,
                    relpath: str | None = None) -> tuple[int, list[str]] | None:
    """Where this page's Contents block starts and the exact lines THIS
    SCRIPT renders for it, or None when the page carries no block or its
    block is not what this script would write.

    It is the provenance answer other tools ask for: a line is generated
    navigation if it is byte-identical to the line here, at its own
    position, on a page this script owns -- pass ``relpath`` and a page
    outside `owns()` answers None, whatever its text looks like.
    `check_em_dash.py` exempts a copied heading label only on
    that answer, so no second reader has to decide what renders as
    navigation -- five rounds of PR #384 showed that a second reader
    decides it differently. Equality holds for every page the `--check`
    arm below passes, which is the same comparison `apply()` makes.
    """
    if relpath is not None and not owns(relpath, text):
        return None
    items = plan(text)
    desc, start, end, separator = existing(text)
    if items is None or start is None:
        return None
    block = render(items, desc, separator or "--")
    if text.split("\n")[start:end] != block:
        return None
    return start, block


def pages() -> Iterator[Path]:
    """Every hand-written .md the gate has an opinion about.

    The corpus comes from `git ls-files`, i.e. THE INDEX - which can name a
    page that is not on disk, most often mid-change when a deletion has been
    made in the working tree but not staged. That used to raise
    FileNotFoundError out of read_text() and take the whole run down, and a
    gate that dies on one missing path reports NOTHING about the other
    hundred-odd pages: one loud traceback reads like a single failure when it
    is really an unmeasured corpus. So a vanished page is SKIPPED and NAMED,
    never fatal - it is a git-state observation, not a table-of-contents
    finding, and it must not be able to mask one.
    """
    out = subprocess.run(["git", "-C", str(REPO), "ls-files", "-z", "*.md"],
                         capture_output=True, text=True, check=True).stdout
    for p in sorted(filter(None, out.split("\0"))):
        md = REPO / p
        if not md.is_file():
            if owns(p, ""):
                print(f"  GONE  {p}: tracked in the index but not on disk "
                      f"(stage the deletion, or restore the file) - skipped")
            continue
        if owns(p, md.read_text()):
            yield md


def verify_anchors() -> int:
    """Check the anchor algorithm against `file.md#frag` links people wrote."""
    ok = bad = 0
    for md in pages():
        for m in re.finditer(r"\]\(([^)\s]+\.md)#([^)\s]+)\)", md.read_text()):
            tgt = (md.parent / m.group(1))
            if not tgt.exists():
                continue
            if m.group(2) in {a for _, _, a in headings(tgt.read_text())}:
                ok += 1
            else:
                bad += 1
                print(f"  MISS {md.relative_to(REPO)} -> {m.group(1)}#{m.group(2)}")
    print(f"anchor check: {ok} existing cross-page fragment links reproduced"
          f"{f', {bad} NOT reproduced' if bad else ''}")
    return 1 if bad else 0


def _tally_guards(families: dict[str, list], scored: int) -> list[str]:
    """What the ARM TALLY must satisfy before a single arm is scored: every
    family present and carrying arms, at least `MIN_ARMS` in all, and every
    arm the tables hold actually reaching the runner.

    Nothing in this tree pinned an arm count, so a family dropped from the
    runner's import printed `PASS (94/94 arm(s))` and exited 0 ([R86]
    suggestion, round 6 on PR #428). `scored` is what the runner will
    really read, which is the half a count of the tables alone cannot see.
    """
    bad = [f"arm family {name!r} is missing or empty"
           for name in ARM_FAMILIES if not families.get(name)]
    total = sum(len(arms) for arms in families.values())
    if total < MIN_ARMS:
        bad.append(f"{total} arm(s) in all, below the {MIN_ARMS} recorded")
    if scored != total:
        bad.append(f"{scored} arm(s) reach the runner of the {total} the "
                   "tables hold")
    return bad


def _owner_guards(name: str, source: str, values: dict) -> list[str]:
    """That the case-table module carries no classification of its OWN: it
    imports no expression engine and holds no compiled expression, so a
    rule cannot migrate out of this script, which #413 names as the one
    owner of block classification ([R85] suggestion, round 6 on PR #428,
    where the property was stated in two docstrings and checked nowhere).

    The imports are read off the module's syntax tree and the compiled
    expressions off its values, so prose that names the engine cannot trip
    it and an alias cannot slip past it.
    """
    bad, imported = [], set()
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.Import):
            imported |= {a.name.split(".")[0] for a in node.names}
        elif isinstance(node, ast.ImportFrom):
            imported.add((node.module or "").split(".")[0])
    if re.__name__ in imported:
        bad.append(f"{name} imports the expression engine: every expression "
                   "that classifies a line belongs beside the walk")
    compiled = sorted(n for n, v in values.items() if isinstance(v, re.Pattern))
    if compiled:
        bad.append(f"{name} holds compiled expression(s) {compiled}: "
                   "the same rule")
    return bad


def selftest() -> int:
    """Run every arm family. 0 when every one holds.

    The RUNNER and every rule it scores live here because this script owns
    the walk: a gate that carried its own copy of it refused a legitimate
    page and exempted three that render nothing ([R0] rounds 4 and 5 on PR
    #384). Only the case TABLES sit next door in `gen_toc_cases.py`, which
    holds fixture pages and expectations and no rule at all ([R86]
    suggestion, round 5 on PR #428).

    The import is here rather than at the top of the file because that
    module imports this one, and this module is registered under its own
    NAME first: run as a script it is `__main__`, so an import by name
    would load the file a second time and the page families would be
    scored against a different walk than the one the runner calls ([R85]
    suggestion, round 6 on PR #428).
    """
    sys.modules.setdefault("gen_toc", sys.modules[__name__])
    import gen_toc_cases as cases
    families = {"walk": cases.walk_arms(), "tag": cases.tag_arms(),
                "guard": cases.guard_arms(), "heading": cases.heading_arms(),
                "predecessor": cases.predecessor_arms(),
                "provenance": cases.provenance_arms()}
    on_walk = families["walk"] + families["tag"]
    on_page = (families["provenance"] + families["predecessor"]
               + families["heading"] + families["guard"])
    arms = len(on_walk) + len(on_page)
    src = Path(cases.__file__)
    notes = (_tally_guards(families, arms)
             + _owner_guards(src.name, src.read_text(), vars(cases)))
    for note in notes:
        print(f"  GUARD {note}")
    problems = len(notes)
    for name, page, holds in on_walk:
        if not holds(blocks(page)):
            problems += 1
            print(f"  FAIL [{name}]: {blocks(page)}")
    for name, page, holds in on_page:
        if not holds(page):
            problems += 1
            print(f"  FAIL [{name}]")
    print(f"TOC selftest: {'PASS' if not problems else 'FAIL'} "
          f"({arms - problems}/{arms} arm(s))")
    return 1 if problems else 0


def main() -> int:
    """Run one of the three arms - `--verify-anchors`, `--write`, or the gate.

    `--check` is the default and the only one that can fail: it separates a
    page with no contents list at all from one whose list has drifted, because
    the two need different work from whoever reads the report.
    """
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    flags = {a for a in sys.argv[1:] if a.startswith("--")}

    if "--selftest" in flags:
        return selftest()
    if "--verify-anchors" in flags:
        return verify_anchors()

    targets = [Path(a).resolve() for a in args] if args else list(pages())
    changed, missing, stale = [], [], []

    for md in targets:
        text = md.read_text()
        rel = md.relative_to(REPO)
        new = apply(md, text)
        if "--write" in flags:
            if new is not None:
                md.write_text(new)
                changed.append(rel)
            continue
        # --check
        if new is not None:
            (missing if TOC_HEAD not in text else stale).append(rel)
        elif TOC_HEAD in text:
            desc, _, _, _ = existing(text)
            if any(d == TODO or not d for d in desc.values()):
                stale.append(rel)

    if "--write" in flags:
        todo = sum(1 for md in targets
                   if TOC_HEAD in md.read_text()
                   for d in existing(md.read_text())[0].values() if d == TODO)
        print(f"TOC: {len(changed)} page(s) written"
              f"{f', {todo} description(s) still {TODO!r}' if todo else ''}")
        return 0

    if missing or stale:
        for p in missing:
            print(f"  NO TOC    {p}  (>= {MIN_SECTIONS} sections and no '{TOC_HEAD}')")
        for p in stale:
            print(f"  TOC DRIFT {p}  (headings changed, or a description is "
                  f"still {TODO!r})")
        print(f"\n{len(missing) + len(stale)} page(s) need attention. "
              f"Run: python3 scripts/gen_toc.py --write <page>\nthen WRITE the "
              f"description for each entry - the generator cannot, and a "
              f"contents\nlist that only repeats the headings is not worth the "
              f"space it takes.")
        return 1

    n = sum(1 for md in targets if TOC_HEAD in md.read_text())
    print(f"TOC gate: OK ({n} page(s) carry an annotated contents list, "
          f"{len(targets) - n} below the {MIN_SECTIONS}-section threshold)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
