#!/usr/bin/env python3
import os, sys
args = sys.argv[1:]
for i, arg in enumerate(args):
    if arg == "-j" and i + 1 < len(args):
        args[i + 1] = str(min(8, int(args[i + 1]) or 8))
os.execv("$VALIDATION_STORAGE/372-manager-candidate1/pinned-tool-bin/verilator", ["verilator"] + args)
