#!/bin/sh
# pinned 5.050 wrapper; caps compile parallelism at 4 jobs
W=$VALIDATION_STORAGE/372-manager-r2/pinned-tool-bin/verilator
args=""; prev=""
for a in "$@"; do
  if [ "$prev" = "-j" ] && [ "$a" = "0" ]; then a=4; fi
  prev=$a; set -- "$@" "$a"; shift
done
exec "$W" "$@"
