#!/usr/bin/env python3
"""Cut the timer arm-port block out of a protocol_processor_top.sv and wrap it.

The block is the text from the '====' line above "timer arm-port priority mux
(banner)" up to the '====' line above "PRNG draw-port owner mux (banner)",
copied byte for byte. The wrapper makes the eight faces inputs and the arm
port and the drop counter outputs. --mutate OLD NEW (repeatable) plants an
exact edit, OLD occurring exactly once in the block.
"""
import argparse
import sys

FACES = ["lstn", "tkr", "adp", "srp", "org", "maapeng", "ntfy", "ntfy_mon"]
INNER = {"ntfy", "ntfy_mon"}  # declared inside the block itself


def cut(text):
    lines = text.split("\n")
    a = next(i for i, l in enumerate(lines) if "timer arm-port priority mux (banner)" in l)
    b = next(i for i, l in enumerate(lines) if "PRNG draw-port owner mux (banner)" in l)
    assert lines[a - 1].strip().startswith("// ====") and lines[b - 1].strip().startswith("// ====")
    return "\n".join(lines[a - 1:b - 1])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("src")
    ap.add_argument("module")
    ap.add_argument("out")
    ap.add_argument("--mutate", nargs=2, action="append", default=[])
    a = ap.parse_args()
    block = cut(open(a.src, encoding="utf-8").read())
    for old, new in a.mutate:
        old = old.encode().decode("unicode_escape")
        new = new.encode().decode("unicode_escape")
        n = block.count(old)
        if n != 1:
            sys.exit(f"mutation text occurs {n} times: {old!r}")
        block = block.replace(old, new)
    ports = ["    input  wire clk_i", "    input  wire rst_n"]
    glue = []
    for f in FACES:
        p = ("i_" + f + "_") if f in INNER else (f + "_")
        ports += [f"    input  wire {p}arm_valid_w", f"    input  wire {p}arm_cancel_w",
                  f"    input  wire [TMR_AW_C-1:0] {p}arm_slot_w",
                  f"    input  wire [PP_TIMER_OWNER_W_C-1:0] {p}arm_owner_w",
                  f"    input  wire [31:0] {p}arm_deadline_w"]
        if f in INNER:
            for s in ("valid", "cancel", "slot", "owner", "deadline"):
                glue.append(f"  assign {f}_arm_{s}_w = i_{f}_arm_{s}_w;")
    ports += ["    output logic tmr_arm_valid_w", "    output logic tmr_arm_cancel_w",
              "    output logic [TMR_AW_C-1:0] tmr_arm_slot_w",
              "    output logic [PP_TIMER_OWNER_W_C-1:0] tmr_arm_owner_w",
              "    output logic [31:0] tmr_arm_deadline_w",
              "    output logic [15:0] arm_drop_o",
              "    output logic [7:0][2:0] dbg_cnt_o",
              "    output logic [7:0] dbg_pop_o",
              "    output logic [7:0] dbg_push_o"]
    out = [f"// generated by extract.py from {a.src}", "`default_nettype none",
           f"module {a.module}", "  import pp_pkg::*;",
           "#(parameter int unsigned TMR_AW_C = 6) (", ",\n".join(ports), ");",
           block, *glue,
           "  assign arm_drop_o = arm_drop_r;",
           "  assign dbg_cnt_o  = armq_cnt_r;",
           "  assign dbg_pop_o  = armq_pop_w;",
           "  assign dbg_push_o = armq_push_ok_w;",
           f"endmodule : {a.module}", "`default_nettype wire", ""]
    open(a.out, "w", encoding="utf-8").write("\n".join(out))


if __name__ == "__main__":
    main()
