import json, re
from pathlib import Path
out=Path(__file__).resolve().parent
rows=[json.loads(line) for line in (out/"gates.jsonl").read_text().splitlines()]
text="""# [A340] Merge-dev handoff for issue #502

Status: the assigned merge and all required local verification are complete. Review-ready evidence is posted.

## Assignment and source state

- Assignment: https://github.com/kebag-logic/milan-fpga/issues/502#issuecomment-5847404798
- Executor: [A340]. Independent reviewers remain [R328] and [R329].
- Branch: `502-pending-live-write`.
- Remote verified before merging: `https://github.com/kebag-logic/milan-fpga.git`.
- Initial head: `87e263fd1d71b1a7a04a2e9c9339220f35e4348f`.
- Fetched and verified dev: `831f94f4146cc45ec476f8c8dcf5afac7cd8eacf`.
- Merge head: `104c8a54b183cd9215ed1e3a2e1be1634f48d33d`.
- Ordered parents: the initial head, then the verified dev head.
- Commit subject: `Merge dev into 502-pending-live-write`; no body or trailers.

The implementation was reconstructed from `git diff 7eb3b0d4 87e263fd` and the public implementation evidence on issue #502. No private transcript or another session's output directory was read. No push, PR operation, merge into dev, hardware operation, donor-source edit or other checkout was performed.

## Retained implementation

`hdl/milan/KL_pp_shadow.sv:941` combines accepted name writes and map phase 5. The sticky source at line 944 and direct pulse at line 953 feed the backend on the accepting edge; the accepted-name output is connected at line 1080. The producers share the backend clock and reset. Later marks retain their command-completion meaning. No name/map record writer is added, so this source clears only on reset.

The observer at `tb/verilator/pp_shadow/sim_main.cpp:283` and real-command checks at line 1385 cover K10/K12, unchanged/repeated/refused commands, both map directions, reset and acknowledgement. `tb/verilator/pp_shadow/Makefile:163` includes the pending fixture; line 169 runs the late-mark mutant. `scripts/measure_test_evidence.py:597` retains the processor reader disposition. Saved-state contracts remain at `docs/design/SAVED_STATE_MATERIALIZATION.md:221` and `docs/design/SAVED_STATE_SNAPSHOT_OWNERSHIP.md:954`.

No RTL, firmware, processor pin or pending test source changed relative to the implementation parent. `source-preservation.txt` records the empty diff. The merge also retains dev's CI runner updates and datapath README corrections unchanged.

## Every conflict hunk and its resolution

Line references below name the resolved head.

| File:line or artifact | Conflict | Resolution |
|---|---|---|
| `CHANGELOG.md:11` and `:12` | Competing new Contents rows | Retained both rows, #502 then #567. |
| `CHANGELOG.md:35` and `:47` | Competing unreleased sections | Retained both sections verbatim, separated by a blank line. |
| `docs/reference/SUBMODULES.md:25` | Current pin `870ff88a` versus `0922e434` | Retained `870ff88a`. |
| `docs/reference/SUBMODULES.md:42` | Competing adoption narrative | Preserved #567 history, inventory checker and ROM rules; identify `870ff88a` as current and retain accepted-write integration facts. |
| `protocol-processor` gitlink | Base `990f9652`, ours `870ff88a`, theirs `0922e434` | Retained `870ff88a`; fetched both pins from the submodule public URL and proved `0922e434` is its ancestor. |
| `docs/diagrams/submodule_boundaries.drawio:1` | Whole-line master, differing pin label | Regenerated from the resolved Git index. |
| `docs/diagrams/submodule_boundaries.svg:29` | Pin label | Regenerated by the same command. |
| `docs/diagrams/submodule_boundaries.png` (binary) | Differing raster | Regenerated, decoded and visually inspected. |
| `docs/diagrams/PNG_MANIFEST.json:12` | Raster/source digests | Seeded unrelated entries from the implementation parent, then let the generator replace the conflicted entry from generated bytes. No hand-merged digest. |

`conflicts.diff` preserves the textual conflicts. `conflict-stages.txt` was saved after resolving the gitlink; its three stages are recorded above. The initial recursive submodule merge declined and reported missing historical object `83c84b19e09d397ed2eb6f5ace337686ce0ef86b`; the explicit pin resolution used the public fetch and successful ancestry proof.

Commands: `git -C protocol-processor fetch https://github.com/Mister-M-alt/protocol-processor-control-plane-avb-milan.git 870ff88ad35bbd532244e4c7e6d7661b9f6e1366 0922e43408f891fc0b84a84691df86b4fd0f1c0d`, then `git -C protocol-processor merge-base --is-ancestor 0922e43408f891fc0b84a84691df86b4fd0f1c0d 870ff88ad35bbd532244e4c7e6d7661b9f6e1366`, both exit 0. `git submodule update --init third_party/verilog-axis protocol-processor gptp-processor` exited 0. The unused SSH-only `external` import remains uninitialized under the documented gate setup.

## Regenerated files and inspection

`python3 docs/diagrams/submodule_boundaries.gen.py` regenerated the Draw.io master, SVG, PNG and `PNG_MANIFEST.json`. All four reproduce the implementation parent's bytes. The generator check, mutation self-test, submodule documentation check and PNG manifest check pass.

`syn/yosys/ooc.sh --record-rom-digests` regenerated current-pin rows and retained #567's tool-recorded rows. `syn/yosys/rom_digests.tsv:7` and `:8` hold `0922e434`; lines 27 and 28 hold `870ff88a`. The two pins' corresponding digests agree. The ledger merged without a textual conflict.

The committed PNG, direct Draw.io PNG/PDF export and A4 landscape raster were inspected. All four pins, ownership labels and connectors are readable without clipping. Inspection files remain under `/tmp/502-a340-diagram`. Exact export/print commands are in the gate table.

## Gate execution and limits

Commands ran in the foreground, without piping gate output. `run_gate.py` records each exit, head, elapsed time and complete log in `gates.jsonl`; the table below includes unsuccessful setup attempts rather than hiding them.

- The default interpreter lacked `html5lib`; em-dash and both Contents modes refused with exit 2. All three passed unchanged using the prepared Markdown interpreter, which includes system site packages. No source, test or ratchet was altered.
- The shared SDK cache lacked a provenance receipt and refused verification. A private SDK was installed outside the output directory from the repository-pinned archive, SHA-256 `d42680e926542595c4c87629d33f5f90aac1e9a964c8955089e0514caa01b78f`, and verified. No shared compiler was modified.
- Full builder modes run serially through `builder_mode.py`, which executes the unchanged `sw/builder/test_builder.py` main program with `runpy`. It intercepts only the three cross-compiler candidates. SDK mode maps only the existing absolute selector's executable and requires `--require-rv32`; absent mode raises FileNotFoundError for all three. Other subprocess calls and every test function remain unchanged. Per-mode invocation audits are retained.
- SDK builder passed with 851 actual firmware compilations. Its only unavailable arm is the pre-existing physical utilization report (gate 11). Compiler-absent mode also passed: all three cross candidates were hidden, zero firmware compilations occurred, and the RV32 census was explicitly excluded alongside the physical report.
- Standalone suites completed before the sweep. All six default sweep chunks run serially with `SUITE_TIMEOUT=10800` and the prepared Markdown interpreter. Selection files record every selected suite. Builder and sweep outputs are separate; their runs may overlap. No two builder modes or sweep chunks overlap.
- Front-end analysis passed at its four recorded processor findings (72 parent and 51 processor files analysed); parent HDL has none. Lint passed at its existing 90-finding ratchet. These are ratchet passes, not zero-warning claims.
- Behave passed 14 features, 344 scenarios and 1739 steps.
- Focused `pp_shadow`: 520 + 520 + 520 + 159 checks. The late-mark mutant fails K10 and K12 while its clean control passes. NVM cosimulation passed 465 checks and killed all 39 named mutants. Backend checks passed 525 + 208 checks and four negative controls.

## Area and capture

Recipe: `OOC_TMP=<scratch>/502-a340-ooc syn/yosys/ooc.sh KL_pp_shadow`, default parameters, `synth_xilinx -family xc7 -flatten`, repository-selected allocator. The merged-head command exited 0. Full synthesis evidence: `KL_pp_shadow.ooc.log`, `KL_pp_shadow.ooc.sv2v.err`, `ooc-merged.log`; versions: `versions.txt`.

| Measurement | LUT | LUTRAM | LUT total | FF | RAMB36 | RAMB18 | DSP | CARRY4 |
|---|---:|---:|---:|---:|---:|---:|---:|---:|
| Merge head, measured this round | 60766 | 6136 | 66902 | 30187 | 15 | 4 | 6 | 2104 |

The prior public implementation evidence reports 60855 LUT before the correction and 60766 after, both at pin `870ff88a`. This round matches that after value: merge delta 0 LUT; original correction delta -89 LUT against the published baseline. The prior baseline was not rerun in this merge-only round. Synthesis sources, parameters, processor pins and ROM bytes are unchanged relative to the implementation parent. Firmware is byte-identical; the capture gate passed without a remeasurement trigger.

## Gate table

Every exit below is the actual command exit. Setup failures have named successful replacements above. Logs are relative to this handoff directory.

| Gate | Exit | Seconds | Command | Log |
|---|---:|---:|---|---|
"""
for row in rows:
    command=row["command"].replace("|","&#124;")
    text+=f"| {row['gate']} | {row['exit']} | {row['seconds']} | `{command}` | `{row['log']}` |\n"
text+="\n## Completed sweep chunks\n\n| Chunk | Suites | Checks | Exit |\n|---|---:|---:|---:|\n"
for row in rows:
    if not row["gate"].startswith("sweep-"): continue
    body=(out/row["log"]).read_text()
    suites=re.search(r"suites: (\d+) +passed:",body)
    checks=re.search(r"checks: (\d+) +in-suite failures:",body)
    text+=f"| {row['gate']} | {suites.group(1) if suites else 'unknown'} | {checks.group(1) if checks else 'unknown'} | {row['exit']} |\n"
text+="\nOptional AAF/AVTP and gPTP field campaigns and their freshness checks are explicitly skipped because tsn-gen is absent; they contribute zero checks.\n"
text+="""
## Final state and public handoff

All 39 required final command records pass at `104c8a54b183cd9215ed1e3a2e1be1634f48d33d`. All 55 distinct default suites passed 2125050 checks with zero failures or timeouts; the full `milan_dp` default target passed 11206 checks. `gate-coverage.json` binds the final gate population and suite selections. `final-state.txt` records a clean parent worktree/index, no unresolved stages, and clean initialized submodules. Both worktree and base-to-head diff checks pass.

PR-BODY.md is complete: first line `[A340]`, closing keyword `Closes #502`, full implementation and merge-dev descriptions, no absolute home paths, tool/model names or attribution footer. REVIEW-READY.md contains the posted issue comment: https://github.com/kebag-logic/milan-fpga/issues/502#issuecomment-5848133819. Posting completed successfully; POSTED.json records its receipt. No independent review or hosted status is claimed by this author evidence. No PR has been opened or edited.
"""
(out/"HANDOFF.md").write_text(text)
