/*
 * SPDX-FileCopyrightText: 2026 Kebag Logic
 *
 * SPDX-License-Identifier: CERN-OHL-W-2.0
 */

//---------------------------------------------------------------------------//
/*
------------------------------------------------------------------------------
  File        : KL_aecp_aem_dyn_mux.sv
  Description : Dynamic-field read overlay for descriptor streaming.

                While the response builder streams a descriptor image out of
                KL_aecp_aem_store, fields whose value is LIVE hardware state
                (entity_id, capabilities, MAC, available_index, current
                configuration, ...) are substituted byte-for-byte from the
                CSR-driven inputs. The address->source map is generated by
                avdecc/gen_aem_store.py (aem_ovl_lookup in gen/aecp_aem_rom.svh)
                so the RTL never hand-encodes descriptor offsets. Fields that
                are AECP-settable but not live-HW (names, sampling rate,
                stream format) are NOT overlaid — SET_* writes them into the
                store and they read back naturally.

                Combinational: addr_i is the store address of rom_byte_i
                (present it in the same cycle the store data is valid).

                clock_identity is derived from the station MAC per IEEE
                802.1AS (EUI-48 -> EUI-64: insert FF-FE).

  Spec refs   : IEEE Std 1722.1-2021 §7.2.1/§7.2.8; Milan v1.2 §5.3
  Company     : Kebag Logic
  Project     : Milan ADP / AECP
------------------------------------------------------------------------------
*/
//---------------------------------------------------------------------------//

`default_nettype none

import aecp_pkg::*;

module KL_aecp_aem_dyn_mux (
  input  wire [15:0]  addr_i,        //! store address of rom_byte_i
  input  wire [7:0]   rom_byte_i,    //! byte read from KL_aecp_aem_store
  //! live values (CSR group 0x600 + ADP/L0 state)
  input  wire [63:0]  entity_id_i,
  input  wire [63:0]  entity_model_id_i,
  input  wire [31:0]  entity_caps_i,
  input  wire [15:0]  talker_sources_i,
  input  wire [15:0]  talker_caps_i,
  input  wire [15:0]  listener_sinks_i,
  input  wire [15:0]  listener_caps_i,
  input  wire [31:0]  controller_caps_i,
  input  wire [31:0]  available_index_i,
  input  wire [63:0]  association_id_i,
  input  wire [15:0]  current_config_i,
  input  wire [47:0]  station_mac_i,   //! [47:40] = first wire byte
  output logic [7:0]  byte_o
);

  `include "gen/aecp_aem_rom.svh"

  //! 802.1AS clockIdentity: MAC EUI-48 with FF-FE inserted in the middle
  wire [63:0] w_clock_id = {station_mac_i[47:24], 16'hFFFE, station_mac_i[23:0]};

  //! {hit, source[3:0], byte_of_source[2:0]} — byte 0 = MSB of the source
  wire [7:0] w_ovl = aem_ovl_lookup(addr_i);

  function automatic [7:0] pick64(input [63:0] v, input [2:0] n);
    pick64 = v[8*(7-n) +: 8];
  endfunction

  always_comb begin
    byte_o = rom_byte_i;
    if (w_ovl[7]) begin
      unique case (w_ovl[6:3])
        OVL_ENTITY_ID_C:   byte_o = pick64(entity_id_i,               w_ovl[2:0]);
        OVL_MODEL_ID_C:    byte_o = pick64(entity_model_id_i,         w_ovl[2:0]);
        OVL_ECAPS_C:       byte_o = pick64({32'd0, entity_caps_i},    w_ovl[2:0] + 3'd4);
        OVL_TALKER_SRC_C:  byte_o = pick64({48'd0, talker_sources_i}, w_ovl[2:0] + 3'd6);
        OVL_TALKER_CAP_C:  byte_o = pick64({48'd0, talker_caps_i},    w_ovl[2:0] + 3'd6);
        OVL_LISTEN_SINK_C: byte_o = pick64({48'd0, listener_sinks_i}, w_ovl[2:0] + 3'd6);
        OVL_LISTEN_CAP_C:  byte_o = pick64({48'd0, listener_caps_i},  w_ovl[2:0] + 3'd6);
        OVL_CTRL_CAP_C:    byte_o = pick64({32'd0, controller_caps_i},w_ovl[2:0] + 3'd4);
        OVL_AVAIL_IDX_C:   byte_o = pick64({32'd0, available_index_i},w_ovl[2:0] + 3'd4);
        OVL_ASSOC_ID_C:    byte_o = pick64(association_id_i,          w_ovl[2:0]);
        OVL_CURRENT_CFG_C: byte_o = pick64({48'd0, current_config_i}, w_ovl[2:0] + 3'd6);
        OVL_MAC_C:         byte_o = pick64({16'd0, station_mac_i},    w_ovl[2:0] + 3'd2);
        OVL_CLOCK_ID_C:    byte_o = pick64(w_clock_id,                w_ovl[2:0]);
        default:           byte_o = rom_byte_i;
      endcase
    end
  end

endmodule

`default_nettype wire
