/*
 * SPDX-FileCopyrightText: 2026 Kebag Logic
 *
 * SPDX-License-Identifier: CERN-OHL-W-2.0
 */

//---------------------------------------------------------------------------//
/*
------------------------------------------------------------------------------
  File        : KL_aecp_aem_store.sv
  Description : AEM descriptor store — byte-wide RAM holding the descriptor
                tree generated by avdecc/gen_aem_store.py (gen/aecp_aem_rom.svh).

                Read port: 1-cycle latency, byte granularity (the response
                builder streams descriptors one byte per cycle).
                Write port: byte granularity, used by the SET_* write-back
                (SET_NAME / SET_SAMPLING_RATE / SET_STREAM_FORMAT). Writes are
                a VOLATILE mirror tonight — the NV overlay / factory-reset
                flush of aem-and-aecp.md §NV is a follow-up; factory_reset_i
                is accepted but only reloads on FPGA reconfiguration.

                Live/runtime fields (entity_id, MAC, ...) are zero in the RAM
                and overlaid at read time by KL_aecp_aem_dyn_mux.

  Spec refs   : IEEE Std 1722.1-2021 §7.2; aem-and-aecp.md (4-level memory L3)
  Company     : Kebag Logic
  Project     : Milan ADP / AECP
------------------------------------------------------------------------------
*/
//---------------------------------------------------------------------------//

`default_nettype none

import aecp_pkg::*;

module KL_aecp_aem_store (
  input  wire          clk_i,
  input  wire          rst_n,
  input  wire [15:0]   addr_i,
  input  wire          rd_i,
  output logic [7:0]   data_o,
  input  wire  [15:0]  wr_addr_i,
  input  wire          wr_i,
  input  wire  [7:0]   wr_data_i,
  input  wire          factory_reset_i,
  output logic         flush_in_progress_o
);

  `include "gen/aecp_aem_rom.svh"

  //! Descriptor image RAM (BRAM-inferred, initialised from the generator)
  logic [7:0] mem_r [0:AEM_ROM_BYTES_C-1];

  initial begin
    for (int k = 0; k < AEM_ROM_BYTES_C; k++) mem_r[k] = AEM_ROM_INIT_C[k];
  end

  always_ff @(posedge clk_i) begin
    if (rd_i)
      data_o <= mem_r[addr_i];
    if (wr_i)
      mem_r[wr_addr_i] <= wr_data_i;
  end

  //! Factory reset: volatile store — nothing to flush until the NV overlay
  //! lands; reconfiguration restores the generated image.
  assign flush_in_progress_o = 1'b0;

  // verilator lint_off UNUSED
  wire unused = &{1'b0, rst_n, factory_reset_i};
  // verilator lint_on  UNUSED

endmodule

`default_nettype wire
