// reviewer probe wrapper: KL_srp_top with req_max_interval_i tied to 1, as the processor top does
`default_nettype none
module srp_area_wrap #(
  parameter int unsigned N_P = 2, parameter int unsigned AW_P = 6,
  localparam int unsigned N_SOURCES_P = N_P, localparam int unsigned N_SINKS_P = N_P,
  localparam int unsigned SLOT_AW_P = AW_P, localparam int unsigned N_VIDS_P = 4,
  localparam int unsigned SLOT_W_C = $bits(pp_pkg::PP_SLOT_NULL_C),
  localparam int unsigned TXA_W_C = $clog2(1600 + 1)
) (
  input wire  clk_i,
  input wire  rst_n,
  input wire [47:0] own_mac_i,
  input wire  link_up_i,
  input wire  p2p_i,
  input wire  cfg_rank_i,
  input wire [31:0] cfg_acc_lat_ns_i,
  input wire [31:0] port_rate_bps_i,
  input wire  mrp_valid_i,
  input wire [7:0] mrp_data_i,
  input wire  mrp_last_i,
  input wire  mrp_msrp_i,
  output wire  mrp_ready_o,
  input wire  req_valid_i,
  output wire  req_ready_o,
  input wire [2:0] req_op_i,
  input wire [7:0] req_index_i,
  input wire [63:0] req_stream_id_i,
  input wire [47:0] req_da_i,
  input wire [11:0] req_vid_i,
  input wire [15:0] req_max_frame_i,
  input wire [1:0] req_lstn_state_i,
  output wire  rsp_valid_o,
  output wire [1:0] rsp_status_o,
  output wire [31:0] rsp_data_o,
  output wire  alloc_req_o,
  output wire  oversize_o,
  input wire [SLOT_W_C-1:0] alloc_slot_i,
  input wire  alloc_gnt_i,
  output wire [SLOT_W_C-1:0] wr_slot_o,
  output wire [TXA_W_C-1:0] wr_addr_o,
  output wire  wr_valid_o,
  output wire [7:0] wr_data_o,
  output wire  wr_commit_o,
  output wire [TXA_W_C-1:0] wr_len_o,
  output wire  txreq_valid_o,
  output wire [SLOT_W_C-1:0] txreq_slot_o,
  input wire  txreq_ready_i,
  input wire [31:0] now_ms_i,
  output wire  arm_valid_o,
  output wire  arm_cancel_o,
  output wire [SLOT_AW_P-1:0] arm_slot_o,
  output wire [7:0] arm_owner_o,
  output wire [31:0] arm_deadline_ms_o,
  input wire  exp_valid_i,
  input wire [SLOT_AW_P-1:0] exp_slot_i,
  output wire  draw_req_o,
  output wire [2:0] draw_kind_o,
  input wire  draw_busy_i,
  input wire  draw_valid_i,
  input wire [15:0] draw_ms_i,
  output wire [N_SINKS_P-1:0] evt_tk_registered_o,
  output wire [N_SINKS_P-1:0] evt_tk_unregistered_o,
  output wire [N_SINKS_P-1:0] evt_tk_fail_chg_o,
  output wire [N_SINKS_P-1:0] evt_tk_latency_chg_o,
  output wire [N_SOURCES_P-1:0] lstn_reg_change_o,
  output wire  evt_domain_change_o,
  output wire [2:0] class_a_prio_o,
  output wire [11:0] class_a_vid_o,
  output wire  domain_adopted_o,
  output wire [N_SOURCES_P-1:0][1:0] tk_decl_state_o,
  output wire [N_SOURCES_P-1:0][1:0] lstn_reg_state_o,
  output wire [N_SOURCES_P-1:0] active_o,
  output wire [N_SOURCES_P-1:0][7:0] src_fail_code_o,
  output wire [N_SOURCES_P-1:0][63:0] src_fail_bridge_o,
  output wire [N_SINKS_P-1:0][1:0] tk_reg_state_o,
  output wire [N_SINKS_P-1:0][1:0] lstn_decl_state_o,
  output wire [N_SINKS_P-1:0][31:0] acc_latency_o,
  output wire [N_SINKS_P-1:0][7:0] snk_fail_code_o,
  output wire [N_SINKS_P-1:0][63:0] snk_fail_bridge_o,
  output wire [N_SOURCES_P-1:0][31:0] granted_slope_bps_o,
  output wire [N_SOURCES_P-1:0] sr_admitted_o,
  output wire [31:0] sum_slope_bps_o,
  output wire  over_limit_o,
  output wire [N_VIDS_P-1:0] dbg_vid_active_o,
  output wire  dbg_vlan_err_o,
  output wire  dbg_adm_round_o,
  output wire  dbg_pdu_done_o,
  output wire  dbg_pdu_ok_o,
  output wire  dbg_pdu_malformed_o
);
  KL_srp_top #(.N_SOURCES_P(N_P), .N_SINKS_P(N_P), .SLOT_AW_P(AW_P)) u_srp (
    .clk_i(clk_i),
    .rst_n(rst_n),
    .own_mac_i(own_mac_i),
    .link_up_i(link_up_i),
    .p2p_i(p2p_i),
    .cfg_rank_i(cfg_rank_i),
    .cfg_acc_lat_ns_i(cfg_acc_lat_ns_i),
    .port_rate_bps_i(port_rate_bps_i),
    .mrp_valid_i(mrp_valid_i),
    .mrp_data_i(mrp_data_i),
    .mrp_last_i(mrp_last_i),
    .mrp_msrp_i(mrp_msrp_i),
    .mrp_ready_o(mrp_ready_o),
    .req_valid_i(req_valid_i),
    .req_ready_o(req_ready_o),
    .req_op_i(req_op_i),
    .req_index_i(req_index_i),
    .req_stream_id_i(req_stream_id_i),
    .req_da_i(req_da_i),
    .req_vid_i(req_vid_i),
    .req_max_frame_i(req_max_frame_i),
    .req_max_interval_i(16'd1),
    .req_lstn_state_i(req_lstn_state_i),
    .rsp_valid_o(rsp_valid_o),
    .rsp_status_o(rsp_status_o),
    .rsp_data_o(rsp_data_o),
    .alloc_req_o(alloc_req_o),
    .oversize_o(oversize_o),
    .alloc_slot_i(alloc_slot_i),
    .alloc_gnt_i(alloc_gnt_i),
    .wr_slot_o(wr_slot_o),
    .wr_addr_o(wr_addr_o),
    .wr_valid_o(wr_valid_o),
    .wr_data_o(wr_data_o),
    .wr_commit_o(wr_commit_o),
    .wr_len_o(wr_len_o),
    .txreq_valid_o(txreq_valid_o),
    .txreq_slot_o(txreq_slot_o),
    .txreq_ready_i(txreq_ready_i),
    .now_ms_i(now_ms_i),
    .arm_valid_o(arm_valid_o),
    .arm_cancel_o(arm_cancel_o),
    .arm_slot_o(arm_slot_o),
    .arm_owner_o(arm_owner_o),
    .arm_deadline_ms_o(arm_deadline_ms_o),
    .exp_valid_i(exp_valid_i),
    .exp_slot_i(exp_slot_i),
    .draw_req_o(draw_req_o),
    .draw_kind_o(draw_kind_o),
    .draw_busy_i(draw_busy_i),
    .draw_valid_i(draw_valid_i),
    .draw_ms_i(draw_ms_i),
    .evt_tk_registered_o(evt_tk_registered_o),
    .evt_tk_unregistered_o(evt_tk_unregistered_o),
    .evt_tk_fail_chg_o(evt_tk_fail_chg_o),
    .evt_tk_latency_chg_o(evt_tk_latency_chg_o),
    .lstn_reg_change_o(lstn_reg_change_o),
    .evt_domain_change_o(evt_domain_change_o),
    .class_a_prio_o(class_a_prio_o),
    .class_a_vid_o(class_a_vid_o),
    .domain_adopted_o(domain_adopted_o),
    .tk_decl_state_o(tk_decl_state_o),
    .lstn_reg_state_o(lstn_reg_state_o),
    .active_o(active_o),
    .src_fail_code_o(src_fail_code_o),
    .src_fail_bridge_o(src_fail_bridge_o),
    .tk_reg_state_o(tk_reg_state_o),
    .lstn_decl_state_o(lstn_decl_state_o),
    .acc_latency_o(acc_latency_o),
    .snk_fail_code_o(snk_fail_code_o),
    .snk_fail_bridge_o(snk_fail_bridge_o),
    .granted_slope_bps_o(granted_slope_bps_o),
    .sr_admitted_o(sr_admitted_o),
    .sum_slope_bps_o(sum_slope_bps_o),
    .over_limit_o(over_limit_o),
    .dbg_vid_active_o(dbg_vid_active_o),
    .dbg_vlan_err_o(dbg_vlan_err_o),
    .dbg_adm_round_o(dbg_adm_round_o),
    .dbg_pdu_done_o(dbg_pdu_done_o),
    .dbg_pdu_ok_o(dbg_pdu_ok_o),
    .dbg_pdu_malformed_o(dbg_pdu_malformed_o)
  );
endmodule
`default_nettype wire
