#!/usr/bin/env python3
"""Generate the R458-4 lockstep bench: base (c4cb84ff) against head
KL_srp_talker_fsm, KL_srp_listener_fsm and KL_srp_admission.

Usage: gen_lockstep.py <head checkout> <base checkout> <out dir>

Writes into <out dir>:
  base/*.sv   the three base modules, renamed with a _base suffix
  ls_top.sv   one top instantiating head and base of each module on shared
              inputs; per-output mismatch vectors tk_mis_o, ls_mis_o, ad_mis_o
  ports.txt   the compared outputs, in mismatch-bit order
The port lists are parsed from the head module headers, so every output of
each module is compared.
"""
import re
import sys
from pathlib import Path

head, base, out = (Path(a) for a in sys.argv[1:4])
MODS = [("tk", "KL_srp_talker_fsm"), ("ls", "KL_srp_listener_fsm"),
        ("ad", "KL_srp_admission")]
(out / "base").mkdir(parents=True, exist_ok=True)


def ports(text):
    hdr = re.sub(r"//[^\n]*", "", text)
    hdr = hdr[hdr.index("\nmodule ") + 1:]
    hdr = hdr[:hdr.index(");")]
    res = []
    for line in hdr.splitlines():
        line = re.sub(r"//.*", "", line).strip()
        m = re.match(r"(input|output)\s+(wire|logic)\s*(.*?)\s*(\w+)\s*,?$", line)
        if m:
            res.append((m.group(1), m.group(3).strip(), m.group(4)))
    return res


body = []
decl = []
topports = ["    input  wire clk_i", "    input  wire rst_n"]
ordered = []
for pfx, mod in MODS:
    src = (head / "hdl/srp" / (mod + ".sv")).read_text()
    btxt = (base / "hdl/srp" / (mod + ".sv")).read_text()
    btxt = re.sub(r"\b%s\b" % mod, mod + "_base", btxt)
    (out / "base" / (mod + "_base.sv")).write_text(btxt)
    ps = ports(src)
    outs = [p for p in ps if p[0] == "output"]
    for d, ty, name in ps:
        if name in ("clk_i", "rst_n"):
            continue
        if d == "input":
            topports.append(f"    input  wire {ty} {pfx}_{name}")
        else:
            decl.append(f"  logic {ty} h_{pfx}_{name}, b_{pfx}_{name};")
    topports.append(f"    output logic [{len(outs)-1}:0] {pfx}_mis_o")
    for side, suffix in (("h", ""), ("b", "_base")):
        params = {"tk": ".N_SOURCES_P(N_SOURCES_P), .SLOT_BASE_P(16), .SLOT_AW_P(SLOT_AW_P), .N_VIDS_P(N_VIDS_P)",
                  "ls": ".N_SINKS_P(N_SINKS_P), .SLOT_BASE_P(32), .SLOT_AW_P(SLOT_AW_P)",
                  "ad": ".N_SOURCES_P(N_SOURCES_P)"}[pfx]
        conns = [".clk_i(clk_i)", ".rst_n(rst_n)"]
        for d, ty, name in ps:
            if name in ("clk_i", "rst_n"):
                continue
            conns.append(f".{name}({pfx}_{name})" if d == "input" else f".{name}({side}_{pfx}_{name})")
        body.append(f"  {mod}{suffix} #({params}) u_{side}_{pfx} (\n    "
                    + ",\n    ".join(conns) + "\n  );")
    for i, (_, _, name) in enumerate(outs):
        body.append(f"  assign {pfx}_mis_o[{i}] = (h_{pfx}_{name} != b_{pfx}_{name});")
        ordered.append(f"{pfx} {i} {name}")

# activity taps, so a run proves the walks and the admission rounds ran
topports += ["    output logic act_tk_push_o", "    output logic act_ls_push_o",
             "    output logic act_ad_round_o", "    output logic act_ad_grant_o"]
body += ["  assign act_tk_push_o  = h_tk_ev_valid_o && tk_ev_ready_i;",
         "  assign act_ls_push_o  = h_ls_ev_valid_o && ls_ev_ready_i;",
         "  assign act_ad_round_o = h_ad_round_done_o;",
         "  assign act_ad_grant_o = |h_ad_sr_admitted_o;"]

sv = f"""// generated by gen_lockstep.py — R458-4 lockstep, base against head
`default_nettype none
module ls_top #(
    parameter int unsigned N_SOURCES_P = 2,
    parameter int unsigned N_SINKS_P   = 2,
    parameter int unsigned SLOT_AW_P   = 7,
    parameter int unsigned N_VIDS_P    = 4,
    localparam int unsigned SRC_W_C = (N_SOURCES_P > 1) ? $clog2(N_SOURCES_P) : 1,
    localparam int unsigned SNK_W_C = (N_SINKS_P > 1) ? $clog2(N_SINKS_P) : 1
) (
{(','+chr(10)).join(topports)}
);
{chr(10).join(decl)}
{chr(10).join(body)}
endmodule
`default_nettype wire
"""
(out / "ls_top.sv").write_text(sv)
(out / "ports.txt").write_text("\n".join(ordered) + "\n")
print(f"wrote {out/'ls_top.sv'}: {len(ordered)} compared outputs")
