// R458-4 lockstep: base (c4cb84ff) against head KL_srp_talker_fsm,
// KL_srp_listener_fsm and KL_srp_admission on shared random inputs, every
// output compared every clock (ls_top.sv, generated by gen_lockstep.py).
// Build with -DTB_M=<sources> -DTB_N=<sinks>; run: <bin> <seed> <cycles>
// +verilator+rand+reset+2 +verilator+seed+<s> so unreset memories start
// random, and different in the two models.
// Stimulus: values drawn from small per-context pools, so decoder values match
// declared records; gate/control ops on in-range indices (the top range-checks
// them); random readies, cadences, LeaveAlls, expiries and mid-run resets;
// admission requests and TSpecs that change with their invalidate strobe.
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <random>
#include "Vls_top.h"
#include "verilated.h"

#ifndef TB_M
#error "TB_M"
#endif
#ifndef TB_N
#error "TB_N"
#endif
constexpr int M = TB_M;
constexpr int N = TB_N;

static std::mt19937_64 rng;
static uint64_t r64() { return rng(); }
static bool chance(double p) { return std::uniform_real_distribution<double>(0, 1)(rng) < p; }
static int pick(int n) { return static_cast<int>(rng() % static_cast<uint64_t>(n)); }

template <typename T> static void setv(T& port, uint64_t v) { port = static_cast<T>(v); }
template <std::size_t W> static void setbits(VlWide<W>& w, int lo, int width, uint64_t v) {
  for (int i = 0; i < width; ++i) {
    int b = lo + i;
    uint32_t bit = (v >> i) & 1u;
    w[b >> 5] = (w[b >> 5] & ~(1u << (b & 31))) | (bit << (b & 31));
  }
}
template <typename T> static void setbits(T& p, int lo, int width, uint64_t v) {
  uint64_t mask = (width >= 64) ? ~0ull : ((1ull << width) - 1);
  uint64_t cur = static_cast<uint64_t>(p);
  cur = (cur & ~(mask << lo)) | ((v & mask) << lo);
  p = static_cast<T>(cur);
}

struct Rec { uint64_t sid, da; uint16_t vid; };
static Rec tpool[16][3], lpool[16][3];
static uint16_t mfs_pool[4] = {64, 300, 1500, 9000};

int main(int argc, char** argv) {
  Verilated::commandArgs(argc, argv);
  uint64_t seed = argc > 1 ? strtoull(argv[1], nullptr, 0) : 1;
  uint64_t cycles = argc > 2 ? strtoull(argv[2], nullptr, 0) : 100000;
  rng.seed(seed);
  for (int s = 0; s < 16; ++s)
    for (int r = 0; r < 3; ++r) {
      tpool[s][r] = {0x02AA000000000000ull | (uint64_t(s) << 16) | (uint64_t(r) << 8) | 0x11,
                     0x91E0F0000000ull | (uint64_t(s) << 8) | uint64_t(r), uint16_t((2 + s + 16 * r) & 0xFFF)};
      lpool[s][r] = {0x0BB0000000000000ull | (uint64_t(s) << 16) | (uint64_t(r) << 8) | 0x22,
                     0x91E0F1000000ull | (uint64_t(s) << 8) | uint64_t(r), uint16_t((3 + s + 16 * r) & 0xFFF)};
    }
  Vls_top* d = new Vls_top;
  uint64_t mis_cycles = 0, mis_tk = 0, mis_ls = 0, mis_ad = 0, resets = 0;
  uint64_t first_tk = 0, first_ls = 0, first_ad = 0;
  uint32_t tk_bits = 0, ls_bits = 0, ad_bits = 0;
  uint32_t now = 1000;
  int rst_hold = 4;
  uint64_t areq = 0;
  uint64_t tk_ev = 0, ls_ev = 0, adm_done = 0;
  d->clk_i = 0;
  for (uint64_t c = 0; c < cycles; ++c) {
    // ---- inputs for this clock -------------------------------------------
    if (rst_hold == 0 && chance(1.0 / 40000)) { rst_hold = 1 + pick(4); ++resets; }
    d->rst_n = rst_hold > 0 ? 0 : 1;
    if (rst_hold > 0) --rst_hold;
    if (c % 8 == 0) ++now;
    // shared decoder event bus
    bool ev = chance(0.25);
    int es = pick(16 > M + 2 ? M + 2 : 16), er = pick(3);
    bool to_talker = chance(0.5);
    Rec er_rec = to_talker ? tpool[es][er] : lpool[es][er];
    if (chance(0.05)) er_rec = {r64(), r64() & 0xFFFFFFFFFFFFull, uint16_t(r64() & 0xFFF)};
    static const uint8_t attrs[] = {1, 2, 3, 3, 4, 1};
    uint8_t attr = attrs[pick(6)];
    uint64_t evid = er_rec.vid | (chance(0.02) ? 0x1000u : 0u);
    uint8_t mev = chance(0.9) ? pick(6) : pick(8);
    uint8_t fpk = pick(4);
    bool msrp = chance(0.9);
    d->tk_evt_valid_i = ev; d->ls_evt_valid_i = ev;
    d->tk_evt_msrp_i = msrp; d->ls_evt_msrp_i = msrp;
    d->tk_evt_attr_type_i = attr; d->ls_evt_attr_type_i = attr;
    d->tk_evt_stream_id_i = er_rec.sid; d->ls_evt_stream_id_i = er_rec.sid;
    d->tk_evt_da_i = er_rec.da; d->ls_evt_da_i = er_rec.da;
    d->tk_evt_vid_i = evid; d->ls_evt_vid_i = evid;
    d->tk_evt_mrp_event_i = mev; d->ls_evt_mrp_event_i = mev;
    d->tk_evt_fourpacked_i = fpk;
    d->ls_evt_acc_latency_i = chance(0.5) ? 500 : (r64() & 0xFFFF);
    d->ls_evt_failure_system_id_i = chance(0.8) ? 0 : r64();
    d->ls_evt_failure_code_i = chance(0.8) ? 0 : pick(256);
    // cadence and LeaveAlls
    bool jt = chance(0.004), pt = chance(0.0005), lo = chance(0.0008);
    uint8_t lrx = chance(0.002) ? pick(16) : 0;
    d->tk_join_tick_i = jt; d->ls_join_tick_i = jt;
    d->tk_periodic_tick_i = pt; d->ls_periodic_tick_i = pt;
    d->tk_leaveall_own_i = lo; d->ls_leaveall_own_i = lo;
    d->tk_leaveall_rx_i = lrx; d->ls_leaveall_rx_i = lrx;
    d->tk_now_ms_i = now; d->ls_now_ms_i = now;
    d->tk_p2p_i = 1; d->ls_p2p_i = 1;
    d->tk_own_mac_i = 0x02AABBCCDDEEull;
    d->tk_ev_ready_i = chance(0.7); d->ls_ev_ready_i = chance(0.7);
    d->tk_user_ready_i = chance(0.7); d->ls_user_ready_i = chance(0.7);
    d->tk_vid_sent_i = chance(0.01) ? pick(16) : 0;
    for (int v = 0; v < 4; ++v) setbits(d->tk_vid_val_i, 12 * v, 12, tpool[v][0].vid);
    // expiries: talker slots from 16, listener from 32
    bool ex = chance(0.01);
    int slot = chance(0.45) ? 16 + pick(M + 1) : chance(0.8) ? 32 + pick(N + 1) : pick(128);
    d->tk_exp_valid_i = ex; d->ls_exp_valid_i = ex;
    d->tk_exp_slot_i = slot; d->ls_exp_slot_i = slot;
    if (chance(0.02)) setbits(d->tk_sr_admitted_i, pick(M), 1, pick(2));
    // talker gate: random index in range, record from its pool; idle faces
    // keep (or randomise) their values
    d->tk_gate_valid_i = chance(0.03);
    if (d->tk_gate_valid_i || chance(0.2)) {
      int s = pick(M), r = pick(3);
      d->tk_gate_open_i = chance(0.7); d->tk_gate_src_i = s;
      d->tk_gate_stream_id_i = tpool[s][r].sid; d->tk_gate_da_i = tpool[s][r].da;
      d->tk_gate_vid_i = tpool[s][r].vid;
      d->tk_gate_max_frame_i = mfs_pool[pick(4)]; d->tk_gate_max_interval_i = 1 + pick(8);
      d->tk_gate_prio_i = pick(8); d->tk_gate_rank_i = pick(2);
      d->tk_gate_acc_lat_i = static_cast<uint32_t>(r64());
    }
    d->ls_ctl_valid_i = chance(0.03);
    if (d->ls_ctl_valid_i || chance(0.2)) {
      int k = pick(N), r = pick(3);
      d->ls_ctl_settle_i = chance(0.7); d->ls_ctl_sink_i = k;
      Rec lr = chance(0.5) ? lpool[k][r] : tpool[k % 16][r];
      d->ls_ctl_stream_id_i = lr.sid; d->ls_ctl_da_i = lr.da; d->ls_ctl_vid_i = lr.vid;
    }
    // admission: a request or TSpec change strobes invalidate (the contract)
    uint64_t inv = 0;
    for (int s = 0; s < M; ++s) {
      if (chance(0.0005)) { areq ^= 1ull << s; inv |= 1ull << s; }
      if (chance(0.0003)) {
        setbits(d->ad_max_frame_i, 16 * s, 16, mfs_pool[pick(4)]);
        setbits(d->ad_interval_frames_i, 16 * s, 16, 1 + pick(64));
        inv |= 1ull << s;
      }
      if (chance(0.0002)) inv |= 1ull << s;
    }
    if (c == 0) d->ad_port_rate_bps_i = (seed & 1) ? 1000000000u : 100000000u;
    for (int s = 0; s < M; ++s) {
      setbits(d->ad_req_i, s, 1, (areq >> s) & 1);
      setbits(d->ad_invalidate_i, s, 1, (inv >> s) & 1);
    }
    // ---- compare in this clock's settled pre-edge state, then the edge -----
    d->clk_i = 0; d->eval();
    uint64_t t = d->tk_mis_o, l = d->ls_mis_o, a = d->ad_mis_o;
    // clock 0 precedes the first reset edge: both models still hold their
    // random power-up state there, so the comparison starts at clock 1
    if (c > 0 && (t | l | a)) {
      ++mis_cycles;
      if (t && !mis_tk++) first_tk = c;
      if (l && !mis_ls++) first_ls = c;
      if (a && !mis_ad++) first_ad = c;
      tk_bits |= static_cast<uint32_t>(t); ls_bits |= static_cast<uint32_t>(l);
      ad_bits |= static_cast<uint32_t>(a);
    }
    tk_ev += d->act_tk_push_o; ls_ev += d->act_ls_push_o;
    adm_done += d->act_ad_round_o && d->act_ad_grant_o;
    d->clk_i = 1; d->eval();
  }
  printf("activity: talker pushes %llu, listener pushes %llu, admission rounds with a grant %llu\n",
         (unsigned long long)tk_ev, (unsigned long long)ls_ev, (unsigned long long)adm_done);
  printf("shape %d/%d seed %llu cycles %llu resets %llu: mismatching cycles %llu "
         "(talker %llu first %llu bits 0x%x; listener %llu first %llu bits 0x%x; "
         "admission %llu first %llu bits 0x%x)\n",
         M, N, (unsigned long long)seed, (unsigned long long)cycles,
         (unsigned long long)resets, (unsigned long long)mis_cycles,
         (unsigned long long)mis_tk, (unsigned long long)first_tk, tk_bits,
         (unsigned long long)mis_ls, (unsigned long long)first_ls, ls_bits,
         (unsigned long long)mis_ad, (unsigned long long)first_ad, ad_bits);
  delete d;
  return mis_cycles ? 1 : 0;
}
