#!/usr/bin/env python3
"""R456-2: summarise every suite, probe and boundary log under PACKET/receipts
into PACKET/receipts/summary.txt. Usage: r2_summarize.py PACKET

Per log: rc, the harness tally, and per graded/ungraded window the offsets
line the head prints (first pop after the end, nearest pop, walk, least
clearance, margin), the law line (PDUs, fill range, delay range), any
[NOT GRADABLE] / [BOUNDARY] verdicts and every [FAIL] line. Then aggregates:
the largest walk per log over every window (graded or not) and over graded
windows only, and the boundary verdicts the sound design and the setpoint
defects reached."""
import re
import sys
from pathlib import Path

P = Path(sys.argv[1]).resolve()
R = P / "receipts"
out: list[str] = []
w = out.append

OFF = re.compile(r"\[i\]\s+(.+?): over (\d+) steady PDU ends the first pop after the end "
                 r"is taken ([+-]\d+)\.\.([+-]\d+) cycles from it and the pop nearest the "
                 r"boundary ([+-]\d+)\.\.([+-]\d+) \(walk (\d+)\); the least clearance is "
                 r"(\d+) cycles, at PDU (-?\d+) \(offset ([+-]\d+)\), against the (\d+)-cycle "
                 r"ambiguity window: margin (-?\d+)")
LAW = re.compile(r"\[i\]\s+(.+?): (\d+) PDUs, fill at the PDU end (\d+)\.\.(\d+), first-event "
                 r"delay from it (\d+)\.\.(\d+) cycles = ([\d.]+)\.\.([\d.]+) media ticks")
NG = re.compile(r"\[NOT GRADABLE\] (.+?): PDU (\d+)'s end has a pop taken ([+-]\d+) cycles")
BND = re.compile(r"\[BOUNDARY\] \+(\d+): (graded PASS|graded FAIL|NOT GRADABLE), (\d+) check")
HIST = re.compile(r"\[i\]\s+(.+?): PDU ends per nearest-pop offset \(offset:ends\):(.*)")
TALLY = re.compile(r"checks: (\d+)\s+failures: (\d+)")


def rc_of(log: Path) -> str:
    for c in (log.with_name(log.name + ".rc"), log.with_suffix(".rc")):
        if c.is_file():
            return c.read_text().strip()
    return "rc=?"


def summarise(log: Path) -> dict:
    text = log.read_text(errors="replace")
    offs = {m[1]: m for m in OFF.finditer(text)}
    laws = {m[1]: m for m in LAW.finditer(text)}
    ngs = {m[1]: m for m in NG.finditer(text)}
    bnds = [(int(m[1]), m[2], int(m[3])) for m in BND.finditer(text)]
    fails = [l.strip() for l in text.splitlines() if l.strip().startswith("[FAIL]")]
    w(f"### {log.relative_to(P)}  ({rc_of(log)}; tallies {TALLY.findall(text)})")
    walk_all = walk_graded = -1
    for tag, m in offs.items():
        lm = laws.get(tag)
        graded = tag not in ngs
        walk = int(m[7])
        walk_all = max(walk_all, walk)
        if graded:
            walk_graded = max(walk_graded, walk)
        law = (f"n {lm[2]} fill {lm[3]}..{lm[4]} d {lm[7]}..{lm[8]} T" if lm
               else "law not graded")
        w(f"  {tag:<26} steady {m[2]:>3} next {m[3]}..{m[4]} nearest {m[5]}..{m[6]} "
          f"walk {m[7]} clear {m[8]} (PDU {m[9]}, {m[10]}) margin {m[12]:>4} "
          f"{'GRADED' if graded else 'NOT GRADABLE'}; {law}")
    for m in HIST.finditer(text):
        w(f"    hist {m[1]}:{m[2]}")
    for tag, m in laws.items():
        if tag not in offs:
            w(f"  {tag:<26} (no offsets line) n {m[2]} fill {m[3]}..{m[4]} d {m[7]}..{m[8]} T")
    if bnds:
        kinds = {}
        for p, k, n in bnds:
            kinds.setdefault(k, []).append(p)
        for k, ps in kinds.items():
            w(f"  [BOUNDARY] {k}: {len(ps)} phase(s): {runs(ps)}")
    w(f"  largest walk: every window {walk_all}, graded windows {walk_graded}")
    w(f"  failing checks: {len(fails)}")
    for f in fails:
        w("    " + f[:180])
    w("")
    return {"walk_all": walk_all, "walk_graded": walk_graded, "bnds": bnds}


def runs(ps: list[int]) -> str:
    rr: list[list[int]] = []
    for p in sorted(ps):
        if rr and p == rr[-1][1] + 1:
            rr[-1][1] = p
        else:
            rr.append([p, p])
    return ", ".join(f"+{a}" if a == b else f"+{a}..+{b}" for a, b in rr)


w("R456-2 receipts summary (generated by scripts/r2_summarize.py)")
w("")
logs = sorted((R / "suites").glob("suite-*.log")) + sorted((R / "probes").glob("*.log"))
res = {}
for log in logs:
    res[log.name] = summarise(log)
w("### boundary runner logs (the published diagnostic, run as TESTING.md documents it)")
for log in sorted((R / "suites").glob("bnd-*.log")):
    text = log.read_text(errors="replace")
    w(f"  {log.relative_to(P)} ({rc_of(log)})")
    for line in text.splitlines():
        if line.startswith(("[PASS] law boundary", "[FAIL] law boundary", "  [i] law boundary")) \
                or re.match(r"\d+ checks: ", line):
            w("    " + line)
w("")
w("### aggregate: largest walk per log (every window / graded windows)")
for name, r in res.items():
    if r["walk_all"] >= 0:
        w(f"  {name:<32} {r['walk_all']:>3} / {r['walk_graded']:>3}")
(R / "summary.txt").write_text("\n".join(out) + "\n")
print(f"wrote {R / 'summary.txt'} ({len(out)} lines)")
