#!/usr/bin/env python3
"""Portable #520 real PP-shadow probe; writes evidence only under --out.

Run from a clean candidate checkout. The shipping selftest wrapper injects
exactly the public round2 generated bytes, without editing any generator.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
from datetime import datetime, timezone


def output(command, tree):
    return subprocess.check_output(command, cwd=tree, text=True).strip()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--tree', type=Path, default=Path.cwd())
    parser.add_argument('--out', type=Path, required=True)
    args = parser.parse_args()
    tree, out = args.tree.resolve(), args.out.resolve()
    sys.path.insert(0, str(tree / 'syn/yosys'))
    import rom_cache_selftest as test
    assert test.ROOT == tree
    assert not output(['git', 'status', '--porcelain'], tree), 'Final evidence requires a clean source tree'
    out.mkdir(parents=True, exist_ok=True)
    head = output(['git', 'rev-parse', 'HEAD'], tree)
    tree_id = output(['git', 'rev-parse', 'HEAD^{tree}'], tree)
    generators = [tree / 'protocol-processor/hdl/acmp/rom/gen_ltn_rom.py',
                  tree / 'protocol-processor/hdl/aecp/ucode/gen_ucode.py',
                  tree / 'gptp-processor/hdl/ucode/gen_gptp_ucode.py']
    original = {str(p.relative_to(tree)): hashlib.sha256(p.read_bytes()).hexdigest() for p in generators}
    tools = {}
    for tool, version in [('yosys', '-V'), ('sv2v', '--version'), ('python3', '--version')]:
        path = Path(shutil.which(tool)).resolve()
        tools[tool] = dict(path=str(path), sha256=hashlib.sha256(path.read_bytes()).hexdigest(),
                           version=output([str(path), version], tree))
    metadata = dict(started=datetime.now(timezone.utc).isoformat(), head=head, tree=tree_id,
                    tools=tools, generator_sha256=original,
                    submodules=output(['git', 'submodule', 'status'], tree),
                    affinity=sorted(os.sched_getaffinity(0)),
                    public_evidence='e4a2d05481b33e9b437023a50f2eb754ea0592eb/review-evidence/478-r1/throughput-cache-triage/round2',
                    injected_bytes='INVALID_ROM_DATA\n')
    (out / 'metadata.json').write_text(json.dumps(metadata, indent=2) + '\n')
    probe = test.Probe(out / 'runs', ('KL_pp_shadow',))
    # Retain the otherwise disposable raw Yosys log, staged input and images
    # when run.sh calls its unchanged JSON extractor after synthesis.
    wrapper = probe.work / 'bin/python3'
    source = wrapper.read_text()
    capture = '''
if args and args[0] == "-" and len(args) == 2 and args[1].endswith(".stat.json"):
    import shutil
    destination = Path(os.environ["ROM_PROBE_TRACE"]).with_suffix(".artifacts")
    destination.mkdir(exist_ok=True)
    for artifact in Path(args[1]).parent.iterdir():
        if artifact.is_file() and artifact.suffix in (".hex", ".json", ".log", ".v"):
            shutil.copyfile(artifact, destination / artifact.name)
'''
    wrapper.write_text(source.replace('os.execv(real, [real, *args])', capture + '\nos.execv(real, [real, *args])'))
    cache = out / 'head-cache'
    flags = ['--cache', str(cache)]
    results = {}
    def run(name, flags, mutation=('', '')):
        print(f'START {name}', flush=True)
        receipt = probe.run(name, flags, mutation)
        results[name] = receipt
        print(json.dumps({k: receipt[k] for k in ('exit', 'seconds', 'cells', 'hits')}), flush=True)
        assert receipt['exit'] == 0, receipt
        return receipt
    cold = run('01-cold', flags)
    assert not cold['hits'] and set(cold['cells']) == {'KL_pp_shadow'}, cold
    baseline = test.cache_inputs(cold, 'lookup')
    assert baseline == test.cache_inputs(cold, 'store')
    warm = run('02-warm', flags)
    assert warm['cells'] == cold['cells'] and warm['hits'] == ['KL_pp_shadow'], warm
    assert baseline == test.cache_inputs(warm, 'lookup')
    with test.readonly_seed(cache, out / 'seed') as seed:
        seeded = run('03-seed', ['--cache-seed', str(seed)])
        assert seeded['cells'] == cold['cells'] and seeded['hits'] == ['KL_pp_shadow'], seeded
        changed = run('04-changed', flags + ['--cache-seed', str(seed)], ('ucode.hex', 'changed'))
        assert not changed['hits'], changed
        actual = test.cache_inputs(changed, 'lookup')
        assert actual == test.cache_inputs(changed, 'store')
        differences = {key for key in baseline['KL_pp_shadow']
                       if baseline['KL_pp_shadow'][key] != actual['KL_pp_shadow'][key]}
        assert differences == {'rom_sha256'}, differences
        changed_warm = run('05-changed-warm', flags, ('ucode.hex', 'changed'))
        assert changed_warm['hits'] == ['KL_pp_shadow'] and changed_warm['cells'] == changed['cells']
        uncached = run('06-changed-uncached', [], ('ucode.hex', 'changed'))
        assert not uncached['hits'] and uncached['cells'] == changed['cells'], uncached
    assert cold['cells'] != changed['cells'], 'The real numeric difference was not reproduced'
    for a, b in [('01-cold', '02-warm'), ('04-changed', '05-changed-warm'),
                 ('04-changed', '06-changed-uncached')]:
        assert (probe.work / a / 'top-KL_pp_shadow.result').read_bytes() == (
            probe.work / b / 'top-KL_pp_shadow.result').read_bytes()
    assert original == {str(p.relative_to(tree)): hashlib.sha256(p.read_bytes()).hexdigest() for p in generators}
    assert output(['git', 'rev-parse', 'HEAD'], tree) == head
    assert not output(['git', 'status', '--porcelain'], tree)
    summary = dict(metadata, result='PASS', source_unchanged=True,
                   completed=datetime.now(timezone.utc).isoformat(),
                   cache_input_differences=sorted(differences),
                   cells={name: data['cells'] for name, data in results.items()},
                   matches_published_values=(cold['cells']['KL_pp_shadow'] == 1141365 and
                                             changed['cells']['KL_pp_shadow'] == 1122602))
    (out / 'complete.json').write_text(json.dumps(summary, indent=2) + '\n')
    print(json.dumps(summary, indent=2), flush=True)


if __name__ == '__main__':
    main()
