#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Kebag Logic
# SPDX-License-Identifier: CERN-OHL-W-2.0
"""Copy milan_datapath's media-plane glue verbatim into an include.

Why this exists. follow_ring_wrap.sv binds the media plane's leaf modules the
way milan_datapath binds them, but several pieces of that binding are not leaf
modules: the clock-source decode (media_clk_table, media_clk_resolve), the
servo's reference mux with its W2 one-cycle unlocked presentation, the
aligner's A2-a select, keep-off and one-cycle-late tick, the servo's window
constant, the #386 settled-grid recentre trigger, the #645 settle recentre
and the render stage's recentre set. Restated in the wrapper they could drift
from the shipped datapath while the harness stayed green (the #617 R395-2 F2
lesson tb/verilator/capture_coherence/mga_keepoff.py records). So the build
copies each piece out of DP_SRC, line for line, into the build directory, and
the wrapper `include-s it. mutants.py points DP_SRC at a planted copy.

Each piece is a line range between two anchors. Every anchor must match
exactly one line, and the end anchor must follow the start, so a refactor
that renames, splits or reorders a piece fails the build here instead of
binding something else.

Usage: python3 dp_glue.py <milan_datapath.sv> <out.svh>
Exit 0 = every piece copied.
"""

import re
import sys
from pathlib import Path

#: (name, start anchor, end anchor): each a regex for one whole line
PIECES = (
    ("clock-source decode",
     r"^\s*localparam int unsigned NSIDX_W_FOLLOW_C = ",
     r"^\s*end : media_clk_resolve\s*$"),
    ("servo reference mux (W2)",
     r"^\s*logic\s+ref_crf_q_r, ref_aaf_q_r;",
     r"^\s*: crf_rate_valid_w;\s*$"),
    ("aligner select, keep-off and tick",
     r"^\s*wire\s+mga_sel_w = ",
     r"^\s*end : mga_tick_delay\s*$"),
    ("servo window",
     r"^\s*localparam int unsigned MCSRV_WIN_LOG2_C\s+=",
     r"^\s*localparam int unsigned MCSRV_WIN_LOG2_C\s+="),
    ("#386 settled-grid recentre",
     r"^\s*localparam int unsigned SRC_SETTLE_ERR_C\s+=",
     r"^\s*end : g_src_recentre\s*$"),
    ("#645 settle recentre",
     r"^\s*localparam int unsigned SETTLE_EXC_ERR_C\s+=",
     r"^\s*end : g_settle_recentre\s*$"),
    ("render recentre pulse",
     r"^\s*wire render_recentre_p_w .*=\s*$",
     r"^\s*\| src_recentre_p_r;\s*$"),
)

HEADER = ("// GENERATED by tb/verilator/follow_ring/dp_glue.py from {src}:\n"
          "// milan_datapath's media-plane glue, verbatim. Do not edit.\n")


def one_line(lines: list[str], pattern: str) -> int | None:
    """The index of the one line matching `pattern`, or None."""
    hits = [i for i, line in enumerate(lines) if re.search(pattern, line)]
    return hits[0] if len(hits) == 1 else None


def main() -> int:
    """Write the include; 1 if an anchor is missing, repeated or out of order."""
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    src_path = Path(sys.argv[1])
    lines = src_path.read_text().splitlines()
    out = [HEADER.format(src=src_path.name)]
    for name, start_pat, end_pat in PIECES:
        start = one_line(lines, start_pat)
        end = one_line(lines, end_pat)
        if start is None or end is None or end < start:
            print(f"dp_glue.py: {src_path}: the {name} piece is not one ordered range "
                  f"(start {start}, end {end}); the wrapper cannot bind the datapath's own "
                  f"glue", file=sys.stderr)
            return 1
        out.append(f"// ---- {name}: {src_path.name}:{start + 1}-{end + 1}\n")
        out.append("\n".join(lines[start:end + 1]) + "\n")
    Path(sys.argv[2]).write_text("".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
