#!/usr/bin/env bash
# Follow-up to probe_vs_full.sh: classify remaining probe-vs-full differences. For .v, compare
# with every '//' comment line removed (LiteX's header lists blackboxes in a run-dependent
# order); for the generated C headers, compare with the LiteX timestamp line removed.
# Usage: normalised_diff.sh <workdir from probe_vs_full.sh>
W=$1
for d in "$W"/probe-*/; do
  n=$(basename "$d"); k=${n#probe-}; F=$W/full-$k
  a=$(grep -v '^[[:space:]]*//' "$d/gateware/alinx_ax7101.v.norm" | sha256sum | cut -c1-16)
  b=$(grep -v '^[[:space:]]*//' "$F/gateware/alinx_ax7101.v.norm" | sha256sum | cut -c1-16)
  dl=$(diff "$d/gateware/alinx_ax7101.v.norm" "$F/gateware/alinx_ax7101.v.norm" | grep '^[<>]' | grep -vc '^[<>][[:space:]]*//')
  echo "$k .v without comment lines: probe $a full $b $( [ "$a" = "$b" ] && echo IDENTICAL || echo DIFFERS ); differing non-comment lines: $dl"
  for g in csr.h soc.h mem.h; do
    x=$(grep -v 'Auto-generated by LiteX' "$d/software/include/generated/$g" | sha256sum | cut -c1-16)
    y=$(grep -v 'Auto-generated by LiteX' "$F/software/include/generated/$g" | sha256sum | cut -c1-16)
    echo "$k $g without timestamp line: $( [ "$x" = "$y" ] && echo IDENTICAL || echo DIFFERS )"
  done
done
