/*
 * SPDX-FileCopyrightText: 2026 Kebag Logic
 * SPDX-License-Identifier: CERN-OHL-W-2.0
 *
 * Self-checking Verilator harness for the AECP/AEM listener subsystem
 * (KL_aecp_top). Crafts real AECP command Ethernet frames, drives them into
 * the RX monitor tap, collects the response frames from the TX AXIS master,
 * and checks the AECP common header + payload against the Milan v1.2 entity
 * model (5 descriptors). Exit 0 = all pass.
 */

#include "VKL_aecp_top.h"
#include "verilated.h"
#include "aem_golden.h"   // generated by avdecc/gen_aem_store.py (-I.. -> this dir)
#include <cstdio>
#include <cstring>
#include <cstdint>
#include <vector>
#include <deque>
#include <string>

static VKL_aecp_top* dut;
static vluint64_t tk = 0;
static long checks = 0, fails = 0;

static void tick() {
    dut->clk_i = 0; dut->eval();
    dut->clk_i = 1; dut->eval();
    tk++;
}
static void ck(const char* what, long got, long exp) {
    checks++;
    if (got != exp) { fails++; printf("  [FAIL] %-40s got=%ld exp=%ld\n", what, got, exp); }
    else            { printf("  [ ok ] %-40s = %ld\n", what, got); }
}
static void ckbytes(const char* what, const std::vector<uint8_t>& g, int off,
                    const std::vector<uint8_t>& exp) {
    checks++;
    bool bad = (int)g.size() < off + (int)exp.size();
    for (size_t i = 0; !bad && i < exp.size(); i++) if (g[off+i] != exp[i]) bad = true;
    if (bad) {
        fails++; printf("  [FAIL] %-40s off=%d\n         exp:", what, off);
        for (auto b : exp) printf(" %02x", b);
        printf("\n         got:");
        for (size_t i = 0; i < exp.size() && off+(int)i < (int)g.size(); i++) printf(" %02x", g[off+i]);
        printf("\n");
    } else printf("  [ ok ] %-40s (%zu bytes @ %d)\n", what, exp.size(), off);
}

// ------------------------------------------------------------------ identity
static const uint8_t ENT_MAC[6] = {0x02,0x00,0x00,0xff,0xfe,0x01};   // our station
static const uint8_t CTL_MAC[6] = {0x68,0x05,0xca,0x95,0xb2,0xd1};   // controller
static const uint8_t CTL2_MAC[6]= {0xaa,0xbb,0xcc,0xdd,0xee,0x02};
static const uint64_t ENTITY_ID = 0x0200'00ff'fe00'0001ULL;
static const uint64_t CTLR_ID   = 0x6805'ca95'b2d1'0000ULL;
static const uint64_t CTLR2_ID  = 0xaabb'ccdd'eeff'0002ULL;

static void put_be64(std::vector<uint8_t>& v, uint64_t x) {
    for (int i = 7; i >= 0; i--) v.push_back((x >> (8*i)) & 0xFF);
}
static void put_be16(std::vector<uint8_t>& v, uint16_t x) {
    v.push_back(x >> 8); v.push_back(x & 0xFF);
}

// Build an AECP AEM/VU command frame (wire order), pad to 60 bytes.
//   msg_type: 0=AEM_COMMAND, 6=VU_COMMAND
//   cmd:      command_type (AEM) — ignored for VU (payload carries it)
static std::vector<uint8_t> aecp_cmd(const uint8_t* dst, const uint8_t* src,
                                     uint64_t target, uint64_t ctlr,
                                     uint8_t msg_type, uint16_t cmd,
                                     uint16_t seq, const std::vector<uint8_t>& payload,
                                     bool unsol=false) {
    std::vector<uint8_t> f;
    for (int i=0;i<6;i++) f.push_back(dst[i]);
    for (int i=0;i<6;i++) f.push_back(src[i]);
    put_be16(f, 0x22F0);                       // ethertype
    f.push_back(0xFB);                          // subtype AECP
    f.push_back((0<<7)|(0<<4)|(msg_type&0xF));  // sv/ver/msg_type
    bool aem = (msg_type != 6);
    // cdl = octets after control_data_length: ctlr(8)+seq(2)+[u/cmd(2) if AEM]+payload
    uint16_t cdl = (aem ? 12 : 10) + (uint16_t)payload.size();
    f.push_back(((0/*status*/&0x1F)<<3) | ((cdl>>8)&0x7)); // status|cdl_hi
    f.push_back(cdl & 0xFF);                    // cdl_lo
    put_be64(f, target);
    put_be64(f, ctlr);
    put_be16(f, seq);
    // AEM frames carry u+command_type here; VU frames go straight to the
    // protocol_id the caller placed at the head of `payload`.
    if (aem) {
        f.push_back(((unsol?1:0)<<7) | ((cmd>>8)&0x7F));  // u|cmd_hi
        f.push_back(cmd & 0xFF);                          // cmd_lo
    }
    for (auto b : payload) f.push_back(b);
    while (f.size() < 60) f.push_back(0x00);    // pad to min Ethernet
    return f;
}

// Drive a frame into the RX monitor tap (little lane, 8 bytes/beat).
static void feed_rx(const std::vector<uint8_t>& f) {
    int n = f.size();
    for (int off = 0; off < n; off += 8) {
        uint64_t d = 0; uint8_t keep = 0;
        for (int l = 0; l < 8; l++) {
            if (off + l < n) { d |= (uint64_t)f[off+l] << (8*l); keep |= (1<<l); }
        }
        dut->rx_tvalid_i = 1;
        dut->rx_tdata_i  = d;
        dut->rx_tkeep_i  = keep;
        dut->rx_tlast_i  = (off + 8 >= n);
        tick();
    }
    dut->rx_tvalid_i = 0; dut->rx_tlast_i = 0; dut->rx_tkeep_i = 0;
}

// Collect one response frame from the TX AXIS master (little lane -> wire bytes).
// Returns empty if none within `budget` cycles.
static std::vector<uint8_t> collect_resp(int budget = 6000) {
    std::vector<uint8_t> b;
    int idle = 0;
    dut->m_axis_tready = 1;
    for (int c = 0; c < budget; c++) {
        dut->eval();
        if (dut->m_axis_tvalid && dut->m_axis_tready) {
            for (int l = 0; l < 8; l++)
                if ((dut->m_axis_tkeep >> l) & 1)
                    b.push_back((dut->m_axis_tdata >> (8*l)) & 0xFF);
            bool last = dut->m_axis_tlast;
            tick();
            if (last) return b;
            idle = 0;
        } else {
            tick();
            // tolerate inter-beat gaps (2-cycle assembly cadence); give up only
            // after a long idle (empty result = no response, e.g. a dropped frame).
            if (++idle > 500) return b;
        }
    }
    return b;   // empty = timeout
}

// AECP response header field accessors (wire bytes)
static int r_status(const std::vector<uint8_t>& b){ return b.size()>16 ? (b[16]>>3)&0x1F : -1; }
static int r_msgt (const std::vector<uint8_t>& b){ return b.size()>15 ? b[15]&0x0F : -1; }
static int r_cmd  (const std::vector<uint8_t>& b){ return b.size()>37 ? ((b[36]&0x7F)<<8)|b[37] : -1; }
static uint64_t r_ctlr(const std::vector<uint8_t>& b){ if(b.size()<34) return 0; uint64_t v=0; for(int i=0;i<8;i++) v=(v<<8)|b[26+i]; return v; }
static int r_seq  (const std::vector<uint8_t>& b){ return b.size()>35 ? (b[34]<<8)|b[35] : -1; }
static int r_cdl  (const std::vector<uint8_t>& b){ return b.size()>17 ? ((b[16]&0x07)<<8)|b[17] : -1; }
// IEEE 1722-2016 §5.4: control_data_length counts the octets FOLLOWING the
// stream_id (target_entity_id) field — i.e. from wire offset 26 (after
// eth 14 + subtype/sv/status/cdl 4 + target_entity_id 8). The pipewire AVB
// reference (Hive-validated) confirms it: CDL = payload + AVB_PACKET_
// CONTROL_DATA_OFFSET(12) = frame - 26. The builder emits no padding so
// CDL must equal len - 26. (NB: tsn-gen's CDL model wrongly counts
// target_entity_id — do not use it as the oracle here.)
static void ck_cdl(const char* nm, const std::vector<uint8_t>& b){
    ck(nm, (b.size()>26) && (r_cdl(b) == (int)b.size()-26), 1);
}

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    setvbuf(stdout, NULL, _IONBF, 0);
    dut = new VKL_aecp_top;

    // reset
    dut->rst_n = 0; dut->enable_i = 1;
    dut->rx_tvalid_i = 0; dut->m_axis_tready = 1;
    dut->station_mac_i = 0; dut->entity_id_i = ENTITY_ID;
    dut->entity_model_id_i = 0;
    dut->entity_caps_i = 0x00008588; dut->talker_sources_i = 8; dut->talker_caps_i = 0x4801;
    dut->listener_sinks_i = 8; dut->listener_caps_i = 0x4801; dut->controller_caps_i = 0;
    dut->available_index_i = 7; dut->association_id_i = 0;
    dut->gptp_gm_id_i = 0x0011223344556677ULL; dut->gptp_domain_i = 0;
    // station MAC [47:40]=first wire byte
    { uint64_t m=0; for(int i=0;i<6;i++) m=(m<<8)|ENT_MAC[i]; dut->station_mac_i = m; }
    for (int i = 0; i < 8; i++) tick();
    dut->rst_n = 1;
    for (int i = 0; i < 4; i++) tick();

    printf("== AECP/AEM listener subsystem — Milan v1.2 entity ==\n");

    // ---------------------------------------------------------------- //
    // 1. READ_DESCRIPTOR(ENTITY, 0)                                     //
    // ---------------------------------------------------------------- //
    printf("\n[1] READ_DESCRIPTOR(ENTITY,0)\n");
    {
        std::vector<uint8_t> pl; put_be16(pl,0); put_be16(pl,0);         // cfg, reserved
        put_be16(pl, 0x0000); put_be16(pl, 0x0000);                      // type ENTITY, index 0
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 4, 0x1001, pl));
        auto r = collect_resp();
        fprintf(stderr,"RESP1 %zu bytes:", r.size());
        for(size_t i=0;i<r.size()&&i<80;i++) fprintf(stderr," %02x", r[i]);
        fprintf(stderr,"\n");
        ck("got response", r.size() > 0, 1);
        ck_cdl("[1] READ_DESC(ENTITY) CDL correct (len-26)", r);
        ck("msg_type=AEM_RESPONSE", r_msgt(r), 1);
        ck("status=SUCCESS", r_status(r), 0);
        ck("command=READ_DESCRIPTOR", r_cmd(r), 4);
        ck("sequence echoed", r_seq(r), 0x1001);
        ck("controller_id echoed", r_ctlr(r)==CTLR_ID, 1);
        // payload: cfg(2) reserved(2) then descriptor image at wire 42
        ckbytes("descriptor_type=ENTITY", r, 42, {0x00,0x00});
        ckbytes("descriptor_index=0",     r, 44, {0x00,0x00});
        // entity_id overlaid from CSR at descriptor offset 4 -> wire 46
        ckbytes("entity_id overlaid", r, 46, {0x02,0x00,0x00,0xff,0xfe,0x00,0x00,0x01});
        // entity_name from ROM at descriptor offset 48 -> wire 90
        ckbytes("entity_name 'Milan'", r, 90, {'M','i','l','a','n'});
        // configurations_count at descriptor offset 308 -> wire 350
        ckbytes("configurations_count=1", r, 350, {0x00,0x01});
    }

    // ---------------------------------------------------------------- //
    // 2. READ_DESCRIPTOR(AVB_INTERFACE,0) — MAC + clock_id overlay      //
    // ---------------------------------------------------------------- //
    printf("\n[2] READ_DESCRIPTOR(AVB_INTERFACE,0)\n");
    {
        std::vector<uint8_t> pl; put_be16(pl,0); put_be16(pl,0);
        put_be16(pl, 0x0009); put_be16(pl, 0x0000);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 4, 0x1002, pl));
        auto r = collect_resp();
        ck("status=SUCCESS", r_status(r), 0);
        ck_cdl("[2] READ_DESC(AVB_IF) CDL correct (len-26)", r);
        ckbytes("descriptor_type=AVB_INTERFACE", r, 42, {0x00,0x09});
        // mac_address at descriptor offset 72 -> wire 42+72 = 114
        ckbytes("mac_address overlaid", r, 114, {0x02,0x00,0x00,0xff,0xfe,0x01});
        // clock_identity (MAC EUI-64) at descriptor offset 80 -> wire 122
        ckbytes("clock_identity EUI-64", r, 122,
                {0x02,0x00,0x00,0xff,0xfe,0xff,0xfe,0x01});
    }

    // ---------------------------------------------------------------- //
    // 3. READ_DESCRIPTOR(STREAM_OUTPUT,0) + non-existent descriptor     //
    // ---------------------------------------------------------------- //
    printf("\n[3] READ_DESCRIPTOR(STREAM_OUTPUT,0) + bad index\n");
    {
        std::vector<uint8_t> pl; put_be16(pl,0); put_be16(pl,0);
        put_be16(pl, 0x0006); put_be16(pl, 0x0000);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 4, 0x1003, pl));
        auto r = collect_resp();
        ck("status=SUCCESS", r_status(r), 0);
        ck_cdl("[3] READ_DESC(STREAM_OUT) CDL correct (len-26)", r);
        ckbytes("descriptor_type=STREAM_OUTPUT", r, 42, {0x00,0x06});
        // current_format at descriptor offset 74 -> wire 116
        ckbytes("current_format 48k", r, 116, {0x02,0x05,0x02,0x20,0x02,0x00,0x60,0x00});

        std::vector<uint8_t> pl2; put_be16(pl2,0); put_be16(pl2,0);
        put_be16(pl2, 0x0006); put_be16(pl2, 0x0005);   // index 5 doesn't exist
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 4, 0x1004, pl2));
        auto r2 = collect_resp();
        ck("status=NO_SUCH_DESCRIPTOR", r_status(r2), 2);
    }

    // ---------------------------------------------------------------- //
    // 4. ACQUIRE_ENTITY -> NOT_SUPPORTED (Milan)                        //
    // ---------------------------------------------------------------- //
    printf("\n[4] ACQUIRE_ENTITY -> NOT_SUPPORTED\n");
    {
        std::vector<uint8_t> pl(16, 0);   // flags(4)+owner(8)+desc(4)
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 0, 0x2000, pl));
        auto r = collect_resp();
        ck("command=ACQUIRE_ENTITY", r_cmd(r), 0);
        ck("status=NOT_SUPPORTED", r_status(r), 11);
    }

    // ---------------------------------------------------------------- //
    // 5. LOCK_ENTITY by ctlr1 -> SUCCESS; ctlr2 lock -> ENTITY_LOCKED   //
    // ---------------------------------------------------------------- //
    printf("\n[5] LOCK_ENTITY (owner grant / other denied)\n");
    {
        std::vector<uint8_t> pl(12, 0);   // flags(4)+locked_id(8)
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 1, 0x3000, pl));
        auto r = collect_resp();
        ck("LOCK status=SUCCESS", r_status(r), 0);
        ck_cdl("[5] LOCK CDL correct (len-26)", r);
        ck("command=LOCK_ENTITY", r_cmd(r), 1);

        feed_rx(aecp_cmd(ENT_MAC, CTL2_MAC, ENTITY_ID, CTLR2_ID, 0, 1, 0x3001, pl));
        auto r2 = collect_resp();
        ck("2nd controller LOCK=ENTITY_LOCKED", r_status(r2), 3);
        // response carries the current owner's id (bytes 38..45)
        ckbytes("locked_id = owner ctlr1", r2, 42,
                {0x68,0x05,0xca,0x95,0xb2,0xd1,0x00,0x00});

        // a mutating command from ctlr2 is also blocked
        std::vector<uint8_t> sc; put_be16(sc,0); put_be16(sc,0);  // reserved, config
        feed_rx(aecp_cmd(ENT_MAC, CTL2_MAC, ENTITY_ID, CTLR2_ID, 0, 6, 0x3002, sc));
        auto r3 = collect_resp();
        ck("SET_CONFIG by non-owner=ENTITY_LOCKED", r_status(r3), 3);

        // owner unlocks (flags bit0 = UNLOCK)
        std::vector<uint8_t> pu(12, 0); pu[3] = 0x01;
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 1, 0x3003, pu));
        auto r4 = collect_resp();
        ck("UNLOCK status=SUCCESS", r_status(r4), 0);
    }

    // ---------------------------------------------------------------- //
    // 6. GET/SET_CONFIGURATION                                          //
    // ---------------------------------------------------------------- //
    printf("\n[6] GET/SET_CONFIGURATION\n");
    {
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 7, 0x4000, {}));
        auto r = collect_resp();
        ck("GET_CONFIG status=SUCCESS", r_status(r), 0);
        ck_cdl("[6] GET_CONFIG CDL correct (len-26)", r);
        ckbytes("current_configuration=0", r, 40, {0x00,0x00});

        std::vector<uint8_t> bad; put_be16(bad,0); put_be16(bad,5);  // config 5 invalid
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 6, 0x4001, bad));
        auto r2 = collect_resp();
        ck("SET_CONFIG(5)=BAD_ARGUMENTS", r_status(r2), 7);
    }

    // ---------------------------------------------------------------- //
    // 7. SET_NAME(ENTITY) then READ_DESCRIPTOR shows the new name       //
    // ---------------------------------------------------------------- //
    printf("\n[7] SET_NAME + read-back\n");
    {
        std::vector<uint8_t> pl; put_be16(pl,0x0000); put_be16(pl,0x0000); // ENTITY,0
        put_be16(pl,0x0000); put_be16(pl,0x0000);                          // name_idx, cfg
        const char* nm = "Studio Talker";
        for (int i = 0; i < 64; i++) pl.push_back(i < (int)strlen(nm) ? nm[i] : 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 16, 0x5000, pl));
        auto r = collect_resp();
        ck("SET_NAME status=SUCCESS", r_status(r), 0);
        ck_cdl("[7] SET_NAME CDL correct (len-26)", r);

        std::vector<uint8_t> rd; put_be16(rd,0); put_be16(rd,0);
        put_be16(rd,0x0000); put_be16(rd,0x0000);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 4, 0x5001, rd));
        auto r2 = collect_resp();
        ck("read-back status=SUCCESS", r_status(r2), 0);
        ckbytes("entity_name updated", r2, 90, {'S','t','u','d','i','o',' ','T'});
    }

    // ---------------------------------------------------------------- //
    // 8. GET/SET_SAMPLING_RATE (valid 96k, invalid 44.1k)              //
    // ---------------------------------------------------------------- //
    printf("\n[8] SET_SAMPLING_RATE\n");
    {
        std::vector<uint8_t> ok; put_be16(ok,0x0002); put_be16(ok,0x0000); // AUDIO_UNIT,0
        for (uint8_t b : {0x00,0x01,0x77,0x00}) ok.push_back(b);           // 96000
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 20, 0x6000, ok));
        auto r = collect_resp();
        ck("SET_SAMPLING_RATE(96k)=SUCCESS", r_status(r), 0);
        ckbytes("sampling_rate echoes 96k", r, 42, {0x00,0x01,0x77,0x00});

        std::vector<uint8_t> bad; put_be16(bad,0x0002); put_be16(bad,0x0000);
        for (uint8_t b : {0x00,0x00,0xac,0x44}) bad.push_back(b);          // 44100
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 20, 0x6001, bad));
        auto r2 = collect_resp();
        ck("SET_SAMPLING_RATE(44.1k)=BAD_ARGUMENTS", r_status(r2), 7);
    }

    // ---------------------------------------------------------------- //
    // 9. MVU GET_MILAN_INFO (vendor unique)                            //
    // ---------------------------------------------------------------- //
    printf("\n[9] MVU GET_MILAN_INFO\n");
    {
        std::vector<uint8_t> pl;
        for (uint8_t b : {0x00,0x1B,0xC5,0x0A,0xC1,0x00}) pl.push_back(b); // protocol_id
        put_be16(pl, 0x0000);   // command_type GET_MILAN_INFO
        put_be16(pl, 0x0000);   // reserved
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 6, 0, 0x7000, pl));
        auto r = collect_resp();
        ck("got MVU response", r.size() > 0, 1);
        ck_cdl("[9] MVU CDL correct (len-26)", r);
        ck("msg_type=VU_RESPONSE", r_msgt(r), 7);
        // response: protocol_id(6) echo at wire 38, command_type(2) at 44,
        // reserved(2) at 46, then milan_info(12) at 48
        ckbytes("protocol_id echoed", r, 36, {0x00,0x1B,0xC5,0x0A,0xC1,0x00});
        ckbytes("protocol_version=1", r, 46, {0x00,0x00,0x00,0x01});
        ckbytes("certification_version=0 (not AVnu-certified)", r, 54, {0x00,0x00,0x00,0x00});
    }

    // ---------------------------------------------------------------- //
    // 9b. GET_COUNTERS — Milan-mandatory, ALWAYS full 136-byte payload   //
    // ---------------------------------------------------------------- //
    printf("\n[9b] GET_COUNTERS (full-size responses, all statuses)\n");
    {
        std::vector<uint8_t> so; put_be16(so, 0x0006); put_be16(so, 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 41, 0x9100, so));
        auto r = collect_resp();
        ck("STREAM_OUTPUT counters SUCCESS", r_status(r), 0);
        ck_cdl("STREAM_OUTPUT counters CDL (len-26)", r);
        ck("counters CDL == 148", r_cdl(r), 148);
        ckbytes("counters_valid 0x1F", r, 42, {0x00,0x00,0x00,0x1F});

        std::vector<uint8_t> av; put_be16(av, 0x0009); put_be16(av, 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 41, 0x9101, av));
        auto r2 = collect_resp();
        ck("AVB_INTERFACE counters SUCCESS", r_status(r2), 0);
        ckbytes("counters_valid 0x23", r2, 42, {0x00,0x00,0x00,0x23});

        std::vector<uint8_t> en; put_be16(en, 0x0000); put_be16(en, 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 41, 0x9102, en));
        auto r3 = collect_resp();
        ck("ENTITY counters BAD_ARGUMENTS", r_status(r3), 7);
        ck("error response STILL full-size (CDL 148)", r_cdl(r3), 148);   // the Hive field-report class

        std::vector<uint8_t> nx; put_be16(nx, 0x0005); put_be16(nx, 9);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 41, 0x9103, nx));
        auto r4 = collect_resp();
        ck("unknown desc NO_SUCH_DESCRIPTOR", r_status(r4), 2);
        ck("error response full-size (CDL 148)", r_cdl(r4), 148);
    }

    // ---------------------------------------------------------------- //
    // 9c. GET_AS_PATH — Milan-mandatory; count=1, path[0]=clock_identity //
    // ---------------------------------------------------------------- //
    printf("\n[9c] GET_AS_PATH\n");
    {
        std::vector<uint8_t> ap; put_be16(ap, 0); put_be16(ap, 0);   // desc_index, reserved
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 40, 0x9200, ap));
        auto r = collect_resp();
        ck("AS_PATH SUCCESS", r_status(r), 0);
        ck("AS_PATH CDL == 24", r_cdl(r), 24);
        ck_cdl("AS_PATH CDL (len-26)", r);
        ckbytes("AS_PATH count == 1", r, 40, {0x00,0x01});
        // clock_identity = MAC-derived EUI64, same as the AVB_INTERFACE overlay
        ckbytes("AS_PATH path[0] == EUI64(station MAC)", r, 42,
                {0x02,0x00,0x00,0xFF,0xFE,0xFF,0xFE,0x01});

        std::vector<uint8_t> bad; put_be16(bad, 3); put_be16(bad, 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 40, 0x9201, bad));
        auto r2 = collect_resp();
        ck("AS_PATH bad index NO_SUCH_DESCRIPTOR", r_status(r2), 2);
        ck("AS_PATH error keeps full payload (CDL 24)", r_cdl(r2), 24);
    }

    // ---------------------------------------------------------------- //
    // 10. Frame for a DIFFERENT entity_id -> ignored (no response)      //
    // ---------------------------------------------------------------- //
    printf("\n[10] wrong target entity_id -> silent\n");
    {
        std::vector<uint8_t> pl; put_be16(pl,0); put_be16(pl,0);
        put_be16(pl,0x0000); put_be16(pl,0x0000);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, 0xDEADBEEF00000000ULL, CTLR_ID, 0, 4, 0x8000, pl));
        auto r = collect_resp(600);
        ck("no response to foreign entity_id", r.size()==0, 1);
    }

    // ---------------------------------------------------------------- //
    // 11. ADP ENTITY_DISCOVER -> discover pulse                         //
    // ---------------------------------------------------------------- //
    printf("\n[11] ADP ENTITY_DISCOVER -> discover pulse\n");
    {
        // ADP discover frame: dst 91:e0:f0:01:00:00, subtype FA, msg 2, target 0
        std::vector<uint8_t> f;
        for (uint8_t b : {0x91,0xe0,0xf0,0x01,0x00,0x00}) f.push_back(b);
        for (int i=0;i<6;i++) f.push_back(CTL_MAC[i]);
        put_be16(f, 0x22F0); f.push_back(0xFA);
        f.push_back((0<<4)|2);              // msg_type = ENTITY_DISCOVER
        f.push_back(0x00); f.push_back(0x38);
        put_be64(f, 0);                      // target_entity_id = 0 (all)
        while (f.size() < 60) f.push_back(0);
        int seen = 0;
        // feed and watch adp_discover_o across the frame + a few cycles
        int n = f.size();
        for (int off = 0; off < n; off += 8) {
            uint64_t d=0; uint8_t keep=0;
            for (int l=0;l<8;l++){ if(off+l<n){ d|=(uint64_t)f[off+l]<<(8*l); keep|=(1<<l);} }
            dut->rx_tvalid_i=1; dut->rx_tdata_i=d; dut->rx_tkeep_i=keep;
            dut->rx_tlast_i=(off+8>=n); tick();
            if (dut->adp_discover_o) seen++;
        }
        dut->rx_tvalid_i=0; dut->rx_tlast_i=0;
        for (int c=0;c<8;c++){ tick(); if (dut->adp_discover_o) seen++; }
        ck("adp_discover pulse asserted", seen>=1, 1);
    }

    // counters
    printf("\n[counters] cmd=%u resp=%u\n", dut->cmd_count_o, dut->resp_count_o);
    ck("cmd_count >= 14", dut->cmd_count_o >= 14, 1);

    printf("\n======================================================================\n");
    printf("AECP subsystem: %ld checks, %ld failures\n", checks, fails);
    delete dut;
    return fails ? 1 : 0;
}
