/*
 * SPDX-FileCopyrightText: 2026 Kebag Logic
 * SPDX-License-Identifier: CERN-OHL-W-2.0
 *
 * Self-checking Verilator harness for the AECP/AEM listener subsystem
 * (KL_aecp_top). Crafts real AECP command Ethernet frames, drives them into
 * the RX monitor tap, collects the response frames from the TX AXIS master,
 * and checks the AECP common header + payload against the Milan v1.2 entity
 * model (5 descriptors). Exit 0 = all pass.
 */

#include "VKL_aecp_top.h"
#include "verilated.h"
#include "aem_golden.h"   // generated by avdecc/gen_aem_store.py (-I.. -> this dir)
#include <cstdio>
#include <cstring>
#include <cstdint>
#include <vector>
#include <deque>
#include <string>

static VKL_aecp_top* dut;
static vluint64_t tk = 0;
static long checks = 0, fails = 0;

static void tick() {
    dut->clk_i = 0; dut->eval();
    dut->clk_i = 1; dut->eval();
    tk++;
}
static void ck(const char* what, long got, long exp) {
    checks++;
    if (got != exp) { fails++; printf("  [FAIL] %-40s got=%ld exp=%ld\n", what, got, exp); }
    else            { printf("  [ ok ] %-40s = %ld\n", what, got); }
}
static void ckbytes(const char* what, const std::vector<uint8_t>& g, int off,
                    const std::vector<uint8_t>& exp) {
    checks++;
    bool bad = (int)g.size() < off + (int)exp.size();
    for (size_t i = 0; !bad && i < exp.size(); i++) if (g[off+i] != exp[i]) bad = true;
    if (bad) {
        fails++; printf("  [FAIL] %-40s off=%d\n         exp:", what, off);
        for (auto b : exp) printf(" %02x", b);
        printf("\n         got:");
        for (size_t i = 0; i < exp.size() && off+(int)i < (int)g.size(); i++) printf(" %02x", g[off+i]);
        printf("\n");
    } else printf("  [ ok ] %-40s (%zu bytes @ %d)\n", what, exp.size(), off);
}

// ------------------------------------------------------------------ identity
static const uint8_t ENT_MAC[6] = {0x02,0x00,0x00,0xff,0xfe,0x01};   // our station
static const uint8_t CTL_MAC[6] = {0x68,0x05,0xca,0x95,0xb2,0xd1};   // controller
static const uint8_t CTL2_MAC[6]= {0xaa,0xbb,0xcc,0xdd,0xee,0x02};
static const uint64_t ENTITY_ID = 0x0200'00ff'fe00'0001ULL;
static const uint64_t CTLR_ID   = 0x6805'ca95'b2d1'0000ULL;
static const uint64_t CTLR2_ID  = 0xaabb'ccdd'eeff'0002ULL;

static void put_be64(std::vector<uint8_t>& v, uint64_t x) {
    for (int i = 7; i >= 0; i--) v.push_back((x >> (8*i)) & 0xFF);
}
static void put_be16(std::vector<uint8_t>& v, uint16_t x) {
    v.push_back(x >> 8); v.push_back(x & 0xFF);
}

// Build an AECP AEM/VU command frame (wire order), pad to 60 bytes.
//   msg_type: 0=AEM_COMMAND, 6=VU_COMMAND
//   cmd:      command_type (AEM) — ignored for VU (payload carries it)
static std::vector<uint8_t> aecp_cmd(const uint8_t* dst, const uint8_t* src,
                                     uint64_t target, uint64_t ctlr,
                                     uint8_t msg_type, uint16_t cmd,
                                     uint16_t seq, const std::vector<uint8_t>& payload,
                                     bool unsol=false) {
    std::vector<uint8_t> f;
    for (int i=0;i<6;i++) f.push_back(dst[i]);
    for (int i=0;i<6;i++) f.push_back(src[i]);
    put_be16(f, 0x22F0);                       // ethertype
    f.push_back(0xFB);                          // subtype AECP
    f.push_back((0<<7)|(0<<4)|(msg_type&0xF));  // sv/ver/msg_type
    bool aem = (msg_type != 6);
    // cdl = octets after control_data_length: ctlr(8)+seq(2)+[u/cmd(2) if AEM]+payload
    uint16_t cdl = (aem ? 12 : 10) + (uint16_t)payload.size();
    f.push_back(((0/*status*/&0x1F)<<3) | ((cdl>>8)&0x7)); // status|cdl_hi
    f.push_back(cdl & 0xFF);                    // cdl_lo
    put_be64(f, target);
    put_be64(f, ctlr);
    put_be16(f, seq);
    // AEM frames carry u+command_type here; VU frames go straight to the
    // protocol_id the caller placed at the head of `payload`.
    if (aem) {
        f.push_back(((unsol?1:0)<<7) | ((cmd>>8)&0x7F));  // u|cmd_hi
        f.push_back(cmd & 0xFF);                          // cmd_lo
    }
    for (auto b : payload) f.push_back(b);
    while (f.size() < 60) f.push_back(0x00);    // pad to min Ethernet
    return f;
}

// Drive a frame into the RX monitor tap (little lane, 8 bytes/beat).
static void feed_rx(const std::vector<uint8_t>& f) {
    int n = f.size();
    for (int off = 0; off < n; off += 8) {
        uint64_t d = 0; uint8_t keep = 0;
        for (int l = 0; l < 8; l++) {
            if (off + l < n) { d |= (uint64_t)f[off+l] << (8*l); keep |= (1<<l); }
        }
        dut->rx_tvalid_i = 1;
        dut->rx_tdata_i  = d;
        dut->rx_tkeep_i  = keep;
        dut->rx_tlast_i  = (off + 8 >= n);
        tick();
    }
    dut->rx_tvalid_i = 0; dut->rx_tlast_i = 0; dut->rx_tkeep_i = 0;
}

// Collect one response frame from the TX AXIS master (little lane -> wire bytes).
// Returns empty if none within `budget` cycles.
static std::vector<uint8_t> collect_resp(int budget = 6000) {
    std::vector<uint8_t> b;
    int idle = 0;
    dut->m_axis_tready = 1;
    for (int c = 0; c < budget; c++) {
        dut->eval();
        if (dut->m_axis_tvalid && dut->m_axis_tready) {
            for (int l = 0; l < 8; l++)
                if ((dut->m_axis_tkeep >> l) & 1)
                    b.push_back((dut->m_axis_tdata >> (8*l)) & 0xFF);
            bool last = dut->m_axis_tlast;
            tick();
            if (last) return b;
            idle = 0;
        } else {
            tick();
            // tolerate inter-beat gaps (2-cycle assembly cadence); give up only
            // after a long idle (empty result = no response, e.g. a dropped frame).
            if (++idle > 500) return b;
        }
    }
    return b;   // empty = timeout
}

// AECP response header field accessors (wire bytes)
static int r_status(const std::vector<uint8_t>& b){ return b.size()>16 ? (b[16]>>3)&0x1F : -1; }
static int r_msgt (const std::vector<uint8_t>& b){ return b.size()>15 ? b[15]&0x0F : -1; }
static int r_cmd  (const std::vector<uint8_t>& b){ return b.size()>37 ? ((b[36]&0x7F)<<8)|b[37] : -1; }
static uint64_t r_ctlr(const std::vector<uint8_t>& b){ if(b.size()<34) return 0; uint64_t v=0; for(int i=0;i<8;i++) v=(v<<8)|b[26+i]; return v; }
static int r_seq  (const std::vector<uint8_t>& b){ return b.size()>35 ? (b[34]<<8)|b[35] : -1; }
static int r_cdl  (const std::vector<uint8_t>& b){ return b.size()>17 ? ((b[16]&0x07)<<8)|b[17] : -1; }
// IEEE 1722-2016 §5.4: control_data_length counts the octets FOLLOWING the
// stream_id (target_entity_id) field — i.e. from wire offset 26 (after
// eth 14 + subtype/sv/status/cdl 4 + target_entity_id 8). The pipewire AVB
// reference (Hive-validated) confirms it: CDL = payload + AVB_PACKET_
// CONTROL_DATA_OFFSET(12) = frame - 26. The builder emits no padding so
// CDL must equal len - 26. (NB: tsn-gen's CDL model wrongly counts
// target_entity_id — do not use it as the oracle here.)
static void ck_cdl(const char* nm, const std::vector<uint8_t>& b){
    ck(nm, (b.size()>26) && (r_cdl(b) == (int)b.size()-26), 1);
}

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    setvbuf(stdout, NULL, _IONBF, 0);
    dut = new VKL_aecp_top;

    // reset
    dut->rst_n = 0; dut->enable_i = 1;
    dut->rx_tvalid_i = 0; dut->m_axis_tready = 1;
    dut->station_mac_i = 0; dut->entity_id_i = ENTITY_ID;
    dut->entity_model_id_i = 0;
    dut->entity_caps_i = 0x00008588; dut->talker_sources_i = 8; dut->talker_caps_i = 0x4801;
    dut->listener_sinks_i = 8; dut->listener_caps_i = 0x4801; dut->controller_caps_i = 0;
    dut->available_index_i = 7; dut->association_id_i = 0;
    dut->gptp_gm_id_i = 0x0011223344556677ULL; dut->gptp_domain_i = 0;
    dut->link_up_i = 1; dut->frames_tx_i = 0;
    // station MAC [47:40]=first wire byte
    { uint64_t m=0; for(int i=0;i<6;i++) m=(m<<8)|ENT_MAC[i]; dut->station_mac_i = m; }
    for (int i = 0; i < 8; i++) tick();
    dut->rst_n = 1;
    for (int i = 0; i < 4; i++) tick();

    printf("== AECP/AEM listener subsystem — Milan v1.2 entity ==\n");

    // ---------------------------------------------------------------- //
    // 1. READ_DESCRIPTOR(ENTITY, 0)                                     //
    // ---------------------------------------------------------------- //
    printf("\n[1] READ_DESCRIPTOR(ENTITY,0)\n");
    {
        std::vector<uint8_t> pl; put_be16(pl,0); put_be16(pl,0);         // cfg, reserved
        put_be16(pl, 0x0000); put_be16(pl, 0x0000);                      // type ENTITY, index 0
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 4, 0x1001, pl));
        auto r = collect_resp();
        fprintf(stderr,"RESP1 %zu bytes:", r.size());
        for(size_t i=0;i<r.size()&&i<80;i++) fprintf(stderr," %02x", r[i]);
        fprintf(stderr,"\n");
        ck("got response", r.size() > 0, 1);
        ck_cdl("[1] READ_DESC(ENTITY) CDL correct (len-26)", r);
        ck("msg_type=AEM_RESPONSE", r_msgt(r), 1);
        ck("status=SUCCESS", r_status(r), 0);
        ck("command=READ_DESCRIPTOR", r_cmd(r), 4);
        ck("sequence echoed", r_seq(r), 0x1001);
        ck("controller_id echoed", r_ctlr(r)==CTLR_ID, 1);
        // payload: cfg(2) reserved(2) then descriptor image at wire 42
        ckbytes("descriptor_type=ENTITY", r, 42, {0x00,0x00});
        ckbytes("descriptor_index=0",     r, 44, {0x00,0x00});
        // entity_id overlaid from CSR at descriptor offset 4 -> wire 46
        ckbytes("entity_id overlaid", r, 46, {0x02,0x00,0x00,0xff,0xfe,0x00,0x00,0x01});
        // entity_name from ROM at descriptor offset 48 -> wire 90
        ckbytes("entity_name 'Milan'", r, 90, {'M','i','l','a','n'});
        // configurations_count at descriptor offset 308 -> wire 350
        ckbytes("configurations_count=1", r, 350, {0x00,0x01});
    }

    // ---------------------------------------------------------------- //
    // 2. READ_DESCRIPTOR(AVB_INTERFACE,0) — MAC + clock_id overlay      //
    // ---------------------------------------------------------------- //
    printf("\n[2] READ_DESCRIPTOR(AVB_INTERFACE,0)\n");
    {
        std::vector<uint8_t> pl; put_be16(pl,0); put_be16(pl,0);
        put_be16(pl, 0x0009); put_be16(pl, 0x0000);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 4, 0x1002, pl));
        auto r = collect_resp();
        ck("status=SUCCESS", r_status(r), 0);
        ck_cdl("[2] READ_DESC(AVB_IF) CDL correct (len-26)", r);
        ckbytes("descriptor_type=AVB_INTERFACE", r, 42, {0x00,0x09});
        // mac_address at descriptor offset 72 -> wire 42+72 = 114
        ckbytes("mac_address overlaid", r, 114, {0x02,0x00,0x00,0xff,0xfe,0x01});
        // clock_identity (MAC EUI-64) at descriptor offset 80 -> wire 122
        ckbytes("clock_identity EUI-64", r, 122,
                {0x02,0x00,0x00,0xff,0xfe,0xff,0xfe,0x01});
    }

    // ---------------------------------------------------------------- //
    // 3. READ_DESCRIPTOR(STREAM_OUTPUT,0) + non-existent descriptor     //
    // ---------------------------------------------------------------- //
    printf("\n[3] READ_DESCRIPTOR(STREAM_OUTPUT,0) + bad index\n");
    {
        std::vector<uint8_t> pl; put_be16(pl,0); put_be16(pl,0);
        put_be16(pl, 0x0006); put_be16(pl, 0x0000);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 4, 0x1003, pl));
        auto r = collect_resp();
        ck("status=SUCCESS", r_status(r), 0);
        ck_cdl("[3] READ_DESC(STREAM_OUT) CDL correct (len-26)", r);
        ckbytes("descriptor_type=STREAM_OUTPUT", r, 42, {0x00,0x06});
        // current_format at descriptor offset 74 -> wire 116
        ckbytes("current_format 48k", r, 116, {0x02,0x05,0x02,0x20,0x02,0x00,0x60,0x00});

        std::vector<uint8_t> pl2; put_be16(pl2,0); put_be16(pl2,0);
        put_be16(pl2, 0x0006); put_be16(pl2, 0x0005);   // index 5 doesn't exist
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 4, 0x1004, pl2));
        auto r2 = collect_resp();
        ck("status=NO_SUCH_DESCRIPTOR", r_status(r2), 2);
    }

    // ---------------------------------------------------------------- //
    // 4. ACQUIRE_ENTITY -> NOT_SUPPORTED (Milan)                        //
    // ---------------------------------------------------------------- //
    printf("\n[4] ACQUIRE_ENTITY -> NOT_SUPPORTED\n");
    {
        std::vector<uint8_t> pl(16, 0);   // flags(4)+owner(8)+desc(4)
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 0, 0x2000, pl));
        auto r = collect_resp();
        ck("command=ACQUIRE_ENTITY", r_cmd(r), 0);
        ck("status=NOT_SUPPORTED", r_status(r), 11);
    }

    // ---------------------------------------------------------------- //
    // 5. LOCK_ENTITY by ctlr1 -> SUCCESS; ctlr2 lock -> ENTITY_LOCKED   //
    // ---------------------------------------------------------------- //
    printf("\n[5] LOCK_ENTITY (owner grant / other denied)\n");
    {
        std::vector<uint8_t> pl(12, 0);   // flags(4)+locked_id(8)
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 1, 0x3000, pl));
        auto r = collect_resp();
        ck("LOCK status=SUCCESS", r_status(r), 0);
        ck_cdl("[5] LOCK CDL correct (len-26)", r);
        ck("command=LOCK_ENTITY", r_cmd(r), 1);

        feed_rx(aecp_cmd(ENT_MAC, CTL2_MAC, ENTITY_ID, CTLR2_ID, 0, 1, 0x3001, pl));
        auto r2 = collect_resp();
        ck("2nd controller LOCK=ENTITY_LOCKED", r_status(r2), 3);
        // response carries the current owner's id (bytes 38..45)
        ckbytes("locked_id = owner ctlr1", r2, 42,
                {0x68,0x05,0xca,0x95,0xb2,0xd1,0x00,0x00});

        // a mutating command from ctlr2 is also blocked
        std::vector<uint8_t> sc; put_be16(sc,0); put_be16(sc,0);  // reserved, config
        feed_rx(aecp_cmd(ENT_MAC, CTL2_MAC, ENTITY_ID, CTLR2_ID, 0, 6, 0x3002, sc));
        auto r3 = collect_resp();
        ck("SET_CONFIG by non-owner=ENTITY_LOCKED", r_status(r3), 3);

        // owner unlocks (flags bit0 = UNLOCK)
        std::vector<uint8_t> pu(12, 0); pu[3] = 0x01;
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 1, 0x3003, pu));
        auto r4 = collect_resp();
        ck("UNLOCK status=SUCCESS", r_status(r4), 0);
    }

    // ---------------------------------------------------------------- //
    // 6. GET/SET_CONFIGURATION                                          //
    // ---------------------------------------------------------------- //
    printf("\n[6] GET/SET_CONFIGURATION\n");
    {
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 7, 0x4000, {}));
        auto r = collect_resp();
        ck("GET_CONFIG status=SUCCESS", r_status(r), 0);
        ck_cdl("[6] GET_CONFIG CDL correct (len-26)", r);
        ckbytes("current_configuration=0", r, 40, {0x00,0x00});

        std::vector<uint8_t> bad; put_be16(bad,0); put_be16(bad,5);  // config 5 invalid
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 6, 0x4001, bad));
        auto r2 = collect_resp();
        ck("SET_CONFIG(5)=BAD_ARGUMENTS", r_status(r2), 7);
    }

    // ---------------------------------------------------------------- //
    // 7. SET_NAME(ENTITY) then READ_DESCRIPTOR shows the new name       //
    // ---------------------------------------------------------------- //
    printf("\n[7] SET_NAME + read-back\n");
    {
        std::vector<uint8_t> pl; put_be16(pl,0x0000); put_be16(pl,0x0000); // ENTITY,0
        put_be16(pl,0x0000); put_be16(pl,0x0000);                          // name_idx, cfg
        const char* nm = "Studio Talker";
        for (int i = 0; i < 64; i++) pl.push_back(i < (int)strlen(nm) ? nm[i] : 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 16, 0x5000, pl));
        auto r = collect_resp();
        ck("SET_NAME status=SUCCESS", r_status(r), 0);
        ck_cdl("[7] SET_NAME CDL correct (len-26)", r);

        std::vector<uint8_t> rd; put_be16(rd,0); put_be16(rd,0);
        put_be16(rd,0x0000); put_be16(rd,0x0000);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 4, 0x5001, rd));
        auto r2 = collect_resp();
        ck("read-back status=SUCCESS", r_status(r2), 0);
        ckbytes("entity_name updated", r2, 90, {'S','t','u','d','i','o',' ','T'});
    }

    // ---------------------------------------------------------------- //
    // 8. GET/SET_SAMPLING_RATE (valid 96k, invalid 44.1k)              //
    // ---------------------------------------------------------------- //
    printf("\n[8] SET_SAMPLING_RATE\n");
    {
        std::vector<uint8_t> ok; put_be16(ok,0x0002); put_be16(ok,0x0000); // AUDIO_UNIT,0
        for (uint8_t b : {0x00,0x01,0x77,0x00}) ok.push_back(b);           // 96000
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 20, 0x6000, ok));
        auto r = collect_resp();
        ck("SET_SAMPLING_RATE(96k)=SUCCESS", r_status(r), 0);
        ckbytes("sampling_rate echoes 96k", r, 42, {0x00,0x01,0x77,0x00});

        std::vector<uint8_t> bad; put_be16(bad,0x0002); put_be16(bad,0x0000);
        for (uint8_t b : {0x00,0x00,0xac,0x44}) bad.push_back(b);          // 44100
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 20, 0x6001, bad));
        auto r2 = collect_resp();
        ck("SET_SAMPLING_RATE(44.1k)=BAD_ARGUMENTS", r_status(r2), 7);
    }

    // ---------------------------------------------------------------- //
    // 9. MVU GET_MILAN_INFO (vendor unique)                            //
    // ---------------------------------------------------------------- //
    printf("\n[9] MVU GET_MILAN_INFO\n");
    {
        std::vector<uint8_t> pl;
        for (uint8_t b : {0x00,0x1B,0xC5,0x0A,0xC1,0x00}) pl.push_back(b); // protocol_id
        put_be16(pl, 0x0000);   // command_type GET_MILAN_INFO
        put_be16(pl, 0x0000);   // reserved
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 6, 0, 0x7000, pl));
        auto r = collect_resp();
        ck("got MVU response", r.size() > 0, 1);
        ck_cdl("[9] MVU CDL correct (len-26)", r);
        ck("msg_type=VU_RESPONSE", r_msgt(r), 7);
        // response: protocol_id(6) echo at wire 38, command_type(2) at 44,
        // reserved(2) at 46, then milan_info(12) at 48
        ckbytes("protocol_id echoed", r, 36, {0x00,0x1B,0xC5,0x0A,0xC1,0x00});
        ckbytes("protocol_version=1", r, 46, {0x00,0x00,0x00,0x01});
        ckbytes("certification_version=0 (not AVnu-certified)", r, 54, {0x00,0x00,0x00,0x00});
    }

    // ---------------------------------------------------------------- //
    // 9b. GET_COUNTERS — Milan-mandatory, ALWAYS full 136-byte payload   //
    // ---------------------------------------------------------------- //
    printf("\n[9b] GET_COUNTERS (full-size responses, all statuses)\n");
    {
        std::vector<uint8_t> so; put_be16(so, 0x0006); put_be16(so, 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 41, 0x9100, so));
        auto r = collect_resp();
        ck("STREAM_OUTPUT counters SUCCESS", r_status(r), 0);
        ck_cdl("STREAM_OUTPUT counters CDL (len-26)", r);
        ck("counters CDL == 148", r_cdl(r), 148);
        ckbytes("counters_valid 0x1F", r, 42, {0x00,0x00,0x00,0x1F});

        std::vector<uint8_t> av; put_be16(av, 0x0009); put_be16(av, 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 41, 0x9101, av));
        auto r2 = collect_resp();
        ck("AVB_INTERFACE counters SUCCESS", r_status(r2), 0);
        ckbytes("counters_valid 0x23", r2, 42, {0x00,0x00,0x00,0x23});

        std::vector<uint8_t> en; put_be16(en, 0x0000); put_be16(en, 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 41, 0x9102, en));
        auto r3 = collect_resp();
        ck("ENTITY counters BAD_ARGUMENTS", r_status(r3), 7);
        ck("error response STILL full-size (CDL 148)", r_cdl(r3), 148);   // the Hive field-report class

        std::vector<uint8_t> nx; put_be16(nx, 0x0005); put_be16(nx, 9);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 41, 0x9103, nx));
        auto r4 = collect_resp();
        ck("unknown desc NO_SUCH_DESCRIPTOR", r_status(r4), 2);
        ck("error response full-size (CDL 148)", r_cdl(r4), 148);
    }

    // ---------------------------------------------------------------- //
    // 9c. GET_AS_PATH — Milan-mandatory; count=1, path[0]=clock_identity //
    // ---------------------------------------------------------------- //
    printf("\n[9c] GET_AS_PATH\n");
    {
        std::vector<uint8_t> ap; put_be16(ap, 0); put_be16(ap, 0);   // desc_index, reserved
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 40, 0x9200, ap));
        auto r = collect_resp();
        ck("AS_PATH SUCCESS", r_status(r), 0);
        ck("AS_PATH CDL == 24", r_cdl(r), 24);
        ck_cdl("AS_PATH CDL (len-26)", r);
        ckbytes("AS_PATH count == 1", r, 40, {0x00,0x01});
        // clock_identity = MAC-derived EUI64, same as the AVB_INTERFACE overlay
        ckbytes("AS_PATH path[0] == EUI64(station MAC)", r, 42,
                {0x02,0x00,0x00,0xFF,0xFE,0xFF,0xFE,0x01});

        std::vector<uint8_t> bad; put_be16(bad, 3); put_be16(bad, 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 40, 0x9201, bad));
        auto r2 = collect_resp();
        ck("AS_PATH bad index NO_SUCH_DESCRIPTOR", r_status(r2), 2);
        ck("AS_PATH error keeps full payload (CDL 24)", r_cdl(r2), 24);
    }

    // ---------------------------------------------------------------- //
    // 10. Frame for a DIFFERENT entity_id -> ignored (no response)      //
    // ---------------------------------------------------------------- //
    printf("\n[10] wrong target entity_id -> silent\n");
    {
        std::vector<uint8_t> pl; put_be16(pl,0); put_be16(pl,0);
        put_be16(pl,0x0000); put_be16(pl,0x0000);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, 0xDEADBEEF00000000ULL, CTLR_ID, 0, 4, 0x8000, pl));
        auto r = collect_resp(600);
        ck("no response to foreign entity_id", r.size()==0, 1);
    }

    // ---------------------------------------------------------------- //
    // 11. ADP ENTITY_DISCOVER -> discover pulse                         //
    // ---------------------------------------------------------------- //
    printf("\n[11] ADP ENTITY_DISCOVER -> discover pulse\n");
    {
        // ADP discover frame: dst 91:e0:f0:01:00:00, subtype FA, msg 2, target 0
        std::vector<uint8_t> f;
        for (uint8_t b : {0x91,0xe0,0xf0,0x01,0x00,0x00}) f.push_back(b);
        for (int i=0;i<6;i++) f.push_back(CTL_MAC[i]);
        put_be16(f, 0x22F0); f.push_back(0xFA);
        f.push_back((0<<4)|2);              // msg_type = ENTITY_DISCOVER
        f.push_back(0x00); f.push_back(0x38);
        put_be64(f, 0);                      // target_entity_id = 0 (all)
        while (f.size() < 60) f.push_back(0);
        int seen = 0;
        // feed and watch adp_discover_o across the frame + a few cycles
        int n = f.size();
        for (int off = 0; off < n; off += 8) {
            uint64_t d=0; uint8_t keep=0;
            for (int l=0;l<8;l++){ if(off+l<n){ d|=(uint64_t)f[off+l]<<(8*l); keep|=(1<<l);} }
            dut->rx_tvalid_i=1; dut->rx_tdata_i=d; dut->rx_tkeep_i=keep;
            dut->rx_tlast_i=(off+8>=n); tick();
            if (dut->adp_discover_o) seen++;
        }
        dut->rx_tvalid_i=0; dut->rx_tlast_i=0;
        for (int c=0;c<8;c++){ tick(); if (dut->adp_discover_o) seen++; }
        ck("adp_discover pulse asserted", seen>=1, 1);
    }

    // ---------------------------------------------------------------- //
    // 12. Milan talker streaming state (docs/design/MILAN_TALKER_SM.md)  //
    //     GET_STREAM_INFO live values, SET_STREAM_INFO matrix,           //
    //     START/STOP_STREAMING = NOT_SUPPORTED on outputs                //
    // ---------------------------------------------------------------- //
    printf("\n[12] Milan talker stream info\n");
    {
        // live inputs: the framer's CSR values
        dut->aaf_dmac_i = 0x91E0F000FE01ULL;
        dut->aaf_vid_i  = 2;
        dut->talker_active_i = 0;
        dut->listener_observed_i = 0;

        auto gsi_pl = []() {                    // GET payload: type+index
            std::vector<uint8_t> pl; put_be16(pl, 0x0006); put_be16(pl, 0);
            return pl;
        };
        auto ssi_pl = [](uint32_t flags, uint32_t lat, uint16_t dtype = 0x0006,
                         uint16_t didx = 0) {   // SET payload: full 56-B block
            std::vector<uint8_t> pl; put_be16(pl, dtype); put_be16(pl, didx);
            for (int i = 3; i >= 0; i--) pl.push_back((flags >> (8*i)) & 0xFF);
            for (int i = 0; i < 16; i++) pl.push_back(0);   // format + stream_id
            for (int i = 3; i >= 0; i--) pl.push_back((lat >> (8*i)) & 0xFF);
            while (pl.size() < 56) pl.push_back(0);
            return pl;
        };
        auto be_at = [](const std::vector<uint8_t>& b, int off, int n) {
            uint64_t v = 0;
            for (int i = 0; i < n; i++) v = (v << 8) | b[off + i];
            return v;
        };

        // (a) GET: live values — stream_id MUST be {station_mac, 0} (the
        //     AVTP/ACMP formula; the old entity_id here was the bug)
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 15, 0x1201, gsi_pl()));
        auto r = collect_resp();
        ck("[12a] GET_STREAM_INFO SUCCESS", r_status(r), 0);
        ck_cdl("[12a] CDL correct (len-26)", r);
        ck("[12a] flags 0xF6000000", be_at(r, 42, 4), 0xF6000000ULL);
        ck("[12a] stream_id {mac,0}", be_at(r, 54, 8), 0x020000FFFE010000ULL);
        ck("[12a] msrp_lat default 2ms", be_at(r, 62, 4), 2000000);
        ck("[12a] dest_mac live", be_at(r, 66, 6), 0x91E0F000FE01ULL);
        ck("[12a] vlan live", be_at(r, 82, 2), 2);
        ck("[12a] flags_ex 0 (no listener)", be_at(r, 86, 4), 0);

        // (b) SET msrp_acc_lat -> SUCCESS; GET reflects the new value
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 14, 0x1202,
                         ssi_pl(0x20000000u, 1000000)));
        r = collect_resp();
        ck("[12b] SET(ACC_LAT) SUCCESS", r_status(r), 0);
        ck("[12b] SET echoes flags", be_at(r, 42, 4), 0x20000000ULL);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 15, 0x1203, gsi_pl()));
        r = collect_resp();
        ck("[12b] GET reflects 1ms", be_at(r, 62, 4), 1000000);

        // (c) any other spec sub-command -> NOT_SUPPORTED, value untouched
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 14, 0x1204,
                         ssi_pl(0x60000000u, 555)));   // STREAM_ID_VALID too
        r = collect_resp();
        ck("[12c] SET(unsupported) NOT_SUPPORTED", r_status(r), 11);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 15, 0x1205, gsi_pl()));
        r = collect_resp();
        ck("[12c] value untouched", be_at(r, 62, 4), 1000000);

        // (d) out-of-range latency -> BAD_ARGUMENTS
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 14, 0x1206,
                         ssi_pl(0x20000000u, 0x80000000u)));
        r = collect_resp();
        ck("[12d] SET(>0x7FFFFFFF) BAD_ARGUMENTS", r_status(r), 7);

        // (e) no sub-command requested -> SUCCESS no-op
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 14, 0x1207,
                         ssi_pl(0, 42)));
        r = collect_resp();
        ck("[12e] SET(none) SUCCESS", r_status(r), 0);

        // (f) STREAM_IS_RUNNING while a listener is registered; REGISTERING
        //     flags_ex when also declaring
        dut->listener_observed_i = 1;
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 14, 0x1208,
                         ssi_pl(0x20000000u, 777)));
        r = collect_resp();
        ck("[12f] SET while running -> STREAM_IS_RUNNING", r_status(r), 12);
        dut->talker_active_i = 1;
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 15, 0x1209, gsi_pl()));
        r = collect_resp();
        ck("[12f] flags_ex REGISTERING", be_at(r, 86, 4), 1);
        dut->talker_active_i = 0;
        dut->listener_observed_i = 0;

        // (g) SET on a STREAM_INPUT -> NOT_SUPPORTED; on a non-stream
        //     descriptor -> BAD_ARGUMENTS
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 14, 0x120A,
                         ssi_pl(0x20000000u, 1, /*dtype*/0x0005)));
        r = collect_resp();
        ck("[12g] SET(STREAM_INPUT) NOT_SUPPORTED", r_status(r), 11);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 14, 0x120B,
                         ssi_pl(0x20000000u, 1, /*dtype*/0x0000)));
        r = collect_resp();
        ck("[12g] SET(ENTITY) BAD_ARGUMENTS", r_status(r), 7);

        // (h) START/STOP_STREAMING: Stream-INPUT-only commands ->
        //     NOT_SUPPORTED on this talker (was NOT_IMPLEMENTED default)
        std::vector<uint8_t> ss_pl; put_be16(ss_pl, 0x0006); put_be16(ss_pl, 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 34, 0x120C, ss_pl));
        r = collect_resp();
        ck("[12h] START_STREAMING NOT_SUPPORTED", r_status(r), 11);
        ck("[12h] START echoes cmd", r_cmd(r), 34);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 35, 0x120D, ss_pl));
        r = collect_resp();
        ck("[12h] STOP_STREAMING NOT_SUPPORTED", r_status(r), 11);
    }

    // ---------------------------------------------------------------- //
    // 13. Unsolicited notifications (Milan §5.4.2.21 / 1722.1 §7.5.2)    //
    // ---------------------------------------------------------------- //
    printf("\n[13] unsolicited notifications\n");
    {
        auto reg_pl = std::vector<uint8_t>{};      // REGISTER: empty payload
        auto u_bit  = [](const std::vector<uint8_t>& b) {
            return b.size() > 36 ? (b[36] >> 7) & 1 : -1;
        };
        auto be_at = [](const std::vector<uint8_t>& b, int off, int n) {
            uint64_t v = 0;
            for (int i = 0; i < n; i++) v = (v << 8) | b[off + i];
            return v;
        };
        // distinct controllers B..E
        const uint8_t MAC_B[6] = {0x68,0x05,0xCA,0x00,0x00,0xB0};
        const uint8_t MAC_C[6] = {0x68,0x05,0xCA,0x00,0x00,0xC0};
        const uint8_t MAC_D[6] = {0x68,0x05,0xCA,0x00,0x00,0xD0};
        const uint8_t MAC_E[6] = {0x68,0x05,0xCA,0x00,0x00,0xE0};
        const uint64_t CID_B = 0x680500FFFE0000B0ULL, CID_C = 0x680500FFFE0000C0ULL;
        const uint64_t CID_D = 0x680500FFFE0000D0ULL, CID_E = 0x680500FFFE0000E0ULL;

        // (a) register A; dedup register -> SUCCESS both times
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 36, 0x1301, reg_pl));
        auto r = collect_resp();
        ck("[13a] REGISTER SUCCESS", r_status(r), 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 36, 0x1302, reg_pl));
        r = collect_resp();
        ck("[13a] re-REGISTER dedup SUCCESS", r_status(r), 0);

        // (b) listener edge -> ONE push: u=1, to A's MAC/eid, seq 0,
        //     GET_STREAM_INFO body with live values
        dut->listener_observed_i = 1;
        r = collect_resp();
        ck("[13b] push arrived", r.size() > 0, 1);
        ck("[13b] push dst = A's MAC", memcmp(r.data(), CTL_MAC, 6) == 0, 1);
        ck("[13b] push u-bit set", u_bit(r), 1);
        ck("[13b] push controller = A", r_ctlr(r) == CTLR_ID, 1);
        ck("[13b] push seq 0", r_seq(r), 0);
        ck("[13b] push cmd GET_STREAM_INFO", r_cmd(r), 15);
        ck("[13b] push status SUCCESS", r_status(r), 0);
        ck("[13b] push stream_id {mac,0}", be_at(r, 54, 8), 0x020000FFFE010000ULL);
        ck("[13b] push desc STREAM_OUTPUT", be_at(r, 38, 2), 6);

        // (c) second edge -> second push, per-controller sequence advanced
        dut->listener_observed_i = 0;
        r = collect_resp();
        ck("[13c] second push seq 1", r_seq(r), 1);

        // (d) SET_STREAM_INFO by A skips A (the change-causing controller)
        {
            std::vector<uint8_t> pl; put_be16(pl, 0x0006); put_be16(pl, 0);
            uint32_t fl = 0x20000000u, lat = 1500000;
            for (int i = 3; i >= 0; i--) pl.push_back((fl >> (8*i)) & 0xFF);
            for (int i = 0; i < 16; i++) pl.push_back(0);
            for (int i = 3; i >= 0; i--) pl.push_back((lat >> (8*i)) & 0xFF);
            while (pl.size() < 56) pl.push_back(0);
            feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 14, 0x1303, pl));
        }
        r = collect_resp();
        ck("[13d] SET SUCCESS", r_status(r), 0);
        r = collect_resp(800);
        ck("[13d] no self-push after own SET", r.size(), 0);

        // (e) fill the table: B, C, D register; E -> NO_RESOURCES
        feed_rx(aecp_cmd(ENT_MAC, MAC_B, ENTITY_ID, CID_B, 0, 36, 0x1304, reg_pl));
        ck("[13e] REGISTER B", r_status(collect_resp()), 0);
        feed_rx(aecp_cmd(ENT_MAC, MAC_C, ENTITY_ID, CID_C, 0, 36, 0x1305, reg_pl));
        ck("[13e] REGISTER C", r_status(collect_resp()), 0);
        feed_rx(aecp_cmd(ENT_MAC, MAC_D, ENTITY_ID, CID_D, 0, 36, 0x1306, reg_pl));
        ck("[13e] REGISTER D", r_status(collect_resp()), 0);
        feed_rx(aecp_cmd(ENT_MAC, MAC_E, ENTITY_ID, CID_E, 0, 36, 0x1307, reg_pl));
        ck("[13e] REGISTER E -> NO_RESOURCES", r_status(collect_resp()), 8);

        // (f) edge -> four pushes (A..D), each unicast to its own MAC with
        //     its own sequence counter
        dut->listener_observed_i = 1;
        int got = 0; bool got_a=false, got_b=false, got_c=false, got_d=false;
        for (int i = 0; i < 4; i++) {
            r = collect_resp();
            if (r.empty()) break;
            got++;
            uint64_t cid = r_ctlr(r);
            if (cid == CTLR_ID) { got_a = true; ck("[13f] A seq 2", r_seq(r), 2); }
            if (cid == CID_B)   { got_b = true; ck("[13f] B seq 0", r_seq(r), 0); }
            if (cid == CID_C)   { got_c = true; }
            if (cid == CID_D)   { got_d = true; ck("[13f] D u-bit", u_bit(r), 1); }
        }
        ck("[13f] four pushes", got, 4);
        ck("[13f] all four controllers", got_a && got_b && got_c && got_d, 1);

        // (g) SET by A -> pushes to B, C, D only
        {
            std::vector<uint8_t> pl; put_be16(pl, 0x0006); put_be16(pl, 0);
            uint32_t fl = 0x20000000u, lat = 1600000;
            for (int i = 3; i >= 0; i--) pl.push_back((fl >> (8*i)) & 0xFF);
            for (int i = 0; i < 16; i++) pl.push_back(0);
            for (int i = 3; i >= 0; i--) pl.push_back((lat >> (8*i)) & 0xFF);
            while (pl.size() < 56) pl.push_back(0);
            dut->listener_observed_i = 0;   // allow the SET
            (void)collect_resp();           // drain the edge pushes (4)
            (void)collect_resp(); (void)collect_resp(); (void)collect_resp();
            feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 14, 0x1308, pl));
        }
        r = collect_resp();
        ck("[13g] SET SUCCESS", r_status(r), 0);
        got = 0; got_a = false;
        for (int i = 0; i < 3; i++) {
            r = collect_resp();
            if (r.empty()) break;
            got++;
            if (r_ctlr(r) == CTLR_ID) got_a = true;
        }
        ck("[13g] three pushes (A skipped)", got, 3);
        ck("[13g] none to A", got_a ? 1 : 0, 0);
        r = collect_resp(800);
        ck("[13g] no extra push", r.size(), 0);

        // (h) deregister A: idempotent SUCCESS; A gets no further pushes
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 37, 0x1309, reg_pl));
        ck("[13h] DEREGISTER SUCCESS", r_status(collect_resp()), 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 37, 0x130A, reg_pl));
        ck("[13h] re-DEREGISTER idempotent", r_status(collect_resp()), 0);
        dut->listener_observed_i = 1;
        got = 0; got_a = false;
        for (int i = 0; i < 3; i++) {
            r = collect_resp();
            if (r.empty()) break;
            got++;
            if (r_ctlr(r) == CTLR_ID) got_a = true;
        }
        ck("[13h] three pushes after dereg", got, 3);
        ck("[13h] none to deregistered A", got_a ? 1 : 0, 0);
        dut->listener_observed_i = 0;
        (void)collect_resp(); (void)collect_resp(); (void)collect_resp();
    }

    // ---------------------------------------------------------------- //
    // 14. Full-directory sweep (FR-ENUM-02): READ_DESCRIPTOR every entry //
    //     and compare byte-exact vs the generated golden image. ENTITY   //
    //     and AVB_INTERFACE carry live overlays — their static prefix    //
    //     checks live in [1]/[2]; here they only get the type/index gate.//
    // ---------------------------------------------------------------- //
    printf("\n[14] READ_DESCRIPTOR sweep over all %zu directory entries\n",
           sizeof(AEM_DIR)/sizeof(AEM_DIR[0]));
    {
        // restore the volatile mirror fields earlier SET_* tests touched so
        // the golden compare sees the power-on image
        std::vector<uint8_t> rs; put_be16(rs, 0x0002); put_be16(rs, 0);
        rs.insert(rs.end(), {0x00,0x00,0xBB,0x80});    // 48 kHz
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 20, 0x13FF, rs));
        (void)collect_resp();

        uint16_t seq = 0x1400;
        for (const auto& e : AEM_DIR) {
            std::vector<uint8_t> pl; put_be16(pl,0); put_be16(pl,0);
            put_be16(pl, e.type); put_be16(pl, e.index);
            feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 4, seq++, pl));
            auto r = collect_resp();
            char nm[64];
            snprintf(nm, sizeof nm, "[14] desc 0x%04X[%u] SUCCESS", e.type, e.index);
            ck(nm, r_status(r), 0);
            snprintf(nm, sizeof nm, "[14] desc 0x%04X[%u] CDL", e.type, e.index);
            ck(nm, r_cdl(r), 16 + e.len);
            bool overlaid = (e.type == 0x0000) || (e.type == 0x0009);
            if (!overlaid) {
                std::vector<uint8_t> exp(AEM_ROM + e.base, AEM_ROM + e.base + e.len);
                snprintf(nm, sizeof nm, "[14] desc 0x%04X[%u] byte-exact", e.type, e.index);
                ckbytes(nm, r, 42, exp);
            }
        }
    }

    // ---------------------------------------------------------------- //
    // 15. New-descriptor semantics spot checks                          //
    // ---------------------------------------------------------------- //
    printf("\n[15] new descriptor spot checks\n");
    {
        // (a) GET_NAME on STREAM_INPUT[1] reads "CRF"
        std::vector<uint8_t> pl; put_be16(pl, 0x0005); put_be16(pl, 1);
        put_be16(pl, 0); put_be16(pl, 0);              // name_index, cfg
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 17, 0x1501, pl));
        auto r = collect_resp();
        ck("[15a] GET_NAME(STREAM_INPUT,1) SUCCESS", r_status(r), 0);
        ckbytes("[15a] name = 'CRF'", r, 46, {'C','R','F',0});

        // (b) SET_NAME on STREAM_INPUT[0] + READ_DESCRIPTOR readback
        std::vector<uint8_t> sn; put_be16(sn, 0x0005); put_be16(sn, 0);
        put_be16(sn, 0); put_be16(sn, 0);
        const char* nn = "Renamed In0";
        for (int i = 0; i < 64; i++) sn.push_back(i < (int)strlen(nn) ? nn[i] : 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 16, 0x1502, sn));
        r = collect_resp();
        ck("[15b] SET_NAME(STREAM_INPUT,0) SUCCESS", r_status(r), 0);
        std::vector<uint8_t> rd; put_be16(rd,0); put_be16(rd,0);
        put_be16(rd, 0x0005); put_be16(rd, 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 4, 0x1503, rd));
        r = collect_resp();
        ckbytes("[15b] readback name", r, 46, {'R','e','n','a','m','e','d',' ','I','n','0'});

        // (c) GET_NAME bad name_index -> BAD_ARGUMENTS (descriptor exists)
        std::vector<uint8_t> bn; put_be16(bn, 0x0005); put_be16(bn, 1);
        put_be16(bn, 1); put_be16(bn, 0);              // name_index 1 invalid
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 17, 0x1504, bn));
        r = collect_resp();
        ck("[15c] bad name_index BAD_ARGUMENTS", r_status(r), 7);

        // (d) CLOCK_DOMAIN[0] static fields: clock_source_index=0, 3 sources
        std::vector<uint8_t> cd; put_be16(cd,0); put_be16(cd,0);
        put_be16(cd, 0x0024); put_be16(cd, 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 4, 0x1505, cd));
        r = collect_resp();
        // descriptor offset 70 = clock_source_index -> wire 42+70
        ckbytes("[15d] clock_source_index=0", r, 112, {0x00,0x00});
        ckbytes("[15d] sources_offset/count/list", r, 114,
                {0x00,0x4C, 0x00,0x03, 0x00,0x00, 0x00,0x01, 0x00,0x02});

        // (e) CONTROL[0] IDENTIFY: type EUI-64 + LINEAR_UINT8 + value format
        std::vector<uint8_t> ct; put_be16(ct,0); put_be16(ct,0);
        put_be16(ct, 0x001A); put_be16(ct, 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 4, 0x1506, ct));
        r = collect_resp();
        // control_value_type at desc offset 80, control_type at 82
        ckbytes("[15e] LINEAR_UINT8 + IDENTIFY type", r, 122,
                {0x00,0x01, 0x90,0xE0,0xF0,0x00,0x00,0x00,0x00,0x01});
        // value_format at desc offset 104: min/max/step/default/current
        ckbytes("[15e] value format 0/255/255/0/0", r, 146,
                {0x00,0xFF,0xFF,0x00,0x00});
    }

    // ---------------------------------------------------------------- //
    // 16. SET/GET_CLOCK_SOURCE (FR-CLK-03)                              //
    // ---------------------------------------------------------------- //
    printf("\n[16] SET/GET_CLOCK_SOURCE\n");
    {
        auto cs_pl = [](uint16_t t, uint16_t i) {
            std::vector<uint8_t> p; put_be16(p, t); put_be16(p, i); return p;
        };
        // (a) GET on CLOCK_DOMAIN[0]: power-on source 0
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 23, 0x1601,
                         cs_pl(0x0024, 0)));
        auto r = collect_resp();
        ck("[16a] GET SUCCESS", r_status(r), 0);
        ck("[16a] CDL 20", r_cdl(r), 20);
        ckbytes("[16a] echo type/index", r, 38, {0x00,0x24,0x00,0x00});
        ckbytes("[16a] source 0 + reserved", r, 42, {0x00,0x00,0x00,0x00});

        // (b) SET to source 1 (AAF stream clock) + GET readback + descriptor
        auto set_pl = cs_pl(0x0024, 0); put_be16(set_pl, 1); put_be16(set_pl, 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 22, 0x1602, set_pl));
        r = collect_resp();
        ck("[16b] SET SUCCESS", r_status(r), 0);
        ckbytes("[16b] response reads back 1", r, 42, {0x00,0x01});
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 23, 0x1603,
                         cs_pl(0x0024, 0)));
        r = collect_resp();
        ckbytes("[16b] GET readback 1", r, 42, {0x00,0x01});
        std::vector<uint8_t> rd; put_be16(rd,0); put_be16(rd,0);
        put_be16(rd, 0x0024); put_be16(rd, 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 4, 0x1604, rd));
        r = collect_resp();
        ckbytes("[16b] descriptor clock_source_index 1", r, 112, {0x00,0x01});

        // (c) SET out of range -> BAD_ARGUMENTS (value stays 1)
        auto bad_pl = cs_pl(0x0024, 0); put_be16(bad_pl, 3); put_be16(bad_pl, 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 22, 0x1605, bad_pl));
        r = collect_resp();
        ck("[16c] SET(3) BAD_ARGUMENTS", r_status(r), 7);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 23, 0x1606,
                         cs_pl(0x0024, 0)));
        r = collect_resp();
        ckbytes("[16c] value unchanged", r, 42, {0x00,0x01});

        // (d) wrong descriptor -> NO_SUCH_DESCRIPTOR; restore source 0
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 23, 0x1607,
                         cs_pl(0x0002, 0)));
        r = collect_resp();
        ck("[16d] GET(AUDIO_UNIT) NO_SUCH_DESCRIPTOR", r_status(r), 2);
        auto rs_pl = cs_pl(0x0024, 0); put_be16(rs_pl, 0); put_be16(rs_pl, 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 22, 0x1608, rs_pl));
        (void)collect_resp();
    }

    // ---------------------------------------------------------------- //
    // 17. SET/GET_CONTROL — IDENTIFY (FR-MGT-01)                        //
    // ---------------------------------------------------------------- //
    printf("\n[17] SET/GET_CONTROL identify\n");
    {
        auto ctl_pl = [](uint16_t t, uint16_t i) {
            std::vector<uint8_t> p; put_be16(p, t); put_be16(p, i); return p;
        };
        // (a) GET: power-on value 0, identify_o low
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 25, 0x1701,
                         ctl_pl(0x001A, 0)));
        auto r = collect_resp();
        ck("[17a] GET SUCCESS", r_status(r), 0);
        ck("[17a] CDL 17", r_cdl(r), 17);
        ckbytes("[17a] value 0", r, 42, {0x00});
        ck("[17a] identify_o low", dut->identify_o, 0);

        // (b) SET 255 -> identify on; readback via GET
        auto on_pl = ctl_pl(0x001A, 0); on_pl.push_back(0xFF);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 24, 0x1702, on_pl));
        r = collect_resp();
        ck("[17b] SET(255) SUCCESS", r_status(r), 0);
        ckbytes("[17b] response value 255", r, 42, {0xFF});
        ck("[17b] identify_o high", dut->identify_o, 1);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 25, 0x1703,
                         ctl_pl(0x001A, 0)));
        r = collect_resp();
        ckbytes("[17b] GET readback 255", r, 42, {0xFF});

        // (c) SET 7 violates step 255 -> BAD_ARGUMENTS, state unchanged
        auto odd_pl = ctl_pl(0x001A, 0); odd_pl.push_back(0x07);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 24, 0x1704, odd_pl));
        r = collect_resp();
        ck("[17c] SET(7) BAD_ARGUMENTS", r_status(r), 7);
        ck("[17c] identify_o still high", dut->identify_o, 1);

        // (d) SET 0 -> identify off; bad index -> NO_SUCH_DESCRIPTOR
        auto off_pl = ctl_pl(0x001A, 0); off_pl.push_back(0x00);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 24, 0x1705, off_pl));
        r = collect_resp();
        ck("[17d] SET(0) SUCCESS", r_status(r), 0);
        ck("[17d] identify_o low", dut->identify_o, 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 25, 0x1706,
                         ctl_pl(0x001A, 1)));
        r = collect_resp();
        ck("[17d] GET(idx 1) NO_SUCH_DESCRIPTOR", r_status(r), 2);
    }

    // ---------------------------------------------------------------- //
    // 18. GET_AUDIO_MAP + ADD/REMOVE (static maps)                      //
    // ---------------------------------------------------------------- //
    printf("\n[18] GET_AUDIO_MAP\n");
    {
        auto map_pl = [](uint16_t t, uint16_t i, uint16_t m) {
            std::vector<uint8_t> p; put_be16(p, t); put_be16(p, i);
            put_be16(p, m); put_be16(p, 0); return p;
        };
        // (a) STREAM_PORT_INPUT[0] map 0: 8 identity mappings
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 43, 0x1801,
                         map_pl(0x000E, 0, 0)));
        auto r = collect_resp();
        ck("[18a] GET SUCCESS", r_status(r), 0);
        ck("[18a] CDL 88", r_cdl(r), 88);
        ckbytes("[18a] echo type/index/map", r, 38, {0x00,0x0E,0x00,0x00,0x00,0x00});
        ckbytes("[18a] n_maps=1 n_mappings=8", r, 44, {0x00,0x01,0x00,0x08,0x00,0x00});
        ckbytes("[18a] mapping[0]", r, 50, {0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00});
        ckbytes("[18a] mapping[5]", r, 90, {0x00,0x00,0x00,0x05,0x00,0x05,0x00,0x00});

        // (b) STREAM_PORT_OUTPUT[0] serves AUDIO_MAP[1]
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 43, 0x1802,
                         map_pl(0x000F, 0, 0)));
        r = collect_resp();
        ck("[18b] output port SUCCESS", r_status(r), 0);
        ckbytes("[18b] mapping[7]", r, 106, {0x00,0x00,0x00,0x07,0x00,0x07,0x00,0x00});

        // (c) map_index 1 doesn't exist; wrong descriptor type
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 43, 0x1803,
                         map_pl(0x000E, 0, 1)));
        r = collect_resp();
        ck("[18c] map 1 NO_SUCH_DESCRIPTOR", r_status(r), 2);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 43, 0x1804,
                         map_pl(0x0006, 0, 0)));
        r = collect_resp();
        ck("[18c] STREAM_OUTPUT NO_SUCH_DESCRIPTOR", r_status(r), 2);

        // (d) ADD/REMOVE_AUDIO_MAPPINGS -> NOT_SUPPORTED (static maps)
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 44, 0x1805,
                         map_pl(0x000E, 0, 0)));
        r = collect_resp();
        ck("[18d] ADD NOT_SUPPORTED", r_status(r), 11);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 45, 0x1806,
                         map_pl(0x000E, 0, 0)));
        r = collect_resp();
        ck("[18d] REMOVE NOT_SUPPORTED", r_status(r), 11);
    }

    // ---------------------------------------------------------------- //
    // 19. lock gating of the new SETs (SET_CLOCK_SOURCE not exempt)     //
    // ---------------------------------------------------------------- //
    printf("\n[19] lock vs new SETs\n");
    {
        std::vector<uint8_t> lk = {0,0,0,0};   // flags=0 -> LOCK
        put_be64(lk, 0);                        // locked_id field
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 1, 0x1901, lk));
        ck("[19] LOCK by ctlr1", r_status(collect_resp()), 0);

        std::vector<uint8_t> sp; put_be16(sp, 0x0024); put_be16(sp, 0);
        put_be16(sp, 2); put_be16(sp, 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL2_MAC, ENTITY_ID, CTLR2_ID, 0, 22, 0x1902, sp));
        ck("[19] SET_CLOCK_SOURCE by ctlr2 ENTITY_LOCKED",
           r_status(collect_resp()), 3);
        std::vector<uint8_t> cp; put_be16(cp, 0x001A); put_be16(cp, 0);
        cp.push_back(0xFF);
        feed_rx(aecp_cmd(ENT_MAC, CTL2_MAC, ENTITY_ID, CTLR2_ID, 0, 24, 0x1903, cp));
        ck("[19] SET_CONTROL by ctlr2 ENTITY_LOCKED", r_status(collect_resp()), 3);
        ck("[19] identify_o unaffected", dut->identify_o, 0);

        std::vector<uint8_t> ul = {0,0,0,1};   // flags UNLOCK
        put_be64(ul, 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 1, 0x1904, ul));
        ck("[19] UNLOCK", r_status(collect_resp()), 0);
    }

    // ---------------------------------------------------------------- //
    // 20. Milan MVU: SET/GET_SYSTEM_UNIQUE_ID + MEDIA_CLOCK_REF_INFO    //
    //     (FR-MVU-02; la_avdecc Milan-1.2 payload sizes 6/2/6 + 74/2/74)//
    // ---------------------------------------------------------------- //
    printf("\n[20] MVU system-unique-id / media-clock-reference-info\n");
    {
        const uint8_t PROTO[6] = {0x00,0x1B,0xC5,0x0A,0xC1,0x00};
        auto vu = [&](uint16_t cmd, const std::vector<uint8_t>& body) {
            std::vector<uint8_t> p(PROTO, PROTO+6);
            put_be16(p, cmd);
            for (auto b : body) p.push_back(b);
            return p;
        };
        // (a) GET_SYSTEM_UNIQUE_ID: power-on 0
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 6, 0, 0x2001,
                         vu(0x0002, {0,0})));
        auto r = collect_resp();
        ck("[20a] GET_SYS_UID SUCCESS", r_status(r), 0);
        ck("[20a] msg_type VU_RESPONSE", r_msgt(r), 7);
        ck("[20a] CDL 24", r_cdl(r), 24);
        ckbytes("[20a] protocol_id echoed", r, 36,
                {0x00,0x1B,0xC5,0x0A,0xC1,0x00,0x00,0x02});
        ckbytes("[20a] uid 0", r, 46, {0x00,0x00,0x00,0x00});

        // (b) SET_SYSTEM_UNIQUE_ID 0xCAFE0042 + readback
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 6, 0, 0x2002,
                         vu(0x0001, {0,0, 0xCA,0xFE,0x00,0x42})));
        r = collect_resp();
        ck("[20b] SET_SYS_UID SUCCESS", r_status(r), 0);
        ck("[20b] CDL 24", r_cdl(r), 24);
        ckbytes("[20b] response mirrors id", r, 46, {0xCA,0xFE,0x00,0x42});
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 6, 0, 0x2003,
                         vu(0x0002, {0,0})));
        r = collect_resp();
        ckbytes("[20b] GET readback", r, 46, {0xCA,0xFE,0x00,0x42});

        // (c) GET_MEDIA_CLOCK_REFERENCE_INFO: defaults (prio 192, empty name)
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 6, 0, 0x2004,
                         vu(0x0004, {0,0})));
        r = collect_resp();
        ck("[20c] GET_MCR SUCCESS", r_status(r), 0);
        ck("[20c] CDL 92", r_cdl(r), 92);
        // payload: cdi(2)@44 flags(1)@46 rsvd@47 def@48 user@49 rsvd32@50 name@54
        ckbytes("[20c] flags both valid", r, 46, {0x03,0x00});
        ckbytes("[20c] default/user prio 192/192", r, 48, {192,192});
        ckbytes("[20c] name empty", r, 54, {0,0,0,0});

        // (d) SET user prio only (flags bit0), name untouched
        std::vector<uint8_t> mcr = {0,0, 0x01, 0, 0, 100, 0,0,0,0};
        for (int i = 0; i < 64; i++) mcr.push_back('X');   // ignored (bit1 clear)
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 6, 0, 0x2005,
                         vu(0x0003, mcr)));
        r = collect_resp();
        ck("[20d] SET_MCR(prio) SUCCESS", r_status(r), 0);
        ckbytes("[20d] flags echoed", r, 46, {0x01});
        ckbytes("[20d] user prio 100", r, 49, {100});
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 6, 0, 0x2006,
                         vu(0x0004, {0,0})));
        r = collect_resp();
        ckbytes("[20d] GET user prio 100, name still empty", r, 49, {100});
        ckbytes("[20d] name not clobbered", r, 54, {0,0,0,0});

        // (e) SET domain name only (flags bit1), prio untouched
        std::vector<uint8_t> mcr2 = {0,0, 0x02, 0, 0, 7, 0,0,0,0};
        const char* dn = "Studio A";
        for (int i = 0; i < 64; i++) mcr2.push_back(i < (int)strlen(dn) ? dn[i] : 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 6, 0, 0x2007,
                         vu(0x0003, mcr2)));
        r = collect_resp();
        ck("[20e] SET_MCR(name) SUCCESS", r_status(r), 0);
        ckbytes("[20e] name in response", r, 54, {'S','t','u','d','i','o',' ','A',0});
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 6, 0, 0x2008,
                         vu(0x0004, {0,0})));
        r = collect_resp();
        ckbytes("[20e] GET name persisted", r, 54, {'S','t','u','d','i','o',' ','A',0});
        ckbytes("[20e] prio still 100", r, 49, {100});

        // (f) bad clock_domain_index -> BAD_ARGUMENTS; unknown MVU cmd ->
        //     NOT_IMPLEMENTED echo (1.3 BIND_STREAM code)
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 6, 0, 0x2009,
                         vu(0x0004, {0,1})));
        r = collect_resp();
        ck("[20f] MCR cdi=1 BAD_ARGUMENTS", r_status(r), 7);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 6, 0, 0x200A,
                         vu(0x0005, {0,0})));
        r = collect_resp();
        ck("[20f] unknown MVU NOT_IMPLEMENTED", r_status(r), 1);
    }

    // ---------------------------------------------------------------- //
    // 21. real GET_COUNTERS values + SET/GET_MAX_TRANSIT_TIME           //
    //     (controllers B/C/D are still unsol-registered: drain pushes)  //
    // ---------------------------------------------------------------- //
    printf("\n[21] live counters + max transit time\n");
    {
        auto gc_pl = [](uint16_t t, uint16_t i) {
            std::vector<uint8_t> p; put_be16(p, t); put_be16(p, i); return p;
        };
        auto be32_at = [](const std::vector<uint8_t>& b, int off) {
            uint32_t v = 0;
            for (int i = 0; i < 4; i++) v = (v << 8) | b[off + i];
            return (long)v;
        };
        // (a) AVB_INTERFACE: link came up once at reset; GM id provisioning
        //     counted one change
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 41, 0x2101,
                         gc_pl(0x0009, 0)));
        auto r = collect_resp();
        ck("[21a] GET_COUNTERS(AVB_IF) SUCCESS", r_status(r), 0);
        ck("[21a] CDL 148", r_cdl(r), 148);
        ckbytes("[21a] valid 0x23", r, 42, {0,0,0,0x23});
        ck("[21a] LINK_UP 1", be32_at(r, 46), 1);
        ck("[21a] LINK_DOWN 0", be32_at(r, 50), 0);
        ck("[21a] GM_CHANGED 1", be32_at(r, 66), 1);

        // (b) link bounce + GM change reflect in the counters
        dut->link_up_i = 0; for (int i = 0; i < 4; i++) tick();
        dut->link_up_i = 1; for (int i = 0; i < 4; i++) tick();
        dut->gptp_gm_id_i = 0x3CC0C6FFFE0002CBULL; for (int i = 0; i < 4; i++) tick();
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 41, 0x2102,
                         gc_pl(0x0009, 0)));
        r = collect_resp();
        ck("[21b] LINK_UP 2", be32_at(r, 46), 2);
        ck("[21b] LINK_DOWN 1", be32_at(r, 50), 1);
        ck("[21b] GM_CHANGED 2", be32_at(r, 66), 2);

        // (c) STREAM_OUTPUT: talker activation cycle + live FRAMES_TX
        dut->frames_tx_i = 0x00012345;
        dut->talker_active_i = 1;
        (void)collect_resp(); (void)collect_resp(); (void)collect_resp(); // B/C/D pushes
        dut->talker_active_i = 0;
        (void)collect_resp(); (void)collect_resp(); (void)collect_resp();
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 41, 0x2103,
                         gc_pl(0x0006, 0)));
        r = collect_resp();
        ck("[21c] GET_COUNTERS(STREAM_OUT) SUCCESS", r_status(r), 0);
        ckbytes("[21c] valid 0x1F", r, 42, {0,0,0,0x1F});
        // test 12 already cycled talker_active once -> this is the 2nd cycle
        ck("[21c] STREAM_START 2", be32_at(r, 46), 2);
        ck("[21c] STREAM_STOP 2", be32_at(r, 50), 2);
        ck("[21c] FRAMES_TX live", be32_at(r, 62), 0x00012345);

        // (d) GET_MAX_TRANSIT_TIME reflects the SET_STREAM_INFO latency
        //     (test 13g left pres_offset at 1600000 ns)
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 0x4D, 0x2104,
                         gc_pl(0x0006, 0)));
        r = collect_resp();
        ck("[21d] GET_MTT SUCCESS", r_status(r), 0);
        ck("[21d] CDL 24", r_cdl(r), 24);
        ck("[21d] mtt hi 0", be32_at(r, 42), 0);
        ck("[21d] mtt = 1600000", be32_at(r, 46), 1600000);

        // (e) SET_MAX_TRANSIT_TIME 2 ms -> pres offset updated (+3 pushes)
        auto mtt_pl = gc_pl(0x0006, 0);
        for (int i = 7; i >= 0; i--) mtt_pl.push_back((2000000ULL >> (8*i)) & 0xFF);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 0x4C, 0x2105, mtt_pl));
        r = collect_resp();
        ck("[21e] SET_MTT SUCCESS", r_status(r), 0);
        ck("[21e] response mirrors 2000000", be32_at(r, 46), 2000000);
        (void)collect_resp(); (void)collect_resp(); (void)collect_resp();
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 0x4D, 0x2106,
                         gc_pl(0x0006, 0)));
        r = collect_resp();
        ck("[21e] GET readback 2000000", be32_at(r, 46), 2000000);

        // (f) SET > 0x7FFFFFFF ns -> BAD_ARGUMENTS; wrong desc; GET_DYNAMIC_INFO
        //     stays NOT_IMPLEMENTED (deferred SHOULD)
        auto big_pl = gc_pl(0x0006, 0);
        for (int i = 7; i >= 0; i--) big_pl.push_back((0x0000000100000000ULL >> (8*i)) & 0xFF);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 0x4C, 0x2107, big_pl));
        r = collect_resp();
        ck("[21f] SET_MTT(2^32) BAD_ARGUMENTS", r_status(r), 7);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 0x4D, 0x2108,
                         gc_pl(0x0005, 0)));
        r = collect_resp();
        ck("[21f] GET_MTT(STREAM_INPUT) NO_SUCH_DESCRIPTOR", r_status(r), 2);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 0x4B, 0x2109,
                         gc_pl(0x0000, 0)));
        r = collect_resp();
        ck("[21f] GET_DYNAMIC_INFO NOT_IMPLEMENTED", r_status(r), 1);
    }

    // ---------------------------------------------------------------- //
    // 22. STREAM_INPUT sinks: stream info / format / start-stop         //
    // ---------------------------------------------------------------- //
    printf("\n[22] STREAM_INPUT listener sink commands\n");
    {
        auto si_pl = [](uint16_t t, uint16_t i) {
            std::vector<uint8_t> p; put_be16(p, t); put_be16(p, i); return p;
        };
        auto be32_at = [](const std::vector<uint8_t>& b, int off) {
            uint32_t v = 0;
            for (int i = 0; i < 4; i++) v = (v << 8) | b[off + i];
            return (long)v;
        };
        // (a) unbound sink 0: identity flags only, zero fields
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 15, 0x2201,
                         si_pl(0x0005, 0)));
        auto r = collect_resp();
        ck("[22a] GET_STREAM_INFO(in0) SUCCESS", r_status(r), 0);
        ck("[22a] CDL 68", r_cdl(r), 68);
        ck("[22a] flags 0xF2000000", be32_at(r, 42), 0xF2000000);
        ck("[22a] stream_id 0", (long)(r[54]|r[55]|r[56]|r[57]), 0);

        // (b) bound + registered sink: CONNECTED flags + live fields + trailer
        dut->lstn_bound_i = 1;
        dut->lstn_sid_i   = 0x0200000000010000ULL;
        dut->lstn_dmac_i  = 0x91E0F000FE01ULL;
        dut->lstn_vlan_i  = 2;
        dut->lstn_pbsta_i = 3;                 // COMPLETED
        dut->lstn_acmpsta_i = 0;
        dut->lstn_ta_reg_i = 1;
        for (int i = 0; i < 4; i++) tick();
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 15, 0x2202,
                         si_pl(0x0005, 0)));
        r = collect_resp();
        // F2000000 | CONNECTED(0x04000000) | FAST_CONNECT|SAVED_STATE(0x6)
        ck("[22b] flags connected", be32_at(r, 42), 0xF6000006);
        ckbytes("[22b] stream_id live", r, 54,
                {0x02,0x00,0x00,0x00,0x00,0x01,0x00,0x00});
        ckbytes("[22b] dmac live", r, 66, {0x91,0xE0,0xF0,0x00,0xFE,0x01});
        ckbytes("[22b] vlan 2", r, 82, {0x00,0x02});
        ckbytes("[22b] flags_ex REGISTERING", r, 86, {0,0,0,1});
        ckbytes("[22b] pbsta/acmpsta trailer", r, 90, {0x60,0,0,0});

        // (c) TalkerFailed adds the failure flags
        dut->lstn_ta_fail_i = 1;
        for (int i = 0; i < 4; i++) tick();
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 15, 0x2203,
                         si_pl(0x0005, 0)));
        r = collect_resp();
        ck("[22c] +MSRP_FAILURE|SRP_REG_FAILED", be32_at(r, 42), 0xFE000046);
        dut->lstn_ta_fail_i = 0;

        // (d) sink 1 (CRF): unbound shape; CRF format from store
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 15, 0x2204,
                         si_pl(0x0005, 1)));
        r = collect_resp();
        ck("[22d] GET_STREAM_INFO(in1) SUCCESS", r_status(r), 0);
        ck("[22d] flags identity-only", be32_at(r, 42), 0xF2000000);
        ckbytes("[22d] CRF format", r, 46,
                {0x04,0x10,0x60,0x01,0x00,0x00,0xBB,0x80});

        // (e) SET_STREAM_FORMAT: sink1 accepts CRF 96k, rejects AAF; sink0
        //     accepts AAF 96k
        std::vector<uint8_t> f1 = si_pl(0x0005, 1);
        for (int i = 7; i >= 0; i--) f1.push_back((0x0410600100017700ULL >> (8*i)) & 0xFF);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 8, 0x2205, f1));
        r = collect_resp();
        ck("[22e] SET_FMT(in1, CRF96k) SUCCESS", r_status(r), 0);
        ckbytes("[22e] readback", r, 42, {0x04,0x10,0x60,0x01,0x00,0x01,0x77,0x00});
        std::vector<uint8_t> f2 = si_pl(0x0005, 1);
        for (int i = 7; i >= 0; i--) f2.push_back((0x0205022002006000ULL >> (8*i)) & 0xFF);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 8, 0x2206, f2));
        r = collect_resp();
        ck("[22e] SET_FMT(in1, AAF) BAD_ARGUMENTS", r_status(r), 7);
        std::vector<uint8_t> f3 = si_pl(0x0005, 0);
        for (int i = 7; i >= 0; i--) f3.push_back((0x020702200200C000ULL >> (8*i)) & 0xFF);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 8, 0x2207, f3));
        r = collect_resp();
        ck("[22e] SET_FMT(in0, AAF96k) SUCCESS", r_status(r), 0);

        // (f) STOP/START_STREAMING on sink0 drives STREAMING_WAIT; outputs
        //     stay NOT_SUPPORTED
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 35, 0x2208,
                         si_pl(0x0005, 0)));
        r = collect_resp();
        ck("[22f] STOP(in0) SUCCESS", r_status(r), 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 15, 0x2209,
                         si_pl(0x0005, 0)));
        r = collect_resp();
        ck("[22f] STREAMING_WAIT set", be32_at(r, 42), 0xF600000E);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 34, 0x220A,
                         si_pl(0x0005, 0)));
        r = collect_resp();
        ck("[22f] START(in0) SUCCESS", r_status(r), 0);
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 34, 0x220B,
                         si_pl(0x0006, 0)));
        r = collect_resp();
        ck("[22f] START(output) NOT_SUPPORTED", r_status(r), 11);

        // (g) GET_COUNTERS on a sink: SUCCESS, empty valid mask
        feed_rx(aecp_cmd(ENT_MAC, CTL_MAC, ENTITY_ID, CTLR_ID, 0, 41, 0x220C,
                         si_pl(0x0005, 0)));
        r = collect_resp();
        ck("[22g] GET_COUNTERS(in0) SUCCESS", r_status(r), 0);
        ck("[22g] CDL 148", r_cdl(r), 148);
        ck("[22g] valid mask 0", be32_at(r, 42), 0);
        dut->lstn_bound_i = 0; dut->lstn_ta_reg_i = 0;
    }

    // counters
    printf("\n[counters] cmd=%u resp=%u\n", dut->cmd_count_o, dut->resp_count_o);
    ck("cmd_count >= 14", dut->cmd_count_o >= 14, 1);

    printf("\n======================================================================\n");
    printf("AECP subsystem: %ld checks, %ld failures\n", checks, fails);
    delete dut;
    return fails ? 1 : 0;
}
