#!/usr/bin/env python3
"""Export one tracked configuration from a checked-out tree, then hash every artifact.

Usage: export_ax.py TREE CONFIG_NAME OUT_DIR VEX_DATA_DIR MANIFEST_JSON MODE
MODE "fixed": time.time() returns 1700000000 and migen Instance.__repr__ prints
the instance duid, applied identically to both trees BEFORE generation (these only
feed banner timestamps and the diagnostic hierarchy comment). MODE "live": no
fixing at all. No generated byte is rewritten afterwards. The tree's own
milan_soc.py is executed as __main__ with the configuration's emitted argv plus
--no-compile-software (no --build, so no vendor tool runs).
Artifact population: the export directory, the builder's per-config output and
the generated shape directory; *.log files are listed separately (diagnostic).
"""
import hashlib, json, runpy, shutil, sys, time
from pathlib import Path

tree, name, out, vex, manifest, mode = sys.argv[1:]
tree, out = Path(tree).resolve(), Path(out).resolve()
sys.path.insert(0, str(tree / "sw/builder"))
sys.path.insert(0, str(tree / "sw/litex"))
import pythondata_cpu_vexiiriscv
pythondata_cpu_vexiiriscv.data_location = vex
import endstation_builder as eb
bout = tree / "sw/builder/out"
gen = tree / "configs/generated" / f"endstation_{name}"
for d in (out, bout / f"endstation_{name}"):  # gen is reset by the driver (tracked file)
    if d.exists():
        shutil.rmtree(d)
result = eb.build(str(tree / "configs" / f"endstation_{name}.yaml"), str(bout))
argv = list(result["argv"]) + ["--entity-gen-dir", str(gen), "--output-dir", str(out),
                               "--no-compile-software"]
if mode == "fixed":
    time.time = lambda: 1700000000
    from migen.fhdl.specials import Instance
    Instance.__repr__ = lambda self: "Instance(%020d)" % self.duid
sys.argv = [str(tree / "sw/litex/milan_soc.py"), *argv]
runpy.run_path(str(tree / "sw/litex/milan_soc.py"), run_name="__main__")
files, logs = {}, {}
for prefix, d in (("export", out), ("builder", bout / f"endstation_{name}"), ("shape", gen)):
    for p in sorted(d.rglob("*")):
        if p.is_file():
            data = p.read_bytes()
            rec = {"bytes": len(data), "sha256": hashlib.sha256(data).hexdigest()}
            (logs if p.suffix == ".log" else files)[f"{prefix}/{p.relative_to(d)}"] = rec
assert any(k.endswith(".v") for k in files), "no gateware exported"
Path(manifest).write_text(json.dumps({"config": name, "mode": mode, "argv": argv,
                                      "files": files, "logs": logs}, indent=1) + "\n")
print("EXPORTED", name, mode, len(files), "artifacts,", len(logs), "logs")
