#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Kebag Logic
# SPDX-License-Identifier: CERN-OHL-W-2.0
#
# Every area figure of the design page, one ooc_measure.sh row each, written
# to results_ooc.txt beside this file. Run from anywhere inside the evidence
# checkout; the processor sources are the pinned submodule's.
#
#   run_ooc.sh            # all rows (a few minutes, one yosys at a time)
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/../../../.." && pwd)"
pe="$here/.."
pp="$root/protocol-processor/hdl"
m="$here/ooc_measure.sh"
out="$here/results_ooc.txt"
S11="N_STREAM_IN_P=2 N_STREAM_OUT_P=2 N_SPORT_IN_P=1 N_SPORT_OUT_P=1 N_AUDIO_UNIT_P=1 N_CLK_DOM_P=1"
S88="N_STREAM_IN_P=9 N_STREAM_OUT_P=9 N_SPORT_IN_P=8 N_SPORT_OUT_P=8 N_AUDIO_UNIT_P=1 N_CLK_DOM_P=1"
W11="$S11 N_NAME_P=38 MAPI_CLS_P=8'd8 MAPO_CLS_P=8'd17 MAP_ENT_MAX_P=17"
W88="$S88 N_NAME_P=99 MAPI_CLS_P=64'd0 MAPO_CLS_P=64'd651061555542690057 MAP_ENT_MAX_P=9"
# the pinned listener's sources; its $readmemh reads ltn_rom.hex in the tool's
# working directory ($OOC_OUT), generated by the pinned generator
lsn="$pp/common/pp_pkg.sv $pp/acmp/pp_acmp_pkg.sv $pp/acmp/KL_pp_acmp_listener.sv"
ooc_out="${OOC_OUT:-/data/milan/tmp/500/ooc}"
mkdir -p "$ooc_out"
python3 -B "$pp/acmp/rom/gen_ltn_rom.py" -o "$ooc_out/ltn_rom.hex" > /dev/null
rows=(
  # label | top | params | nodsp | sources
  "cal-backend-1x1-n30|KL_nvm_backend|$S11 N_NAME_P=30|0|$root/hdl/milan/KL_nvm_backend.sv"
  "cal-backend-1x1-n38|KL_nvm_backend|$S11 N_NAME_P=38|0|$root/hdl/milan/KL_nvm_backend.sv"
  "cal-backend-8x8-n99|KL_nvm_backend|$S88 N_NAME_P=99|0|$root/hdl/milan/KL_nvm_backend.sv"
  "cal-port|KL_pp_nvm_port||0|$pp/packet_engine/KL_pp_nvm_port.sv"
  "cal-bindmgr-1x1|KL_acmp_nvm_shadow|N_SINKS_P=2|0|$pp/acmp/pp_acmp_pkg.sv $pp/acmp/KL_acmp_nvm_shadow.sv"
  "cal-bindmgr-8x8|KL_acmp_nvm_shadow|N_SINKS_P=9|0|$pp/acmp/pp_acmp_pkg.sv $pp/acmp/KL_acmp_nvm_shadow.sv"
  "b-writer-1x1|KL_aecp_nvm_writer|$W11|0|$pe/prototype/KL_aecp_nvm_writer.proto.sv"
  "b-writer-1x1-nodsp|KL_aecp_nvm_writer|$W11|1|$pe/prototype/KL_aecp_nvm_writer.proto.sv"
  "b-writer-8x8|KL_aecp_nvm_writer|$W88|0|$pe/prototype/KL_aecp_nvm_writer.proto.sv"
  "b-writer-8x8-nodsp|KL_aecp_nvm_writer|$W88|1|$pe/prototype/KL_aecp_nvm_writer.proto.sv"
  "b-arbiter|KL_pp_nvm_mgr_arb||0|$pe/prototype/KL_pp_nvm_mgr_arb.proto.sv"
  # revision c's seams: the guard (S2, new), and the AMENDED port (S1) and
  # binding manager (S1, S3), each beside its pinned row above (cal-port,
  # cal-bindmgr-*) so the increment is the difference of the two
  "s2-desc-guard|KL_aecp_desc_mem_guard||0|$pe/prototype/KL_aecp_desc_mem_guard.proto.sv"
  "s1-port-amended|KL_pp_nvm_port_amd||0|$pe/prototype/KL_pp_nvm_port.amended.proto.sv"
  "s3-bindmgr-amended-1x1|KL_acmp_nvm_shadow_amd|N_SINKS_P=2|0|$pp/acmp/pp_acmp_pkg.sv $pe/prototype/KL_acmp_nvm_shadow.amended.proto.sv"
  "s3-bindmgr-amended-8x8|KL_acmp_nvm_shadow_amd|N_SINKS_P=9|0|$pp/acmp/pp_acmp_pkg.sv $pe/prototype/KL_acmp_nvm_shadow.amended.proto.sv"
  # revision d's seam S4: the admission gate alone (NEW), the pinned listener
  # alone (EXISTING hardware, for scale) and the listener with the gate in
  # front (the gate IN PLACE: its increment is the difference of the two)
  "s4-lsn-admit-1x1|KL_pp_acmp_lsn_admit|N_SINKS_P=2|0|$pe/prototype/KL_pp_acmp_lsn_admit.proto.sv"
  "s4-lsn-admit-8x8|KL_pp_acmp_lsn_admit|N_SINKS_P=9|0|$pe/prototype/KL_pp_acmp_lsn_admit.proto.sv"
  "cal-listener-1x1|KL_pp_acmp_listener|N_SINKS_P=2|0|$lsn"
  "cal-listener-8x8|KL_pp_acmp_listener|N_SINKS_P=9|0|$lsn"
  "s4-listener-admitted-1x1|d3s4_listener_admit|N_SINKS_P=2|0|$lsn $pe/prototype/KL_pp_acmp_lsn_admit.proto.sv $here/d3s4_listener_admit.sv"
  "s4-listener-admitted-8x8|d3s4_listener_admit|N_SINKS_P=9|0|$lsn $pe/prototype/KL_pp_acmp_lsn_admit.proto.sv $here/d3s4_listener_admit.sv"
  "a-manager-unit|KL_acmp_nvm_shadow|N_SINKS_P=1|0|$pp/acmp/pp_acmp_pkg.sv $pp/acmp/KL_acmp_nvm_shadow.sv"
  "a-shadows-1x1|d3a_shadow_proxy|N_STREAM_IN_P=2 N_STREAM_OUT_P=2 N_MAP_ENT_P=25 N_NAME_P=38|0|$here/d3a_shadow_proxy.sv"
  "a-shadows-8x8|d3a_shadow_proxy|N_STREAM_IN_P=9 N_STREAM_OUT_P=9 N_MAP_ENT_P=72 N_NAME_P=99|0|$here/d3a_shadow_proxy.sv"
  "c-fabric-1x1|d3c_fabric_proxy|N_STREAM_IN_P=2 N_STREAM_OUT_P=2 N_SPORT_IN_P=1 N_SPORT_OUT_P=1 N_NAME_P=38|0|$here/d3c_fabric_proxy.sv"
  "c-fabric-8x8|d3c_fabric_proxy|N_STREAM_IN_P=9 N_STREAM_OUT_P=9 N_SPORT_IN_P=8 N_SPORT_OUT_P=8 N_NAME_P=99|0|$here/d3c_fabric_proxy.sv"
)
{
  printf "%-34s %-26s %6s %6s %7s %6s %6s %6s %4s %6s\n" label top LUT LUTRAM LUT_TOT FF RAMB36 RAMB18 DSP CARRY4
  for r in "${rows[@]}"; do
    IFS='|' read -r label top params nodsp srcs <<< "$r"
    # shellcheck disable=SC2086
    "$m" "$label" "$top" "$params" "$nodsp" $srcs
  done
} | tee "$out"
