"""Generate one AX7101 export at the composed tree with a chosen milan_soc.py.

  MEASURE_DIR=<dir> VEX_DATA_DIR=<isolated copy> PYTHONHASHSEED=0 python -P -s compose_export.py <phase> <config>

Not -I: it implies -E, which drops PYTHONHASHSEED, and the CPU wrapper spells
its ISA string from a set, so an unpinned seed differs between any two runs.

Run from the root of a disposable checkout of the candidate. <phase> is
`baseline` (milan_soc.py taken from the dev parent blob, i.e. the candidate tree
without this PR's recipe change) or `candidate` (the candidate's own file).
Both phases see the same tree, LiteX install and patch series, and the same
fixed inputs: wall-clock time and the diagnostic Instance repr, which would
otherwise vary between any two runs. No generated byte is normalized.
`candidate` requires every artifact to equal the baseline snapshot.
"""
import hashlib
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

DEV = "99e4eb6c14462aafa84bb1ac597fd241abc1a240"
root = Path.cwd().resolve()
scratch = Path(os.environ["MEASURE_DIR"]).resolve()
phase, name = sys.argv[1:]
assert phase in ("baseline", "candidate"), phase
sys.path.insert(0, str(root / "sw/builder"))
sys.path.insert(0, str(root / "sw/litex"))
import endstation_builder as eb  # noqa: E402
import pythondata_cpu_vexiiriscv  # noqa: E402
pythondata_cpu_vexiiriscv.data_location = os.environ["VEX_DATA_DIR"]

result = eb.build(root / "configs" / f"endstation_{name}.yaml", root / "sw/builder/out")
out = scratch / "exports" / name
if out.exists():
    shutil.rmtree(out)
argv = result["argv"] + ["--entity-gen-dir", str(root / "configs/generated" / f"endstation_{name}"),
                         "--output-dir", str(out), "--no-compile-software"]
sys.argv = ["milan_soc.py", *argv]
time.time = lambda: 1700000000
from migen.fhdl.specials import Instance  # noqa: E402
Instance.__repr__ = lambda self: "Instance(%020d)" % self.duid
soc_path = root / "sw/litex/milan_soc.py"
if phase == "baseline":
    source = subprocess.check_output(["git", "show", f"{DEV}:sw/litex/milan_soc.py"], cwd=root)
else:
    source = soc_path.read_bytes()
exec(compile(source, str(soc_path), "exec"), {"__name__": "__main__", "__file__": str(soc_path)})

files = {}
mismatched = []
for prefix, directory in [("export", out), ("builder", root / "sw/builder/out" / f"endstation_{name}"),
                          ("shape", root / "configs/generated" / f"endstation_{name}")]:
    for p in sorted(directory.rglob("*")):
        if p.is_file() and p.suffix != ".log":
            data = p.read_bytes()
            key = f"{prefix}/{p.relative_to(directory)}"
            files[key] = {"bytes": len(data), "sha256": hashlib.sha256(data).hexdigest()}
            saved = scratch / "snapshots" / phase / name / key
            saved.parent.mkdir(parents=True, exist_ok=True)
            saved.write_bytes(data)
            if phase == "candidate":
                base = scratch / "snapshots" / "baseline" / name / key
                if not base.exists() or base.read_bytes() != data:
                    mismatched.append(key)
assert files and any(k.endswith(".v") for k in files), files
manifest = {"config": name, "argv": argv, "files": files}
(Path(os.environ.get("RECEIPT_DIR", scratch)) / f"{phase}-{name}.json").write_text(
    json.dumps(manifest, indent=2) + "\n")
if phase == "candidate":
    previous = json.loads((Path(os.environ.get("RECEIPT_DIR", scratch)) / f"baseline-{name}.json").read_text())
    missing = sorted(set(previous["files"]) - set(files))
    assert not mismatched and not missing and previous == manifest, (mismatched, missing)
print("EXPORT PASS", phase, name, len(files), "artifacts", flush=True)
